### ISSUE TITLE
Lava no longer working with combustion engines.

### ISSUE THREAD

**Issue by Alec-Rave** [BuildCraft/BuildCraft#1254]
As of 4.1.0 combustion engines will no longer accept lava either through pipes or buckets (or I assume cells). Engines that had lava stored in them before updating retain the lava, but act as though there is no fuel (they don't animate, heat up, or output power).

**Comment by redferret** [comment]
It would be nice to have Lava back again. It's weird that it was removed. My entire factory is no longer working because of it.

**Comment by AEnterprise** [comment]
it has been removed almost 3 years ago so the version you where running must have been ancient. while lava is indeed a heat source it's not something you can actually "burn", there are plenty of alternatives though

**Comment by asiekierka** [comment]
Actually, it was brought back briefly in 2014 - but it doesn't make sense -
you don't heat up lava to burn it...

2016-07-21 21:58 GMT+02:00 AEnterprise <notifications@github.com>:

**Comment by dj3520** [comment]
>you don't heat up lava to burn it

Perhaps the stirling engine then? Same as a lava bucket minus the bucket part.
