### ISSUE TITLE
Blueprint projector

### ISSUE THREAD

**Issue by dmillerw** [BuildCraft/BuildCraft#1646]
As suggested here

http://mod-buildcraft.com/forums/index.php?topic=460.0

Just putting this here for my reference. If no one has objections, I'll take it on as a side project.

**Comment by asiekierka** [comment]
Not interested, far too much work for too little benefit.

**Comment by simon816** [comment]
Aww this was a great idea.
(Future reference: forum URL is now http://mod-buildcraft.com/forums/showthread.php?tid=220)
