### ISSUE TITLE
Add a trigger for plant maturity

### ISSUE THREAD

**Issue by SpaceToad** [BuildCraft/BuildCraft#1751]
As suggested on YouTube.

**Comment by yt-chilm** [comment]
This would be great to have, if possible?

**Comment by hea3ven** [comment]
I've been thinking about this. In stead of doing something specific like this, having a block update trigger. In one hand, it opens a lot more gameplay options, in the other hand, it breaks the immersion.

**Comment by AEnterprise** [comment]
hmm, a block update one wouldn't do the trick for this use cause you need multiple updates before it's fully grown

**Comment by hea3ven** [comment]
Well, yeah, it would be harder than just having a "plant is mature" trigger, but it would be possible.

**Comment by yt-chilm** [comment]
think a block update would do (you could count the ticks per plant with some rs and hoppers?), but it does break the immersion I agree. I was quite liking the biological-summink-or-other idea, but applied to a trigger :)

**Comment by asiekierka** [comment]
@hea3ven - We're not breaking the immersion, not in a thousand suns.

**Comment by AEnterprise** [comment]
planned for 8.0?

**Comment by AlexIIL** [comment]
No. But it feels like it might be helpful to have in a "misc BC pluggables" addon that I could make.
