### ISSUE TITLE
Quarry issues with fences

### ISSUE THREAD

**Issue by SpaceToad** [BuildCraft/BuildCraft#1777]
For some reasons, fences don't get extracted when one on top of the other. That may explain other problems seen with the Quarry. See http://mod-buildcraft.com/forums/index.php?topic=585.0

**Comment by Lord-Mimir** [comment]
The getHeightValue function called in the createColumnVisitList function on line 305 of the TileQuarry.java file, may be the cause for the stacked fence posts and other non Opaque blocks being missed by the quarry.

The getHeightValue(x,z) function returns the block above the first opaque block, this causes it to miss non opaque blocks unless there is a opaque one directly below it. 

So a fence post on dirt will be quarried, but one over air, or more then 1 block above a opaque block will be missed.  This also is the case with glass and any other non opaque blocks.  the Quarry ignores them unless the block directly below it is opaque.

if create a tower of glass blocks over a flat grass field, only the first glass block directly over the grass will be quarried.  If while the quarry is running one replace any of the other glass blocks with dirt, the quarry would get the glass block directly over the new dirt block and the dirt block.

**Comment by OrionDevelopment** [comment]
Yes that might indeed be the issue here.
I had no time since my last comment to try stuff. (University and Work got in the way), If you want you can fix it if you know how.

If you need any information please feel free to contact me.
