### ISSUE TITLE
Seams on Facade edges

### ISSUE THREAD

**Issue by da3dsoul** [BuildCraft/BuildCraft#1900]
I made a post about Facade occlusion and culling on the forums [here](http://mod-buildcraft.com/forums/index.php?topic=726.0). The occlusion is much more involved, so for now I'm leaving it alone and talking about the seams on the edges of faces.

private static final float zFightOffset = 1F / 4096F;

There is a line here that causes the seams, but I was wondering if there is a reason for its existence, because changing it to

private static final float zFightOffset = 0F;

fixes the problem. I know not everyone has the same hw as I do, and there is a possibility that the 1/4096 padding might be there for a reason.

**Comment by da3dsoul** [comment]
It's hilarious looking at the log for this. I get it's an annoying thing to write, consisting of lots of math and effort, so I don't blame you or anyone else.

**Comment by AlexIIL** [comment]
This can either be fixed by using a super-complicated set of multiple passes with a "model bisector", or with a custom offset on a per-side basis. I wonder which is easier... :P

**Comment by asiekierka** [comment]
Wouldn't it be possible to do partial facade edge occlusion, though?

a) marking facades which are opaque vs. ones which are not with a helper function,
b) culling edges between facades which are opaque or have the same block/meta, as well as between opaque facades and blocks with isSideSolid() set right?

**Comment by AEnterprise** [comment]
duplicate, can be closed

**Comment by afdw** [comment]
Fix in 8.0.x.
