### ISSUE TITLE
forge microblocks not supported by Builder (1.7.2, BC 6.16)

### ISSUE THREAD

**Issue by Ngar1** [BuildCraft/BuildCraft#1993]
Forge Multiblocks in 1.7.2 are not supported by buildcraft 6.16 with builder.
Later on I will try it with 6.17 and 1.7.10 - but i still fightingl with updating my server :-)

**Comment by Dijkstra1** [comment]
I plan on making a mod that makes bc pipes and other mod's cables/pipes microblocks compatible, that is with Forge Multipart, when I have finished my wardrobe mod and jaffacake mod, if no one has done it yet.

**Comment by asiekierka** [comment]
@Dijkstra1 - @amadornes has already been working on that and I have made massive improvements to the API to make this possible in the future; perhaps you two could collaborate?
