### ISSUE TITLE
Make BuildCraft splittable again

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildCraft#2045]
Module | Responsibilities | Dependencies | Done
------ | ------ | ------ | -------
Core | Provide core functionality shared between multiple modules, few actual blocks/items (wrench, map location, ...) | - | -
Silicon | Laser tables | Core | Yes
Transport | Pipes of all kinds, Gates, Facades | Core, Silicon for gate recipes | Yes
Robotics | Robots, Redstone Boards, Zone Planners | Core, Silicon, Transport | Yes
Factory | Machines, quarries, refineries, mining wells | Core | Yes
Builders | Builder, filler, blueprints, schematics | Core | Yes
Energy | Engines, fuel, oil deposits | Core | Yes

**Comment by asiekierka** [comment]
And with the 6.5.x branch, I'm almost done!

**Comment by liach** [comment]
How about API?
