### ISSUE TITLE
issue with combustion engine

### ISSUE THREAD

**Issue by ilturko** [BuildCraft/BuildCraft#2062]
Hi all, i have a crash when i try to use this engine. This is the report, please help
the system runs on cauldron 1.7.10 187 207

---- Minecraft Crash Report ----
// There are four lights!

Time: 10/19/14 7:04 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at buildcraft.energy.TileEngineIron.engineUpdate(TileEngineIron.java:203)
    at buildcraft.energy.TileEngine.func_145845_h(TileEngine.java:236)
    at net.minecraft.world.World.func_72939_s(World.java:2492)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
    at java.lang.Thread.run(Thread.java:744)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at buildcraft.energy.TileEngineIron.engineUpdate(TileEngineIron.java:203)
    at buildcraft.energy.TileEngine.func_145845_h(TileEngine.java:236)

-- Block entity being ticked --
Details:
    Name: net.minecraft.src.buildcraft.energy.TileEngineIron // buildcraft.energy.TileEngineIron
    Block type: ID #213 (tile.engineBlock // buildcraft.energy.BlockEngine)
    Block data value: 2 / 0x2 / 0b0010
    Block location: World: (179,4,-486), Chunk: (at 3,0,10 in 11,-31; contains blocks 176,0,-496 to 191,255,-481), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Actual block type: ID #213 (tile.engineBlock // buildcraft.energy.BlockEngine)
    Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2492)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
    Level name: TurcoCraft
    All players: 1 total; [GCEntityPlayerMP['ilturco'/26, l='TurcoCraft', x=181.13, y=4.00, z=-485.18](ilturco at 181.13453772236528,4.0,-485.18126641672575)]
    Chunk stats: ServerChunkCache: 697 Drop: 0
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (1,169,0), Chunk: (at 1,10,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 34699074 game time, 35049203 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 39557 (now: false), thunder time: 67417 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
    at java.lang.Thread.run(Thread.java:744)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.4.36-mc-verygames
    Java Version: 1.7.0_55, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 267839064 bytes (255 MB) / 665161728 bytes (634 MB) up to 2803171328 bytes (2673 MB)
    JVM Flags: 18 total; -Xms256M -Xmx2814M -XX:MaxPermSize=512M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:NewRatio=3 -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=8 -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:MaxGCMinorPauseMillis=7 -XX:+ExplicitGCInvokesConcurrent -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+BindGCTaskThreadsToCPUs -Xnoclassgc
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 31, tallocated: 77
    FML: MCP v9.05 FML v7.10.25.1207 Minecraft Forge 10.13.0.1207 24 mods loaded, 24 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.25.1207} [Forge Mod Loader](cauldron-1.7.10-1.1207.01.187-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.0.1207} [Minecraft Forge](cauldron-1.7.10-1.1207.01.187-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bcmod{2.6.3} [BCMod (Brad16840 Core Mod)](BCMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.2.13} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    backpacks16840{2.6.1} [Backpacks!](Backpacks-Mod-by-Brad16840-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.8.2} [BiblioCraft](BiblioCraft[v1.8.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{6.1.2} [BuildCraft](buildcraft-6.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{6.1.2} [BC Transport](buildcraft-6.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{6.1.2} [BC Silicon](buildcraft-6.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{6.1.2} [BC Builders](buildcraft-6.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{6.1.2} [BC Factory](buildcraft-6.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{6.1.2} [BC Energy](buildcraft-6.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ComputerCraft{1.64} [ComputerCraft](ComputerCraft1.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    customnpcs{1.7.10b} [CustomNpcs](CustomNPCs_1.7.10b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DragonsRadioMod{1.6.2} [Dragon's Radio Mod](DragonsRadioMod-MC1.7.10-1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{2.2.650-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.650-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry{3.1.1.4} [Forestry for Minecraft](forestry_1.7.10-3.1.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GalacticraftCore{3.0.3} [Galacticraft Core](GalacticraftCore-BETA-1.7-3.0.3.201.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GalacticraftMars{3.0.3} [Galacticraft Planets](Galacticraft-Planets-BETA-1.7-3.0.3.201.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{6.0.41.729} [Iron Chest](Iron-Chests-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    cfm{3.3.5} [§6MrCrayfish's Furniture Mod](MrCrayfishs-Furniture-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    harvestcraft{1.7.2d} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry : [Forestry] Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, MCPC+, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 999; [GCEntityPlayerMP['ilturco'/26, l='TurcoCraft', x=181.13, y=4.00, z=-485.18](ilturco at 181.13453772236528,4.0,-485.18126641672575)]
    Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by kowalsky01** [comment]
I'm with the same problem... I don't know what to do anymore... :'(

**Comment by psxlover** [comment]
What version of Buildcraft are you using? Also post your log, it may be different.

**Comment by asiekierka** [comment]
@kowalsky01 - You might want to update from BuildCraft 6.1.5 to 6.4.14.
