### ISSUE TITLE
stripe pipes destroying gates when moving

### ISSUE THREAD

**Issue by AEnterprise** [BuildCraft/BuildCraft#2079]
If you send a pipe through a stripe pipe the stripe pipe will move forward one, placing the pipe behind it but the stripe pipe had a gate on it that gate is destroyed

reported on the forum before but it was a while back, couldn't find the thread for it

**Comment by hea3ven** [comment]
I tested this with the current version and the gates are not being destroyed, they stay in the position they were. The question is, is this the expected behaviour or should the gates move with the striped pipe?

**Comment by asiekierka** [comment]
@hea3ven - The entire stripes pipe "extension" code is up for a major rewrite.
