### ISSUE TITLE
[Reminder] Gate trigger and action dropdown menus

### ISSUE THREAD

**Issue by Vexatos** [BuildCraft/BuildCraft#2096]
This is a reminder for @asiekierka.
Even in BC without any addons, in some cases you can get 30 gate triggers or actions available. A dropdown menu to easily choose between them would be very useful.

**Comment by AlexIIL** [comment]
This has been implemented in a list like format. However there is no easy way to choose between parameters, so perhaps that could also be implemented?

**Comment by AEnterprise** [comment]
is the parameters list still planned?

**Comment by AlexIIL** [comment]
Urm... no. There are generally very few parameters, and I'm not sure where it would go.
