### ISSUE TITLE
Items drop with furnaces

### ISSUE THREAD

**Issue by sfchipan** [BuildCraft/BuildCraft#2161]
https://www.youtube.com/watch?v=spjoA54IQMk

When the furnace is full, sometimes the extra cobblestone can come back into the previous pipe; at other times they pop up.

Forge 10.13.2.1232
Buildcrat 6.1.5
Factorization 0.8.88.5

**Comment by hea3ven** [comment]
The requested behaviour has been implemented as the clay pipes.

**Comment by asiekierka** [comment]
It's actually a bug with a transport pipe not force-updating the tile entity if it was invalidated and then revalidated during the movement of the item, which generally only happened with vanilla furnaces.
