### ISSUE TITLE
Picker will not place items in chest or pipe

### ISSUE THREAD

**Issue by SullyTheUnusual** [BuildCraft/BuildCraft#2200]
I set up a very basic tree farm with a Lumberjack, Planter and Picker.  The Picker will go get saplings and wood, but will not release them when returning to the docking station.  I've tried using the filter, request items and accept items parameters.

**Comment by shadoxxhd** [comment]
i think i know what he means, the pickers are keeping their items sometimes, and deposit them only if their inventory is full

**Comment by hea3ven** [comment]
This could be the same as #2350

**Comment by asiekierka** [comment]
Assuming duplicate since not seen in production.
