### ISSUE TITLE
Kinesis pipes taking all power from each source

### ISSUE THREAD

**Issue by hubertnnn** [BuildCraft/BuildCraft#2265]
An example, lets have a system with one sink accepting 100RF/t and connect a single source. The system will drain that source for 100RF/t and feed it to sink, everything works fine.
If you connect second source, the system will drain 100RF/t from each (for total of 200RF/t) but feed only 100RF/t to the sink, wasting other 100RF/t.
Connecting third source will make a total drain of 300RF/t (waste of 200RF/t) and so on.
The amount of sinks does not affect the bug.

On image the cell is set to accept 100RF/t (and it does) but EnderIO thing is sending 500RF/t.
![2014-12-02_07 43 24](https://cloud.githubusercontent.com/assets/1189576/5258826/f55c59b2-79f6-11e4-9b9c-56aec65b2e3a.png)

**Comment by asiekierka** [comment]
It's actually fixed.

It's actually fixed!
