### ISSUE TITLE
[Enhancement] Add switchable 'loop mode' and 'wait if mobs interrupt' options to filler

### ISSUE THREAD

**Issue by bochen415** [BuildCraft/BuildCraft#2285]
We talked about this on technic forums

Sorry for the pseudoart, it's just faster than writing an essay on filler mechanics.
![filler](https://cloud.githubusercontent.com/assets/8314356/5355986/82826c0e-7f98-11e4-9ac8-5f0b251c99fa.JPG)

Current filler mechanics are:
- loop mode disabled (as opposed to classic BC)
- do not wait on entities to leave work area, skip blocks (as opposed to classic BC)

**Comment by asiekierka** [comment]
Now #2268.
