### ISSUE TITLE
Move API to a separate repository

### ISSUE THREAD

**Issue by CovertJaguar** [BuildCraft/BuildCraft#2286]
This greatly simplified things for anyone using the API and also helps keep things like licensing and histories separate.

Than anyone wishing to depend on it can simple just add the api repo as a submodule.

**Comment by liach** [comment]
How will this be affected by modulizing Buildcraft?

**Comment by asiekierka** [comment]
This is next.

**Comment by Kubuxu** [comment]
Is really separating repositories good idea? Now with gradle separate project can be created in one repository, API only artifacts can be published and so on. The gitsubmodules are messy and unintuitive.

**Comment by asiekierka** [comment]
API artifacts have been published for years. I guess you're right - I also have issues with having more repositories than the three I already do (main, localization + compat), and Gradle works well enough. @CovertJaguar - what do you think?

**Comment by Kubuxu** [comment]
@asiekierka the project (in gradle) can be spitted to API and modules. This would enforce clear chain of dependencies.

**Comment by CovertJaguar** [comment]
Splitting it off is imo the best thing to do. It allows people to quickly look at the history to see if it change and it also makes it easier for other projects to interface with the API.

Additionally, I'm of the personal opinion that projects with different licensing terms should not be under the same repository.

**Comment by AlexIIL** [comment]
Created in https://github.com/BuildCraft/BuildCraftAPI. Let me know if there are any issues with rthe way it has been split up

**Comment by CovertJaguar** [comment]
Looks fine.
