### ISSUE TITLE
Filler causes lag after server restarts

### ISSUE THREAD

**Issue by m31t** [BuildCraft/BuildCraft#2303]
When the server restarts and there is a chunkloaded filler that isn't finished yet, it causes massive lag. The TPS drop to 3-4 (i used 3 fillers , each ~50x50x20, at once) until i remove the filler. Before the server restart there is no lag at all.

**Comment by m31t** [comment]
totally forgot about this. i used the wrong github account. :x Without WAILA i have no issues with normal sized fillers. 

But there is definitly a problem with fillers exceeding the landmarks max_size of 64x64x64 (even without waila). For example if you use markerplus or any other IAreaProvider to mark for example a 256x100x256 area. Even if all chunks are loaded, the tps on the server drop to 10-15 and the server sometimes crashes. But with 16 single 64x100x64 fillers you don't have that problem. 
I don't know if it's possible to avoid this with the way the filler works currently. 
One solution may be to limit the max size of a filler and/or include a advanced filler that doesn't use "throwing blocks" and just fills all air blocks in the area without any exception and doesn't search spots it has placed something before again for a free spot.

**Comment by asiekierka** [comment]
Actually, the lag seems to come from sloppy coding in the blueprint system. What crashes are these? Can you provide a profiler log?

**Comment by m31t** [comment]
No unfortunately not. It's a while ago and currently i dont have time for minecraft because of exams. 
Maybe it has to do something with storing and loading the progress of the filler from/to the world save?

**Comment by asiekierka** [comment]
@m31t - Does it still happen in BC 6.4.0?

**Comment by m31t** [comment]
@asiekierka  cannot reproduce anymore with 6.4.0
