### ISSUE TITLE
Quarry jammed in two lines

### ISSUE THREAD

**Issue by Granik24** [BuildCraft/BuildCraft#2322]
Hi. I have problem with my quarry. Quarry is in Aroma1997 Mining World and +- 4 hour still mining only two lines of invisible blocks. 
I tried to place some block to that invisible line and those blocks quarry can mine.

This happens two times of my 5 quarry's.
Breaking the quarry and then set the same size will not help.

Here si video: http://youtu.be/CLPvHMKqNZU

**Comment by Rokmonkey** [comment]
I am having the same problem.  I am only running Railcraft as my chunkloader. The quarry just runs over the same section over and over.  A filler was used to clear that section of stone, then it started up again only to stop soon after.  I am using Buildcraft 6.2.6

**Comment by Thog92** [comment]
Can you try it with BuildCraft 6.3.1?

**Comment by Rokmonkey** [comment]
Currently, no, the world has parts from mods that are not compatible with BC 6.3.1

We did find that upon removing Tinker's Construct torches from the area, the quarry started mining again.

**Comment by klusekrules** [comment]
I have BC 6.3.1 and I have the same problem. I must restart server to fix quarry for a while.

**Comment by klusekrules** [comment]
I installed on a server BC 6.3.3. I still get this error. It occurs every day. This is a very annoying bug, because I often have to restart the server. If it helps, I can send the map and modifications installed. Could you investigate it?

**Comment by drakke1980** [comment]
i have found that if i mine the blocks it is stuck on myself i dont have to restart the server.

**Comment by psxlover** [comment]
Has any of you set quarry.loads.chunks in the config to false?

**Comment by klusekrules** [comment]
I have set that: B:quarry.loads.chunks=true

**Comment by asiekierka** [comment]
Does this still happen in 7.2.x?

**Comment by AEnterprise** [comment]
no further info indicating this isn't fixed has been given

can be closed

**Comment by Granik24** [comment]
Sorry about my inactivity, it's fixed.
