### ISSUE TITLE
Still having mixed results with stripes pipes and liquids

### ISSUE THREAD

**Issue by Wiley85** [BuildCraft/BuildCraft#2338]
I posted an issue a couple months ago, that was since resolved in 6.2.4, and I have had varied results with it since upgrading.  I will post some screenshots of it working and not working and maybe someone can shed some light on what I'm doing wrong.

![2014-12-24_23 13 31](https://cloud.githubusercontent.com/assets/9661233/5552638/419a9120-8bc4-11e4-8678-f37d05dfe23c.png)
![2014-12-24_23 13 33](https://cloud.githubusercontent.com/assets/9661233/5552639/4702e11c-8bc4-11e4-900a-d2f9f4c11f9a.png)
![2014-12-19_00 57 31](https://cloud.githubusercontent.com/assets/9661233/5552650/84b2dad0-8bc4-11e4-9606-dcbc2f2fc6ca.png)
![2014-12-19_00 57 33](https://cloud.githubusercontent.com/assets/9661233/5552651/a04c8c00-8bc4-11e4-929a-567579eb8cdb.png)

With the water, I only had to replace the stripes pipe a couple of times before it started to work, and since has been very consistent.  The lava, however, I've replaced several times, restarted minecraft several times, and nothing seems to work.  I had the same setup several chunks away and it worked just fine.  Now the are both in the same chunk and the stripes pipe refuses to pick up the lava.  Thank you for your consideration.

**Comment by asiekierka** [comment]
Please retry in 6.4.0, @Wiley85

**Comment by asiekierka** [comment]
Fixed.
