### ISSUE TITLE
BC Dupe

### ISSUE THREAD

**Issue by TheseAreMyDepths** [BuildCraft/BuildCraft#2339]
Duplication of just about **anything** is capable through the use of an Architect Table and Builder.

This is done by placing a storage-block of any type or mod within the designated border of an Architect Table, right-clicking said storage (after filling it with the desired resource / item) with Mekanisms "Cardboard Box" and creating a Blueprint.

After doing this, take it to the Builder and it'll only ask for **just** the Cardboard box, but as soon as it's thrown into the world, you can undo the Cardboard Box and effectively dupe the storage-block as well as its contents.

Hope this helped. Cheers.

**Comment by asiekierka** [comment]
I can't believe it took us this long.

**Comment by SandGrainOne** [comment]
Please try to link in what commit that fixes an issue. You can even have issues closed automatically by having a code in the commit text.

https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by asiekierka** [comment]
@SandGrainOne I have. It just appears I forgot to push.
