### ISSUE TITLE
Dangerous Lasers

### ISSUE THREAD

**Issue by ruifung** [BuildCraft/BuildCraft#2342]
Is it possible to make the lasers deal fire damage to anyone who walks through them while active? With the amount of damage scaling with the efficiency color. 
For some reason it always irks me when I see people walking through the lasers while they are active =P.

**Comment by Syer10** [comment]
I would prefer if it was a new set of lasers that did this. or if they had a setting to. maybe they could be a better laser then the current one with the drawback of hurting people.

**Comment by asiekierka** [comment]
Not as good an idea to care about. Might be reopened in the far future.
