### ISSUE TITLE
Lists Still not working correctly?

### ISSUE THREAD

**Issue by PyroTornado** [BuildCraft/BuildCraft#2343]
Am I doing something wrong when making a list? Sometimes lists work just fine, but other times they don't work at all. Is it possible that the lists lock into place once you close the interface the first time? Because while setting up a sorting system for my more abundant supplies, I could only get a few items to go into the right subsystem of sorters, so I did a little moving items around in the lists and now nothing goes into the subsystems.
Maybe for the interface methods, you need to make sure it updates both the old contents and the new contents of the list, so it isn't trying to access data no longer there.

EDIT: I think I figured out my issue. I seems to only register the first item in each row as an item on the list. You can place ghosts of other items in the other slots, but they don't do anything. The other slots are just there to use the equivalence and approximate buttons. So even if you can place a bunch of items into each list, it will only read six custom items each. Am I correct?

**Comment by asiekierka** [comment]
@PyroTornado - could not reproduce, issuer did not follow on.
