### ISSUE TITLE
mining wells trying to break water taking forever ??

### ISSUE THREAD

**Issue by kurokuno** [BuildCraft/BuildCraft#2347]
ok so when a mining well is over water to get down one block fully powered it can take 3-5 seconds allmost like its mining obsidian if not worse i am guessing this is a bug or ? if otherwise just let me know =D

**Comment by dominikh** [comment]
Yes, 6.2.6. https://www.youtube.com/watch?v=KxDsV7tWLoE demonstrates the issue (video not by me, but by someone else with the same problem.)

**Comment by asiekierka** [comment]
I THINK I fixed that in 6.3.0. Not sure. Could you check @Kurokuno ?

**Comment by dominikh** [comment]
6.3.0 fixes the issue for me.

**Comment by asiekierka** [comment]
Oh, it does!
