### ISSUE TITLE
Picker robot won't drop items in pipe

### ISSUE THREAD

**Issue by narrowtux** [BuildCraft/BuildCraft#2350]
I run BuildCraft version 6.2.2 and built a picker robot. It collects drops in the designated area just fine, but when I set the gate to "Drop Items in Pipe" it doesn't do it.

Here's a screenshot of the gate configuration:
![2014-12-30_12 31 09](https://cloud.githubusercontent.com/assets/616791/5578067/c2045abc-901f-11e4-997e-226f8a0b6c72.png)

And a screenshot of the docking station with the robot, as you can see it has some items in its inventory but it won't drop them.
![2014-12-30_12 31 34](https://cloud.githubusercontent.com/assets/616791/5578072/cf36196e-901f-11e4-8bc0-d5323d7fc25f.png)

**Comment by ruifung** [comment]
Actually It does work for the home station of the robot. BUT. For some reason, the order in which you specify the actions (dock, drop items in pipe, etc) matter. I can't remember the exact order right now, but I believe that drop items in pipe should be before the dock action - or in this case the work in area action.

**Comment by hea3ven** [comment]
Thank's for the info ruifung, it made finding this bug really easy.
