### ISSUE TITLE
Combustion engines crash when oil is put in them

### ISSUE THREAD

**Issue by Sunconure11** [BuildCraft/BuildCraft#2352]
I attempted to put oil in a combustion engine, sometime after I decided upon a good set of tech mods, for a custom mod pack, and discovered this crash:

pastebin.com/Gru7qmHL

**Comment by Chocohead** [comment]
Pretty sure https://github.com/ForestryMC/ForestryMC/commit/a9fbfbbe7453d12787ba7c32ccb093e13e3540f1 has fixed this

**Comment by mezz** [comment]
This was a Forestry bug, yes
