### ISSUE TITLE
Liquid dupe bug with BlockTank

### ISSUE THREAD

**Issue by mezz** [BuildCraft/BuildCraft#2353]
When your inventory is full and you put a fluid into a tank using a container registered with the FluidContainerRegistry, the tank will accept the liquid and then return "false" from `onBlockActivated`. 

For forestry cans and capsules, this means the capsule is not consumed.
For ic2 cells, this means the cell dumps its contents on the ground.
Either way, duplicated liquid is added to the tank.

I think the best solution is to throw the empty container on the ground and return true.

Relevant Code: https://github.com/BuildCraft/BuildCraft/blob/91a5d428219d3719f9519f2336759419af93f955/common/buildcraft/factory/BlockTank.java#L116

Found while investigating: https://github.com/ForestryMC/ForestryMC/issues/425

**Comment by asiekierka** [comment]
It should not be adding the liquid at all. Will investigate.

**Comment by mezz** [comment]
If you don't accept the liquid, the ic2 cells will act like the tank is full and dump their water on the ground (super annoying). 
I think it would be more user-friendly to accept the liquid and drop the empty can on the ground.

**Comment by asiekierka** [comment]
IC2 will do what!?

**Comment by mezz** [comment]
If you see the player's inventory is full and say "sorry I can't accept liquid."
IC2 cell says "hey this thing can't accept liquid, I'll happily dump my contents here because I'm basically a bucket"
Now I'm dying in a pool of `hot liquid here`

**Comment by asiekierka** [comment]
@mezz I know, I know. It's just... Eh. I'll fix it now.
