### ISSUE TITLE
Combustion Engines should be able to use IC2 Coolant

### ISSUE THREAD

**Issue by Speiger** [BuildCraft/BuildCraft#2354]
Buildcraft combustion Engines have only two ways to cool it...
First water... That will be consumed pretty quick and BC Pipes are mostly not able to keep up (thats a reason why people yell we need bigger pipes),
The Second and Painfull way is Liquid ICE. If you got to the point where you got easy access to the materials it is a extremly powerfull coolant. It is a couple 1000 times better then water.
So now here is liquid Coolant. You need Lapis lazuli to create it and it is not that easy to get access to and it takes a little bit of time.
I added it already in my 1.6.4 version and suggest that it is keeping up the half time of liquid ICE (Number of Water = 0,0023. Liquid ICE = 10) I would say 4-5 would be perfect for LiquidCoolant.
And The TE3 Liquid Cryophium or something i would give him the same number as liquid ice because its the same thing just another name...

**Comment by AEnterprise** [comment]
this is an IC2 thing to fix, there is a coolantRegistry in the BC api, other mods (or something like BC compat) should register the coolants there

**Comment by Speiger** [comment]
@Raga combustion engines use min 1mb water every tick.
And my engines do not blow up because i use liquid ice as coolant or biomass engines from foresty.
Note Liquid Ice is needed maybe 1 mb per minute or something. Maybe even more.

And because i am now the coder of IC2 Classic i will make a compatiblity xD.
1.6 for the win!

**Comment by Speiger** [comment]
@raga and ICEBlocks count as water! And to create ICE blocks it takes also a lot of time!
If you do not use IC2 Compressors with snowballs and 20 overclocker upgrades.
Also it reduces the amount of lag because you have to run less machines :)

**Comment by RagaRBM** [comment]
my Engines do not blow up because I use water.

**Comment by asiekierka** [comment]
Moved.
