### ISSUE TITLE
crash in buildcraft 6.3

### ISSUE THREAD

**Issue by Sailren** [BuildCraft/BuildCraft#2358]
http://paste.ubuntu.com/9682545/

btw, would be nice if some1 unbans my account M.Marsha@web.de / Sailren on bc forum cuz im not a bot, bots cant report crashlogs, which u get when running minecraft, at least this is what i think

ask speiger, he often talks with me on ftb teamspeak

**Comment by AEnterprise** [comment]
@Sailren for the forum i'm the one responsible for the ban, you had speiger contact me for that but i guess he didn't relay my message to you yet: i can't find your account nor is your email or username blocked so your ip is blocked this means your IP was used to post spam on the forums so i sugest you do a complete virus and malware check of your pc. as for unbanning you could you contact me by email (aenterprise2 'at' gmail 'dot' com) and include your ip adress? i can't just dissable the rule

i also want to apologize for removing your account but it must have been 'hidden' by the spam bots

**Comment by Sailren** [comment]
thx for quick reply aenterprise, yeah, lemme look up the ip, i guess u want the ip the router has right?

**Comment by AEnterprise** [comment]
yes i need the your external ip, also please send any more questions for this to my email in the message above so we can use this issue to fix your crash, otherwise it might get confusing

**Comment by Sailren** [comment]
emails are sent :)

**Comment by Sailren** [comment]
does anybody also have this shematic crash?

**Comment by asiekierka** [comment]
One of your mods might be distributing an outdated BC API. Can you reproduce with just BC, BCCompat and FMP?

**Comment by grydian** [comment]
I am also getting this crash after updating to latest FMP and BC.

**Comment by Sailren** [comment]
yes, this also happens with just BC, BCCompat and FMP

**Comment by asiekierka** [comment]
@Sailren, @grydian, @MattaBase - try http://asie.pl/bcc-test1.jar

**Comment by Sailren** [comment]
this works, how stable im not sure

**Comment by asiekierka** [comment]
Excellent.
