### ISSUE TITLE
Weird pipe effects when anisotropic filtering is on

### ISSUE THREAD

**Issue by LouisHutch** [BuildCraft/BuildCraft#2363]
Mods: BC 6.3, BCA 1.8.4, Fastcraft NEI, WAILA

When you turn anostroptic filtering on, the contents of the pipes become weird:
Fuel looks like fire,
Oil looks like fuel,
Water turns brown,
Energy becomes a weird yellow lines with green squares

**Comment by LouisHutch** [comment]
![2015-01-06_21 08 01](https://cloud.githubusercontent.com/assets/9326429/5636240/3cb23a2c-95e8-11e4-8897-282039125462.png)
![2015-01-06_21 07 47](https://cloud.githubusercontent.com/assets/9326429/5636241/3cb5d920-95e8-11e4-8e5b-993dbbc5a22e.png)
![2015-01-06_21 07 54](https://cloud.githubusercontent.com/assets/9326429/5636242/3cb9722e-95e8-11e4-8ac7-76e43c109631.png)

**Comment by psxlover** [comment]
Are you using optifine?

**Comment by LouisHutch** [comment]
Nope, just the mods shown :)

**Comment by asiekierka** [comment]
@ganymedes01 - Could you take a look at this?

**Comment by ganymedes01** [comment]
That's bizarre lol
But yeah I'll see what I can do

**Comment by Kubuxu** [comment]
It is problem when you turn filtering on or off after load. It probably causes some shifts in atlases and de-synchronizes IIcons.
I have no idea why it is happening (it does no happen always) and it affects probably not only BC.

**Comment by ganymedes01** [comment]
I can't reproduce it
Loaded a world with it off, turned it on, and the icons still look normal.

**Comment by asiekierka** [comment]
Fixed this, forgot to close.
