### ISSUE TITLE
Relicense BuildCraft (the whole thing) to LGPLv3

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildCraft#2364]
This is very important for a few reasons: much clearer legal standing and not being bound to Minecraft (see the "legal copy of MC" clause) which is important for futureproofing and for a game-agnostic voxel engine API I am working on, which I'd like to adapt BuildCraft too so we can stay innovative I guess?

The API will stay on MIT, and for resources I am thinking of something akin to CC BY-SA (but we need to remove all Mojang-derived textures FIRST.)

Since getting all the necessary agreements is a task for months, I will start small by calling the core BuildCraft contributors: @CovertJaguar @SirSengir @Krapht @SpaceToad @cpw, and we shall go from there as I clean up the codebase and figure out a real list of current contributors.

PERMISSIONS NEEDED:
@CovertJaguar 
@SirSengir 
@Krapht 
@SpaceToad 
@cpw 

PERMISSIONS ACQUIRED:
@asiekierka
@AEnterprise 
@adudney 
@smbarbour 
@Vexatos 
@Kubuxu

**Comment by xbony2** [comment]
Woot

**Comment by Ianaver** [comment]
:D sounds good!

**Comment by AEnterprise** [comment]
this sounds like a very good idea, i duno if i have any contributions left in the BC codebase (did a few things here and there but most where just sugestions ST or someone else then aplied) but you have my permission for the changing the license in case you need it

**Comment by adudney** [comment]
I contributed some stuff related to Fillers back in 1.7.2. I'm not sure it still exists in the current codebase, but whatever :P

I hereby give you ( @asiekierka ) permission to relicense any and all contributions I have made to the code or assets.

**Comment by asiekierka** [comment]
@50Wliu - note that the list of contributors includes contributors to past code, and if their code has been removed or replaced, they no longer have rights to the current release, and I'm not planning to backdate the license change (this is for BuildCraft 7.0.0+).

**Comment by smbarbour** [comment]
For any of the tiny contributions I have made, I give permission for the relicense.

**Comment by SoniEx2** [comment]
ugh, did I delete my logs or what... meh, can't find the logs where @SpaceToad gave me permission to relicense BC code :/ I guess you'll have to wait...

**Comment by Vexatos** [comment]
You have my permission as well in case it matters.

**Comment by Kubuxu** [comment]
You have my permission if something is left there.

**Comment by warlordjones** [comment]
In the event my PR is merged, you have my permission also.

**Comment by asiekierka** [comment]
Deferred - after a discussion with CovertJaguar we have deemed LGPLv3 as not necessarily the best option. (Also, the whole idea of porting BC to NOVA had been deferred earlier.)
