### ISSUE TITLE
Error when entering a new world with the latest Buildcraft and rotorycraft installed

### ISSUE THREAD

**Issue by Ianaver** [BuildCraft/BuildCraft#2365]
I switched versions of buildcraft from the latest stable (6.2.6) to beta (6.3.0) and found that it spits an error when I enter any world (new or existing) with rotorycraft installed. this was not an issue at the stable builds :(

**Comment by 50Wliu** [comment]
What's the error?  It would be great if you could give us the whole Minecraft Forge log.

**Comment by asiekierka** [comment]
RotaryCraft, or more specifically, DragonAPI, needs to update first.

**Comment by Ianaver** [comment]
@RagaRBM no, I am using the latest build

**Comment by RagaRBM** [comment]
@lanaver @Ianaver Then the solution is to wait for RotaryCraft or DragonAPI to give a new update. You could post a bug report to Reika to remind him.
