### ISSUE TITLE
Startup Crash: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Anarcraft** [BuildCraft/BuildCraft#2366]
I've heavily customized my Direwolf20 pack and it's been working great using the FTB Launcher.  When I copy over the pack folder to MultiMC I get the following crash at startup.  I also saw this same error on the latest ModSauce.

http://pastebin.com/VEDpNFKa

Buildcraft 6.2.6, Mac OS 10.9.5, Java 7u67.

**Comment by asiekierka** [comment]
Oh, wow, a real bug! (Sadly, for DW20 it will take a while to update as we're on 6.3.x now)

**Comment by Anarcraft** [comment]
Confirmed fixed, thanks!
