### ISSUE TITLE
Crashing with 6.3.0

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [BuildCraft/BuildCraft#2367]
https://paste.ee/p/6sO1a#9SIzg7PkfdJOXFxCDTMznn8iQTZuCFRa

No idea what's going on...

**Comment by Kubuxu** [comment]
You are using BC 6.3 but EnhancedPortals is still built for 6.0-6.1.

**Comment by asiekierka** [comment]
Exactly that.

**Comment by Unrepentant-Atheist** [comment]
Noes :(. Any alternatives to EP?

**Comment by asiekierka** [comment]
@Unrepentant-Atheist StarGateTech2, Greg's SGCraft, LanteaCraft...
