### ISSUE TITLE
Can't place items such as torches onto facades

### ISSUE THREAD

**Issue by LouisHutch** [BuildCraft/BuildCraft#2368]
BC 6.3.0, BCA 1.8.4, NEI, WAILA, Fastcraft

When you try to place an item such as redstone, redstone repeater and torches onto a facade the item will either when placed on a horizontal facade or will get placed on the nearest valid side when you try to place it on a vertical facade.

**Comment by RagaRBM** [comment]
Yeah, this is true. When right clicking the facade with torches, it does show that they can hold it but the torch gets back to your inventory right away.
But this isn't true with Signs as I can place signs on facades with no problem.

**Comment by asiekierka** [comment]
Got it!
