### ISSUE TITLE
Buildcraft API crash with galacticraft NoSuchMethodError: buildcraft.api.core

### ISSUE THREAD

**Issue by mrdeadlocked** [BuildCraft/BuildCraft#2371]
https://github.com/micdoodle8/Galacticraft/issues/1368

I had a issue opened with GC they said its a API issue. If you need the pastebins posted directly in here I can do that. This just seemed easier.

**Comment by asiekierka** [comment]
GC_YesTheirFaultException

**Comment by mrdeadlocked** [comment]
So they say its yours, you say its theirs. :-(

**Comment by laz2727** [comment]
Who do you think would have older BC API, BC or GC?

**Comment by asiekierka** [comment]
@mrdeadlocked: The fact BuildCraft is deprecating MJ has been known since September. It has been carried out fully in mid-November. Mods have had 2.5 months to prepare for that and if some still try to support MJ it's their fault.
