### ISSUE TITLE
Make players explode by being set on fire after swimming in fuel

### ISSUE THREAD

**Issue by magik6k** [BuildCraft/BuildCraft#2375]
That'd be a mostly fun addition. Should be doable by adding custom efect and listening for some kind of event indicating that player is set on fire

**Comment by psxlover** [comment]
Why would they explode ? :S

**Comment by Techokami** [comment]
Might work as a potion effect. "Flammable", which makes you take double damage from fire at double rate. Because being soaked in gasoline doesn't make you explode, it just makes you burn very hot very fast.

**Comment by Kubuxu** [comment]
I would say it make you "explode" as you would have been surrounded by fuel fumes which are highly flammable and with good fumes to air ratio, explosive.

**Comment by RagaRBM** [comment]
I have a bad feeling about this. 
I am a player and this is trouble. :P

**Comment by Kubuxu** [comment]
Noo. This will be FUN.

**Comment by AEnterprise** [comment]
it should at least have a config option for those that don't find it fun to be lit on fire or explode

**Comment by asiekierka** [comment]
@AEnterprise - but BuildCraft was all about explosions!

...Then the GregTech nation attacked.

**Comment by AEnterprise** [comment]
@asiekierka right now you make me wana hit a like button on that reply :p :+1:

**Comment by Kubuxu** [comment]
Working on it now.

**Comment by psxlover** [comment]
I can understand tanks exploding, but players makes no sense. More damage from fire perhaps, explosion no

**Comment by Kubuxu** [comment]
@psxlover with current code explosion is rare and destroys maximum one dirt block and leaves few fire blocks.

**Comment by RagaRBM** [comment]
I want to know how many people actually will find this fun. And how many who will not.

**Comment by Kubuxu** [comment]
@RagaRBM This is not Explosion. In my current version you get amplified damage from fire and form time to time you "smashed into your back". Explosion is able to destroy only one dirt block.

**Comment by SandGrainOne** [comment]
@RagaRBM Do you often bade in Fuel or put yourself on Fire? In this case you must do both at the same time. (Or at least shortly after.) I don't think most players will even notice. Kind of useless change if you ask me.

**Comment by asiekierka** [comment]
@SandGrainOne - Sometimes, easter eggs make a mod experience a whole lot more enjoyable.

**Comment by Mengmoshu** [comment]
As a player I don't think I'd have much problem with this, at least the version where nothing happens without fire. Thermal Expansion and MineFactory Reloaded fluids have various side effects and I never found them unreasonable. If the code is already written then I think it should stay in.

**Comment by RagaRBM** [comment]
*sigh* Oh well ... :P

**Comment by kane-thornwyrd** [comment]
I seccond this demand… That would be FUN ! (with a toclafane voice)

**Comment by immibis** [comment]
Seems like most players wouldn't ever experience the feature, but the ones who do would definitely not find it fun.

**Comment by Kubuxu** [comment]
@immibis did you ever experienced oil/fuel field fire? It might be not super fun but makes game more complete.

**Comment by immibis** [comment]
@Kubuxu those are also annoying, and do not add to the gameplay in any way whatsoever.

**Comment by AEnterprise** [comment]
won't realy add much no, and most users don't read the changelogs (or not the entire thing) so they probably won't know about this feature, making it much more annoying for them

**Comment by asiekierka** [comment]
Decided against.
