### ISSUE TITLE
Robots and mfr safari nets

### ISSUE THREAD

**Issue by babassoonist** [BuildCraft/BuildCraft#2379]
hey I don't know if this is on your side or skyboy's but when you pick up a robot in a mfr safari net it captures the entity and drops the item duping the robot

**Comment by Kubuxu** [comment]
@asiekierka if it is doable by IMC should it go to Main or into Compact?

**Comment by asiekierka** [comment]
@Kubuxu Compat. AE2 and TE4 Sawmill support will also go in Compat.

**Comment by loordgek** [comment]
put the robot blacklist for the mfr net in bc it self not in compat
or make a pr to mfr
