### ISSUE TITLE
Crafting recipe conflict between Stripes pipes and Switch transport pipes from Additional Buildcraft object

### ISSUE THREAD

**Issue by leSamo** [BuildCraft/BuildCraft#2380]
Both of them has the same recipe: 2 gold gears and a piece of glass.

**Comment by laz2727** [comment]
ABO bug, obviously.

2015-01-12 21:00 GMT+06:00 le Samo <notifications@github.com>:

**Comment by asiekierka** [comment]
Yes, ABO bug. We're not responsible if addon mods use the same recipes we do. Ask them to change it.
