### ISSUE TITLE
Need a OptOut config option for Robots

### ISSUE THREAD

**Issue by Reddawg99** [BuildCraft/BuildCraft#2381]
Wether this is an optout for each robot type, or one whole config option, we need this for servers. This would allow us to disable something that, from my own testing, can cause major lag issues. Not to mention some of the robots can bypass protected claim areas.

Reddawg99
SysAdmin
PlanetBeast

**Comment by asiekierka** [comment]
What thing? Which robots?

**Comment by AEnterprise** [comment]
i think he's asking to add a config option for each robot individually to dissable that robot

**Comment by Reddawg99** [comment]
Or all of them would also be fine.
