### ISSUE TITLE
Server crash on world load BC 6.3.1

### ISSUE THREAD

**Issue by justin2108** [BuildCraft/BuildCraft#2382]
Hi just installed the latest version of build craft and my server crashes
BC 6.3.1

reverted back to BC 6.2.1 and works fine

Here is a crash report
http://pastebin.com/raw.php?i=q0LSEsq2

Client works fine on BC 6.3.1

**Comment by liach** [comment]
Other mods used old BC API?

**Comment by justin2108** [comment]
I thought about that to.
But when i run a client and start a new world. Why isn't crashing ?

The only mod i can think off using the build craft API is forestry.
Has issues with that in the past. But the latest version supports API of BC 6.2.1

I think it's in the Enhanced Portals ?

**Comment by justin2108** [comment]
Solved the problem with the latest version off Enhanced Portals 3 3.0.10 & disabling Electrical Age ( to bad liked that mod )

**Comment by asiekierka** [comment]
@justin2108 I had the Electrical Age dev is releasing a fix today
