### ISSUE TITLE
StackOverflow on ChunkLoaders

### ISSUE THREAD

**Issue by CandiceJoy** [BuildCraft/BuildCraft#2383]
We have several chunkloaders that operator continuously and we seem to continually get this problem since updating to 1.3.4.17. http://pastebin.com/2M87qWwD

From ChickenBones: "Please report also to BC, see what they have to say about it"

ChickenChunks Issue: https://github.com/Chicken-Bones/ChickenChunks/issues/20

**Comment by Thog92** [comment]
Same as #2326 and that seem to be fixed in BuildCraft 6.3.

**Comment by asiekierka** [comment]
Why yes, yes it is.
