### ISSUE TITLE
Error with facades

### ISSUE THREAD

**Issue by ReneMuetti** [BuildCraft/BuildCraft#2384]
hello
I have upgraded my server from version 6.2.5 to version 6.3.1 Stable, BuildCraftCompat 6.3.1 Stable. Now it is on the one hand so that all facades "disappeared". This Währe first not so bad, if not Wühre the fact the facades now interrupt all tubes. It is no longer (as before) possible to lay pipes in walls. There are always ugly holes and gaps. Also (and especially) to connect to machines, equipment and boxes is interrupted.
Is this a bug or have wanted?

**Comment by RagaRBM** [comment]
Wait ... you mean there's something that makes you not able to place pipes whatsoever? 
My facades did disappear too, but I still can place pipes. 
Could you perhaps post some pictures too so we can better identify?

**Comment by AEnterprise** [comment]
i think he means that facedes block pipes from connecting and thus he can't run them in the walls

@ReneMuetti there are now holow facades that don't block pipe connections, you can craft regular facades intro holow ones

**Comment by ReneMuetti** [comment]
ok ...
![2015-01-14_19 28 59](https://cloud.githubusercontent.com/assets/3787937/5744744/af5c7970-9c23-11e4-9c1d-c2cb535443bd.png)
![2015-01-14_19 29 09](https://cloud.githubusercontent.com/assets/3787937/5744747/b544fdda-9c23-11e4-9d76-090553fee965.png)

**Comment by asiekierka** [comment]
Craft hollow facades. You can stick a facade into an assembly table to get a hollow facade. This was a side-effect of a change in BuildCraft 6.3.

**Comment by RagaRBM** [comment]
Thing is, hollow facades are not present in creative tab so I'm not really surprised if some are confused.

**Comment by ReneMuetti** [comment]
I use on the server with us the Craft Guide. There is not any reference. The amount of possibilities and options (also in BuildCraft) considerably. It is slow really impossible to know everything and know. A complete recipe book and / or a full wiki are helpful for all.
From this façade type I knew nothing about. There is also no indication at any point on it.
I'll look even know if I am stuck here with success.

But a little more user-guide I would like already - just by "you big"

**Comment by RagaRBM** [comment]
@ReneMuetti Your indication is in 6.3.0's changelogs that you can see in BuildCraft website. The wiki is in the process of updating but in case you're wondering which is the real wiki, it's here : http://mod-buildcraft.com/wiki/doku.php
