### ISSUE TITLE
Filler causes hard crash

### ISSUE THREAD

**Issue by nefarious411** [BuildCraft/BuildCraft#2387]
Had a filler and was cycling through the patterns and minecraft had a hard crash.  Loading the world causes minecraft to exit completely.  

Direwolf20 1.7.10 pack version 1.0.3

crashlog:

https://gist.github.com/nefarious411/9106f23781eba3a6610a

**Comment by kane-thornwyrd** [comment]
Consider using https://gist.github.com/ to show us your logs, please :)

**Comment by nefarious411** [comment]
My apologies.  Updated ticket with gist to clean it up

**Comment by kane-thornwyrd** [comment]
Thank you :+1:

**Comment by asiekierka** [comment]
Fixed in BC 6.3.0+
