### ISSUE TITLE
Facades added through IMC only allow crafting of metadata 0 in multiplayer

### ISSUE THREAD

**Issue by Choonster** [BuildCraft/BuildCraft#2389]
BC version: 6.3.1
Chisel version: [2.2.1](http://minecraft.curseforge.com/mc-mods/225236-chisel-2/files)
Chisel Facades version: [2.7-cricket](http://minecraft.curseforge.com/mc-mods/222784-chisel-facades/files) ([GitHub](https://github.com/Choonster/ChiselFacades/tree/1.7.10-2.7-cricket))

In my ChiselFacades mod, I add Chisel's blocks as Facades using the `add-facade blockName@metadata` [IMC](https://github.com/Choonster/ChiselFacades/blob/1.7.10-2.7-cricket/src/main/java/com/choonster/chiselfacades/FacadeCreator.java).

With BC 6.3.0 and 6.3.1, the Facades are visible in the creative menu and NEI as well as the Assembly Table; but only metadata 0 version of each block's Facade can be crafted in the Assembly Table when in multiplayer (dedicated server). The other variations of each block will show in the Assembly Table output slots, but nothing will happen when their slot is clicked.

This issue doesn't occur in single player (integrated server).

This is similar to my previous issue #2234, except the uncraftable Facades are showing in the Assembly Table and only metadata 0 Facades can be crafted (previously it was the first metadata registered, either 0 or 1 depending on the block).

**Comment by asiekierka** [comment]
You might want to try the add-facade ItemStack IMC. For some reason, I don't really trust the String one.

**Comment by asiekierka** [comment]
Fixed
