### ISSUE TITLE
BC RF tools

### ISSUE THREAD

**Issue by medsal15** [BuildCraft/BuildCraft#2392]
BC has a Charging Table used for... Nothing if you're only using BC!! This is why I suggest RF tools!
1) 5 Tiers: Wooden < (worse than) Stone < Iron < Gold < Diamond.
2) Chipsets are used for modifying. Redstone: +5% for max energy stored. Iron: +10% for max energy stored. Gold: +5% speed gain. Diamond: +1 mining level (diamond will be able to mine Cobalt and Ardite from TiC). Pulsating: Items come to you. Quartz: +7,5% for max energy stored. Comp: +45% (instead of 42,5%) for max energy stored.
3) Tools: Wrench, pickaxe, axe, hoe, sword, shovel, laser, bow (cheaper than laser), and armor. This means wrenches have now durability.
4) Crafting: No (Automatic) Crafting Table... The Advanced Crafting Table is the only way to craft one of those tools.

Tell me what do you think about it!

**Comment by Mrkol** [comment]
1. Electric tools don't make sense in the first place. Are they transforming their energy into matter to fix the physical damage they take, or what?
2. Such suggestions have already been made more than 9000 times, search the closed issue list before creating a new one.
3. Buildcraft is not about tools, weapons, loot, etc. It's about automation and industrialization.
4. There's one RF-tools mod out there already, and there's plenty of other energy-based tool mods. If you want «magical» tools, just use one of those.

**Comment by RagaRBM** [comment]
BuildCraft Additions' Kinetic Multi-Tool.

**Comment by asiekierka** [comment]
Refused. Use an addon.
