### ISSUE TITLE
Wen updating from 6.2.6 to 6.3.1 World wont load

### ISSUE THREAD

**Issue by drago87** [BuildCraft/BuildCraft#2393]
After i updated from buildcraft 6.2.6 to 6.3.1 my world wont load (new or old). The game starts but when i try to load a world or make a new one (SP) i get sent to the MP window.

So i dont have a error log to submit but i can zip/rar my mods and settings and put them on dropbox if that would help.
Using forge 10.13.2.1277

**Comment by leSamo** [comment]
What mods are you using?

**Comment by liach** [comment]
Shutting down internal server? Is it that window?

**Comment by drago87** [comment]
i'm using about 220 mods so listing all off them is abit mutch. But i'm mostly using magic mods with there addons (Thaumcraft, withcery, blood magic Ars Magica 2) then i'm also using most of reika's mods (cromaticraft, rotarycraft). Here is a link to a rar with all mods https://www.dropbox.com/s/tobe7hxwivsxjds/mods.rar?dl=0

**Comment by leSamo** [comment]
You can go to your modpack directory and get crash log there.
Probably - Roaming/nameOfYourModpack/logs/ and find log with the right date and time

**Comment by drago87** [comment]
http://pastebin.com/T4z2NSrr
this is the log file inside the .gz file in the logs folder.
if you want i can also give you the
fml-client-1.log
fml-client-2.log
fml-client-3.log
fml-client-latest.log
fml-junk-earlystartup.log
latest.log

**Comment by leSamo** [comment]
Are you using optifine?

**Comment by drago87** [comment]
no i'm using fastcraft 1.16

**Comment by leSamo** [comment]
no this is renderring issue... it's about missing textures... maybe texturepack or corrupted mod file

**Comment by drago87** [comment]
well i dont use a texturepack and its only when i change to buildcraft 6.3.1 it happens
