### ISSUE TITLE
Flood Gate and FMP parts

### ISSUE THREAD

**Issue by TheJulianJES** [BuildCraft/BuildCraft#2395]
A flood gate kills FMP parts, just removes it.
Buildcraft 6.3.1
Minecraft 1.7.10
Forge 10.13.2.1277

**Comment by asiekierka** [comment]
@TheJulianJES - Is it still happening with 6.4.0? It probably is...

**Comment by hea3ven** [comment]
yes, I looked a little bit into it, and it seems that FMP is not notifying of updates when placing a block, see https://github.com/Chicken-Bones/ForgeMultipart/blob/master/src/codechicken/multipart/MultipartGenerator.scala#L93 , so the buildcraft worldproperties cache does not get updated making the flood gate not know that there is a FMP block there. I meant to open an issue on fmp to ask why it is this way, but I forgot.

**Comment by asiekierka** [comment]
Calling @Chicken-Bones

**Comment by asiekierka** [comment]
Bug in FMP, either way.

**Comment by Chicken-Bones** [comment]
Read through the BC code a bit, in vanilla, the markBlockForUpdate is only used to resend the block-id/meta/tile, since FMP didn't need any of those when placing a part, I didn't call it, I suppose I can add it for compatiblity, a few extra block changes being sent won't hurt anything

**Comment by Chicken-Bones** [comment]
Fixed https://github.com/Chicken-Bones/ForgeMultipart/commit/ce6d36a9a8fc9c62892e51744666c1346fcac153

**Comment by TheJulianJES** [comment]
Thank's @Chicken-Bones!
