### ISSUE TITLE
One side of pipe entity is slightly blue with GLSL shader

### ISSUE THREAD

**Issue by Gibbycraft** [BuildCraft/BuildCraft#2398]
With Shaders Mod v2.3.28 Forge Edition, SEUS 10.1, Optifine Ultra B4, and Buildcraft 6.3.1, the south face of the block (I believe this was south, included Rei minimap in screenshots for reference) a pipe entity resides in turns light blue. With Normap Mapping turned off, this color becomes opaque black. Buildcraft 6.0.16 for Minecraft 1.7.2 (with relevant versions of Optifine, Shaders Mod, and SEUS 10.1) worked fine with this setup. 

Disabling Optifine has no effect on this graphical bug, but disabling the shader removes it. No error is output in the debug log when this glitch happens. 

Attached are screenshots at different angles of the pipe. I am not well-versed enough with the rendering of entities to provide much assistance as to why this issue just began, but I am not the only one with this issue (see http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1273247-buildcraft-nextgen-6-0-17-builders-blueprints?page=1055 and http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280299-sonic-ethers-unbelievable-shaders-v10-1?page=1270).

**Comment by Gibbycraft** [comment]
Apparently Github is having issues with image upload. I have posted the images http://imgur.com/0c4q3Iv,O2DidLQ,WDGg42P instead.

**Comment by psxlover** [comment]
Did you try without optifine?

**Comment by AEnterprise** [comment]
you have both SEUS and optifine messing with rendering, nothing we can do about it, both of those mods are known to break some mods rendering

**Comment by asiekierka** [comment]
I know the reason for this.

It's a workaround we do to go around a bug in 1.7.10 in which if you declare you render in pass 1 but then send no quads, Minecraft will crash - so we force-render an empty, transparent quad like that.

We can work around this, but we cannot fully fix this.

**Comment by Kubuxu** [comment]
asie, you can render null quad. Quad with all vertex in the same point.

**Comment by Gibbycraft** [comment]
Thank you very much. Perhaps a later version of Forge will have a fix for
this. Should I leave the issue open for now, in case they do release a bug
fix?

**Comment by Kubuxu** [comment]
@Gibbycraft it won't be fixed. My PR wad denied as Forge has ended support for 1.7.10.

**Comment by RagaRBM** [comment]
@Gibbycraft Yes, keep it open.

**Comment by asiekierka** [comment]
@Gibbycraft try with 6.3.3

**Comment by Gibbycraft** [comment]
Issue resolved as of 6.3.3! Great work asie!
