### ISSUE TITLE
API hook to list facades

### ISSUE THREAD

**Issue by planetguy32** [BuildCraft/BuildCraft#2400]
A future-proof way to list what facades are on a block, and which sides they're on, would be helpful.

**Comment by asiekierka** [comment]
@planetguy32 - generally, my plan was to:
a) split off IPipeTile into IPluggableProvider and IPipeTile
b) add IFacadePluggable which gives you that information

Would this work?

**Comment by asiekierka** [comment]
For what you're doing, I think https://github.com/BuildCraft/BuildCraft/commit/a14eb3b55fea33f1f595ff987a0c6c8054a60f37 is enough

**Comment by planetguy32** [comment]
That looks perfect, thanks. I've finished writing my end of this, and it's working.

**Comment by asiekierka** [comment]
Excellent. Closing. However, don't expect a release before February.

**Comment by planetguy32** [comment]
Good to know. I'll add a check for the actual API I use, and make sure to test it with other BC versions.
