### ISSUE TITLE
Add block queue to builder

### ISSUE THREAD

**Issue by AlexTheGre4t** [BuildCraft/BuildCraft#2401]
Would be pretty useful to see what the next block or item is gonna be used when using the builder.

http://mod-buildcraft.com/forums/index.php?topic=3355.0

**Comment by AEnterprise** [comment]
more clarification here: i think that the sugestion here is to show what the block it is going to place next in a seperate slot or in the first slot so people know what it needs if it's stuck, in large blueprints using more different materials then can be shown in the gui it is inpossible to know what it's waiting for.

**Comment by asiekierka** [comment]
No longer necessary.
