### ISSUE TITLE
Robots do not consume energy

### ISSUE THREAD

**Issue by Vexatos** [BuildCraft/BuildCraft#2404]
~~As you can see at https://github.com/BuildCraft/BuildCraft/blob/6.4.x/common/buildcraft/core/robots/AIRobotRecharge.java#L40-L44, the robots are basically given free energy. I assume the first call of receiveEnergy() should have `simulate` set to true.~~

**Comment by Vexatos** [comment]
Also, `consumePower()` does not actually consume power all the time, see https://github.com/BuildCraft/BuildCraft/blob/6.4.x/common/buildcraft/transport/PipeTransportPower.java#L546

**Comment by asiekierka** [comment]
No. 2 fixed in 6.3.x, No. 1 fixed in 6.4.x
