### ISSUE TITLE
Crash with latest version of this mod and latest version of AM2

### ISSUE THREAD

**Issue by crunkazcanbe** [BuildCraft/BuildCraft#2407]
Like the title says and here is the crash report http://pastebin.com/mGzT2Qvf

This does not happen with BuildCraft 6.3.1 and earlier versions . BTW I don't know if this is on your end or AM2 so I am posting this report on both GitHubs

**Comment by asiekierka** [comment]
In a sense, both, but I'll fix it on my side.

**Comment by asiekierka** [comment]
Fixed in BC 6.3.3. I hope.

**Comment by asiekierka** [comment]
I also fixed the update code from 6.2 -> 6.3. Turns out I screwed up badly.

**Comment by crunkazcanbe** [comment]
Thanks this fixed it. :) Thank you very much!
