### ISSUE TITLE
[6.3.3] Log spam and slow start-up together with Artifice

### ISSUE THREAD

**Issue by Revemohl** [BuildCraft/BuildCraft#2409]
Looks like using the newest version of BC together with Artifice makes something a bit bizarre happen.  Trying to start the game results in a huge stream of this line:
> [14:13:55] [Client thread/ERROR] [FML/]: 4479: ASM: shukaro.artifice.render.connectedtexture.TextureSubmap@10ac771 TexturesStitched(Lnet/minecraftforge/client/event/TextureStitchEvent$Post;)V

with a different set of characters every time after the TextureSubmap bit.

I got a crash this time (http://pastebin.com/G8HbdGHa), but that doesn't always happen - sometimes the game gets to the title screen, but I haven't checked how things look like in-game.
I'm not using much more than BC, Artifice and NEI in that instance either, so I doubt it's a bigger cross-mod interaction issue.
Lastly, going back to BC 6.3.1 solves this issue.

**Comment by asiekierka** [comment]
A workaround is likely to rename BuildCraft so as to force it to load before Artifice (like AAA_BuildCraft.jar)

**Comment by Mortvana** [comment]
For what it is worth (likely less than a quarter of a peso) I can confirm both (except in my case it always crashed)

**Comment by asiekierka** [comment]
The crash fixed.
