### ISSUE TITLE
Minecraft Crash

### ISSUE THREAD

**Issue by GoltikRee** [BuildCraft/BuildCraft#2410]
Minecraft Crashes when it tries to load BuildCraft
Crash Report: http://pastebin.com/7ypieqxH
BildCraft Version: 6.3.1
Forge Version: 10.13.2.1230 (MC 1.7.10)

**Comment by liach** [comment]
logisticspipes issue. Close it!

**Comment by GoltikRee** [comment]
http://pastebin.com/TU33ZKJP

**Comment by psxlover** [comment]
buildcraft-6.3.1-dev.jar... don't use the "dev" files

**Comment by liach** [comment]
Don't report it. In readme it said that if you have fastcraft or sth which makes changes on game engine, check them first. You have fastcraft. It seems that something had overridden the original method.

**Comment by asiekierka** [comment]
Update LogisticsPipes to the latest release. Update BuildCraft to the latest release. Don't use -dev files.
