### ISSUE TITLE
Fluid pipes won't connect to Thermal Expansion Tesseract

### ISSUE THREAD

**Issue by wollfxp** [BuildCraft/BuildCraft#2412]
Hi, not sure if this is a correct place to leave this bug report.
I'm playing FeedTheBeast Direwolf20 1.7.10 modpack, which includes Buildcraft 6.2.6 and Thermal Expansion 4.0.0B8-23. Here's [gist](https://gist.github.com/wollfxp/ce63b48e99d9ddc55e18) with all mods list.
I don't know if it is a thermal expansions bug with tesseracts, but fluid pipes simply do not connect to them in any configuration. Kinesis and item pipes do work correctly. Please, see attached screenshots.
![image](https://cloud.githubusercontent.com/assets/6288958/5884386/3e2fdf46-a365-11e4-9c4f-11d4d1b4feeb.png)
![image](https://cloud.githubusercontent.com/assets/6288958/5884378/2c832a64-a365-11e4-8f67-bbcde859775b.png)
![image](https://cloud.githubusercontent.com/assets/6288958/5884380/3166860c-a365-11e4-8895-e86fee363137.png)

Is this a Buildcraft bug or should I go to thermal expansions issue tracker and make them a little bit happier? :)

**Comment by asiekierka** [comment]
I think fixed on both sides, but DW20 is so slow at updating

**Comment by wollfxp** [comment]
OK, thx a lot! :)
