### ISSUE TITLE
Conflict with buildcraft and Rotarycraft

### ISSUE THREAD

**Issue by Mowmaster** [BuildCraft/BuildCraft#2413]
I have come across a crash with buildcraft 6.3.3(and 6.3.1) and the latest rotarycraft for 1.7.10. the pastebin crash report can be found here:   http://pastebin.com/Kzkyqu0E   This occurs when opening the Rotarycraft machines tab in creative. A similar error occures with nei installed. My uneducated gues s is its how buildcraft renders the tileentity from RC. Im looking for a fix for this otherwise I may have to remove BC for the time being :(

**Comment by AEnterprise** [comment]
nope this is caused by one of the mods you have installed using an to old BC api

**Comment by asiekierka** [comment]
Yes. Might be EnhancedPortals. Anything having buildcraft.api.mj in it really.
