### ISSUE TITLE
Filler Issue?

### ISSUE THREAD

**Issue by psychofad** [BuildCraft/BuildCraft#2415]
Is it just me or does the filler now clear land in a strange way.  The way it used to work it would clear everything line by line, but now it seems to clear only the soft materials this way (and sometimes not all of them) then move to the most random pattern of clearing away the harder materials like stone and ores.  I looked in the configs to see if there was anything I might have missed in there, but I see no mention of a random-ass clearing pattern option in there. 

Maybe this is a bug?  I haven't gotten any crashes or logs to post of this, but if you need more info please feel free to ask and I will help where I can.

**Comment by RagaRBM** [comment]
I like this behaviour of the Filler, actually. :))

**Comment by AEnterprise** [comment]
this is caused by the fact that the power required for breaking the block is now dependant on the block hardness. as long as it has enough power it'll behave like it used to behave, but if it doesn't have enough power to break the block it will skip the block and move on to the next one until it finds one that it can break. This results in your "random" patern

**Comment by psychofad** [comment]
aha...I am just starting out this world and I am currently powering it with 4 EnderIO stirling generators with Octadic capacitors so they are putting out a combined 320RF/t.  What is the optimal power input for the filler in RF?

**Comment by AEnterprise** [comment]
hmm, looking at the code the max input is 1000RF/T

**Comment by psxlover** [comment]
The filler shouldn't advance to the next block if it doesn't have enough energy IMO.

**Comment by asiekierka** [comment]
Intended behaviour. It will try to break the first block it has the energy to break.
