### ISSUE TITLE
One user can't connect to server because buildcraft error

### ISSUE THREAD

**Issue by RagaRBM** [BuildCraft/BuildCraft#2416]
I do not usually redirect bug reports in the forums, but this one seems to be quite an issue.
http://mod-buildcraft.com/forums/index.php?topic=3329.0

**Comment by leSamo** [comment]
Try not using optifine. It usually messes up with renderring.

**Comment by asiekierka** [comment]
That bug there was fixed in 6.3.2. It must be another bug.
