### ISSUE TITLE
[Server side only] Crash while using the search bar on creative

### ISSUE THREAD

**Issue by xJon** [BuildCraft/BuildCraft#2418]
Crash report: http://paste.ubuntu.com/9878452/
Very weird. Started to happen when I updated to the latest version (6.3.3).
Thanks!

**Comment by liach** [comment]
1. It shows that it's client on the crash report;
2. Try with less mod. Sometimes caused by overridden method by other mods.

**Comment by xJon** [comment]
1. You misunderstood me: This happens only when you're on a server, but client crashes - not the server.
2. I'll try and update here, thanks!

**Comment by liach** [comment]
Now I remember that I had met the same issue. @asiekierka told me to delete uuid.dat in server side save game. That time was caused by clicking facade in NEI. Maybe something wrong in source?

**Comment by xJon** [comment]
This happeneds on a new generated world.
