### ISSUE TITLE
Major Crash

### ISSUE THREAD

**Issue by EmanGremory** [BuildCraft/BuildCraft#2420]
Hello please help me my mine craft is crashing because i out an akward block that i took from my toomanyitems mod but it is a build craft block and when i placed it it was invisible and i bugg into it and the world don't want to start and i don't want to lose it please someone help me. Here is the crash report:

---- Minecraft Crash Report ----
// Don't do that.

Time: 28/01/15 16:22
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at buildcraft.transport.BlockGenericPipe.updateNeighbourSignalState(BlockGenericPipe.java:1118)
	at buildcraft.transport.TileGenericPipe.notifyBlockChanged(TileGenericPipe.java:351)
	at buildcraft.transport.TileGenericPipe.func_145845_h(TileGenericPipe.java:365)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at buildcraft.transport.BlockGenericPipe.updateNeighbourSignalState(BlockGenericPipe.java:1118)
	at buildcraft.transport.TileGenericPipe.notifyBlockChanged(TileGenericPipe.java:351)
	at buildcraft.transport.TileGenericPipe.func_145845_h(TileGenericPipe.java:365)

-- Block entity being ticked --
Details:
	Name: net.minecraft.src.buildcraft.transport.GenericPipe // buildcraft.transport.TileGenericPipe
	Block type: ID #194 (tile.pipeBlock // buildcraft.transport.BlockGenericPipe)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-518,80,83), Chunk: (at 10,5,3 in -33,5; contains blocks -528,0,80 to -513,255,95), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Actual block type: ID #194 (tile.pipeBlock // buildcraft.transport.BlockGenericPipe)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Build Craft
	All players: 1 total; [EntityPlayerMP['EMAN_THE_MEN'/209, l='Build Craft', x=-514,58, y=80,00, z=81,93]]
	Chunk stats: ServerChunkCache: 1066 Drop: 0
	Level seed: -1983228130014222897
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 799003 game time, 145836 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 28296 (now: false), thunder time: 2821 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.7.5
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 184859696 bytes (176 MB) / 488574976 bytes (465 MB) up to 1065025536 bytes (1015 MB)
	JVM Flags: 1 total; -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.85.1284 Minecraft Forge 10.13.2.1284 17 mods loaded, 17 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1284} [Forge Mod Loader] (forge-1.7.10-10.13.2.1284.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1284} [Minecraft Forge] (forge-1.7.10-10.13.2.1284.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	battlegear2{1.0.6.3} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	furnace3d{1.2.0} [Furnace 3D] ([1.7.10] 3D Furnace-1.3a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	abm{0.1} [Anime Battle Mod] (Anime-Battle-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bleach{F1.0.4} [LittleBreadLoaf's Bleach Mod] (bleach-v-1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{6.3.1} [BuildCraft] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{6.3.1} [BC Transport] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{6.3.1} [BC Silicon] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{6.3.1} [BC Builders] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{6.3.1} [BC Energy] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{6.3.1} [BC Factory] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SwordPedestal{1.0(1.7.10)} [Sword Pedestal] (Sword-Pedestal-Mod-1.7.10-2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	uraniumMod{dev14.9.14a} [Uranium Mod] (Uranium-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['EMAN_THE_MEN'/209, l='Build Craft', x=-514,58, y=80,00, z=81,93]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by kane-thornwyrd** [comment]
Please, put your logs in [Gist](https://gist.github.com/) that's wayyyy better to read !

**Comment by asiekierka** [comment]
http://asie.pl/bc640a1.jar - use this to remove the erroring block ONLY. Also calling @marcin212 @Kubuxu they had the same issue

**Comment by gixmy** [comment]
I also had this issue. Running my server once with the bc jar removed the erroring block. Thank you.

**Comment by asiekierka** [comment]
Fixed in BuildCraft 6.3.5.

**Comment by spamenigma** [comment]
Hi, Getting the same issue suddenly here. Crashing my server. Using BC 6.3.6

http://pastebin.com/Q7jYUtyT

Thanks
