### ISSUE TITLE
Gradle subprojects

### ISSUE THREAD

**Issue by SoniEx2** [BuildCraft/BuildCraft#2421]
http://gradle.org/docs/current/userguide/multi_project_builds.html

Things that could go on their own subproject:

1. BCCore. This subproject is the "main" project and everything depends on it. (there are reasons why you'd want to put it in a subproject instead of using the main/base project.)
2. BCMiners.
3. BCBuilders.
4. BCFactory.
5. [etc, you get the idea.]

**Comment by Kubuxu** [comment]
subprojects are confusing and split PR, Issues. They also bring a lot of mess into general management.

**Comment by SoniEx2** [comment]
Gradle subprojects are not git subprojects. PRs and issues won't be split.

**Comment by asiekierka** [comment]
No.
