### ISSUE TITLE
Architect Table crash + Builder unable to place chests with signs on

### ISSUE THREAD

**Issue by LouisHutch** [BuildCraft/BuildCraft#2424]
Mods: BC 6.3.3, BCA 1.8.4, Openblocks, NEI, WAILA

Firstly I crashed When trying to place a blank blueprint in an architect table : http://pastebin.com/rcQgj4G5

This crash happened when I changed the option in the architect table from survival to creative and put a blank blueprint into it.

I already have a blueprint of the build and when i tested buiding it using the builder, It doesn't place the chests and the signs that are supposed to be on the chests just fall on the ground and the chests aren't placed

Blueprint + World download: https://drive.google.com/folderview?id=0B0kT-t-Y3RDTYlg1Z3hGSFlVX0U&usp=sharing 

Images: http://imgur.com/a/UFRvB

**Comment by asiekierka** [comment]
Does the architect table have any box configured in the first case? What is inside the box? What is inside any chests in the box?

The chests aren't placed as it fails to map items with that build.

**Comment by LouisHutch** [comment]
Yes the architect table has an area selected (as shown in the pics) which has diamond pipes, iron pipes, lenses, golden pipes, chests and signs inside the architect table area. There are a bunch of lists in the chests. These lists have BC items, vanilla items and BCA items on the lists.

**Comment by hea3ven** [comment]
This issue seems to be caused by items configured in the lists, that are no longer defined. This could be happen when an update removes an item from the game. How old is the world? would it be possible for this to be the case?

**Comment by LouisHutch** [comment]
this could not be the case, I used the architect table to scan the build and the builder to rebuild it right after each other

**Comment by hea3ven** [comment]
Ohh, I understood it wrong. I guess I stumbled into a different bug by chance.

**Comment by LouisHutch** [comment]
i have now just check my list again and they have all got changed, to random items, both vanilla and BC

**Comment by hea3ven** [comment]
man, this was a tough one. Unfortunately, the list items in your world were modified and you are gonna need to set them up again them again.
