### ISSUE TITLE
java.lang.NullPointerException: Registering texture

### ISSUE THREAD

**Issue by fcpwiz** [BuildCraft/BuildCraft#2425]
Crash Report: https://gist.github.com/fcpwiz/3e9eff550b661ba86710
Log: https://gist.githubusercontent.com/fcpwiz/ab1e8b8130680a317c16/raw/gistfile1.txt

Buildcraft 6.3.3

**Comment by GreatOrator** [comment]
Looks like the same crash I am getting in my modpack.

I tested extensively to make sure another mod wasn't modifying the rendering in minecraft before reporting.

http://pastebin.com/vX6ZcZ73

Excellent work asie!

**Comment by fcpwiz** [comment]
@GreatOrator So, no fix so far?

**Comment by GreatOrator** [comment]
That would be why I am reporting it, so she has more examples to try to fix.  :)

**Comment by asiekierka** [comment]
He.

**Comment by fcpwiz** [comment]
@asiekierka Hey Asie, how do I fix this?

**Comment by asiekierka** [comment]
You update.

**Comment by GreatOrator** [comment]
Woops, sorry asie...hard to tell sometimes bases on avatar and name. :)

**Comment by fcpwiz** [comment]
@asiekierka Awesome! Thanks Asie!!
