### ISSUE TITLE
Buildcraft Refineries use network crippling amounts of bandwidth

### ISSUE THREAD

**Issue by ZeekDaGeek** [BuildCraft/BuildCraft#2428]
Mod version: buildcraft-6.3.3.jar
Forge version: 1.7.10-10.13.2.1277
Other mods: https://docs.google.com/a/graythought.com/spreadsheet/ccc?key=0AndvSyXha_pPdHRYTXVtNVpHSzhrNjZxTDAzS2V3UEE&usp=sharing#gid=0

http://i.imgur.com/Ta1qAXK.png

When using Refineries to process oil to fuel it seems that it really likes to tell clients about how it's doing work or something. If you look in the bottom right hand corner of the screen using 8-10 refineries it's sending 1020 packet per second.

When attempting to do this in multiplayer with 32 refineries the server was attempting to send over 10mbps and causing my client to be unable to remain connected.

This bug makes fuel completely impossible to use as power.

**Comment by warlordjones** [comment]
Investigating

**Comment by AEnterprise** [comment]
@warlordjones  i think that the most BC machines are just sending WAY to much update packages, some send one every tick even i think

**Comment by warlordjones** [comment]
Indeed. I shall see what I can do/find out

**Comment by warlordjones** [comment]
In the meantime @ZeekDaGeek you can turn down update frequency in the main config (note: increase the number, not decrease it! :P)

**Comment by warlordjones** [comment]
I've turned down (halved) update frequency by default now, but I need to investigate reducing packets, since as AE said, the numbers being sent are way too high.

**Comment by ZeekDaGeek** [comment]
This is still a problem. 4 Refineries make a server unusable in terms of network usage..

**Comment by asiekierka** [comment]
@ZeekDaGeek what version?

**Comment by ZeekDaGeek** [comment]
Sorry I've neglected this ticket after submitting again on it.

Buildcraft version: 6.4.3

Testing on a server here is my setup: http://zeekdageek.tv/ss/aX2yU.png
Here is the network usage (Reported by Opis): http://zeekdageek.tv/ss/q2raY.png

There is a direct correlation to when Oil is being processed in the Buildcraft Refineries to the amount of network being used and it seems way excessive.

If no oil is being processed the network usage drops to about 15,000b/s while not loading chunks. By only adding oil processing the the network traffic spikes insanely high.

http://zeekdageek.tv/ss/jkidy.png

What has been fixed is it doesn't seem to be an issue anymore when the Refineries are idle.

**Comment by ZeekDaGeek** [comment]
Never mind, just ignore Zeek, he's a rambling crazy man, after breaking and replacing things in the patch things seemed to have fixed themselves.

**Comment by simon816** [comment]
@ZeekDaGeek On a totally unrelated note there is massive red warnings when visiting that site linked above, you may want to investigate this: https://www.mywot.com/en/scorecard/zeekdageek.tv

**Comment by ZeekDaGeek** [comment]
@simon816 I wouldn't trust services like this, they bully companies. Essentially they allow a user to review websites, then the owner comes by because someone mentions it and then in order for me to remove reviews they try to charge you a fee.

Users who are aware of the scam from working in a web development industry then go around and review websites poorly to grief people.

I'm a livestreamer as a full time job, which if you've ever read YouTube comments or been in Twitch chats you can collaborate that it brings a wide variety of griefers.
