### ISSUE TITLE
Advanced Crafting Table Crash with Minetweaker

### ISSUE THREAD

**Issue by ultrasn0w** [BuildCraft/BuildCraft#2429]
Whenever I lay a Recipe made with Minetweaker into an Advanced Crafting Table, my game crashes and the log spits out this:

http://pastebin.com/B0WCC7zk

I'm not sure if this is a crash related to Minetweaker or BC, so I opened the Issue on both Gits.
(MT Issue: https://github.com/stanhebben/MineTweaker3/issues/144)

Greetings
ultrasn0w

Edit: Auto Workbenches are working fine.

**Comment by hea3ven** [comment]
What versions are you using for both buildcraft and minetweaker? also, if possible, could you provide the minetweaker scripts you are using?

**Comment by asiekierka** [comment]
Most likely MT's side.
