### ISSUE TITLE
BC 6.3.4 - Builder does not place the mining well

### ISSUE THREAD

**Issue by LouisHutch** [BuildCraft/BuildCraft#2430]
See title ^

**Comment by AEnterprise** [comment]
was the mining well recorded in the blueprint? did it show a mining well as requirement?

**Comment by LouisHutch** [comment]
it did not show the mining well as a requirement. The mining well was in the blueprinted area. Also the builder trys to place a path marker and it drops on the ground. It does show the path marker as a requirement

**Comment by AEnterprise** [comment]
if it didn't show the mining well as a requirement then it's not recorded, it might have been in the area but not all TE's get recorded in blueprints to prevent dupe bugs

**Comment by loordgek** [comment]
TE? the mining well is from BC it self

**Comment by BigXplosion** [comment]
@loordgek, he was talking about a TileEntity
