### ISSUE TITLE
Pipe model:

### ISSUE THREAD

**Issue by CubeWrench202** [BuildCraft/BuildCraft#2433]
I don't know if it's the model, or the texture, but the Buildcraft pipe(s) look different in newer versions compared to older ones, any chance of bring the old pipe looking-style like back?

**Comment by warlordjones** [comment]
Placed in world or in inventory?

**Comment by CubeWrench202** [comment]
In World.

**Comment by CubeWrench202** [comment]
I've been searching and i think that @CovertJaguar made this change.

**Comment by laz2727** [comment]
Screenshots?

**Comment by CubeWrench202** [comment]
Leave me a second....

**Comment by CubeWrench202** [comment]
Past:
http://www.google.com.ar/imgres?imgurl=http://vignette2.wikia.nocookie.net/technicpack/images/c/c8/500px-Buildcraft.png/revision/latest%253Fcb%253D20120808085850&imgrefurl=http://technicpack.wikia.com/wiki/Category:BuildCraft&h=279&w=500&tbnid=G7kDP5n7jaUN2M:&zoom=1&docid=xUSRyX-7zXTnQM&ei=KW7OVJrfOs32gwTSwIKIBQ&tbm=isch&ved=0CDwQMygRMBE

Now:
http://imgur.com/yoIHDTv

**Comment by warlordjones** [comment]
Only difference I can see is transported items used to render a bit larger...

**Comment by CubeWrench202** [comment]
If you prest attention:
1 - The connection of one pipe to other pipe is different, prest attention.
2 - TEXTURE ONLY:Cobblestone pipe is more darker now.
3 - As you said before, items rendered more bigger before.
4 - I think all the pipe textures has been a little bit tweaked, leave me show you:
Check minute 0:13 of this video of BC pipes in a older version : https://www.youtube.com/watch?v=gyra1TDWmQA.
Now check how they look now : http://imgur.com/uXy1Pkz

**Comment by SandGrainOne** [comment]
Try making Stone pipes using smooth stone.

There has probably been multiple changes to the pipes, both intentionally and as side effects. I don't think the old version will be back.
