### ISSUE TITLE
Make 6.3.x the default branch in the repository

### ISSUE THREAD

**Issue by KamranMackey** [BuildCraft/BuildCraft#2438]
The repository should no longer go to the 6.1.x branch when somebody visits the repo. It should go to the 6.3.x branch, as that's the latest stable version, so it should be the default branch instead of the default branch still being 6.1.x.

**Comment by liach** [comment]
No, it should be master. More, Adrian is just a collaborator.

**Comment by asiekierka** [comment]
No can do. Only SpaceToad can do.

**Comment by AEnterprise** [comment]
i think @CovertJaguar also might be able to do it

**Comment by CovertJaguar** [comment]
6.3? Done

**Comment by psxlover** [comment]
I think "master" is a better choise, else you'll have to change it again when 6.4 become mainstream.

**Comment by KamranMackey** [comment]
@psxlover Actually no it shouldn't be master. That branch is only updated when @asiekierka releases a new version, and normally the branch that's updated the most should be default. Trust me, it's the same way in the Forestry for Minecraft repository.

**Comment by liach** [comment]
@KamranMackey The biggest problem is if you always change the default branch, the argument between Adrian and CJ,Lex may be... Oh dear

**Comment by CovertJaguar** [comment]
The biggest reason to change it to the current dev branch is because its the branch that PRs default against. And trust me, it a huge pain to have to change the branch that you merge a PR to after the fact.
