### ISSUE TITLE
java.lang.NullPointerException api.robots

### ISSUE THREAD

**Issue by Yselith** [BuildCraft/BuildCraft#2441]
Hello,

I get a spam console with this logs:

http://pastebin.com/t7skW2pE

**Comment by liach** [comment]
Not enough information. You should put the log in (gist)[http://gist.github.com/], which you can find the log in .minecraft\logs\fml-client-latest.log .

**Comment by Yselith** [comment]
Is this enought ? I don't think i can get more

https://gist.github.com/Yselith/817a5eeb27385aa839a3

**Comment by hea3ven** [comment]
What version are you using?, 6.3.0 should have fixed this.

**Comment by Yselith** [comment]
buildcraft-6.2.6.jar
bcapi-6.0.x.jar 

Mods from DW20 1.0.3 pack

**Comment by asiekierka** [comment]
"6.3.0 should have fixed this."
