### ISSUE TITLE
BuildCraft:Factory:miningWellBlock obtains ID 178 thus blocking inverted daylight sensor (vanilla)

### ISSUE THREAD

**Issue by chde** [BuildCraft/BuildCraft#2442]
ID to be fixed. Tested version 6.3.3.

Thanks in Advance

**Comment by AEnterprise** [comment]
there is a newer BC available and we don't assign ID's, forge does that

**Comment by chde** [comment]
Wasnt in any changelog so I figured it is not stuck with .3
Thanks for the update on ID assignment.
I'll follow it up.
