### ISSUE TITLE
A solid facade does not actually plug a pipe [6.3.4]

### ISSUE THREAD

**Issue by Sandriell** [BuildCraft/BuildCraft#2443]
I have a solid facade between a wooden pipe and a chest, however the wooden pipe is still able to pull items from that chest, through the solid facade.

![facade-bug](https://cloud.githubusercontent.com/assets/10704907/6053547/b7c33a4a-acae-11e4-951e-01e777aa2bd8.png)

As shown in the picture, the wooden pipe was pulling items from the chest on the right.

Upon further testing while I was writing this, I discovered this only happens when both ends of the wooden pipe are "open", as shown in the pic. If I smack it with a wrench and close the end attached to the chest on the left, it stop pulling from the chest on the right. Regardless, it seems to me it should never be able to pull through a solid facade.

**Comment by asiekierka** [comment]
That, oddly enough, does look clearly like a hollow facade. Reproduction steps?

**Comment by hea3ven** [comment]
The wooden pipe is just not taking into account facades and plugs when it comes to selecting the valid inputs.

**Comment by asiekierka** [comment]
Oh. I see.

**Comment by Sandriell** [comment]
It is a hollow facade on the left, that is where I wanted it to pull from.

On the right though is a solid facade, and that is the one it was incorrectly pulling from.

**Comment by crunkazcanbe** [comment]
asiekierka glad to see your not gone . I thought my fav modder was gone :(

**Comment by asiekierka** [comment]
@crunkazcanbe - But I am gone.

**Comment by Sandriell** [comment]
You rock hea3ven! :D
