### ISSUE TITLE
Quarry doesn't break blocks

### ISSUE THREAD

**Issue by Ariazone** [BuildCraft/BuildCraft#2446]
I'm running a Direwolf20 1.7 FTB server. We are using Forge Essentials for permissions. 

The issue is that i can build a quarry but once i start the quarry it will show a breaking animation but it doesn't actually break the block. 

We've tried adjusting the permissions of [BuildCraft] (and [[BuildCraft]]) to /OP, and also with regular permission (members, OPS).

I've also seen issue #2224 which suggest a Fake Player. We've been searching through all the relevant folders and files but couldn't find anything. (Neither the BuildCraftCore.java?)

**Comment by asiekierka** [comment]
The username is [BuildCraft], which has a UUID derived from "buildcraft.core".

**Comment by Ariazone** [comment]
The server doesn't know [BuildCraft] or [[BuildCraft]], it only agrees with 'Buildcraft'. 

(And how should i apply it, as it does not work well with group-permissions? )

**Comment by rob5251** [comment]
I'm having the same issue with fillers placing blocks, I've tried opping as well as setting [BuildCraft] as the admin group in my permissions.

@Ariazone 
Are you using PermissionsEx? That's what I'm using to handle permissions.

**Comment by Ariazone** [comment]
@rob5251 No, just Forge Essentials. I kind of hoped we didn't have to install all extra things for a normally working server >.< (I assume the code is the UUID?)

**Comment by rob5251** [comment]
@Ariazone 
Yeah the UUID is 77456a1f-b9f9-3f84-8863-ddef5b8e2209 however I've yet to get it working.

**Comment by rob5251** [comment]
@Ariazone 
I got it working on my server, I have the permissions set with PermissionsEx like shown above, the issue was that the following line had to be set to "true" in cauldron.yml

```
fake-players:
  do-login: true
```

**Comment by Ariazone** [comment]
@rob5251 The only thing we added to the main ftb download is forge essentials ^-^; (And i believe Cauldron is not part of basic FTB)

I'll try and see if i can find something with fake players then...

**Comment by rob5251** [comment]
Reporting back; my fix seemed to work at first, but now it's not working again. I've tried multiple things to get it working again.
Tried adding the UUID's back into my permissions and made sure that fake-players was still set to true.

I have no idea what caused it to brake again, fillers can not place blocks yet again. :(

**Comment by asiekierka** [comment]
This is not our issue.

**Comment by Cosmicnatrix** [comment]
Be sure that any plugin like AcceptRules has the uuid of buildcraft accept the rules.

**Comment by AEnterprise** [comment]
@Cosmicnatrix thanks for your input but posting on a thread that has been closed for more then a year is kinda pointless

**Comment by Manjack4060** [comment]
here's a notification
