### ISSUE TITLE
Crash when creating template: java.lang.IllegalArgumentException: Empty string not allowed

### ISSUE THREAD

**Issue by Sandriell** [BuildCraft/BuildCraft#2449]
Trying to create a template using the Architect Table with rotation off (it worked once with rotate on, and then never again, on or off), excavate and creative mode- and sadly, I am crashing.

https://gist.github.com/Sandriell/77cc20e0df979ff3bc15

I am using BC: 6.3.6

**Comment by hea3ven** [comment]
What blocks are you trying to copy?, basically it's crashing because one of the items (could be items inside a chest for example) you are trying to copy is not in the item registry, which should't happen.

**Comment by Sandriell** [comment]
Far too many to list. lol It is my home, which consists of my house and a large underground sorting system, so lots of chest with lots of items in them.

No clue what could be causing it.. there is nothing in any of the chests that crashes me.

**Comment by asiekierka** [comment]
@Sandriell - could you send over the world + modpack?

**Comment by Sandriell** [comment]
I might have deleted the world.. I was moving things to a new world, that's why I needed to make the blueprints. I'll check and pack it all up if I still have it.

**Comment by Sandriell** [comment]
Looks like I did indeed delete the world.
