### ISSUE TITLE
Pipe Inventory Error

### ISSUE THREAD

**Issue by Wolfseverest93** [BuildCraft/BuildCraft#2452]
Hey, I found a pretty annoying error in interaction between your pipes and machines from other mods, for instance: I don't have any problem pulling items out with your pipes, but when I go to put items needed into an inventory by use of your pipes it causes a ghost item bug in the machine, I discovered this issue when using the pipes to interact with a Forestry multiblock farm to add dirt and fertilizer without having to keep heading back and doing it myself, that didn't work out too well though...

It caused the machine to generate ghost items in any free spaces of the inventory when the machine gathered from the trees it broke, making it impossible to gather further items because of this error, thus killing the automation of it.

At first I thought this was a Forestry issue since I hadn't had this problem with any other machines, but then I updated to their latest and it persisted, so I tried Ender IO pipes and the issue vanished right away, leading me to believe it to actually be a buildcraft pipe bug. Heres a backlink to the issue posted to Forestry for reference: https://github.com/ForestryMC/ForestryMC/issues/500#event-232066429 I really hope this gets fixed some time, I actually like using your pipes a lot.

PS: Really loving the robots you guys came up with, great idea~ but can they be configured to automatically go back to work even if items or such are placed after the robots? At least some day...

**Comment by hea3ven** [comment]
Interesting, what version of buildcraft are you using. Also, what types of pipes are you using?, it would really help if you post a screenshot of the pipe setup.

Regarding robots, they are still being worked on heavily to fix all their bugs.

**Comment by Wolfseverest93** [comment]
nevermind i fixed it. it was caused by the world memory leak issue i had from telepads. Sorry to have wasted your time and that of Forestry. next time i'll further look into things before reporting any problems i encounter. if you would still like to see the error in action let me know and i will reinstall telepads and induce the error by replacing the telepad next to the pipe again. i got rid of that mod because it caused lag by flooding the client threads, but now im kinda glad i did.
