### ISSUE TITLE
restore stripe pipe behaviour for farming

### ISSUE THREAD

**Issue by AEnterprise** [BuildCraft/BuildCraft#2455]
in the past you could use stripe pipe for farming automation, in earlier version of BC 6 you could put a stripe pipe 1 block above your farmland and it would plant seeds, now it doesn't, the pipe has to be touching the block (on the side) to plant it

**Comment by hea3ven** [comment]
I'm working on the stripe pipe code, so I'll take a look at it.

**Comment by hea3ven** [comment]
This is fixed in 6.4.0
