### ISSUE TITLE
Crash Server - Buildcraft Transport Pipe

### ISSUE THREAD

**Issue by YouTy6bl4** [BuildCraft/BuildCraft#2456]
Versions mod: 6.3.4 and 6.3.6
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212

When entering players is a crash servers.

Crash Report:
https://yadi.sk/i/1pl5oTHqecKjy

**Comment by hea3ven** [comment]
Very similar to #2420, could you post the crash report using the 6.3.6 version?

**Comment by YouTy6bl4** [comment]
6.3.4 and 6.3.6, ok
