### ISSUE TITLE
Missing Texture

### ISSUE THREAD

**Issue by vigia122** [BuildCraft/BuildCraft#2457]
The texture **action_machinecontrol_mode.png** can't be loaded. *BuildCraft 6.3.6*.

![screenshot_12](https://cloud.githubusercontent.com/assets/2721565/6173723/0e16d8ac-b2d1-11e4-9599-18c902a9bb31.png)

Edit: It's really missing.

![screenshot_14](https://cloud.githubusercontent.com/assets/2721565/6174375/720399d2-b2d5-11e4-80f4-82ec12652d6b.png)

**Comment by hea3ven** [comment]
Asie, what does the "Mode" mode do?

**Comment by VitorH** [comment]
I don't know. Probally it chages the working mode in some machines. But I think it don't break anything. Maybe the texture isn't used in the mod, but is in code and it is just some console spam.

**Comment by hea3ven** [comment]
Yeah, it's not used by buildcraft itself, but it is in the api, so it might have been implemented for another mod to use.

**Comment by neclimdul** [comment]
Outside observer, exceptions are slow. Really slow. Missed textures cause forge to exception multiple times while loading. Removing or providing the texture seems a reasonable fix.

**Comment by VitorH** [comment]
So I will reopen this issue and wait for a fix...
