### ISSUE TITLE
Feature Request - Gates/liquid transfer pipes.

### ISSUE THREAD

**Issue by cainland** [BuildCraft/BuildCraft#2465]
Is it possible to make the tiers of gates extract more items with the energy pulse the higher tier the gate is. 1 at basic 2 at iron 4 at gold etc. whatever amount adds up to a stack at a time with 4 gates at the highest teir. or whatever seems more balanced. possibly the same thing for liquids. the liquid pipes even at their highest teir are incredibly slow.

**Comment by SandGrainOne** [comment]
They should already do that. With higher tier gates you have more action slots that can have Energy Pulser selected. They stack and produce exponential amounts of power the more you add.

**Comment by cainland** [comment]
this is the first i've heard of this. does it matter if it's an and or or gate? doesn't seem to be documented anywhere.

**Comment by SandGrainOne** [comment]
It does not matter if it is an AND or OR gate. Just keep in mind that all the conditions must be true.

**Comment by cainland** [comment]
thank you i appreciate the advice

**Comment by Sandriell** [comment]
Didn't know this either! Just tested it and can confirm it does still work like this. You can even use multiple gates to further increase the effect.
