### ISSUE TITLE
Suggestion: Add support for Forestry Backpacks

### ISSUE THREAD

**Issue by Sandriell** [BuildCraft/BuildCraft#2475]
Would be cool to see support added for three (that I can think of so far) backpacks if you have Forestry installed.

Plumper's Backpack (plus woven version)
 - Holds all the different pipes and the wrench

Electrician's Backpack (plus woven version)
 - Holds wire, chip-sets, gates,  lens', filters, gate-copier, etc.

Robotic's Backpack (plus woven)
 - Basically everything related to robots.

**Comment by hea3ven** [comment]
This should be done in [BuildCraftCompat](https://github.com/BuildCraft/BuildcraftCompat)

**Comment by Silwing** [comment]
Second this... That would be really cool :+1:

**Comment by asiekierka** [comment]
Replicated in https://github.com/BuildCraft/BuildcraftCompat/issues/7
