### ISSUE TITLE
Builders not respecting player permissions

### ISSUE THREAD

**Issue by AEnterprise** [BuildCraft/BuildCraft#2476]
if someone uses a mod/plugin to protect block from being broken in an area that blocks the mining of blocks by the quarry but not the destruction of blocks to build the frame

reported on the forum: http://mod-buildcraft.com/forums/index.php?topic=3519.0

**Comment by asiekierka** [comment]
This is actually a bigger issue.

**Comment by asiekierka** [comment]
Please test and report back -> http://asie.pl/bc641d.jar

**Comment by Nentify** [comment]
Quarries can break blocks and place frames inside WorldGuard 6 protected areas and GriefPrevention 9.1 protected areas.

**Comment by asiekierka** [comment]
The code is working properly. It might be a bug on Cauldron's side, however we are emitting the right events.

**Comment by SebasvanDuuren** [comment]
I cant even start my server

**Comment by LemADEC** [comment]
Issues isn't reproduced with buildcraft 7.0.23 + KCauldron 1.7.10-1492.155
