### ISSUE TITLE
All I know it has something to do with buildcraft crashing my world : /

### ISSUE THREAD

**Issue by Megachuggayoshi** [BuildCraft/BuildCraft#2477]
ummmm help me alot....Please

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 2/18/15 10:05 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
at buildcraft.transport.BlockGenericPipe.updateNeighbourSignalState(BlockGenericPipe.java:1117)
at buildcraft.transport.TileGenericPipe.notifyBlockChanged(TileGenericPipe.java:351)
at buildcraft.transport.TileGenericPipe.func_145845_h(TileGenericPipe.java:365)
at net.minecraft.world.World.func_72939_s(World.java:1939)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at buildcraft.transport.BlockGenericPipe.updateNeighbourSignalState(BlockGenericPipe.java:1117)
at buildcraft.transport.TileGenericPipe.notifyBlockChanged(TileGenericPipe.java:351)
at buildcraft.transport.TileGenericPipe.func_145845_h(TileGenericPipe.java:365)

-- Block entity being ticked --
Details:
Name: net.minecraft.src.buildcraft.transport.GenericPipe // buildcraft.transport.TileGenericPipe
Block type: ID #781 (tile.pipeBlock // buildcraft.transport.BlockGenericPipe)
Block data value: 0 / 0x0 / 0b0000
Block location: World: (-407,208,-1435), Chunk: (at 9,13,5 in -26,-90; contains blocks -416,0,-1440 to -401,255,-1425), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,0,-1536 to -1,255,-1025)
Actual block type: ID #781 (tile.pipeBlock // buildcraft.transport.BlockGenericPipe)
Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1939)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
Level name: Lo/
All players: 1 total; [EntityPlayerMP['Megachuggayoshi'/29, l='Lo/', x=-403.50, y=209.00, z=-1435.50]]
Chunk stats: ServerChunkCache: 1250 Drop: 0
Level seed: -13153935784635129
Level generator: ID 00 - default, ver 1. Features enabled: true
Level generator options:
Level spawn location: World: (-75,64,-732), Chunk: (at 5,4,4 in -5,-46; contains blocks -80,0,-736 to -65,255,-721), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
Level time: 1988765 game time, 338150 day time
Level dimension: 0
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 38223 (now: false), thunder time: 35066 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Mac OS X (x86_64) version 10.9.4
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 244174312 bytes (232 MB) / 686817280 bytes (655 MB) up to 954728448 bytes (910 MB)
JVM Flags: 1 total; -Xmx1G
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 69 mods loaded, 69 mods active
mcp{9.05} Minecraft Coder Pack Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
FML{7.10.85.1291} Forge Mod Loader Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Forge{10.13.2.1291} Minecraft Forge Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
appliedenergistics2-core{rv1-stable-1} AppliedEnergistics2 Core Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
CodeChickenCore{1.0.4.29} CodeChicken Core Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
{000} CoFH ASM Data Initialization Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
NotEnoughItems{1.0.4.83} Not Enough Items Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
OpenModsCore{0.6} OpenModsCore Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
bspkrsCore{6.15} bspkrsCore Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Treecapitator{1.7.10} Treecapitator Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
appliedenergistics2{rv1-stable-1} Applied Energistics 2 Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ArchimedesShips{1.7.10 v1.7.1} Archimedes' Ships Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Backpack{2.0.0} Backpack Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
BiblioCraft{1.9.2} BiblioCraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
CoFHCore{1.7.10R3.0.0B9} CoFH Core Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ThermalFoundation{1.7.10R1.0.0RC1} Thermal Foundation Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ThermalExpansion{1.7.10R4.0.0B8} Thermal Expansion Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
BigReactors{0.4.1A} Big Reactors Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
BuildCraft|Core{6.3.6} BuildCraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
BuildCraft|Transport{6.3.6} BC Transport Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
BuildCraft|Silicon{6.3.6} BC Silicon Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
BuildCraft|Builders{6.3.6} BC Builders Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
BuildCraft|Energy{6.3.6} BC Energy Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
BuildCraft|Factory{6.3.6} BC Factory Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ChickenChunks{1.3.4.16} ChickenChunks Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
chisel{1.5.7} Chisel Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ComputerCraft{1.65} ComputerCraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Baubles{1.0.1.10} Baubles Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ForgeMultipart{1.1.0.314} Forge Multipart Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ExtraUtilities{1.1.0k} Extra Utilities Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
inventorytweaks{1.58-147-645ca10} Inventory Tweaks Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
IronChest{6.0.62.742} Iron Chest Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Waila{1.5.8} Waila Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
JABBA{1.1.4} JABBA Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Mantle{1.7.10-0.3.2.jenkins184} Mantle Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded{1.7.10R2.8.0RC6} MineFactory Reloaded Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
RedstoneArsenal{1.7.10R1.1.0RC1} Redstone Arsenal Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Mekanism{7.1.1} Mekanism Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MekanismGenerators{7.1.1} MekanismGenerators Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MekanismTools{7.1.1} MekanismTools Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC6} MFR Compat: Applied Energistics Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC6} MFR Compat: Atum Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC6} MFR Compat: BackTools Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC6} MFR Compat: BuildCraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC6} MFR Compat: Chococraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC6} MFR Compat: ExtraBiomes Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC6} MFR Compat: Forestry Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC6} MFR Compat: ForgeMicroblock Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC6} MFR Compat: IC2 Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC6} MFR Compat: Mystcraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC6} MFR Compat ProjectRed Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC6} MFR Compat: Railcraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC6} MFR Compat: RP2 Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC6} MFR Compat: Sufficient Biomes Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Thaumcraft{4.2.3.4} Thaumcraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC6} MFR Compat: Thaumcraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC6} MFR Compat: Thermal Expansion Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
TConstruct{1.7.10-1.8.2.build858} Tinkers' Construct Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC6} MFR Compat: Tinkers' Construct Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC6} MFR Compat: TwilightForest Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC6} MFR Compat: Vanilla Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
NetherOres{1.7.10R2.3.0RC4} Nether Ores Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
OpenMods{0.6} OpenMods Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
OpenBlocks{1.3} OpenBlocks Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
harvestcraft{1.7.10d} Pam's HarvestCraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
simplyjetpacks{1.3.2} Simply Jetpacks Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
YALSM{2.1.3} Yet Another Leather Smelting Mod Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
McMultipart{1.1.0.314} Minecraft Multipart Plugin Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ForgeMicroblock{1.1.0.314} Forge Microblocks Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
Mantle Environment: Environment healthy.
TConstruct Environment: Environment healthy.
Stencil buffer state: Function set: ARB, pool: internal, bits: 8
AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:ON, MJ6:ON, MJ5:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Player Count: 1 / 8; [EntityPlayerMP['Megachuggayoshi'/29, l='Lo/', x=-403.50, y=209.00, z=-1435.50]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by asiekierka** [comment]
See #2456.
