### ISSUE TITLE
Robot Blacklist not generating in Configs

### ISSUE THREAD

**Issue by aridhol** [BuildCraft/BuildCraft#2482]
I tested this on various versions since 6.3.2 (when it was implemented) and of course fresh configs each time and the option doesn't seem to show up. There should be a boolean for each robot that can easily be set to true or false.

I love buildcraft but the robots are a bit overmuch for my taste and can get messy, so just the option would be fabulous and I know you've already implemented it so yeah..

If its as simple as manually entering the lines into the config, let me know and I can do that for myself and you can just push that into the next version for later..

Thanks Asie

**Comment by asiekierka** [comment]
The robots will get a lot better in 6.4.0. What exactly is your issue with them?

**Comment by aridhol** [comment]
Well I will admit I am a bit nit-picky so I wouldn't say my reasons are very good.. lol. But its basically, why do they have to be?

Anyhow for me, its a combo of entity lag and I find it a little too easy, I like people to have to do things for themselves :P

**Comment by asiekierka** [comment]
BC robots are both threaded and not exactly trivial to use. But fiiiiiiine.

**Comment by asiekierka** [comment]
(This will be fixed in BC 7.0.1 with the advent of the modularity system, since the asker here clearly wants to disable all robots.)
