### ISSUE TITLE
Crash after setting Robot Go Station if no redstone signal 

### ISSUE THREAD

**Issue by 3TUSK** [BuildCraft/BuildCraft#2486]
I am using 1.7.10, Buildcraft & BCCompat 6.4.0, Forge 10.13.2.1291(recommend)
When a butcher robot goes away with a diamond sword, I wanted to call it back, but when I set Go station if redstone off in AND emerald gate (no chip add-on), game crashed immediately. Then this save will be unable to load with a crash. Previously I used a Awaken Ichorium Sword from Thaumic Tinkerer, them I got the same crash report as well. (Note. Thaumcraft 4.2.3.5, Thaumic Tinkerer 1.7.10 2.5-439)
I have tried using a pump robot to pump some oil, and after robot went away I set Robot Go station if no redstone, got crash again.
All tests above are using AND emerald gate with no upgrade and a cobblestone structure pipe, also using TE 4.0.0RC1-119, CoFH 3.0.0RC1-181.

Because the report is a little strange and unusual, and all crash report are almost the same (I mean, the main reason of these crashes are the same, that is, java.lang.AbstractMethodError: buildcraft.transport.TileGenericPipeCompat.getWorldObj()Lnet/minecraft/world/World;) I took this issue.
One of the four crash-reports is here: http://pastebin.com/pY1zKii5

Sorry for my English, and I hope I can get reply soon.

**Comment by asiekierka** [comment]
Try redownloading BuildCraftCompat.

**Comment by 3TUSK** [comment]
I did re-download, but Same crash again, I am sorry but that is fact.
Crash-report: http://pastebin.com/hyNzk4EP
Also, it should be noticed that this time I even didn't place a robot on docking station. Crash seems to happen when you have a gate which has "Robot go station when balabala", but other function (e.g. active, filter, request/provide item) seems work well.
Also, I bet that #2487 is talking about the exactly same thing as mine. I will keep testing until the final answer.
Note, this time I use normal cobblestone item pipe with a vanilla chest, in a new generated world.

**Comment by Lightcraft45** [comment]
I have the same problem.

**Comment by Nhalkir** [comment]
@3TUSK that is the same problem I'm having in #2487 . Everything else seems to work except that "Robot go to station". I've also generated a ton of new world and tested on a ton of pipes. I've found the same result on pretty much all of them. Also I've tested with and without chest.
