### ISSUE TITLE
Crash after setting Robot Go To Station with no robot on station

### ISSUE THREAD

**Issue by Nhalkir** [BuildCraft/BuildCraft#2487]
I've tried this on both buildcraft versions with multiple mod combinations [compat / no compat]. The only other mod I have installed is NEI and the problem is easily replicable. Minecraft says something about a ticking entity, but I can provide full logs if needed. This problem basically cripples all robot functionality in my minecraft.

**Comment by hea3ven** [comment]
Duplicate of #2486
