### ISSUE TITLE
stripe bot things leather is an egg

### ISSUE THREAD

**Issue by AEnterprise** [BuildCraft/BuildCraft#2491]
it looks like stripe bots think they can throw leather like eggs
![2015-02-25_12 04 22](https://cloud.githubusercontent.com/assets/5206666/6369456/dcb23642-bce6-11e4-9d72-d17191c87a00.png)

**Comment by hea3ven** [comment]
The stripe bot will take any item you give him and will try to handle it. Use the new filter tool gate action to limit the items he can pick up.

**Comment by AEnterprise** [comment]
ah, i thought he would only use items it can use, also how do i get the bot to stop trying to use it?

**Comment by hea3ven** [comment]
For now, the only way is breaking the station and replacing it.

**Comment by AEnterprise** [comment]
alright

**Comment by asiekierka** [comment]
com.github.NotAnIssueException

**Comment by AEnterprise** [comment]
hmm, not realy an issue but would it be possible to add an action to make the bot drop the item or have it drop it when you hit it with a wrench?
