### ISSUE TITLE
Buildcraft 6.4 Beta Energy line overloaded

### ISSUE THREAD

**Issue by kremsy** [BuildCraft/BuildCraft#2495]
I noticed a bug that some energy lines we have from some combustion engine to quarrys always get overlaoded, but there are only 8 combustion engines on the golden energy pipe so it should be far away from getting overloaded.

**Comment by asiekierka** [comment]
Fixed in 6.4.1 with https://github.com/BuildCraft/BuildCraft/commit/dcccad0658d8f0d1e3d2169558f4f57d13c259f7

**Comment by kremsy** [comment]
Do you know when 6.4.1 will get released?
