### ISSUE TITLE
Maven is not updated, and that makes everything more annoying with forge.

### ISSUE THREAD

**Issue by da3dsoul** [BuildCraft/BuildCraft#2497]
![image](https://cloud.githubusercontent.com/assets/5205810/6388485/6fcf4f92-bd68-11e4-8704-a58cac64e374.png)

**Comment by Thog** [comment]
Can we see your build.gradle? Also, we need more logs, that is not enought so restart it with --debug and send your logs.

**Comment by da3dsoul** [comment]
build.gradle
http://pastebin.com/HZvtUizR

I'm very familiar with gradle and forge, if you are saying it works for you for BC6.4.0:dev, then I'll close this now and figure it out.

**Comment by Thog** [comment]
I think you can try with this repository
https://github.com/AEnterprise/Buildcraft-Additions/blob/multiblockRefinery/build.gradle#L89-L92

**Comment by da3dsoul** [comment]
Thanks I'll try it. It works if I specify 6.3.3:dev. Last time I tried and it didn't work, it was because asie didn't update the maven.

**Comment by da3dsoul** [comment]
Nope it still gives a 403 forbidden error on the maven.

**Comment by asiekierka** [comment]
We cannot control the Maven. I don't even know where the Jenkins is hosted!

6.4.0 was not uploaded intentionally, as it was a beta release and the API was not finalized - depending on it would be a very bad idea.

**Comment by da3dsoul** [comment]
Ah ok thanks. I was wondering. If it was intentional, then all is good.

**Comment by AEnterprise** [comment]
@da3dsoul we did update BCA to use BC 6.4.0 by using ivy for now, we know the api will change in the future but we did this to be able to test with the latest BC and make sure it's compatible

https://github.com/BCA-Team/Buildcraft-Additions/commit/4a26f56212743fae705712289d64cb2ac977e37c
