### ISSUE TITLE
REQUEST: New Pipes - Chunkloading Pipes

### ISSUE THREAD

**Issue by kremsy** [BuildCraft/BuildCraft#2498]
One of the most annoying things in buildcraft is if you make a line over 300 blocks or something from a quarry to your home and than after some minutes the things just don't appear. How about making an additional craftable form of pipes which are chunkloading. For example a Chunkloading Cobblestone Pipe. Make them quite expensive like 2 diamonds and the type of the pipe you wan't to make chunkloading.

This would be soooo awesome!!!!!

**Comment by da3dsoul** [comment]
I'm fairly certain this has been requested before and rejected by spacetoad and done by someone else  in an addon.

**Comment by asiekierka** [comment]
No.

The plan is to let you control the Stripes Pipe output direction with gates, and then to let you attach pipe wire with them.

**Comment by kremsy** [comment]
I have no clue what your answer should have todo with my request @asiekierka 
@da3dsoul Thanks I checked out the modes, but still I would prefer a Method without using Teleport pipes or something, I want to use just normal pipes over higher distances.

**Comment by asiekierka** [comment]
@kremsy - this will let stripes pipes place chunkloaders next to themselves

**Comment by da3dsoul** [comment]
Oh, I've never thought of that asie. Clever, dynamic chunkloading for horizontal drills. Not by any means easy to set up, though.

**Comment by kremsy** [comment]
Interesting, I don't understand it yet, is there always a chunkloaded at the end of a stripe pipe automatically for the block after it?

I looked into the Modpack Additional Pipes, I think the chunkloader block there will solve my issues :). Thanks for your help!

**Comment by kremsy** [comment]
Really weired, I installed the mod additional pipes, the quarry is about 300 blocks away from the destination, the items get sent at the source but don't appear at the exit. I tried them with just 5 blocks from eachother and it worked.

**Comment by kremsy** [comment]
More investigation showed that it works until im next to the quarry, when I move away from the quarry, after about 30seconds, no items appear at the receive point. Im wondering if i make something wrong, if it is a problem of the plugin or if chunkloading of buildcraft has a bug. @da3dsoul

**Comment by da3dsoul** [comment]
what version of buildcraft, there was a bug with quarry chunkoading.

**Comment by kremsy** [comment]
6.4 Beta

**Comment by da3dsoul** [comment]
Hmmm then i dunno

**Comment by kremsy** [comment]
Its weired, it definitly looks like a chunkloading Problem, but I have no clue what else could I test, it is a online server btw.

**Comment by kremsy** [comment]
Testet it now with two people, im at the end of the teleportation pipe, and the other one at the quarry, as long he stands at the quarry it works perfectly, but as soon he moves away from the quarry abt 100 blocks, teleportation stops. (Energy get transfered via energy teleportation.

@asiekierka can you check again if the quarry chunkloading itself works correctly?

If you want you can join us at the server that we can show you the issue (we updated to Buildcraft 6.4.1).

**Comment by kremsy** [comment]
We tried to place a chest directly at the quarry, and moved away when we came back just half an stack of cobblestone was in there, so there is defintily a bug with chunkloading.
