### ISSUE TITLE
Crash when setting gate action

### ISSUE THREAD

**Issue by Sp3rw3r** [BuildCraft/BuildCraft#2499]
Game crashed when I was cycling through gate actions in a gate gui.  It was an emerald gate next to a docking station on a pipe connected to a chest. There was no robot on assigned to the station.

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 26-2-15 10:43
Description: Ticking block entity

java.lang.AbstractMethodError: buildcraft.transport.TileGenericPipeCompat.getWorldObj()Lnet/minecraft/world/World;
	at buildcraft.robots.statements.ActionRobotGotoStation.actionActivate(ActionRobotGotoStation.java:55)
	at buildcraft.transport.Gate.resolveActions(Gate.java:483)
	at buildcraft.transport.Pipe.updateEntity(Pipe.java:156)
	at buildcraft.transport.TileGenericPipe.func_145845_h(TileGenericPipe.java:385)
	at buildcraft.transport.TileGenericPipeCompat.func_145845_h(TileGenericPipeCompat.java:85)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at buildcraft.robots.statements.ActionRobotGotoStation.actionActivate(ActionRobotGotoStation.java:55)
	at buildcraft.transport.Gate.resolveActions(Gate.java:483)
	at buildcraft.transport.Pipe.updateEntity(Pipe.java:156)
	at buildcraft.transport.TileGenericPipe.func_145845_h(TileGenericPipe.java:385)
	at buildcraft.transport.TileGenericPipeCompat.func_145845_h(TileGenericPipeCompat.java:85)

-- Block entity being ticked --
Details:
	Name: net.minecraft.src.buildcraft.transport.GenericPipe // buildcraft.transport.TileGenericPipeCompat
	Block type: ID #167 (tile.pipeBlock // buildcraft.transport.BlockGenericPipeCompat)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-207,65,138), Chunk: (at 1,4,10 in -13,8; contains blocks -208,0,128 to -193,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #167 (tile.pipeBlock // buildcraft.transport.BlockGenericPipeCompat)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Sp3rw3r'/5040, l='New World', x=-206,90, y=66,48, z=140,49]]
	Chunk stats: ServerChunkCache: 290 Drop: 0
	Level seed: -3460108213816118718
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-176,64,148), Chunk: (at 0,4,4 in -11,9; contains blocks -176,0,144 to -161,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 4348 game time, 4348 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 128787 (now: false), thunder time: 150335 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 103339696 bytes (98 MB) / 390594560 bytes (372 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 10 mods loaded, 10 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Core{6.4.0} [BuildCraft] (buildcraft-6.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Transport{6.4.0} [BC Transport] (buildcraft-6.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Silicon{6.4.0} [BC Silicon] (buildcraft-6.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Builders{6.4.0} [BC Builders] (buildcraft-6.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Energy{6.4.0} [BC Energy] (buildcraft-6.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Factory{6.4.0} [BC Factory] (buildcraft-6.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Compat{6.4.0} [BuildCraft Compat] (buildcraft-compat-6.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Sp3rw3r'/5040, l='New World', x=-206,90, y=66,48, z=140,49]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by asiekierka** [comment]
Duplicate; fixed in 6.4.1
