### ISSUE TITLE
Quarrys don't destroy/collect chest in Minecart in Mineshaft

### ISSUE THREAD

**Issue by kremsy** [BuildCraft/BuildCraft#2500]
Would be cool if quarrys could destroy chest from mineshafts and collect their items as they get just lost otherwise, the minecart with the chest is just standing there and not getting destroyed by the quarry (Tested only under water). It generally would be good that if they destroy a chest they get what is in there.

**Comment by asiekierka** [comment]
Chest blocks are fixed in 6.4.0+. We do not plan to handle minecarts (for now).

**Comment by kremsy** [comment]
Thank you!

That means if a chest is in a minecart they don't get handled by the quarry? It would be cool if that could be managed in the future! 

And the items which are in the normal chests get transfered out of the quarry with the fix?

**Comment by SandGrainOne** [comment]
A minecart is an Entity and not a TileEntity like chests.

Entities will probably drop down and end up at the bottom of the quarry. At least those entities that do not despawn. Like minecarts.
