### ISSUE TITLE
[6.4] Combustion engine not recognized as tank from front

### ISSUE THREAD

**Issue by roc13x** [BuildCraft/BuildCraft#2502]
If there is a gate at the front side of a combustion engine (the colored side), there are no available triggers for fluid tanks, such as Tank Full, Tank Empty, etc.
Any other side and they are available.

It's caused by TileEngineIron.java:396

**Comment by asiekierka** [comment]
It's a not-fully-avoidable side effect of another bugfix. Might look into it, but no promises!

**Comment by roc13x** [comment]
No problem, thanks for taking note of it. Might I ask what the original bugfix was?

**Comment by asiekierka** [comment]
@roc13x: We fixed being able to pump liquid from the colored side, which was... kind of silly.
