### ISSUE TITLE
Buildcraft 6.4.1 Energy Bug

### ISSUE THREAD

**Issue by kremsy** [BuildCraft/BuildCraft#2504]
Have a weired energybug since the 6.4.1 update:

http://www.pictures.paragon-esports.com/upload2/energybug.png

The right combustion engines are running as well, but the energy does not go into the pipe.

Probably related to the fix at:
https://github.com/BuildCraft/BuildCraft/issues/2495

**Comment by asiekierka** [comment]
Maybe you don't need that much energy?

**Comment by kremsy** [comment]
Well, at the end of the powerline there are three really big quarrys, would wonder me if they don't need that energy

**Comment by asiekierka** [comment]
@kremsy - Odd. Calling @CovertJaguar as most of the current energy code is his

**Comment by kremsy** [comment]
But im quite sure the bug wasn't existing in 6.4.0, except it got not noticed because of the overload bug, but energy from both, left and right got supplied to the quarries.

**Comment by asiekierka** [comment]
@kremsy - Try placing all the kinesis pipes again, possibly in creative mode. I have some suspicions....

**Comment by asiekierka** [comment]
@kremsy - Check again in 6.4.0.

**Comment by kremsy** [comment]
Will do.

**Comment by kremsy** [comment]
Will take a while because i need to replace the quarrys first, because they got finished since yesterday, what was the maximum energy a quarry can take before not everything would go in the pipe?

**Comment by kremsy** [comment]
But I could make one screenshot in 6.4.0, will try the same instantly in 6.4.1 and see if there is a difference.

**Comment by asiekierka** [comment]
Are you sure the energy is not going into the pipe? (Try doing two separate measurements with a TE Energy Cell or EIO Capacitor Bank)

**Comment by kremsy** [comment]
I am sure as the combustion engine overheated and all Stirling engines exploded.

**Comment by asiekierka** [comment]
@kremsy - Can you reproduce it in a minimal environment? One of us tried and can't -> http://i.gyazo.com/af78a07e16db8e3bc5e9454511fe295d.png http://i.gyazo.com/47bb6bbd2307c297373a1a8f5e8e0da5.png

**Comment by kremsy** [comment]
I can try but dunno if I can manage it, maybe you could join our server for a sec and check it out yourself.

**Comment by kremsy** [comment]
Weired, I placed the block again and it works now, but its bit random, I will inform you as soon the same problem is again there.

**Comment by kremsy** [comment]
Same bug, just another a bit earlier: http://pictures.esc-clan.net/upload2/kopie_bcbug1.png you can see in front the 4 combustion engines showed from before, just two are producing energy, the other two tending to overheat.

**Comment by kremsy** [comment]
I connected a energy cell, and full electricity flow through everything, everything works perfect. But it wonders me that these three quarrys dont need more energy than. As well I am wondering if there is a way and make the power requested pipe signal to off if there is no power from this part requested (for example the right side before).

**Comment by CovertJaguar** [comment]
@kremsy Power Requested Gate Trigger is based on the internal storage capacity of the Wooden Pipe. If its low, the engines will turn on until the Wooden Pipe fills up. The Wooden Pipe then uses that power in its internal storage to feed the pipe network.

**Comment by kremsy** [comment]
@asiekierka At least there must be a bug with the quarrys than, that they dont consume the maximum they could consume.

**Comment by kremsy** [comment]
@CovertJaguar If you have a gate directly on the wooden pipe -> on energy requested -> redstone signal, than they should never explode, shouldnt they? They exploded multiple times for me already in different szenarios.

**Comment by CovertJaguar** [comment]
I thought explosions were gone?

**Comment by RagaRBM** [comment]
I thought explosions were gone too.

**Comment by laz2727** [comment]
> (Explosions can be restored via config)


2015-03-02 17:44 GMT+06:00 RagaRBM <notifications@github.com>:

**Comment by kremsy** [comment]
Nope I just solved it for myself with some other mechanisms like a energy cell before the quarries and other stuff, but basically if the quarries run, they request power and as the Screenshot showed before the power from the right side is not getting into the system, on the right side there are also these ten Stirling engines, and if it runs like on the Screenshot, the Stirling Engines are exploding. They have a gate exactly on the Wooden pipes On energy Requested -> Redstone Signal

**Comment by laz2727** [comment]
The only thing i can see exploding with explosions off is an item pipe. You
most likely have explosions enabled in config.

2015-03-02 17:48 GMT+06:00 Lukas Kremsmayr <notifications@github.com>:

**Comment by kremsy** [comment]
What I mean as explosion is the overheating of the Stirling Engines, that they get black.

**Comment by laz2727** [comment]
They can still overheat if they make more energy than requested in that
setup.

2015-03-02 17:53 GMT+06:00 Lukas Kremsmayr <notifications@github.com>:
