### ISSUE TITLE
641 stable crashes to desktop

### ISSUE THREAD

**Issue by tatjam** [BuildCraft/BuildCraft#2505]
Hi there:

Although 6.4.0 beta was working like a charm, stable 6.4.1 crashes MC while loading. Only client crash report generated:

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 26/02/15 23:27
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: programmingTable
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at magic.launcher.Launcher.main(SourceFile:214)
Caused by: java.lang.NoSuchFieldError: programmingTable
	at buildcraft.BuildCraftCore.loadConfiguration(BuildCraftCore.java:304)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4138702992 bytes (3946 MB) / 5187305472 bytes (4947 MB) up to 5187305472 bytes (4947 MB)
	JVM Flags: 3 total; -Xms5120m -Xmx5120m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_U_B5 131 mods loaded, 131 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	gasesCore{1.5.2} [Glenn's Gases Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	gasesFrameworkCore{1.0.5.1} [Gases Framework Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.4.90} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.90-universal.jar) Unloaded->Constructed->Pre-initialized
	PlayerAPI{1.2} [Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	SmartCore{1.0} [Smart Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FLabsBF{4.3} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.3.jar) Unloaded->Constructed->Pre-initialized
	FLabsBFCompat{3.1} [BF Compatibility] ([1.7.10]BFCompatV3.1.jar) Unloaded->Constructed->Pre-initialized
	CoFHCore{1.7.10R3.0.0RC2} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC2-195.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Core{6.4.1} [BuildCraft] (buildcraft-6.4.1.jar) Unloaded->Constructed->Errored
	BuildCraft|Transport{6.4.1} [BC Transport] (buildcraft-6.4.1.jar) Unloaded->Constructed->Errored
	BuildCraft|Silicon{6.4.1} [BC Silicon] (buildcraft-6.4.1.jar) Unloaded->Constructed->Errored
	BuildCraft|Factory{6.4.1} [BC Factory] (buildcraft-6.4.1.jar) Unloaded->Constructed->Errored
	additionalpipes{3.4} [Additional Pipes] (additionalpipes-3.4.jar) Unloaded->Constructed->Pre-initialized
	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized
	Aquaculture{1.2.3} [Aquaculture] (Aquaculture-1.7.10-1.2.5.14.jar) Unloaded->Constructed->Pre-initialized
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
	ThermalFoundation{1.7.10R1.0.0RC3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC3-56.jar) Unloaded->Constructed->Pre-initialized
	ThermalExpansion{1.7.10R4.0.0RC2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0RC2-129.jar) Unloaded->Constructed->Pre-initialized
	BigReactors{0.4.2A2} [Big Reactors] (BigReactors-0.4.2A2.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Builders{6.4.1} [BC Builders] (buildcraft-6.4.1.jar) Unloaded->Constructed->Errored
	BuildCraft|Energy{6.4.1} [BC Energy] (buildcraft-6.4.1.jar) Unloaded->Constructed->Errored
	BuildCraft|Compat{6.4.0} [BuildCraft Compat] (buildcraft-compat-6.4.0.jar) Unloaded->Constructed->Errored
	bcadditions{2.0.1} [Buildcraft Additions] (BuildcraftAdditions-1.7.10-2.0.1.jar) Unloaded->Constructed->Pre-initialized
	ChickenChunks{1.3.4.17} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.17-universal.jar) Unloaded->Constructed->Pre-initialized
	TwilightForest{2.3.3} [The Twilight Forest] (twilightforest-1.7.10-2.3.3.jar) Unloaded->Constructed->Pre-initialized
	ForgeMultipart{1.1.1.323} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.323-universal.jar) Unloaded->Constructed->Pre-initialized
	chisel{2.3.7.34} [Chisel 2] (Chisel2-2.3.7.34.jar) Unloaded->Constructed->Pre-initialized
	ChiselFacades{1.7.10-2.10-cricket} [Chisel Facades] (ChiselFacades-1.7.10-2.10-cricket.jar) Unloaded->Constructed->Errored
	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) Unloaded->Constructed->Pre-initialized
	cookiecore{1.3.1} [Cookie Core] (CookieCore-1.7.10-1.3.1-5.jar) Unloaded->Constructed->Pre-initialized
	BuildMod{v1.0} [Build Mod] (coroutil-1.1.2 for MC v1.7.10.jar) Unloaded->Constructed->Pre-initialized
	CoroAI{v1.0} [CoroAI] (coroutil-1.1.2 for MC v1.7.10.jar) Unloaded->Constructed->Pre-initialized
	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.2 for MC v1.7.10.jar) Unloaded->Constructed->Pre-initialized
	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.2 for MC v1.7.10.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	Eln{46} [Electrical Age] (ElectricalAge_BETA-1.9_r46.jar) Unloaded->Constructed->Pre-initialized
	Enchiridion2{2.0c} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0c.jar) Unloaded->Constructed->Pre-initialized
	Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed->Pre-initialized
	enhancedportals{3.0.10} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.10.jar) Unloaded->Constructed->Pre-initialized
	enviromine{1.3.107} [EnviroMine] (EnviroMine-v1.3.107.jar) Unloaded->Constructed->Pre-initialized
	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded{1.7.10R2.8.0RC7} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	Waila{1.5.8} [Waila] (Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized
	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) Unloaded->Constructed->Pre-initialized
	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized
	flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) Unloaded->Constructed->Pre-initialized
	gasesFramework{1.0.6} [Gases Framework] (gasesFramework-1.0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	gases{1.5.2} [Glenn's Gases] (gases-1.5.2-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	gasesFrameworkWAILA{1.0.0} [Gases Framework WAILA plugin] (gasesFrameworkWAILA-1.0.0.jar) Unloaded->Constructed->Pre-initialized
	k4lib{1.7.10-0.1.18} [K4Lib] (k4lib-1.7.10-0.1.18-universal.jar) Unloaded->Constructed->Pre-initialized
	HydCraft{1.7.10-2.0.87} [Hydraulicraft] (HydCraft-1.7.10-2.0.87-universal.jar) Unloaded->Constructed->Pre-initialized
	IguanaTweaks{1.7.10-Beta-19} [Iguana Tweaks] (IguanaTweaks-1.7.10-Beta-19.jar) Unloaded->Constructed->Pre-initialized
	IGWMod{1.1.1-17} [In-Game wiki Mod] (IGW-Mod-1.7.10-1.1.1-17-universal.jar) Unloaded->Constructed->Pre-initialized
	Mariculture{1.7.10-1.2.4d} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4d.jar) Unloaded->Constructed->Pre-initialized
	MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4d.jar) Unloaded->Constructed->Pre-initialized
	radixcore{1.3.4} [RadixCore] (RadixCore-1.7.10-1.3.4-universal.jar) Unloaded->Constructed->Pre-initialized
	mca{4.1.5} [Minecraft Comes Alive] (MCA-1.7.10-4.1.5-universal.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC7} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC7} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC7} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC7} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC7} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC7} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC7} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC7} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC7} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC7} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MrTJPCoreMod{1.0.5.11} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.11-universal.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Core{4.5.13.65} [ProjectRed] (ProjectRed-1.7.10-4.5.13.65-Base.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Exploration{4.5.13.65} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.5.13.65-World.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC7} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC7} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC7} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC7} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC7} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC7} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC7} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC7} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC7} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized
	MoarPeripherals{1.7.10-1.7-1.52} [MoarPeripherals] (MoarPeripherals-1.7.10-1.7-1.52.jar) Unloaded->Constructed->Pre-initialized
	morechisels{@VERSION@} [More Chisels] (MoreChisels-1.7.10-1.0-17.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons{1.12.4.16} [NEI Addons] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|Botany{1.12.4.16} [NEI Addons: Botany] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|Forestry{1.12.4.16} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|CraftingTables{1.12.4.16} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|ExNihilo{1.12.4.16} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized
	neiintegration{1.0.7} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.7.jar) Unloaded->Constructed->Pre-initialized
	NetherOres{1.7.10R2.3.0RC4} [Nether Ores] (NetherOres-[1.7.10]2.3.0RC4-4.jar) Unloaded->Constructed->Pre-initialized
	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10g.jar) Unloaded->Constructed->Pre-initialized
	PneumaticCraft{1.6.2-64} [PneumaticCraft] (PneumaticCraft-1.7.10-1.6.2-64-universal.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Transmission{4.5.13.65} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.13.65-Integration.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Transportation{4.5.13.65} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.5.13.65-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Compatibility{4.5.13.65} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.5.13.65-Compat.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Integration{4.5.13.65} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.13.65-Integration.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Illumination{4.5.13.65} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.13.65-Lighting.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Expansion{4.5.13.65} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.5.13.65-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized
	RedstoneArsenal{1.7.10R1.1.0RC2} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0RC2-43.jar) Unloaded->Constructed->Pre-initialized
	SmartMoving{15.3} [Smart Moving] (SmartMoving-1.7.10-15.3.jar) Unloaded->Constructed->Pre-initialized
	SmartRender{2.1} [Smart Render] (SmartRender-1.7.10-2.1.jar) Unloaded->Constructed->Pre-initialized
	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) Unloaded->Constructed->Pre-initialized
	SpiceOfLife{1.2.3} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.2.3.jar) Unloaded->Constructed->Pre-initialized
	ThermalDynamics{1.7.10R1.0.0RC2} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0RC2-77.jar) Unloaded->Constructed->Pre-initialized
	TSteelworks{1.7.10-1.1.0} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.0-6.jar) Unloaded->Constructed->Pre-initialized
	TiCTooltips{1.2.3} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.3.jar) Unloaded->Constructed->Pre-initialized
	TMechworks{0.2.13.96} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.13.96.jar) Unloaded->Constructed->Pre-initialized
	AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) Unloaded->Constructed->Pre-initialized
	weather2{v2.3.6} [weather2] (Weather-2.3.7.jar) Unloaded->Constructed->Pre-initialized
	eureka{2.2} [Eureka] (Eureka-1.7.10-2.2.jar) Unloaded->Constructed->Pre-initialized
	McMultipart{1.1.1.323} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.323-universal.jar) Unloaded->Constructed->Pre-initialized
	aobd{2.4.0} [Another One Bites The Dust] (AOBD-2.4.0.jar) Unloaded->Constructed->Pre-initialized
	HungerOverhaul{1.7.10-beta.5.jenkins47} [Hunger Overhaul] (HungerOverhaul-1.7.10-beta.5.jar) Unloaded->Constructed->Pre-initialized
	IguanaTweaksTConstruct{1.7.10-2.1.2.101} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.2.jar) Unloaded->Constructed->Pre-initialized
	ForgeMicroblock{1.1.1.323} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.323-universal.jar) Unloaded->Constructed->Pre-initialized
	CoFHCore: -[1.7.10]3.0.0RC2-195
	ThermalFoundation: -[1.7.10]1.0.0RC3-56
	ThermalExpansion: -[1.7.10]4.0.0RC2-129
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	MineFactoryReloaded: -[1.7.10]2.8.0RC7-71
	TConstruct Environment: Environment healthy.
	NetherOres: Lacking version information.
	RedstoneArsenal: Lacking version information.
	ThermalDynamics: -[1.7.10]1.0.0RC2-77

**Comment by vital74** [comment]
Buildcraftaddition is conflicting, removing it solves the issue. wait for an update on their side

**Comment by tatjam** [comment]
Many thanks vital. Cheers!

**Comment by AEnterprise** [comment]
@vital74 and @tatjam another way of fixing it is by opening the BCA jar and removing the BC folder
