### ISSUE TITLE
6.4.1 cause lag

### ISSUE THREAD

**Issue by Yg0R2** [BuildCraft/BuildCraft#2506]
Hi there,

I just updated to 6.4.1 and everything in the game lagged. The memory usage increased radically. 
When I tried to open the chest, it toke almost 2-5s to open it.
When I braked a block, it appeared on the original place, and I had to brake it about 5 times.

As I saw the GC worked really hard. Under two second the memory usage reached the 60% and immediately went back to 20% continuously, while I did nothing in an almost clear world. I have a BigReactor and a Quarry (3x3 chunk) and a Builder (3x3 chunk) on this world.
I use these Java args: "-Xmx6G -Xms512m -XX:MaxPermSize=2048m".

I went back to 6.3.6 and it is worked well for me. I haven't tried 6.4 releases before, because I just realized, there is a new version of BuildCraft.

I use a few mods, all of them quite up to date and didn't get any error with 6.3.6.
Here are my modes:
```
mcp(Minecraft Coder Pack:9.05): minecraft.jar
FML(Forge Mod Loader:7.10.85.1291): forge-1.7.10-10.13.2.1291.jar (e3c3d50c7c986df74c645c0ac54639741c90a557)
Forge(Minecraft Forge:10.13.2.1291): forge-1.7.10-10.13.2.1291.jar
CodeChickenCore(CodeChicken Core:1.0.4.35): minecraft.jar
<CoFH ASM>(CoFH ASM Data Initialization:000): minecraft.jar
NotEnoughItems(Not Enough Items:1.0.4.83): NotEnoughItems-1.7.10-1.0.4.83-universal.jar
CoFHCore(CoFH Core:1.7.10R3.0.0RC2): CoFHCore-[1.7.10]3.0.0RC2-195.jar
BuildCraft|Core(BuildCraft:6.4.1): buildcraft-6.4.1.jar
BuildCraft|Transport(BC Transport:6.4.1): buildcraft-6.4.1.jar
BuildCraft|Silicon(BC Silicon:6.4.1): buildcraft-6.4.1.jar
BuildCraft|Builders(BC Builders:6.4.1): buildcraft-6.4.1.jar
BuildCraft|Energy(BC Energy:6.4.1): buildcraft-6.4.1.jar
BuildCraft|Factory(BC Factory:6.4.1): buildcraft-6.4.1.jar
Additional-Buildcraft-Objects(Additional Buildcraft Objects:MC1.7.10-BC6.3release2.1): ABO-MC1.7.10-BC6.3-release2.1.jar
ThermalFoundation(Thermal Foundation:1.7.10R1.0.0RC3): ThermalFoundation-[1.7.10]1.0.0RC3-56.jar
ThermalExpansion(Thermal Expansion:1.7.10R4.0.0RC2): ThermalExpansion-[1.7.10]4.0.0RC2-129.jar
BigReactors(Big Reactors:0.4.2A2): BigReactors-0.4.2A2.jar
IC2(IndustrialCraft 2:2.2.684-experimental): industrialcraft-2-2.2.684-experimental.jar (de041f9f6187debbc77034a344134053277aa3b0)
Turbo(Minecraft Turbo:1.2.0): Turbo-1.7.10-1.2.0.jar
BioMaterials(Bio Materials:4.1.0): BioMaterials-1.7.10-4.1.1.jar
BiomesOPlenty(Biomes O' Plenty:2.0.2): BiomesOPlenty-1.7.10-2.1.0.144-universal.jar
ChickenChunks(ChickenChunks:1.3.4.17): ChickenChunks-1.7.10-1.3.4.17-universal.jar
craftguide(CraftGuide:1.6.8.1): CraftGuide-1.6.8.1.zip
EnderStorage(EnderStorage:1.4.5.27): EnderStorage-1.7.10-1.4.5.27-universal.jar
Forestry(Forestry for Minecraft:3.4.0.7): forestry_1.7.10-3.4.0.7.jar
GraviSuite(Graviation Suite:1.7.10-2.0.3): GraviSuite-1.7.10-2.0.3.jar
IronChest(Iron Chest:6.0.62.742): ironchest-1.7.10-6.0.62.742-universal.jar
LogisticsPipes(Logistics Pipes:0.8.3.104): logisticspipes-0.8.3.104.jar (4ab9c640e37baa2d4eca3354863a84d2c06bee42)
MineFactoryReloaded(MineFactory Reloaded:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatAppliedEnergistics(MFR Compat: Applied Energistics:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatAtum(MFR Compat: Atum:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatBackTools(MFR Compat: BackTools:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatBuildCraft(MFR Compat: BuildCraft:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatChococraft(MFR Compat: Chococraft:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatExtraBiomes(MFR Compat: ExtraBiomes:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatForestry(MFR Compat: Forestry:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatForgeMicroblock(MFR Compat: ForgeMicroblock:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatIC2(MFR Compat: IC2:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatMystcraft(MFR Compat: Mystcraft:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
ForgeMultipart(Forge Multipart:1.1.1.320): ForgeMultipart-1.7.10-1.1.1.320-universal.jar
MrTJPCoreMod(MrTJPCore:1.0.5.11): MrTJPCore-1.7.10-1.0.5.11-universal.jar
ProjRed|Core(ProjectRed:4.5.13.65): ProjectRed-1.7.10-4.5.13.65-Base.jar
ProjRed|Exploration(ProjectRed-Exploration:4.5.13.65): ProjectRed-1.7.10-4.5.13.65-World.jar
MineFactoryReloaded|CompatProjRed(MFR Compat ProjectRed:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatRailcraft(MFR Compat: Railcraft:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatRP2(MFR Compat: RP2:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatSufficientBiomes(MFR Compat: Sufficient Biomes:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatThaumcraft(MFR Compat: Thaumcraft:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatThermalExpansion(MFR Compat: Thermal Expansion:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatTConstruct(MFR Compat: Tinkers' Construct:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatTwilightForest(MFR Compat: TwilightForest:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineFactoryReloaded|CompatVanilla(MFR Compat: Vanilla:1.7.10R2.8.0RC7): MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
NetherOres(Nether Ores:1.7.10R2.3.0RC4): NetherOres-[1.7.10]2.3.0RC4-4.jar
clayspawn(Pam's Clay Spawn:1.7.2a): Pam's Clay Spawn 1.7.2a.zip
desertcraft(Pam's DesertCraft:1.7.2b): Pam's DesertCraft 1.7.10a.zip
getalltheseeds(Pam's Get all the Seeds!:1.7.2a): Pam's Get all the Seeds 1.7.2a.zip
harvestcraft(Pam's HarvestCraft:1.7.2d): Pam's HarvestCraft 1.7.10a.zip
mobdropcrops(Pam's Mob Drop Crops:1.7.2a): Pam's Mob Drop Crops 1.7.10a.zip
randomplants(Pam's RandomPlants:1.7.2a): Pam's Random Pants 1.7.2a.zip
weeeflowers(Pam's Weee! Flowers:1.7.2b): Pam's WeeeFlowers 1.7.2b.zip
ProjRed|Transmission(ProjectRed-Transmission:4.5.13.65): ProjectRed-1.7.10-4.5.13.65-Integration.jar
ProjRed|Transportation(ProjectRed-Transportation:4.5.13.65): ProjectRed-1.7.10-4.5.13.65-Mechanical_beta.jar
ProjRed|Compatibility(ProjectRed-Compatibility:4.5.13.65): ProjectRed-1.7.10-4.5.13.65-Compat.jar
ProjRed|Integration(ProjectRed-Integration:4.5.13.65): ProjectRed-1.7.10-4.5.13.65-Integration.jar
ProjRed|Illumination(ProjectRed-Illumination:4.5.13.65): ProjectRed-1.7.10-4.5.13.65-Lighting.jar
ProjRed|Expansion(ProjectRed-Expansion:4.5.13.65): ProjectRed-1.7.10-4.5.13.65-Mechanical_beta.jar
ReiMinimap(Rei's Minimap:1.7.10): ReiMinimap-1.7.10-3.6.jar
ThermalDynamics(Thermal Dynamics:1.7.10R1.0.0RC2): ThermalDynamics-[1.7.10]1.0.0RC2-77.jar
Translocator(Translocator:1.1.1.14): Translocator-1.7.10-1.1.1.14-universal.jar
WR-CBE|Core(WR-CBE Core:1.4.1.9): WR-CBE-1.7.10-1.4.1.9-universal.jar
WR-CBE|Addons(WR-CBE Addons:1.4.1.9): WR-CBE-1.7.10-1.4.1.9-universal.jar
WR-CBE|Logic(WR-CBE Logic:1.4.1.9): WR-CBE-1.7.10-1.4.1.9-universal.jar
McMultipart(Minecraft Multipart Plugin:1.1.1.320): ForgeMultipart-1.7.10-1.1.1.320-universal.jar
ForgeMicroblock(Forge Microblocks:1.1.1.320): ForgeMultipart-1.7.10-1.1.1.320-universal.jar
```

I really love your mod!
Thank you,
Yg0R2

**Comment by asiekierka** [comment]
@Yg0R2 Try with these versions so we can figure out where we went wrong:

- 6.4.0: http://www.mod-buildcraft.com/releases/BuildCraft/6.4.0/buildcraft-6.4.0.jar
- 6.3.7: http://www.mod-buildcraft.com/releases/BuildCraft/6.3.7/buildcraft-6.3.7.jar

JUST BACKUP YOUR WORLD FIRST!

**Comment by Yg0R2** [comment]
@asiekierka I tried the two mentioned versions and it worked everything well.
I tried the 6.4.1 again, and I got the same issue.

Sorry for the late response :)

**Comment by asiekierka** [comment]
@Yg0R2 - Try turning off the Builder and report back.

**Comment by tiborkovacs** [comment]
Ok, here is my results:
 1. I broke the builder's block with 6.4.0 and restart the game with 6.4.1.
 2. Load the game, and everything works well.
 3. Add the builder to the same place (it receives power, because I didn't broke the RedNet Energy Cables)
  - The game works well.
 4. Add a blueprint to the builder
  - The same issue appears.

**Comment by Yg0R2** [comment]
Ok, here is my results:
 1. I broke the builder's block with 6.4.0 and restart the game with 6.4.1.
 2. Load the game, and everything works well.
 3. Add the builder to the same place (it receives power, because I didn't broke the RedNet Energy Cables)
  - The game works well.
 4. Add a blueprint to the builder
  - The same issue appears.

**Comment by asiekierka** [comment]
@Yg0R2 I think I know what caused this. I'll get you a fixed release tomorrow, hopefully.

**Comment by Yg0R2** [comment]
Thank you so much ;)

**Comment by psychofad** [comment]
just an fyi....filler is apparently also doing this on 6.4.1....causing players to time out from the server and causing server to freeze every so often (GC more than likely).  Not sure if this is tied to the same thing...but just in case!

**Comment by RagaRBM** [comment]
Might be similar to this too : http://mod-buildcraft.com/forums/index.php?board=3.0

**Comment by asiekierka** [comment]
Can you try and narrow down which version broke it? Re-check 6.2.6, 6.3.1, etc.

**Comment by psychofad** [comment]
I will try and narrow it down...so far I have gone all the way back to 6.3.1 and still having freezing issues.  It's weird tho...it only happens when I look at it.  If I look at the filler the server will overload and TPS goes to 0.01, but if I look away for a while then the server will recover and TPS goes back up to 20ish.  The filler will continue to work as normal as long as I don't look at it...server is fine....look at the block and blam server almost screeches to a halt.  I will continue to try and downgrade until I can find a version that doesn't get all touchy when you look at the blocks.  Not sure how far back I can go without my pack crashing though due to API changes that occurred in the later builds.

**Comment by psychofad** [comment]
Ok.. well... I tried everything going back to 6.2.6 and this was still happening.  So on a hunch I decided to try uninstalling the various WAILA addons I had and guess what...WAWLA was the culprit.  As I had this installed on both server and client, I guess it was trying to determine if I had the correct tool to break it and instead it was grinding the server to a halt.  Unfortunate, but at least now I know where to actually report this issue and how to fix it in the meantime.  Sorry for wasting time on this issue tracker.  I will now go and create an issue on the WAWLA tracker.  :D

**Comment by psychofad** [comment]
https://github.com/Darkhax-Minecraft/WAWLA/issues/29

**Comment by asiekierka** [comment]
Funky. WAILA had the same issue and was in fact the reason behind the original issues to begin with!

**Comment by psychofad** [comment]
NBT OP please nerf! Thanks for your help!

**Comment by Yg0R2** [comment]
Ok, but I'm not using this WAILA mod, and the game is lagging when I use this version of BC.
Am I missed something?

**Comment by asiekierka** [comment]
@Yg0R2 - do the same steps as the previous person, that is check previous versions.

**Comment by Yg0R2** [comment]
I already did it, you asked me to do it.
And I confirmed that, only the latest version lags for my.

**Comment by asiekierka** [comment]
@Yg0R2 - very sorry, school is being very stressful this week and I just forget... I'll get you a build with what I think fixes it in a few hours

**Comment by Yg0R2** [comment]
It is ok, I understand that ;)
I just want a to be sure, the latest version of BC is stable and really good ;)
