### ISSUE TITLE
this doesnt seem right

### ISSUE THREAD

**Issue by Sailren** [BuildCraft/BuildCraft#2513]
http://abload.de/img/2015-02-28_12.18.5550uet.png

**Comment by iTitus** [comment]
Erm  okay?

**Comment by Sailren** [comment]
there you are, fixed it

**Comment by Sailren** [comment]
for some reasons the robot dont want to be crafted

**Comment by asiekierka** [comment]
@Sailren - you're not supposed to put the robot in there - to program the robot, use an integration table; the prog. table only programs the board

**Comment by Sailren** [comment]
ah, hehe

**Comment by Sailren** [comment]
what about this: http://abload.de/img/2015-02-28_12.23.36cquc3.png
