### ISSUE TITLE
Crash after placing a empty redstone board in input of Programming Table

### ISSUE THREAD

**Issue by 3TUSK** [BuildCraft/BuildCraft#2517]
I am testing robots system and I found there is no empty redstone board neither in Creative Tab nor NEI, then I use /give to get an empty one. However, when I placing it in the Programming Table, game crashed immediately.

I did test for 4 times, first time is using many other mods, 2nd is without NEI, 3rd and 4th is only BC and BCCompact, and all crash has the same reason: java.lang.NoSuchMethodError: java.util.List.sort(Ljava/util/Comparator;)V

Using Minecraft 1.7.10, Buildcraft 6.4.1, BCCompat 6.4.0, Forge 10.13.2.1291(recommended)

Last crash-report (using BC and BCCompat only) is here: http://pastebin.com/4Fx2tf5J

I checked all closed issues, but mine is unlikely to be a duplicate one. Hope I can get reply soon, whatever the result is.

**Comment by hea3ven** [comment]
@asiekierka does [this](https://github.com/BuildCraft/BuildCraft/blob/6.4.x/common/buildcraft/silicon/boards/BoardProgrammingRecipe.java#L41) line compile for you?, I tried compiling as 1.8 and still wouldn't compile. What java are you using that has List<>.sort?

**Comment by 3TUSK** [comment]
Well, FYI: I am using Java8 Update 31.

**Comment by asiekierka** [comment]
@hea3ven - I might have accidentally used a Java 7 function. Whoops.
