### ISSUE TITLE
Pump robots entering endless exception coma

### ISSUE THREAD

**Issue by SolraBizna** [BuildCraft/BuildCraft#2518]
Immediately after placing a pump robot in a creative world for testing purposes, I get this:
https://gist.github.com/SolraBizna/ffc4ebbd1fedd0abfbba

I'm using Minecraft 1.7.10, Buildcraft 6.4.1, and Forge 1291. I have no other mods installed.

Steps to reproduce:
- Create new Superflat world. (I used the preset `2;64x7;1;`)
- Place a small oil pool. (I made a 5x5 one at the same Y-level as the pipes.)
- Place an emerald kinesis pipe and gold kinesis pipe in a line.
- Place a creative engine on the end of the emerald kinesis pipe. Shift-rightclick it with a wrench until its output is 1280RF/t. Place a redstone torch on it to make it always active.
- On the gold kinesis pipes, place one docking station, one quartz AND gate, and a Refinery.
- Configure the gate like so: on redstone signal off, filter (oil bucket); on space for fluid (oil bucket), accept fluids (oil bucket)
- Place a (fully-charged to work around #2509) Pump Robot on the docking station.

Expected result: Pump Robot will methodically pump out the oil pool and transport it to the Refinery.
Actual result: Pump Robot throws an exception and goes to sleep, then begins throwing exceptions every second or so until I remove it from the world.

Additional notes: Removing the robot _after_ it has thrown an exception, shutting down the world (and Minecraft), _then_ reloading the world and replacing the robot (and docking station) results in a pump robot behaving as expected. If the exception-throwing robot is still in the world when it's saved, or if Minecraft is not closed entirely in between, a subsequent load does _not_ fix the problem.

**Comment by asiekierka** [comment]
Nice template! I see multiple potential bugs in there - hmm...

**Comment by asiekierka** [comment]
@hea3ven - calling you for this one!
