### ISSUE TITLE
Do loops cause problems?

### ISSUE THREAD

**Issue by RagaRBM** [BuildCraft/BuildCraft#2521]
http://mod-buildcraft.com/forums/index.php?topic=3538.0
Not necessarily a bug in a way as perhaps it is intended. But I think it would be nice to minimize strange loop oddities.

**Comment by laz2727** [comment]
:D
I use them as a really low-tech energy storage.

2015-03-02 17:39 GMT+06:00 RagaRBM <notifications@github.com>:

**Comment by Kubuxu** [comment]
@asiekierka I think energy system you rolled back is allowing for energy looping.

**Comment by asiekierka** [comment]
Inviting @CovertJaguar 

@Kubuxu - is that a bad thing?

**Comment by Kubuxu** [comment]
Back in the day it was mean of storying power now it can cause power voiding.

**Comment by asiekierka** [comment]
@Kubuxu - the algorithm, at this point, does not lose excess power, and the energy buffer in the pipe is /theoretically/ infinite - however, making overloaded power pipes explode in the same vein overloaded item pipes do (only destroys its own block) might be a good idea to prevent lag, overflows making energy go negative, etc.

**Comment by Kubuxu** [comment]
@asiekierka this way.you are breaking perfectly correct power systems that.are currently existing.

**Comment by Kubuxu** [comment]
And also IIRC energy loops were major reason for energy system rewrite back then.

**Comment by SandGrainOne** [comment]
How do we limit the flow of power through pipes with lower capacity? I thought the buffer size and power capacity was closely linked.

**Comment by asiekierka** [comment]
In general, I believe the "overload" rendering should be changed to reflect if a pipe is actually overloaded (that is, the internal power buffer is at its peak), and not whether it is used at full capacity (which is the normal thing for a pipe to do). What do you think?

**Comment by CovertJaguar** [comment]
The only downside to energy looping is that it reduces the total energy throughput through the looped section.

The cpu cost is identical for loops as non-loops.

**Comment by CovertJaguar** [comment]
The "overload" state exists as a simple feedback to let people know that things on the other side of the overloaded pipe are requesting more power than the pipe can provide.

Having it display the pipes "internal buffer" is really kind of pointless because the user gets no benefit from knowing that, its a transient state that has no impact on the operation of the network.

**Comment by asiekierka** [comment]
@CovertJaguar - isn't it already capped at the pipe's maximum RF/t transfer rate per side?

**Comment by CovertJaguar** [comment]
@asiekierka Is what capped? I don't understand the relevance of the question.

**Comment by AartBluestoke** [comment]
waht if the ability for a pipe to accept new energy was related to the
amount of energy already in it -- powerInflow
*((floor(3*maxStorage/currentStorage,1)
that way a power loop can be used with power up to a moderate level, then
after that it slowly stops accepting energy, without going near integer
overflow, but still buffering a few kilo-mj, and it would allow a sensible
buildup/release mechanism to spiky power draws distant from the main power
generators.

On Sun, Apr 12, 2015 at 3:15 PM, CovertJaguar <notifications@github.com>
wrote:

> @asiekierka <https://github.com/asiekierka> Is what capped? I don't
> understand the relevance of the question.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BuildCraft/BuildCraft/issues/2521#issuecomment-91993841>
> .
>



-- 
“Getting information off the Internet is like taking a drink from a fire
hydrant.”
*– Mitchell Kapor*
