### ISSUE TITLE
Blueprint not working with mod (Railcraft)

### ISSUE THREAD

**Issue by DarciofMountain** [BuildCraft/BuildCraft#2524]
First things first, I'm not a native English speaker so please bear with me.
I did just set up an architect table with a 7x7x7 area(also tried something really bigger) and recorded (at least tried) a 5x5x6 Steel tank. The thing is, the blueprint is actually empty, there's only the area dimensions recorded, no steel tank wall nor steel tank gauge nor valves. It's okay if I do write a template instead, but then I'll have to destroy some walls and add the valves all by myself.
Is this a bug? Am I doing something wrong, perhaps something about the configs?
Thanks in advance.

An unrelated note, I really love this mod. Thank you for keeping it.

**Comment by DarciofMountain** [comment]
Update:
I tried different blocks and mods:
Railcraft: Lead block - OK
Buildcraft: Pumps, Pipes and Builders - OK
Simple Ores: Tin and Copper blocks - OK
Simple Ores: Onyx Furnace - FAIL
Forestry: Apatite Blocks - OK
Forestry: Alveary Blocks - FAIL
Iron Chests: Everything - FAIL
Greg's Lighting: FloodLights - OK
Greg's Lighting: Carbide blah blah Lights - FAIL
Vanilla: Chests, Furnaces - OK

So far I think it is something to do with the interactive blocks...(Buildcraft and Vanilla seems ok)
Anything that got an inventory failed to work, Greg's light are the best example.
Multiblock Structures also failed, e.g. Railcraft's Tanks and Forestry's Alveary.

Hope this helps

**Comment by asiekierka** [comment]
Whatever uses tile entities won't work unless the mod adds explicit support to it. This is to prevent dupe bugs.

**Comment by DarciofMountain** [comment]
Ok, Thanks.
