### ISSUE TITLE
Buildcraft has a issue with AM2 mod once again. :/

### ISSUE THREAD

**Issue by crunkazcanbe** [BuildCraft/BuildCraft#2525]
Here is the error in the console . If I am not mistaking I posted about this issue here awhile back , and you @asiekierka had fixed it . Well now it seems to be back .

http://pastebin.com/ne6GFCQR

Thank you!

-Crunk

**Comment by liach** [comment]
It's more likely to be an AM2 issue. Btw, what's AM2?

**Comment by asiekierka** [comment]
I believe that's a warning, not an error. We're just informing you that AM2 crashed while scanning for facades, but we're recovering from it now and the game boots up.

Is that correct?

**Comment by KamranMackey** [comment]
@liach AM2 stands for Ars Magica 2. It's a magic-based mod which adds lot's of new Magic-related things. :smiley:

**Comment by liach** [comment]
Thx@kamranmackey

**Comment by crunkazcanbe** [comment]
@asiekierka Yep the game boots fine. :) Its just I seen this in the console while loading .
I just posted the issue over on the AM2 github. I said something about it to @Mithion on the Minecraft forums . I think he didn't know who's fault it was, but I could be wrong .
