### ISSUE TITLE
Energy stored of assembly table is reset after completition with nothing else to do.

### ISSUE THREAD

**Issue by Kubuxu** [BuildCraft/BuildCraft#2526]
It is problem when you pause production of for example Redstone Crystal to make one gate.
1. You stop producing crystal. Energy is stored.
2. You insert ingredients for gate. Energy is stored.
3. You instant craft gate. Assembly table has nothing else to do. Energy is voided.

**Comment by asiekierka** [comment]
I am not sure if that isn't intended behaviour. That is how the code was coded to work explciitly. @CovertJaguar? @SandGrainOne?

**Comment by SandGrainOne** [comment]
I think we should consider the table as a machine that slowly craft the component as opposed to a machine that slowly gather power in order to quickly craft an item when the required power is buffered up.

I would like to see a change so that power is voided if the player deselects the component currently being crafted or removes the required resources. 

This could be made into a bigger change where the item is given a damage number that is slowly "repaired" so that it is possible to continue the crafting at a later time.

**Comment by Silwing** [comment]
The damage thing sounds really cool. So you can do part-crafts without loosing the progress. 

One thing that is a bit annoying about how it currently works is that if you input ressources for a single craft of something that requires very little power, then the crafting is done. If you then later input ressources that match the same crafting it will quickly craft a bunch of the item before you can manage to deselect the item. Does my explanation of this make sense?

**Comment by asiekierka** [comment]
The damage thing sounds like something I do not want to do. Also, it does, but that was intended for automation - what I think could be done is power be voided more often rather than less.

**Comment by SandGrainOne** [comment]
The additional idea with % progress on the crafted item was meant to be a separat idea. A natural continuation if somone is suddenly hit with a jolt of inispiration.

**Comment by Kubuxu** [comment]
Assembly Table is required for progression and early game with BC only is rough already. Assembly Table itself is pretty pricy.

I think Assembly Table should never void energy. It is totally counter-intuitive. If you craft Redstone Crystal early game (progress in BC exclusive pack is not possible without it) you usually have only one assembly table. You sometimes want to stop and craft something smaller. Also the crafting cannot be paused without deselecting crafting so for early game you would have to have already two Assembly Tables and Lasers as energy is really limited and doing two crafting at the time is not an option.

Voiding energy would only cause harder and more flustrating early game with BC.
Filled progress bar of gate crafting to 90%. Oh, you deselected it by accident. Looks like you have to wait 20 minutes once more.

**Comment by asiekierka** [comment]
@Kubuxu - how about slowly dropping the power, let's say by 10RF/t, once the item is deselected? That would mean a far smaller loss in case of mistake and no way to cheat by pre-buffering the assembly table with a 99% crafted crystal.

**Comment by Kubuxu** [comment]
And what with reselection of something else. For me main issue is that when you craft energy crystal you have locked your Assembly Table for, in case of early game, more than an hour.

**Comment by CovertJaguar** [comment]
Assembly Table? The one that makes gates? It has always been a mess in need of a major rewrite. It had many quirks and oddities that weren't quite right.

**Comment by ryuben** [comment]
can the table have a pause button - or a timer of a few seconds so i have time to select what i want it to do? as sometimes i will put mats in and it will throw out something i have all ready crafted which wasn't what i wanted
