### ISSUE TITLE
zone planner needs 4 gbs of memory or lag out

### ISSUE THREAD

**Issue by shivachirr** [BuildCraft/BuildCraft#2529]
so ive been trying to use the zone planner on my custom modpack its pretty profromance frendly but the werid thing is when i place a zone planer it needs 4 gb+ of memory aviable other wise it just casues massvie lag outs nomatter what this way to much for me due to i only have 8 gbs on my system not sure if this is a bug or a bad memory leak but thought you should know

**Comment by shivachirr** [comment]
um ok dont know whats going on

**Comment by AEnterprise** [comment]
@shivachirr zone planner is getting a rewrite for BC 7, i think that's why this issue got closed

**Comment by shivachirr** [comment]
ah ok

**Comment by asiekierka** [comment]
Yeah. I close issues I have fixed.
