### ISSUE TITLE
Energy loss in kinesis pipes?

### ISSUE THREAD

**Issue by jyumai** [BuildCraft/BuildCraft#2533]
I have the following setup:
battbox -> LV ic2 consumer -> bridge -> RF producer -> wooden KP -> cobblestone KP -> quarry.
The pipes seem to be losing RF along the way because my quarry does not power up yet I am still using all the energy in my batt box. I am producing about 52 RF from my 32EU/t source. What is causing the problem exactly?

**Comment by asiekierka** [comment]
That's three mods involved. You need to narrow down at which point the energy disappears.

**Comment by Speiger** [comment]
The Powerloss happen in the Wooden K Pipe, because of the EnergyRemovement when there is no PowerSource connected to it. It has defautly a 0.5 MJ/RF Powerloss... It will be increased to 5MJ/RF when there is no Powersource connected...

I nodest that while i created the Emerald PowerPipe for TinyModularThings...

**Comment by asiekierka** [comment]
@Speiger - that's BC 4.2.2, not 6.2+

**Comment by Speiger** [comment]
True asie but the wooden pipe code did not really change and that part is still in the code (i did compare the codes).

**Comment by asiekierka** [comment]
@Speiger - it did change - it only depletes 50 RF/t if there are no power sources connected to it, to stop it being used as a buffer.  It does no longer have a 5 RF/t (0.5 MJ/t) power loss.

**Comment by Speiger** [comment]
Then make a testrun to proof it and i am quiet.

Leadstone EnergyCell -> wooden Powerpipe -> 5-10 powerpipes -> Empty leadstone Energycell and look if the Power is 100% Equal.

If that is the case then it is a IC2 Bug,
then you can blame player for that.

**Comment by asiekierka** [comment]
@Speiger - BC wooden pipes do not extract but expect machines to pump into them. @marcin212 spent hours testing the engines and the power is 100% equal in this case and others.

What's wrong is that the EnetBridge expects energy to be extracted from generators.

**Comment by jyumai** [comment]
The problem is at the wooden pipe. Only by removing it the power stops decreasing. I am a little confused by the conversation here....what exactly should I do to solve the issue? (Aside from using engines directly connected to the quarry).
