### ISSUE TITLE
game start issue - forge version

### ISSUE THREAD

**Issue by harvald** [BuildCraft/BuildCraft#2536]
When updated Buildcraft to 6.4.2 minecraft give me messsage on start about missing mod:
     Forge: minimum version required 10.13.2.1236

But i have forge in version 10.13.2.1291
Buildcraft 6.4.1 works normally.

**Comment by asiekierka** [comment]
What? Why did you close this?

...what?

**Comment by harvald** [comment]
Polak? ;) Ja też. 
    
    Sorry. My mistake. I had forge forge-1.7.10-10.13.2.1291.jar but it
    it was not loaded. Minecraft was loading old
    forge-1.7.10-10.13.2.1231.
    
    W dniu 2015-03-08 o 09:26, Adrian
      Siekierka pisze:
    
    
      What? Why did you close this?
      ...what?
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
      harvald
      
      
        Pomyśl o środowisku zanim wydrukujesz ten list. Please consider
        the
        environment before printing.
