### ISSUE TITLE
Knights don't attack Ghasts, Slimes & Magma Cubes

### ISSUE THREAD

**Issue by Be-Cool-Man** [BuildCraft/BuildCraft#2537]
I've set up a base in the Swampland and wanted to use the knights to fight the slimes. BUT they attack the Slimes not at all, just the other hostile mobs. The same thing in The Nether with the Magma Cubes and Ghasts.

OH..
They should not attack but ignore The Wither. The Wither fly as long upward until the robots run out of energy or they reach the height of 256 blocks and thereby become inactive and driving after a hit from The Wither ad infinitum.
_____
My Modlist:

forge-1.7.10-10.13.2.1307-1.7.10
[1.7.10]Treecapitator-universal-2.0.4
appliedenergistics2-rv2-beta-8
bamsgrave-1.7.2-1.4.2_01
buildcraft-6.4.2
BuildcraftAdditions-1.7.10-2.0.2
buildcraft-compat-6.4.0
ChickenChunks-1.7.10-1.3.4.17-universal
CodeChickenCore-1.7.10-1.0.4.35-universal (1)
EnderIO-1.7.10-2.2.8.344
EnderStorage-1.7.10-1.4.5.27-universal
extrautilities-1.2.1
ForgeMultipart-1.7.10-1.1.1.321-universal
neiaddons-mc1710-1.12.3.11
NEIIntegration-MC1.7.10-1.0.6
NotEnoughItems-1.7.10-1.0.4.83-universal
OpenEye-0.6-1.7.10
QuarryPlus-1.7.10-2.0.3
simplefluidtanks-1.7.10-1.2.0.5
Telepads-1.7.2_1.7
Waila-1.5.8a_1.7.10

**Comment by psxlover** [comment]
Slimes are neutral, they don't attack you unless you attack them, just like pigmen. I don't think that having knights attack anything that moves is a good idea.

**Comment by Be-Cool-Man** [comment]
@psxlover the Wiki (http://minecraft.gamepedia.com/Slime) lists the Slimes as hostile Mobs. Only the tiny Slimes give no attack-damage to you. You can try as simple test: generate a new World [Singleplayer -> Create New World -> Game Mode Survival ->  More World Options... -> World Type: Superflat -> Create New World] after generating set the difficulty to Easy, Normal or Hard and search big Slimes after you found them, stand near them and wait (Don't attack them first)
