### ISSUE TITLE
TE: Energy Cell Request more Triggers

### ISSUE THREAD

**Issue by kremsy** [BuildCraft/BuildCraft#2538]
Would be nice if there could be found an solution, check out:

https://github.com/CoFH/Feedback/issues/254#issuecomment-77721358

**Comment by asiekierka** [comment]
That is planned, we've just never had the time to do it.

**Comment by warlordjones** [comment]
Might do this, I want to learn how to add new triggers.

**Comment by AgentK9** [comment]
So we are getting KEBs in vanilla BC? AWESOME!!!

**Comment by asiekierka** [comment]
@AgentK9 - not at all

**Comment by AgentK9** [comment]
?

**Comment by TheJulianJES** [comment]
Sorry, I have to ask because I'm German: What is KEB(s)?

**Comment by iTitus** [comment]
Kinetic Energy Buffer. An energy storage method from Buildcraft Additions.

**Comment by TheJulianJES** [comment]
@iTitus Thx. :)

**Comment by kremsy** [comment]
Any progress here? A simple trigger which triggers less than 75% or something would be awesome.

**Comment by AEnterprise** [comment]
can be closed, BC energy system is ment to not store energy, other mods can provide the trigers for it with the api, energy requested triger exists, and TE energy cells give a redstone comparator signal indicate there charge

**Comment by AlexIIL** [comment]
BC has an odd energy system that sometimes looks like energy but behaviours mechanically, and all BC machines do store power but might not be meant to... I don't really know what's going on here any more. Although it might be implemented in BC 8.

**Comment by AEnterprise** [comment]
what's going on is the result of the views of so many developers over the years

**Comment by AEnterprise** [comment]
there is no TE for newer versions of MC yet, in case it does become available this would also be something for the compat module
