### ISSUE TITLE
Refinery not accepting Biomass

### ISSUE THREAD

**Issue by Megistus** [BuildCraft/BuildCraft#2541]
I have two refineries that have been, and continue to operate converting biomass. I tried placing a new refinery to add to my production and it will not accept biomass. Looking at the GUI of the Refinery, the input slots are already filled in with a Black, undefined, item and will not let me replace it with biomass. Apparently, it looks as if the bug fix for oil not filling both slots has ensured that no other fluid can be used in the refinery if it did not already have the fluid in it prior to the update. I attempted to left and right click the input slots with a bucket of biomass to no effect. The black item in the slot would disappear momentarily and return.

Buildcraft 6.4.2
Forge 1291

**Comment by asiekierka** [comment]
Expect a new release tomorrow.

**Comment by Megistus** [comment]
Excellent!

**Comment by warlordjones** [comment]
Whoops!

**Comment by asiekierka** [comment]
@warlordjones - could you fix it? you wrote the code and it would spare me some free time.

**Comment by warlordjones** [comment]
Cannot reproduce.

**Comment by Megistus** [comment]
Well, for whatever reason, my configuration / collection of mods is not allowing this to occur. I suspect - as I have not done any coding in a number of years - that tileRefinery.class is not getting past     this.tanks[0].setAcceptedFluid(BuildCraftEnergy.fluidOil);
this.tanks[1].setAcceptedFluid(BuildCraftEnergy.fluidOil);

What ever coding method that clears this entry and allows the addition of biomass is not being reached.

Though, as I am thinking about it, could this possibly be due to using Java 8, and an incompatibility from that version and what is coded?

**Comment by warlordjones** [comment]
Not sure why those lines are even there, they don't appear to do anything...

**Comment by Megistus** [comment]
It looks as if when I place down a refinery, that those lines of code are getting run. Of course, that is an assumption as I don't have a dev environment set up that can track what is getting run and what isn't.

**Comment by warlordjones** [comment]
I know they are being run, but in my dev environment my refinery accepts biofuel with or without those lines...

**Comment by psxlover** [comment]
Perhaps a mod that Megistus uses is overwriting oil, which causes "BuildCraftEnergy.fluidOil" to be an invalid liquid.

**Comment by asiekierka** [comment]
@psxlover - yes!

@Megistus - are you using Artifice?

@warlordjones - rewrite the code to query the fluid registry for "oil"; in fact, replace all direct references to blockOil with that.

**Comment by warlordjones** [comment]
Hrm - those lines just aren't needed...it works with and without >.>

**Comment by asiekierka** [comment]
@warlordjones - Artifice (with BC's help) can overwrite our oil - this could be the reason.

**Comment by warlordjones** [comment]
I'm not directly checking for oil, I don't think, I'm checking in the RefineryRecipes, but I'll see.

**Comment by asiekierka** [comment]
@warlordjones - try adding Artifice and see if the issue appears, as fluidOil would be null in that case

**Comment by warlordjones** [comment]
Yup, doing that

**Comment by Megistus** [comment]
I am not using Artifice mod

**Comment by warlordjones** [comment]
Oh.

**Comment by Megistus** [comment]
Buildcraft oil works as expected. Oil fills both tanks and shows up in the GUI. Processes into fuel.
However, when placing down a new refinery, where the left and right slot should be empty, it displays oil. Thus, it looks as if the refinery is initialized with a fluid (oil) ensuring that no other fluid can be added, even though there was no fluid introduced. The refinery thinks it has oil, even though it does not.

**Comment by warlordjones** [comment]
Looks like my previous commit should fix that then.

**Comment by Megistus** [comment]
Just a quick thanks. The removal of those lines of code fixed the issue with no apparent issues caused. Thanks again!
