### ISSUE TITLE
Travis workspace caching.

### ISSUE THREAD

**Issue by Kubuxu** [BuildCraft/BuildCraft#2553]
With caching build time on Travis could be speed up by about 40%. It is fairly easy to set up.
Should I do it?

**Comment by iTitus** [comment]
That would be nice for BCA too ;)
cc @AEnterprise , @BigXplosion

**Comment by Kubuxu** [comment]
It would speed up much more if ForgeGradle allowed caching of its resources but as far as I know it is not that simple.

**Comment by AEnterprise** [comment]
@iTitus we're not using travis, we're using jenkins

**Comment by iTitus** [comment]
@AEnterprise Dont we have a travis.yml file?

**Comment by asiekierka** [comment]
I think that Travis should rather be disabled, if anything.

**Comment by Kubuxu** [comment]
Maybe the checkstyle on travis as almost no-one respects it either way as it is always broken.

Second option is to check checkstyle before any push so that Travis works and tells you whether PR is compiling and passing checkstyle.

**Comment by asiekierka** [comment]
@Kubuxu - I always fix checkstyle prior to a release. And I don't really care about it before, as I'd rather work than fix style prior to a release.

**Comment by Kubuxu** [comment]
Travis is mostly for PRs. When developer himself pushes code that he knows does not passes build requirements whole idea of Travis breaks. It is meant to check things that are not visible on the first glance, fe. missing imports or miss-spellings. This way you can pull simple fixes without building them yourself.

**Comment by asiekierka** [comment]
@Kubuxu - ?

**Comment by Kubuxu** [comment]
What should I do? It is up to you.
