### ISSUE TITLE
Miner Robots don't use Mod Pickaxes

### ISSUE THREAD

**Issue by ruifung** [BuildCraft/BuildCraft#2555]
Just as the title says, the Miner Robots do not work when holding a mod pickaxe, I've tried dark picks from EnderIO and Bedrock Pickaxes from RotaryCraft, they recognize it as a pickaxe and picks it up from the chest, but does not do any work with it.

On a side note, is there a robot that breaks stone?

**Comment by Thog** [comment]
What is your BC version? Also, in 6.4.x, all pickaxes from IC2 works for me...

**Comment by ruifung** [comment]
6.4.3 I don't have IC2 so I can't say.

**Comment by laz2727** [comment]
IC picks are basic copies of vanilla picks with different durability/mining
level/speed, while dark pick is most likely custom(it's chargeable), while
reika is a very hardcore modder and most likely simply cannot into simpler
things.

**Comment by ruifung** [comment]
Still, the robots recognize it as a valid pickaxe and picks them up, from that one would usually assume they would work with it.

**Comment by asiekierka** [comment]
@ruifung - I believe the code currently checks whether it's a *vanilla-derivative* pickaxe, not just a pickaxe.

**Comment by asiekierka** [comment]
Solved in 7.0.x.
