### ISSUE TITLE
Visual Bug - Pipes

### ISSUE THREAD

**Issue by kremsy** [BuildCraft/BuildCraft#2557]
I don't know if it is a Buildcraft bug or a bug from another mode but we have a weired issue, sometimes Coal looks like cobblstone in the Pipe but it is coal and get handled correctly.

Screen (hard to see the cstone on that screen but look the coal):

http://pictures.esc-clan.net/upload2/cstone.png

**Comment by MrGraphic** [comment]
i noticed something similar but only on cauldron server with some protection plugins.

**Comment by asiekierka** [comment]
Can anyone reproduce this without Cauldron?

**Comment by kremsy** [comment]
I don't use cauldron but Railcraft, IC2, Thermal Expansion, GregTech

**Comment by laz2727** [comment]
Optifine?

2015-03-16 23:58 GMT+06:00 Lukas Kremsmayr <notifications@github.com>:

**Comment by kremsy** [comment]
Don't use optifine, and weired thing is we haven't noticed that bug in the past, updated some modes including Buildcraft some days ago and then it appeared. Can't really reproduce it without the Mods as it is hard to remove them and so on..

**Comment by kremsy** [comment]
Also have another visual Bug, I see combustion Engines Running while they don't run.

**Comment by asiekierka** [comment]
I think something is corrupting your packets.
