### ISSUE TITLE
Planter robot won't plant Forestry saplings

### ISSUE THREAD

**Issue by Amelia-** [BuildCraft/BuildCraft#2561]
I am unable to get a planter robot to plant Forestry saplings. It works fine with vanila saplings and saplings from Thaumcraft or Natura.
I'm not sure if I should take this problem up to the Forestry team or leave it here because it only affects Forestry saplings from the ones I tested but it also has to do with the planter robot.

I'm using BuildCraft 6.4.3 and Forestry 3.5.0.485 unstable.

**Comment by laz2727** [comment]
Same bug as with the Miner.

**Comment by asiekierka** [comment]
Not the same, as I already fixed the Miner one.

**Comment by laz2727** [comment]
No, i mean, it most likely has same roots. "Not vanilla-like? Not supported"

**Comment by Amelia-** [comment]
I'm sorry, I forgot to mention something.
What happens is the robot does not pick up the saplings.

I had a little look at the BuildCraft code and and what I can make of it the robot looks for items that implement IPlantable. Perhaps Forestry's saplings don't implement that?

**Comment by hea3ven** [comment]
The forestry sapplings don't implement the standard IPlantable interface that all vanilla (except reeds) plants and most mod crops do. The item doesn't implement any kind of generic "plant" mechanism so we have the following choices:
 1. special case the ItemGermlingGE in the planter
 2. create a new robot in buildcraft-compat for forestry sapplings (maybe it can also add triggers to filter based on the genetics in the sappling)
 3. add an api to be able to add special sapplings to the planter.

Option 2 just came to me, and haven't though it all through yet, but sounds cool.

**Comment by asiekierka** [comment]
Option 3 sounds like the best thing - I'll look into it later.

**Comment by Intel** [comment]
Are there any news on this?

**Comment by asiekierka** [comment]
BuildCraftCompat 7.1.0 adds support, I think.

2015-11-11 1:02 GMT+01:00 Intel <notifications@github.com>:

**Comment by Intel** [comment]
I tested this with BC 7.1.13, compat 7.1.2 and it still doesn't seem to work. While in earlier versions planter didn't even pick up forestry saplings, now it does pick up them but doesn't plant them. It just stands on the docking station after picking up sapling and doesn't do anything.

**Comment by Amelia-** [comment]
I can confirm this. I didn't report it because I thought it has to do with me using an older version of Forestry (Stable 3.6.9.28) and wanted to wait until I can test it with a newer version.
It did improve with BuildCraftCompat 7.1.0 but as said above above the robot now picks up the sapling and just sits on the docking station.
