### ISSUE TITLE
Filler issues

### ISSUE THREAD

**Issue by jakemobile34** [BuildCraft/BuildCraft#2565]
hi, so i could post this is the bug report sections was locked. but when i try to plant sugar canes using the filler it shoots them out but they dont appear. like it tries to plant them but they just dont appear. i have the latest buildcraft for 1.7.10 in use plus the latest forge for it too. And where im trying to get them to go meets the requirements for the sugarcane 
![2015-03-16_14 19 14](https://cloud.githubusercontent.com/assets/11545081/6718584/055b7e50-cd72-11e4-896b-803672a335ff.png)

**Comment by jakemobile34** [comment]
bump?

**Comment by asiekierka** [comment]
We know. There's only one dev handling most of this stuff, so please be patient.

**Comment by jakemobile34** [comment]
mkay, i understand. just thought it was missed or something

**Comment by iTitus** [comment]
Very inefficient pattern :P

**Comment by jakemobile34** [comment]
i was just making a farm real quick lol wasnt actually building a legit farm

**Comment by will-janz** [comment]
The filler does the same thing with cakes; it spits them out but doesn't actually place them, they simply never appear. I've tested similarly shaped blocks, including stone slabs, tracks, beds (beds will crash a server it seems), cacti, heavy weighted pressure plates, enchanting tables, carpets, iron bars, heads, and fences all place as expected. Doors, signs, and redstone repeaters do not get placed and also simply vanish. Brewing stands and cauldrons get placed one block above a placable surface.

Cakes from Pam's Harvestcraft will be thrown, but when they're placed, they appear for a few ticks and then vanish. 

I'm using: 
* FTB Infinity 1.8.2 with Fastcraft
* Minecraft 1.7.10
* BuildCraft 7.0.15
* BuildCraft Compat 7.0.4
