### ISSUE TITLE
robots, no class def

### ISSUE THREAD

**Issue by Bennyboy1695** [BuildCraft/BuildCraft#2568]
Updated my modpack and when trying to launch the server it crashes with this crash everytime, i have tried both the latest verson of buildcraft and also 6.4.1.

http://pastebin.com/bezsGsFf

**Comment by liach** [comment]
logisticspipes' fault. Please update that mod.

**Comment by Bennyboy1695** [comment]
thanks that fixed it :) swear there wasnt a update for logistics when i looked though :P
