### ISSUE TITLE
Railcraft Ironfurnace Gates are not working correctly

### ISSUE THREAD

**Issue by kremsy** [BuildCraft/BuildCraft#2570]
Dunno if its the right place to post this issue, the Railcraft Irfonfurnaces are the same as the normal Furnaces except they are faster. I replaced one nomral through it and found out that a Gate I had directly on a pipe on the backside should trigger a signal as soon there is coal in the ofen (works perfect with normal furnaces, with the iron one, the signal always get triggered if there is something in the output).

**Comment by asiekierka** [comment]
I believe that's because the RailCraft Iron Furnace uses ISidedInventory, while Minecraft's Furnace does some weird things (like a lot of vanilla). @CovertJaguar ?

**Comment by Forecaster** [comment]
You mean the steam oven : P

**Comment by kremsy** [comment]
Ups I've ment the Iron Furnace from Industrial Craft² "http://feed-the-beast.wikia.com/wiki/Iron_Furnace"

**Comment by asiekierka** [comment]
BC_NotMyFaultException, we go by ISidedInventory

**Comment by CovertJaguar** [comment]
Well that one missed the mark by a fair bit, lol.
