### ISSUE TITLE
Horizon setting on filler crash

### ISSUE THREAD

**Issue by ToxicCriminal21** [BuildCraft/BuildCraft#2571]
I am playing on a server using the FTB Infinity modpack and my server crashes everytime  I try to open the filler. Everything was fine until I changed the mode to horizon. Any help?

**Comment by akvgergo** [comment]
Got the same issue, here's the crash:
http://paste.ee/p/AlDx0

@ToxicCriminal21 FYI You are supposed to give a crashlog if you say it crashed :P

**Comment by Zackarymadden1** [comment]
Playing on FTB Infinity had the same issue listed above. (So i won't repeat the crash log) Tried updating to latest version did not help. Issue is repeatable in test world, and will crash player on start up. The crash will not force close, but instead just make world stop ticking. Thank you for your time. Just wanted to add in some extra information not seen above.

**Comment by asiekierka** [comment]
Fixed.
