### ISSUE TITLE
railcraft residual heat quarry

### ISSUE THREAD

**Issue by nitsuga5124** [BuildCraft/BuildCraft#2572]
the bc quarry try to dig/mine the residual heat block generated by the player to detect where it is.

the quarry basicly (if you enter in the area to mine) stop work and i need to delate the residual heat with mcedit ):

fix it

**Comment by asiekierka** [comment]
No please? But alright, I'll look into it.

**Comment by Techokami** [comment]
Disable residual heat in Railcraft?

Sent from my Windows Phone
________________________________

**Comment by Kubuxu** [comment]
The solution is probably to make quarry skip if Block#isAir but this would only work if RC overrides this method or uses air material.

**Comment by SandGrainOne** [comment]
What version of BC are you using @nitsuga5124 ?

**Comment by laz2727** [comment]
isAir was *created* because of rf residual heat.

**Comment by nitsuga5124** [comment]
bc 6.4.3 with railcraft 9.4.0.0 (residual heat desabled still unworking)

**Comment by ganymedes01** [comment]
isAir is a vanilla method. Every mod should use it.

**Comment by asiekierka** [comment]
@ganymedes01 Except we do.

Huh.

**Comment by asiekierka** [comment]
I believe that doesn't happen anymore.

**Comment by nitsuga5124** [comment]
FIXED
