### ISSUE TITLE
Add support for Cauldron-users

### ISSUE THREAD

**Issue by iLeonidze** [BuildCraft/BuildCraft#2576]
There are a lot of users using Forge mods and Bukkit plugins, but if you try to install BuildCraft on latest cauldron (Official version 1.1207.01.198, unofficial version 1.1307.06.218) you will get an incompatibility error. BuildCraft|Core (BuildCraft) requires Forge@[10.13.2.1236], to be available, but last cauldron based on Forge Mod Loader with old version 7.10.25.1207. So this cause a new MissingModsExeption at cpw.mods.fml.common.Loader.sortModList.

Check this logs:
[:page_with_curl: crash-2015-03-22_08.47.55-server.txt](http://pastebin.com/zaFJVcaH)
[:page_facing_up: latest.log](http://pastebin.com/AYmBKccp)
[:page_facing_up: fml-server-latest.log](http://pastebin.com/Cq696kxa)

*Galacticraft successfully running on this version of cauldron and all new updates are compatible too. I hope, you can do the same one* :smile: 

:ballot_box_with_check: All plugins, mods updated, no dependencies.

**Comment by laz2727** [comment]
I don't see how this is BC's fault.

2015-03-22 14:22 GMT+06:00 Leonid Fedotov <notifications@github.com>:

**Comment by iLeonidze** [comment]
@laz2727 please, read carefully the body of my issue. There is no BC's fault, the main problem that BC uses sortModList, incompatible with Forge 7, and it cause server failure. For example, old BCs (5.0.0) work fine with Forge 7. Everything I need - support for died cauldron.

**Comment by Kubuxu** [comment]
As you said there exists unofficial version for 1307. Use it instead.
Now you are asking to stop progress as Cauldron project died. It might not be the only issue with current BC and Forge 1207. It is 100 builds of Forge <=> 100 commits. No-one knows which features were added and so on.

**Comment by iLeonidze** [comment]
@Kubuxu okay, checked all BuildCraft versions right now. BC 6.4.0 works fine, but BC 6.4.1 drop the server down. This problem issued recently, as I see.

**Comment by asiekierka** [comment]
@iLeonidze - use Cauldron 1236 from http://tcpr.ca/ and stop complaining about using outdated software, because we need to move with the times - Forge 1231+ adds functionality we *actually use*.
