### ISSUE TITLE
Forum issue

### ISSUE THREAD

**Issue by KyeDuo** [BuildCraft/BuildCraft#2581]
I can't get the forum to send me a password reset e-mail.
I look in my junk email folder and nothing ever comes.
It is frustrating and I don't want to have to create a new account to get back on.

**Comment by AEnterprise** [comment]
what is your forum username? also did you ever make any posts with your user? if you never made any posts then the account was removed in the migration to the new forum, this was done to get rid of all the remaining spam bot accounts that where causing issues in the migration

**Comment by KyeDuo** [comment]
Kye_Duo

**Comment by AEnterprise** [comment]
user does exist, please join me on irc so i can pm you for it

**Comment by KyeDuo** [comment]
IRC. uh.....how?

**Comment by laz2727** [comment]
Can't you just email him?

2015-03-23 21:21 GMT+06:00 KyeDuo <notifications@github.com>:

**Comment by AEnterprise** [comment]
thought irc would be easier but if he can send me his email then i can do it that way as well

**Comment by KyeDuo** [comment]
imperial_destroyer@hotmail.com

**Comment by laz2727** [comment]
IRC is not the easiest way for about 4 years at least.

2015-03-23 21:23 GMT+06:00 AEnterprise <notifications@github.com>:

**Comment by AEnterprise** [comment]
issue can be closed

**Comment by asiekierka** [comment]
@laz2727 yes it is

**Comment by laz2727** [comment]
Maybe for you, but not for the outsider.

2015-03-23 22:37 GMT+06:00 Adrian Siekierka <notifications@github.com>:
