### ISSUE TITLE
Laser Rendering Issue

### ISSUE THREAD

**Issue by zlainsama** [BuildCraft/BuildCraft#2582]
Description: Laser didn't render properly with solid blocks in front of it.
How to reproduce: place an laser block/device, and place a stone in front of it.

Forge Version: 1.7.10-10.13.2.1291
Buildcraft Version: 6.4.4
Buildcraft Compact Version: 6.4.1
Optifine Version: not used
Fastcraft Version: 1.19 (I tried remove fastcraft, didn't make a difference)

These screenshots were taken without fastcraft.
![2015-03-23_23 45 21](https://cloud.githubusercontent.com/assets/3251859/6783860/1c802772-d1b7-11e4-84a4-13ddca4e0882.png)
![2015-03-23_23 45 25](https://cloud.githubusercontent.com/assets/3251859/6783861/1d08500c-d1b7-11e4-981d-af8b26a0f442.png)

**Comment by laz2727** [comment]
You sure it didn't just stick to the stone?

2015-03-23 21:52 GMT+06:00 Lain MultipleInstances <notifications@github.com>
:

**Comment by zlainsama** [comment]
Do you mean 'stick to the stone' as it's base placed on the side where stone at?

**Comment by laz2727** [comment]
Yes?

2015-03-23 22:00 GMT+06:00 Lain MultipleInstances <notifications@github.com>
:

**Comment by davboecki** [comment]
I would guess that it is the render Side check which doesn't render sides connected to another solid block.

**Comment by zlainsama** [comment]
To: laz2727
No. I didn't change the laser block in two screenshots.
