### ISSUE TITLE
Filler halves tick rate when out of blocks.

### ISSUE THREAD

**Issue by crescentrose** [BuildCraft/BuildCraft#2584]
The filler seems to be filling fine, when it has enough blocks. However once it has no more blocks left, it throws a fit and lags down the entire server.

With filler running, no blocks available:
![Running](http://puu.sh/gMA1w/8803920f74.png)

After placing blocks in the filler:
![Not running](http://puu.sh/gMA73/1422ef55aa.png)

It's a weird issue for sure, but the filler appears to be the source of lag, since as soon as it received blocks to continue its job, the server returned to normal.

**Comment by asiekierka** [comment]
Trickier to fix than I wanted it to be.

**Comment by asiekierka** [comment]
@crescentrose Could you try with http://asie.pl/bc645c.jar ?

**Comment by Goobaroo** [comment]
I tried this latest fix on my sever and still ended up with very large delays when the builder runs out of blocks.  It's almost like it's in a race condition looking for blocks.  If needed, I can provide a snapshot of my server.

Average tick got as high as 1300ms

**Comment by asiekierka** [comment]
That would be appreciated

**Comment by asiekierka** [comment]
@Goobaroo - ping?

**Comment by Goobaroo** [comment]
https://dl.dropboxusercontent.com/u/34742192/HermitcraftModsauce_1011.tgz

The builder is setup in the overworld above ground near the spawn point for the world.  It's quite a large pattern.
