### ISSUE TITLE
Hollow Facade in tabs

### ISSUE THREAD

**Issue by dotrich** [BuildCraft/BuildCraft#2587]
Apologies if this isn't the right place. As far as I can tell Buildcraft Compat handles what NEI sees. If this is not the case please close this issue immediately.

Could you make one hollow facade item appear for NEI. I'm using the FTB Infinity modpack v1.2.1 on Minecraft v1.7.10.

It was incredibly frustrating trying to figure out why the only facade that appeared from a search wouldn't allow pipes to travel through while all readily available material said it would.

Reference:
Stone facade name: 'Facade: Stone' ID 5168 
Hollow stone facade name: 'Facade: Stone (item.Facade.state_hollow)' ID 5168

**Comment by asiekierka** [comment]
Because this was a very recent change.
