### ISSUE TITLE
Pipes with multiple engines

### ISSUE THREAD

**Issue by GrnEyedDvl** [BuildCraft/BuildCraft#2588]
When using multiple engines to extract items from a chest, such as 3 redstone engines on a single wooden pipe, the number of items sent does not always match the number of items received. This is especially true if the engines are not in sync, that is they are running at different speeds. The problem is worse if you save and shut down while items are in the pipes, then restart.

To replicate this, start a new creative world. Place a chest and a wooden pipe, and 3 redstone engines on it. Run some pipe to another chest, make sure there are some twists and turns in it. I mixed gold and stone pipe for my test. Power up the redstone engines, make sure you start one several seconds behind the others so that 2 of them turn red while one is still green. Place two or three different stacks in the sending chest, make sure you know exactly what you placed. 

In my test with two stacks of stone and a stack of dirt, I ended up with 11 extra dirt and short 12 stone. Throw the items back in the sending chest, wait until there are a bunch of items in the pipe, save the game. Restart, wait for the items to finish sending and check the numbers. You will be over or short depending on where each engine was in its cycle when it shut down. 

If you wait until all engines are running full speed before you shut down, when you start up again they will all be in sync, stroking at the same time (at least visually) but you will still have problems with the number of items in the pipe vs the number of items sent.

**Comment by asiekierka** [comment]
I have done this repeatedly and it never happened. Can you reproduce this without any coremods?

**Comment by GrnEyedDvl** [comment]
Thanks for the fast reply!

There are no coremods in the modpack. Lots of mods though not anything I haven't used before. I will try it with no other mods loaded over the weekend then load them one by one and see if I can figure out if another mod is causing the issue.
