### ISSUE TITLE
BC 6.4.1 Builder sacks server TPS

### ISSUE THREAD

**Issue by EnigmaticaGH** [BuildCraft/BuildCraft#2589]
Running Infinity 1.2.1 modpack from FTB which uses BC 6.4.1. A builder with a Blueprint placed inside of it causes the TPS of the server to tank. Current TPS is less than 1 (5%) and it's kicking other players from the server.

https://youtu.be/NcHig-1uWLo?t=14m23s A Youtuber using the same modpack encountered the same issue. It seems to happen if the Builder runs out of materials (seen in the video at 16:15)

**Comment by asiekierka** [comment]
Most likely same issue as https://github.com/BuildCraft/BuildCraft/issues/2584 - however, I want to be sure that was fixed properly in the Filler before I apply it to the Builder. Waste of effort trying to do the same bugfix twice and then failing.
