### ISSUE TITLE
6.4.5 creates regular "can't keep up" lag and blocks are hard to break.

### ISSUE THREAD

**Issue by lymem** [BuildCraft/BuildCraft#2591]
With buildcraft 6.4.5 on minecraft 1.7.10, forge-1.7.10-10.13.2.1277 on the server, my server: AMD FX(tm)-4100 Quad-Core Processor, with 10 out of 20GB allocated to minecraft. There are regular "can't keep up" events on the console, and you have to break a block 3-4 times before it actually is broken. This issue is not present in buildcraft 6.4.3

**Comment by asiekierka** [comment]
Builders? Fillers? Are you using any of these?

**Comment by lymem** [comment]
No builders or fillers in use, a number of quarries though.

My server is currently using just shy of 6gb for minecraft, which happens when you have a lot of chunkloaded areas.

**Comment by asiekierka** [comment]
This is very weird. I didn't touch any quarry code. You'd need to provide a sampling, from either Opis, [Player's Sampler](http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820) or something else.

**Comment by Tencao** [comment]
For the past few versions, quarries have been very laggy if pressed up against a wall in a cave, the tps drops massively. I think this is the same issue
http://prntscr.com/6lqj94

**Comment by Tencao** [comment]
If you would like some more info, as I've found out from logblocker, it seems to spam loads of block requests, roughly 70k in 5 seconds, and the quarry frame never ends up building, almost like it gets stuck.

**Comment by asiekierka** [comment]
Aaaaaaaah. So it is the builder code at fault... And it does get stuck... What size is the quarry?

**Comment by asiekierka** [comment]
Going off to sleep. Remember that grief prevention mods might cause the frame not to be built. Anyway, good night,

**Comment by Tencao** [comment]
Area was completely unprotected, and the quarry was default size. This issue doesn't happen on the surface, just when it;s facing a wall, which can be mostly done in caves.

**Comment by asiekierka** [comment]
Cannot reproduce. That's why I need a report of what's going on.

**Comment by lymem** [comment]
I'll get something together for you, or working on it at least.. It will be tomorrow pst when I get time to put it together.

**Comment by lymem** [comment]
Grr.. The setup in my world that was the source of the issue seems to have resolved itself and the lag is now gone.. Closing this and will re-open if/when I can reproduce and put a dump together.
