### ISSUE TITLE
Fluid Duplicating With Stripe Pipe & Vanilla Bucket

### ISSUE THREAD

**Issue by 3TUSK** [BuildCraft/BuildCraft#2593]
Sorry for bothering again. My friend told me that lava can be duplicated in Buildcraft 6.4.5 just now, then I tried to reproduce it, and I succeeded under Forge 10.13.2.1291 and Buildcraft 6.4.5 only.
Further test shows that Buildcraft Fuel can also be duplicated, as the following screenshot shown. (Also this screenshot shows the structure.)
![2015-03-26_16 27 43](https://cloud.githubusercontent.com/assets/9113033/6856356/f8b3bacc-d3d5-11e4-8d31-97224846f6b2.png)

Steps:
1.Building a structure as shown.
2.Throws a empty vanilla bucket into obsidian pipe.
3.Seconds later you get a fuel bucket, while the fluid resource did NOT disappear.

Hope to get reply soon, also thanks for your time.

Beside, why stripe pipe need to be risen one block higher so that it can collect fluid with a bucket? (test with vanilla water block) I remember that pipe need to be placed as high as fluid to collect fluid in BC 6.3.

**Comment by asiekierka** [comment]
The Stripes Pipe got a rewrite in BC 6.4.

Also, nice catch!

**Comment by 3TUSK** [comment]
Beside, FYI, @bakaxyf helped me find BC 3.2, BC 3.5.1 and BC 3.5.2. Currently I have no access to my laptop, I will confirm it as soon as I get my laptop.
