### ISSUE TITLE
Some Gate Triggers/Actions not aware of others.

### ISSUE THREAD

**Issue by mattymatny** [BuildCraft/BuildCraft#2597]
No sure if the title is the best way to explain the issue but ill will try my best to make it clear.

The issue I am personally having is with the "Power Requested" trigger and the "Open/Closed" action. In my setup I had engines with gates set to emit a redstone signal when there was power requested, on the other end of the grid was a laser setup. I set up a gate on the laser grid in order to "close" the pipe when it received a redstone signal from the attached lever. Turning on the lever closed the lasers and the the engines shut down. However when flipping the lever back off in order to re-open the lasers to the power grid the gates with the "Power Requested" condition would not trigger even tho there was still work for the lasers to do on the assembly table. Not sure if I am missing something or if these two actions dont work together.

**Comment by Be-Cool-Man** [comment]
Use one Iron-OR-Gate or two Basic-Gates (on your Laser grid)
Redstonsignal on -> Close Pipe
Redstonesignal off -> Open Pipe

**Comment by hea3ven** [comment]
To clear any confusion, the close action is "set pipe to close state" not "close pipe while the action is active", so once you close a pipe you need another action to open it.

**Comment by mattymatny** [comment]
Yeah, I managed to figure that out about an hour after I posted this. But passed out shortly after and never got around to updating my issue.
