### ISSUE TITLE
Builder & vanila lever

### ISSUE THREAD

**Issue by chemban** [BuildCraft/BuildCraft#2598]
Hello, not sure if this is buildCraft related or another mod.  It appear that a blueprint with a lever in it will cause the builder to malfunction.
![buildcraft builder](https://cloud.githubusercontent.com/assets/11477931/6882300/0077c024-d556-11e4-865f-ccf04c1e3da4.png)
Notice the Fluid tanks.

**Comment by iTitus** [comment]
Does this happen without a resource pack?

**Comment by chemban** [comment]
![buildcraft no rp](https://cloud.githubusercontent.com/assets/11477931/6882367/a375fa96-d558-11e4-971a-565ebd3424e9.png)

It doesnt show the black lines, but i added water to it, and it does not show it stored.

**Comment by chemban** [comment]
sorry i should have mentioned this is not just a visual glich.  the builder will not place liquids with the lever present.

**Comment by chemban** [comment]
this is also 1.7.10 BC 6.4.5 and updated forge.  Several other mods as weil.

**Comment by chemban** [comment]
Also this was created in creative mode, and attempted in survival with a survival only blueprint, original design includes tesseracts from TE.  the Builder will work in survival with a creative blueprint to include both water for the engines, tesseracts, and facades as long as i dont include the lever.

**Comment by chemban** [comment]
![buildcraft no blueprint](https://cloud.githubusercontent.com/assets/11477931/6882491/1a18ac44-d55d-11e4-8715-7139a077569a.png)
![buildcraft no rp](https://cloud.githubusercontent.com/assets/11477931/6882492/1c7717b4-d55d-11e4-871b-d0480ca2a10e.png)

**Comment by Max-Shen0** [comment]
![2015-04-02_04 54 24](https://cloud.githubusercontent.com/assets/11188862/6960881/5d0771a8-d8f4-11e4-8771-15e528463f16.png)
Could not reproduce in BuildCraft 6.4.6 alone.

**Comment by asiekierka** [comment]
Bukkit plugins maybe?

**Comment by chemban** [comment]
i dont user Bukkit.

**Comment by chemban** [comment]
possible its an interaction between the red wire, or gates?

**Comment by chemban** [comment]
it is only a minor inconvenience, just wanted to make sure it wasn't a bug within buildcraft.

**Comment by asiekierka** [comment]
@chemban - Could you try with BuildCraft 6.4.13 and 7.0.2?
