### ISSUE TITLE
Used memory spazzing out

### ISSUE THREAD

**Issue by jakemobile34** [BuildCraft/BuildCraft#2600]
so.... randomly when i play my memory likes to jump through % like milliseconds on a watch.... it doesnt do this on vanilla minecraft. and I currently have the latest forge and buildcraft for 1.7.10
I would post a video of it spazzing out but idk to do that... so ive got four screenshots of me standing in the same spot taken with 5 seconds. it was doing this in the previous buildcraft update too.
![2015-03-30_13 11 25](https://cloud.githubusercontent.com/assets/11545081/6905757/233e96a2-d6df-11e4-8ce0-b2ce1adf4c1e.png)
![2015-03-30_13 11 28](https://cloud.githubusercontent.com/assets/11545081/6905758/23415fcc-d6df-11e4-89e5-bec4d7b150dd.png)
![2015-03-30_13 11 15](https://cloud.githubusercontent.com/assets/11545081/6905759/23445c22-d6df-11e4-904e-6f2d0320d6df.png)
![2015-03-30_13 11 20](https://cloud.githubusercontent.com/assets/11545081/6905760/2344c7c0-d6df-11e4-9076-0a06781db99a.png)

**Comment by jakemobile34** [comment]
btw... those screenshots were taken when i had mcpatcher on. but it does it when dont use mcpatcher

**Comment by asiekierka** [comment]
So... Memory leak! With fillers/builders, no less!

...These things really need a rewrite. I give up.

**Comment by Kubuxu** [comment]
@asiekierka it is not memory leak. It is just normal memory usage with Forge and mods. Garbage in memory builds up and then Java decides to do minor garbage collection. It totally normal and until Java does not run out of memory there is nothing to worry for.

**Comment by jakemobile34** [comment]
but when this happens nothing works. the filler doesnt do anything, the builders stop. even the pipes dont even do anything

**Comment by jakemobile34** [comment]
its one filler with like maybe 10 creative pistons attached to it

**Comment by asiekierka** [comment]
"creative pistons"

As I said, I can't reproduce any of the filler issues and people just come to us and shout at us to fix them, when we don't even know what is wrong.

**Comment by jakemobile34** [comment]
is there any other information i can provide?

**Comment by jakemobile34** [comment]
i can close the world and open it up and its still there. i cant shut down minecraft and then go back in and its still there. i can restart my computer and its still there. i can wait with my computer off for a few days and comeback and its still doing it. i pretty much have to play and ride it out

**Comment by Kubuxu** [comment]
JMX/VisualVM CPU sampler snapshot would be useful. It is the only way we can localize the bottleneck.

**Comment by jakemobile34** [comment]
thats the alternate F3 right?

**Comment by jakemobile34** [comment]
![2015-03-31_01 52 50](https://cloud.githubusercontent.com/assets/11545081/6915427/cafc547e-d748-11e4-8382-98890e78d251.png)
![2015-03-31_01 53 06](https://cloud.githubusercontent.com/assets/11545081/6915428/cb005c72-d748-11e4-8f34-06d96afec129.png)

**Comment by Kubuxu** [comment]
It is not. It is tool in JavaDevelopmentKit. You run it, select MC instance ( it might be named "launchwrapper"something) select Sampler tab, click CPU button after you have joined lagging world, wait a minute or so, click Snapshot, select Snapshot tab, save it and upload. It is bit complicated but it is the only way to debug it.

**Comment by jakemobile34** [comment]
![untitled](https://cloud.githubusercontent.com/assets/11545081/6916205/269729a2-d74f-11e4-9d49-09f75047f9ac.png)

**Comment by jakemobile34** [comment]
took me forever to figure out how to do that lol

**Comment by Kubuxu** [comment]
Good. You've done one step. Now select sampler tab, click CPU button... Just read my previous comment once more. If you send us correct snapshot (not screenshot) we will know which function causes lag.

**Comment by jakemobile34** [comment]
this one? im sorry. not as techie as i want to be yet
![1](https://cloud.githubusercontent.com/assets/11545081/6917499/e8366898-d759-11e4-90c7-5ad9aabe5b9f.png)

![untitled2](https://cloud.githubusercontent.com/assets/11545081/6917452/8df313b8-d759-11e4-84ae-75103cf3a212.png)

**Comment by jakemobile34** [comment]
found the snapshot. but i cant upload it

**Comment by laz2727** [comment]
rghost.net

**Comment by asiekierka** [comment]
Or email it to me. asiekierka at gmail dot com

**Comment by asiekierka** [comment]
You also want to make a memory snapshot if you dont have any lag? As your issue is memory not CPU

**Comment by Kubuxu** [comment]
It is called Heap Dump but memory is not the case. IMHO it is normal JVM operation with completely lagged out Main Thread.

**Comment by jakemobile34** [comment]
well i sent the snapshot to asiekierka. i can send it to you or post it through rghost or something kubuxu

**Comment by Kubuxu** [comment]
Asie will send it to me if he needs help.

**Comment by asiekierka** [comment]
I didn't get it.?

**Comment by jakemobile34** [comment]
i sent it to asiekierka@gmail.com

**Comment by asiekierka** [comment]
Strange.

**Comment by jakemobile34** [comment]
spam folder maybe?

**Comment by jakemobile34** [comment]
send me an email and ill reply back, jakemobile34 at gmail com

**Comment by jakemobile34** [comment]
so..... whats that mean
