### ISSUE TITLE
Quarry cannot mine dirt or gravel

### ISSUE THREAD

**Issue by ExDomino** [BuildCraft/BuildCraft#2601]
On my server, a player has noticed that quarries cannot mine dirt or gravel. The quarry, when it meets dirt or gravel, doesn't mine it and continue its work. It will not mine under dirt or gravel either.

**Comment by AgentK9** [comment]
Are you sure is not lava? Also, which version of BC are you using?

**Comment by ExDomino** [comment]
BiblioCraft[v1.9.2][MC1.7.10].jar

**Comment by asiekierka** [comment]
Old. Try 6.3.7 or 6.4.5.
