### ISSUE TITLE
BC 7 Assembley table crash :(

### ISSUE THREAD

**Issue by LouisHutch** [BuildCraft/BuildCraft#2603]
I had a assembley table creating a redstone cystal and all of a sudden crash: http://pastebin.com/fqUt8ZMg
I had about 20 lasers powering the assemble table from ender io vibrant capaciter banks

Mods Installed:
BC7 - Core and SIlicon
Ender IO
NEI
WAILA

Edit: It crashes when the assembly table finishes crafting the redstone crystal

**Comment by asiekierka** [comment]
Minor as it was specific to the modularization.
