### ISSUE TITLE
NPE when searching in creative menu

### ISSUE THREAD

**Issue by shadowfacts** [BuildCraft/BuildCraft#2604]
[Here](http://pastebin.ubuntu.com/10715936/) is the crash report. This happened when was searching for the flood gate in the creative menu.

**Comment by shadowfacts** [comment]
Update: I had another, related [crash](http://pastebin.ubuntu.com/10715961/), although I'm not sure if this was caused by the same thing.

**Comment by asiekierka** [comment]
The former is caused by Twilight Forest. The latter is ours.

**Comment by asiekierka** [comment]
Can anyone reproduce this?

**Comment by BionicFelps** [comment]
http://hastebin.com/cunojawamo.md

Bunch of mods installed, rotarycraft, pneumaticcraft, twilight forest, forestry, etc. I think there's a list at the end of the paste...

**Comment by asiekierka** [comment]
@BionicFelps Your ID map seems to be broken, as well as your fluid registry...?

**Comment by BionicFelps** [comment]
Could be, I'm working on a modpack, and I'm at a stage where I just stapled together a load of various mods... I believe the DragonAPI (rotarycraft coremod) does some odd things with item names...

**Comment by BionicFelps** [comment]
Upon closer inspection... The reason I couldn't reproduce it with buildcraft was it was because it was enderstorage causing the issue in (my) case...
