### ISSUE TITLE
Planter robot sits on chest station when told to plant on one block

### ISSUE THREAD

**Issue by andrewminer** [BuildCraft/BuildCraft#2605]
STEPS

1. Create a powered docking station for a robot and define a working area which maps to a single side of a single block.  Program the gate to make the robot work within that "area" and filter to only a certain kind of sapling.
2. Near the working "area", but distance from the robot's base, put down a chest and configure a second docking station adjacent to the chest.  Program it to always provide items.
3. Stuff some saplings in the chest.
4. Drop a Planter robot on the first docking station.

EXPECTED

After charging, the planter will leave its initial docking station and head over to the second docking station to grab a sapling.  Sapling in hand, it will go to the work site and plant.  No further work possible, it will return to its initial docking station until there is room at it's planting location again.

ACTUAL

After charging, the planter leaves its initial docking station and heads over to the second docking station where it grabs a sapling.  Sapling in hand, it goes to the work site and plants it.  At this point, it returns to the second docking station, grabs another sapling and sits there (hogging the docking station) until it's planting location is empty again.

**Comment by asiekierka** [comment]
I love your bug reports. Which version? @hea3ven ?

**Comment by andrewminer** [comment]
I knew I forgot something!  BC6.4.5 with MC1.7.10

**Comment by andrewminer** [comment]
Quick update... I just had a case where, after several minutes (~10), the Planter returned to its home docking station.

**Comment by asiekierka** [comment]
@andrewminer - try http://asie.pl/bc646a.jar ?

**Comment by Kubuxu** [comment]
@asiekierka AFAIK it affects all robots. If no work is to be done they will sit where they are but IIRC they won't occupy a station.

**Comment by hea3ven** [comment]
Yes, he was pathfinding, 4dfca53 should make those 10 minutes more like a couple of seconds.

**Comment by asiekierka** [comment]
Okay, then, I will try to release BC 6.4.6 soon.
