### ISSUE TITLE
Insane filler lag with 6.4.6

### ISSUE THREAD

**Issue by NipsuGamer** [BuildCraft/BuildCraft#2608]
6.4.6 update made filler lag much worse. My server is skipping 130-170 seconds constantly. And my client console spams this while filler interface is open. http://i.gyazo.com/1ac0e9afe931c53cff285945591577fd.png

Edit: Server only starts lagging when filler interface is opened / filler is active.

**Comment by asiekierka** [comment]
What version did you upgrade from? Those prints were around since 6.4.0 and I just forgot about them.

**Comment by NipsuGamer** [comment]
I upgraded from 6.4.5 to 6.4.6

**Comment by asiekierka** [comment]
Try http://asie.pl/bc647a.jar - also, try downgrading to 6.4.5 and see if that helps.

**Comment by asiekierka** [comment]
http://asie.pl/bc647b.jar <- try this. Fixed two issues.

**Comment by NipsuGamer** [comment]
Same issue, my server started skipping 100 seconds and timing everyone out when i first opened the filler without even giving it power. Client console spam was fixed tho.

**Comment by asiekierka** [comment]
@NipsuGamer - Is there a chance you can run VisualVM's Sampler and give me a CPU snapshot?

**Comment by asiekierka** [comment]
Can't reproduce.

**Comment by NipsuGamer** [comment]
Oh wow.. my server was choking on ram, had too little ram allocated. Didn't think of that one cause I haven't had any other lag problems with my server. Sorry..
