### ISSUE TITLE
Buildcraft 6.4.6 incompatibility with EIO SAG Mill

### ISSUE THREAD

**Issue by tgstyle** [BuildCraft/BuildCraft#2609]
Please see the following thread on EIO GIthub.

https://github.com/SleepyTrousers/EnderIO/issues/2207

**Comment by asiekierka** [comment]
I didn't touch anything in that code. All I changed was facades, buckets and blueprint handling.

Must be some kind of massive coincidence. Or an April Fools' joke.

**Comment by tgstyle** [comment]
Odd as it works fine with 6.4.5, but not 6.4.6.

**Comment by tgstyle** [comment]
Just to note that 6.4.7 has the same issue.

**Comment by tgstyle** [comment]
Updating to the latest AE2 and overriding the SAG Mill charged certus quartz recipe appear to have resolved this.
