### ISSUE TITLE
Buildcraft Advanced Crafting Table crashes

### ISSUE THREAD

**Issue by Rpvinjumoad** [BuildCraft/BuildCraft#2613]
I need help guys, I wanted to try this laser and when I placed the Advanced Crafting Table the game crashed because of the Crafting table. My MC is 1.4.7 and im using Buildcraft A 3.4.3. Heres the crash report:
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 4/4/15 10:23 AM
Description: Ticking tile entity

java.lang.ArrayIndexOutOfBoundsException: 9
	at buildcraft.core.utils.SimpleInventory.a(SimpleInventory.java:39)
	at buildcraft.silicon.TileAssemblyAdvancedWorkbench$InternalInventoryCrafting.a(TileAssemblyAdvancedWorkbench.java:55)
	at ry.b(SourceFile:35)
	at noppes.npcs.controllers.RecipeAnvil.checkMatch(RecipeAnvil.java:112)
	at noppes.npcs.controllers.RecipeAnvil.a(RecipeAnvil.java:70)
	at wn.a(CraftingManager.java:293)
	at buildcraft.silicon.TileAssemblyAdvancedWorkbench.updateCraftingResults(TileAssemblyAdvancedWorkbench.java:351)
	at buildcraft.silicon.TileAssemblyAdvancedWorkbench.g(TileAssemblyAdvancedWorkbench.java:261)
	at yc.h(World.java:2151)
	at in.h(WorldServer.java:516)
	at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:680)
	at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
	at bdz.q(IntegratedServer.java:170)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
	at fy.run(SourceFile:849)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at buildcraft.core.utils.SimpleInventory.a(SimpleInventory.java:39)
	at buildcraft.silicon.TileAssemblyAdvancedWorkbench$InternalInventoryCrafting.a(TileAssemblyAdvancedWorkbench.java:55)
	at ry.b(SourceFile:35)
	at noppes.npcs.controllers.RecipeAnvil.checkMatch(RecipeAnvil.java:112)
	at noppes.npcs.controllers.RecipeAnvil.a(RecipeAnvil.java:70)
	at wn.a(CraftingManager.java:293)
	at buildcraft.silicon.TileAssemblyAdvancedWorkbench.updateCraftingResults(TileAssemblyAdvancedWorkbench.java:351)
	at buildcraft.silicon.TileAssemblyAdvancedWorkbench.g(TileAssemblyAdvancedWorkbench.java:261)

-- Tile entity being ticked --
Details:
	Name: net.minecraft.src.buildcraft.factory.TileAssemblyAdvancedWorkbench // buildcraft.silicon.TileAssemblyAdvancedWorkbench
	Block type: ID #0
	Block data value: Unknown? (Got -1)
	Block location: World: (717,56,2109), Chunk: (at 13,3,13 in 44,131; contains blocks 704,0,2096 to 719,255,2111), Region: (1,4; contains chunks 32,128 to 63,159, blocks 512,0,2048 to 1023,255,2559)
Stacktrace:
	at yc.h(World.java:2151)
	at in.h(WorldServer.java:516)

-- Affected level --
Details:
	Level name: RJLand
	All players: 1 total; [iq['Rpvinjumoad'/141, l='RJLand', x=717.56, y=57.48, z=2108.08]]
	Chunk stats: ServerChunkCache: 1067 Drop: 0
	Level seed: 1034236484657392568
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-90,64,329), Chunk: (at 6,4,9 in -6,20; contains blocks -96,0,320 to -81,255,335), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 43749 game time, 137564 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 8946 (now: true), thunder time: 123593 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:680)
	at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
	at bdz.q(IntegratedServer.java:170)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
	at fy.run(SourceFile:849)

-- System Details --
Details:
	Minecraft Version: 1.4.7
	Operating System: Windows XP (x86) version 5.1
	Java Version: 1.6.0_31, Sun Microsystems Inc.
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Sun Microsystems Inc.
	Memory: 304533216 bytes (290 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - Macro / Keybind Mod version 0.9.8
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	AABB Pool Size: 4183 (234248 bytes; 0 MB) allocated, 4183 (234248 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 63
	FML: MCP v7.26 FML v4.7.4.520 Minecraft Forge 6.6.0.497 Optifine OptiFine_1.4.6_HD_U_D2 37 mods loaded, 37 mods active
	mcp [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	FML [Forge Mod Loader] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	Forge [Minecraft Forge] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	CodeChickenCore [CodeChicken Core] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	NotEnoughItems [Not Enough Items] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	mod_ReiMinimap [mod_ReiMinimap] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	PaintingSelGui [PaintingSelectionGui] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	jammyfurniture [Jammy Furniture Mod] (1.4.7_Jammy_Furniture_Mod_V4.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	mod_AnimalBikes [mod_AnimalBikes] (AnimalBikes_1.4.7_ML.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	BiblioCraft [BiblioCraft] (BiblioCraft[v1.1.2].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	BuildCraft|Core [BuildCraft] (buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	BuildCraft|Builders [BC Builders] (buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	BuildCraft|Energy [BC Energy] (buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	BuildCraft|Factory [BC Factory] (buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	BuildCraft|Transport [BC Transport] (buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	BuildCraft|Silicon [BC Silicon] (buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	CameraCraft [CameraCraft] (CameraCraft2.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	ComputerCraft [ComputerCraft] (ComputerCraft1.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	CCTurtle [ComputerCraft Turtles] (ComputerCraft1.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	CustomNpcs [CustomNpcs 1.4.5] (CustomNPCs_1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	EasyColoredGlass [Easy Colored Glass] (EasyColoredGlass[1.4.7.3]) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	mod_Elevator [mod_Elevator] (ElevatorMod1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	NBTEdit [In-game NBTEdit] (Forge_NBTEditv1.4.6.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	StarShadesMods_GlobalBank [GlobalBank] (GlobalBankMod1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	mod_InvTweaks [Inventory Tweaks] (InvTweaks-1.50-1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	MoneyModCore [CJBorCHARLES's Money Mod!] (Money-Mod-V131.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	Paintball [Paintball] (Paintball.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	PortalGun [Portal Gun] (PortalGun1.4.7v5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	QuartzMod [QuartzMod] (QuartzMod_v1.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	RopesPlus [Ropes+] (RopePlus_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	hoboewan_securitymod [Security Mod] (SecurityMod 1.1 (Minecraft Version 1.4.7).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	Staircraftmod [Staircraft] (Staircraftmod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	Steamship [Steamship] (Steamship.v1.2-1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	Teleport [TeleportationMod] (TeleportationMod1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	TorchLevers_HitchH1k3r [Torch Levers] (TorchLeversMC1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	Trapcraft [Trapcraft] (TrapcraftMod1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	WirelessRedstoneCore [Wireless Redstone] (WirelessRedstone.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 1282 (71792 bytes; 0 MB) allocated, 1282 (71792 bytes; 0 MB) used
	Player Count: 1 / 8; [iq['Rpvinjumoad'/141, l='RJLand', x=717.56, y=57.48, z=2108.08]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge,fml'
Hope you can help me, tnx ^_^

**Comment by simon816** [comment]
>  My MC is 1.4.7

??? !!!
Seriously wat

**Comment by Rpvinjumoad** [comment]
yeah, cuz i was supposed to update my MC to 1.6.4 but Some of my buildings are made from this quartz  mod because 1.4.7 has no quartz yet and I have many mods and some are not updating to 1.5.3+

**Comment by simon816** [comment]
If a mod has not updated in two years, consider it dead. Find a replacement or start over.

You're not going to get any support for buildcraft versions less than 6 (MC 1.7.10).

Like, that crash was probably fixed over a year ago, you just haven't updated for a LONG time.

**Comment by Rpvinjumoad** [comment]
well, i did decided yesterday to un-install some dead mods and start all over again like how some servers I entered that decided to move on. K tnx for the advice.

**Comment by Rpvinjumoad** [comment]
Ima just uninstall dead mods today and start building again sometime this month
