### ISSUE TITLE
Robots Continuously Requesting Power

### ISSUE THREAD

**Issue by DoctorToast3** [BuildCraft/BuildCraft#2614]
I have discovered an issue where a Quartz AND Gate will continuously turn a redstone signal on and off if it is set to emit a redstone signal when power is requested and a fully charged robot is docked on its station on a power pipe connected to the gate. Here is an example:
![2015-04-04_17 01 15](https://cloud.githubusercontent.com/assets/11801214/6994824/52e2b4fe-daec-11e4-9bea-66be737b3c88.png)
The issue does not occur when the robots are not on their stations, so I can only assume the robots are requesting power even though they are already fully charged.

**Comment by asiekierka** [comment]
They use a tiny amount of RF/t to sleep.
