### ISSUE TITLE
Quarry in buildcraft 6.4.8 doesn't break tinker's construct bushes

### ISSUE THREAD

**Issue by Staegrin** [BuildCraft/BuildCraft#2618]
The quarry in buildcraft 6.4.8 doesn't break tinker's construct bushes. All other blocks get broken/harvested just not the bushes. Leaving them alone.
![2015-04-07_18 00 59](https://cloud.githubusercontent.com/assets/8494635/7027499/1766e8b2-dd50-11e4-9eb2-c5401a258262.png)
As visible in the screen-shot aluminium and tin oreberry bushes are left untouched by the quarry.

**Comment by Ianaver** [comment]
strange indeed

**Comment by TheJulianJES** [comment]
Not again....

**Comment by Staegrin** [comment]
I remember this being a problem in 1.5

**Comment by Adaptivity** [comment]
Still occurs on 6.4.13. Quarry just ignore them... I'll try 7.0.2 latter

**Comment by Staegrin** [comment]
Just updated to 7.0.8 and berry bushes are still left alone.

**Comment by Staegrin** [comment]
Ore berry bushes are still being ignored in version 7.0.14
![2015-07-12_13 59 19](https://cloud.githubusercontent.com/assets/8494635/8637680/78d99ed4-289e-11e5-9e3b-b4662d72e346.png)
