### ISSUE TITLE
Zone Planners should store maps in blueprints relatively

### ISSUE THREAD

**Issue by AEnterprise** [BuildCraft/BuildCraft#2619]
when recording a zone planner in a blueprint and then rebuilding it somewere else results in the zone planner's map being the one from it's old location

**Comment by asiekierka** [comment]
Yes. Non-trivial to move the data around when building, so this is a low-priority issue.

**Comment by AEnterprise** [comment]
i know it's trivial but just putting it here so eventually once someone has time this can be fixed

**Comment by asiekierka** [comment]
Non-trivial, not trivial

**Comment by AEnterprise** [comment]
most likely not fixed but i guess it could be an easy fix by just changing the handler to not record that info in the blueprint

**Comment by AlexIIL** [comment]
I think this is basically impossible to fix properly (as it could be stored in any inventory). However if its a map used by a gate trigger then maybe it could be -- but its not something I'm too keen on.

**Comment by AEnterprise** [comment]
i think you misunderstood: it's the map in the zone planner GUI that is being stored and loaded

**Comment by AlexIIL** [comment]
*facepalms*

That makes a lot more sense. I think zone planners might want to not store ite themselves, and cache it in a world saved data or something like that.

**Comment by asiekierka** [comment]
The map is no longer stored in the zone planner, but the selected areas still are - obviously - and they need moving to relative coordinates *or* special Builder support.
