### ISSUE TITLE
EEPROMS/ Lua Bios copying in BC adv crafting tables

### ISSUE THREAD

**Issue by n00b7** [BuildCraft/BuildCraft#2623]
![bug](https://cloud.githubusercontent.com/assets/11874683/7073805/f9cd05aa-dec3-11e4-9a28-42d9dc40c3cc.png)

Hello, I am using 
(forge 1291 for 1.7.10)
Open Computers v1.5.6.13
Buildcraft v6.4.8

I think that I have discovered a bug, so i was going to let you know about it.

When i put a eeprom or a Lua bois into an advanced crafting table from BuildCraft. I put the Eeprom or Lua bois into the top of the table. (material crafting area) (the amount doesnt seem to matter.) and I have more stacks down in the slots below. It will make/add more copies of itself if you continue to move the stacks around.

I don't know if this is an issue with BuildCraft or Open computers,
 but i am going to post this in both places. 

Thank you for taking the time to look at this error. :)

**Comment by asiekierka** [comment]
@fneucke? @n00b7?

**Comment by fnuecke** [comment]
The last I heard this was fixed after updating BC? Otherwise I'd have had a look into it.
