### ISSUE TITLE
Oil causes weird transparency glitch

### ISSUE THREAD

**Issue by Geethebluesky** [BuildCraft/BuildCraft#2624]
Hello, please check these screenshots: http://imgur.com/a/hmVod for examples of a visual glitch involving oil transparency. The background spires are Biomes O'Plenty blocks, not visible behind the oil well in the first picture, but I just rotate around a little and they became visible through the oil. The storm particles are from Coros's Localized Weather & Storms mod. I am also using Optifine (1.7.10_U_B5).

I'm reporting this here because the spires aren't visible through the storm particles; it's only with the oil as an added "layer" that this is visible. 

I'm not sure what other settings to provide at this point but I realize there are many, please let me know what would be useful.

**Comment by iTitus** [comment]
I suspect resource pack + Optifine. If you remove the resource pack and Optifine, this will not happen any more.

**Comment by asiekierka** [comment]
Very likely an OptiFine issue.
