### ISSUE TITLE
Stripes Transport pipe cannot place blocks.

### ISSUE THREAD

**Issue by tokoku-11** [BuildCraft/BuildCraft#2629]
Stripes Transport pipe cannot place blocks.
![2015-04-11_15 12 48](https://cloud.githubusercontent.com/assets/7271486/7100446/4dc23852-e05d-11e4-8f53-e05c2a741a68.png)

**Comment by hea3ven** [comment]
This is fixed in the BuildCraft 7 branch, so @asiekierka if you put out another 6.4.x release backport the changes you did to StripesHandlerPlaceBlock in https://github.com/BuildCraft/BuildCraft/commit/36ec39a59e54b709d4cf9222128058a273623887
