### ISSUE TITLE
serverside crash (maybe fluidstack problem with new forge)

### ISSUE THREAD

**Issue by Tsunayoshi** [BuildCraft/BuildCraft#2630]
Hey,
I have got this crash on right-click a combustion engine

I have many mods with problems with new forge >1355 because of the removed fluidstack
Maybe this is it here, too but the crash-report didn't look like the other mods crash-report. So I am not sure:
http://pastebin.com/p0qLVF87
(tested 2x)

buildcraft-6.4.10
buildcraft-compat-6.4.2
forge-1.7.10-10.13.3.1370-1.7.10

**Comment by asiekierka** [comment]
FORGE 1355 WHY ARE YOU SO CRUEL TO ME

6.4.11 incoming

**Comment by Tsunayoshi** [comment]
Thanks a lot!!!
