### ISSUE TITLE
[Bug 6.4.10] Quarry completely bugs out if the game is closed normally

### ISSUE THREAD

**Issue by VileTouch** [BuildCraft/BuildCraft#2636]
i won't go into much detail, as it is a known bug, just wanted to let you know that it's still there. it won't work until anything related to the quarry is removed and the game is closed. then the second time it "might" work. replacing the quarry without closing the game has no effect, as you already know.

**Comment by asiekierka** [comment]
@VileTouch - No, I don't know any of these.

**Comment by VileTouch** [comment]
as a test, set up a quarry in a SP world (so it doesn't keep running in a server somewhere) and let it build the frame. as it starts working close the game normally (quit to menu, then quit game). probably kill the hidden java process afterwards (sometimes it just stays running for no reason)

now start the game again and look at the quarry. try breaking it and placing it (and the markers) again. nothing yet? exactly. now it's stuck.

same thing happens with engines sometimes.

**Comment by psxlover** [comment]
Can you post some screenshots?

**Comment by VileTouch** [comment]
sure, but that will be next time i log in here. (tomorrow night)

**Comment by VileTouch** [comment]
alright, so yesterday i was unable to glitch the quarry by logging off while it's working,
however, a different kind of glitch happened today.
-pic-
let me explain. after that happened i removed buildcraft, along with a bunch of other mods that were not getting much use, later on i updated some of the remaining ones, so my mc environment is quite different than it was last month. that's why i was surprised that it didn't seem to trigger the glitch as reliably as it used to.
-pic-
but today, i decided to leave the quarry running (chunkloaded), and go to my void age to make some more cable and another tesseract. I return to this:
-pic-
turns out the quarry decided to stop accepting connections almost completely (energy cables still work)
-pic-

but wait. there's more: the first time i deployed the quarry, i did so with an item conduit (as i always had ). the second time i used a tesseract and it **did** work. now neither establish connection.
-pic-

to be fair, gold pipes seem to connect, but i always make a point NOT to use bc pipes. ever. so i didn't test that any further.

what ended up working was this:
-pic-

but then another wild glitch appeared. thankfully it's a benign one:
-pic-

sometimes after hitting a spot of lava, the quarry head will get stuck in place, but keep digging normally. this is the opposite of the original glitch. that the crane would move and consume energy, but the head would be retracted in an awkward way and not dig anything.

(uploading pics. will edit the post later. posting as is so you have something to chew on in the mean time)

**Comment by EntropicPariah** [comment]
I've seen the head get stuck today and it continued breaking blocks and that was after a fresh client restart and world load. As for the anomaly with the quarry barfing out blocks like that, I simply set it up like this: Quarry>1 BC pipe>Chest then I use enderIO item conduit for the rest. Haven't had a single problem since I started setting them up like that.

**Comment by asiekierka** [comment]
Please re-open if it still happens in 1.8.x.
