### ISSUE TITLE
Wooden pipes drain massive energy from surrounding power cables

### ISSUE THREAD

**Issue by LightningLdr180** [BuildCraft/BuildCraft#2638]
After hours of trying to figure out where all my power was going, I found out that I inadvertantly had a Mekanism Universal Cable next to a wooden fluid pipe that was pumping liquid.  I have tested this on a single player server with just a wooden fluid pump hooked up to a tank.  It happens with both Fluxducts from Thermal Dynamics, and Universal Cables from Mekanism.  The wooden pump does function from this energy, but it is using approximately 1 million RF/sec.

Buildcraft 6.4.11
Buildcraft Compat 6.4.2

**Comment by asiekierka** [comment]
The wooden fluid pipe cannot physically take in more than 400 RF/sec in the absolutely worst case. Strange.
