### ISSUE TITLE
[7.0.1] Quarry doesn't work

### ISSUE THREAD

**Issue by AgentK9** [BuildCraft/BuildCraft#2642]
Screenshot: https://drive.google.com/open?id=0BzK_G4me5sh7fkVxdHoydTlpUHdzemlObjl4eDllZ0VxQ1Z4Wnp5bjZvNnpwemk5TEdvNkk&authuser=0

I have three creative engines, all set to 1280 RF/t, all on, and all directly inputting into the quarry, with a chest on top. And it does not work.

**Comment by AgentK9** [comment]
it starts all fine, puts up all of the framing, but does not spawn the mining arm

**Comment by Sp3rw3r** [comment]
For me the quarry does not work either. I just tried. For me it spawned the mining arm. About 32 blocks outside the quary. And it does not move.

**Comment by AEnterprise** [comment]
this sounds suspiciously familar

**Comment by Sp3rw3r** [comment]
One step back, 2 steps forward. Hopefully.

**Comment by Sp3rw3r** [comment]
I like the red light saying it has no work. Will be awesome when everything works again.

**Comment by AEnterprise** [comment]
found it: https://github.com/BuildCraft/BuildCraft/issues/1640
