### ISSUE TITLE
Emerald Fluid Pipes and NBT fluids

### ISSUE THREAD

**Issue by soundlogic2236** [BuildCraft/BuildCraft#2647]
Emerald fluid pipes don't seem to be able to pull nbt fluids, even when given the same fluid in a bucket.

**Comment by asiekierka** [comment]
@soundlogic2236 - example of such a fluid?

**Comment by soundlogic2236** [comment]
Witchery brews.

**Comment by asiekierka** [comment]
@soundlogic2236 I'll need a better example.

>This Mod may not be decompiled, reproduced and/or modified under any circumstances without prior written permission of the Owner. This Mod is not open source.

Go complain to Emoniph. I'm not going out of my way to provide mod compatibility for mods which actively refuse it.

Issue still open as someone might have a better example.

**Comment by ganymedes01** [comment]
Should be easy to fix tbh.
On the extractFluid method just change:
```JAVA
Fluid targetFluid = FluidUtils.getFluidFromItemStack(filters.getStackInSlot(0)):
```
to
```JAVA
FluidStack targetFluid = FluidUtils.getFluidStackFromItemStack(filters.getStackInSlot(0)):
```

And it should just work

**Comment by ganymedes01** [comment]
Tested with my own FluidStacks with NBT tags and the above works flawlessly :3
