### ISSUE TITLE
fluid pipes crash bug

### ISSUE THREAD

**Issue by minpav** [BuildCraft/BuildCraft#2648]
You can see the log on attached image.
![screenshot 2015-04-19 08 57 14](https://cloud.githubusercontent.com/assets/12015515/7218496/353ec776-e672-11e4-8ea8-d68d4b35d3b1.png)

It may seem like a bug of the better barrels mod (jabba), but if I remove it the game crashes again and in the crash log is different mod. It started crashing after I build cobblestone fluid transport pipes and when I removed them with MCEdit it stopped crashing.

(From the log it looks like the renderer for pipes doesn't stop tesselating sometimes.)

**Comment by TheJulianJES** [comment]
What BC version are you using?

**Comment by iTitus** [comment]
Do you have Optifine installed?

**Comment by asiekierka** [comment]
Eh? Strange.

**Comment by minpav** [comment]
I had 6.4.10 and I tried updating to 6.4.11. Problem was in both. And yes, I have Optifine (version OptiFine_1.7.10_HD_U_B5)

(Minecraft 1.7.10)

**Comment by asiekierka** [comment]
What fluid was in the pipe, if any?

**Comment by minpav** [comment]
There wasn't any. I was just preparing it and it crashed during building.

**Comment by iTitus** [comment]
I blame Optifine

**Comment by AEnterprise** [comment]
yeah, this is the same bug someone reported on the BCA issuetracker last week, removing optifine fixed it

**Comment by minpav** [comment]
I'll try it

**Comment by minpav** [comment]
Solved.

**Comment by LukasKaua** [comment]
Me Is Happening The Same Thing, But Do not Have The Optifine
Link Of Mods: C: \ Users \ valdeir \ Pictures \ Capturar.MHT

**Comment by LukasKaua** [comment]
Me This Acontesendo The Same Thing, So What Not I The Optifine
Link Of Mods From List : http://prntscr.com/7h2ijt

**Comment by Maerecque** [comment]
So in 2021 this issue still exists and hasn't been fixed ever since?

**Comment by AEnterprise** [comment]
don't necrobump old issues, also if you actually read what people say it's an issue with optifine or another mod messing with rendering

**Comment by asiekierka** [comment]
Specifically, it's an issue with OptiFine's multi-threaded rendering patches - the rendering pipeline pre-1.8 is not designed to be threaded in this manner, and so some mods (BuildCraft, TCon, ...) will crash with them. Should work fine with said multi-threaded rendering patches disabled or such variants not used, however.
