### ISSUE TITLE
server crash after resetting nether; buildcraft fluid issue on joining (when in nether)

### ISSUE THREAD

**Issue by Nick-77ab2** [BuildCraft/BuildCraft#2649]
Block being updated error: # 571 Tile.blockOil // buildcraft.energy.BlockBuildcraftFluid
complete crash: http://pastebin.com/BrFxDiNH
idk how to fix, i've tried so many things and since im in the nether there's no way i can join the world without the server crashing.
might just be minecraft, but i still don't know how to fix it, so any actual help would be appreciated :D

**Comment by asiekierka** [comment]
Disable oil explosions in the config for now.

**Comment by Nick-77ab2** [comment]
thank you!

**Comment by Nick-77ab2** [comment]
i can't find oil explosions in the main config, is it burnOil?

**Comment by asiekierka** [comment]
Might be. Not sure.

**Comment by Nick-77ab2** [comment]
it was
