### ISSUE TITLE
Is this a problem with BC or Logistics Pipes?

### ISSUE THREAD

**Issue by StarkRG** [BuildCraft/BuildCraft#2652]
As soon as a logistics fluid satellite pipe (or, apparently an extraction pipe, though I haven't experienced this) is placed in a world (whether it's a new one or an old one) the following crash occurs: http://pastebin.com/vW5K77a1

https://github.com/RS485/LogisticsPipes/issues/662

The LP folks have been thinking it's a problem with other mods (ie, not LP), so I removed everything I possibly could (with the exception of NEI which, as far as I know, doesn't create fluids). Since BC is a dependency of LP I couldn't remove it, therefore leaving a question about who's actually at fault.

Alternatively it could be an incompatibility with forge versions (especially given that there has been a lot of changes to forge fluids over the last few days and weeks), but I'm not really sure which forge version to try (the recommended version is way too out of date to be much use).

**Comment by AEnterprise** [comment]
this is a LP issue not a BC issue, there have been changes in the way the fluidregistry works in the lastest versions of forge, LP needs to update

**Comment by asiekierka** [comment]
LP. Downgrade to Forge 1307 or something for now, but then another mod might need an upgrade so we can't do anything about it.

**Comment by theZorro266** [comment]
@asiekierka are those changes compatible with Forge version 10.13.2.1291 ? cc @davboecki

**Comment by asiekierka** [comment]
@theZorro266 - the way BC did them, yes. the way other mods did, probably not.
