### ISSUE TITLE
buildcraft builder in 6.4.11 not working

### ISSUE THREAD

**Issue by alundai159** [BuildCraft/BuildCraft#2653]
when powering the builder the blueprint (and the black version) just enter the inventory of the builder. it doesn't build, it doesn't clear, it just puts the blueprint in the inventory where the building materials are. i've tried with different types of engines, i've tried with tesseracts, conduits and getting the power from my big reactor. i've tried big builds and small builds (going as small as something that is a 3 by 3 containing 16 blocks. it just doesn't do annything. was the builder disabled in 6.4.11 because i've seen people on youtube using it again, after the verry long disabled period.

**Comment by asiekierka** [comment]
Uh? Could you export the blueprint and send it to me?

If it puts it in the inventory, it means the blueprint is corrupt and/or otherwise invalid.

**Comment by alundai159** [comment]
i've tried it with multiple blueprints (all freshly crafted) and i've also tried it with multiple templates. the second i connect the power the blueprint/template just go's into the builders inventory.

**Comment by AgentK9** [comment]
Are you sure the architect actually recorded the blueprints? How long does it take for the architect to make them?

**Comment by alundai159** [comment]
a second or 2 i'm even naming it.

**Comment by asiekierka** [comment]
@alundai159 - Could you try 6.4.13?
