### ISSUE TITLE
Incorrect version within buildcraft-compat-6.4.2.jar

### ISSUE THREAD

**Issue by spannerman79** [BuildCraft/BuildCraft#2654]
mcmod.info reports the incorrect version number
updated mcmod.info https://gist.github.com/spannerman79/ac1c1a444df4f031bd54

**Comment by asiekierka** [comment]
Not a huge enough issue to care. I'll just fix it the next time I compile.

**Comment by AEnterprise** [comment]
@asiekierka you can just use $version and gradle should replace it with the version it's using
https://github.com/BCA-Team/Buildcraft-Additions/blob/2.1.x/src/main/resources/mcmod.info#L6

**Comment by psxlover** [comment]
That's what he is doing... https://github.com/BuildCraft/BuildcraftCompat/blob/master/resources/mcmod.info

**Comment by spannerman79** [comment]
I know its not a huge issue @asiekierka its just less console spam to go through if there is an issue.  Even more so with solder (solder.io) potentially hooking into Not Enough Mods listing ( https://bot.notenoughmods.com/ ) which reads the mcmod.info within the jar
