### ISSUE TITLE
High bandwidth with only 1 BC Pump.

### ISSUE THREAD

**Issue by tommydrum** [BuildCraft/BuildCraft#2655]
![stuff](https://cloud.githubusercontent.com/assets/950485/7265534/4ac81de2-e850-11e4-9964-c6458d930525.png)

My little FTB Infinity server isn't doing too much, not complaining, not exactly an issue, but I thought I'd let you know. It's just using more than 35x the next largest mod that's talking between client/server.

**Comment by Kubuxu** [comment]
IMHO `462B/s` is not much but if it is scaling it might be a problem.

**Comment by Thog** [comment]
@Kubuxu Yes but it's only with one pump...

**Comment by asiekierka** [comment]
16.4/s? The pump must be going down...

**Comment by tommydrum** [comment]
Thank you for clarifying this, I thought this might be a problem, but if the pump was in an animation of going down, this makes complete since.
