### ISSUE TITLE
Quarry error

### ISSUE THREAD

**Issue by Badcholo** [BuildCraft/BuildCraft#2657]
buildcraft-6.4.13
I have uploaded a clip of the error since there is no crash report.
I'll do more testing and see if i can find out what is causing this.
I do have other mods installed, so i'll try and see if it is one of them.
I did break some blocks and it started again, but stopped, i was able to finish by 
breaking the blocks a few times.
https://www.dropbox.com/s/dnlsvtsqsdnlhy7/Buildcraft%20error.avi?dl=1

**Comment by asiekierka** [comment]
Known issue, most likely. Can't see the video as I'm on mobile. Sounds like the ghost blocks bug.

**Comment by asiekierka** [comment]
File deleted. I probably know this issue.
