### ISSUE TITLE
Robots popping off and dropping items

### ISSUE THREAD

**Issue by seppitm** [BuildCraft/BuildCraft#2658]
Hi, im using the BC Robots intensively, they litterally play minecraft for me :-). 
Sometimes a robot don't come back to his station, the station turns green and the robot popping off at the place he currently idle. My picker picks them up, thats not the problem but it where cool if you can pop them at the station in case of an error. 

Also the delivery and the crafting bots sometimes dropping items in my base XD

maybe the reason: 
I'm using the robots in the underground they have a 1x1 hole to the overworld

**Comment by hea3ven** [comment]
Do they have a suitable place to recharge?

**Comment by marcin212** [comment]
I have a robot which collects eggs and feathers from the farm chickens. The robot is able to charge again, but somtimes not. I don't know why.

**Comment by seppitm** [comment]
yes they have everyhing

**Comment by marcin212** [comment]
https://dl.dropboxusercontent.com/u/25172450/8c4340a6f1a1b55c59ada8ad42fd63a2.png

**Comment by hea3ven** [comment]
@seppitm what version of buildcraft are you using?

@marcin212 that's BC7, right?, definately a different issue than seppitm's one.

**Comment by marcin212** [comment]
@hea3ven  BC7 (special build from asie)

**Comment by asiekierka** [comment]
@hea3ven - latest github as of right now

**Comment by seppitm** [comment]
@hea3ven i'm using 6.4.11

**Comment by psxlover** [comment]
@marcin212 Is both the robot working area and the station on chunks being kept alive by a chunk loader?

**Comment by Kubuxu** [comment]
@psxlover marcin212 was AFK on that roof while the robot died out.

**Comment by asiekierka** [comment]
@marcin212's issue seems to have been fixed, how about @seppitm's? @hea3ven?

**Comment by hea3ven** [comment]
Not sure, the only reasons for robots popping off are running out of energy, or the station being removed/not found in the registry.

@seppitm could you post screenshots of your docking stations and the gate configurations?

**Comment by seppitm** [comment]
Minecraft version: 1.7.10
Forge version: 10.13.3.1395ls
Buildcraft version: 6.4.14
Server type: Vanilla with forge installed
Installed Mods (233): http://goo.gl/TqHocZ
Robot setup gallery: http://imgur.com/a/M6jI0#0
Every station is in the working area.

**Comment by hea3ven** [comment]
Both this issues might be the same as #2715 , try with BuildCraft 6.4.16.

**Comment by asiekierka** [comment]
Closing as BC 6.4 is slowly going out of support and we haven't gotten any input.
