### ISSUE TITLE
Leaf cutter's don't react to go to station signal

### ISSUE THREAD

**Issue by seppitm** [BuildCraft/BuildCraft#2659]
The Leaf cutter don't come back to the station.

**Comment by AgentK9** [comment]
what version?

**Comment by seppitm** [comment]
6.4.11

**Comment by asiekierka** [comment]
@hea3ven ?

**Comment by hea3ven** [comment]
What is the leaf cutter doing? is it moving?

**Comment by seppitm** [comment]
one of them stands infront of a tree for like one hour and the other is cutting

**Comment by asiekierka** [comment]
Cauldron?

**Comment by seppitm** [comment]
Minecraft version: 1.7.10
Forge version: 10.13.3.1395ls
Buildcraft version: 6.4.14
Server type: Vanilla with forge installed
Installed Mods (233): http://goo.gl/TqHocZ
Robot setup gallery: http://imgur.com/a/M6jI0#0
Every station is in the working area.

**Comment by hea3ven** [comment]
Did, by any chance, the shears broke and the robot didn't have anywhere to get new ones from?

**Comment by asiekierka** [comment]
No input - closed.
