### ISSUE TITLE
[BC 7.0.1] Unable to Run the Core and Transport Modules together without also adding the Silicon Module

### ISSUE THREAD

**Issue by mallrat208** [BuildCraft/BuildCraft#2661]
Forge 10.13.3.1391
BuildCraft 7.0.1 [Core, Transport]

Upon trying to launch the game with just Forge and BC Core and Transport, the Client Crashes due to it being unable to find the ItemRedstoneChipset class.

I've got a log of it here; https://gist.github.com/mallrat208/2042a448ec196ce9fc90

Installing the Silicon module allows the client to load properly.

**Comment by AEnterprise** [comment]
inteded, the transport module needs silicon to work (for the gates)

@asiekierka could you edit the mod annotation so forge knows silicon is required for transport so it gives a message instead of crashing?

**Comment by mallrat208** [comment]
I was under the impression that it only needed the Silicon Module for the Gate Recipes but should otherwise work fine as the actual logic for the gates is self contained to the Transport Module.

https://github.com/BuildCraft/BuildCraft/blob/6.5.x/common/buildcraft/BuildCraftTransport.java#L72

Near as I can tell it only requires the Silicon Module because of how the Chipsets are referenced for the recipes.
