### ISSUE TITLE
(Minor) Missing localization

### ISSUE THREAD

**Issue by Adaptivity** [BuildCraft/BuildCraft#2665]
Found in 7.0.2 beta:
1) item.Facade.state_hollow
2) item.tablet.name
3) item.redstone_chipset_chipset.name
4) tile.buildToolBlock.name
5) tile.blockRedPlasma.name
6) tile.pipeBlock.name
Can you give them names or hide them from NEI if they are not needed? (There are an API function exist in NEI for that)

**Comment by asiekierka** [comment]
Fixed to the extent I felt is necessary.
