### ISSUE TITLE
LWC and Buildcraft

### ISSUE THREAD

**Issue by SebasvanDuuren** [BuildCraft/BuildCraft#2666]
for some reason when building the quarry the builder removes the lwc locked blocks but when a quarry goes mining it does not remove the lwc locked blocks.. is there something wrong with the permissions? 

Versions: 
Minecraft 1.7.10
buildcraft-6.2.6
LWC 4.5.0-SNAPSHOT/4.4.0
Cauldron 1.7.10
Forge 10.13.2.1277

Here is a video that shows what I mean:
https://www.youtube.com/watch?v=z83zLczgxcc

- Sebas

**Comment by asiekierka** [comment]
BuildCraft 6.2.6 did not have full permissions support - upgrade to the latest version.
