### ISSUE TITLE
Updated my Buildcraft

### ISSUE THREAD

**Issue by SebasvanDuuren** [BuildCraft/BuildCraft#2667]
Hey, Today I updated my buildcraft from 6.4.6 to 7.0.2 but I get an error in the server and in the client.
I never had any errors when I had 6.4.6 installed

Client error: http://pastebin.com/9Axrc2L3
Server error: http://pastebin.com/g1Kw5j3S

- Sebas

**Comment by asiekierka** [comment]
Don't use betas that quickly. LogisticsPipes 0.8 is not compatible with BuildCraft 7.

Also, make backups - you cannot revert from BC7 to BC6 if you ever make the move, so I recommend you wait for it to go stable.
