### ISSUE TITLE
Sleeping robots.

### ISSUE THREAD

**Issue by marcin212** [BuildCraft/BuildCraft#2668]
Robot was working and even charged properly. After some time it started sleeping and the wake up call does not work.

https://dl.dropboxusercontent.com/u/25172450/bugs/bc/7285ee2935a93016eeb758eebd8a73e9.png

https://dl.dropboxusercontent.com/u/25172450/bugs/bc/a1869e2c5808fb1945f140863aa2091b.png

https://dl.dropboxusercontent.com/u/25172450/bugs/bc/c01f88bf0977780495529f0b595d60b7.png

**Comment by asiekierka** [comment]
Caused by the docking station TE invalidating before robots were, and robot NBT saving checking linkedDockingStation and not Index (which was null by then).
