### ISSUE TITLE
Clay pipes losing items

### ISSUE THREAD

**Issue by marcin212** [BuildCraft/BuildCraft#2669]
Items keep falling out of clay pipes. I pump items out with iron pipes and a pulsar gate on each slot. Clay pipes hooked up to vanilla furnaces.

**Comment by asiekierka** [comment]
Screenshot? Can't get on your server from school...

**Comment by marcin212** [comment]
http://i.gyazo.com/db31336540d5e1b46c34758b68dba7a9.png

**Comment by asiekierka** [comment]
Fixed via https://github.com/BuildCraft/BuildCraft/commit/9a21a93a1d652aaf08a852d2f4a7f77f248eec40
