### ISSUE TITLE
Delivery robots carry only one item at the time.

### ISSUE THREAD

**Issue by Kubuxu** [BuildCraft/BuildCraft#2671]
It is due to this [line](https://github.com/BuildCraft/BuildCraft/blob/6.5.x/common/buildcraft/robotics/boards/BoardRobotDelivery.java#L56). The delivery robot only takes one item at a time which renders them extremely weak.

**Comment by hea3ven** [comment]
Yes, the problem is that requests are made one item at a time too. There is no way to specify a bigger request.

**Comment by asiekierka** [comment]
@hea3ven - The request system in general needs a rewrite, for multiple reasons:

1. I want a system of requesting that's independent of robots, for instance so Logistics Pipes or AE2 can cooperate with Builders better.
2. It's kinda eh.
