### ISSUE TITLE
[Feature] 3-pointed gear instead of pick for quarry/mining well

### ISSUE THREAD

**Issue by AgentK9** [BuildCraft/BuildCraft#2674]
Especially if you have TCon installed, you usually want a TCon pick for stuff. Because TCon does not use diamonds as materials, it uses them as a modifiers, I think you should make a recipe for a three-pointed gear. it will cost the same amount of diamonds/iron, but will not use a pickaxe. (config option?) (This will be helpful for ModPack creators)

**Comment by iTitus** [comment]
So you are requesting a type of gear that should be used in crafting recipes instead of a pickaxe?

**Comment by asiekierka** [comment]
You usually want to use MineTweaker for recipes fitting different mods better.

**Comment by Techokami** [comment]
This. I'm using MineTweaker to change the Quarry recipe to use a Manyullyn (or however it's spelled) shuriken instead of a diamond pick. This makes quarries locked to endgame, which is fitting for how powerful they are.

Sent from my Windows Phone
________________________________
