### ISSUE TITLE
Builder should have more pages

### ISSUE THREAD

**Issue by Platypus007** [BuildCraft/BuildCraft#2675]
I made a complex blueprint with a lot of type of materials, When i put the blueprint into the builder i can't see all the needed materials, because it's more than the builder has space for. So i thought, it would be awesome, if you guys could make more pages there, and we could switch between them, to check, if we have everything what is needed.

**Comment by KiakahaEvans** [comment]
a quick solution would be to split the template up into parts but yeah I agree we shouldn't be limited just because the builder can't display the whole schematic.

**Comment by asiekierka** [comment]
https://github.com/BuildCraft/BuildCraft/commit/d732d4ee11ff7319ef07cd6c3bd1389aeb0bdfa9
