### ISSUE TITLE
Energy pipe enchancement

### ISSUE THREAD

**Issue by DrSoda** [BuildCraft/BuildCraft#2676]
The beam in energy pipes should be red as they transfer REDstone flux. This has been bugging me since the switch to RF

**Comment by asiekierka** [comment]
Red is a color naturally associated with error, warning; light blue not only looks a lot better, it's also a lot more "glow"-y than red and a lot more postiive.

**Comment by iTitus** [comment]
As we all know: Electrons are blue and protons are red :P
