### ISSUE TITLE
Lumberjack cuts wood outside of area.

### ISSUE THREAD

**Issue by Kubuxu** [BuildCraft/BuildCraft#2677]
We have work area specified by Map Location of land marks. The lumberjack is cutting wood outside of designated area.

**Comment by Sp3rw3r** [comment]
Same:

![](http://i.imgur.com/TgenjwS.png)

![](http://i.imgur.com/YGbZrMv.png)

**Comment by laz2727** [comment]
Try the area planner.

2015-04-29 14:22 GMT+06:00 Sp3rw3r <notifications@github.com>:

**Comment by Kubuxu** [comment]
@laz2727 last time I used Zone Planner it worked but I want to use 3D designated area.

**Comment by Sp3rw3r** [comment]
I just tried the area planner with a 5x5 area. The lumberjack ignored the work area.
I had marked out an area with red wool. It showed white in the zone planner.
