### ISSUE TITLE
Auto workbench not working properly with logistical transporter

### ISSUE THREAD

**Issue by dominx** [BuildCraft/BuildCraft#2678]
Auto workbench does not start crafting when receiving too many ingredients in one packet. I've tested and it crafts chests only if it receives 11 or less planks at a time. Same goes for glowstone block recipe but here the number is 22. The crafting starts when the bench receives few enough item if it got too many before. There seems to be no problem when there is item filter set on logistical sorter to send no more than that. There seems to be no problem with recipes using more than one ingredient, I've tested just a few.

I'm using Regrowth 0.7.4 (buildcraft 6.4.7 Mekanism 1.7.10 7.1.2.185)

I understand this might be Mekanism bug.

**Comment by asiekierka** [comment]
The auto workbenches were rewritten in BuildCraft 7 and, quite honestly, I do not feel like fixing the BC6 ones too much.
