### ISSUE TITLE
[Suggestion] QuarryPlus functional.

### ISSUE THREAD

**Issue by anishin** [BuildCraft/BuildCraft#2681]
Hello.
Now mod QuarryPlus is incompatitible with latest Buildcraft. And development of this mod goes very slow (one build per month for old Buildcraft) or stops at all.

Maybe, you can implement some functional of this mod into Buildcraft. (For example, make quarry capable to dig with fortune of silktouch).

And thank you very-very-very much for your work!
P. S. Sorry for my English. I'm from Russia.

**Comment by asiekierka** [comment]
The Quarry is already crazy powerful as it is.
