### ISSUE TITLE
Buildcraft compat crashes when NEI not installed

### ISSUE THREAD

**Issue by Sp3rw3r** [BuildCraft/BuildCraft#2682]
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2-5-15 18:02
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: buildcraft/compat/nei/RecipeHandlerBase

Workaround: install NEI

**Comment by Kubuxu** [comment]
BuildCraft Compat has its own issue tracker.

**Comment by Sp3rw3r** [comment]
Will use that next time.

**Comment by iTitus** [comment]
Can be closed, copied it to Buildcraft/BuildcraftCompat#13
