### ISSUE TITLE
Robots without work area lost

### ISSUE THREAD

**Issue by Sp3rw3r** [BuildCraft/BuildCraft#2683]
I had a butcher and picker without work area.
They went too far and I lost them.
I think a default work area around the docking station would be nice.

**Comment by laz2727** [comment]
Have you TRied return to base action?

**Comment by asiekierka** [comment]
What version?

**Comment by Sp3rw3r** [comment]
7.0.3.
It's more a suggestion then a bug I suppose. It is not an issue when I define a work area.

**Comment by asiekierka** [comment]
@hea3ven - perhaps set a default work area as a radius from the docking station?

**Comment by hea3ven** [comment]
I dunno, l think that creating a big area with the zone planner is easy enough, and adding a default work area removes valid setups, where the users take advantage of the robot's independence, as few as they might be.

@Sp3rw3r If you have access to creative you can find the exact position of the robots using the debugger on the docking stations. If you are in survival you can leave the "go to station" action active and run around the perimeter of your base till you load the chunks where the robots are.

**Comment by Sp3rw3r** [comment]
I guess this issue can be closed. I hope things like this get covered in the wiki or a video tutorial.
