### ISSUE TITLE
Requester robot drops item when request already fullfilled

### ISSUE THREAD

**Issue by Sp3rw3r** [BuildCraft/BuildCraft#2685]
If somehow a request gets fulfilled while a requester robot has picked up an item, the item will be dropped.

I had a picker that I changed filter. It immediately went to a drop off location to get rid of the now invalid items. Is something like that possible with the requester too?

**Comment by hea3ven** [comment]
Are you sure there was a valid drop point in the robot's working area, that wasn't occupied?, the delivery bot should only drop items to the ground if it doesn't find anywhere to put them.

**Comment by Sp3rw3r** [comment]
Oops. My bad.
