### ISSUE TITLE
Server with BC7.0.3 and BCCompat 7.0.1 Crash on boot

### ISSUE THREAD

**Issue by TheMrCaveman** [BuildCraft/BuildCraft#2686]
Server won't boot anymore after updating to BC7

See http://pastebin.com/KGKxkt7i cauldron test server

See http://pastebin.com/sdLmb3Bi Latest forge test server

**Comment by Kubuxu** [comment]
Official release of forestry is not compatible with BC7 use dev branch or use BC6.

**Comment by asiekierka** [comment]
It's a beta for a reason.
