### ISSUE TITLE
CRASH BUILDCRAFT 4.2.2 - 1.6.4 LATEST 

### ISSUE THREAD

**Issue by ArtutoGamerYT** [BuildCraft/BuildCraft#2688]
I opened my modified Minecraft (1.6.4) and Mojang loading screen, the game was closed and this error appeared.

Crash: http://pastebin.com/8Y0KuYJ2

You can help me ????

PS: If you're going to say that updates to 1.7.10, do not comment :)

**Comment by AEnterprise** [comment]
BC is trying to create a facade from a non facadable itemstack, try blacklisting the mods one by one in the config to find the cullput and keep that blacklisted, other then that nothing we can do about it as you're on an older version, more recent versions have protection against that iirc

**Comment by asiekierka** [comment]
I'll look into it **if** I can get a 1.6.4 instance working still. Seems like a trivial bug to fix.

**Comment by ArtutoGamerYT** [comment]
Okay

I checked my mods and the crash maker is Golem World Mod... But, this mod
only adds:

The golems (entity)
Paper of awenking (item)
And nothing block!!

**Comment by AEnterprise** [comment]
it is possible BC is trying to make a facade out of the item or maybe there are blocks you can't see that it adds

**Comment by ArtutoGamerYT** [comment]
How i detect that in the BC config of the Golem World config?

**Comment by AEnterprise** [comment]
blacklist only the item, if it doesn't crash it's the item causing the issue

**Comment by ArtutoGamerYT** [comment]
Okay
