### ISSUE TITLE
Mekanism incompatibility

### ISSUE THREAD

**Issue by vl20100** [BuildCraft/BuildCraft#2689]
Hi,

I have a problem concerning the compatibility with Mekanism. I setted the Mekanism energy type in MJ in the config file but the cables don't link my quarry.

I'm using Buildcraft 6.4.14 and I tested with Buildcraft 7.0.3 Beta. I'm using Mekanism 8.1.2.229 with Mekanism Generators and Mekanism Tools from the same version.

Is it a bug or is it my configuration ?

Below : some screenshots in creative.

![2015-05-04_09 14 06](https://cloud.githubusercontent.com/assets/11457015/7449966/be64a2e0-f23f-11e4-8b0f-c7db367bacce.png)
![2015-05-04_09 14 24](https://cloud.githubusercontent.com/assets/11457015/7449967/be67d3d4-f23f-11e4-9564-f5520bcb78d4.png)
![2015-05-04_09 14 34](https://cloud.githubusercontent.com/assets/11457015/7449968/be70121a-f23f-11e4-8098-16d8de91c7bd.png)
![2015-05-04_09 17 28](https://cloud.githubusercontent.com/assets/11457015/7449969/be71bf5c-f23f-11e4-9d0d-df1f124b34ac.png)
![2015-05-04_09 17 45](https://cloud.githubusercontent.com/assets/11457015/7449970/bec2855e-f23f-11e4-9ba0-0bd281fd8d3d.png)

Thank you for your help.
Regards,

vl20100

**Comment by asiekierka** [comment]
MJ is dead. Use RF.

**Comment by vl20100** [comment]
I'm now using RF and it doesn't work.

**Comment by LouisHutch** [comment]
https://github.com/aidancbrady/Mekanism/issues/2401
It is an issue on mekanism's end. It requires COFH Core at the moment.
