### ISSUE TITLE
World gets corrupted when robots turned on a few hours

### ISSUE THREAD

**Issue by seppitm** [BuildCraft/BuildCraft#2690]
Minecraft version: 1.7.10
Forge version: 10.13.3.1395ls
Buildcraft version: 6.4.14
Server type: Vanilla with forge installed
Installed Mods (233): http://goo.gl/TqHocZ
Robot setup gallery: http://imgur.com/a/M6jI0#0
Every station is in the working area.
The workingarea is loaded with a chunkloader.

I have found a strange bug. When i turn the robots on and log off, the world gets corrupted a few hours later. but if i play while the robots are working, everything is fine. Maybe it's a fault from another mod, but its verry interesting.

**Comment by hea3ven** [comment]
Do you have a crash log from the corrupted world?

**Comment by seppitm** [comment]
yes: https://pastee.org/pmpdy

**Comment by asiekierka** [comment]
It's a known issue, but it's not known which mod causes it. @marcin212 has a fix for it.

**Comment by marcin212** [comment]
@seppitm http://starchasers.pl/OpenGlasses/doku.php?id=cmf
