### ISSUE TITLE
Filler doesn't drop items

### ISSUE THREAD

**Issue by ExDomino** [BuildCraft/BuildCraft#2692]
On my server, the filler doesn't drop items when it clear an area. Does it exist a way to make it drop items as before? My players need that this way. Thank you in advance.

**Comment by KiakahaEvans** [comment]
It's a config option which is disabled by default. you just have to go turn it on mate.

**Comment by asiekierka** [comment]
The config option is temporaily useless, broken in 6.0. It will be restored in BC 7.

**Comment by ExDomino** [comment]
And BuildCraft 7 will be only for 1.8 ?

**Comment by asiekierka** [comment]
Only for 1.7.10.

**Comment by ExDomino** [comment]
Ok, so we'll be patient and wat for BC 7.0.4.

**Comment by TheJulianJES** [comment]
@ExDomino It will probaly take some time (if BC update to 1.8) to update to 1.8 ;)

**Comment by ExDomino** [comment]
It's useless to update to 1.8 because nothing in 1.8 cannot be found in 1.7.10, even the three new rocks are added by Chisel. ^^

**Comment by TheJulianJES** [comment]
@ExDomino Slime Blocks :P?

**Comment by asiekierka** [comment]
@TheJulianJES - yes, Pistronics 2

**Comment by ExDomino** [comment]
And Tinker Construct with their slime islands.

**Comment by leSamo** [comment]
I am pretty sure 1.9 will be out sooner than buildcraft would took to update to 1.8.

**Comment by AgentK9** [comment]
gany's surface adds a whole bunch of 1.8 stuff and more

**Comment by liach** [comment]
Thog was doing [that] (https://github.com/Thog/BuildCraft) but the impatient French guy abandoned. Whoops poor.

**Comment by asiekierka** [comment]
We were working on it together, but we gave up.
