### ISSUE TITLE
Robots Spamming console while charging 7.0.3

### ISSUE THREAD

**Issue by KiakahaEvans** [BuildCraft/BuildCraft#2696]
When my robots are being charged (energy flowing through their kinesis pipe) the console is spammed with these errors.

[buildcraft.robotics.EntityRobot:receiveEnergy:1201]: ABOVE THRESHOLD - 13
[buildcraft.robotics.EntityRobot:receiveEnergy:1201]: ABOVE THRESHOLD - 24
[buildcraft.robotics.EntityRobot:receiveEnergy:1201]: ABOVE THRESHOLD - 25
[buildcraft.robotics.EntityRobot:receiveEnergy:1201]: ABOVE THRESHOLD - 12

looks like they get to much power in a tick and waste it or something? etc etc

**Comment by asiekierka** [comment]
This doesn't matter at all. Ancient debug code.

**Comment by asiekierka** [comment]
This doesn't matter at all. Ancient debug code.
