### ISSUE TITLE
[Request][Mod Interaction] Method/Interface/API Hook to blacklist certain blocks from the quarry, builder, and similar

### ISSUE THREAD

**Issue by ReikaKalseki** [BuildCraft/BuildCraft#2698]
I am working on a dimension with extensive puzzle-type structures, and being able to mine them is very much a problem. The blocks are unbreakable by the player, but their actual hardness is not (and cannot be) less than zero because other metadatas of the block are mineable.

I would greatly appreciate an API hook of some sort - like making a block implement INonMineable - to stop the quarry and similar from tearing into the structures.

**Comment by asiekierka** [comment]
Why not make two Blocks, one with all the non-mineable metas and one with all the mineable ones?

I feel that API hook would be greatly abused.

**Comment by ReikaKalseki** [comment]
Because they are completely identical for all other purposes and I feel it is wasteful of the still-limited block IDs. Also, doing that change now would break every existing world, as these blocks have already been used extensively for worldgen.

**Comment by asiekierka** [comment]
Idea 2: Cancel BlockBreakEvents.

**Comment by ReikaKalseki** [comment]
That works; do the Quarry and similar fire them and fail to break a block if that is canceled?

**Comment by asiekierka** [comment]
Yes; Quarries, Fillers, Builders and Robots listen to the event. Stripes Pipes don't (yet), and other mods should be. Doubt many of them do, though.
