### ISSUE TITLE
Client crashes on chunk load - on server

### ISSUE THREAD

**Issue by Cuppycake** [BuildCraft/BuildCraft#2699]
We are having a random issue on two of my servers.

Entering a chunk can sometimes cause a client to disconnect from the server and display a Fatal Error message. Some of these chunks do not even have any bit of Buildcraft items in them. The only reasons I speculate BC is because the only thing in the logs I can find at the time of the chunk loads is:

http://pastebin.com/qbRa0945

We are running a cauldron build on Forge 1370.01.0
Alongside the following mod list: https://www.atlauncher.com/pack/MechMagic

**Comment by asiekierka** [comment]
To use BC with Forge 1355+ you NEED BC 6.4.11+.
