### ISSUE TITLE
Nearly overheated engine w/o power still producing energy

### ISSUE THREAD

**Issue by AcidicWolf** [BuildCraft/BuildCraft#2700]
Type: Glitch
When my combustion engine was red (about to explode/die), I turned off the power to it, but when I did it kept running, cooling down, producing small amounts of energy, and not changing back to Yellow -> Green -> Blue.
(Sorry for bad snapshot of the red engine, but you can see it through the pipe)
The engines in the background I disconnected a while ago, the power that the hot engine is the only power in the pipe.

EDIT: It went away after I exited and re-loaded the world

![2015-05-07_20 04 45](https://cloud.githubusercontent.com/assets/12317837/7530101/9769c3c2-f4f7-11e4-8943-06b045e5d6fd.png)
![2015-05-07_20 04 58](https://cloud.githubusercontent.com/assets/12317837/7530100/9769186e-f4f7-11e4-8528-a219e82cf748.png)

Installed mods:

* Carpenter's Blocks 3.3.6
* Code Chicken Core 1.0.4.29
     * Not Enough Items 1.0.3.74
* CoFH Core 3.0.2
     * MineFactory Reloaded 2.8.0
     * Redstone Arsenal 1.1.0
     * Thermal Foundation 1.0.0
          * Thermal Expansion 4.0.1
     * Nether Ores 2.3.0
* Micdoodle Core 3.0.11.306
     * Galacticraft Core 3.0.11.306
          * Galacticraft Planets 3.0.11.306
* Added crafting recipes 1.0 Final (Self made, private, only workbench recipes)

The only mod that was within the energy production process was Galacticraft

Buildcraft 6.4.14

Forge version 1.7.10-Forge10.13.2.1291

**Comment by leSamo** [comment]
From what I understood, I think this is not a bug, this is intended.

**Comment by marcin212** [comment]
Engine and emerald pipe have energy buffer.
