### ISSUE TITLE
Curse - outdated version of Buildcraft

### ISSUE THREAD

**Issue by leSamo** [BuildCraft/BuildCraft#2702]
Curse has got older (6.4.11) version of Buildcraft. It should be kept up-to-date or it might cause problems, especially for people using curse voice.

**Comment by AEnterprise** [comment]
fixed, most recent versions are now uploaded to CF

**Comment by leSamo** [comment]
Thanks. Try to keep it up-to-date, especially when a major bug is fixed between versions.

**Comment by AEnterprise** [comment]
yeah i sometimes forget that, feel free to ping me on irc or message me on the forum anytime for this and i'll get it up there

**Comment by simon816** [comment]
IIRC there's a ForgeGradle task to push to curseforge, perhaps that could be used when making a release build.

**Comment by AEnterprise** [comment]
not usable, i don't have direct access to upload the files, only @CovertJaguar has that, i'm pinging the people from cursforge to upload the files every once in a while

**Comment by leSamo** [comment]
Just a question, why is SirSengir displayed as author, shouldn't it be SpaceToad? And isn't asiekierka the maintainer?

**Comment by AEnterprise** [comment]
outdated information

**Comment by CovertJaguar** [comment]
More like those people all declined to be added to project when I asked them. *shrugs*
