### ISSUE TITLE
Builder issuse

### ISSUE THREAD

**Issue by t999uk** [BuildCraft/BuildCraft#2705]
Asie im sorry to say I broke the builder again, same issue as before just a different way to do it,

to everyone else yes I know im being obscure, but it for a good reason

**Comment by leSamo** [comment]
Best bug report eu

**Comment by t999uk** [comment]
heres a videos of the issue in action https://www.dropbox.com/s/h5wkjy3lp8wv66n/2015-05-12-0631-32.mp4?dl=0

**Comment by asiekierka** [comment]
@t999uk: 6.4.4? Really?

**Comment by t999uk** [comment]
yep and it still works with 6.4.14, the method with the chest doesn't work anymore but all you need to do is remove the meta data from the required items and it will then accept the same item just different meta, as you technically still give it the required block/items, it doesn't delete them

**Comment by t999uk** [comment]
seemsed to be fixed In the leatest versions
