### ISSUE TITLE
BuildCraft Error it was crash my Minecraft ,please Help.

### ISSUE THREAD

**Issue by NexusAleksandr** [BuildCraft/BuildCraft#2706]
When i am use BuildCraft it was crash my Minecraft,please help.
------Crash-Reports------
---- Minecraft Crash Report ----
// Would you like a cupcake?
Time: 5/11/15 7:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Lbuildcraft/core/BCCreativeTab;
at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:522)
at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:206)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:273)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:363)
at org.multimc.EntryPoint.listen(EntryPoint.java:165)
at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: Lbuildcraft/core/BCCreativeTab;
at java.lang.Class.getDeclaredFields0(Native Method)
at java.lang.Class.privateGetDeclaredFields(Unknown Source)
at java.lang.Class.getDeclaredField(Unknown Source)
at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:43)
at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
... 18 more
Caused by: java.lang.ClassNotFoundException: buildcraft.core.BCCreativeTab
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 45 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.7.0_67, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 906161944 bytes (864 MB) / 1781530624 bytes (1699 MB) up to 3817865216 bytes (3641 MB)
JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m -XX:PermSize=152m
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.05 FML v7.10.141.1403 Minecraft Forge 10.13.3.1403 Optifine OptiFine_1.7.10_HD_U_B7 116 mods loaded, 116 mods active
mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
FML{7.10.141.1403} [Forge Mod Loader] (forge-1.7.10-10.13.3.1403-1.7.10-universal.jar) Unloaded->Constructed
Forge{10.13.3.1403} [Minecraft Forge] (forge-1.7.10-10.13.3.1403-1.7.10-universal.jar) Unloaded->Constructed
AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) Unloaded->Constructed
CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
ivtoolkit{IvToolkit} [1.2] (minecraft.jar) Unloaded->Constructed
Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed
NotEnoughItems{1.0.4.106} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.106-universal.jar) Unloaded->Constructed
ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed
AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed
arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed
doggytalents{v1.9.0f} [Doggy Talents] ([1.7.10] Doggy Talents - v1.9.0f.zip) Unloaded->Constructed
lotr{Beta v23.3 for Minecraft 1.7.10} [The Lord of the Rings Mod] ([1.7.10] The Lord of the Rings Mod B23.3.jar) Unloaded->Constructed
DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed
bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed
Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed
gregapi{GT6-MC1710} [Greg-API] (gregtech_1.7.10-6.00.35.jar) Unloaded->Constructed
BuildCraft|Core{7.0.4} [BuildCraft] (buildcraft-7.0.4.jar) Unloaded->Constructed
BuildCraft|Silicon{7.0.4} [BC Silicon] (buildcraft-7.0.4.jar) Unloaded->Constructed
BuildCraft|Factory{7.0.4} [BC Factory] (buildcraft-7.0.4.jar) Unloaded->Constructed
BuildCraft|Transport{7.0.4} [BC Transport] (buildcraft-7.0.4.jar) Unloaded->Errored
additionalpipes{4.5.0} [Additional Pipes] (additionalpipes-4.5.0.jar) Unloaded->Errored
IC2{2.2.719-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.719-experimental.jar) Unloaded->Constructed
AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) Unloaded->Constructed
antiqueatlas{4.2.2-1.7.10} [Antique Atlas] (antiqueatlas-4.2.2-1.7.10.jar) Unloaded->Constructed
nevermine{2.0.1} [AdventOfAscension] (AoA-2.2.jar) Unloaded->Constructed
AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed
Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded->Constructed
BetterFoliage{1.0.12} [Better Foliage] (BetterFoliage-mc1.7-1.0.12.jar) Unloaded->Constructed
Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed
Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed
betterstorage{0.13.1.126} [BetterStorage] (BetterStorage-1.7.10-0.13.1.126.jar) Unloaded->Constructed
BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar) Unloaded->Constructed
Forestry{3.5.6.15} [Forestry for Minecraft] (forestry_1.7.10-3.5.6.15.jar) Unloaded->Constructed
BinnieCore{2.0-pre8} [Binnie Core] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed
Botany{2.0-pre8} [Botany] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed
ExtraBees{2.0-pre8} [Extra Bees] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed
ExtraTrees{2.0-pre8} [Extra Trees] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed
Genetics{2.0-pre8} [Genetics] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed
AWWayofTime{v1.3.2} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.2-1.jar) Unloaded->Constructed
Botania{r1.6-187} [Botania] (Botania r1.6-187.jar) Unloaded->Constructed
BuildCraft|Builders{7.0.4} [BC Builders] (buildcraft-7.0.4.jar) Unloaded->Constructed
BuildCraft|Energy{7.0.4} [BC Energy] (buildcraft-7.0.4.jar) Unloaded->Constructed
BuildCraft|Robotics{7.0.4} [BC Robotics] (buildcraft-7.0.4.jar) Unloaded->Constructed
ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed
chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) Unloaded->Constructed
DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) Unloaded->Constructed
dungeonpack{1.7.10-1.0} [Dungeon Pack] (Dungeon-Pack-Mod-1.7.10.jar) Unloaded->Constructed
eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed
Enchiridion{1.1} [Enchiridion] (Enchiridion 2-1.7.10-2.0.1.jar) Unloaded->Constructed
Enchiridion2{2.0.1} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.1.jar) Unloaded->Constructed
EnderStorage{1.4.7.36} [EnderStorage] (EnderStorage-1.7.10-1.4.7.36-universal.jar) Unloaded->Constructed
Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed
Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) Unloaded->Constructed
TConstruct{1.7.10-1.8.4.build939} [Tinkers' Construct] (TConstruct-1.7.10-1.8.4a.jar) Unloaded->Constructed
ExtraTiC{1.4.1} [ExtraTiC] (ExtraTiC-1.7.10-1.4.1.jar) Unloaded->Constructed
FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) Unloaded->Constructed
ForgeMultipart{1.1.2.334} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.334-universal.jar) Unloaded->Constructed
ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) Unloaded->Constructed
ForbiddenMagic{1.7.10-0.562} [Forbidden Magic] (Forbidden Magic-1.7.10-0.562.jar) Unloaded->Constructed
fossil{1.7.10 Build 7.1.0} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.1.jar) Unloaded->Constructed
GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.333.jar) Unloaded->Constructed
GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.333.jar) Unloaded->Constructed
GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) Unloaded->Constructed
IC2NuclearControl{2.2.1a-Yolo} [Nuclear Control 2] (IC2NuclearControl-2.2.1a-Yolo.jar) Unloaded->Constructed
harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10h.jar) Unloaded->Constructed
Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) Unloaded->Constructed
TwilightForest{2.3.5} [The Twilight Forest] (twilightforest-1.7.10-2.3.5.jar) Unloaded->Constructed
gregtech{GT6-MC1710} [GregTech] (gregtech_1.7.10-6.00.35.jar) Unloaded->Constructed
Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed
Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed
Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed
Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo] (growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed
Growthcraft|Bees{2.1.0} [Growthcraft Bees] (growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed
Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed
Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed
Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed
Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed
Highlands{2.2.3} [Highlands] (Highlands-1.7.2-v-2.2.3.jar) Unloaded->Constructed
InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) Unloaded->Constructed
inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed
journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed
legendgear{2.b.2.1} [LegendGear 2] (legendgear-1.7.10-2.b.2.1.jar) Unloaded->Constructed
LogisticsPipes{0.9.0.94} [Logistics Pipes] (logisticspipes-0.9.0.94.jar) Unloaded->Errored
MagicBees{@VERSION@} [Magic Bees] (magicbees-1.7.10-2.3.0.jar) Unloaded->Constructed
testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.6.jar) Unloaded->Constructed
MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8.jar) Unloaded->Constructed
Mystcraft{0.11.7.00} [Mystcraft] (mystcraft-1.7.10-0.11.7.00.jar) Unloaded->Constructed
pandorasbox{2.0.1} [Pandora's Box] (PandorasBox-2.1.jar) Unloaded->Constructed
MrTJPCoreMod{1.0.6.13} [MrTJPCore] (MrTJPCore-1.0.6.13-universal.jar) Unloaded->Constructed
ProjRed|Core{4.6.0.79} [ProjectRed] (ProjectRed-1.7.10-4.6.0.79-Base.jar) Unloaded->Constructed
ProjRed|Transmission{4.6.0.79} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.6.0.79-Integration.jar) Unloaded->Constructed
ProjRed|Transportation{4.6.0.79} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.6.0.79-Mechanical_beta.jar) Unloaded->Constructed
ProjRed|Exploration{4.6.0.79} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.6.0.79-World.jar) Unloaded->Constructed
ProjRed|Compatibility{4.6.0.79} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.6.0.79-Compat.jar) Unloaded->Constructed
ProjRed|Integration{4.6.0.79} [ProjectRed-Integration] (ProjectRed-1.7.10-4.6.0.79-Integration.jar) Unloaded->Constructed
ProjRed|Illumination{4.6.0.79} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.6.0.79-Lighting.jar) Unloaded->Constructed
ProjRed|Expansion{4.6.0.79} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.6.0.79-Mechanical_beta.jar) Unloaded->Constructed
RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) Unloaded->Constructed
reccomplex{0.9.6.2} [Recurrent Complex] (RecurrentComplex-0.9.6.2.jar) Unloaded->Constructed
libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) Unloaded->Constructed
xreliquary{1.2} [Reliquary] (Reliquary-1.2.jar) Unloaded->Constructed
AS_Ruins{14.7} [Ruins Spawning System] (Ruins-1.7.10.jar) Unloaded->Constructed
SSR{rc3} [Soul Shards Reborn] (SSR-rc3.jar) Unloaded->Constructed
StorageDrawers{1.7.10-1.4.5} [Storage Drawers] (StorageDrawers-1.7.10-1.4.5.jar) Unloaded->Constructed
ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-37.jar) Unloaded->Constructed
TiCTooltips{1.2.4} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.4.jar) Unloaded->Constructed
AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed
nolpfij_wildycraft{1.7.4} [Wildycraft] (wildycraft-1.7.10-1.7.4.jar) Unloaded->Constructed
witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) Unloaded->Constructed
YALSM{2.1.3} [Yet Another Leather Smelting Mod] (yalsm-2.1.3.jar) Unloaded->Constructed
yegamolchattels{1.1.2} [Ye Gamol Chattels] (YeGamolChattels-1.1.2.jar) Unloaded->Constructed
McMultipart{1.1.2.334} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.334-universal.jar) Unloaded->Constructed
HungerOverhaul{1.7.10-beta.6.jenkins70} [Hunger Overhaul] (HungerOverhaul-1.7.10-beta.6.jar) Unloaded->Constructed
IguanaTweaksTConstruct{1.7.10-2.1.4.132} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.4.jar) Unloaded->Constructed
ForgeMicroblock{1.1.2.334} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.334-universal.jar) Unloaded->Constructed
Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
TConstruct Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: gregtech

**Comment by psxlover** [comment]
LogisticsPipes{0.9.0.94} Logistics Pipes Unloaded->Errored
