### ISSUE TITLE
Quarry connected to a cobble stone generator stops

### ISSUE THREAD

**Issue by inucune** [BuildCraft/BuildCraft#2709]
A quarry set up over the piston output of a cobblestone generator will sometimes stop if it removes the block closest to the quarry I/O block even though there is stone still present in the layer.

temporary work-around is to restart server, at which point the quarry will resume normal operation, or to place quarry again.

Without looking at the code myself, my suggestion would be to have the quarry run a check to see that all blocks within the quarry's designated zone are clear before shutting down. In addition, have some way of manually instructing the quarry to rescan the zone (smack it with a wrench?)

Image of quarry configuration(operating).

![cobble-quarry](https://cloud.githubusercontent.com/assets/12404410/7579434/8bf9455a-f829-11e4-9531-fbabdd500a43.png)

Halted quarry

![halted quarry](https://cloud.githubusercontent.com/assets/12404410/7579456/e7412176-f829-11e4-9f8f-453b167c6bbc.png)

**Comment by asiekierka** [comment]
That's some clever engineering and abuse right there, I like that.

**Comment by AEnterprise** [comment]
a temp fix could be to limit/reduce the amount of power the quarry gets so it always has a backlog

**Comment by inucune** [comment]
There is always a backlog of cobblestone in the underside. the quarry is powered by a hobby engine with direct steam input, so at best operates at 1 cobble every 2 seconds
