### ISSUE TITLE
FakePlayer and AuthMe

### ISSUE THREAD

**Issue by ArcasCZ** [BuildCraft/BuildCraft#2712]
Hello there!

I want to ask you - can you add boolean to config where i can change avability of fakeplayer? It's a pitty that querry and another blocks with FakePlayers from BC canno't work on server with AuthMe. I pulle request to AuthMe creator and i hoped he can fix it - but it's three months ago and nothink happend...

**Comment by asiekierka** [comment]
Get a job and earn 20 bucks - then you won't need AuthMe.

On a more serious note, I'm not going out of my way to remove FakePlayers in the mining system - they serve a very important purpose in grief prevention and even cross-mod functionality.

**Comment by ArcasCZ** [comment]
It's not about me - i have original. But about other players. I'm not saing ,,Remove fakeplayer" bud add one config option, where i can switch true or false and choose, if i want to use FakePlayer.

**Comment by Kubuxu** [comment]
You can add BC's fake player to the AuthMe exception list. Many many mods use fake players so just turning it off in one place is notfix even for you. Don't ask me what is the BC's fakeplayer UUDI/name. Look for it in code on your own; I would have to do the same.

**Comment by ArcasCZ** [comment]
I tried - nothing happend.
