### ISSUE TITLE
Buildcraft robots duplication with Railcraft anchors

### ISSUE THREAD

**Issue by RofElMao** [BuildCraft/BuildCraft#2715]
Hi there,

I'm not sure, wether this bug is BC or RC related, so I'm going to post this on both trackers. *apologizes*
While robots are on their docking stations in a chunk that is kept loaded by an anchor of Railcraft (I'm using the personal anchor), each time I relog in those chunks the robots are popping of the docking stations (incl. the holded / stored items). The docking stations itself stays occupied (indicated by the red "LED") and I'm not able to place them on the docking stations again. So I have removed the station which resulted in not only one docking station popps off: Instead I gained the docking station, a duplicate of the robot (identic energy level) and also duplicates of the items that the robot was holding / storing. (Yeah... Theoretically I now have an unlimited amount of everything ^^)
This was reproducable each time I removed the anchor, relogged, replaced and relogged again.

Forge version: 10.13.2.1291
Buildcraft version: 6.4.15
Railcraft version: 9.6.1.0

Best regards to all the devs! :)

**Comment by RofElMao** [comment]
Addition 1) CovertJaguar said that it's either a BC or Forge issue (See /CovertJaguar/Railcraft/issues/611 )
Addition 2) Seems like if the server is restarted, the Docking Stations still stays occupied after the Robots popped off, but by removing the Docking Station no duplicate of the Robot and it's storage is popping off.

**Comment by hea3ven** [comment]
I could not reproduce with just those 2 mods, are you using a specific modpack?, also if you could provide the server logs, it would help.

**Comment by RofElMao** [comment]
Unfortunately the log itself doesn't show any errors / warnings - that was the first place I've looked at.
It's no special modpack, so here's the complete list of the mods and versions I use: http://pastebin.com/acBK79m8
I hope it's okay, that I simply bypassed the whole file-listing-output. Otherwise just tell me what hits your bias :)

**Comment by RofElMao** [comment]
Stupefying... I just realised I used the wrong server folder for the modlist. So some of the mod-versions don't match. Here's the correct list of the mods and download links to the server files with alle the configs, ... and, as an extra download, the map we played on + coordinates:
http://pastebin.com/suMfMb9c

"Sometimes a single living can be as stupid as the whole livings stupidity summarised." -- Me ^^

**Comment by hea3ven** [comment]
Could you try with buildcraft 6.4.16

**Comment by RofElMao** [comment]
At the moment I don't have enough time, but I'll test it latest coming Saturday and give feedback afterwards.

**Comment by RofElMao** [comment]
I'm a little late, but I have good news: Some quick tests, which formerly caused that pop-off-behavior now didn't work anymore. The robots stay on their docking stations and are working really fine. Thanks! :)
