### ISSUE TITLE
Crash in dev environment, BC Version 6.4.15

### ISSUE THREAD

**Issue by chazwarp923** [BuildCraft/BuildCraft#2717]
Once i drop buildcraft into my development mods folder and try to load up i get this crash.
ive looked at the error and it looks to me that its mapping a method to the wrong class or something along those lines.

http://pastebin.com/KzFVpfN4

**Comment by asiekierka** [comment]
One of your amazing development mods is bundling an amazingly outdated BuildCraft API.
