### ISSUE TITLE
robots disappear, placing multiple on one docking station, robots not dropping items in the pipe

### ISSUE THREAD

**Issue by Turmfalke2** [BuildCraft/BuildCraft#2720]
hi,
I have hard time getting anywhere with my robots. After building everything required to make them and making some diamond chipsets I am completly out of diamonds so I don't have the zone marker block.
The first picker robot I placed pretty much directly flew of and was never to be seen again. I then placed another one on the same station and I got to watch it fly a bit around my house. For several minutes it would just hang in the air. After that it picked up a steak, but ignoring the gate condition and never dropped the steaks in the pipe. It would sit on the docking station, but not drop them. While I learned how the charging docking station has to look like the 2th picker robot also disappeared. The return to base conditon again did nothing. After that I placed a knight robot who was on another docking station on the docking station of the missing picker robots. Apparently this shouldn't be possible?

Chatlog from #buildcraft http://pastebin.com/AwBaxCs9
buildcraft version:  buildcraft-6.4.15.jar
forge version:  forge-1.7.10-10.13.2.1291-universal.jar

**Comment by asiekierka** [comment]
You should be using Map Locations or they will flow everywhere including unloaded areas.

**Comment by hea3ven** [comment]
The robots are not smart, and if you don't configure them properly, they will mess up. Using map locations you can tell them where they can work.

> After that I placed a knight robot who was on another docking station on the docking station of the missing picker robots. Apparently this shouldn't be possible?
Were the lights on the docking station green or red?

**Comment by Turmfalke2** [comment]
I am colour blind, I have no idea.

**Comment by hea3ven** [comment]
![2015-06-04_20 19 14](https://cloud.githubusercontent.com/assets/6192652/7996600/4a380340-0af8-11e5-9708-45f9d41e4589.png)

Quick question, are you able to differentiate the states of the stations in the image? from left to right they are available (green), reserved (yellow), linked (red), you can read a little more what they mean [here](https://docs.google.com/document/d/1w0odEh0LMYfAYakwRU5N88xSivPSnF3ZXZj1AWJ-vyU/edit#heading=h.efet7g7nsgbt).

Regarding the issue, can you try with 6.4.16, there was a fix that prevents robots from dying in certain situations. Also, you can use landmarks to define zones for map locations without using the zone planner.

**Comment by Turmfalke2** [comment]
Yes, I can tell that the shape of the lights is different.
 Regarding the original bug reported, I have deleted the minecraft instance in that I discovered the faulty behaviour. So I can't longer test things there.

**Comment by asiekierka** [comment]
Closing until reproduced in BC *7*. BC6 is on its way out.
