### ISSUE TITLE
[Suggestion] A way to power a furnace with engines

### ISSUE THREAD

**Issue by ExDomino** [BuildCraft/BuildCraft#2721]
I don't know if this is the good place to post a suggestion, but my idea creating a way to power a vanilla furnace, or a new kind of furnace, with engines, if you don't have another mod like IC2 or TE installed.

If this is not the good place for a suggestion, where can I post it?

**Comment by BigXplosion** [comment]
BuildcraftAdditions has a furnace that can either run with coal, lava or BC lasers.

**Comment by hea3ven** [comment]
You can easily power a vanilla furnaces by piping in items, in a fully automated way. There is no need for BuildCraft to add another furnace, plus as stated before, there's already addons that provide furnaces.
