### ISSUE TITLE
Redstone signals from buildcraft gates not recognised by multiple mods 

### ISSUE THREAD

**Issue by DireTry20** [BuildCraft/BuildCraft#2722]
Mods found so far are computercraft and projectRed
![2015-05-21_03 05 29](https://cloud.githubusercontent.com/assets/12532738/7731787/44f8fef4-ff66-11e4-85bf-2fa19180612d.png)
I am using the DW20 pack and i have fastcraft installed

**Comment by SandGrainOne** [comment]
That does not look like a valid connection (if I remember ProjectRed correctly). Does it work if you replace the pipe and gate with a redstone block?

**Comment by DireTry20** [comment]
Good point 
But computercraft turtles can't read the RS signal, there is still an issue, I just left for school so I will test when I get home (8 hrs). This time my test will be more extensive and test more sides of the structure pipe.

Thanks, DireTry20

On 21 May 2015, at 5:38 am, SandGrainOne <notifications@github.com> wrote:

That does not look like a valid connection (if I remember ProjectRed correctly). Does it work if you replace the pipe and gate with a redstone block?

**Comment by DireTry20** [comment]
Good point about the alloy wire, i just tested it seems to work otherwise, so maybe just a problem  w/ CC

**Comment by DireTry20** [comment]
soz

**Comment by asiekierka** [comment]
Redstone and mods do not follow the same logic. We're not going to bother supporting further edge cases unless someone tells us specifically what's wrong, and we doubt anything is on our side.
