### ISSUE TITLE
Server Booting Error

### ISSUE THREAD

**Issue by chloeprince** [BuildCraft/BuildCraft#2726]
I can't tell if this is BC's issue or something EnderIO is doing.
Its causing an error upon trying to boot the server.

http://pastebin.com/j2y5QCf2

**Comment by chloeprince** [comment]
I also tried using newer 7.4 of BC.

Another and different crash:

http://pastebin.com/3tJRBrGr

**Comment by AEnterprise** [comment]
the first error is indeed a BC bug it seems, second error is forestry, just dissable the apiarists pipe to fix that
