### ISSUE TITLE
Liquid Transformation Bug

### ISSUE THREAD

**Issue by natedogith1** [BuildCraft/BuildCraft#2729]
The robot's fill method doesn't check that the fluid types match.

**Comment by hea3ven** [comment]
Which robot are you talking about, the tank robot or the pump robot? also, please tell us what versions of buildcraft and forge you are using.

**Comment by natedogith1** [comment]
I've tested it with the tank robot. Buildcraft version is 6.4.8, FML version is 7.10.103.1352, Forge version is 10.13.2.1352
1. get robot to pick up some lava from a tank (make sure the robot won't completely fill it's tank)
2. get robot to move to another tank to pick up lava
3. switch lava out with water before robot gets to tank
4. have robot place fluid in empty tank
5. water has been transformed to lava

**Comment by AgentK9** [comment]
Why are you playing on such an old BC?

**Comment by natedogith1** [comment]
Because I haven't yet updated FTB Infinity to more recent versions. And because this was actually a bug a discovered a while ago and never got around to reporting.
