### ISSUE TITLE
yet another integration table bug

### ISSUE THREAD

**Issue by AEnterprise** [BuildCraft/BuildCraft#2733]
yet again i try to update BCA to the new BC integration table system and found yet anohter bug: expansions don't get used up when crafting

**Comment by hea3ven** [comment]
Are you decreasing the stack size of the expansions in your recipe handler?

**Comment by AEnterprise** [comment]
duno, how do you do that? also it heapens with BC recipes as well

**Comment by asiekierka** [comment]
@AEnterprise - we did not want to do that on our own so that mods could use up multiple of an ItemStack. thus, this part of the behaviour is intentional.

**Comment by AEnterprise** [comment]
looking at the BC recipes i don't see how to use up the items, also seems like it doesn't use them up with BC recipes as well

**Comment by asiekierka** [comment]
@AEnterprise - that would mean it's a bug of this kind.

**Comment by asiekierka** [comment]
@AEnterprise - also, it should be using them up:

					if (!preview) {
						chipset.stackSize--;
					}

etc.

**Comment by AEnterprise** [comment]
odd thing is i tried a BC recipe as well (installing pulsating chipset on a gate) and the pulsating chipset did not get used up, i'll take another look later today when i am home

**Comment by asiekierka** [comment]
@AEnterprise - if the gate already has a pulsating chipset in it won't get reused twice

**Comment by AEnterprise** [comment]
the gate did not have any chipsets installed, it crafted the pulsating gate with pulsar, used up the gate but not the chipset

**Comment by asiekierka** [comment]
@AEnterprise - i just tested it and it works fine. perhaps a coremod meddling?

**Comment by AEnterprise** [comment]
i duno, only coremod i have is codechickencore for nei, will try again when i get home
