### ISSUE TITLE
Crash while compiling

### ISSUE THREAD

**Issue by EeveeA** [BuildCraft/BuildCraft#2735]
Just a heads up, It's probably a problem on my part, but It's 

java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft

Crash Report: http://a.pomf.se/lbmkeb.txt

**Comment by EeveeA** [comment]
(derp) but it looks like it's buildcraft, so I figured I'd post it here.

**Comment by LouisHutch** [comment]
Disable the apiarist pipe in the forestry config

**Comment by EeveeA** [comment]
I disabled it, still crashing.
I believe it's the same problem. http://a.pomf.se/dzvyst.txt

(I disabled it in the modules.cfg )

**Comment by asiekierka** [comment]
You haven't.
