### ISSUE TITLE
Crash With Open Mods/Blocks

### ISSUE THREAD

**Issue by AgentK9** [BuildCraft/BuildCraft#2737]
Crash Report:https://gist.github.com/AgentK9/1ba269fd26e56f6a7862

**Comment by psxlover** [comment]
You are placing normal mods in a dev environment...

**Comment by AgentK9** [comment]
I know. Sometimes normal mods work, sometimes they don't. Sometimes "dev" mods work, sometimes they don't. I am using the slightly laggy forge instead of the real MC because my parents are not sure they want me to be playing minecraft.

**Comment by AgentK9** [comment]
btw, BCA also errors when it is installed

**Comment by asiekierka** [comment]
What?

**Comment by AEnterprise** [comment]
@AgentK9 unless you are running from eclipse or intelliJ you NEVER want to use "dev" versions of mods, they simply CAN'T run in a non-dev environment

**Comment by AgentK9** [comment]
I know. eclipse

**Comment by laz2727** [comment]
Try to add Cofhcore dev. Iirc it fixes some errors with launching normal
mods in dev.

2015-06-02 18:09 GMT+06:00 AgentK9 <notifications@github.com>:

**Comment by AgentK9** [comment]
I looked for it all over the net. Where is it?

**Comment by iTitus** [comment]
www.teamcofh.net or directly via CurseForge. You have to download the 'dev'-version.

**Comment by AgentK9** [comment]
I CAN"T FIND THE -dev VERSION!!!

**Comment by AgentK9** [comment]
nevermind.
It is only on CF, tho
