### ISSUE TITLE
MFR Biofuel Generating 4 RF/t in Combustion Generator

### ISSUE THREAD

**Issue by permdaddy** [BuildCraft/BuildCraft#2739]
Using newest buildcraft 7.0.5

Sort of new to buildcraft so I don't know if it needs to warm up or what but it stayed blue for a long time and the temp creeped up very slowly.

**Comment by laz2727** [comment]
MFR BC integration most likely never switched to RF properly.

2015-06-02 13:07 GMT+06:00 permdaddy <notifications@github.com>:

**Comment by permdaddy** [comment]
Yeah - this is on MFR. Closing.
