### ISSUE TITLE
Robots can in rare cases overload an item pipe

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildCraft#2743]

**Comment by hea3ven** [comment]
hmm, is it when there are already items in the pipe?

**Comment by asiekierka** [comment]
@hea3ven - no. the pipe is empty. it's also very random. it might be a timing issue - might help just to slow down their extraction a bit

**Comment by asiekierka** [comment]
screens from marcin212:  https://dl.dropboxusercontent.com/u/25172450/bugs/bc/b82b3f8be49f37ca9918b2b59c02457c.png  https://dl.dropboxusercontent.com/u/25172450/bugs/bc/d7720226b8c88457cf300e70887bacea.png

**Comment by hea3ven** [comment]
weird, they put a stack per tick, I'll make it have a delay between stacks. Also, what do you mean by overload, they blow up?

**Comment by asiekierka** [comment]
Yes

**Comment by asiekierka** [comment]
We won't get this done in time.

@hea3ven - at one point, the pipe gets 65 stacks and blows up.
