### ISSUE TITLE
Weird Issue: Pics describe it better

### ISSUE THREAD

**Issue by AgentK9** [BuildCraft/BuildCraft#2745]
pics:
https://drive.google.com/folderview?id=0BzK_G4me5sh7fkRUdGpTZEFYeDh5X05VTzFKUXFZejBEWmpQdlppdkl4eXAtRFlHa1BjWjA&usp=sharing
pics
The gate on top of the engine does not get that there are items in the inventory, whereas the one on the side does

**Comment by laz2727** [comment]
Most likely because it blocks the engine.

2015-06-05 23:31 GMT+06:00 AgentK9 <notifications@github.com>:

**Comment by SandGrainOne** [comment]
The inventory in the engines are not accessible from the front/top side of the engine.

There are two ways to solve this:
 1. Hide triggers that are placed at a side of the engine(s) without access to any inventory slots. This might be the preferred options as it could be used for all types of machines. I've not checked the API to see if there are built in support for this.
 2. Make the inventory available through the top of the engine.

**Comment by SandGrainOne** [comment]
This has been addressed through https://github.com/BuildCraft/BuildCraft/commit/ef6e12f9acb8ca81a7f1c598e0a5eafc58cbeaf2
