### ISSUE TITLE
Weird glitch with builder gui

### ISSUE THREAD

**Issue by AgentK9** [BuildCraft/BuildCraft#2757]
![2015-06-06_13 33 11](https://cloud.githubusercontent.com/assets/11563088/8020710/74d9ba62-0c51-11e5-8030-234c9df7eb87.png)

**Comment by AgentK9** [comment]
easter egg?

**Comment by asiekierka** [comment]
Eeeeeeh? You may or may not have a corrupt blueprint. What are you blueprinting?

**Comment by Landrash** [comment]
Based on inventory and blueprint contense I would guess a mobspawner?

**Comment by AgentK9** [comment]
a beta base. I can send you it if you want. creative

**Comment by AgentK9** [comment]
@Landrash that is part of it, but not the whole thing

**Comment by AgentK9** [comment]
I still do not get how the fluid part of the builder works

**Comment by AEnterprise** [comment]
maybe it's different states of flowing water it recorded?

**Comment by AgentK9** [comment]
btw, This is not the whole blueprint. It already built most of it

**Comment by n00b7** [comment]
my builder gui when fluids are in it
![2015-06-12_16 53 49](https://cloud.githubusercontent.com/assets/11874683/8139744/146aba82-1124-11e5-9333-4393a15fecb9.png)
