### ISSUE TITLE
Pipe not updating on block update 

### ISSUE THREAD

**Issue by bookerthegeek** [BuildCraft/BuildCraft#2758]
https://github.com/erogenousbeef/BigReactors/issues/393

Is this still an issue or did it get fixed? Looked through all the issues since then and cannot find that it was ever reported here. 

Sorry if this is no longer an issue.

**Comment by asiekierka** [comment]
Great to know someone was talking about us.

**Comment by bookerthegeek** [comment]
Glad I could help. :)
