### ISSUE TITLE
BuildCraft 7.0.6 Crash with Forestry 3.5

### ISSUE THREAD

**Issue by jjmcquaid** [BuildCraft/BuildCraft#2760]
So I tried updating BuildCraft to 7.0.6. It said there was a crash with Forestry but it was fixed in version 7.0.5 of the mod. So idk if I'm doing something wrong or not. Here's a copy of the crash report, let me know if you need anything else. BuildCraft 7 looks really nice, and I'm eager to try it out. 

https://gist.github.com/jjmcquaid/95df137f48ea59ced357

**Comment by davboecki** [comment]
See: https://github.com/BuildCraft/BuildCraft/issues/2749
