### ISSUE TITLE
Disabling Quarries

### ISSUE THREAD

**Issue by whitestarx0312** [BuildCraft/BuildCraft#2764]
I just upgraded to Buildcraft 7 and reset my config as I am sure new settings were added. Upon doing this I found that the "Disable mining machines" option was removed, which enables quarries and mining wells.

I found this config option to be extremely useful in forcing players to mine, and getting rid of potential TPS issues regarding massive quarry setups. I love quarries, but is there anyway to re-implement this config option?

**Comment by asiekierka** [comment]
MineTweaker is a good one.
