### ISSUE TITLE
texture error with buildcraft-7.0.6

### ISSUE THREAD

**Issue by Antecer** [BuildCraft/BuildCraft#2765]
There's a BUG, maybe happen with robot.
It makes the pipe texture error！

![qq 20150607175227](https://cloud.githubusercontent.com/assets/8684916/8023431/0f3d7d26-0d3f-11e5-8c4c-d3bfcfb641b4.png)
![qq 20150607180026](https://cloud.githubusercontent.com/assets/8684916/8023432/1c8a5daa-0d3f-11e5-91ed-60b282b6421a.png)

**Comment by Antecer** [comment]
![qq 20150608185336](https://cloud.githubusercontent.com/assets/8684916/8033302/b5af6fae-0e0f-11e5-90e7-2b0c86139119.jpg)
![qq 20150608185418](https://cloud.githubusercontent.com/assets/8684916/8033313/cedd8ab0-0e0f-11e5-97d3-39b4d20008e4.png)

**Comment by asiekierka** [comment]
Are you using Cauldron?

**Comment by Antecer** [comment]
Yes
