### ISSUE TITLE
Robots can have an unlimited number of IRobotOverlayItem's equiped.

### ISSUE THREAD

**Issue by RiskyKen** [BuildCraft/BuildCraft#2769]
Even if a robot already has an item using the IRobotOverlayItem interface equipped, more can be equipped on top of it.

http://puu.sh/iggNG/13257fcfd5.png

Stack them!

**Comment by hea3ven** [comment]
It should be up to 8 items that they can equip. If it's more than that, its a bug, otherwise, working as intended.

**Comment by RiskyKen** [comment]
Oh sorry I only stacked them until it looked silly. Guessing it is working the way it should.

Got to ask thought why 8 items and not 1? Seems a little strange.

**Comment by asiekierka** [comment]
Not everyone uses AW. I chose 8 items because nobody would go beyond silly.
