### ISSUE TITLE
[7.0.8] Table textures change when placed beside blocks.

### ISSUE THREAD

**Issue by l3CY** [BuildCraft/BuildCraft#2770]
![texture render -y](https://cloud.githubusercontent.com/assets/5257728/8026409/3d5e5fd8-0d42-11e5-9bfb-855dc65e8ac1.png)

As you can see, the tables texture gets lines through it when placed beside a block.  I do not recall this issue occurring with the 7.0.6.

-System Details-
Forge:1408
Buildcraft: 7.0.8
Buildcraft Compact: 7.0.7

**Comment by psxlover** [comment]
Try a newer version of forge. This could be related to https://github.com/MinecraftForge/MinecraftForge/pull/1892.

**Comment by asiekierka** [comment]
That's not related. This issue is related to the hackiness of our rendering code

**Comment by ganymedes01** [comment]
Btw: this has been fixed in 1.8 (by a Forge patch)
