### ISSUE TITLE
[BC7] Blueprints featuring cactus and sand can cause them to be unusable

### ISSUE THREAD

**Issue by Ugaps** [BuildCraft/BuildCraft#2772]
Today vvhen I made a blueprint of a cactus farm, it vvas unable to finish because the cacti that it needed vvere supposed to be placed BEFORE sand, vvhich unfortunately vvas on the list after the cacti. 

Unsure if you need any more info, I think it's simple enough for a short description.

**Comment by asiekierka** [comment]
Fixed in BC 7.1.3.
