### ISSUE TITLE
Placing BC tank beside Railcraft track causes world crash

### ISSUE THREAD

**Issue by neograymatter** [BuildCraft/BuildCraft#2775]
Crashlog: http://pastebin.com/f7nLQVXb

Have a few pieces of track down, place a tank right beside them, World crashes and cannot be reloaded until you remove the tank via MCedit. After it took down my server, I reproduced the problem in new single player creative world as well.

**Comment by AgentK9** [comment]
versions? forge/bc/railcraft?

**Comment by neograymatter** [comment]
Sorry about that, I had assumed that would be included in the crash log

Forge: 10.13.3.1428
Buildcraft: 7.0.8
Buildcraft compat: 7.0.7
Railcraft: 9.6.10

**Comment by AEnterprise** [comment]
pure RC crash, has nothing to do with BC, as far as i can see

**Comment by asiekierka** [comment]
Not our fault.
