### ISSUE TITLE
Exception java.util.ConcurrentModificationException but server still works.

### ISSUE THREAD

**Issue by klusekrules** [BuildCraft/BuildCraft#2777]
Forge 10.13.3.1401
BuildCraft 7.0.8 for Minecraft 1.7.10
BuildCraftCompat 7.0.7 for Minecraft 1.7.10

I received this exception. The server still works.

http://pastebin.com/fiRQCASc

**Comment by asiekierka** [comment]
Fixed in BC 7.0.9.
