### ISSUE TITLE
Suggestion: New Explosives

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [BuildCraft/BuildCraft#2778]
Almost every techmod, magicmod, whathaveyoumod add new items, blocks, tools, etc. but strangely almost none of them add any new explosives to the game.

I kinda want to have more choices besides TNT. Bigger, smaller, better, different, anything, really :).

Kaboom is gud!

**Comment by asiekierka** [comment]
Why not use the Bomber robot? Rejected for now.

**Comment by Unrepentant-Atheist** [comment]
Yes, I'm using it. Bomber robot is fun. Would be funnier if he could deliver bigger kaboom.

**Comment by marcin212** [comment]
![comment_gdrzsgiq2kwddiczbvlaejic7pg5kjeu](https://cloud.githubusercontent.com/assets/3790635/8080871/67327242-0f70-11e5-92c1-6c612b55c5b7.gif)

**Comment by AgentK9** [comment]
LOL :D

**Comment by karakufire** [comment]
Same title issues by @Unrepentant-Atheist can found other projects, I have seen in [CoFH/FeedBack](https://github.com/CoFH/Feedback) and [SleepyTrousers/EnderIO](https://github.com/SleepyTrousers/EnderIO).
Why he posted in some projects?

**Comment by Unrepentant-Atheist** [comment]
Because I use these mods? Because not every mod author watches all possible MC mods on GitHub?

**Comment by asiekierka** [comment]
It's good that he opened those issues, it's just a shame that we're not interested I guess.
