### ISSUE TITLE
BC 7.0.8 broken robots

### ISSUE THREAD

**Issue by AEnterprise** [BuildCraft/BuildCraft#2779]
we updated to BC 7.0.8 on the server and the some things that worked before broke, others still don't work

harvester robot: all setup earlier and worked just fine, now he just sleeps and when he wakes up he just goes back to sleep even if he has work

planter robot: needs to be adjacent to an inventory to get it's stuff, the load/unload area doesn't work nor does he respect his working area, each time he planted something he goes to sleep even if there is still work to be done

**Comment by asiekierka** [comment]
The harvester works just fine on our server.

**Comment by AEnterprise** [comment]
he just keeps sleeping here, will break and replace him in a bit, see if that helps but i doubt it

**Comment by hea3ven** [comment]
try removing the docking station an placing it back, if that fixes it then it's the same issue as #2743

**Comment by AEnterprise** [comment]
doesn't make it work again, even broke the pipe with station and gate and replaced it all, still keeps sleeping

**Comment by hea3ven** [comment]
Same as #2784
