### ISSUE TITLE
BC 7.0.8 Robots Not Working

### ISSUE THREAD

**Issue by MimirDroid** [BuildCraft/BuildCraft#2784]
Running BC 7.0.8 for 1.7.10

Robots are not responding to signal to work in area or return to station.

When I pick up the docking station they are not reverting back to items I can pick up.  The red eye just turns black and they stay in the same spot.  Docking stations are on gold power pipes.  I have 6 total 3 knights, a picker, a harvester, and a planter.

**Comment by AgentK9** [comment]
prob same as #2779

**Comment by hea3ven** [comment]
For the first problem, try updating to 7.0.9.

Regarding robots not dropping as items, that's a feature of BuildCraft 7, if you remove their docking station they turn off. You can turn any robot into items by shift right-clicking it with a wrench.

**Comment by MimirDroid** [comment]
upgraded to 7.0.9 and they seem to be working better.  And using the shift right click with the wrench does turn the robot back to an item that can be picked up.
