### ISSUE TITLE
BC 6.4.15 - Water Spring does not generate properly

### ISSUE THREAD

**Issue by SpwnX** [BuildCraft/BuildCraft#2785]
I'm currently playing on a server that has finite water (no 2x2 pools of infinite water), so i thought, hey, there is a block on buildcraft that makes infinite water, I should find a spring and be good. However... after looking for about 2 hours with creative flight I couldn't find a single spring.
It is supposed to form vertical shaft/geysers like oil wells, no?

Then, unsatisfied with the result I used player's sampler to find said water springs on the server...
The result was quite unexpected. (http://pastebin.com/Nvbes0nR)
There are 2043 water springs in the server! How can't I find one? After teleporting to a few of them I found why. They're generated at Y=1. No water shaft to surface, below the other layers of bedrock.
You can't see them, they don't generate water, they're often surrounded by bedrock.
Another interesting found is that they're even generated on the nether. (http://puu.sh/ikjlx/6c9836286f.jpg) This one was also under the bedrock layers and hidden.

So, I'd like to be able to use water springs in the future. It is a quite useful block for finite water worlds.
That said, it should also have a config on how fast they spawn a block of water.
Note: Oil wells generate just fine.

**Comment by asiekierka** [comment]
This has been broken for an unsightly amount of years.

**Comment by SandGrainOne** [comment]
Your time perspective is a little bit different from mine. My 1.6.4 (recently converted to 1.7.10) has multiple water springs. I haven't found any in chunks generated in 1.7.10 though.

**Comment by asiekierka** [comment]
@SandGrainOne - The code has never changed since 1.6.4, though. Perhaps the bedrock generation changed in 1.7? Strange.

**Comment by SpwnX** [comment]
The server i'm playing updated to BC 7.0.9, the springs now do generate their water shafts and can be accessed, however they are still a bit broken, since the water shaft does not go all the way up to surface (or is that not intended?). It goes 32 blocks and stops (or till it hits a cave). I mean, my chances of finding one if it doesnt go all the way to the surface is quite shallow.
http://puu.sh/io9sE/cd6b63361f.jpg

Even if not going all the way to the surface is intended, the shafts depth should be a random number (between 32 and 256), so that at least some of them can be seen on the surface.

**Comment by asiekierka** [comment]
That's intended because I think that with the flowing nature of water, water springs might look ugly. But now I realized that they wouldn't, as they would flow down.
