### ISSUE TITLE
Request, Iron Fluid Pipes with 80mb

### ISSUE THREAD

**Issue by kremsy** [BuildCraft/BuildCraft#2786]
There are the Gold Pipes which can carry 80mb, so I think the Iron Pipe output should provide 80mb, while the inputs are supporting 40mb. Or better make the inputs also supporting 80mb and the output 80mb, it would be more flexible.

(If there is already a way todo is, just ignore it and close this request.

**Comment by ganymedes01** [comment]
Someone requested this a while back on #1210 and no one could agree on what to do :3

**Comment by kremsy** [comment]
Better to increase it to 80mb as doing nothing, they are completely unusable with the gold pipes (at least i saw no solution yet).

**Comment by ganymedes01** [comment]
But then people would use them as cheap gold pipes

**Comment by kremsy** [comment]
Makes sence, maybe make new pipes which requierst an iron and an gold fluid pipe to craft. And these can hold 80mb.

**Comment by asiekierka** [comment]
Why not use diamond fluid pipes as directional pipes with their sorting?
Those do 80.

2015-06-11 19:04 GMT+02:00 Lukas Kremsmayr <notifications@github.com>:

**Comment by asiekierka** [comment]
I might go for dynamic fluid pipes, though, because I fear none.

**Comment by kremsy** [comment]
Thanks for the solution with the diamond, I think it solves this problem, and don't really know if there is still a need for more :).

**Comment by asiekierka** [comment]
Removed for now. If someone can find an important enough usecase, let me know.
