### ISSUE TITLE
Please add zh_CN.lang to buildcraft-compat

### ISSUE THREAD

**Issue by Antecer** [BuildCraft/BuildCraft#2788]
####################
# APIARIST'S PIPE
####################

item.buildcraftPipe.pipeitemspropolis.name=养蜂员管道

for.gui.pipe.filter.anything=任意物品
for.gui.pipe.filter.bee=任意蜜蜂
for.gui.pipe.filter.cave=穴居蜂
for.gui.pipe.filter.closed=已关闭
for.gui.pipe.filter.drone=雄蜂
for.gui.pipe.filter.flyer=强壮飞蜂
for.gui.pipe.filter.item=物品
for.gui.pipe.filter.natural=自然
for.gui.pipe.filter.nocturnal=夜行蜜蜂
for.gui.pipe.filter.princess=公主蜂
for.gui.pipe.filter.pure_breed=纯种蜜蜂
for.gui.pipe.filter.pure_cave=纯种穴居蜂
for.gui.pipe.filter.pure_flyer=纯种飞蜂
for.gui.pipe.filter.pure_nocturnal=纯种夜行蜜蜂
for.gui.pipe.filter.queen=蜂后

**Comment by asiekierka** [comment]
Next time please pull request

**Comment by Antecer** [comment]
sorry,but i can't find Compat in github

**Comment by Antecer** [comment]
Okay, next time.
