### ISSUE TITLE
[BC 7.0.9] Visual Bug Fluid Pipes / Raffineries, Tanks

### ISSUE THREAD

**Issue by kremsy** [BuildCraft/BuildCraft#2789]
http://pictures.esc-clan.net/upload2/visualbug.png

The rafeniery is running but shows no animation, as well the pipes are empty while they are full. Rejoining the server helps sometimes but not always. This bug is since version 7.0.9, never noticed this bug in 7.0.8.

**Comment by kremsy** [comment]
It actually seems like that the rafinery isnt running at all anymore and thats why the visuals like this, but on many other places I have the bug as well that nothing get shown in fluid pipes.

**Comment by kremsy** [comment]
Seems like fluids are completely bugged in this version :/.

**Comment by kremsy** [comment]
More investigation: 
http://pictures.esc-clan.net/upload2/oildbu2.jpg

This left tank is visually full, but I cant put anything out or in with a bucket.

On the right tank putting fluids out an in works without any problems.

**Comment by asiekierka** [comment]
Cauldron?

**Comment by kremsy** [comment]
?

**Comment by asiekierka** [comment]
Are you using Cauldron?

**Comment by kremsy** [comment]
Nope

**Comment by kremsy** [comment]
Also a server restart didnt solve the problem.

**Comment by kremsy** [comment]
The weired thing is that the right tank is working, but nothing get transfered over the fluid pipe to the rafinery, I will try to replace the pipe from the right tank to the rafinery and see what happens.

**Comment by kremsy** [comment]
Maybe this helps with finding out the cause:

The fluids are bugged since I placed this pump here:

http://pictures.esc-clan.net/upload2/kopie_fluidbug1.png

All the tanks you can see on the pictures are bugged and all pipes where the oil from these pumps get pumped into.

**Comment by psxlover** [comment]
Are you sure that's oil?

**Comment by kremsy** [comment]
What else should it be, if it isnt oil, why does the diamond pipe fail?

**Comment by psxlover** [comment]
#2761

**Comment by kremsy** [comment]
How can I find out if its sludge or oil? Which of my mods could have added that? If it would be not oil we found out the cause at least, but stil would be a bug that the diamond pipe cant sort it out, or cant does a dia fluid pipe not direct stuff in the direction withoht an full bucket? I can do some more tests tomorrow, thanks for the hint.

**Comment by kremsy** [comment]
Maybe it is http://wiki.micdoodle8.com/wiki/Crude_Oil if so, kinda weired that it isnt compatible with bc, and I guess there is no way to remove the already generated blocks of that stuff in all created world already, right?

**Comment by kremsy** [comment]
https://github.com/BuildCraft/BuildCraft/issues/2780 maybe this issue has todo as well with that crude oil.

**Comment by kremsy** [comment]
Made more investigations with the Diamond Pipes, it doesnt work with that stuff at all. Maybe in the future there could be some possibility that this stuff is compatible and works like normal BC oil.

It makes sence now that the Rafenery doesnt work, but that you cant even put that stuff from a tank in your bucket is weired.

I was already wondering why so much oil got created and kinda want remove all non BC oil, but no clue howtodo it yet.

**Comment by psxlover** [comment]
You should try WAILA to see what it is.

**Comment by kremsy** [comment]
Im pretty sure now that its Crude Oil from Galacticraft as it explains quite exactly how it can be found and explains the distribution in the quarry hole. As it is described: "Crude Oil generates between y-levels 15 and 34 in small reservoirs of about 20 blocks. " it makes all sence.

**Comment by kremsy** [comment]
Wailla says oilgc.

**Comment by psxlover** [comment]
According to https://github.com/micdoodle8/Galacticraft/issues/1490 you will need a galacticraft refinary for that.

**Comment by kremsy** [comment]
Yes I read that already as well, but its still weired that its different to the BC oil, im wondering if the fuel what the rafineries are producing is getting the same at the end.

**Comment by radfast** [comment]
As posted on #2795, I will be adding a recipe to the Buildcraft Refinery so that it accepts "oilgc" as an input.

I don't see any other __issue__ actually being reported here.  If there is another issue and it's Galacticraft related, please can someone re-state exactly what it is and how we can reproduce it, and then someone can maybe take a look at it.

**Comment by kremsy** [comment]
One weired thing I still dont understand, why cant you put oilgc out of a tank in a Bucket=

**Comment by radfast** [comment]
There is plentiful documentation on Galacticraft's wiki which is put there to help server owners in all aspects of setup and configs.  If you created your world without reading it then, yes, I guess you might indeed have to spend a lot of time in WorldEdit to get things how you want them to be.
