### ISSUE TITLE
[BC 7] Visual Bug on Pipes

### ISSUE THREAD

**Issue by kremsy** [BuildCraft/BuildCraft#2790]
Another bug which I had already some times I think in 7.0.5 or 7.0.6 (not sure anymore) than it was fine, was also fine the whole day on 7.0.9 but now it appeared again.

http://pictures.esc-clan.net/upload2/visbug.png

I place electric or transport pipes and they didnt get shown correctly, structure pipes get shown instead.
I tried to restart the server, restart the game, reconnect, nothing helps. (But after every reconnect they get shown correctly but as soon I place blocks again they are not shown correctly (the new placed ones).

**Comment by kremsy** [comment]
Seems like electric isnt rendering anymore as well, maybe the fluid bug and this bug are all related to eachother somehow :/. Hope a solution could be found as it got quite unplayable.

Installed mods:
http://pictures.esc-clan.net/upload2/mods.png

You can also join our server to make tests if you need to.
Download modpack:
http://kremsmayr.net/mods_paragon-mc.zip
server adress: mc.paragon-esports.com:26000

**Comment by AgentK9** [comment]
erm... probably unrelated but you should install BCCompat

**Comment by kremsy** [comment]
I will try that, didn't knew (or didnt read enough carefully that this is "needed"). I thought its included in the normal Buildcraft download somehow.

**Comment by kremsy** [comment]
I installed BCCompat, all bugs are still there.

**Comment by kremsy** [comment]
Now another Bug appeared we already have in version 5 or 6, if I rightmousclick a gate it shows no interface.

**Comment by kremsy** [comment]
All this buggs are random, sometimes they appear all the time, sometimes they dont appear some hours at all, but at the time they are appearing they are anoying, every reconnect to the server fixes the bug, had to reconnect yesterday every 10 seconds.

**Comment by asiekierka** [comment]
Cauldron? No Cauldron? Does it happen without Cauldron?

**Comment by kremsy** [comment]
Happens without Cauldron, never used that.

**Comment by skittishtrigger** [comment]
Also happens with kcauldron. 1420 iirc. Newest BC7.09 w/compat. I run both a dev server and a main line if anything needs tested. Issue present in both servers,

**Comment by kremsy** [comment]
What I can maybe think off is that it happens more while the server is bit laggy.

**Comment by skittishtrigger** [comment]
I can do some more testing but I just moved hosts to a dedi and have 8Gb ram allocated and one cpu (not that it uses it all) dedicated to it. Average for last week was 19.65 with drop to 17, and high side ping was 300+ (client side issue) with average being less than 80 during stress testing if that helps at all.

**Comment by spidey1958** [comment]
I'm seeing the same issue in single play. I assume it is an issue with another mod. I have all the same mods (plus a lot more) except for nether ores.

**Comment by spidey1958** [comment]
A related issue might be that facades I place do not show up till I exit and reenter the game

**Comment by spidey1958** [comment]
I found the issue for me was the buildcraft api in the forestry jar. Removed it an issue went away.

**Comment by spidey1958** [comment]
I was wrong still getting issue randomly.

**Comment by spidey1958** [comment]
Did some more testing and appears to work fine until I teleport. I'm using 7.11 I have all the area my pipes in chunckloaded

**Comment by asiekierka** [comment]
No longer applies in the same form in 7.2.0+.
