### ISSUE TITLE
Quarry Trouble

### ISSUE THREAD

**Issue by jahpickney** [BuildCraft/BuildCraft#2791]
I'm sorry to begin this way, but: Why is it that with every significant update my quarry is broken? The problem I have is that a single Ender IO combustion engine usually works fine, but if I use two the quarry spits half to two thirds of the items all over the ground. I've tried using BC engines, but it's the same. Some of the items go up the pipes, the majority go all over the place - as if there were no pipe at all. One of those engines sometimes seems to work fine...just a little slow. Strangely, the major upgrade to Buildcraft 6 didn't break anything! Yet, now that I upgrade to BC 7 I'm back to the same weird thing. I don't understand. The worst part is that my only viable option is to use an Ender Quarry. They work great, but, I much prefer the aesthethic quality of BC quarries.

**Comment by laz2727** [comment]
Use a buffer chest. Quarry can be a little bit too fast for pipes.

2015-06-12 4:04 GMT+06:00 jahpickney <notifications@github.com>:

**Comment by jahpickney** [comment]
Thank you very much, friend! It strikes me as odd that pipes, as central as they are to BC, would be too slow, but then again, I don't know much about writing mods. Due to the compact nature of my build, I used Vacuum Chest from Ender IO with a Wooden Pipe and Basic Gate w/Autarchic Pulsar feeding back into the Diamod Pipe. I hope this is helpful to anyone else who reads this. Again, thanks for the help!

**Comment by SandGrainOne** [comment]
Any item transportation pipe should be able to take the output of a BuildCraft Quarry at full speed. Post a picture of your quarry with surounding pipes.

**Comment by asiekierka** [comment]
It's Ender IO conduits. We can't quite make them work right with quarries, and sometimes it mistakes power conduits for item ones and BAM!
