### ISSUE TITLE
[Request] The Repost Permission of Buildcraft

### ISSUE THREAD

**Issue by 3TUSK** [BuildCraft/BuildCraft#2793]
Hello Buildcraft Team:
As a Chinese minecraft player who usually add a whole bunch of tech mods, I am worrying about other Chinese players cannot get latest BC, or learn what added/changed/removed/improved/etc., due to the barrier of language. So, now, here I request for the permission of reposting Buildcraft to www.mcbbs.net , the largest unofficial minecraft forum in China. (This website has been recorded [here] (https://minecraft.net/community))

The entire repost will OBEY the [licence used by Buildcraft (MMPL)] (https://github.com/BuildCraft/BuildCraft/blob/6.5.x/LICENSE) as well as the [licence used by Buildcraft API (MIT)] (https://github.com/BuildCraft/BuildCraft/blob/6.5.x/LICENSE.API) WITHOUT any condition.

Some of the key terms:
1.I will clearly STATES the official website, the mcf page as well as the github page here at the head of my repost page. Also I will either list the core contributors' name, or give a link to [the contribution history page] (https://github.com/BuildCraft/BuildCraft/graphs/contributors)
2.I will give the download link from the official Buildcraft website directly and clearly note that "This is the official download link, please click it first"
3.(Optional) In case of that net speed varies on different positions in China, I probably prepare another mirror link to download Buildcraft. I can make sure (even I can swear) that the link will direct to a ad-free page, and people just need to click "download" to get Buildcraft as if they use dropbox.
4.Last but not least, I won't use it to get ANY profit/benefit in terms of money, etc., and I will stats that anyone who use Buildcraft cannot use Buildcraft to make money.

I know #stopmodrepost, and I know that some modders' hearts have been hurt by some disgusted website. However, I also know the barrier of language blocks many players to enjoy the latest (also bug-free?) Buildcraft 7.
Please have a look on my request. If I get permission from BC Team, I will say appreciate with my real herat; if not, I will still say appreciate to the person/people who spend their time on reading the whole request. 
Last, if there is grammatical mistakes, please forgive me because my English is still poor. 

Sincerely
3TUSK

**Comment by asiekierka** [comment]
The license is the only binding agreement of BC. Follow that and you shall be fine.

**Comment by 3TUSK** [comment]
Thanks a lot!

**Comment by 3TUSK** [comment]
@asiekierka Sorry for bothering again on this old issue. I hereby request to revoke my permission of reposting BuildCraft, without conditions, due to a severe issue regarding on Minecraft mod reposting. I have removed the contents of the [post](http://mcbbs.tvt.im/thread-455049-1-1.html) and have sent notification to forum moderators, and I am waiting for them to remove the thread entirely.

**Comment by asiekierka** [comment]
We have never granted you any explicit permissions, so what is there to revoke?

**Comment by 3TUSK** [comment]
Just in case if there is any... well, maybe I thought too much on this topic. Repost has been a controversial topic on my side for a very long while...

**Comment by asiekierka** [comment]
@3TUSK Many mods don't require permissions to repost at all, as long as the terms of the license are followed. BuildCraft is one of them.

**Comment by AEnterprise** [comment]
@3TUSK what about if we make a formal post on the BC forum and link to your repost from the site stating it's explicitly allowed?

**Comment by asiekierka** [comment]
@AEnterprise We cannot legally do that. Giving ANY explicit permissions not already covered by the license requires the agreement of every contributor - yes, all 150+ of them; and, if they're covered, we need not giv ethem.

**Comment by AEnterprise** [comment]
no we can't all give them explicit permission, but we can keep tabs on a few of them and kinda "verify" some as legit uploads we could check every once in a while. while none of them require permission we verify that some are realy the bc version like they claim and not a modified version that will do other things

**Comment by 3TUSK** [comment]
@asiekierka @AEnterprise

> what about if we make a formal post on the BC forum and link to your repost from the site stating it's explicitly allowed?

I have already removed my post for a severe reason. I don't think GitHub is a place to elaborate [the reason](https://en.wikipedia.org/wiki/NetEase#Licensed_Online_Games), and I cannot found an English article that demonstrate my concerns very well.

> Many mods don't require permissions to repost at all, as long as the terms of the license are followed and respected.

I *have acknowledged* that point long before. 
The situation is that, most modders still want single, legit distribution method for various reasons e.g. prevent users from using out-dated version; things like Curseforge which somehow pay mod dev back; counting downloads; et cetera. (Think about #StopModRepost) I know what Buildcraft's license allows me to do, what I did is just for (redundant) formality sake...

 
Beside of that, I wonder if any of buildcraft devs have been contacted with someone who claimed as employee from [NetEase](https://en.wikipedia.org/wiki/NetEase)?

**Comment by asiekierka** [comment]
@3TUSK Yes, ping me on #buildcraft at any time. I'll be happy to elaborate our stance further.

**Comment by AEnterprise** [comment]
@3TUSK i wanted to update BC on curse and i did get a message from someone claiming to be from netease (send to the buildcraftschildplay account on curse, wouldn't have seen it if i hadn't missclicked)

not sure what or if we should do something with it but could you confirm if a @corp.netease.com email is indeed the email domain used by that company?

**Comment by asiekierka** [comment]
@AEnterprise I have already taken care of the NetEase thing. Don't worry about it.

**Comment by AEnterprise** [comment]
@asiekierka you sure? the message was from about 2 hours ago

**Comment by asiekierka** [comment]
@AEnterprise Yes, I am fairly sure about that.

**Comment by 3TUSK** [comment]
@AEnterprise Just to clarify, I am not affiliated to NetEase, but here is the [citation](https://minecraft.net/en-us/article/minecraft-closed-beta-comes-china) you want.

**Comment by AEnterprise** [comment]
yeah i've seen the MC announcement, just wanted to know the email adress was legit or just a prank/phishing, wouldn't be the first time someone tries to use something like this to fool others and take credit for a mod he/she didn't make

**Comment by 3TUSK** [comment]
Well, you could try click into netease.com and see what we get

> Seems redundant though

**Comment by AEnterprise** [comment]
already did that quickly, on their official site corp.netease.com is the email domain used for general contact information so itt's legit, already send them an email that for BC things should be handled with asie if they are not already in order
