### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by blockbreaker1361** [BuildCraft/BuildCraft#2794]
There seems to be a lack of documentation on how the robots work and how to use them properly. It would be extremely nice if you could have an actual wiki made by your team or maybe there could be some in-game documentation on them. I like the In Game Wiki mod. It would be a great format for everything Buildcraft. Thank you and have a wonderful day. :)

**Comment by AgentK9** [comment]
https://docs.google.com/document/d/1w0odEh0LMYfAYakwRU5N88xSivPSnF3ZXZj1AWJ-vyU/edit

**Comment by AEnterprise** [comment]
in-game documentation is comming in BC itself (once it's all been written)
