### ISSUE TITLE
Galacticcraft Crude Oil / Fuel Compatiblity

### ISSUE THREAD

**Issue by kremsy** [BuildCraft/BuildCraft#2795]
As found out in this topic: https://github.com/BuildCraft/BuildCraft/issues/2789 the Crude Oil from Galacticcraft looks the same as the Buildcraft one but the Buildcraft Rafineries and Diamond Pipes are not working with it. It would be good if it could be completely compatible with the Buildcraft Oil. Galacticcraft has also a Fuel but havent tested if that is compatible with Buildcraft.

Another thing is that you cant put anything of the crude oil out of a Buildcraft tank with a Bucket.

**Comment by asiekierka** [comment]
I believe the decision was intentional on their side or they would have added it themselves via our APIs.

**Comment by kremsy** [comment]
But still why do the Diamon Pipes not work with it? If I put two tanks, one Im sorting out something, the rest should go in the other, it doesnt go in the other.

**Comment by radfast** [comment]
This is a good example of how difficult mod compatibility is.

Over at Galacticraft we intend for our mod to be compatible with other tech mods as we know players like to use these mods together.  But Galacticraft is of course a freestanding mod with its own systems, not a submod of Buildcraft (nor IC2 nor Mekanism nor Thermal Expansion nor other CoFH and RF mods, all of which Galacticraft is also compatible with).  This means we certainly very much appreciate the help given by the Buildcraft guys to get things 100% compatible.

We can use the Buildcraft API to add a Buildcraft Refinery recipe for the Galacticraft oil, that is no problem.

The diamond pipes thing, it seems like that is something that may have to be investigated and fixed on Buildcraft's side, at least I can't right now see any reason why it shouldn't be working.  To put this another way: I'm happy to do anything on our side which is needed to get this working: I just don't know what that "thing" is...

**Comment by jonabrv1965** [comment]
It seems that there are some work in progress from Galacticraft team about this. With the .350 update (the latest version of GC as of July 30, 2015) the BC refineries (and the Quarryplus ones, by the way) works fine with either oils (BC or GC), but.... and this is a big "but" .350 update broke the loading oil to tier 3 rockets! see: https://github.com/micdoodle8/Galacticraft/issues/1778 (and wont load oil in the tier4-8 rockets from more planets mod either!). I'm back and forth changing the version of GC mod and reloading Minecraft any time I have to refill my rockets... a pain in the....
