### ISSUE TITLE
Forestry Apiarist's Pipe Not Craftable

### ISSUE THREAD

**Issue by gazebomom** [BuildCraft/BuildCraft#2797]
As of BuildCraft version 7.0.0, the Forestry Apiarist's Pipe is no longer craftable.

It works with BuildCraft version 6.4.17

Forestry Versions tested: 3.5.7.16, 3.5.6.15 (and others in between)

I am reporting this bug to both BuildCraft and Forestry.

**Comment by SandGrainOne** [comment]
The Apiarist Pipe was moved to a third mod, BuildCraftCompat.
