### ISSUE TITLE
BC7 gold waterproof pipes have invisible blockages

### ISSUE THREAD

**Issue by Kalbuck** [BuildCraft/BuildCraft#2800]
Since upgrading to BC 7.0.9 yesterday, my existing pipes connected to machines and inventories have invisible blockages, wherein water/lava/whatever won't move past a certain block. I have to destroy the affected pipe and then place it again, wherein the fluid will continue to move past as it should. I already went through once and "fixed" all my pipes by re-placing them, but now upon logging back into my world again the problem is back. It seems to be corner pipes and turns that are affected most. 

![2015-06-13_22 27 56](https://cloud.githubusercontent.com/assets/11761718/8146830/ce7407f6-121b-11e5-9123-7d38a62884d5.png)

![2015-06-13_22 28 09](https://cloud.githubusercontent.com/assets/11761718/8146832/d5eb9328-121b-11e5-948a-458c0414a495.png)

**Comment by asiekierka** [comment]
Is it just a rendering issue? That's important. If yes, then I am aware of this one.

**Comment by kremsy** [comment]
Have the same issue and I guess its only a rendering issue.

**Comment by Kalbuck** [comment]
My apologies. After further testing, I've confirmed it is indeed only a rendering issue.
