### ISSUE TITLE
7.0.9 - Tile Entity Crash

### ISSUE THREAD

**Issue by iDrewt** [BuildCraft/BuildCraft#2803]
http://pastebin.com/dk2wD2FD

Pre-gennerated my world overnight and a friend started flying around, when he loaded this chunk it crashed the server. 

See crash log. 

Thanks :)

**Comment by iDrewt** [comment]
And if it helps... My Dynmap looks like this at those coords... 

http://puu.sh/ip5vV/9ceeb223df.png

**Comment by liach** [comment]
BCA?

**Comment by iDrewt** [comment]
It's the village world gen. I had to go into NBT explorer and delete the pipes. BCA is in here.

**Comment by liach** [comment]
I mean you should report it to BCA first. BuildCraft-Additions called some BuildCraft functions and crashed.

**Comment by hea3ven** [comment]
Same as #2799 will be fixed next version.
