### ISSUE TITLE
Disconnect with Internal Server Error (Nullpointerexception on Structure Pipes?)

### ISSUE THREAD

**Issue by kremsy** [BuildCraft/BuildCraft#2804]
I built something with Structure Pipes and pipe wires on it, and sometimes I get this random disconnect from the server, on the client it just says Internal Server Error.

15.06 17:14:22 [Server] Server thread/INFO §6XeRoX§r left the game
15.06 17:14:22 [Disconnect] User XeRoX has disconnected, reason: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
15.06 17:14:22 [Server] INFO at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
15.06 17:14:22 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
15.06 17:14:22 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
15.06 17:14:22 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
15.06 17:14:22 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
15.06 17:14:22 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
15.06 17:14:22 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
15.06 17:14:22 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
15.06 17:14:22 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
15.06 17:14:22 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
15.06 17:14:22 [Server] INFO at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376) ~[mx.class:?]
15.06 17:14:22 [Server] INFO at buildcraft.transport.BlockGenericPipe.func_149727_a(BlockGenericPipe.java:674) ~[BlockGenericPipe.class:?]
15.06 17:14:22 [Server] INFO java.lang.NullPointerException

**Comment by asiekierka** [comment]
Duplicate. Use http://nallar.me/buildservice/job/Buildcraft/727/artifact/build/libs/buildcraft-7.0.10.jar
