### ISSUE TITLE
Rewrite "valve" system into something better

### ISSUE THREAD

**Issue by mimic2300** [BuildCraft/BuildCraft#2808]
Hi again, if set on Basic Gate (redstone - closed) and use lever so turn OFF works currectly but turn ON not works - energy pipe is still OFF.
Please, fix it.

BC 7.0.9 MC 1.7.10 Forge 10.13.3.1428

**Comment by laz2727** [comment]
Is it lit up? The side might be wrong.

**Comment by mimic2300** [comment]
yes, graphics action works, but logic for change state from ON to OFF not

**Comment by laz2727** [comment]
Does the gate touch the lever?

**Comment by hea3ven** [comment]
Try having a separate action with (no redstone - open). Once you "close" a pipe, it will stay in that state until you tell it to "open".

**Comment by asiekierka** [comment]
Oh, yeah. That. We made it that way because some triggers only fire once and not constantly.

**Comment by mimic2300** [comment]
sorry, but i dont understand... i try 2x Gates.. first set redstone ON - closed and second redstone OFF - open and still not work.. i try separated and both in same time.. if any way "close" pipe so i can not open it again

**Comment by mimic2300** [comment]
ok.. OR gate works, but simple AND gate not

**Comment by SandGrainOne** [comment]
It is a bit counterintuitive that not even removing the gate opens up the pipe again. It will not open unless you give it the open "command" with a gate. It is fine when you know of this limitation, but is bound to be very confusing for the uninitiated.

**Comment by RagaRBM** [comment]
I know I don't have a say, but I completely agree with SandGrainOne.

**Comment by asiekierka** [comment]
It is unintuitive, but changing behaviour cannot just be done in a point release. My plan was to add explicit Valves to put on a pipe, which actually close and open - so you can see what is going on.

**Comment by mimic2300** [comment]
Hm, so i must always use OR gate for open/close pipe?

And it would be possible to add a simple valve, which would also suspend all the engines that are connected to the pipeline?

**Comment by SandGrainOne** [comment]
I tested with an AND gate and that worked fine. AND gates will only AND two "lines" with the same action and "Close" and "Open" are different actions.

**Comment by asiekierka** [comment]
Or just remove the valves!
