### ISSUE TITLE
only allow specific robots on a station

### ISSUE THREAD

**Issue by AEnterprise** [BuildCraft/BuildCraft#2811]
could an option be added to only allow specific robots in a station? and then i don't mean like only cariers or only delivery robots bot a specific robot, for example by naming robots and using them in a gate only robots that have the same name would be allowed to dock on a station.

the idea behind this is to be able to dedicate certain robots to certain tasks in an area, for example to make sure only a specific planter can get items from a chest to plant with, setting things up with zone planners and/or map locations isn't always very easy/feasable to do and gives problems with compact builds where there things are realy close to each other

**Comment by asiekierka** [comment]
Names and string tagging in general has always felt too obvious to me. I do, however, wish to add tagging by helmet/overlay item.

**Comment by AEnterprise** [comment]
that works as well, might even be better as you can visually see it on the robot then
