### ISSUE TITLE
[7.0.10] Crash on inserting Blueprint into Builder

### ISSUE THREAD

**Issue by Tonius** [BuildCraft/BuildCraft#2812]
- Created a blueprint using an Architect Table. Saved a rather large chunk of forest terrain.
- Tried to insert the blueprint into a Builder, rotated differently than the Architect Table.
- Game crashed with following report: http://puu.sh/iqPwM/5225bbbd31.txt

EDIT: This is the blueprint I created: http://puu.sh/iqQun/d46484a573.bpt

**Comment by asiekierka** [comment]
Fixed in 7.0.11
