### ISSUE TITLE
[suggestion]robots should have a GUI

### ISSUE THREAD

**Issue by n00b7** [BuildCraft/BuildCraft#2816]
robots should have a gui for telling the amount of power in it and whether it inventory is full
or has space or empty heres what it should look like:
![generic_ui](https://cloud.githubusercontent.com/assets/11874683/8220602/f4453cf2-1522-11e5-8060-4e753b0ea528.png)

![symbols](https://cloud.githubusercontent.com/assets/11874683/8220752/9d3be742-1524-11e5-8414-7cdd14ed88ee.png)

**Comment by asiekierka** [comment]
The red light on the robot already shows the battery level and sleep state, and you don't need to know the rest. GUIs are overrated.
