### ISSUE TITLE
Unable to craft Auto Workbench

### ISSUE THREAD

**Issue by DoctorToast3** [BuildCraft/BuildCraft#2817]
I'm not sure if this is just a recipe change or an actual bug (I just upgraded to Buildcraft 7.0.11 and haven't made this item for awhile), but I am unable to craft an Auto Workbench. I have put a regular crafting table at the center of the recipe and have added a wooden gear on the top, left, bottom, and right of it in the grafting grid but no output is given.

I'm using Buildcraft 7.0.11, Railcraft 9.6.1.0, Iron Chest 6.0.41 build 729, Iron Chest Minecarts 1.0.0, Buildcraft Compat 7.0.4, OpenEye 0.6, and Minecraft Forge 10.13.3.1428. Running on Minecraft 1.7.10.

![2015-06-17_20 39 12](https://cloud.githubusercontent.com/assets/11801214/8222503/0db4bdb6-1532-11e5-994f-e88a48c86a68.png)

**Comment by asiekierka** [comment]
The recipe changed. Try two stone gears.
