### ISSUE TITLE
Game crash after set fuel in a wrong place on my map

### ISSUE THREAD

**Issue by Hitman4** [BuildCraft/BuildCraft#2824]
Hello,

i have wrongly placed fuel on my map and that is going to crash my game

---- Minecraft Crash Report ----
// I let you down. Sorry Sad

Time: 16.06.15 23:48
Description: Rendering entity in world

java.lang.IllegalStateException: Already tesselating!
at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
at buildcraft.core.lib.render.RenderEntityBlock.renderBlock(RenderEntityBlock.java:183)
at buildcraft.core.lib.render.RenderEntityBlock.doRenderBlock(RenderEntityBlock.java:173)
at buildcraft.core.lib.render.RenderEntityBlock.func_76986_a(RenderEntityBlock.java:137)
at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271)
at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244)
at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:712)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1305)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
at buildcraft.core.lib.render.RenderEntityBlock.renderBlock(RenderEntityBlock.java:183)
at buildcraft.core.lib.render.RenderEntityBlock.doRenderBlock(RenderEntityBlock.java:173)
at buildcraft.core.lib.render.RenderEntityBlock.func_76986_a(RenderEntityBlock.java:137)

-- Entity being rendered --
Details:
Entity Type: null (buildcraft.core.lib.EntityBlock)
Entity ID: 154
Entity Name: Unbekannt
Entity's Exact location: -214,75, 62,01, 1417,25
Entity's Block location: World: (-215,62,1417), Chunk: (at 9,3,9 in -14,88; contains blocks -224,0,1408 to -209,255,1423), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
Entity's Momentum: 0,00, 0,00, 0,00

-- Renderer details --
Details:
Assigned renderer: buildcraft.core.lib.render.RenderEntityBlock@71bc0674
Location: -4,24,-19,57,-38,58 - World: (-5,-20,-39), Chunk: (at 11,-2,9 in -1,-3; contains blocks -16,0,-48 to -1,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Rotation: 0.0
Delta: 0.5654131
Stacktrace:
at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271)
at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244)
at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:712)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityClientPlayerMP['Hitman_GER'/1961, l='MpServer', x=-210,51, y=81,58, z=1455,83]]
Chunk stats: MultiplayerChunkCache: 175, 175
Level seed: 0
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options:
Level spawn location: World: (4,64,68), Chunk: (at 4,4,4 in 0,4; contains blocks 0,0,64 to 15,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 4732835 game time, 4904514 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Forced entities: 65 total; [EntityClientPlayerMP['Hitman_GER'/1961, l='MpServer', x=-210,51, y=81,58, z=1455,83], EntityBlock['Unbekannt'/154, l='MpServer', x=-214,75, y=62,01, z=1417,25], EntityBlock['Unbekannt'/155, l='MpServer', x=-204,75, y=62,01, z=1417,25], EntityItem['item.item.redstone'/1962, l='MpServer', x=-209,63, y=69,13, z=1447,19], EntityItem['item.item.diode'/1963, l='MpServer', x=-208,13, y=69,13, z=1446,16], EntityItem['item.item.redstone'/1964, l='MpServer', x=-208,50, y=73,13, z=1440,88], EntityItem['item.item.diode'/1965, l='MpServer', x=-206,13, y=69,13, z=1444,16], EntityPig['Schwein'/1966, l='MpServer', x=-237,44, y=68,00, z=1438,56], EntityItem['item.item.redstone'/1967, l='MpServer', x=-206,19, y=73,22, z=1439,88], EntityItem['item.item.diode'/1968, l='MpServer', x=-206,53, y=69,13, z=1438,19], EntityItem['item.item.diode'/1969, l='MpServer', x=-198,84, y=69,13, z=1435,09], EntityItem['item.item.diode'/1970, l='MpServer', x=-206,13, y=69,13, z=1432,81], EntitySheep['Schaf'/1971, l='MpServer', x=-249,50, y=47,00, z=1451,34], EntityPig['Schwein'/1972, l='MpServer', x=-255,39, y=63,00, z=1444,34], EntityPig['Schwein'/1973, l='MpServer', x=-250,47, y=48,00, z=1454,66], EntitySheep['Schaf'/1974, l='MpServer', x=-254,41, y=63,00, z=1441,69], EntityPig['Schwein'/1975, l='MpServer', x=-181,50, y=60,05, z=1453,47], EntitySquid['Tintenfisch'/1976, l='MpServer', x=-219,35, y=61,00, z=1480,04], EntitySquid['Tintenfisch'/1977, l='MpServer', x=-224,50, y=61,00, z=1483,75], EntityPig['Schwein'/1978, l='MpServer', x=-254,50, y=69,00, z=1421,69], EntityBat['Fledermaus'/1979, l='MpServer', x=-262,53, y=16,10, z=1446,25], EntityPig['Schwein'/1980, l='MpServer', x=-272,88, y=63,00, z=1451,72], EntitySheep['Schaf'/1981, l='MpServer', x=-174,56, y=64,00, z=1453,25], EntityBat['Fledermaus'/1982, l='MpServer', x=-261,69, y=13,00, z=1441,31], EntityPig['Schwein'/1983, l='MpServer', x=-256,50, y=69,00, z=1436,50], EntityBat['Fledermaus'/1984, l='MpServer', x=-194,88, y=57,10, z=1404,44], EntityPig['Schwein'/1985, l='MpServer', x=-160,91, y=63,00, z=1438,06], EntitySquid['Tintenfisch'/1986, l='MpServer', x=-159,60, y=59,57, z=1464,97], EntitySheep['Schaf'/1987, l='MpServer', x=-169,16, y=63,00, z=1464,63], EntitySheep['Schaf'/1988, l='MpServer', x=-253,50, y=73,00, z=1494,34], EntityPig['Schwein'/1989, l='MpServer', x=-256,03, y=64,00, z=1420,50], EntityPig['Schwein'/1990, l='MpServer', x=-256,94, y=63,00, z=1411,09], EntitySheep['Schaf'/1991, l='MpServer', x=-259,91, y=71,00, z=1411,53], EntitySheep['Schaf'/1992, l='MpServer', x=-161,96, y=63,00, z=1486,47], EntityBat['Fledermaus'/1993, l='MpServer', x=-285,50, y=14,36, z=1454,31], EntityBat['Fledermaus'/1994, l='MpServer', x=-284,91, y=14,00, z=1454,84], EntityPig['Schwein'/1995, l='MpServer', x=-279,47, y=62,00, z=1465,66], EntityPig['Schwein'/1996, l='MpServer', x=-278,25, y=68,00, z=1469,53], EntitySquid['Tintenfisch'/1997, l='MpServer', x=-155,47, y=58,42, z=1469,66], EntitySquid['Tintenfisch'/1998, l='MpServer', x=-158,94, y=58,44, z=1469,14], EntityPig['Schwein'/1999, l='MpServer', x=-145,94, y=69,00, z=1459,94], EntityPig['Schwein'/2000, l='MpServer', x=-250,53, y=65,00, z=1513,53], EntityPig['Schwein'/2001, l='MpServer', x=-157,47, y=61,00, z=1479,44], EntitySquid['Tintenfisch'/2002, l='MpServer', x=-155,47, y=57,18, z=1472,17], EntitySquid['Tintenfisch'/2003, l='MpServer', x=-156,79, y=58,16, z=1472,50], EntityPig['Schwein'/2004, l='MpServer', x=-280,97, y=63,00, z=1501,84], EntityBat['Fledermaus'/2006, l='MpServer', x=-169,47, y=47,10, z=1379,25], EntityCartChest['entity.MinecartChest.name'/2134, l='MpServer', x=-121,50, y=14,69, z=1331,50], EntityBat['Fledermaus'/2007, l='MpServer', x=-166,22, y=45,00, z=1385,84], EntityCow['Kuh'/2008, l='MpServer', x=-171,72, y=63,00, z=1378,66], EntityBat['Fledermaus'/2009, l='MpServer', x=-148,63, y=35,10, z=1407,72], EntityPig['Schwein'/2010, l='MpServer', x=-141,91, y=71,00, z=1454,94], EntitySheep['Schaf'/2011, l='MpServer', x=-209,81, y=63,00, z=1526,63], EntityPig['Schwein'/2013, l='MpServer', x=-290,06, y=65,00, z=1458,91], EntityCartChest['entity.MinecartChest.name'/2141, l='MpServer', x=-140,50, y=13,85, z=1318,50], EntityPig['Schwein'/2014, l='MpServer', x=-290,81, y=72,00, z=1432,50], EntityPig['Schwein'/2016, l='MpServer', x=-141,16, y=69,00, z=1461,50], EntitySheep['Schaf'/2017, l='MpServer', x=-197,84, y=63,00, z=1535,84], EntityCow['Kuh'/2018, l='MpServer', x=-244,88, y=61,00, z=1535,81], EntityPig['Schwein'/2020, l='MpServer', x=-280,47, y=70,00, z=1515,47], EntityPig['Schwein'/2021, l='MpServer', x=-281,53, y=70,00, z=1516,53], EntityPig['Schwein'/2022, l='MpServer', x=-135,59, y=61,00, z=1501,69], EntityBat['Fledermaus'/2025, l='MpServer', x=-166,84, y=18,60, z=1532,53], EntitySheep['Schaf'/2042, l='MpServer', x=-158,47, y=63,00, z=1524,59], EntityPig['Schwein'/2043, l='MpServer', x=-147,94, y=62,00, z=1527,06]]
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Non-integrated multiplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 8.1 (amd64) version 6.3
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot™ 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 460446280 bytes (439 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
FML: Minecraft 1.7.10 MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1451 Optifine OptiFine_1.7.10_HD_U_B7 39 mods loaded, 39 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
UCHIJA FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1451-1.7.10.jar)
UCHIJA Forge{10.13.4.1451} [Minecraft Forge] (forge-1.7.10-10.13.4.1451-1.7.10.jar)
UCHIJA CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar)
UCHIJA NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal.jar)
UCHIJA PlayerAPI{1.0} [Player API] (minecraft.jar)
UCHIJA SmartCore{1.0.2} [Smart Core] (minecraft.jar)
UCHIJA DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar)
UCHIJA Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar)
UCHIJA BuildCraft|Core{7.0.11} [BuildCraft] (buildcraft-7.0.11.jar)
UCHIJA BuildCraft|Energy{7.0.11} [BC Energy] (buildcraft-7.0.11.jar)
UCHIJA BuildCraft|Factory{7.0.11} [BC Factory] (buildcraft-7.0.11.jar)
UCHIJA BuildCraft|Robotics{7.0.11} [BC Robotics] (buildcraft-7.0.11.jar)
UCHIJA BuildCraft|Silicon{7.0.11} [BC Silicon] (buildcraft-7.0.11.jar)
UCHIJA BuildCraft|Transport{7.0.11} [BC Transport] (buildcraft-7.0.11.jar)
UCHIJA BuildCraft|Builders{7.0.11} [BC Builders] (buildcraft-7.0.11.jar)
UCHIJA craftguide{1.6.8.2} [CraftGuide] (CraftGuide-1.6.8.2-forge.jar)
UCHIJA props{2.0.2} [Decocraft] (Decocraft-2.0.2_1.7.10.jar)
UCHIJA DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.7.10.jar)
UCHIJA DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar)
UCHIJA DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar)
UCHIJA DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar)
UCHIJA DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar)
UCHIJA DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar)
UCHIJA DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar)
UCHIJA DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar)
UCHIJA DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar)
UCHIJA DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar)
UCHIJA eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar)
UCHIJA FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar)
UCHIJA FoodPlus{3.2rS} [§bFood Plus] (FoodPlus-1.7.2-3.2rS.jar)
UCHIJA IC2{2.2.736-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.736-experimental.jar)
UCHIJA journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar)
UCHIJA cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar)
UCHIJA Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar)
UCHIJA SmartMoving{15.5} [Smart Moving] (SmartMoving-1.7.10-15.5.jar)
UCHIJA SmartRender{2.1} [Smart Render] (SmartRender-1.7.10-2.1.jar)
UCHIJA StorageDrawers{1.7.10-1.5.6} [Storage Drawers] (StorageDrawers-1.7.10-1.5.6.jar)
UCHIJA AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar)
Launched Version: 1.7.10-Forge10.13.4.1451-1.7.10
LWJGL: 2.9.1
OpenGL: GeForce GTS 450/PCIe/SSE2 GL version 4.5.0 NVIDIA 352.86, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Sphax PureBDcraft 32x MC17.zip]
Current Language: Deutsch (Deutschland)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)

**Comment by AEnterprise** [comment]
you have optifine installed and that is most likely causing this, can you remove optifine and try again?

**Comment by Hitman4** [comment]
Yes , after removing optifine it's working thx =)

**Comment by asiekierka** [comment]
I have no way to check whether the Tessellator is tessellating - in other words, I have no coremodless way of fixing this issue.
