### ISSUE TITLE
[Mod Interaction][Bug]

### ISSUE THREAD

**Issue by ReikaKalseki** [BuildCraft/BuildCraft#2825]
For some reason, the BC quarry seems to mostly ignore ReactorCraft fluorite ores. I have no idea why, seeing as the most unusual thing about this ore is its luminosity.

Its code for reference:
https://github.com/ReikaKalseki/ReactorCraft/blob/master/Blocks/BlockFluoriteOre.java
https://github.com/ReikaKalseki/ReactorCraft/blob/master/Blocks/BlockFluorite.java

My best guess is its transparency to light that is making this happen.

**Comment by BigXplosion** [comment]
I heard that making sure that your block is opaque (or any other indicator that would make it a full block) is a fix for this.

**Comment by asiekierka** [comment]
It is strange, and it's not the first report. This is worth checking.

**Comment by ReikaKalseki** [comment]
> I heard that making sure that your block is opaque (or any other indicator that would make it a full block) is a fix for this.

As I said, while isOpaqueCube() returns true, it is not opaque in the normal sense, nor can it be, because that will cause render glitches.

**Comment by ReikaKalseki** [comment]
So...any updates?

**Comment by asiekierka** [comment]
I usually leave the stranger issues for when I'm in a good mood. Maybe today.

**Comment by ReikaKalseki** [comment]
Works for me. :P

**Comment by asiekierka** [comment]
@ReikaKalseki - tried putting deobf ReactorCraft into workspace, crashed on signatures. Woo.

**Comment by ReikaKalseki** [comment]
Try adding it as source. Also how did you get a deobf version?

**Comment by asiekierka** [comment]
I used "illegal" methods, that is Bearded Octo Nemesis, but you sign your stuff so it failed.

**Comment by ReikaKalseki** [comment]
I have no problem with BON for this purpose, but yes, the jar signing will catch that. Do you need me to make a source jar?

**Comment by asiekierka** [comment]
I fixed it already, so no.

**Comment by ReikaKalseki** [comment]
Oh, good. What was causing it?

**Comment by psxlover** [comment]
https://github.com/BuildCraft/BuildCraft/commit/915d900a409208c7be968f009d222d2b2bc29eb7
