### ISSUE TITLE
Quarry has no output?

### ISSUE THREAD

**Issue by nevestul4o** [BuildCraft/BuildCraft#2826]
I don't know why, but sometimes the quarry stops to output items in the pipe, connected to it. I'm using a stone pipe and Thermal expansion energy conduits. Recently I updated the buildcraft mod to its latest version and then this problem occurred.
![2015-06-20_18 10 07](https://cloud.githubusercontent.com/assets/12813622/8267852/49242164-1778-11e5-9dc8-a678641a8121.png)

**Comment by asiekierka** [comment]
Can you replicate the issue with a BC energy pipe? Is nothing connected on the bottom?

**Comment by nevestul4o** [comment]
I just tried to connect BC pipes, it still had no output. 
![2015-06-21_23 28 48](https://cloud.githubusercontent.com/assets/12813622/8273254/6dd2f256-186d-11e5-97d0-33f231839241.png)
However when I restarted the server it started to work again o_0.
![2015-06-21_23 34 06](https://cloud.githubusercontent.com/assets/12813622/8273260/05fcbf1c-186e-11e5-837b-0ae92cf09829.png)

**Comment by AEnterprise** [comment]
might be connected to #2790 it might have been outputting but not rendering the items
