### ISSUE TITLE
[Request] Zonemap save folder change

### ISSUE THREAD

**Issue by BevoLJ** [BuildCraft/BuildCraft#2827]
o/

In my SSP I change the name of my save folder after every video I record [for record keeping and backups so incase I need to rollback so I don't lose the Let's Play].  It seems once I started making maps it now creates folders with the old names every time I log back in. They are empty folders, but I was wondering if there was a way to disable it from creating those folders.

**Comment by asiekierka** [comment]
It only creates the folder once a world is loaded. It should not be creating the old ones.

**Comment by BevoLJ** [comment]
Yep, did not run into this issue at all in my last recording.  No idea what was going on previously.  I was getting lots of saved game folder.  Seems all good.  =)
