### ISSUE TITLE
Stamping Table Bucket Issue

### ISSUE THREAD

**Issue by LouisHutch** [BuildCraft/BuildCraft#2830]
BC 7.0.11

I have a packager which creates a package with this factorization recipe:
http://imgur.com/a/Ks149

The stamper will 'stamp' the package and will output the clean gold gravel, the empty bucket and the occational sludge into the adjacent pipe. The stamper as well as outputing its contents to the pipes it may also 'spit out' a bucket and the occasional sludge onto the floor therefore duping the bucket. It may also dupe the sludge but i am unsure due to its random probability.

P.S. The autoworkbench doesnt accept water buckets in a recipe

**Comment by asiekierka** [comment]
Fixed in 7.0.12 via that other Stamper issue.

P.S. We know it don't, it won't.
