### ISSUE TITLE
Robots misc.

### ISSUE THREAD

**Issue by kitsu** [BuildCraft/BuildCraft#2831]
I've tried my first build with robots, and they work well enough (90% maintenance free). I have run into some annoying problems though:

  * Planter plants saplings on farm land - ruining farms.
  * Harvester didn't seem to work with landmark region.
  * Harvester is obsessed with grass but ignores flowers.
  * Lumberjack starts leaving bottom log (stump) after running a while (fixed by minecraft restart).
  * Lumberjack sometimes hangs when his axe breaks.

Using Buildcraft 7.0.11

BTW the Planter/Harvester seem to work fine with Nevermine2 crops :open_mouth:

**Comment by hea3ven** [comment]
> Planter plants saplings on farm land - ruining farms.

Yes, farm land is a valid spot to plant sapplings, so they will plant sapplings. You need to properly configure the robots to prevent this, either by zoning where the planter plants, or filtering what items the planter can pick up with the "Filter tool" gate action.

> Harvester didn't seem to work with landmark region.

Please post picks of the landmarks and gate configuration, it should be working.

> Harvester is obsessed with grass but ignores flowers

Unfortunately we've had to disable them picking flowers for now, due to compatibility with other mods.

> Lumberjack starts leaving bottom log (stump) after running a while (fixed by minecraft restart).

This is already fixed for the next version.

> Lumberjack sometimes hangs when his axe breaks.

Where does he get's his axes?, a chest right next to this linked docking station by any chance?

**Comment by kitsu** [comment]
Thanks for clarifying.

Lumberjack is docked on the power line, supply chest is in work zone. When he hangs his light turns black (dormant?). Toggling return to station resets him and he successfully grabs the next axe.

I will confirm landmark/Harvester issue when I segregate my tree and food farms.

**Comment by RagaRBM** [comment]
I can confirm that the first time I configured the Harvester to a specific Map Location, it did not respect the map. But when I restarted Minecraft the problem is fixed and never returns.

**Comment by kitsu** [comment]
Just tested with latest 7.0.12 and the Harvester does work in a landmarked zone - first try.

I did have a little problem though - I was in creative and just broke the pipe the bot was docked to. It then proceeded to sink through the ground and out of sight... I started digging down to find it when I got a Ticking entity `java.lang.ClassCastException: mods.railcraft.common.blocks.hidden.TileHidden cannot be cast to buildcraft.api.transport.IPipeTile` :laughing: So don't do that.

No news on broken axe hang, but I am assuming that is an issue with the modded axe I'm using. I will open a new issue if I have something to report.

**Comment by Mr-Turing** [comment]
I've also encountered the sinking robot issue, here's the pastebin of the error generated in the console: http://paste.feed-the-beast.com/view/98d0b740

Broke the pipe it was standing on (structure pipe with quartz gate and dockign station) and it fell through the ground slowly. The picker robot I broke in the same way a couple seconds late was fine.

**Comment by luizdgarcia** [comment]
as in version 7.1.14 I just had the same sinking bug, I broke the pipe and they fell though the world
