### ISSUE TITLE
fuel bug

### ISSUE THREAD

**Issue by n00b7** [BuildCraft/BuildCraft#2838]
when i go to place fuel and put fire near it
it spreads on top of the fuel and eventuly eats the fuel 

bug demonstation: http://tinypic.com/player.php?v=2uh02tl%3E&s=8

screenshot:
![2015-06-24_12 54 17](https://cloud.githubusercontent.com/assets/11874683/8336516/2cb2bb82-1a73-11e5-892a-2c058bb6c074.png)

**Comment by asl97** [comment]
that is a `Class B` fire. imo, not a bug.

**Comment by AEnterprise** [comment]
i would not classify this as a bug, in real life there are plenty of fluids that can burn and eventually burn up, fuel being one of them

**Comment by MrKickkiller** [comment]
Technically speaking it is not the fuel burning, but the vapours that rise from it. Liquid fuel (In real life) does NOT burn. It is the vapours that are rising from the fuel that burn up.

Same principle with a candle. Wax melts, gets drawn into the wick and then the gaseous wax burns up in the flame.

**Comment by BigXplosion** [comment]
this is not a bug, it's intentional :/

**Comment by Kubuxu** [comment]
@MrKickkiller this is a case over here also. The fire start about 0.0625-0.9375m above the fluid.

**Comment by MrKickkiller** [comment]
@Kubuxu Are we talking real life now, or Minecraft?
If real life, I think that margin could be less then 0.0625 m..

**Comment by Kubuxu** [comment]
MC. (1/16-15/16)
