### ISSUE TITLE
Suggestion: Location Storage

### ISSUE THREAD

**Issue by Speiger** [BuildCraft/BuildCraft#2840]
I nodest in the BevoLJ LetsPlay with BC that a Location Storage (TileEntity Based Not player)
would be kind of usefull. Giving locations Names and Save them in case you ever need them again in your world. ^^"

**Comment by asiekierka** [comment]
Too easy. Just carry Map Locations around.

**Comment by Speiger** [comment]
Then remove the builder libary because thats the same thing. You just could carry the blueprints with you!

**Comment by asiekierka** [comment]
No. How do you get them INTO the game? Map Locations are fairly simple: you
just use a Zone Planner, or landmarks.

2015-06-27 12:28 GMT+02:00 Speiger <notifications@github.com>:

**Comment by Speiger** [comment]
I did not talk about the Zoneplanner. Thats reasonable that you deny there.
I mean do you construct always your markers back to rebuild one of your Zones for robots?
Or do you keep the Zone always there to have it always ready? I do not think so.
It does not have to be a block. It can be a portable one to which you can stick into a safty chest or something...
