### ISSUE TITLE
Crash with oil in nether

### ISSUE THREAD

**Issue by Andrey96** [BuildCraft/BuildCraft#2841]
So, when there's some oil in nether, server crashes http://andrey96.ru/files/crash-2015-06-26_16.26.26-server.txt Latest buildcraft, latest forge

**Comment by asiekierka** [comment]
Upd---

...What?

**Comment by Andrey96** [comment]
It's incompatibility with some other mod, I'll try to find out what mod causes it.

**Comment by AEnterprise** [comment]
do you have that mod that adds fluid gravity?

**Comment by Andrey96** [comment]
Yes. I don't know exactly what mod does it (no special mods installed for it). I tried to reproduce it on new map by just emptying oil bucket in nether. But it just exploded. Seems that oil generated in nether somehow o_O

**Comment by hea3ven** [comment]
It's IHL Tools & Machines for IC2V2, it modifies fluids so that, for instance source blocks can move down hills by themselves. There already was another bug report about it some time ago.

**Comment by AEnterprise** [comment]
yeah, this causes crashes sometimes (not only with BC oil) because it is trying to update to many fluid blocks at the same time

**Comment by Andrey96** [comment]
At least I know what to turn off. It must be really huge amount of oil if it's crashed due to recursion (crash happens instantly after loading nether). And huge amount of oil is generated sphere of oil. And I'm not sure that it's IHL caused it to generate there.

**Comment by asiekierka** [comment]
Workaround until 7.0.14: disable oil explosions
