### ISSUE TITLE
Buildcraft error but extra utilities item

### ISSUE THREAD

**Issue by Solorgo** [BuildCraft/BuildCraft#2843]
I crash whenever I place item transfer nodes and makes my world unplayable so I have to refer to a backup. This is strange because the report mentions something about build craft but the 2 items causing the crash is from extra utilities and thermal expansion. Or possibly I have no idea what I am talking about :s

http://pastebin.com/47CmgPKf

**Comment by AEnterprise** [comment]
update extra utilities, if that doesn't fix it report on that issue tracker, extra utilities is using an outdated api
