### ISSUE TITLE
assembly table won't assemble RR3

### ISSUE THREAD

**Issue by smiletactician** [BuildCraft/BuildCraft#2845]
Hey,

RR3: Resonant Rise 3 mainline customised
3.2.6.8

Sorry I have no self generated crash or bug report. This has been happening for a while I didn't realise it will still exist. Maybe I haven't use laser tables in a (while)

Issue:
essentially the table will not even show the chipset result when the ingredients have been placed in the load side (left side) of the guy. This is after it has managed to produce multiple chipset (iron, gold and diamond) previously.

Let me know what information would help you out if at all.

**Comment by asiekierka** [comment]
Did you update before this started happening?

**Comment by smiletactician** [comment]
Allt he updates have happened, It intermittently decides when its gonna run the ingredients i've place. usually after i have completely reset MC.

**Comment by asiekierka** [comment]
Odd.

**Comment by smiletactician** [comment]
I'm not sure what or how to produce some kind of bug report as the issue seems pretty specific. Let me know if there's something I can do to help out.

**Comment by laz2727** [comment]
Sounds like desync.

**Comment by asiekierka** [comment]
Update to BC 7.0.12.

**Comment by smiletactician** [comment]
Coolio i'll try that and let you know
