### ISSUE TITLE
Critical Crash when laying fluid pipes

### ISSUE THREAD

**Issue by jccreszMinecraft** [BuildCraft/BuildCraft#2847]
When i'm setting up a energy source for diabolical experimentation with other mods like Big Reactors, if I happen to use any type of pipe in the wrong area, the world becomes corrupt and kicks me from world, giving a message "A fatal error has occurred".
I've collected what i can about the event.

[B#301]  [00:58:13] [Client thread/WARN] [FML]: ****************************************
[B#301]  [00:58:13] [Client thread/WARN] [FML]: * Null fluid supplied to fluidstack. Did you try and create a stack for an unregistered fluid?
[B#301]  [00:58:13] [Client thread/WARN] [FML]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:35)
[B#301]  [00:58:13] [Client thread/WARN] [FML]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
[B#301]  [00:58:13] [Client thread/WARN] [FML]: *  at buildcraft.transport.network.PacketFluidUpdate.readData(PacketFluidUpdate.java:87)
[B#301]  [00:58:13] [Client thread/WARN] [FML]: *  at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:47)
[B#301]  [00:58:13] [Client thread/WARN] [FML]: *  at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:22)
[B#301]  [00:58:13] [Client thread/WARN] [FML]: *  at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77)...
[B#301]  [00:58:13] [Client thread/WARN] [FML]: ****************************************
[B#301]  [00:58:13] [Client thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
[B#301]  io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
[B#301]  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
[B#301]  	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
[B#301]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[B#301]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[B#301]  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
[B#301]  	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
[B#301]  	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[B#301]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[B#301]  	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
[B#301]  	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
[B#301]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
[B#301]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
[B#301]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#301]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
[B#301]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
[B#301]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
[B#301]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
[B#301]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[B#301]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[B#301]  Caused by: java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
[B#301]  	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36) ~[FluidStack.class:?]
[B#301]  	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67) ~[FluidStack.class:?]
[B#301]  	at buildcraft.transport.network.PacketFluidUpdate.readData(PacketFluidUpdate.java:87) ~[PacketFluidUpdate.class:?]
[B#301]  	at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:47) ~[BuildCraftChannelHandler.class:?]
[B#301]  	at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:22) ~[BuildCraftChannelHandler.class:?]
[B#301]  	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
[B#301]  	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
[B#301]  	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
[B#301]  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
[B#301]  	... 18 more
[B#301]  [00:58:13] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel BC-TRANSPORT
[B#301]  io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
[B#301]  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
[B#301]  	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
[B#301]  	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
[B#301]  	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
[B#301]  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
[B#301]  	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
[B#301]  	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[B#301]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[B#301]  	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
[B#301]  	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
[B#301]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
[B#301]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
[B#301]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#301]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
[B#301]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
[B#301]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
[B#301]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
[B#301]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[B#301]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[B#301]  Caused by: java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
[B#301]  	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36) ~[FluidStack.class:?]
[B#301]  	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67) ~[FluidStack.class:?]
[B#301]  	at buildcraft.transport.network.PacketFluidUpdate.readData(PacketFluidUpdate.java:87) ~[PacketFluidUpdate.class:?]
[B#301]  	at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:47) ~[BuildCraftChannelHandler.class:?]
[B#301]  	at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:22) ~[BuildCraftChannelHandler.class:?]
[B#301]  	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
[B#301]  	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
[B#301]  	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
[B#301]  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
[B#301]  	... 18 more

**Comment by asiekierka** [comment]
Update BuildCraft. I think. The log doesn't tell me what version it is.

**Comment by jccreszMinecraft** [comment]
The version is 7.12.

**Comment by asiekierka** [comment]
I'm pretty sure it's not 7.0.12. Check again.

**Comment by jccreszMinecraft** [comment]
Further analysis: Version 7.11/7.12 has a big issue with Forestry. It only crashes when Forestry is present. I may need to report that there.

**Comment by asiekierka** [comment]
BUT did you update Forestry?

**Comment by jccreszMinecraft** [comment]
Yes.

**Comment by asiekierka** [comment]
The error doesn't seem like it's relevant to Forestry, though. In fact, the crashing class never creates any FluidStacks since BC 6.4.11/7.0.6! Thus why I suspect your BC is still outdated.

**Comment by jccreszMinecraft** [comment]
I've gotten a full crash log now and a list of installed mods.
http://pastebin.com/wXEgvUwU

**Comment by asiekierka** [comment]
This is a completely different bug fixed in 7.0.13 related to item pipes.

2015-06-30 23:18 GMT+02:00 jccreszMinecraft <notifications@github.com>:
