### ISSUE TITLE
BC Archtiect Table does not recognize all blocks

### ISSUE THREAD

**Issue by Chaos234** [BuildCraft/BuildCraft#2848]
If I want to save an area marked with land markers over a blueprint and an architect table it won't save all blocks in this area.

Blocks, which are missing:

All Blocks from BigReactors (they are not formed as a multiblock!) and some many more.
So the Architect Table should scan the entire area, after that he has to search for the blocks founded in the area in the item database and then he hast to count them (it seem that the limit is at 999 which is inacceptable because the max int value is 2 billion (in german 2 milliards)).

This should be simply done by scanning the entire item databse because it's a simpel system:

1st: Search for all Blocks in the specified area
2nd: Get the names foreach different Block (Dirt, Reactor Housing, Marble, Redstone Alloy, Redstine wire, ME Dense Cable, ...)
3rd: Get the amount for each founded Block without limitation to 999 because the int value is high enough for this.

So all Blocks can be get over this Tool and set over the BC Builder easily.

**Comment by asiekierka** [comment]
Sorry, we can't just support arbitrary tile entities. Dupe bugs would happen.

(Also, 999 is only a limit of the display area. It has been raised to "99K" recently)

**Comment by Chaos234** [comment]
BigReactors blocks are not arbitrary tile entities. They are a full block which forms into a multiblock if setuped correctly but to prevent a bug with that the multiblock will be not be compleatly builded it will missing one block so e. g. the tourbine housing or the reactor glass are normal blocks.

Also I can't accept that you wouldn't do this but supporting carpenter's blocks which are tile entities and there are no bugs with them and in addition they are also placed correctly and the detection what carpenter's block it is, is also working so I can't understand this desicion.

For me it's a dissent to the actually functionallity so my oppinion is that it's better to support all full blocks, all liquids/fluids and tile entities as many as possible.

**Comment by SandGrainOne** [comment]
BuildCraft does not support carpenter's Block. Carpenter's Block has special support for the BuildCraft Builder.

**Comment by Chaos234** [comment]
Over the API?

**Comment by laz2727** [comment]
Except BR blocks *are* TEs.

**Comment by asiekierka** [comment]
@Chaos234 - we have added explicit support to the Builder for quite a lot of mods, see http://mod-buildcraft.com/pages/faq.html - we have to test each and every mod to make sure it cannot cause dupe bugs when used with the Builder, as well as write special requirements/rotation handling code,

**Comment by Chaos234** [comment]
Thanks for your replay. I'll look at the side :).
