### ISSUE TITLE
Graphical Glitch on Assembly Table when using Texture Packs

### ISSUE THREAD

**Issue by Megistus** [BuildCraft/BuildCraft#2849]
So, I have been working on a texture pack and have been updating to BC7. When I got to the assembly table, I found that it can only display a texture that is the size of 64x (or at a 16x resolution). When increasing the size of the image to 256x (or 64x resolution), the image does not display properly. 

Included are screen shots of both resolutions so you may see. Top is 16x resolution, bottom is 64x resolution. I only know for certain that this is the case with the Assembly Table, and have not checked for certain if this issue is with all images for the models.

![assemblytable16x](https://cloud.githubusercontent.com/assets/6314023/8396815/d3761800-1d7b-11e5-9f41-11bd87ccf504.jpg)

![assemblytable64x](https://cloud.githubusercontent.com/assets/6314023/8396816/dbf109f4-1d7b-11e5-979f-bf1e393deb6d.jpg)

**Comment by asiekierka** [comment]
This texture is awesome! However, I do know that our block icon rendering is a massive hack.

**Comment by Megistus** [comment]
Thanks for the compliment ... it is for Glimmar's Steampunk. I have been working on the mod textures for him, Buildcraft included. Just look for Glimmar in curse forge, and you can see some of the work I have done. 

Thanks for getting this fixed. It is greatly appreciated!
