### ISSUE TITLE
[Mod Interaction] IC2 UU-Matter duplication with BC pipe

### ISSUE THREAD

**Issue by 3TUSK** [BuildCraft/BuildCraft#2851]
I suspect that it is at IC2 end, but I can't be 100% sure. Then I reported here first.
Environment: Forge 10.13.3.1355, Buildcraft 7.0.12, BC Compat 7.0.8, IC2 2.2.739
Steps:
1.Put 1000mb liquid uu-matter into an ic2 replicator.
2.Use wooden fluid pipe or emerald fluid pipe to extract them.
3.Wait for a while.
The result is shown below, compared to Thermal Dynamic and Mekanism:
![2015-06-29_19 07 03](https://cloud.githubusercontent.com/assets/9113033/8406815/cf1e2ce4-1e92-11e5-8c99-93a1ceac784d.png)
While other ic2 machines seem to not have the same issue:
![2015-06-29_19 07 11](https://cloud.githubusercontent.com/assets/9113033/8406846/2ae3b9f4-1e93-11e5-9b06-483fadcdf6a6.png)

Thanks for your time.

**Comment by AEnterprise** [comment]
what version of IC2 is this?

**Comment by 3TUSK** [comment]
[The latest one] (http://ic2.player.to:8080/job/IC2_experimental/739/)

**Comment by asiekierka** [comment]
IC2 bug.
