### ISSUE TITLE
Diamond Fluid Pipes Don't Sort into Unfiltered Slots

### ISSUE THREAD

**Issue by larrythemodder** [BuildCraft/BuildCraft#2852]
According to most of what I've read about diamond pipes, any items that don't match a specific filter are supposed to go through an empty one. I made a pipe system that sorted several liquids into several colors and filled the empty ones with bread, leaving one open filter for extra liquids to pass through. Instead of going into the unsorted filter, however, the liquid just remained in the diamond pipe. This is very inconvenient. If I'm doing something wrong, sorry for the report, but this seems like an issue.

**Comment by asiekierka** [comment]
Fixed in 7.0.13

**Comment by larrythemodder** [comment]
That was fast! Thanks for taking care of it so quickly.
