### ISSUE TITLE
IRequestProvider rewrite

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildCraft#2853]
The logic for IRequestProvider should be moved in the following manner:

* IRequestProvider is rewritten to only have two functions: List<ItemStack> getNeededItems() and ItemStack offerItem(ItemStack item).
* The logic for taking and keeping track of StackRequests is moved to a separate Registry class, maintained by the robotics code - that way, we hide the implementation from the implementer.

This is a breaking change but nothing uses the API at the moment (is it even possible to?) so I don't care.

**Comment by hea3ven** [comment]
@asiekierka what do you think of https://github.com/hea3ven/BuildCraft/blob/fcce9cd6013ec63c4a3fc479b1931950b1c80c5c/api/buildcraft/api/robots/IRequestProvider.java as the api, having no continuity between two calls to getNeededItems() overcomplicates a lot the StackRequests registry implementation.

**Comment by asiekierka** [comment]
Is the amount of request slots expected to be constant or not? Either way, I like this API. Just document nuances like that, if you could.

**Comment by hea3ven** [comment]
It shouldn't be hard to make it be a dynamic amount of slots if you think there's a use case.
