### ISSUE TITLE
Laser Power loss

### ISSUE THREAD

**Issue by unknownEnemy1345** [BuildCraft/BuildCraft#2854]
I noticed that Lasers(or my assembly table) seem to loose a lot(25%) of power, i have 4 lasers supplied with 80RF/t, but my assembly table just gets ~60 RF per tick which is quite a big loss of power

The setup consists of 2 combustion engines(running on forestry ethanol->40 RF per engine) connected to 4 lasers directly above the assembly table
![2015-06-30_21 44 05](https://cloud.githubusercontent.com/assets/13124041/8440242/45b1ca44-1f71-11e5-9ff9-72cac44150cb.png)

**Comment by Fuujin2Raijin** [comment]
lol what you say and what's in the picture are different you said for lasers there are actually 5 and for generators you said 2 when there is 3 be sure to know this before posting XD

**Comment by RagaRBM** [comment]
Apply more Engines.

**Comment by asiekierka** [comment]
BuildCraft does not lose energy unless power loss is enabled in your pack. Also, you want to watch out for power loops - they're a dangerous power.
