### ISSUE TITLE
Pipe Sealant can't be crafted by slimeball

### ISSUE THREAD

**Issue by sfchipan** [BuildCraft/BuildCraft#2856]
v7.0.13

**Comment by RagaRBM** [comment]
Have you turned on the config?

**Comment by sfchipan** [comment]
No. I didn't know it needs config. Now it works.
Btw, what's the recipe of List now? I can't see it with latest NEI.
Thanks.

**Comment by RagaRBM** [comment]
https://docs.google.com/document/d/1VfEx2Pd3ttRso2bnO1I7y2QkHMVwqQnKVDT_N8tZez8/pub
