### ISSUE TITLE
blueprint/builder not respecting rotate option with creative only

### ISSUE THREAD

**Issue by KyeDuo** [BuildCraft/BuildCraft#2857]
like the title says.
the blueprint/builder is not respecting the rotate option if the blueprint is creative only. it will respect the option if the blueprint is survival.
Tested in a survival world, have not tested in a creative world.
it will still build, it just won't respect that setting.
BC 7.0.13
forge .1388
and about another 100 mods...

**Comment by mainframecn** [comment]
I'm experiencing the same issue.
BC 7.0.16
BC Compat 7.0.9
Forge 10.13.4.1448

**Comment by asiekierka** [comment]
Could not reproduce on 7.1.3.
