### ISSUE TITLE
Paint Brushes still open GUIs when painting blocks

### ISSUE THREAD

**Issue by Vexatos** [BuildCraft/BuildCraft#2858]
Tested with a Computronics Tape Drive. When I right click a paint brush on the block, it properly changes colour, but the GUI still opens. I think it should not open the GUI when the paint brush successfully recoloured the block.
Mind that I am returning `false` from `recolourBlock` to make the paint brush not take damage. It shouldn't open the GUI anyway.

**Comment by asiekierka** [comment]
The paintbrush is supposed to take damage. If you're returning false, it's your own fault - the API expects you to return true if the paintbrush is doing anything.

**Comment by Vexatos** [comment]
There are multiple mods doing it this way, see for instance OpenComputers.

**Comment by asiekierka** [comment]
That's their fault then. A successful colour change should ALWAYS return
true.
