### ISSUE TITLE
Striped Robot Issues

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#2859]
1. When setting striped robot with a point map location, the robot seem to place blocks 1 block infront of the block selected as well as the block orginally selected. 
2. There needs to be a way to stop striped robots putting skulls/hemets on another robots head
3. Striped pipes and stipes robots cant place down mob heads

http://imgur.com/a/VFszD

**Comment by hea3ven** [comment]
> 1. When setting striped robot with a point map location, the robot seem to place blocks 1 block infront of the block selected as well as the block orginally selected.

Fixed with #2919

> 2. There needs to be a way to stop striped robots putting skulls/hemets on another robots head

Didn't knew this was possible, it is awesome. Unfortunately, there's no easy way to limit this.

> 3. Striped pipes and stipes robots cant place down mob heads

Depend's whether @asiekierka wants to allow stripes pipes to place mob heads.

**Comment by RagaRBM** [comment]
I'll report it here instead of making a new issue. 
-When assigned to shear Sheeps in a working area, after a single successful shearing, Stripes Bot would drop the Shear on the ground and get a new one.

**Comment by asiekierka** [comment]
Striped robots are going out.
