### ISSUE TITLE
Blueprint library crashes when there is a file named just "bpt" or any other supported extension

### ISSUE THREAD

**Issue by hea3ven** [BuildCraft/BuildCraft#2860]
http://www.mod-buildcraft.com/forums/showthread.php?tid=1684&pid=16541#pid16541

**Comment by n00b7** [comment]
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

UCHIE BuildCraft|Builders{7.0.13} [BC Builders] (buildcraft-7.0.13.jar)

**Comment by n00b7** [comment]
bpt? BluePrinT
