### ISSUE TITLE
TOO Bad Compitability with MineFactory Reloaded

### ISSUE THREAD

**Issue by ishitatsuyuki** [BuildCraft/BuildCraft#2861]
Yup, BuildCraft 7.0.13.
The pipes doesn't connect to some of the machines in MineFactory Reloaded.
A famous mod (by CoFH :) called Thermal Expansion does it very well.
Comparasion:
![2015-07-03_17 10 15](https://cloud.githubusercontent.com/assets/12389383/8495310/985c29e6-21a7-11e5-8d1c-a003047ed9be.png)
![2015-07-03_17 11 14](https://cloud.githubusercontent.com/assets/12389383/8495313/9867d282-21a7-11e5-89ac-2f5845e151f7.png)
![2015-07-03_17 11 59](https://cloud.githubusercontent.com/assets/12389383/8495311/9866e160-21a7-11e5-9203-ef7bcecd92a5.png)
![2015-07-03_17 12 57](https://cloud.githubusercontent.com/assets/12389383/8495312/98674312-21a7-11e5-90c8-d0ad8262327f.png)
Liquid router doesn't connect but works well though.

**Comment by asiekierka** [comment]
Thermal Expansion and MFR's developers work together (they're part of one team), so that is no surprise. I'll look into it.

**Comment by RagaRBM** [comment]
Do you have BCCompat?

**Comment by ishitatsuyuki** [comment]
Of course.

**Comment by KingLemming** [comment]
@asiekierka - we didn't collude on this one in any way. This would seem to be on your end with how BC pipes detect valid tiles.

**Comment by asiekierka** [comment]
@KingLemming - Except I am?

For fluids, see https://github.com/BuildCraft/BuildCraft/blob/6.5.x/common/buildcraft/transport/PipeTransportFluids.java#L216-L218

For power, see https://github.com/BuildCraft/BuildCraft/blob/6.5.x/common/buildcraft/transport/PipeTransportPower.java#L116-L123

**Comment by asiekierka** [comment]
@ishitatsuyuki , @KingLemming  - could not reproduce.

![](http://i.imgur.com/AnPqfPr.png)

**Comment by ishitatsuyuki** [comment]
I got CoFHTweaks (or optifine when previous reproduce) but I don't think they do something bad.
And Thermal Expansion of course.

**Comment by Casper-O** [comment]
skyboy/MineFactoryReloaded/issues/474

**Comment by Casper-O** [comment]
Seems like im not the only one that have this issue, reported it over at MFR but was told on IRC that it was a BC issue.

skyboy/MineFactoryReloaded/issues/474

**Comment by AnrDaemon** [comment]
After investigation, it seems that the culprit is BCCompat. Removing it makes everything work as intended.

**Comment by Inari-Whitebear** [comment]
Yeah, tested with:
MC 1.7.10
forge-1.7.10-10.13.4.1448
buildcraft-7.0.17
buildcraft-compat-7.0.9
CoFHCore-[1.7.10]3.0.3-303
MineFactoryReloaded-[1.7.10]2.8.0-104
magicalcrops-4.0.0Beta5 and MFR Compat 1.2.1
Optfine 1.7.10 HD U C1

Slaughterhouse and Golden Kinesis Pipe not connecting
disabled optifine, magical crops, mfr compat, still not connecting
disabled bc compat, connects
enabled bc compat, doesn't connect

skyboy said something about the bc compat breaking default connection override to RF-providers, which apparently MFR uses?

**Comment by Casper-O** [comment]
Interesting, on the phone right now so it's a little difficult to make a issue for me over at BCCompat - will look tonight if other made the report with reference to this
