### ISSUE TITLE
[7.0.13]Lost Waila Compitability

### ISSUE THREAD

**Issue by ishitatsuyuki** [BuildCraft/BuildCraft#2862]
Comparing from: 7.0.11
Comparing to: 7.0.13
Screenshot:
![2015-07-03_17 13 18](https://cloud.githubusercontent.com/assets/12389383/8495355/f481beca-21a7-11e5-81cf-ee056ea1e40e.png)

**Comment by larrythemodder** [comment]
I've noticed this as well. It hasn't affected my experience at all, but you're not the only one seeing this.

**Comment by Casper-O** [comment]
Can confirm this is still a problem in 7.0.17

maybe this is why ?

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289765-waila-1-5-7-for-1-7-10-1-6-0-for-1-8-1?comment=948
