### ISSUE TITLE
[7.0.13]Extraction Fluid pipe with IC2EXP Machine

### ISSUE THREAD

**Issue by Antecer** [BuildCraft/BuildCraft#2863]
![qq 20150703221016](https://cloud.githubusercontent.com/assets/8684916/8500739/8a93b322-21d1-11e5-87b3-5d5f5f3d275b.png)
![qq 20150703221525](https://cloud.githubusercontent.com/assets/8684916/8500740/8b3ae0a2-21d1-11e5-962d-29fada7e7eb8.png)
Fluid in these Machine Will not reduce！

**Comment by asiekierka** [comment]
IC2 bug
