### ISSUE TITLE
[Suggestion] Filler/Architect idea

### ISSUE THREAD

**Issue by AgentK9** [BuildCraft/BuildCraft#2864]
Add a new tier/mode to the Architect/Filler that, on Shift-Right-click w/ wrench will generate a ghost cube starting at 3x3 blocks but can go up to 64x64. Recipe would possibly include Zone planner. It would then operate as it would but without markers. It would still need markers, but only for rectangular prisms.

related idea: Same as above but instead of Shift-Right-Clicking with a wrench on the machine, part of the GUI would include xyz for the rectangular prism. This would alleviate the need for markers. Again, this would not fully replace the Filler/Architect, but add another tier/mode.

**Comment by AEnterprise** [comment]
seeing as there has been no discussion on this for almost a year i think this can be closed

**Comment by AlexIIL** [comment]
Yeah this probably isn't happening.
