### ISSUE TITLE
Server crash....

### ISSUE THREAD

**Issue by fragstealern** [BuildCraft/BuildCraft#2866]
Hi, I have created a new Resonant Rise 3 server.

We have two diffrent physical servers. On one of them the RR3 server works perfectly without crashing. But on the second server ( our new physical server, with better hardware) the server seems to crash whenever we got close to an village. 

Things I've tried:
*Reinstall Java 1.7
*Move the RR3 server between the physical servers, so they have the exact same settings.
*Reinstall RR3

Here is the crash-report: http://pastebin.com/xVDyCi33

**Comment by AgentK9** [comment]
What version of BC?

**Comment by AgentK9** [comment]
also, try w/o cauldron

**Comment by AEnterprise** [comment]
this is a logistics pipes crash

**Comment by fragstealern** [comment]
Buildcraft 7.0.12
Will try without Cauldron now
Are you sure? Because when i enter the game on the server that works, the block that causes it is a "Stone Kinesis pipe" from BC transport

**Comment by AEnterprise** [comment]
hmm, the village ringed a bell, afther looking intro the crash report it's a mix of things: you have BCA installed, that does some trickery to place pipes in the world as part of a village structure, that causes LP to crash when it's trying to do a check on it, not sure how i could fix it from my end, my sugestion is asking the LP devs to do a null check to prevent this

**Comment by fragstealern** [comment]
The server seems to work w/o cauldron.. But I kinda need some plugins :P

**Comment by AEnterprise** [comment]
go to the village to make sure it all generated, then you can reload the world with cauldron and it should work i think

**Comment by fragstealern** [comment]
Thats already done, but therese alot of vilalges.. And almost everyone of them contains the "stone Kinesis Pipe"

**Comment by fragstealern** [comment]
Solved by changing /config/forge.cfg to true

# Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=true

**Comment by AEnterprise** [comment]
that will indeed solve it indeed, not an very good solution but it'll at least prevent crashes
