### ISSUE TITLE
ERROR in Buildcraft 7.0.13 ?

### ISSUE THREAD

**Issue by JUERG660** [BuildCraft/BuildCraft#2867]
Hello,

i installed the newest Buildcraft Version 7.0.13.  InGame when i place Pipes they will lost her Caption.
For Example a Cobblestone Transport Pipe in my Inventory ist named correct. But when it is placed the Name is: tile.pipeBlock.name
Look at the Picture. Also the textures of the Pipes and the AutoWorkbench wrong. I cant change it ?

Jürgen
![error pipes](https://cloud.githubusercontent.com/assets/13183835/8510723/8d69f62a-22f7-11e5-81fb-07d563f7708a.jpg)

**Comment by Kubuxu** [comment]
This is not a bug, this is how BC handles pipes and everything. They are one and the same block in world. WAILA just reads what it shouldn't.

**Comment by JUERG660** [comment]
Hey Kubuxu, thanks for you reply.
When i install the 7.0.12 Version it is named right ?
What means WAILA ? My English is not so good sry

**Comment by psxlover** [comment]
WAILA is the mod you are using that is displaying the box with information of what you are looking at, in the top of your screen.

**Comment by asiekierka** [comment]
There's a different issue already opened for this.
