### ISSUE TITLE
Architect Tables' Issue

### ISSUE THREAD

**Issue by sfchipan** [BuildCraft/BuildCraft#2868]
If a Architect Table is connecting a Construction Mark or another Architect Table using Construction Mark, the blueprint doesn't work for builder.
(https://www.youtube.com/watch?v=yharxcu4Ql8   about 9:20)
version 7.0.13
![2015-07-05_16 16 37](https://cloud.githubusercontent.com/assets/4555814/8510952/d8133ea2-2333-11e5-937a-4111a45f6d44.png)

**Comment by 3TUSK** [comment]
Get the same issue under Buildcraft 7.0.13 with Forge 10.13.4.1470, also BCCompat installed.

Define multiple areas, then use the middle one to make a blueprint:
![2015-07-11_14 38 31](https://cloud.githubusercontent.com/assets/9113033/8632776/09015498-27dc-11e5-91e8-b5dd4172d335.png)
Then there is *nothing* required in a builder:
![2015-07-11_14 38 43](https://cloud.githubusercontent.com/assets/9113033/8632778/1b8fdbac-27dc-11e5-8fec-5d358634bf51.png)

**Comment by asiekierka** [comment]
Fixed in late BC 7.0.
