### ISSUE TITLE
[suggestion] building turtles for computercraft 1.7.4+

### ISSUE THREAD

**Issue by n00b7** [BuildCraft/BuildCraft#2870]
i thing a building turtle / advanced building turtle 
would be cool!

crafting recipie: none none none
                        none  turtle   builder
                        none none none

functions:
blueprint.load([slot]) loads the blueprint in the given slot
blueprint.build() builds the blueprint if the matirials are in the builder(will pause when waiting for matierials)

isBlueprint() returns true if the loaded blueprint is a blueprint(returns false if it is a template)
isTemplate() returns true if the loaded blueprint is a template(returns false if it is a blueprint)
blueprint.hasMatierieals() returns true if the turtle has matierieals for building the loaded blueprint
isEnoughFuel() (returns if it has enough fuel to build the blueprint)

how it works:

consumes 2 fuel per block placed
blueprint.load() uses the selected slot by default

computers may use this as a peripheral when conected directly or by modems and cables

changes when using with computers
isEnoughFuel() will be isEnoughRF()
blueprint.load() will not do anything

**Comment by AEnterprise** [comment]
there is already the robot builder

**Comment by n00b7** [comment]
ok

**Comment by asiekierka** [comment]
Builders without RF? Not like that, oh no... Might as well play creative.
