### ISSUE TITLE
Oil Refinery with Galacticraft

### ISSUE THREAD

**Issue by r0rs** [BuildCraft/BuildCraft#2871]
Running only Buildcraft 7.0.13 and Buildcraft compat oil refines like it should. Adding Galacticraft causes the refinery to only be able to refine Galacticraft's oil and not Buildcraft's. Buildcraft oil will sit in the refinery and nothing happens.

**Comment by r0rs** [comment]
Edit: I realize this may be a Galacticraft issue but it did work in Buildcraft 6.4.x

**Comment by Thog** [comment]
Caused by the move of oil blocks declarations (https://github.com/micdoodle8/Galacticraft/blob/53a03c4114e1694bd8d1b198a6d365c6fdbc0cdd/src/main/java/micdoodle8/mods/galacticraft/core/event/EventHandlerGC.java#L284-L312)

**Comment by Thog** [comment]
Are you talking of the BC refinery or the Galacticraft one?

I don't get any problems with both...

![Image 1](http://i.imgur.com/ftIZCyg.jpg "IMG 1")

![Image 2](http://i.imgur.com/e3Q42G7.png "IMG 2")

**Comment by r0rs** [comment]
The BC refinery. It works if I feed it GC oil. 

As soon as I replace the oil source with BC oil(along with the pipes and refinery to clear it) it stops. The refinery takes in a bit of power until it is full on energy then the side pieces stop moving and it fills up with oil never making fuel.

**Comment by steveowashere** [comment]
Here are screenshots of the issue: 

With BC Oil: 

![2015-07-06_07 56 53](https://cloud.githubusercontent.com/assets/13194819/8516497/28482780-23b5-11e5-981d-ee28fb47d354.png)

![2015-07-06_07 57 31](https://cloud.githubusercontent.com/assets/13194819/8516498/2c1a2c96-23b5-11e5-9a47-f0b86bb91dbd.png)

![2015-07-06_07 57 42](https://cloud.githubusercontent.com/assets/13194819/8516504/3bbbd92e-23b5-11e5-9ac1-2ec20195b54d.png)


With GC Oil: 

![2015-07-06_07 58 34](https://cloud.githubusercontent.com/assets/13194819/8516506/3eaa3950-23b5-11e5-9a37-16434feb73c0.png)


![2015-07-06_07 58 54](https://cloud.githubusercontent.com/assets/13194819/8516508/417c83b8-23b5-11e5-8466-85708bcf3dfb.png)

**Comment by n00b7** [comment]
try supplying it with a bc creative/stirling/combustion engine (i see the creative energy cell under the refinery)

**Comment by Starhero** [comment]
Found my issue, watching. +1 for those experiencing. Currently trying to find a work around as in game play all I have is GC oil, my base runs on it, because of a misconfig of the world gen settings due to human error, but i digress...
