### ISSUE TITLE
Chipset recipes missing from NEI

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [BuildCraft/BuildCraft#2873]
I can't get any recipes from NEI for all the different chipsets. Using latest curseforge versioN!

**Comment by AEnterprise** [comment]
you need to install buildcraft compat for that

**Comment by Unrepentant-Atheist** [comment]
Say what? http://minecraft.curseforge.com/search?search=buildcraft don't see any compat.

**Comment by AgentK9** [comment]
It is not nessecarily on CF. ALWAYS check the website: mod-buildcraft.com

**Comment by asiekierka** [comment]
Yup. CurseForge is all unofficial mirrors.

**Comment by AEnterprise** [comment]
latest BC is on curseforge i'm putting it there when new versions are released (might be a delay between the release and the CF upload) BCC is not on thare at the moment
