### ISSUE TITLE
Facades using chisel blocks don't load immediately after leaving the chunk

### ISSUE THREAD

**Issue by SeriousCreeper** [BuildCraft/BuildCraft#2874]
Buildcraft version: 7.0.13 

I'm using facades with a chiseled oak plank. They show up fine until you leave the area and come back. It shows the pink/black no texture until you get close and let it load for a couple of seconds.

http://i.imgur.com/4MU0uWN.png 

They eventually turn into the proper texture after a couple of seconds. 
Seems fine with vanilla blocks.

**Comment by asiekierka** [comment]
A copy of the world/region and modpack would be nice, as this requires further inspection.

**Comment by SeriousCreeper** [comment]
Hm i just did some more testing, it seems like it actually only happens with logistics pipes, not with the buildcraft ones, and also only with certain blocks (wooden crate block was broken, copper block was fine). 
http://i.imgur.com/37x0BBO.png
(All the blocks on the left were ok, wooden ones on the middle and right pipe were broken, until i moved close enough)

Pack was SeriousPack 1.6.4 (http://forum.feed-the-beast.com/threads/1-7-10-seriouspack-magic-tech-and-adventure.53572/)
Test level download: https://dl.dropboxusercontent.com/u/1658875/delete/buildcraft_bug.zip

I'll resubmit it over at the logistics pipes github page (unless there is someone i can @ here)

Sorry about the confusion!

**Comment by asiekierka** [comment]
It's probably a LogiPipes issue, then. They do some crazy hooks into BC code to make it all work.
