### ISSUE TITLE
Chute extract items

### ISSUE THREAD

**Issue by sfchipan** [BuildCraft/BuildCraft#2875]
Hello. I see a  changelog in 6.3.0, "Chutes can now be powered with Engines, much like wooden pipes, to extract items; however, they have a 10 RF/t cap". But I set them like followed images:
![2015-07-08_21 19 36](https://cloud.githubusercontent.com/assets/4555814/8571389/0958c37e-25b9-11e5-87de-974868521eea.png)
I don't know if it's right to set like this. It can't extract items in top chest. The version in images is 6.3.0, and in 7.0.13 it also doesn't work.

By the way, I found a texture in bc's file. Is this update version of chute exist in 7.0.13 ?
![hopper_gui_tier2](https://cloud.githubusercontent.com/assets/4555814/8571404/1f4ffb48-25b9-11e5-9b13-b81b0dd7fc42.png)

Thanks.

**Comment by sfchipan** [comment]
Ok...I have figured out how to use chute with engine. When using engine the chute can transport items in itself to pipe below it. Sorry for unnecessary asking.

**Comment by asiekierka** [comment]
They should probably be able to extract above too... Hmm.

**Comment by Kubuxu** [comment]
AFAIK you added pushing from chutes to pipes.

**Comment by asiekierka** [comment]
Chutes are going to be changed.
