### ISSUE TITLE
BuildCraft 7.0.13 startup error

### ISSUE THREAD

**Issue by Shaggy84675** [BuildCraft/BuildCraft#2879]
Hello. When I run my modpack I've got this BuildCraft error.
Here's crash log.

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 10.7.15 14:48
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft
	at minewiz.buildcraftutils.mod.plugin.pipes.Pipes.Build(Pipes.java:94)
	at minewiz.buildcraftutils.mod.plugin.pipes.Pipes.registerPipes(Pipes.java:72)
	at minewiz.buildcraftutils.mod.plugin.pipes.Pipes.init(Pipes.java:66)
	at minewiz.buildcraftutils.mod.plugin.pipes.PluginPipes.preInit(PluginPipes.java:9)
	at minewiz.buildcraftutils.mod.PluginManager.preInit(PluginManager.java:53)
	at minewiz.buildcraftutils.mod.PluginManager.preInit(PluginManager.java:46)
	at minewiz.buildcraftutils.BuildcraftUtilities.preInit(BuildcraftUtilities.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more
Caused by: java.lang.ClassNotFoundException: buildcraft.core.CreativeTabBuildCraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1044716896 bytes (996 MB) / 1716518912 bytes (1637 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 72 mods loaded, 72 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
	UCH	Forge{10.13.4.1448} [Minecraft Forge] (modpack.jar) 
	UCH	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCH	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCH	OpenComputers|Core{1.5.13.28} [OpenComputers (Core)] (minecraft.jar) 
	UCH	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCH	asielib{0.4.2} [asielib] (AsieLib-1.7.10-0.4.2.jar) 
	UCH	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCH	bdlib{1.9.0.94} [BD Lib] (bdlib-1.9.0.94-mc1.7.10.jar) 
	UCH	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1364-universal.jar) 
	UCH	BuildCraft|Core{7.0.13} [BuildCraft] (buildcraft-7.0.13.jar) 
	UCH	Forestry{3.6.2.19} [Forestry for Minecraft] (forestry_1.7.10-3.6.2.19.jar) 
	UCH	BinnieCore{2.0-pre14} [Binnie Core] (binnie-mods-2.0-pre14.jar) 
	UCH	Botany{2.0-pre14} [Botany] (binnie-mods-2.0-pre14.jar) 
	UCH	ExtraBees{2.0-pre14} [Extra Bees] (binnie-mods-2.0-pre14.jar) 
	UCH	ExtraTrees{2.0-pre14} [Extra Trees] (binnie-mods-2.0-pre14.jar) 
	UCH	Genetics{2.0-pre14} [Genetics] (binnie-mods-2.0-pre14.jar) 
	UCH	Botania{r1.7-201} [Botania] (Botania r1.7-201.jar) 
	UCH	BuildCraft|Transport{7.0.13} [BC Transport] (buildcraft-7.0.13.jar) 
	UCE	buildcraftutils{1.2.0} [BuildCraft Utilities] (BuildCraft Utilities-1.7.10-1.2.0.jar) 
	UCH	BuildCraft|Silicon{7.0.13} [BC Silicon] (buildcraft-7.0.13.jar) 
	UCH	BuildCraft|Builders{7.0.13} [BC Builders] (buildcraft-7.0.13.jar) 
	UCH	BuildCraft|Robotics{7.0.13} [BC Robotics] (buildcraft-7.0.13.jar) 
	UCH	BuildCraft|Energy{7.0.13} [BC Energy] (buildcraft-7.0.13.jar) 
	UCH	BuildCraft|Factory{7.0.13} [BC Factory] (buildcraft-7.0.13.jar) 
	UCH	BuildCraft|Compat{7.0.8} [BuildCraft Compat] (buildcraft-compat-7.0.8.jar) 
	UCH	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	MrTJPCoreMod{1.1.0.27} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.27-universal.jar) 
	UCH	ProjRed|Core{4.7.0pre5.89} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre5.89-Base.jar) 
	UCH	ProjRed|Transmission{4.7.0pre5.89} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre5.89-Integration.jar) 
	UCH	OpenComputers{1.5.13.28} [OpenComputers] (OpenComputers-MC1.7.10-1.5.13.28-universal.jar) 
	UCH	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10(1).jar) 
	UCH	Mekanism{8.1.5} [Mekanism] (Mekanism-1.7.10-8.1.5.246.jar) 
	UCH	computronics{1.5.5} [Computronics] (Computronics-1.7.10-1.5.5.jar) 
	UCH	endercore{1.7.10-0.0.1.12_alpha} [EnderCore] (EnderCore-1.7.10-0.0.1.12_alpha.jar) 
	UCH	extracells{2.2.73} [Extra Cells 2] (ExtraCells-1.7.10-2.2.73b129.jar) 
	UCH	gendustry{1.5.2.107} [GenDustry] (gendustry-1.5.2.107-mc1.7.10.jar) 
	UCH	LogisticsPipes{0.9.1.15} [Logistics Pipes] (logisticspipes-0.9.1.15.jar) 
	UCH	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCH	masssound{1.1.1} [MassSound] (MassSound-1.7.10-1.1.1.jar) 
	UCH	MekanismGenerators{8.1.5} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.5.246.jar) 
	UCH	MekanismTools{8.1.5} [MekanismTools] (MekanismTools-1.7.10-8.1.5.246.jar) 
	UCH	NEIAddons{1.12.10.33} [NEI Addons] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCH	NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCH	NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCH	NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCH	NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCH	NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCH	neiintegration{1.0.11} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.11.jar) 
	UCH	openglasses{1.0.46} [OC Glasses] (OpenGlasses-1.0.46.jar) 
	UCH	openprinter{0.1.0.102} [OpenPrinter] (OpenPrinter-MC1.7.10-OC1.4-0.1.0.102.jar) 
	UCH	ProjectBlue{1.1.4} [Project Blue] (ProjectBlue-1.1.4-mc1.7.10.jar) 
	UCH	ProjRed|Transportation{4.7.0pre5.89} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre5.89-Mechanical.jar) 
	UCH	ProjRed|Exploration{4.7.0pre5.89} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre5.89-World.jar) 
	UCH	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCH	ProjRed|Compatibility{4.7.0pre5.89} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre5.89-Compat.jar) 
	UCH	ProjRed|Integration{4.7.0pre5.89} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre5.89-Integration.jar) 
	UCH	ProjRed|Fabrication{4.7.0pre5.89} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre5.89-Fabrication.jar) 
	UCH	ProjRed|Illumination{4.7.0pre5.89} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre5.89-Lighting.jar) 
	UCH	ProjRed|Expansion{4.7.0pre5.89} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre5.89-Mechanical.jar) 
	UCH	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UCH	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) 
	UCH	wailaplugins{MC1.7.10-0.1.0-16} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.1.0-16.jar) 
	UCH	wawla{1.3.1} [What Are We Looking At] (Wawla-1.3.1-1.7.10.jar) 
	UCH	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	ForgeRelocation{0.0.1.3} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.3-universal.jar) 
	UCH	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.3-universal.jar) 
	UCH	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCH	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.4.13292 Compatibility Profile Context 14.502.1014.1001' Renderer: 'AMD Radeon HD 5670'
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	List of loaded APIs: 
		* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-10.jar
		* asielibAPI (1.1) from AsieLib-1.7.10-0.4.2.jar
		* asielibAPI|chat (1.0) from AsieLib-1.7.10-0.4.2.jar
		* asielibAPI|tile (1.0) from AsieLib-1.7.10-0.4.2.jar
		* asielibAPI|tool (1.1) from AsieLib-1.7.10-0.4.2.jar
		* Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
		* BiomesOPlentyAPI (1.0.0) from BiomesOPlenty-1.7.10-2.1.0.1364-universal.jar
		* BotaniaAPI (56) from Botania r1.7-201.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.0.13.jar
		* BuildCraftAPI|blueprints (1.3) from buildcraft-7.0.13.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.0.13.jar
		* BuildCraftAPI|core (1.5) from buildcraft-7.0.13.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.0.13.jar
		* BuildCraftAPI|events (1.0) from buildcraft-7.0.13.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.0.13.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.0.13.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.0.13.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.0.13.jar
		* BuildCraftAPI|items (1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.0.13.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.0.13.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.0.13.jar
		* BuildCraftAPI|robotics (2.1) from buildcraft-7.0.13.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.0.13.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.0.13.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.0.13.jar
		* BuildCraftAPI|tools (1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.0.13.jar
		* CoFHAPI (1.7.10R1.0.3) from EnderCore-1.7.10-0.0.1.12_alpha.jar
		* CoFHAPI|energy (1.7.10R1.0.1) from Railcraft_1.7.10-9.6.1.0.jar
		* CoFHAPI|inventory (1.7.10R1.0.1) from buildcraft-compat-7.0.8.jar
		* CoFHAPI|transport (1.7.10R1.0.1) from buildcraft-compat-7.0.8.jar
		* computronicsAPI (1.3) from Computronics-1.7.10-1.5.5.jar
		* computronicsAPI|chat (1.3) from Computronics-1.7.10-1.5.5.jar
		* computronicsAPI|multiperipheral (1.1) from Computronics-1.7.10-1.5.5.jar
		* computronicsAPI|tape (1.0) from Computronics-1.7.10-1.5.5.jar
		* ForestryAPI|apiculture (3.5.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|arboriculture (2.3.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|circuits (2.0.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|core (3.2.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|farming (1.1.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|genetics (3.3.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|lepidopterology (1.1) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|recipes (3.1.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|world (1.1.0) from forestry_1.7.10-3.6.2.19.jar
		* ForgeRelocation|API (0.0.1.3) from ForgeRelocation-1.7.10-0.0.1.3-universal.jar
		* gendustryAPI (2.1.0) from gendustry-1.5.2.107-mc1.7.10.jar
		* IC2API (1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* MekanismAPI|core (8.0.0) from Mekanism-1.7.10-8.1.5.246.jar
		* MekanismAPI|energy (8.0.0) from Mekanism-1.7.10-8.1.5.246.jar
		* MekanismAPI|gas (8.0.0) from Mekanism-1.7.10-8.1.5.246.jar
		* MekanismAPI|infuse (8.0.0) from Mekanism-1.7.10-8.1.5.246.jar
		* MekanismAPI|laser (8.0.0) from Mekanism-1.7.10-8.1.5.246.jar
		* MekanismAPI|reactor (8.0.0) from Mekanism-1.7.10-8.1.5.246.jar
		* MekanismAPI|recipe (8.0.0) from Mekanism-1.7.10-8.1.5.246.jar
		* MekanismAPI|transmitter (8.0.0) from Mekanism-1.7.10-8.1.5.246.jar
		* MekanismAPI|util (8.0.0) from Mekanism-1.7.10-8.1.5.246.jar
		* OpenComputersAPI|Component (5.5.2) from OpenComputers-MC1.7.10-1.5.13.28-universal.jar
		* OpenComputersAPI|Core (5.5.2) from OpenComputers-MC1.7.10-1.5.13.28-universal.jar
		* OpenComputersAPI|Driver (5.5.2) from OpenComputers-MC1.7.10-1.5.13.28-universal.jar
		* OpenComputersAPI|Driver|Item (5.5.2) from OpenComputers-MC1.7.10-1.5.13.28-universal.jar
		* OpenComputersAPI|Event (5.5.2) from OpenComputers-MC1.7.10-1.5.13.28-universal.jar
		* OpenComputersAPI|FileSystem (5.5.2) from OpenComputers-MC1.7.10-1.5.13.28-universal.jar
		* OpenComputersAPI|Internal (5.5.2) from OpenComputers-MC1.7.10-1.5.13.28-universal.jar
		* OpenComputersAPI|Machine (5.5.2) from OpenComputers-MC1.7.10-1.5.13.28-universal.jar
		* OpenComputersAPI|Manual (5.5.2) from OpenComputers-MC1.7.10-1.5.13.28-universal.jar
		* OpenComputersAPI|Network (5.5.2) from OpenComputers-MC1.7.10-1.5.13.28-universal.jar
		* OpenComputersAPI|Prefab (5.5.2) from OpenComputers-MC1.7.10-1.5.13.28-universal.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|carts (1.3.1) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|core (1.3.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|signals (1.3.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|tracks (2.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.6.1.0.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10(1).jar

**Comment by AEnterprise** [comment]
update buildcraft utilities, the version you have installed is not BC7 compatible

**Comment by Shaggy84675** [comment]
Thanks. Where can I found the newest version?

**Comment by AEnterprise** [comment]
don't use it myself but you have it installed so you should know where to download it

**Comment by Shaggy84675** [comment]
Yea. But I found only the version which I have, so It's possible there's not exist newest version.

**Comment by AEnterprise** [comment]
that or the mod author didn't update to BC7 yet, best bet is to contact him about it

**Comment by Shaggy84675** [comment]
Okay. Thanks for help.
