### ISSUE TITLE
Bug with fluid pipe

### ISSUE THREAD

**Issue by Rannonds** [BuildCraft/BuildCraft#2880]
Hello, 
I have update my Buildcraft to 7.0.13 today and i found a bug with fluid : 
The water get blocked in the pipe...
I made a video to explain :
https://www.youtube.com/watch?v=w1lUNLoVpP0

As you can see the water still blocked even i restart the world...
Am i the only person with this bug ?
PS: this bug is with all fluid and all Waterproof Pipes
PS 2: I have other mods and my forge version is 10.13.4.1448
My mods file
![capture](https://cloud.githubusercontent.com/assets/13276319/8623696/2ad57166-2733-11e5-8c66-6c93186d452b.PNG)

**Comment by SandGrainOne** [comment]
Break the pipes and place them back down. That solved it for me. I don't know the cause of the issue.

**Comment by Rannonds** [comment]
It work but this is a temporary solution : 2 minutes later this bug reappear...
