### ISSUE TITLE
Buildcraft Compat crashes server

### ISSUE THREAD

**Issue by SneakyDevil** [BuildCraft/BuildCraft#2881]
Recently updated all my stuff(including buildcraft) on both clientside and serverside of the modpack I'm maintaining. For some reason Clientside has no issues starting up but whenever the Server tries to start up Buildcraft Compat gives a Fatal null error and crashes it out.

Heres the dropbox link to fml-server-latest.log: https://www.dropbox.com/s/qyffro3pwfw5wnd/fml-server-latest.log?dl=0

**Comment by SneakyDevil** [comment]
Deleted forestry and disabled lording of it in config for buildcraft compat. Now I get a infinite stall with mismatched ids.
![error](https://cloud.githubusercontent.com/assets/11374726/8634845/bc583a8e-27d7-11e5-9e49-02301a02ffae.PNG)

**Comment by SneakyDevil** [comment]
java.lang.NullPointerException: remap target is null

**Comment by asiekierka** [comment]
Will be fixed in 7.0.9.

**Comment by SneakyDevil** [comment]
Uhm, I'm still getting a null remap error. Updated buildcraft and compat.

The link below contains the new log file from post update startup.
https://www.dropbox.com/s/qyffro3pwfw5wnd/fml-server-latest.log?dl=0

**Comment by asiekierka** [comment]
Add Forestry, maybe?

**Comment by SneakyDevil** [comment]
Good News: I no longer crash due to null value.
Bad News: I now crash because of Forestry.

Have some logs:
https://www.dropbox.com/s/c0q3y1fjmutqcyp/crash-2015-07-12_14.25.03-server.txt?dl=0
https://www.dropbox.com/s/qyffro3pwfw5wnd/fml-server-latest.log?dl=0

**Comment by AEnterprise** [comment]
you need to update computronics

**Comment by SneakyDevil** [comment]
Okay. That worked. Why did updating computertronics make forestry run so buildcraft compat wouldn't return a null value. I just... I dont even... Thanks. I can finally release this modpack.

**Comment by AEnterprise** [comment]
initial problem was computonics not being updated to latest forestry

when you removed forestry the apiarists pipe was no longer present BUT that pipe also moved from forestry tor BCC recently, BCC tried to remap it's forestry module wasn't loaded, causing that to crash

**Comment by SneakyDevil** [comment]
Ah, so it was just a really weird series of events that coincided with me updating things at the wrong time in the wrong way? Good to know

**Comment by AEnterprise** [comment]
yeah

@asiekierka i sugest adding a check in BCC remapping to make sure the forestry module is loaded to prevent this in the future
