### ISSUE TITLE
Recipe Packager - massive dupe

### ISSUE THREAD

**Issue by linkinkov** [BuildCraft/BuildCraft#2882]
[removed]

**Comment by asiekierka** [comment]
Oh. This is bad. Very bad.

**Comment by linkinkov** [comment]
Thank you for fast answer :3
Wait for new commits

**Comment by SandGrainOne** [comment]
Probably the same error that pops up everytime we create a new machine with ghost slots. :)
Look at SlotPhantom. It is either canAdjust or canTakeStack (or both) that needs to return false.
