### ISSUE TITLE
Bug with fluid pipe again

### ISSUE THREAD

**Issue by Rannonds** [BuildCraft/BuildCraft#2885]
Hello, 
First i would to thanks asiekierka for responding to my last bug : 
https://github.com/BuildCraft/BuildCraft/issues/2880
But i update buildcraft to 7.0.14 today and i have the same bug with fluid pipe : 
This video was made with buildcraft 7.0.14 :
https://www.youtube.com/watch?v=H4Q0--Kjfto
As you can see the bug still here...

**Comment by asiekierka** [comment]
Intended behaviour. Pipes don't store water evenly as that causes fractional calculation bugs, and they don't spill water out because a single pipe segment only stores 250mB.

**Comment by psxlover** [comment]
I believe that his issue is that the liquid does not bounce back.

**Comment by UnknownSoldier777** [comment]
Well, me here on 2023 with the same problem but instead of water it is steam, restart word, change versions, nothing changed lmao.
