### ISSUE TITLE
Move default blueprint directory from config/

### ISSUE THREAD

**Issue by Chaos234** [BuildCraft/BuildCraft#2886]
Hi,

we have changed from FTB Infinity 1.6.2 to 1.7.0 and since that no blue print works any more :(.
I recognized that the machines designe has changed but why are old blue prints not ported?

Conten was some chiseled blocks and carpenter's blocks which where saved successfully at 1.6.2.
Was the change so big?

**Comment by AgentK9** [comment]
try re-making the Blueprints.

**Comment by Chaos234** [comment]
Thats not possible because the structure and the world is always deleted - is there a way to edit the stored data value over NBTExplorer or is there another way to get them working?

I wonder why there is no "Blubrint/Template Converter" Block to prevent such an error ... rly uncool that an update breaks older BPs :(

**Comment by Chaos234** [comment]
Ok, I tested smth. with the blueprint:

I seted up a small area of dirt and saved it in a BP on ftb infinity 1.6.2, then downgraded to 1.5.0 then to 1.6.0 and then to 1.6.2 back. Result was a full broken bp which isn't useable anymore, so it seems that after a version change in BC all BPs are breaking instantly ... not good (my oppinion)

**Comment by asiekierka** [comment]
That's weird. This has never happened for me.

2015-07-12 22:29 GMT+02:00 Chaos234 <notifications@github.com>:

**Comment by Chaos234** [comment]
Then we are two how are weird.

I looked in the Items NBT-Data and found only a HEX-Value but it seems thats only an UUID for the BP itself.

Is there a file missing wich will be deleted by an update over the FTB launcher? Because I also looked trough the soruce but I can't follow them how the BP is builded or better how they are stored?
My first thought was, that it will be saved as a schematic file but this seems to be false.

So why is this happen? There is also no log entry o0 ... weird ... confused ...

**Comment by Chaos234** [comment]
Ok, I've used a recovery tool and searched directly after the "bpt" file ending and some magice there are bpt-files which seems to be deleted after an modpack update O.O - now there is a little problem with them ... they don't have there old file name ... they are called $IEUXWR8.bpt and $REUXWR8.bpt.

Is there a way to extract the UUID from the affected bluprint over the stored 32 byte HEX-Code? Can it be done over a normal HEX-Code-Editor?

I'll try smth with the recovered files and I'll response soon :).

**Comment by asiekierka** [comment]
So is this a bug in the FTB launcher? I admit that storing the blueprint files in config/blueprints/server is very unfortunate (it is entirely a historical reason) and I would love to change it, maybe even for 7.0.16.

**Comment by Chaos234** [comment]
Yeah, can be a bug. But I can't say it with 100%, not compleatly tested. At fisrt I must get the correct UUID from the 32 bit HEX-Code and then I must rename the file with this code and optionally his stored bp-name.

If the test will be a success then it's definitly a bug from the launcher and it will be better to store all things from BC under config/bc or config/buildcraft with a dir for bluprints/templates because you can choose to save a backup from the conifg and the SP-Worlds.

**Comment by Chaos234** [comment]
Well, can you tell me how the hex is generated @asiekierka ? Is it a Base32 or an Base32HEX or ...?
If I have the correct one, then I can "hack" the UUID to reencode them.

**Comment by Chaos234** [comment]
;( ... they are gonna way, all I have isto hope that they are left on C.\ and matching the uniqueBptId from the NBTExplorer.

To prevent this why you dont store the saved structure over NBT only? A list foreach layer and in there all Blocks with ID and position of the created 3D-Room from the architect table?

**Comment by asiekierka** [comment]
Because items are synced over the network with all their NBT data and that
would cause severe bandwidth crippling. Probably bigger world sizes, too.

2015-07-13 0:45 GMT+02:00 Chaos234 <notifications@github.com>:
