### ISSUE TITLE
Ender Fluid Tank and Buildcraft not compatable

### ISSUE THREAD

**Issue by ALGIEandFAMILY** [BuildCraft/BuildCraft#2887]
crash report is as follows running couldron 1.7.10 using the ender tank in cobblestone fulid pipe

13.07 11:22:15 [Server] INFO A detailed walkthrough of the error, its code path and all known details is as follows:
13.07 11:22:15 [Server] INFO at java.lang.Thread.run(Thread.java:745)
13.07 11:22:15 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
13.07 11:22:15 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
13.07 11:22:15 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
13.07 11:22:15 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
13.07 11:22:15 [Server] INFO at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
13.07 11:22:15 [Server] INFO at net.minecraft.world.World.func_72939_s(World.java:2412)
13.07 11:22:15 [Server] INFO at net.minecraft.world.World.func_72870_g(World.java:2600)
13.07 11:22:15 [Server] INFO at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
13.07 11:22:15 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:2647)
13.07 11:22:15 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:374)
13.07 11:22:15 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:699)
13.07 11:22:15 [Server] INFO at codechicken.enderstorage.common.TileFrequencyOwner.func_145844_m(TileFrequencyOwner.java:111)
13.07 11:22:15 [Server] INFO at codechicken.enderstorage.storage.liquid.TileEnderTank.writeToPacket(TileEnderTank.java:221)
13.07 11:22:15 [Server] INFO at codechicken.lib.packet.PacketCustom.writeFluidStack(PacketCustom.java:376)
13.07 11:22:15 [Server] INFO java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluidID()I
13.07 11:22:15 [Server] INFO Description: Ticking entity
13.07 11:22:15 [Server] INFO Time: 7/13/15 11:22 AM
13.07 11:22:15 [Server] INFO // Don't do that.
13.07 11:22:15 [Server] ERROR ---- Minecraft Crash Report ----

**Comment by asiekierka** [comment]
EnderStorage needs an update to Forge 1355+.

2015-07-13 13:35 GMT+02:00 ALGIEandFAMILY <notifications@github.com>:
