### ISSUE TITLE
Chisel 2 hex plating pipe covers don't retain color chosen with Chisel item

### ISSUE THREAD

**Issue by Novocastrian** [BuildCraft/BuildCraft#2888]
As the title suggests, pipes don't keep the color chosen pre - assembly table.  Originally posted in Chisel 2 ' git repo, but they claim that it on your end (https://github.com/Chisel-2/Chisel-2/issues/370)

**Comment by laz2727** [comment]
Custom render.

**Comment by asiekierka** [comment]
On 1.8+, everything will be so different here.
