### ISSUE TITLE
Clicking on FS (Fullscreen) in Zone Planner DC's from server.

### ISSUE THREAD

**Issue by Zetharion** [BuildCraft/BuildCraft#2892]
Everytime I hit the fullscreen button in the Zone Planner I get disconnected from the server.  There is no crash so no crash report to provide.  Using BC version 7.0.12, Compat 7.0.8 and BC Additions 2.2.0.

**Comment by smbarbour** [comment]
Also occurs in 7.0.16.

From the server's log:  https://gist.github.com/smbarbour/7c66e6609e7547783001

**Comment by asiekierka** [comment]
Workaround: Lower your resolution. (Yup.)
