### ISSUE TITLE
Planter issue on 7.0.16

### ISSUE THREAD

**Issue by FinalPast** [BuildCraft/BuildCraft#2894]
All is working in my base on 7.0.13 but in 7.0.16, planters don't move from the docking station, even in "Wake up" mode, and necessared items in chest and off course, there are loaded.
It's very strange, Thanks for this amazing mod.
Moreover, sorry for my English.

**Comment by hea3ven** [comment]
Does the chest with the seeds have a station with the gate action "provide items" activated?

**Comment by FinalPast** [comment]
You are Amazing, it's working perfectly. Thank you for all.
Sorry for your wasted time, I hope that this post will help someone who has the same problem.
I searched all the way to make them work but with a stone pipe (because that was worked) like in the 7.0.13. 
I might read the changelog a little too fast.
You can close, this issue, and if it's useless, delete, burn or I don't know.
