### ISSUE TITLE
Wooden kenisis pipe not extracting energy

### ISSUE THREAD

**Issue by isaacpokemon2003** [BuildCraft/BuildCraft#2895]
![2015-07-18_22 19 25](https://cloud.githubusercontent.com/assets/13400922/8764689/4708c3b2-2d9e-11e5-8a86-19c45a0d8642.png)
![2015-07-18_22 19 10](https://cloud.githubusercontent.com/assets/13400922/8764690/4cdd954c-2d9e-11e5-99c1-86479c0cd123.png)

**Comment by asiekierka** [comment]
Nothing is using power, why would it extract energy?

**Comment by isaacpokemon2003** [comment]
As soon as I posted it and played the game I ended up realizing and facepalmed
