### ISSUE TITLE
Add missing Comparator support

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildCraft#2897]
* Filtered Buffer
* Chute
* Requester

**Comment by RagaRBM** [comment]
How about Tanks? :P

**Comment by asiekierka** [comment]
Already in BC7

Dnia 21 lip 2015 o godz. 04:30 RagaRBM <notifications@github.com> napisał(a):

**Comment by asiekierka** [comment]
https://github.com/BuildCraft/BuildCraft/commit/a0a81e2503fdc1784bd671e710132ae2de0353c8
