### ISSUE TITLE
Crash report from having a bunch of mods installed.

### ISSUE THREAD

**Issue by SystemPony** [BuildCraft/BuildCraft#2899]
Crash Report: http://pastebin.com/XevxzGSv

I know Buildcraft is the problem because when I uninstall it everything works fine!

Thanks in advance ^^

**Comment by Kubuxu** [comment]
Its not BC problem. One of your mods includes old BC API. It vanishes after you remove BC as nothing is then using it.

**Comment by SystemPony** [comment]
Oh I see. Does the report have any information on what mod that is or do I have to, sadly, go through the mods and see which one it is?

**Comment by Kubuxu** [comment]
Unfortunately it doesn't. You might want to look into mods jars for folder `buildcraft`.
Just remove this folder from jar (leave it in buildcraft itself) and restart MC. If it won't crash you've found it.

**Comment by SystemPony** [comment]
Issue solved!
It was Universal Electricity. Thanks Kubuxu :D
