### ISSUE TITLE
Current Build In Github is Uncompilable

### ISSUE THREAD

**Issue by tincopper2** [BuildCraft/BuildCraft#2901]
I followed all of your steps for recompiling Buildcraft, and was met with no luck when after I tried 'gradle setupCIWorkspace build', and I installed Gradle, and set a path for it in environment variables, I ended up with this:
http://pastebin.com/9jHpSYfs

**Comment by asiekierka** [comment]
That's normal. The checkstyle is supposed to fail until an actual release (when I routinely fix the style issues), but the files are okay!
