### ISSUE TITLE
Filler being inconsistent with non-full power

### ISSUE THREAD

**Issue by Zaflis** [BuildCraft/BuildCraft#2902]
My power source in base is so far only 320 RF/t, so once the buffer dried out, filler (in full clearing mode) started leaving gaps, like this https://jhbcheesy1.files.wordpress.com/2014/07/swiss-cheese.jpg

So what i think is happening is that the machine is pushing the work queue onwards even if it doesn't have enough power to do it. So blocks get skipped.

Buildcraft 7.0.16, Builcraft-compat 7.0.9
MC 1.7.10

**Comment by Kubuxu** [comment]
Yes, it breaks softer blocks if he have not enough power to break stronger.
It will resume to breaking harder blocks when a) it gets more power b) it broke all softer blocks.
