### ISSUE TITLE
API issue with CoFH core 3.0.3-303 stops Minecraft during load. Buildcraft affected [Forge Mod sorting isue]

### ISSUE THREAD

**Issue by craft90** [BuildCraft/BuildCraft#2907]
So every time I try to launch Minecraft, Forge runs into a error and fails to load any further. It seems to be caused by some kind of mod sorting issue by CoFHcore mod. I have approached team CoFH about this issue but they claim that they are not the cause of this error, The problem persists through everything I do:, Mod updating, JAR surgery. So I dediced to approach you as your mod seems to be one of the affected mods. I have no crash log because Minecraft crashes on load. I can't seem to find MinecraftForge-log-0 either which the error claims have more information. (I did catch a couple other Forge logs, which I could share)

Without further ado, here's the error I get:
<a href="http://s151.photobucket.com/user/Nick_Jason/media/COFHcoreError_zpskbhhfx95.png.html" target="_blank"><img src="http://i151.photobucket.com/albums/s146/Nick_Jason/COFHcoreError_zpskbhhfx95.png" border="0" alt=" photo COFHcoreError_zpskbhhfx95.png"/></a>

**Comment by asiekierka** [comment]
It's in .minecraft/logs

**Comment by craft90** [comment]
It isn't. Not on my client anyway. There's fml-client-1.log fml-client-2.log fml-client-3.log fml-client-latest-log fml-junk-earlystartup.log and latest.log no ForgeModLoader-client-0.log I use MultiMC

**Comment by asiekierka** [comment]
fml-client-latest.log MIGHT be it.

**Comment by craft90** [comment]
OK. I can share that one. fml-client-2 and fml-client-3 are too big to be able to share on free pastebin or here.

http://pastebin.com/YnSsPeqY

**Comment by asiekierka** [comment]
[15:49:47] [Client thread/ERROR] [FML/]: Likely cycle is in : [FMLMod:CoFHCore{1.7.10R3.0.3}, FMLMod:BiblioWoodsForestry{1.7}, FMLMod:Forestry{3.6.3.20}, APIContainer{CoFHAPI:1.0}, Dummy Container (AfterAll) @28497624, APIContainer{CoFHAPI|energy:1.7.10R1.0.1}, Dummy Container (After) @3613876]

No idea what's wrong here.

**Comment by loordgek** [comment]
i had it to i fixed it by updating all mods
i think it is a api mismatch
