### ISSUE TITLE
[BC 7.0.17 ] robotics NullPointerException

### ISSUE THREAD

**Issue by MySt1k** [BuildCraft/BuildCraft#2911]
http://pastebin.com/jgEBPdSv

**Comment by hea3ven** [comment]
Damn, same as #2898, I fixed it in the 7.1 branch. @asiekierka if you make another release cherry-pick 41bb30a

**Comment by asiekierka** [comment]
I thought it's 7.1-specific! Next time, please push to the 7.0 branch if it's related to both.
