### ISSUE TITLE
ROBOT

### ISSUE THREAD

**Issue by KnottyCord** [BuildCraft/BuildCraft#2913]
IS there a way to delete a Dead robot because the only solution that i found was to but the robot in the void!

**Comment by Kubuxu** [comment]
Removing its base station should destroy it.

**Comment by KnottyCord** [comment]
No it does not work the Robot is now dead if you remouve the station

**Comment by hea3ven** [comment]
Shift-right click it with a buildcraft wrench.

**Comment by KnottyCord** [comment]
thx man !!!!
