### ISSUE TITLE
Question about reset world.

### ISSUE THREAD

**Issue by lightning02** [BuildCraft/BuildCraft#2915]
The new fluid that your mod add, subscribe the existing chunks??
If i put your mod in my server i have to reset the world for the new oli that add? 

Matierials and stuff of your mod will generate only in new chunks? Or even in old chunks of my world?

this are also for Dragon api?

**Comment by gjgfuj** [comment]
It will only generate in newly generated chunks. So if you explore further
it'll show up.

**Comment by dj3520** [comment]
Actually in config/Galaticraft/core.conf

B:"Retro Gen of GC Oil in existing map chunks"=false

change to true
But yes from now on questions on the forum.

**Comment by gjgfuj** [comment]
That's... Galacticraft... Not buildcraft.

**Comment by dj3520** [comment]
*facepalm* oops

Though while on the topic, they also have oil.

**Comment by gjgfuj** [comment]
Yes, as does pneumaticraft, and both are compatible with bc. That's off
topic though.
