### ISSUE TITLE
[suggestion] Steel pipes.

### ISSUE THREAD

**Issue by demethan** [BuildCraft/BuildCraft#2916]
Hi, 

the pack I`m currently playing has 183 mods. I have a fully power EnderQuarry that eats a chunk a minute. A tesseract is used to transport the items from the Deep Dark to Overworld. I use a gold pipe to connect the tesseract to an LP network. 

the problem I have is that the gold pipe will blow up under load. It only happens on the pipe connecting the quarry. I have the same setup for my farm and that gold pipe doesn't blow up. 

It would be nice to have a stronger pipe that can withstand the load. I leave the particulars to you. 

Thanks.

**Comment by asiekierka** [comment]
Or make a buffer with a chest next to the Ender Quarry, then use a wooden pipe to extract into the Tesserract at a manageable rate.

(Or use multiple tesseracts. Or have multiple output pipes. Or...)

**Comment by demethan** [comment]
Of course everyone can work arround the pipe blowing up.  that is what I did. I just find funny that the highest tier pipe in the mod can't  handle it and a better pipe is required. Or remove the blowing mechanic on the gold pipe.  

De toute façon ce n'était qu'une suggestion.  Merci pour ton mod. Thanks for your mod.

**Comment by SandGrainOne** [comment]
The mechanism blowing up the pipe isn't there for game play reasons. It is to ensure that players are prevented from using the pipe as storage. BuildCraft has a bad reputation related to lag partly because players made loops and had thousands of items going around.

There are two values. One to limit the number of stacks and another to limit the total number of items. The pipe will blow up when one of them is exceeded. The values are coded as 2 constants with values 64 and 1024 respectively.

Maybe it should be made into config options.

**Comment by demethan** [comment]
I like the explanation.  thank you. 

In the Technic pack 1.2.7 there was a block called a Buffer.  it would accept blocks from any side and automatically export from one side.  What happened to that block? The current buffer doesn't behave that way.

**Comment by SandGrainOne** [comment]
That block might have been a part of Red Power 2. At least not a part of BuildCraft.

**Comment by asiekierka** [comment]
@SandGrainOne - Config options? I can't wait for people to raise it to 9999 stacks and 999999 items and then blame us.

**Comment by Kubuxu** [comment]
Great idea. It would also solve of dumping a lot of items into obsidian pipe at one time.

**Comment by AEnterprise** [comment]
that and issues with non chunkloaded pipes

**Comment by dj3520** [comment]
Maybe a maximum though. The only time I have over 1000 items in a pipe at
once is an accidental loop.

**Comment by asiekierka** [comment]
@AEnterprise there are no issues with non-chunkloaded pipes as they are chunkloaded on demand, unless you're using Cauldron in which case you have only yourself to blame
