### ISSUE TITLE
Game keeps crashing when placing/interacting/activating BuildCraft Blocks

### ISSUE THREAD

**Issue by ChlodAidanAlejandro** [BuildCraft/BuildCraft#2920]
Whenever I try to play Minecraft with Buildcraft and other mods, I always get a crash report saying 

"Rendering entity in world

java.lang.IllegalStateException: Already tesselating!"

I don't know what tesselating means but when I dug deeper into the crash report I saw something related to BuildCraft:
"at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
	at buildcraft.core.lib.render.RenderEntityBlock.renderBlock(RenderEntityBlock.java:183)
	at buildcraft.core.lib.render.RenderEntityBlock.doRenderBlock(RenderEntityBlock.java:173)
	at buildcraft.core.lib.render.RenderEntityBlock.func_76986_a(RenderEntityBlock.java:137)"

How do you fix this?
Additional Info:
GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.4.13084 Compatibility Profile Context 14.301.1001.0' Renderer: 'AMD Radeon HD 8370D'
	Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 8370D GL version 4.4.13084 Compatibility Profile Context 14.301.1001.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

P.S: I did not connect the whole crash report since it is REALLY long

**Comment by XFactHD** [comment]
If you are using Optifine, removing it should fix the issue.

**Comment by ChlodAidanAlejandro** [comment]
Hmm... if that's so, do you know any more mods that can zoom in?

**Comment by XFactHD** [comment]
No, I am also looking for a mod like that.
