### ISSUE TITLE
Underwater Pipe Rendering

### ISSUE THREAD

**Issue by larrythemodder** [BuildCraft/BuildCraft#2923]
If a pipe is placed underwater, it renders as if a full block is taking up the space and looks rather out of place.

**Comment by Kubuxu** [comment]
Buildcraft won't be using AquaTweaks. Recreate this issue in BuildCraft/BuildcraftCompat

**Comment by larrythemodder** [comment]
Alright, recreated it there.

**Comment by larrythemodder** [comment]
Quick question, though, should rendering fixes have to be part of a separate mod?

**Comment by Kubuxu** [comment]
@larrythemodder it is not render fix. It is standard behaviour of MC that non solid blocks look different under water. BC has policy that it should not depend on other mods nor link them. This is why BC Compat was created. You should usually have it installed either way.

**Comment by asiekierka** [comment]
To my best knowledge, AquaTweaks makes patches into Minecraft itaelf via coremods to provide the functionality. I am not going to have coremods within BC, if only to let myself sleep at night.

**Comment by larrythemodder** [comment]
@Kubuxu Alright, makes sense. Thanks for clarifying.
