### ISSUE TITLE
Builder's issue

### ISSUE THREAD

**Issue by sfchipan** [BuildCraft/BuildCraft#2924]
Some chest can't be place.
Video: https://youtu.be/3OQ3RIEQbLI

**Comment by asiekierka** [comment]
Could you send me the blueprint file? Is anything else output in the console?

**Comment by sfchipan** [comment]
https://www.dropbox.com/s/ih09fkgn4ce9ko9/Chest-71a07773468b41c505b11f0082830595819d1377d913705459d1ab7f72b367b9.bpt?dl=0
The previous blueprint has been deleted, I make a new one that just contains chests. It also have the issue.
Btw, it seems have no problem generally if the chests in a blueprint are empty. So could you add a feature that we can make the blueprints not recording any items in all inventories ?

**Comment by asiekierka** [comment]
I'll try to look into it later. For 7.0.19/7.1.0.

**Comment by AEnterprise** [comment]
should be fixed, most likely this was the bug where the builder's internal power buffer wasn't large enough for the power needs of a chest with alot of items

can be closed

**Comment by AlexIIL** [comment]
No this still happens in 7.2.7 :)

**Comment by AEnterprise** [comment]
should be fixed with in 7.99, if not let us know
