### ISSUE TITLE
Builder's issue about placing track

### ISSUE THREAD

**Issue by sfchipan** [BuildCraft/BuildCraft#2925]
Video:https://youtu.be/V_NCmqDcZFU
The tracks are placed before the block below them.
I think the builder can have a mechanism to check if there are tracks in blueprint, the builder place blocks below tracks firstly.
Or maybe adding a function to Achitect Table that we can config the order of placing manually.

**Comment by psxlover** [comment]
It's because of the gravel.
The builder should probably place falling blocks before non-opaque blocks, but that could also create problems.
Most appropriate solution would be to place falling blocks as soon as the block below them is in place, instead of after non-opaque blocks.

**Comment by asiekierka** [comment]
It's hard to do it without changing fluid stages. Marking to look into it for 7.1.0...
