### ISSUE TITLE
Suggestion: Making pipe can give out light

### ISSUE THREAD

**Issue by sfchipan** [BuildCraft/BuildCraft#2926]
![1](https://cloud.githubusercontent.com/assets/4555814/8958848/fd9b54de-3639-11e5-983e-7caae22d87af.png)
I strike this idea when I build this. If the pipe can light, I don't need the torch.
For instance, using glowstong dust materials add on pipe, making glowstone brush, or a special gate that can give out light.

**Comment by Kubuxu** [comment]
Or a pluggable that gives off light.

**Comment by hea3ven** [comment]
> Or a pluggable that gives off light.

That can also be integrated with facades, making it so that the facade gives off light.

**Comment by asiekierka** [comment]
Ehhhhh... Never liked the idea myself.

**Comment by AEnterprise** [comment]
maybe a plugable that draws power to emit light?

**Comment by dj3520** [comment]
like an IC2 luminator?

**Comment by Biochao** [comment]
Support for light emitting liquids?
![2015-07-30_11 21 14](https://cloud.githubusercontent.com/assets/6515654/8987092/3e173e42-36ad-11e5-986b-27254cddcbe9.png)

**Comment by loordgek** [comment]
glowstone facades?

**Comment by laz2727** [comment]
Too easy. Glowstone chipsets.

**Comment by psxlover** [comment]
> Support for light emitting liquids?
> 2015-07-30_11 21 14

I though that lava in liquid pipes emitted light.

**Comment by laz2727** [comment]
Nope.

2015-07-31 17:58 GMT+06:00 psxlover <notifications@github.com>:

**Comment by ganymedes01** [comment]
I don't know about pluggables that emit light, but I thing fluid pipes should emit the same light level as the fluids they are transporting... would only make sense seen as the pipes are transparent

**Comment by asiekierka** [comment]
This will be too laggy. All I can do is make the fluid glow /inside/ the pipe, which is what I will do...
