### ISSUE TITLE
Could you add a counter to BC Machines (specifically the Filler)

### ISSUE THREAD

**Issue by Hypocrisy** [BuildCraft/BuildCraft#2928]
A counter that would inform you of how many blocks are left to be cleared or built.

**Comment by asiekierka** [comment]
That's not a bad idea!

**Comment by AEnterprise** [comment]
still planned? if so the 'needs developer tag' is not needed

**Comment by AlexIIL** [comment]
Still planned, will probably happen with a "side gui thingy"
