### ISSUE TITLE
Builder, Filler, Quarry: Whitelist for destroyable blocks

### ISSUE THREAD

**Issue by lucom** [BuildCraft/BuildCraft#2930]
It would be great to define a whitelist for blocks that can be destroyed with machines. With that whitelist one could still use these machines, like the filler, to e.g. flatten the landscape, without getting too many resources like iron ore, obsidian, etc.

**Comment by psxlover** [comment]
What do you mean, without getting too many resourcers? Filler destroys the blocks so you don't get any resources.

**Comment by lucom** [comment]
In the config one can enable that fillers or builders drop the blocks instead of destroying them. With that option enabled, a filler set to clear an area and a good energy source one can mine extreme amounts of ressources in a very short time.
With the whitelist for the filler you would have to mine the remaining blocks by hand.

**Comment by dj3520** [comment]
Not too sure why you'd want to enable that when the quarry is an option.

**Comment by asiekierka** [comment]
Exactly. They eat almost the same amount of energy (+/- the arm moving usage).
