### ISSUE TITLE
Crash - buildcraft-7.0.17

### ISSUE THREAD

**Issue by 008** [BuildCraft/BuildCraft#2932]
http://pastebin.com/5AbUdKH6

**Comment by AEnterprise** [comment]
from the bottom of the log:
```
Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client:
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
```

**Comment by Kubuxu** [comment]
and how is that even connected with BC. I can only see ic2 in this log.

**Comment by 008** [comment]
sorry, wrong past bin, also i am downgrade BC and no crash any more

**Comment by AEnterprise** [comment]
downgrading isn't always the best solution, please provide the correct pastebin and we can investigate a proper fix
