### ISSUE TITLE
Programming Table: Mix up between Harvester and Butcher

### ISSUE THREAD

**Issue by Gragnar** [BuildCraft/BuildCraft#2935]
When trying to make a butcher redstone board, it makes a harvester and vice-versa.

List of mods:

1.7.10-Pistronics2-v0.5.8
AgriCraft-1.7.10-1.4.0-alpha-7-1.7.10
AOBD-2.7.1
AppleCore-mc1.7.10-1.1.0
archimedesshipsplus-1.7.10-1.7.12
Atum-1.7.10-0.6.60
BBG-1.0.0
bdlib-1.9.0.94-mc1.7.10
BetterFoliage-mc1.7-1.0.13
BiblioCraft[v1.10.4][MC1.7.10]
BiblioWoods[Forestry][v1.7]
BiblioWoods[Natura][v1.5]
binnie-mods-2.0-pre14
BiomesOPlenty-1.7.10-2.1.0.1364-universal
buildcraft-7.0.16
buildcraft-compat-7.0.9
BuildcraftAdditions-1.7.10-2.2.0
Carpenter's Blocks v3.3.6 - MC 1.7.10
Chisel2-2.4.1.40
ChiselTones-1.7.10-1.0-1
chocolateQuest-1.7.10-1.0
CodeChickenCore-1.7.10-1.0.7.46-universal
CoFHLib-[1.7.10]1.0.3-175
CustomNPCs_1.7.10d
Decocraft-2.0.2_1.7.10
dimensional-anchor-59.0.3
DoomlikeDungeons-1.8.3-MC1.7.10
EnchantingPlus-1.7.10-3.0.2-d
EnderStorage-1.7.10-1.4.7.36-universal
EnhancedPortals_1.7.10-universal-3.0.12
Eureka-1.7.10-3.0.2
ExtraTiC-1.7.10-1.4.5
extrautilities-1.2.8
fastcraft-1.21
FastLeafDecay-1.7.10-1.1
forestry_1.7.10-3.6.3.20
Fossils_Archeology_Revival-1.7.10_Build-7.2
funky-locomotion-1.7.10-beta-5c
gendustry-1.5.2.107-mc1.7.10
IguanaTinkerTweaks-1.7.10-2.1.5
immibis-core-59.1.1
INpureCore-[1.7.10]1.0.0B9-62
InventoryTweaks-1.59-dev-152
ironchest-1.7.10-6.0.60.741-universal
IvToolkit-1.2
Jabba-1.2.1a_1.7.10
journeymap-1.7.10-5.1.0-unlimited
logisticspipes-0.9.2.17
magicbees-1.7.10-2.3.2
Mantle-1.7.10-0.3.2
Minechem-1.7.10-5.0.5.398
MobiusCore-1.2.5_1.7.10
movingworld-1.7.10-1.7.12B
natura-1.7.10-2.2.0.1
neiaddons-1.12.10.33-mc1.7.10
NEIIntegration-MC1.7.10-1.0.11
NotEnoughItems-1.7.10-1.0.5.111-universal
OpenBlocks-1.7.10-1.4.3
OpenComputers-MC1.7.10-1.5.14.30-universal
OpenModsLib-1.7.10-0.7.3
OpenModularTurrets-1.7.10-2.0.3-150
Pam's Clay Spawn 1.7.10a
Pam's HarvestCraft 1.7.10i
PlayerInterfaceMod-1.3
ProjectRed-1.7.10-4.7.0pre6.90-Base
ProjectRed-1.7.10-4.7.0pre6.90-Compat
ProjectRed-1.7.10-4.7.0pre6.90-Integration
ProjectRed-1.7.10-4.7.0pre6.90-Lighting
Railcraft_1.7.10-9.6.1.0
RecurrentComplex-0.9.6.3
SimplyJetpacks-MC1.7.10-1.5.1
SolarFlux-1.7.10-0.8a
SpiceOfLife-mc1.7.10-1.2.3
StorageDrawers-1.7.10-1.5.12
StorageDrawers-Forestry-1.7.10-1.0.1
StorageDrawers-Natura-1.7.10-1.0.2
TConstruct-1.7.10-1.8.5
TiCTooltips-mc1.7.10-1.2.5
TMechworks-1.7.10-0.2.14.100
twilightforest-1.7.10-2.3.7
Waila-1.5.10_1.7.10
Ztones-1.7.10-2.2.1

**Comment by asiekierka** [comment]
https://github.com/BuildCraft/BuildCraft/commit/3ba0cc56f6f8eb6f7bfaaa872769b81036cd06e8 - maybe.
