### ISSUE TITLE
Quarry bug block-breaking (sorry for english)

### ISSUE THREAD

**Issue by Serehactka** [BuildCraft/BuildCraft#2937]
On the server I have the latest buildcraft version (7.0.17). Server has WorldGuard plugin. I have installed quarry and chosen the max size for digging. But some zones wich don't exactly include chunks (they can be bigger or smaller then chuncs) don't digging by quarry. And also quarry try to break them but not succesfull. Quarry work on the not private land. Can someone get to me advice for this problem? Sorry again for my english.

**Comment by asiekierka** [comment]
Op the BuildCraft player UUID. Check your server launch logs for what it is.
