### ISSUE TITLE
Config option to disable destruction and construction of blocks automatically

### ISSUE THREAD

**Issue by Carbon-Ghost** [BuildCraft/BuildCraft#2938]
This config will disable builders and fillers, and will make quarry unable to work if the area of construction isn't clear, I request this feature because someone destroyed everything in a completely warded ( thaumcraft ) base of one of my friends, the only thing that was left was the warded blocks...

Quarry itself can't mine this stuff but when setting it up it can destroy everything inside...
I also requested that because one may use a builder or filler to fill in someone base with blocks exteriorly... Flood gates are fine though ^^

**Comment by asiekierka** [comment]
Just remove the Builders module.

**Comment by Carbon-Ghost** [comment]
Aow, but it will remove the quarry ? :c
