### ISSUE TITLE
Quarry make server crash when used

### ISSUE THREAD

**Issue by evernife** [BuildCraft/BuildCraft#2939]
Here follows the crash report:

http://pastebin.com/2mEHg7Xk

This is not everytime, but, sometimes, crashes...

**Comment by asiekierka** [comment]
Can you reproduce withotu Cauldron? Looks fine to me.

**Comment by Meegooo** [comment]
Similar bug exists with filler. Cauldron as well.
[Crash report](https://gist.github.com/Meegooo/9b6c67a147ee983b7d82)

Player said that he placed filler, tried to select mode and server crashed. And every time he tried to login, server crashed.
I couldn't reproduce it myself even at the same coordinates.

**Comment by Deadlock989** [comment]
Same issue. Can reproduce both on a Cauldron MP server and in single player with the same modpack. In MP it effectively kills the server as any player wandering within range will be stuck in a crash loop.

http://pastebin.com/Z7Z058gD

**Comment by asiekierka** [comment]
@Deadlock989 - how are you reproducing it?

**Comment by Deadlock989** [comment]
Place 3 land marks in an L shape. Place a quarry next to one of them. Place a chest and a power source. Quarry will build the first corner of the frame and then crash when it gets to the top. Save is effectively corrupted.

**Comment by asiekierka** [comment]
@evernife @Deadlock989 please try http://asie.pl/bc7021a.jar

**Comment by Deadlock989** [comment]
Same result. Quarry placed with no land marks works, putting a default size frame. Any quarry placed next to a landmark produces just one short stub which will crash server and corrupt save.
![2015-08-11_16 06 56](https://cloud.githubusercontent.com/assets/3128845/9201096/27698fc0-4043-11e5-8c73-5bb8a5125e89.png)

**Comment by evernife** [comment]
Same here :D
