### ISSUE TITLE
Redstone Signals Don't Turn on Engines

### ISSUE THREAD

**Issue by larrythemodder** [BuildCraft/BuildCraft#2940]
Placing levers and turning them on or placing redstone torches next to engines does turn them on, but for some reason a redstone signal doesn't. BC 7.0.17.

**Comment by SandGrainOne** [comment]
Could you provide a screenshot?

**Comment by psxlover** [comment]
The redstone signal should be above a block that is next to the engine, that's how vanilla redstone works.

**Comment by SandGrainOne** [comment]
There are other configurations that would work, but in general: the engines requires direct power or to be next to a block with a strong signal.

**Comment by larrythemodder** [comment]
@psxlover Still nothing with redstone, and levers work fine on the same level as the engine. @SandGrainOne What would these configurations be? I've tried repeaters, but no luck.

**Comment by psxlover** [comment]
Like I said when you use redstone, the redstone should be above a block that is adjacent to the engine, not next to the engine. Levers on the same level work fine because they emit redstone signals, they are not the same as redstone. Also provide a screenshot.

**Comment by SandGrainOne** [comment]
I did 3 different setups. http://i.imgur.com/ajkTQKb.png

First is invalid the two others are okay.
