### ISSUE TITLE
Knight Robot Sword Damage wrong

### ISSUE THREAD

**Issue by Rearth** [BuildCraft/BuildCraft#2941]
Im using a Knight Robot, and gave it an Ichorium Sword with +9 Attack Damage. However, when it attacks Mobs with this Sword equipped, it only deals 2 Damage Points (1 Heart)

**Comment by chemdork123** [comment]
See new issue opened, #3159 .  It seems the enchantment issue was fixed, but the inherent damage characteristic of the sword is being ignored (so unenchanted wooden = just as powerful as unenchanted diamond)
