### ISSUE TITLE
Gates react unreliably to short Redstone pulses

### ISSUE THREAD

**Issue by pennywis3** [BuildCraft/BuildCraft#2942]
Test setup:
![2015-08-03_01 27 06](https://cloud.githubusercontent.com/assets/4288061/9028586/d02c0528-397e-11e5-8ebf-42e93ba143f6.png)
The Gate is set to trigger a Single Energy Pulse on active Redstone. Short Redstone pulses sometimes won't trigger the action, even though the gate will light up to indicate the signal.
When the timer (set to 1 or 2 seconds) is running, the gate will either trigger on every pulse, or none, until the timer is turned off and on again. This can be reproduced with pulse lengths between 1 and at least 4 ticks, where 1 tick seems to have the highest probability of failing.
Changing the repeater setting / pulse length during a timer run does not produce consistent results, and it won't make it react to something it hasn't before.

I am using BC 7.0.17.

**Comment by SandGrainOne** [comment]
What Action are you testing with? Energy Pulser?
Could you try with a different action like Power a Wire?

**Comment by pennywis3** [comment]
It's not going away just yet (BC 7.0.19).
The Gate in the above picture is a Diamond OR Gate with each slot set to a Single Energy Pulse on active Redstone, so it should extract 8 items per pulse.
In cases where it would not trigger before, it will now extract only 1 item and still not trigger the "pump-style" Gate animation.
In cases where it would have triggered before, it will either extract 8 + 1 items in 2 separate stacks, or 8 items like it should.

This only applies to the Single Energy Pulse setting, the standard Energy Pulsar shows the behavior (for short pulses, of course) I described in the original post.

Adding an intermediate stage to the signal like Pipe Wire does not affect the behaviour.

**Comment by asiekierka** [comment]
Oh. Huh.

**Comment by pennywis3** [comment]
Is it possible that
```java
if (tick++ % PULSE_PERIOD != 0) {
    // only do the treatement once every period
    return;
}
```
in [GateExpansionPulsar.java#L87](https://github.com/BuildCraft/BuildCraft/blob/6.5.x/common/buildcraft/transport/gates/GateExpansionPulsar.java#L87) breaks on pulse lengths < 10 ticks?
