### ISSUE TITLE
Quarry problem with item-conduits

### ISSUE THREAD

**Issue by Granik24** [BuildCraft/BuildCraft#2944]
Hi, I have problem with Quarry and EnderIO item conduits.
We are ussing buildcraft-7.0.17 and EnderIO-1.7.10-2.3.0.404_beta.
Sometimes, quarry pull items to item condiuts, sometime no.

There is a screen
![11827181_851439224932459_457391549_o](https://cloud.githubusercontent.com/assets/4377405/9043816/83e02ab0-3a18-11e5-8142-1ede9f4806bc.jpg)

**Comment by cr0wl** [comment]
Try to put the capacitor next to the quarry. The quarry starts throwing blocks for me if it's powered with a conduit. Ducts from Thermal Expansions works fine for me though.
Playing FTB Infinity 1.8.2 with Buildcraft 7.0.15

**Comment by asiekierka** [comment]
Try BuildCraft 7.0.19 + Compat 7.0.10. Some fixes were done in that area.

**Comment by Granik24** [comment]
@cr0wl You're right. Thats setup works fine.
@asiekierka Still not fixed in 7.1.0 same in 1.0.19.

**Comment by EntropicPariah** [comment]
I've experienced weird stuff in the past where enderio conduits extracted the scaffolding from the quarry so to mitigate all the problems trying to interface the two mods I just run one buildcraft extraction pipe from the quarry into a chest and then run enderio conduit from the chest. This way, other than the power source, the two mods aren't interacting with each other when it comes to the quarry.

**Comment by asiekierka** [comment]
@EntropicPariah - the "scaffolding" part was mostly fixed a while back IIRC

**Comment by AEnterprise** [comment]
item conduits have a limit of how much they can transfer how fast so the quarry in this case is probably faster, also don't know how they accept items, using a buffer chest is probably better

can be closed
