### ISSUE TITLE
Texture missing BC7 and IC2exp

### ISSUE THREAD

**Issue by Hemz1989** [BuildCraft/BuildCraft#2945]
hi i´m new here, i´ve been searching for an answer to this but i dont find it, frist of all ,thank you for support the mod and for your enormous amount of patience. 
Well since i´ve changed buildcraft 6.1.8 to buildcraft 7.017 some textures went missing or invisible( i said some because it is a new a world so i havent much) after that i google some information so i know that textures form both versions are incompatible so you must make a compilation or something like a resourse pack.
 The main reason that i post my issue here is. 
1: I dont mind playing with the new textures form BC7 so what can i do beside the resourse pack? 
2. There is a chance that when i changed BC6 to BC7 , industrialcraft 2 experimental textures went wrong too?and if it is possible how could I solve it?

note: the textures of BC6 and IC2exp were working fine before i made the change to BC7

I made some screenshots for examples
http://imgur.com/a/LE3Kw

as you notice someother mods  like forestry or  betterstorage do not get affected 

note 2: i apologize for my poor english 
Some system and mod information:
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 713242696 bytes (680 MB) / 1231552512 bytes (1174 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_A4 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHI	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHI	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHI	ImmibisMicroblocks{59.0.0} [Immibis's Microblocks] (Immibiss-Microblocks-Mod
1.7.10.jar) 
	UCHI	minecraftloader{0.1} [MinecraftLoader] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHI	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
	UCHI	IC2{2.2.757-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.757-experimental.jar) 
	UCHI	AdvancedMachines{1.1.3} [IC2 Advanced Machines Addon] (AdvancedMachinesAS-1.7.10.jar) 
	UCHI	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHI	betterstorage{0.9.2.107} [BetterStorage] (Better-Storage-Mod-1.7.10.jar) 
	UCHI	BuildCraft|Core{7.0.17} [BuildCraft] (buildcraft-7.0.17.jar) 
	UCHI	BuildCraft|Factory{7.0.17} [BC Factory] (buildcraft-7.0.17.jar) 
	UCHI	BuildCraft|Energy{7.0.17} [BC Energy] (buildcraft-7.0.17.jar) 
	UCHI	BuildCraft|Silicon{7.0.17} [BC Silicon] (buildcraft-7.0.17.jar) 
	UCHI	BuildCraft|Builders{7.0.17} [BC Builders] (buildcraft-7.0.17.jar) 
	UCHI	BuildCraft|Robotics{7.0.17} [BC Robotics] (buildcraft-7.0.17.jar) 
	UCHI	BuildCraft|Transport{7.0.17} [BC Transport] (buildcraft-7.0.17.jar) 
	UCHI	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) 
	UCHI	bcadditions{2.2.0} [BuildCraft Additions] (BuildcraftAdditions-1.7.10-2.2.0.jar) 
	UCHI	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHI	CompactSolars{4.4.39.315} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.39.315-universal.jar) 
	UCHI	thebombzenapi{2.4.1} [ThebombzenAPI] (ThebombzenAPI-v2.4.1-mc1.7.2.jar) 
	UCHI	enchantview{4.0.4} [EnchantView] (EnchantView-v4.0.4-mc1.7.10.jar) 
	UCHI	Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) 
	UCHI	enhancedportals{3.0.9} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.9.jar) 
	UCHI	flansmod{4.8.0} [Flan's Mod] (Flans Mod-1.7.10-4.8.0.jar) 
	UCHI	Forestry{3.6.3.20} [Forestry for Minecraft] (forestry_1.7.10-3.6.3.20.jar) 
	UCHI	IC2NuclearControl{1.7.10.07} [Nuclear Control] (ic2nc-1.7.10-1.7.10.07.jar) 
	UCHI	ImmibisCore{59.0.1} [Immibis Core] (Immibis-Core-1.7.10.jar) 
	UCHI	iridiummod{0.8} [Iridium Mod] (iridiummod-1.7-0.8.jar) 
	UCHI	LogisticsPipes{0.9.2.23} [Logistics Pipes] (logisticspipes-0.9.2.23.jar) 
	UCHI	lom{1.7.10-3.0.0} [LotsOMobs] (lom-1.7.10-3.0.0.jar) 
	UCHI	cfm{3.3.6} [§6MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.3.6(1.7.10).jar) 
	UCHI	harvestcraft{1.7.10b} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10c.jar) 
	UCHI	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) 
	UCHE	RedLogic{59.0.1} [RedLogic] (RedLogic-Mod-1.7.10.jar) 
	UCHI	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHI	treeores{1.0} [treeores] (TreeOresMod-1.7.10-4.5.jar) 
	UCHI	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar)

**Comment by asiekierka** [comment]
Something's corrupting your textures. Update ALL of the mods.

**Comment by psxlover** [comment]
Start by removing Optifine...
