### ISSUE TITLE
Screen flickering after setting career

### ISSUE THREAD

**Issue by rikipm** [BuildCraft/BuildCraft#2947]
Hello. The fact that playing with mod BuildCraft I found a nasty bug: after setting career and including some chunks periodically (with a frequency of 5-6 seconds) started to flicker white. The console on this score remained silent. Play with the following build:
BuildCraft 3.7.1
Industrial Craft 1.117
Oprifine
Forge
my video card Nvidia GeForce 7025\Nvidia Ge Force 630a
----------------------------------------------------------------------------------
Forgive apologize for any grammatical errors. Google Translate is probably bad

**Comment by psxlover** [comment]
BuildCraft 3.7.1 is ancient, you wont get any support for it.
The only thing I could advise you is to try without Optifine.

**Comment by asiekierka** [comment]
Try updating to BuildCraft 3.7.2, too.
