### ISSUE TITLE
The Precision Mode of List can't work

### ISSUE THREAD

**Issue by sfchipan** [BuildCraft/BuildCraft#2948]
https://youtu.be/mGiPiyaUua0
I put it in diamond item pipe, it can't distinguish tools have different damages. But it can distinguish forestry bees.

**Comment by AEnterprise** [comment]
presision mode checks NBT, damage is meta

**Comment by sfchipan** [comment]
But in this video https://www.youtube.com/watch?v=_Z1leMHp-AM ,
asie said the mode can detect damage.
