### ISSUE TITLE
Add dedicated linking tool to BC

### ISSUE THREAD

**Issue by sfchipan** [BuildCraft/BuildCraft#2949]
https://youtu.be/mjj8hFrTfGk
If many path marks are used, the starting point is random.
The builder's direction can't adjust the structure's direction if using path mark.

**Comment by asiekierka** [comment]
Oh yeah. Hmm.

**Comment by asiekierka** [comment]
Oh I see why this is. You need to connect the path markers in the order of building.

**Comment by RagaRBM** [comment]
Same as : https://github.com/BuildCraft/BuildCraft/issues/2832

**Comment by asiekierka** [comment]
We need some kind of linking tool. Not just for Path Markers, but Architect Tables too. Any ideas?

**Comment by AlexIIL** [comment]
Mostly implemented in 8.0.x atm.

**Comment by AEnterprise** [comment]
has this been fully implemented?

**Comment by AlexIIL** [comment]
Yes! Its done and works very well now :)
