### ISSUE TITLE
Minecraft freezes when using Mining Wells

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [BuildCraft/BuildCraft#2950]
When using Mining Wells the Minecraft Game freezes, both if they are connected to pipes or not. Their simple action to dig seems to cause so much lag that the game freezes. No crash, no log, only some spam in the console, where fastcraft says that the server is running x ms behind, and y ticks will be skipped. A single mining well makes minecraft freeze only when connected to a pipe (tested with logistics pipes and thermal expansion itemducts), but not when connected to some kind of inventory (tested with ender chest by ender storage mod). More than one causes to freeze both ways.

The problem didn't happen in previous versions, but I can't figure out in which version the bug occurred first. 

Using 
Forge 1492
Buildcraft 7.0.20
BC compat 7.0.11

I'm using fastcraft 1.22 testbuild 13, which I always used before and after the bug happened

**Comment by asiekierka** [comment]
List of all mods? Are you using Cauldron?

**Comment by SmokeyTheBandicoot** [comment]
I'm not using cauldron, I was on SSP. I'm using a pretty big modpack.

Forge 1492

Buildcraft related:
BC 7.0.20
BC compat 7.0.11
Additional pipes 4.5.2 hotfix1
Logistics pipes 0.9.2.30
Chisel 2 2.4.1.40
Chisel facades 2.11 cricket

Full modlist:
http://pastebin.com/6TFfUQM1

How I found this issue:

I was building a frame machine, runnin pretty well in Aroma1997's mining world. Funky locomotion frames moved 16 mining wells, connected to (powered) logistics pipes leading to an ender chest, to process all the ores and put the results into my ME system. I built a remote activation/deactivation for the frame quarry, using ender chests, pretty much as Direwolf20 did in his let's play series in season6. 
I update my modpack pretty much everyday, and since a few days I noticed that my frame quarry didn't work anymore. After some days (and modpack updates) I decided to figure it out, thinking that it was a logic problem on my side related to gates and ender chests udes for activation. I entered the mining dimension and as soon as the frame quarry chunk loaded the game frozen. I had to delete DIM6 folder from my save, and I lost my machine. So I started rebuilding it in creative, and I managed to reduce the problem to:

A single mining well attached to a logistics pipes, connected to some kind of inventory
Multiple mining wells attached each one to its own enderchest, without any pipe
Multiple mining wells attached to non-opaque warp itemducts, connected to an enderchest

A single mining well attached directly to an ender chest didn't freeze my game.

**Comment by SmokeyTheBandicoot** [comment]
Any news on this? At least an idea on which mod that interacts with buildcraft may cause the issue, because this prevents me from using more than one mining well in my game at once, and I really need them.

**Comment by DraksterAU** [comment]
@asiekierka @SmokeyTheBandicoot Any plugin (that's right plugin) on cauldron that monitors block break events will lag the server to a halt as a result of the mining well.
Perhaps throttling their efficiency might be a good idea? or a config for it? Just a suggestion.

**Comment by AEnterprise** [comment]
the problem lies with that plugin or with cauldron then, forge has block break events as well and there are plenty of mods that listen to them but they don't lag things to death

**Comment by DraksterAU** [comment]
@AEnterprise Its not the plugin or Cauldron, the design of Bukkit has break events happen on the main thread.

**Comment by AEnterprise** [comment]
same still applies, this is a design issue that BC can't realy do much about, this also will give problems with alot more then just the BC mining well but with any other automated setup that breaks blocks

**Comment by DraksterAU** [comment]
Yeah that's fine. Hence why I suggested an option to throttle the speed of the device (for use on cauldron servers).

Same thing applies for mechanism digital miners with a 10x speed upgrade. 1x is fine.

**Comment by asiekierka** [comment]
Honestly, BuildCraft for 1.7.10 is essentially EOL with a rewrite being undertaken for 1.10.2. You're better off forking the thing and patching it yourself - future commits are very unlikely.
