### ISSUE TITLE
Obsidian Pipe can't work with Power Adapter

### ISSUE THREAD

**Issue by sfchipan** [BuildCraft/BuildCraft#2951]
![2015-08-08_20 52 44](https://cloud.githubusercontent.com/assets/4555814/9150526/dc26dee4-3e0f-11e5-970b-2484a3a4667c.png)
However If the engine directly power the adapter, it can do...
![2015-08-08_20 59 58](https://cloud.githubusercontent.com/assets/4555814/9150544/a7fdd8c4-3e10-11e5-94d6-14e10edfef4f.png)

**Comment by asiekierka** [comment]
Cannot reproduce. Just tried.

**Comment by AEnterprise** [comment]
the engine is hooked up to 2 power adapters in the first picture, it probably wasn't producing enough power to power both obsidian pipes

**Comment by sfchipan** [comment]
Yes...maybe the power in above image was not enough, I reproduced it with combustion engine.

**Comment by RagaRBM** [comment]
It seems items that came out from Obsidian pipe can't be sucked, but items thrown for example directly from outside the Obsidian Pipe can.

**Comment by sfchipan** [comment]
@RagaRBM Yes It seems to be the problem.
https://youtu.be/kn2iW1j5nUM

**Comment by asiekierka** [comment]
@RagaRBM I think that was added to stop infinite Obsidian Pipe loops. But it should be tweaked.

**Comment by AEnterprise** [comment]
maybe a delay? if it comes out of an obsidian pipe it can't be picked up for a short while by the pipe again
