### ISSUE TITLE
Bring pulsed RF back as a config option

### ISSUE THREAD

**Issue by SoniEx2** [BuildCraft/BuildCraft#2955]
I miss that, and I probably won't be playing BC until it comes back.

**Comment by SandGrainOne** [comment]
What do you imagine would be better or more interesting with pulsed power?

**Comment by SoniEx2** [comment]
It's just a personal preference thing, ya know?

Also I don't really wanna go back to playing MC 1.4.7.

**Comment by asiekierka** [comment]
You only realized it after 10 months?

It's not going to be a config option. It's permament, because otherwise huge chunks of BC are broken (and Forestry and RailCraft pulse anyway).

**Comment by gjgfuj** [comment]
Clarifying: pulsed rf will be back permanently, not unpulsed.

**Comment by SoniEx2** [comment]
Fair enough. Thanks.
