### ISSUE TITLE
striped pipes keep going even without energy

### ISSUE THREAD

**Issue by unknownEnemy1345** [BuildCraft/BuildCraft#2959]
so i noticed that in bc 7.1.1 striped pipes just keep going destroying blocks if they once started and you need to destroy them to stop it if they get a single energy pulse from an autharcic gate they start destroying blocks and never stop
![2015-08-11_19 11 38](https://cloud.githubusercontent.com/assets/13124041/9204331/e111b772-405c-11e5-937a-aff582ae08e5.png)
keeps going with gate and pipe wire removed (gave it a single energy pulse)

**Comment by asiekierka** [comment]
That's fixed in BC 7.1.2. I will check if I broke it in BC 7.0, though, however, as I think I did...

**Comment by asiekierka** [comment]
Oh, no, it's only an issue in BC 7.1.x. But fixed already.
