### ISSUE TITLE
Flywheel is un-craftable

### ISSUE THREAD

**Issue by adudney** [BuildCraft/BuildCraft#2960]
https://github.com/BuildCraft/BuildCraft/commit/3cdaf604a6445e005f292b9e5ed23f3ab3097c35

The gear in the recipe went from gearIron to gearStcone, which is misspelled.

**Comment by asiekierka** [comment]
Oh.

2015-08-11 19:40 GMT+02:00 adudney <notifications@github.com>:

**Comment by immibis** [comment]
Yay for not testing things! (I do this too sometimes...)

**Comment by asiekierka** [comment]
We all do that once in a while. At least we don't do it in release...

except we do

2015-08-19 3:25 GMT+02:00 immibis <notifications@github.com>:
