### ISSUE TITLE
Server Crash 

### ISSUE THREAD

**Issue by Omuck3** [BuildCraft/BuildCraft#2961]
http://pastebin.com/1x71FUn0

**Comment by AEnterprise** [comment]
your world is currupt it seems, it's trying to load something but corrupted, nothing we can do about it sadly

**Comment by Omuck3** [comment]
How can I find out where it is corrupt?  I can easily delete the region and
replace it(custom map)

**Comment by Omuck3** [comment]
Help!

**Comment by dj3520** [comment]
it doesn't say where. so you'll need a new world unless you want to go
digging for what's going wrong yourself
