### ISSUE TITLE
Buildcraft doesn't support "Carpenter's Blocks" mod.

### ISSUE THREAD

**Issue by BoyHarry** [BuildCraft/BuildCraft#2963]
I try to use filler to place some carpenter's blocks.Although the blocks can be place normally...but it places silly blocks--the carpenter block placed by filler is different from that placed by hand,it'can be coverd with any other block like that placed by hand.

**Comment by AEnterprise** [comment]
nothing we can do about that, only the person who placed the carpenter's block can cover it with another block, BC is using it's fake player to place down blocks

**Comment by BoyHarry** [comment]
So,i tell the carpenter's author.Maybe he can reslove.

**Comment by AEnterprise** [comment]
depends, i think it's a design choise to only allow the player who placed it to cover a block

**Comment by BoyHarry** [comment]
o...i see.
I suddenly have idea about filler.Can filler display the shape profile in the world before building?
Just like the building guider in the openblocks mod.
