### ISSUE TITLE
When I changed the texturepack,the tank with liquid displayed some wrong textures.

### ISSUE THREAD

**Issue by BoyHarry** [BuildCraft/BuildCraft#2964]
Such as the title,i used the defualt texture to open the game.I placed some tank and filled some liquid. When I changed the texturepack to the "soartex fanver"(64x texturepack),the tank will displayed  some wrong texture.
Similarly,when i use the  "soartex fanver"texturepack and change the texturepack into defualt,it will also happened.

**Comment by QORTEC** [comment]
I don't think this bug is Buildcraft specific, I ran into the same bug with Railcraft Iron/Steel Tanks.

**Comment by BoyHarry** [comment]
so you mean...does this bug belong to forge liquid system?

**Comment by Kubuxu** [comment]
@asiekierka are you rebuilding display lists on `TextureStitchEvent.Post`, this event signals that UV positions in `Icon`s could have changed.

**Comment by XFactHD** [comment]
@BoyHarry No, this seems to be a bug in Minecraft. This also sometimes happens for blocks that have different textures for different sides.

**Comment by dj3520** [comment]
I've had this happen before. Loaded the texture pack, force reloaded
textures with F3 + T (I think...) and restarted Minecraft.
