### ISSUE TITLE
Torches do not get placed on fence with builder (bc 7.1.1)

### ISSUE THREAD

**Issue by Sp3rw3r** [BuildCraft/BuildCraft#2968]
Builder tries to place torch in air first.
Puts fences later.
Torches drop on ground.

Eg. sheepfarm blueprint on forum.
Might be caused by fence altering mods (ganny's surface, forestry and railcraft installed among others)

**Comment by knexer** [comment]
Probably the same kind of thing as issue 2925 - torches need an analogous treatment.
