### ISSUE TITLE
Stamping table accepts wrong input

### ISSUE THREAD

**Issue by Sp3rw3r** [BuildCraft/BuildCraft#2972]
A stamping table set to create packages from oak wood planks was accepting oak wood from a clay pipe.
The stamping table to create packages from sticks and stone did not accept the packages while being first in line and connected with a clay pipe too.

**Comment by asiekierka** [comment]
You cannot nest packages in this manner. You can only nest packages by adding onto an existing package by inserting a package instead of paper.
