### ISSUE TITLE
Railcraft controller box does not respond to "redstone - this side only" gate action

### ISSUE THREAD

**Issue by Sp3rw3r** [BuildCraft/BuildCraft#2973]
A railcraft controller box reacts to the normal redstone on action.
It does not respond when using the action parameter this side only.

Not sure where the problem belongs: buildcraft, railcraft or bc compat.

**Comment by AEnterprise** [comment]
most likely it's BC not returning true in canEmitRedstone(side)

**Comment by SandGrainOne** [comment]
I'm unable to reproduce this issue with up to date versions of the mods. I do not have BuildCraftCompat at the moment, but I do not think it is involved with this specific interaction.

Please update mods and test again.
