### ISSUE TITLE
Multiple integration recipes using the same input itemstack

### ISSUE THREAD

**Issue by iTitus** [BuildCraft/BuildCraft#2981]
Currently it is not possible to use two separate integration table recipes. One is prioritized.
I am trying to add two recipes which only differ in the expansions. It will be difficult to compress that down (but possible)
Is this the intended behaviour?

**Comment by hea3ven** [comment]
Yes, it's one recipe per main input item, but you can return a different output depending on the expansions that are passed in.

**Comment by AEnterprise** [comment]
yeah, it is tricky but possible, still need to rewrite the BCA kinetic multitool stuff to work with it fully

**Comment by iTitus** [comment]
That is what I am trying to do now @AEnterprise . Because the Stick integration should require a stick and a chipset and the upgrade integration only requires an upgrade, the NEI recipe handler crashes because BC(C)/NEI tries to put the upgrade and the chipset together which crashes beacuse the recipe returns null

**Comment by iTitus** [comment]
For now I will just make them all require only the stick/upgrade

**Comment by AEnterprise** [comment]
yeah tried that before, the sytem needs a full rewrite, sadly real life kicked in then, though if you wana talk about this more, make a BCA issue, this isn't the best place to discuss those things

**Comment by asiekierka** [comment]
This is intentional.
