### ISSUE TITLE
Emerald Item Pipe Crash

### ISSUE THREAD

**Issue by sfchipan** [BuildCraft/BuildCraft#2982]
When emerald item pipe extract items. 7.1.2 beta
https://www.dropbox.com/s/x71mygp220dsbd6/crash-2015-08-22_08.35.27-server.txt?dl=0

**Comment by dj3520** [comment]
Having the same crash loading my single player test world, which has a lot
of emerald pipes.

**Comment by asiekierka** [comment]
https://github.com/BuildCraft/BuildCraft/commit/0353b8c15c831f3c57a1197a2c9b715c04295e5d
