### ISSUE TITLE
Engine 'work' when no fuel

### ISSUE THREAD

**Issue by sfchipan** [BuildCraft/BuildCraft#2983]
(7.1.2 beta)
When provide redstone signal to striling/combustion engine, it will start motion even if there's no fuel in them. They just don't produce energy actually.

**Comment by tambry** [comment]
@sfchipan Is this still an issue?

**Comment by asiekierka** [comment]
@tambry Only on 7.1.x which is going to get a lot of rewrites and refactors still, as the design plan for the future is not set in stone yet

**Comment by asiekierka** [comment]
Not relevant anymore.
