### ISSUE TITLE
Builder registering MineFactory Reloaded Blocks?

### ISSUE THREAD

**Issue by MKHenson** [BuildCraft/BuildCraft#2985]
Hi guys

Not sure if this the correct place to report the issue, but I created a structure using white stone bricks and plastic (MineFactory Reloaded blocks v2.8.0-104), and tried to get the buider to build this structure. After getting a blueprint with the architects table I place it in the builder. The builder does not register the whitestone bricks nor the plastic blocks (But it does for the regular minecraft blocks like glass or cobblestone). I think have the latest compat and buildcraft installed...

buildcraft-7.0.20.jar
buildcraft-compat-7.0.11.jar

Is this an issue to report?

**Comment by gjgfuj** [comment]
The builder doesn't register anything of which compatibility isn't
specifically specified if its a special block. Those... Don't sound like
special blocks though. But I'd assume it's just a case of there not yet
being compatibility for it.

**Comment by MKHenson** [comment]
Ah ok, thanks gjgfuj. Is there a list of special blocks I can use as a reference?

**Comment by gjgfuj** [comment]
Any block that's not a basic block. Blocks with tile entities. No idea why
mfr decorative things aren't but oh well. Most decorative things should
work.
