### ISSUE TITLE
I can't pick up robot after dock station demolition.

### ISSUE THREAD

**Issue by SakuraBloom** [BuildCraft/BuildCraft#2987]
![2015-08-22_15 41 21](https://cloud.githubusercontent.com/assets/13917494/9424007/aaf27fd8-48e4-11e5-9935-084dc03d0e32.png)

Robots simply slowly falling on the ground and nothing else happens.
Bug or there is new method to collect robots from the ground?

[Sorry for my english].

[Forestry]
[RailCraft]
[DivineRPG]

**Comment by hea3ven** [comment]
Shift+right click it with a wrench to pick it up.

**Comment by SakuraBloom** [comment]
Oh..Thank a lot. So simpl..
