### ISSUE TITLE
Pipes decreate FPS

### ISSUE THREAD

**Issue by mimic2300** [BuildCraft/BuildCraft#2988]
Hello.
Please can you better optimize the pipes? I created a larger factory, where are more pipes and drastic decrease of FPS after approach to building. And it was not much, about 30 machines connected via a pipes.

**Comment by asiekierka** [comment]
BC 7.0+ is optimized to the point where I don't think I can make the
*pipes* optimized further. They should lag no more than a set of chests, or
something.

2015-08-22 20:24 GMT+02:00 mimic <notifications@github.com>:

**Comment by SandGrainOne** [comment]
Also remember that you added a lot more than pipes. You added 30 machines and probably a lot of other things as well.

**Comment by AEnterprise** [comment]
can you show us the setup in the area (here or on the forums), maybe we can see if something is going on there that would cause this that can be fixed

**Comment by gjgfuj** [comment]
Is rendering of pipes optimized? Or just the tps?

**Comment by asiekierka** [comment]
Both. BC's pipes have just about the least complex model one could possibly
make and still have it look like a pipe; on top of that, almost everything
is an ISBRH (except a gate's dynamic part, that is the front face).

2015-08-23 11:34 GMT+02:00 Sandra <notifications@github.com>:

> Is rendering of pipes optimized? Or just the tps?
>

**Comment by ganymedes01** [comment]
If there's a lot of items travelling through the pipes at the same time it could affect your FPS quite badly, after all, the items inside the pipes are rendered the same way items dropped on the floor are.

How about opaque pipes? Could have them adjust automatically depending on the client's quality settings. Just a thought...

**Comment by asiekierka** [comment]
They are, but Graphics: Fast optimizes both. Also, we have limits on how
many items in one pipe can render.

2015-08-24 19:41 GMT+02:00 ganymedes01 <notifications@github.com>:
