### ISSUE TITLE
Fluid extraction pipe extract ic2 kinetic steam generator's distilled water infinitely

### ISSUE THREAD

**Issue by sfchipan** [BuildCraft/BuildCraft#2989]
https://youtu.be/sVSGA1yC1oI
7.1.2 beta and 7.0.21
I'm not sure if this is the IC's issue. And after reloading the save world, the distilled water in generator had been consumed. But the total extraction fluid that had been extracted by BC pipes still more than 1000mB.

**Comment by asiekierka** [comment]
IIRC, that's IC2's fault.
