### ISSUE TITLE
Robots take suffocation and drowning damage

### ISSUE THREAD

**Issue by Meow-J** [BuildCraft/BuildCraft#2995]
![test](https://cloud.githubusercontent.com/assets/5229241/9542015/d6fc9eaa-4d9f-11e5-9173-3fb9cca2e5f4.gif)

Robots are actually losing energy instead of taking actual damage(I know this part is intended).  
Buildcraft version: 7.1.2 beta

**Comment by tambry** [comment]
@Meow-J I haven't worked on BC in a long time, but what would be the correct behaviour? Them only losing energy?

**Comment by asiekierka** [comment]
They do not know how to react to damage yet at all.
