### ISSUE TITLE
[Feature Request]IGW (In-Game Wiki) support

### ISSUE THREAD

**Issue by soulgriever** [BuildCraft/BuildCraft#2997]
![2015-08-28_21 23 41](https://cloud.githubusercontent.com/assets/2360198/9559882/2321693e-4dcb-11e5-8a45-0422c23e0dea.png)
![2015-08-28_21 23 58](https://cloud.githubusercontent.com/assets/2360198/9559883/2323a6ea-4dcb-11e5-88d9-5d5948837c5d.png)
Wiki in game you can press I and view description of block you are looking at also good for explaining on how to use machines or tools such as book press
https://github.com/MineMaarten/IGW-mod

**Comment by Sandriell** [comment]
If you add support for it, please do not add (or supress it if you can) that annoying spam message every time you login if IGW isn't installed.

**Comment by simon816** [comment]
See #2595 and #2794
