### ISSUE TITLE
quarry breaking blocks it shouldn't break (maybe blacklist)

### ISSUE THREAD

**Issue by AEnterprise** [BuildCraft/BuildCraft#2998]
reported on the forums:
http://www.mod-buildcraft.com/forums/showthread.php?tid=1810&pid=17308#pid17308

quarry seems to break protected blocks, a blacklist would be an easy solution

**Comment by AlexIIL** [comment]
Can I assume this affects both BC versions? (7.0.x and 7.1.x)

**Comment by AEnterprise** [comment]
not sure, guy on the forum didn't specify that, didn't have time to test it myself

**Comment by AlexIIL** [comment]
It looks like it might be though, the quarry code hasn't changed by that much between versions (I'm going to try to add a way of automatically not breaking blocks that say they don't want to be broken.)

**Comment by AlexIIL** [comment]
Ok, I couldn't find a generic method to call to check if a block was protected (Although one might exist that I have missed), but I'm making a pull request now to implement a black list (That affects both the quarry and the mining well)
