### ISSUE TITLE
Fix all your getStackInSlotOnClosing

### ISSUE THREAD

**Issue by SoniEx2** [BuildCraft/BuildCraft#3005]
Like wtf? https://github.com/BuildCraft/BuildCraft/blob/6.5.x/common/buildcraft/robotics/EntityRobot.java#L696-L699

See also ModCoderPack/MCPBot-Issues#32

**Comment by asiekierka** [comment]
That's the correct behaviour in EntityRobot, you know? Think.

**Comment by SoniEx2** [comment]
But it's inconsistent with `getStackInSlot(i)` followed by `setInventorySlotContents(i, null)`!

**Comment by hea3ven** [comment]
Yeah, var1 is supposed to be the slot number, splitting the stack in the inventory by it is weird. That said, no one should call this method, and even more, now that I think about it, there may be some of the robot boards assume they have complete control over the robot's inventory and might break if you forcefully add/remove stacks from it.

**Comment by asiekierka** [comment]
@hea3ven - wait, that's the slot number!? okay that's a bug then wow

**Comment by asiekierka** [comment]
Fixed. Not bothering to mention in changelog as nobody will hit this ever.

**Comment by SoniEx2** [comment]
I think you forgot to updateClientSlot...?
