### ISSUE TITLE
Pipe wire does not activate when connecting by building through striped pipe

### ISSUE THREAD

**Issue by Sp3rw3r** [BuildCraft/BuildCraft#3010]
I build a pipe with a striped pipe. On the striped pipe is a pipe wire.
Another pipe has active pipe wire.
Once the stripe pipe connects with the pipe with active wire, the wire on the striped pipe does not update.

**Comment by Sp3rw3r** [comment]
https://youtu.be/nVHwJl3B1sU

**Comment by asiekierka** [comment]
Most likely will be fixed by complete accident during the BC 7.1/7.2 pipe
wire rewrite.

2015-09-13 16:17 GMT+02:00 Sp3rw3r <notifications@github.com>:
