### ISSUE TITLE
Packager pulls from input only slots from adjacent machines

### ISSUE THREAD

**Issue by Sp3rw3r** [BuildCraft/BuildCraft#3015]
When a packager has a blank slot in the crafting grid, it pulls from any adjacent inventory.
I think it should only pull from the output slots of adjacent machines.

It also has this behavior when the slot is not blank but matches. Maybe sloppy but doesn't produce unexpected results.

**Comment by asiekierka** [comment]
It is meant to pull from all adjacent inventories, including chests. Why?

2015-09-12 23:50 GMT+02:00 Sp3rw3r <notifications@github.com>:

**Comment by Sp3rw3r** [comment]
Suppose I want to craft torches and put a packager next to an oven that is creating the coal I wouldn't expect it to pull the wood from it.

**Comment by Sp3rw3r** [comment]
Hoppers wouldn't take those items either.
Nor does the extraction pipe. 
I think a packager only should take items that a hopper or extraction pipe would take.

**Comment by AEnterprise** [comment]
i see what is heapening, it is looping through all slots, it should first check witch slots are available from that side

**Comment by asiekierka** [comment]
@AEnterprise - that's not it; I found out that the Packager actually reads from the side *opposite* it, rather than the side facing it. Fixed.
