### ISSUE TITLE
Version 7.0.20. Can't find a 'Crafter' Robot.

### ISSUE THREAD

**Issue by SakuraBloom** [BuildCraft/BuildCraft#3025]
This robot was added to BC so long before, but i can;t find it in game. Even "Programming Table' do not offer me a "Crafter" chip to create.

Bug or my mistake?

Sorry for my english.

**Comment by asiekierka** [comment]
Was removed in 7.0.x due to having serious design flaws.

**Comment by SakuraBloom** [comment]
Is it goind to appear in future?

**Comment by asiekierka** [comment]
Unlikely.

2015-09-20 21:50 GMT+02:00 SakuraBloom <notifications@github.com>:
