### ISSUE TITLE
Filler bug? 

### ISSUE THREAD

**Issue by Uzumachi02** [BuildCraft/BuildCraft#3026]
https://www.youtube.com/watch?v=j9e5hh4OsGQ

**Comment by asiekierka** [comment]
That's amazing. Definitely a bug, but could be a nice easter egg...

Dnia 21 wrz 2015 o godz. 13:40 Uzumachi02 <notifications@github.com> napisał(a):

**Comment by Kubuxu** [comment]
It was nice building block. ;p
