### ISSUE TITLE
0.23: Crash in ticking world entities  java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by sylphio** [BuildCraft/BuildCraft#3028]
Hi, since my last update, the server crash ~ once per 1-2 hours while ticking entities.

https://gist.githubusercontent.com/sylphio/f0fd7dfef0c6b42d4aa4/raw/3832755587c478f578e0d678e867db20a1574c8c/Crash1

The only recently updated mod are buildcraft and opencomputer. 
(This is on a live server i cannot remove a mod to do testing.)

The server crash often when i am around my base who is really heavy in BC pipe.

buildcraft related?

**Comment by asiekierka** [comment]
Try with BC 7.0.24. (Also, this crash can be caused by other mods too. It's
really hard to debug.)

2015-09-21 20:08 GMT+02:00 sylphio <notifications@github.com>:
