### ISSUE TITLE
robot lumberjack - bug?

### ISSUE THREAD

**Issue by utel** [BuildCraft/BuildCraft#3030]
Hi)
buildcraft-7.0.25 and forestry_1.7.10-4.0.0.705

1) when the robot lumberjack cuts trees of Forestry - logs do not fall
2) robot lumberjack does not work with coastal Sequoia and giant Sequoia

Thanks)

**Comment by asiekierka** [comment]
Should work now? Can someone check on 7.1.16?

**Comment by AEnterprise** [comment]
no info given that says this isn't fixed

can be closed

**Comment by AlexIIL** [comment]
^

But feel free to re-open this if you come across it again.

**Comment by AEnterprise** [comment]
if you close it they can't re-open, but they can make a new issue or just comment here to have it re-opened
