### ISSUE TITLE
[1.7.10][7.0.24][7.0.25] mcmod.info file included in 0.24 and 0.25 is malformed and prevents loading on Forge 1448

### ISSUE THREAD

**Issue by Aedda** [BuildCraft/BuildCraft#3034]
I've been trying to track down this issue for a couple days. I originally installed the individual modules Buildcraft|Core 7.0.23 and Buildcraft|Energy 7.0.23 to gain access to oil wells. This worked fine until updating to 0.24 where Forge reported things were missing when trying to load my world. I downgraded and everything was fine.

7.0.25 had the same issue, I noticed in the Forge log for both 24 and 25 the following error:

```
[18:13:03] [Client thread/DEBUG] [FML/]: Examining file buildcraft-7.0.25-core.jar for potential mods
[18:13:03] [Client thread/TRACE] [FML/]: Located mcmod.info file in file buildcraft-7.0.25-core.jar
[18:13:03] [Client thread/WARN] [FML/]: Zip file buildcraft-7.0.25-core.jar failed to read properly, it will be ignored
java.lang.NullPointerException
	at cpw.mods.fml.common.MetadataCollection.parseModMetadataList(MetadataCollection.java:88) ~[MetadataCollection.class:?]
```

After some googling I learned this is caused by a malformed mcmod.info file, typically a modid mismatch. I compared the mcmod.info files in 24 and 25 to 23 and the most obvious difference is 23 ships with a mcmod.info file covering all BC modules (as ships in the complete package) whereas 24 and 25 are specific to their module.

Other than manually deleting the mcmod.info files from 24 and 25 I have been unable to resolve this issue.

fml-client-latest.log: http://pastebin.com/MaQ1HGSP

**Comment by AEnterprise** [comment]
sounds like the script used to compile the different modules got broken

**Comment by iTitus** [comment]
@Thog ?

**Comment by iTitus** [comment]
Or maybe @QORTEC ?

**Comment by QORTEC** [comment]
looking into it right now

**Comment by QORTEC** [comment]
There needs to be a square bracket at the begging and end of the mcmod.info file. ````[  ]````

Fixing the script now, will submit pull request when tested.

**Comment by Thog** [comment]
@iTitus My changes have been made in the 7.1.x branch

**Comment by iTitus** [comment]
Sorry man ;) It's all fixed now

**Comment by asiekierka** [comment]
I'm so sorry for this. Releasing update on the blog right now.
