### ISSUE TITLE
Server crash when I try to load up

### ISSUE THREAD

**Issue by djoveryde** [BuildCraft/BuildCraft#3038]
I'm unsure what's causing this problem but on startup I'm getting an nbt error from buildcraft which crashes the server. http://pastebin.com/RH7rxFyg

**Comment by XFactHD** [comment]
It seems that your world got damaged pretty badly. Try rolling back to a back-up if you can.

**Comment by djoveryde** [comment]
Figured it out, had to delete the buildcraft folder that was inside the world folder, seems that got corrupted for some reason :(
