### ISSUE TITLE
Font error with Buildcraft and AE2

### ISSUE THREAD

**Issue by mdfntr** [BuildCraft/BuildCraft#3040]
When loading a fresh instance of Minecraft with just Buildcraft and AE2 installed, I get the following error with fonts:

<img width="966" alt="screen shot 2015-09-26 at 12 07 11 am" src="https://cloud.githubusercontent.com/assets/9371833/10116259/2f66929a-63e3-11e5-84d2-73b5992afa5c.png">

Details:
Minecraft 1.7.10
Forge 10.13.4.1448
AE2 rv2-stable-10
Buildcraft 7.0.25

Log: https://paste.ee/p/5NyLN

AppliedEnergistics/Applied-Energistics-2#1916

**Comment by mdfntr** [comment]
Confirmed to happen with Forge 10.13.4.1492, as well.

**Comment by AEnterprise** [comment]
does it also heapen with only forge installed?

**Comment by loordgek** [comment]
try disabling the forge loading screen

**Comment by mdfntr** [comment]
This does not happen with only Forge 10.13.4.1448.

After disabling the Forge loading screen, the issue is resolved.

Are there any guesses as to why these two mods alone cause an issue with the loading screen but a larger collection of mods (Infinity, DW20, etc.) that includes AE and Buildcraft do not?

**Comment by mdfntr** [comment]
Once the loading screen's `splash.properties` configuration file is present, there are no issues whether the loading screen is enabled or not. See AppliedEnergistics/Applied-Energistics-2#1916 for more comments. It's silly that the lack of an auto-generated config file causes such a problem...
