### ISSUE TITLE
Pump doesn't pump everything

### ISSUE THREAD

**Issue by Zaflis** [BuildCraft/BuildCraft#3052]
The pump is leaving some spots of lava in the world.

Example: http://imgur.com/oDceYNg

buildcraft-7.0.25, buildcraft-compat-7.0.12
(I see 7.1.6 was released 23 hours ago, i'll give a comment if i can get to test it with that too. Changelog doesn't mention pump exactly.)

**Comment by Forecaster** [comment]
Are you sure they're really source blocks? That is that there are lava blocks there you can pick up with a bucket?

**Comment by Zaflis** [comment]
Yes. Also pump was just behind me few blocks away, and the lava was filling the entire tunnel earlier 2 blocks high. I was standing next to it as "chunkloader" while watching youtube :p  And you can see the other bigger lava source still sticking out from the back wall. Pump should have drained them too.

**Comment by asiekierka** [comment]
I think the pump only pumps out blocks it can reach, and it cannot magically pump "up", or defy gravity.

**Comment by Zaflis** [comment]
The pump generally follows the pattern where if it's given a lava flow, it will follow the flow to the source block even if it's above the flow itself. It works like this now and always have. It's just these random spots it's now missing out. These lava sources were definitely within its range, since it's almost within same chunk.

**Comment by dj3520** [comment]
I can actually say that it does not do this. A player on my server had set
up a pump in the nether. It went straight down, making a one block sized
hole, only pumping out source blocks. Though IIRC it was back in 1.6.4

**Comment by Zaflis** [comment]
It's definitely not making a one block sized hole, you need to screenshot that if you can prove. It will make more like a crater if you pump a lava ocean in nether.

I don't remember it being bugged before even in 1.7.10 so it's propably something recent. It's not entirely closed out that it's another mod's fault either if it relates to worldgen.

**Comment by AEnterprise** [comment]
sounds like the MC bug where sometimes flowing lava blocks don't get removed even though there is no more source block

can be closed

**Comment by AlexIIL** [comment]
^

But feel free to re-open this if you encounter it again.
