### ISSUE TITLE
Question about getting dev builds from maven

### ISSUE THREAD

**Issue by liach** [BuildCraft/BuildCraft#3053]
http://files.minecraftforge.net/maven/com/mod-buildcraft/buildcraft
On forge maven there is only buildcraft 6.4.16. Where can I get maven dev builds of buildcraft 7.x?

**Comment by asiekierka** [comment]
Use the instructions on the repo to add BC to your Gradle project.

2015-10-04 6:22 GMT+02:00 liach <notifications@github.com>:

**Comment by liach** [comment]
Thx

**Comment by asiekierka** [comment]
What are you working on that's BC-related, by the way? Just curious.

2015-10-04 8:10 GMT+02:00 liach <notifications@github.com>:
