### ISSUE TITLE
Robot shutting down for no reason

### ISSUE THREAD

**Issue by Wykks** [BuildCraft/BuildCraft#3054]
Using Buildcraft 7.1.7 & Buildcraft compat 7.1.1
(Forge 10.13.4.1492)

My setup : 
Simple wood farm : 3 picker, 3 planter, 3 lumberjack
Configured with a zone planner
3 docking station for each. Only one station for energy.

And another similar setup : 
1 picker, 1 harvester
Configured with a zone planner
3 docking station for each. Only one station for energy.

/!\ These setup are not chunkloaded when i'm not connected.

Same issues for both of them, server log regulary say that : 

    [BuildCraft]: Robot with id %d was not unregistered properly
    [BuildCraft]: A robot entity was not properly unloaded
    [BuildCraft]: Robot with id %d was not unregistered properly
    [BuildCraft]: Shutting down robot EntityRobot['Robot'/9526155, l='world', x=-26,05, y=63,75, z=1088,00] - wrong docking station

When I reconnect my robot are "dead" and I have to manually re-place them on their station :(

**Comment by asiekierka** [comment]
Are you using Cauldron?

**Comment by Wykks** [comment]
No, not this time :)

**Comment by Wykks** [comment]
If I keep the robot area chunloaded, everything works fine

**Comment by dj3520** [comment]
Could you try this setup again, but have each home station be an energy
providing one? I do this myself every time and don't have issues.

**Comment by Wykks** [comment]
It's definitly related to chunk loading stuff.
After multiple test, only the robot that left the chunk loaded area shut down to "dead" status. (With the same error in the server log)

**Comment by TheQuantumGeneral** [comment]
Also seem to be having this issue, robots just randomly dying and sinking into their pipes. Area is always chunkloaded, all stations provide power.  
![2015-11-07_10 04 45](https://cloud.githubusercontent.com/assets/7843312/11010958/78ef745c-8537-11e5-8533-106049aa8f19.png)
![2015-11-07_10 05 02](https://cloud.githubusercontent.com/assets/7843312/11010959/78f181ac-8537-11e5-95b0-f597c2d570c6.png)

**Comment by seajay1221** [comment]
Having this issue as well. Area is fully chunkloaded by Railcraft's World Anchor. Robots disappear and I receive BuildCraft Shutting down robot EntityRobot['Robot'/10394, l='world', x=14.51, y=43.20, z=1023.62] - wrong docking station errors in the server log.

**Comment by dj3520** [comment]
Not seeing this with the newest version myself. Can you try upgrading and
testing on a new world?

**Comment by AEnterprise** [comment]
old issue with outdated BC that most likely fixed and neighter of them provided any info that says otherwise

**Comment by AlexIIL** [comment]
^

Feel free to re open this if you encounter this with the latest version though.
