### ISSUE TITLE
Updating AoA to 2.4.10H causes Buildcraft to crash the server with the following report

### ISSUE THREAD

**Issue by aking4125** [BuildCraft/BuildCraft#3057]
Updating AoA (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286381-aoa-21-new-dimensions-330-mobs-27-bosses-600-items) to the latest build on the server side causes this crash when a user joins the server. When the affected blocks are removed using McEdit. The world works but all modded blocks are corrupted or broken. AoA dev says it's a buildcraft issue. Any ideas? Upgrading to Buildcraft 7 causes a crash with Forestry and I have no idea why, updating forestry to any version still causes that crash.

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 10/1/15 12:28 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
at buildcraft.transport.TileGenericPipe.func_145845_h(TileGenericPipe.java:360)
at buildcraft.transport.TileGenericPipeCompat.func_145845_h(TileGenericPipeCompat.java:85)
at net.minecraft.world.World.func_72939_s(World.java:2513)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at buildcraft.transport.TileGenericPipe.func_145845_h(TileGenericPipe.java:360)
at buildcraft.transport.TileGenericPipeCompat.func_145845_h(TileGenericPipeCompat.java:85)

-- Block entity being ticked --
Details:
Name: net.minecraft.src.buildcraft.transport.GenericPipe // buildcraft.transport.TileGenericPipeCompat
Block type: ID #581 (tile.pipeBlock // buildcraft.transport.BlockGenericPipeCompat)
Block data value: 0 / 0x0 / 0b0000

Block location: World: (-150,52,263), Chunk: (at 10,3,7 in -10,16;
contains blocks -160,0,256 to -145,255,271), Region: (-1,0; contains
chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Actual block type: ID #581 (tile.pipeBlock // buildcraft.transport.BlockGenericPipeCompat)
Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:2513)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
Level name: world

All players: 1 total; [EntityPlayerMP['blueking4125'/1708, l='world',
x=-138.19, y=74.00, z=257.93](blueking4125 at
-138.1886389914068,74.0,257.9325574212939)]
Chunk stats: ServerChunkCache: 470 Drop: 0
Level seed: -343452314079336738
Level generator: ID 08 - default_1_1, ver 0. Features enabled: true
Level generator options:

Level spawn location: World: (-156,64,448), Chunk: (at 4,4,0 in -10,28;
contains blocks -160,0,448 to -145,255,463), Region: (-1,0; contains
chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Level time: 184143876 game time, 22789748 day time
Level dimension: 0
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 27376 (now: false), thunder time: 79975 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
Minecraft Version: 1.7.10
KCauldron Version: pw.prok:KCauldron:1.7.10-1492.152
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_60, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 4220132744 bytes (4024 MB) / 6845104128 bytes (6528 MB) up to 7635730432 bytes (7282 MB)
JVM Flags: 2 total; -Xmx8192M -Xms4096M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 11, tcache: 0, allocated: 15, tallocated: 95
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 136 mods loaded, 136 mods active

States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' =
Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available
'D' = Disabled 'E' = Errored
UCHIJAAAA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
UCHIJAAAA FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1492.152-server.jar)
UCHIJAAAA Forge{10.13.4.1492} [Minecraft Forge] (KCauldron-1.7.10-1492.152-server.jar)
UCHIJAAAA kimagine{0.1} [KImagine] (minecraft.jar)
UCHIJAAAA appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar)
UCHIJAAAA Aroma1997Core{1.0.2.14} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.14.jar)
UCHIJAAAA CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar)
UCHIJAAAA ImmibisMicroblocks{59.1.1} [Immibis's Microblocks] (immibis-microblocks-59.1.1.jar)
UCHIJAAAA ivtoolkit{IvToolkit} [1.0.3] (minecraft.jar)
UCHIJAAAA NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal.jar)
UCHIJAAAA <CoFH ASM>{000} [CoFH ASM] (minecraft.jar)
UCHIJAAAA <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar)
UCHIJAAAA mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar)
UCHIJAAAA gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util.jar)
UCHIJAAAA lotr{Beta v23.3 for Minecraft 1.7.10} [The Lord of the Rings Mod] ([1.7.10] The Lord of the Rings Mod B23.3.jar)
UCHIJAAAA bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar)
UCHIJAAAA FloatingRuins{1.7.10.r02} [FloatingRuins] ([1.7.10]FloatingRuins-universal-1.7.10.r02.jar)
UCHIJAAAA StartingInventory{1.7.10.r03} [StartingInventory] ([1.7.10]StartingInventory-universal-1.7.10.r03.jar)
UCHIJAAAA Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar)
UCHIJAAAA CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar)
UCHIJAAAA BuildCraft|Core{6.4.15} [BuildCraft] (buildcraft-6.4.15.jar)
UCHIJAAAA BuildCraft|Factory{6.4.15} [BC Factory] (buildcraft-6.4.15.jar)
UCHIJAAAA BuildCraft|Transport{6.4.15} [BC Transport] (buildcraft-6.4.15.jar)
UCHIJAAAA BuildCraft|Silicon{6.4.15} [BC Silicon] (buildcraft-6.4.15.jar)
UCHIJAAAA additionalpipes{3.4} [Additional Pipes] (additionalpipes-3.4.jar)
UCHIJAAAA aether{Alpha 1.7.10-1.4} [Aether II] (aether.jar)
UCHIJAAAA AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar)
UCHIJAAAA nevermine{2.3} [AdventOfAscension] (AoA-2.4.10H.jar)
UCHIJAAAA appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar)
UCHIJAAAA Aroma1997CoreHelper{1.0.2.14} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.14.jar)
UCHIJAAAA AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar)
UCHIJAAAA atum{0.6} [Atum] (Atum-1.7.10-0.6.60.jar)
UCHIJAAAA BattleTowers{1.5.1} [Battle Towers] (BattleTowers-1.7.10.jar)
UCHIJAAAA BiblioCraft{1.11.2} [BiblioCraft] (BiblioCraft[v1.11.2][MC1.7.10].jar)
UCHIJAAAA ExtrabiomesXL{3.16.2} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.2.jar)
UCHIJAAAA BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition] (BiblioWoods[ExtraBiomesXL][v1.4].jar)
UCHIJAAAA HardcoreEnderExpansion{1.8.3} [Hardcore Ender Expansion] (HardcoreEnderExpansion MC-1.7.10 v1.8.3.jar)
UCHIJAAAA Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar)
UCHIJAAAA Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar)
UCHIJAAAA Forestry{3.6.3.20} [Forestry for Minecraft] (forestry_1.7.10-3.6.3.20.jar)
UCHIJAAAA BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar)
UCHIJAAAA BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar)
UCHIJAAAA BuildCraft|Builders{6.4.15} [BC Builders] (buildcraft-6.4.15.jar)
UCHIJAAAA BuildCraft|Energy{6.4.15} [BC Energy] (buildcraft-6.4.15.jar)
UCHIJAAAA BuildCraft|Compat{6.4.0} [BuildCraft Compat] (buildcraft-compat-6.4.2.jar)
UCHIJAAAA CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar)
UCHIJAAAA ChickenChunks{1.3.4.17} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.17-universal.jar)
UCHIJAAAA TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar)
UCHIJAAAA chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar)
UCHIJAAAA ChiselFacades{1.7.10-2.11-cricket} [Chisel Facades] (ChiselFacades-1.7.10-2.11-cricket.jar)
UCHIJAAAA Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar)
UCHIJAAAA chiseltones{@VERSION@} [Chisel Tones] (ChiselTones-1.7.10-1.0-1.jar)
UCHIJAAAA chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar)
UCHIJAAAA MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
UCHIJAAAA Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar)
UCHIJAAAA ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar)
UCHIJAAAA ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar)
UCHIJAAAA Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar)
UCHIJAAAA TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar)
UCHIJAAAA DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V9a.jar)
UCHIJAAAA ChromatiCraft{1.0} [ChromatiCraft] (ChromatiCraft 1.7.10 V9a.jar)
UCHIJAAAA colourfulportalsmod{1.4.2} [Colourful Portals] (ColourfulPortals-1.4.2_for_1.7.X.jar)
UCHIJAAAA cookiecore{1.3.0} [Cookie Core] (cookiecore-1.3.0.jar)
UCHIJAAAA craftingpillars{1.6.0} [Crafting Pillars Mod] (CraftingPillars-1.7.x-1.6.1.jar)
UCHIJAAAA customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar)
UCHIJAAAA DeadlyWorld{1.0.2} [Deadly World] (DeadlyWorld-1.7.10-1.0.2.jar)
UCHIJAAAA PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.1_1.7.10.jar)
UCHIJAAAA props{2.1} [Decocraft] (Decocraft-2.1_1.7.10.jar)
UCHIJAAAA DLDungeonsJBG{1.6.3} [Doomlike Dungeons] (DoomlikeDungeons-1.6.3-MC1.7.10.jar)
UCHIJAAAA divinerpg{1.4.1.1} [DivineRPG] (DRPG 1.4.1.4.jar)
UCHIJAAAA dungeonpack{1.7.10-1.0} [Dungeon Pack] (dungeonpack-1.7.10-1.0.jar)
UCHIJAAAA eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar)
UCHIJAAAA endercore{1.7.10-0.0.1.13_alpha} [EnderCore] (EnderCore-1.7.10-0.0.1.13_alpha.jar)
UCHIJAAAA EnderStorage{1.4.7.36} [EnderStorage] (EnderStorage-1.7.10-1.4.7.36-universal.jar)
UCHIJAAAA eternalfrost{2.0b4} [Eternal Frost] (eternalfrost-2.0b6.jar)
UCHIJAAAA ExtraUtilities{1.2.6} [Extra Utilities] (extrautilities-1.2.6.jar)
UCHIJAAAA MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar)
UCHIJAAAA Metallurgy{4.0.8} [Metallurgy 4] (Metallurgy-1.7.10-4.0.8.97.jar)
UCHIJAAAA TSteelworks{1.7.10-1.0.7} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.0.7.jar)
UCHIJAAAA ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar)
UCHIJAAAA CARuins{0.1.7} [Cellular Automata Generator] (Generatormods-0.1.7(1.7.10).jar)
UCHIJAAAA GreatWallMod{0.1.7} [Great Wall Mod] (Generatormods-0.1.7(1.7.10).jar)
UCHIJAAAA WalledCityMod{0.1.7} [Walled City Generator] (Generatormods-0.1.7(1.7.10).jar)
UCHIJAAAA GeoStrata{1.0} [GeoStrata] (GeoStrata 1.7.10 V9a.jar)
UCHIJAAAA ImmibisCore{59.1.2} [Immibis Core] (immibis-core-59.1.2.jar)
UCHIJAAAA inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar)
UCHIJAAAA JourneyMapServer{1.0.5_MC1.7.10} [JourneyMapServer] (JourneyMapServer1.0.5_MC1.7.10.jar)
UCHIJAAAA LavaMonsters{2.2.1} [Lava Monsters] (LavaMonsters-1.7.10-2.2.1.jar)
UCHIJAAAA Mimicry{1.7.x_1067_1.0.4} [Mimicry] (Mimicry-1.7.x_1067_1.0.4a.jar)

UCHIJAAAA MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0}
[MFR Compat: Applied Energistics]
(MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
UCHIJAAAA MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)

UCHIJAAAA MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR
Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)

UCHIJAAAA MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR
Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)

UCHIJAAAA MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR
Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)

UCHIJAAAA MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR
Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
UCHIJAAAA MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)

UCHIJAAAA MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR
Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
UCHIJAAAA MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)

UCHIJAAAA MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR
Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
UCHIJAAAA MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)

UCHIJAAAA MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR
Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)

UCHIJAAAA MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR
Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)

UCHIJAAAA MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR
Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)

UCHIJAAAA MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR
Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)

UCHIJAAAA MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR
Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)

UCHIJAAAA MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR
Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
UCHIJAAAA MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
UCHIJAAAA MobProperties{0.4.0} [Mob Properties] (MobProperties-1.7.10-0.4.0.jar)
UCHIJAAAA NEIAddons{1.12.11.36} [NEI Addons] (neiaddons-1.12.11.36-mc1.7.10.jar)
UCHIJAAAA NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools] (neiaddons-1.12.11.36-mc1.7.10.jar)
UCHIJAAAA NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.11.36-mc1.7.10.jar)
UCHIJAAAA NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany] (neiaddons-1.12.11.36-mc1.7.10.jar)
UCHIJAAAA NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry] (neiaddons-1.12.11.36-mc1.7.10.jar)
UCHIJAAAA NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables] (neiaddons-1.12.11.36-mc1.7.10.jar)
UCHIJAAAA NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo] (neiaddons-1.12.11.36-mc1.7.10.jar)
UCHIJAAAA neiintegration{1.0.11} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.11.jar)
UCHIJAAAA newdungeons{0.3} [New Dungeons] (NewDungeons-0.3(1.7.10).jar)
UCHIJAAAA clayspawn{1.7.2a} [Pam's Clay Spawn] (Pam's Clay Spawn 1.7.2a.zip)
UCHIJAAAA RadixCore{2.0.1} [RadixCore] (RadixCore-2.0.1-1.7.10-universal.jar)
UCHIJAAAA reccomplex{0.9.3.1} [Recurrent Complex] (RecurrentComplex-0.9.3.1.jar)
UCHIJAAAA RedLogic{59.1.11} [RedLogic] (redlogic-59.1.11.jar)
UCHIJAAAA Roguelike{1.3.5} [Roguelike Dungeons] (roguelike-1.7.10-1.3.5.jar)
UCHIJAAAA AS_Ruins{14.7} [Ruins Spawning System] (Ruins-1.7.10.jar)
UCHIJAAAA SolarExpansion{1.6a} [Solar Expansion] (SolarExpansion-Basic-1.6a.jar)
UCHIJAAAA SpecialMobs{3.1.1} [Special Mobs] (SpecialMobs-1.7.10-3.1.1.jar)
UCHIJAAAA TerritoryZone{1.0} [TerritoryZone] (TerritoryZone 1.7.10 V9a.jar)
UCHIJAAAA elysium{1.0} [The Elysium] (TheElysium-1.7.x-1.0.3.jar)
UCHIJAAAA erebus{0.2a} [Erebus] (TheErebus-0.2b.jar)
UCHIJAAAA ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar)
UCHIJAAAA TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar)
UCHIJAAAA VoidMonster{1.0} [Void Monster] (VoidMonster 1.7.10 V9a.jar)
UCHIJAAAA WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar)
UCHIJAAAA wailaplugins{MC1.7.10-0.1.0-16} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.1.0-16.jar)
UCHIJAAAA WaslieCore{1.1} [WaslieCore] (WaslieCore-1.1_B44.jar)
UCHIJAAAA wawla{1.3.1} [What Are We Looking At] (Wawla-1.3.1-1.7.10.jar)
UCHIJAAAA redgear_core{2.2.0} [Red Gear Core] (RedGearCore-1.7.10-2.2.0.jar)
CoFHCore: -[1.7.10]3.0.3-303
AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
MineFactoryReloaded: -[1.7.10]2.8.0-104
ThermalFoundation: -[1.7.10]1.2.0-102
ThermalExpansion: -[1.7.10]4.0.3B1-218
TConstruct Environment: Environment healthy.
ThermalDynamics: -[1.7.10]1.1.0-161

Forestry : Warning: You have mods that change the behavior of
Minecraft, ForgeModLoader, and/or Minecraft Forge to your client:
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.

AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON,
RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON,
Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used

Player Count: 1 / 30; [EntityPlayerMP['blueking4125'/1708, l='world',
x=-138.19, y=74.00, z=257.93](blueking4125 at
-138.1886389914068,74.0,257.9325574212939)]
Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
Type: Dedicated Server (map_server.txt)

**Comment by asiekierka** [comment]
You need to get the latest Forestry 3.6 (NOT 4.0), THEN BuildCraft 7, THEN BuildCraft Compat, and THEN it should work fine.

**Comment by aking4125** [comment]
That didn't 100% fix the problem. Now all modded blocks are corrupted and switched around destroying the entire world.

**Comment by asiekierka** [comment]
That's Forge's problem, not ours - go report it to them or restore from a
backup.

2015-10-05 3:18 GMT+02:00 Angel Rodriguez <notifications@github.com>:
