### ISSUE TITLE
Sound file repeating

### ISSUE THREAD

**Issue by mgwerner** [BuildCraft/BuildCraft#3059]
Since updating to 7.1.8, I have constant repetition of the sound file of a tool being used.  I have tried to track it to a machine, then shut down all machines, repetition continues.  Sound file is that of a wrench being used in the crafting bench.  I have placed sound mufflers, no effect.  Sound file is heard in multiple dimensions, regardless of activity - running, walking, standing still - all changes have no effect.  Sound plays at random times, no set interval.

**Comment by asiekierka** [comment]
Have you updated anything else? Have you tried downgrading? What version have you upgraded from? Are there any other things you had done?

...Do you have ThaumCraft Warp? (Silly question, I know, but couldn't resist asking it)

Dnia 5 paź 2015 o godz. 11:46 mgwerner <notifications@github.com> napisał(a):

**Comment by mgwerner** [comment]
Downgraded, no sound.  Had upgraded a few other things, but downgraded them as well and left them out.  No thaumcraft, only tech mods.  Upgraded from 7.1.7.

**Comment by asiekierka** [comment]
I checked twice, I touched nothing possibly related between 7.1.7 and 7.1.8. Odd.

**Comment by mgwerner** [comment]
With a bit more playing around, it seems that I get the "wrench" sound whenever a job in a machine is completed.  I missed the update I did a few days back with IC2 Experimental, I think the issue is with that, not with BC.  Sorry for the trouble, and thanks for the response and help in troubleshooting.
