### ISSUE TITLE
Server crash with land marks

### ISSUE THREAD

**Issue by ENeMy235** [BuildCraft/BuildCraft#3060]
Hi, I found, when I placed landmarks and I tried to click on them, server crashed. BC 7.1.6
And when player came to minig world, server crash too.
Here is crash report to 2nd crash - http://pastebin.com/XXW4bkEC

**Comment by asiekierka** [comment]
Crash log?

2015-10-05 21:43 GMT+02:00 ENeMy235 <notifications@github.com>:

**Comment by ENeMy235** [comment]
Landmark problem: http://pastebin.com/ERqF0Peq
Quarry near player problem: http://pastebin.com/XXW4bkEC

**Comment by asiekierka** [comment]
Both were fixed in 7.1.7.
