### ISSUE TITLE
Can't automate the Filler...

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [BuildCraft/BuildCraft#3061]
So I'm trying to use the filler together with botania. Now botania has a flower, munchie, that eats leaves blocks.

I use the BC filler to fill an area full of leave blocks. Meanwhile, the botania flowers start eating the flower blocks. The filler is still filling. Once if fills the area, it stops working, but the botania flowers still eat the blocks.
 
After that the botania flowers have eaten all the blocks, but the filler has stopped operation. How can I make it continuously or periodically fill an area?

**Comment by LuigiHutch** [comment]
See: https://github.com/BuildCraft/BuildCraft/issues/2268

**Comment by Unrepentant-Atheist** [comment]
Oh, I see. Seems to be an old bug or something.

**Comment by asiekierka** [comment]
"Bug". Rather an inability to decide on a solution.

**Comment by dj3520** [comment]
Have you tried a gate with Work done = Loop?

**Comment by Unrepentant-Atheist** [comment]
Yea, I have. Gate seems to work fine.
