### ISSUE TITLE
Cant pump Buildcraft Oil with Pump

### ISSUE THREAD

**Issue by Hackling92** [BuildCraft/BuildCraft#3063]
I can not pump buildcraft oil from an oil spring with the pump in version 7.1.8, however it works in version 7.1.6.  However this version has a server sided crash bug that is fixed in the later versions.  Just to be clear I can pump other mods oils as well as any other fluid.  However when trying to pump from a buildcraft oil spring the pump does nothing, it does not even lower the pipe.

**Comment by asiekierka** [comment]
I did not touch any pump or oil-related code in 7.1.7 or 7.1.8.

Perhaps something else is involved?

**Comment by Hackling92** [comment]
It seems to only be a multiplayer bug I will keep testing and let you know what I find tomorrow hopefully.

**Comment by asiekierka** [comment]
Try "/buildcraft op" if you are the server owner

2015-10-07 6:47 GMT+02:00 Jacob Wilkes <notifications@github.com>:

**Comment by Hackling92** [comment]
Still didnt change anything.  It only refuses to pump bc oil any other fluid including several other types of oil work fine.  I am going to start removing mods tonight in a test world to see if any of them are the culprit.  If you were curious the pump dose not even lower its spout when over bc oil.

**Comment by Hackling92** [comment]
Whatever it is does not seem to be mod dependent.  I tried a fresh world on the same server and it works fine.  So I guess something in my world file got corrupted.

**Comment by AEnterprise** [comment]
do you have pneumaticcraft installed?

**Comment by Hackling92** [comment]
I do but disabling it seems to have no effect.

**Comment by psxlover** [comment]
Are you sure that was buildcraft oil and not some other kind of liquid that looked like oil?

**Comment by AEnterprise** [comment]
can you try updating your pneumaticcraft if you're not using the latest version? i know there where some bugs with those fluids

**Comment by Hackling92** [comment]
I am currently running the latest pneumaticcraft, and it is definitely buildcraft oil.  I can even place fresh build craft oil from creative mode and it still wont pump it.  It seems to have corrupted something in just that world file, so I dont no whats up with that.  I am not terribly worried about it worse case I will just clear all of the chunks around my house and move the rest to a new world.

**Comment by asiekierka** [comment]
Sending me the world + modpack could work.

**Comment by Hackling92** [comment]
I will try to get it uploaded on friday, its been a bit of a hectic week for me.

**Comment by Potsukin** [comment]
Same issue was happened to me too. Pump water works fine though. I am currently running buildcraft-7.1.11 and PneumaticCraft-1.7.10-1.11.18-140

**Comment by SandGrainOne** [comment]
Please test the last release of PneumaticCraft.
