### ISSUE TITLE
Refactor Engine code

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildCraft#3064]
Right now it's a hacky mess of hacks, causing random bugs to pop up during refactors.

**Comment by AEnterprise** [comment]
outdated milestone, rendering has been redone already and i think the functional code has been worked on as well for 8.0

**Comment by AlexIIL** [comment]
I haven't touched engines much for 8.0.x yet @AEnterprise :P

Although it will probably be redone anyway.
