### ISSUE TITLE
Allow right-clicking on a pipe to waterproof it

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildCraft#3066]
Thanks, Forecaster!

**Comment by AEnterprise** [comment]
maybe also alow clicking redstone on it?

**Comment by Kubuxu** [comment]
Is there should be a way to take it off then, I can see many situations when someone accidentally right-clicks pipe. Maybe make it at least Shift-right-click

**Comment by BlaCoiso** [comment]
We could right click to put, shift right click with a wrench to take it

**Comment by AEnterprise** [comment]
is this still planned? if so the milestone needs updating

**Comment by AlexIIL** [comment]
I'm not too fond of this tbh. But perhaps It will be reconsidered later in the BC 8 dev cycle.
