### ISSUE TITLE
when 1.8 

### ISSUE THREAD

**Issue by hamhamfreak** [BuildCraft/BuildCraft#3070]
when is buildcraft 1.8 compatable

**Comment by Unrepentant-Atheist** [comment]
The fuck are you doin'? That ain't an issue.

**Comment by AEnterprise** [comment]
there probably won't be any official migration to mc 1.8 but there is a unofficial port on available on the forums
http://mod-buildcraft.com/forums/showthread.php?tid=1853

**Comment by asiekierka** [comment]
why do you need 1.8 so much

use et futurum and fastcraft

1.8 is buggy slow and generally not fun playing on
