### ISSUE TITLE
Make pipes inherit some of the facade's resistance

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildCraft#3076]
As suggested by Forecaster.

**Comment by AEnterprise** [comment]
is this still planned? if so what to do with advanced facades?

**Comment by AlexIIL** [comment]
Advanced facades? What are they?

(And yes this is planned as a "thing that would be good")

**Comment by AEnterprise** [comment]
facades with multiple states depending on pipe wires but if you don't know about them i guess they got lost in the port?

they are a great feature that sadly alot of people don't know about

**Comment by dj3520** [comment]
I've never forgot about them since I learned about them. I think they're not very popular since their use cases aren't very numerous. I'd still be sad if they left.
[BuildCraft Tutorial: Phased Facades](https://www.youtube.com/watch?v=T39c5NPSy0E)

**Comment by AlexIIL** [comment]
I knew about phased facades, I just didn't think of them when you said advanced facades :P.

Also phased facades ARE in the 1.8.9 version, and I have no plans to remove them.

**Comment by dj3520** [comment]
Are advanced facades different from phased?

**Comment by AEnterprise** [comment]
originally we called them advanced facades instead of phased :p 

i usually use them when i hide pipes with faces, give them a 2nd glass state so i can just flip a lever and i can see exactly where i left all my pipes and where i can hook into
