### ISSUE TITLE
Fix integration width MineTweaker3 please!

### ISSUE THREAD

**Issue by Tsyklop** [BuildCraft/BuildCraft#3077]
https://github.com/stanhebben/MineTweaker3/issues/264

https://github.com/stanhebben/MineTweaker3/issues/221

**Comment by iTitus** [comment]
I think you need to report that [here](https://github.com/BuildCraft/BuildcraftCompat/issues).

**Comment by Tsyklop** [comment]
https://github.com/BuildCraft/BuildcraftCompat/issues/41 

Already ... but no one answers.

**Comment by kotasc3** [comment]
Just be patient, just because someone doesn't answer instantly does not mean you have to open a new issue or spam the issue tracker

**Comment by LuigiHutch** [comment]
And you did have the issue closed for like a month :/

**Comment by Tsyklop** [comment]
@LuigiHutch nobody answered ..

**Comment by asiekierka** [comment]
If an issue is closed, we don't look at it - we assume that there is no
problem.

You've had it closed from the day it was opened to 5 hours ago. This is the
first time I saw it. Seriously.

2015-10-14 11:41 GMT+02:00 Tsyklop <notifications@github.com>:

**Comment by Tsyklop** [comment]
@asiekierka Ok. Sorry. But Refinery dont work
