### ISSUE TITLE
I can not remove the recipe Gasoline from Refinery

### ISSUE THREAD

**Issue by Tsyklop** [BuildCraft/BuildCraft#3078]
Ok. I can not remove the recipe Gasoline from Refinery using MineTweaker 3.

Script: `mods.buildcraft.Refinery.removeRecipe(liquid:fuel);`

Error in chat: 

[Client thread/INFO]: [CHAT] ERROR: Recipes - Thermal Expansion - Fluid Transoser.zs:17 > No such static member in mods.buildcraft.Refinery: removeRecipe

[Client thread/INFO]: [CHAT] ERROR: Error executing Recipes - Thermal Expansion - Fluid Transoser.zs: minetweaker/api/liquid/ILiquidStackAny

Prior to that, I have not answered.

**Comment by asiekierka** [comment]
https://github.com/BuildCraft/BuildcraftCompat/pull/42

**Comment by Tsyklop** [comment]
@asiekierka But mods.buildcraft.Refinery.remove(liquid:fuel); dont working to....
