### ISSUE TITLE
Critical! Memory leak

### ISSUE THREAD

**Issue by MySt1k** [BuildCraft/BuildCraft#3080]
http://pastebin.com/dQ6Q7dt0
buildcraft-7.1.8

**Comment by KyeDuo** [comment]
BC is now up to 7.1.11, update and try to reproduce.

**Comment by MySt1k** [comment]
yes  :(

http://pastebin.com/PwvB7azv

**Comment by psxlover** [comment]
I doubt that's a memory leak. How much memory have you allocated for minecraft?

**Comment by MySt1k** [comment]
2GB

**Comment by MySt1k** [comment]
The problem arises if the approach to the site with the mechanisms and pipes ... just can not say, as if the customer hangs fly up close and get this error

**Comment by AEnterprise** [comment]
this isn't a memory leak at all
```
[18:00:10] [Client thread/ERROR] [FML/]: There was a critical exception handling a packet on channel BC-CORE
java.lang.OutOfMemoryError: Java heap space
```

increase the ram (and with that heap size) allocated to MC and it should work, java is just running out of memory

**Comment by MySt1k** [comment]
@AEnterprise This is repeated for all, even the one allocated more than 4 GB of RAM

**Comment by MySt1k** [comment]
P.S
Before BuildCraft upgrade to 7.1. *, this was not

**Comment by AEnterprise** [comment]
did you try increasing the permagen memory then? that could also trigger this error

**Comment by MySt1k** [comment]
@AEnterprise PermGen not work on java 8

**Comment by psxlover** [comment]
You should post your fml.log.
Also make sure you are using a 64-bit Java.

**Comment by MySt1k** [comment]
https://www.dropbox.com/s/hyqg1e070mgjo2l/fml-client-latest.log?dl=0
http://joxi.ru/nAyXkK4ckJZw2Z.jpg

**Comment by AEnterprise** [comment]
alright eighther java 8 is derping up it's heap size or there is a bug in the BC networking code where it tries to read read data from the message buffer that isn't there

**Comment by MySt1k** [comment]
I fell back to version 7.0.23, and this problem is not there, this is clearly a mistake versions 7.1. *

**Comment by asiekierka** [comment]
Alright, I shall look into it.

**Comment by XFactHD** [comment]
@AEnterprise permgen space was removed in java 8.

**Comment by AEnterprise** [comment]
@XFactHD i didn't know he was using java 8, doesn't matter anyways as i suspect there is something wrong with a gate sync package

**Comment by XFactHD** [comment]
@AEnterprise no problem, just as an information because you thought that java had derped. 😊

**Comment by DPxKnightxZero** [comment]
Confirmed has to do with the bots. I noticed after taking a sample while the mod was present there is a process leak that takes about 40 mins to be really visible.

**Comment by CitiesXL2815** [comment]
I was having the same problem, created new world in single player and it say [shutting down internal server] a fetal error occurred and I minimal down the version and still happens

**Comment by DPxKnightxZero** [comment]
Okay so this has a massive memory leak feel free to fix it. Let me know when its dealt with.

**Comment by ShadowT1me** [comment]
When you are near with robot, server will begin sending packets, but client can`t read them. And so will continue till memory is run out :)

**Comment by tambry** [comment]
Might be worth attaching a profiler (such as JProfiler or others) and seeing, what's leaking the memory.

**Comment by MySt1k** [comment]
@tambry At me won't leave any more. I on the old version and a place where occurred leakage of memory is already forgotten

**Comment by tambry** [comment]
@MySt1k Well, I was suggesting that for those, who are investigating or looking into fixing the memory leak.

**Comment by DPxKnightxZero** [comment]
I can take a profile snapshot if it pleases the court :D

**Comment by asiekierka** [comment]
Re-open if anything new pops up.
