### ISSUE TITLE
emzuli pipe bug

### ISSUE THREAD

**Issue by KyeDuo** [BuildCraft/BuildCraft#3081]
I can't get emzuli pipes to work anymore.
I updated to 7.1.11 and it stopped working.
I have the items set properly, a trigger for allowing the extraction of the color and an energy pulsar.
I know it isn't the side of the singularity compressor as a regular wooden pipe works.
This is currently killing a setup I have for refilling IC2 blast furnaces with compressed air cells.
I've tried robots, but they seem to like to either randomly drop them, or the pipes spit them out because they went in the wrong way.

**Comment by asiekierka** [comment]
I partially fixed Emzuli pipes in 7.1.11, but I did it wrong. Will fix again in 7.1.12.
