### ISSUE TITLE
Disabling the item variant but not the non-item variant of a pipe causes recipe crash

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildCraft#3083]
http://pastebin.com/gCrS09Wt

**Comment by oldjunyi** [comment]
Another crash issue related with pipe recipe:

Disabling the pipe lens in object.cfg and checking the assembly recipes (in NEI) that can be crafted with lapis (or other dyes) will crash the game.
https://gist.github.com/oldjunyi/2e75ba8b631a1e9d48d0
