### ISSUE TITLE
Block Rendering Crash

### ISSUE THREAD

**Issue by JasonMcRay** [BuildCraft/BuildCraft#3084]
http://pastebin.com/aJcnXWyH - Not sure what causes the crash. Player of Infitech 2 has reported this:
> I encountered this crash when leaving the Client running for a few hours.

No idea how to recreate it. Do you have any ideas what can be a cause of it?

It happened with BC7.1.8. so if it is fixed in later versions, sorry about the report :)

**Comment by AEnterprise** [comment]
seems like MC crashed when trying to get a TE out of the world, odd

**Comment by asiekierka** [comment]
Might be fixed in later versions, but we do have a config option to disable it if it still crashes.

Dnia 17 paź 2015 o godz. 21:04 Jason McRay <notifications@github.com> napisał(a):

**Comment by JasonMcRay** [comment]
May I ask in which place is the config option or how is it named so I can tell the player who is crashing?

**Comment by asiekierka** [comment]
If 7.1.11 did not solve it, it's general.useServerDataOnClient
