### ISSUE TITLE
Delivery Robots AI downgrade sine 7.1.9

### ISSUE THREAD

**Issue by dj3520** [BuildCraft/BuildCraft#3085]
Recently upgraded from 7.1.9 to 7.1.11 and saw issues with Delivery robots immediately.
I have quite a few requests being handled via quartz gates and worked perfectly on 7.1.9 (downgraded and working now as well)
Robots will end up dead (no charge), throwing items, refusing docking plates, etc.
Haven't checked other kinds of robots yet.
[Full Mods list](http://net.dj3520.net:8000/minecraft/modlist.btm)

**Comment by Sp3rw3r** [comment]
Other robots have issues too. Lumbejack can't find trees in working area.

**Comment by dj3520** [comment]
Persists in 7.1.12
Planter does not plant saplings. Picker does not pick up dropped items. Tested same world with 7.1.12 & 7.1.9, working as expected in the latter.

**Comment by dj3520** [comment]
Seemingly working in 7.1.13
Will report if back if I'm wrong.
