### ISSUE TITLE
Robots getting stuck on docking stations in certain directions

### ISSUE THREAD

**Issue by Amelia-** [BuildCraft/BuildCraft#3087]
My robots are getting stuck on docking stations that are facing down, west or north when they dock on them. Placing them on a docking station that is facing one of those directions will make also make it so the robot just sits there and does nothing. Having a robot on a docking station on the same pipe in one of the three directions that do work (up, east or south) will work just fine.

This is with Buildcraft 7.1.11.

Another problem I've noticed is if a robot is on a docking station that is facing down that I cannot pick up the robot with a wrench. This works fine for docking stations facing all other directions.

**Comment by Unknown-Zombie** [comment]
You're right. I've spent the last four hours banging my head on the desk trying to figure out why I couldn't get my robots to work. I kept moving them around to different stations and wasn't getting consistent behavior out of them, and I couldn't figure out why.

This is completely right, though. Any robot placed on a docking port that is on one of these sides of a pipe will never leave that docking port.

**Comment by SubliminallySublime** [comment]
I'd like to 3rd this. North, Bottom and West Directions are broken. The robots do not ever move, and eventually fall off the station and become inactive! The other directions work extremely reliably however.

**Comment by Unknown-Zombie** [comment]
This issue is still occurring in 7.1.12 for me

**Comment by Amelia-** [comment]
For me as well. I've tried breaking and replacing the existing docking stations and pipes the robots were on but they still won't move from docking stations on the directions that I first reported.

**Comment by Unknown-Zombie** [comment]
No, you can't reopen it. Normally an administrator would receive a notification that this issue is still getting replies, check them, and they would reopen it if appropriate.
