### ISSUE TITLE
Miner robots do not use the enchantments placed on the tool they are using

### ISSUE THREAD

**Issue by Amelia-** [BuildCraft/BuildCraft#3088]
I noticed that if I put either Silk Touch or Fortune on a pickaxe and have a miner robot use this pickaxe to mine that the effect of the enchant is not applied. I didn't test with Unbreaking or Efficiency because those are a little harder to test.
I don't know if it is even intended for them to be able to benefit from the effects of enchanted tools but if it is intended then it is not working properly.

There are also a few other issues with the robots when you make them use tools from Redstone Arsenal but that is another discussion. I only mention it here because I'm not really sure where to start a discussion about that and this is a little related or perhaps someone can tell me where to discuss that?

I am using Buildcraft 7.1.11.

**Comment by AEnterprise** [comment]
if you want to discuss things that are not realy a bug report feel free to open a thread on the forum: http://www.mod-buildcraft.com/forums/index.php

as for the enchantments stuff i think they should eighter apply the enchants or not use the enchanted tools at all

**Comment by Amelia-** [comment]
Thank you, I'll start a discussion there.

And for the enchantments, I agree with your view on that.
