### ISSUE TITLE
Robots delete repairable tools after they break.

### ISSUE THREAD

**Issue by Unknown-Zombie** [BuildCraft/BuildCraft#3090]
When a robot is using a tool that may normally be repaired after it breaks (such as those from Tinkers' Construct), the robot will delete the tool once it has broken.

The robot should be smarter about these types of items, and put them into a chest so that they may be repaired.

**Comment by asiekierka** [comment]
Is there a way to check this in a mod-independent manner?

**Comment by AEnterprise** [comment]
not sure, i also think it might be a good idea to call the item update function when in the robot's inventory though for self-reparing tools
