### ISSUE TITLE
Problems between PMC oil and BC oil

### ISSUE THREAD

**Issue by Potsukin** [BuildCraft/BuildCraft#3094]
I am playing PneumaticCraft about a year, then tried to install BuildCraft about a week ago. BC pump doesn't recognize BC oil. I tried to fill BC oil with bucket to Thermal Expansion Creative Portable Tank, it works, then I can not fill PMC oil to Portable tank. Then I made Superflat world which do not have PMC oil lake underground, tried to make BC oil lake with WorldEdit, BC pump works, but I can not fill PMC oil to the tank, PMC gas lift do not work.
It seems that
1. if PMC oil is available in-world, BC pump will not work
2.If BC oil is available in-world, PMC gas lift will not work

Versions:
PneumaticCraft-1.7.10-1.11.18-140-universal
buildcraft-7.1.11

**Comment by SandGrainOne** [comment]
There was a new PneumaticCraft release 3. November. (1.7.10-1.11.19-141). It should contain a fix that I hope will solve your issue.
