### ISSUE TITLE
Lumberjack unable to chop logs BC 7.1.12

### ISSUE THREAD

**Issue by Unknown-Zombie** [BuildCraft/BuildCraft#3095]
My Lumberjack robot is no longer able to chop trees down in 7.1.12. Using vanilla or TCon tools it will move to a log, and once there just kind of hover back and forth while swinging the axe; it will never break the log.

**Comment by Amelia-** [comment]
What kind of tree are they trying to cut down?
I have my robots working on a tree farm with red maple trees from Forestry or Extra Trees and they work just fine. They use vanila stone axes.

**Comment by Unknown-Zombie** [comment]
They are trying to chop down Cypress Trees from EBXL. In 7.1.11 they were cutting the trees down fine with vanilla or TCon axes. After updating they won't cut the trees down with either tool. (It's worth noting that I'm playing Regrowth, and vanilla tools are nerfed for players).

After downgrading to 7.1.11 they are able to cut the trees again with either tool.

**Comment by Unknown-Zombie** [comment]
My lumberjack robot is unable to chop down even vanilla trees with TCon or Vanilla tools.

Here's a video of what he is doing:
https://www.youtube.com/watch?v=-WncWv2vLyA

**Comment by Amelia-** [comment]
That looks just like what my lumberjack robot did when I tested it with a Flux Infuxed axe while the axe was empowered on Buildcraft 7.1.11. Perhaps one of the mods in your modpack does something with it?

**Comment by Unknown-Zombie** [comment]
I don't think so. The tools tested were a vanilla stone axe and a plain TCon hatchet that had a flint head, wooden handle, and no modifiers.

**Comment by Sp3rw3r** [comment]
I had same issue in 7.11. Maybe to do with pathing. Because sometimes when starting with another tree it would chop down the one it has trouble with after.
Also reloading the world sometimes makes the lumberjack work a while like it should.

**Comment by dj3520** [comment]
have you done /buildcraft op?

**Comment by Unknown-Zombie** [comment]
`/buildcraft op` command did not help.

**Comment by asiekierka** [comment]
Swinging back and forth means it's trying to break a block, failing to do so, moving to the nearest block, trying to break that, failing again, and then moving to the nearest block from that block (which is usually the one it tried to break before). In other words, *something* is blocking the robot from breaking. But what?

**Comment by Unknown-Zombie** [comment]
I've noticed that _sometimes_ Quitting to Title screen and going back into the world will allow him to break 1 block, but then get stuck when trying to break the next block. Doesn't work every time, though.

**Comment by SecretSnake55** [comment]
Hello I know it is a bit late six days late lol 
do you have another mod installed like multimine?
I use that mod and I have noticed that sometimes when chopping wood if I stop chopping before it breaks and then continue chopping it will break but it leaves an invisible block that does not show up I realize this when I tried replanting a sampling and it would not grow when I re-log back in I found that one piece of log floating in the air so maybe that is your trouble and invisible block worth checking out hope that it helps.

**Comment by Unknown-Zombie** [comment]
No, I don't have Multimine or anything like it installed.

**Comment by dj3520** [comment]
Are all of the other robots working? Particularly block breaking ones.

**Comment by asiekierka** [comment]
@Unknown-Zombie Regrowth blocks vanilla tools from working. We did not check for that earlier, but with the tool handling improvements in recent BuildCraft versions, we do.
