### ISSUE TITLE
Minecraft Crash Report Fix Needed Help

### ISSUE THREAD

**Issue by CrossAvenger** [BuildCraft/BuildCraft#3098]
When Using Buildcraft (7.1) With these Other Mods Minecraft Crashes on World Gen:
Applied Energistics 2 core, Applied Energistics 2, code chicken core, NEI, Open mods core, CoFH core, Baubles, Thermal Expansion, Thermal Foundation, Thermal Dynamics, Big Reactors, Biomes O' plenty, Thaumcraft, Botania, Twilight forest, Chisel 2, Computer Craft, Ender IO, Extra Utilities, Forestry For Minecraft, Journey Map Mantle, Minefactory Reloaded, Walia, Tinkers' Construct, Open Blocks, Veinminer
Crash Report: 
Crash Log Taken From Minecraft Launcher:
---- Minecraft Crash Report ----
// Don't do that.
Time: 10/25/15 3:16 PM
Description: Exception in server tick loop
java.lang.NoSuchMethodError: buildcraft.api.core.JavaTools.getAllFields(Ljava/lang/Class;)Ljava/util/List;
at buildcraft.api.mj.MjAPI.getMjBatteryField(MjAPI.java:196)
at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:85)
at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:55)
at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:46)
at buildcraft.api.power.PowerHandler.<init>(PowerHandler.java:159)
at buildcraft.api.power.PowerHandler.<init>(PowerHandler.java:145)
at crazypants.enderio.power.PowerHandlerUtil.createHandler(PowerHandlerUtil.java:62)
at crazypants.enderio.machine.AbstractMachineEntity.<init>(AbstractMachineEntity.java:86)
at crazypants.enderio.machine.AbstractMachineEntity.<init>(AbstractMachineEntity.java:185)
at crazypants.enderio.machine.AbstractPoweredTaskEntity.<init>(AbstractPoweredTaskEntity.java:26)
at crazypants.enderio.machine.alloy.TileAlloySmelter.<init>(TileAlloySmelter.java:35)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at java.lang.Class.newInstance(Unknown Source)
at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:104)
at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496)
at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78)
at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_65, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 502003848 bytes (478 MB) / 1318060032 bytes (1257 MB) up to 2863661056 bytes (2731 MB)
JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 21, tcache: 0, allocated: 12, tallocated: 97
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1517 59 mods loaded, 59 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
UCHIJAA FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
UCHIJAA Forge{10.13.4.1517} [Minecraft Forge] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
UCHIJAA appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
UCHIJAA CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
UCHIJAA NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
UCHIJAA VeinMiner_coremod{0.21.2_build-43} [Core mod] (minecraft.jar) 
UCHIJAA OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
UCHIJAA <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
UCHIJAA appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
UCHIJAA CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
UCHIJAA Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
UCHIJAA ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
UCHIJAA ThermalExpansion{1.7.10R4.0.0} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0-176.jar) 
UCHIJAA BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
UCHIJAA BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1396-universal.jar) 
UCHIJAA Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
UCHIJAA Botania{r1.7-226} [Botania] (Botania r1.7-226.jar) 
UCHIJAA BuildCraft|Core{7.1.12} [BuildCraft] (buildcraft-7.1.12.jar) 
UCHIJAA BuildCraft|Builders{7.1.12} [BC Builders] (buildcraft-7.1.12.jar) 
UCHIJAA BuildCraft|Transport{7.1.12} [BC Transport] (buildcraft-7.1.12.jar) 
UCHIJAA BuildCraft|Energy{7.1.12} [BC Energy] (buildcraft-7.1.12.jar) 
UCHIJAA BuildCraft|Silicon{7.1.12} [BC Silicon] (buildcraft-7.1.12.jar) 
UCHIJAA BuildCraft|Robotics{7.1.12} [BC Robotics] (buildcraft-7.1.12.jar) 
UCHIJAA BuildCraft|Factory{7.1.12} [BC Factory] (buildcraft-7.1.12.jar) 
UCHIJAA TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
UCHIJAA chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
UCHIJAA ComputerCraft{1.74} [ComputerCraft] (ComputerCraft1.74.jar) 
UCHIJAA EnderIO{1.7.10-2.0.5.214} [Ender IO] (EnderIO-1.7.10-2.0.5.214.jar) 
UCHIJAA ExtraUtilities{1.2.11} [Extra Utilities] (extrautilities-1.2.11.jar) 
UCHIJAA Forestry{4.0.10.39} [Forestry for Minecraft] (forestry_1.7.10-4.0.10.39.jar) 
UCHIJAA journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited.jar) 
UCHIJAA Mantle{1.7.10-0.3.2.jenkins188} [Mantle] (Mantle-1.7.10-0.3.2a.jar) 
UCHIJAA MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
UCHIJAA TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
UCHIJAA MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
UCHIJAA OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
UCHIJAA OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
UCHIJAA ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
UCHIJAA VeinMiner{0.21.2} [Vein Miner] (VeinMiner-1.7.10_0.21.2.43.jar) 
UCHIJAA VeinMinerModSupport{0.21.2} [Mod Support] (VeinMiner-1.7.10_0.21.2.43.jar) 
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
Class transformer null safety: all safe
AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
CoFHCore: -[1.7.10]3.0.3-303
ThermalFoundation: -[1.7.10]1.2.0-102
ThermalExpansion: -[1.7.10]4.0.0-176
Mantle Environment: Environment healthy.
MineFactoryReloaded: -[1.7.10]2.8.0-104
TConstruct Environment: Environment healthy.
ThermalDynamics: -[1.7.10]1.1.0-161
Stencil buffer state: Function set: GL30, pool: forge, bits: 8
AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Player Count: 0 / 8; []
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by dj3520** [comment]
Think one of those mods have an outdated Buildcraft API. You can single it
out by starting with only Buildcraft and one other mod on a new world.
Start adding then in one by one until you crash again.

**Comment by AEnterprise** [comment]
yeah it's looking for MJ so definatly one of your mods is seriously outdated or shiping a realy old api

**Comment by CrossAvenger** [comment]
So i went through every Mod and re-installed it, but all on a new world.The New World loaded fine, with no apparent issues. But the first world, once again, crashed on the loading screen. I've come to the conclusion that this world is somehow faulty or there is some kind of conflict between mods that i haven't found. Thanks for the help.

**Comment by AEnterprise** [comment]
@CrossAvenger this shouldn't be an world issue but a mod issue, my guess is that it will crash again once you start placing machines, as the mod probably isn't accessing the api till a block is in the world

**Comment by CrossAvenger** [comment]
Yes you're right. it seems i inadvertently removed the problem from the world by destroying all of the Ender IO pipes. You're correct, because when i tried to place an Ender IO pipe the world crashed. But i simply removed the mod and now everything seems to work fine. Thank goodness i made world backups though. Thanks again for the help.

**Comment by AEnterprise** [comment]
@CrossAvenger update ender io to the latest version then, if it's still crashes then report it there, they shouldn't be shiping an that old api
