### ISSUE TITLE
Incompatibility with SecurityCraft.

### ISSUE THREAD

**Issue by Geforce132** [BuildCraft/BuildCraft#3100]
A player has brought to my attention that whenever a security camera/monitor from my mod is setup in the same chunk with a facade block (it looks like) from BuildCraft, this crash occurs: http://pastebin.com/cv2zcPKf

Any idea what it could be?

I'll leave a link to SecurityCraft's github repo if you want to check it out: https://github.com/Geforce132/SecurityCraft

**Comment by AEnterprise** [comment]
is securitycraft doing anything special with rendering?

**Comment by asiekierka** [comment]
It's an easy to fix NPE.
