### ISSUE TITLE
Disabled items still 'craftable' but crash the game

### ISSUE THREAD

**Issue by MidnightsFX** [BuildCraft/BuildCraft#3102]
Attempting to craft a recipe for anything that is in the config and set to 'false' results in a null pointer exception. The recipe is still detected as a valid recipe but results in a null item. NEI etc ignore the recipe, but creating the recipe in the crafting grid will result in a crash

crash....
http://pastebin.com/YB6XccRa

this was detected by Hardcore Ender Expansion...
`[13:56:10] [Client thread/ERROR] [FML/]: Caught exception from HardcoreEnderExpansion
java.lang.RuntimeException: A defective recipe has crashed the game! Another mod is creating recipes with non-existent blocks or items, which is a serious error that will cause item or even world loss when crafting these recipes. Corrupted recipes have been saved in the log with tag [HEE-ORB], please try to find which mod they belong to and report them to the respective modder. Then enable the 'overrideRemoveBrokenRecipes' option in Hardcore Ender Expansion and the game will start.`

`[13:56:05] [Client thread/ERROR] [HardcoreEnderExpansion/HardcoreEnderExpansion]: [HEE-ORB] Corrupted shaped ore recipe: <error:null> <= {[minecraft]item.dyePowder/0(ore), [BuildCraft|Core]tile.markerBlock/32767, [minecraft]item.dyePowder/0(ore), [minecraft]item.dyePowder/11(ore), [minecraft]tile.workbench/32767, [minecraft]item.dyePowder/11(ore), [BuildCraft|Core]item.diamondGearItem/0(ore), [minecraft]tile.chest/32767, [BuildCraft|Core]item.diamondGearItem/0(ore)}`

`[13:56:05] [Client thread/ERROR] [HardcoreEnderExpansion/HardcoreEnderExpansion]: [HEE-ORB] Corrupted shaped ore recipe: <error:null> <= {<empty>, [minecraft]item.ingotIron/0(ore), <empty>, [minecraft]item.ingotIron/0(ore), [minecraft]tile.workbench/0(ore), [minecraft]item.ingotIron/0(ore), <empty>, [minecraft]tile.pistonBase/32767, <empty>}`

`[13:56:05] [Client thread/ERROR] [HardcoreEnderExpansion/HardcoreEnderExpansion]: [HEE-ORB] Corrupted shaped ore recipe: <error:null> <= {[minecraft]item.ingotIron/0(ore), [minecraft]item.redstone/0(ore), [minecraft]item.ingotIron/0(ore), [BuildCraft|Core]item.goldGearItem/0(ore), [minecraft]item.emptyMap/0, [BuildCraft|Core]item.goldGearItem/0(ore), [minecraft]item.ingotIron/0(ore), [BuildCraft|Core]item.diamondGearItem/0(ore), [minecraft]item.ingotIron/0(ore)}`

`[13:56:05] [Client thread/ERROR] [HardcoreEnderExpansion/HardcoreEnderExpansion]: [HEE-ORB] Corrupted shaped ore recipe: <error:null> <= {[minecraft]item.ingotIron/0(ore), [minecraft]tile.pistonBase/32767, [minecraft]item.ingotIron/0(ore), [BuildCraft|Core]item.ironGearItem/0(ore), [minecraft]tile.chest/0(ore), [BuildCraft|Core]item.ironGearItem/0(ore), [minecraft]item.ingotIron/0(ore), [minecraft]item.redstone/0(ore), [minecraft]item.ingotIron/0(ore)}`

Config
http://pastebin.com/WFvh7aQ0

**Comment by psxlover** [comment]
Are you sure the client has the same config as the server?

**Comment by MidnightsFX** [comment]
This was in single player. So the configs were the same, I can check on a
server if you would like?
