### ISSUE TITLE
Robots returning to home station when colliding with certain things

### ISSUE THREAD

**Issue by Amelia-** [BuildCraft/BuildCraft#3103]
I've noticed for a while now that my robots return to their home station when they collide or intersect with some things. Examples of these are Forestry saplings, brick walls from Railcraft, torches, ender lillies and probably many more things I've not ran into yet.

It seems to happen mostly to picker robots when they want to pick up an item that is in the same block space as one of those things.
The pickers will just attempt to pick up the item, fail because they intersect with the thing that is also on the block and then return home. As soon as they get home they will fly back for another attempt and keep repeating until the item they are trying to pick up despawns.

The brick walls are only a problem for the picker robots when an item drops in the same block space. The other robots don't have anything to do with them and will just avoid and fly over them as they should.

I'm using Buildcraft 7.1.12.

**Comment by asiekierka** [comment]
Should be fixed in 7.1.13. Sort of.
