### ISSUE TITLE
I can‘t open the GUI of Architect Table from BC7.1.12

### ISSUE THREAD

**Issue by Antecer** [BuildCraft/BuildCraft#3105]
Right click the Machine,It does not respond.

**Comment by asiekierka** [comment]
Did you define it an area?

**Comment by Antecer** [comment]
No,i just place it.

**Comment by asiekierka** [comment]
https://www.youtube.com/watch?v=VEj4CJ4DDlQ

**Comment by Antecer** [comment]
Thanks！but，i think ,it need message help.
