### ISSUE TITLE
Lumberjack robots don't recognize IC2 rubber trees.

### ISSUE THREAD

**Issue by TheQuantumGeneral** [BuildCraft/BuildCraft#3106]

**Comment by asiekierka** [comment]
Perhaps it's for the better. Lumberjacks don't use treetaps.

2015-10-31 10:22 GMT+01:00 The Quantum General <notifications@github.com>:

**Comment by TheQuantumGeneral** [comment]
Neither do I :P, industrial centrifuge the wood for sticky resin.

**Comment by TheQuantumGeneral** [comment]
Using forestry farms and IC2 crops for stickreed is a better workaround. FWIW.

**Comment by KKyang** [comment]
IC2 crops are not available in MC 1.8+. Neither do Forestry.

**Comment by AEnterprise** [comment]
@KKyang you are posting on a very old issue and the information is not realy relevant. Can you open a new issue if you have a bug with all the needed info?
