### ISSUE TITLE
Compatibility Request Ic2 Classic (Speiger) Gate triggers

### ISSUE THREAD

**Issue by Okkasionen** [BuildCraft/BuildCraft#3108]
Add gate triggers for example  the massfabricator, if ic2 Classic is  installed.
Thanks for reading

**Comment by LuigiHutch** [comment]
IC2 Classic already has gate triggers.

Tested With BC 7.1.12 and IC2 Classic 1.1.2.1

**Comment by Okkasionen** [comment]
Are you serious. I tried all of them and they dont work. Let it be the integration of railcraft , buildcraft ore forestry. I must have derped something pretty hard or The newest version of Ic2 classic broke it all down

**Comment by LuigiHutch** [comment]
What version of IC2 classic are you using? Its more likely to be IC2 Classics fault as the compat is added from their side.

**Comment by Okkasionen** [comment]
I AM DUMB !!! Sorry for posting i used immimbis port instead of speiger out of pure silliness
