### ISSUE TITLE
Fake player performance issue

### ISSUE THREAD

**Issue by TheAndrey** [BuildCraft/BuildCraft#3109]
I noticed lags on the server (5-6 TPS). Warmroast shows that a problem in TileQuarry. Why you use FakePlayer for destruction of blocks? Why it can't be done as it was in the previous versions - directly through setBlockToAir()?

![Screenshot](http://dl2.joxi.net/drive/0001/2623/92735/151103/aff578072d.png)

**Comment by 008** [comment]
ppl can grief if you dont use FakePlayer, WorldGuard

**Comment by TheAndrey** [comment]
@008 I added to a code a mode special Bukkit event. They are processed by only one plug-in. It considerably reduces loading and does to impossible grief regions where [buildcraft] is added to members. The plug-in looks who the owner of quarry and decides to give access or not. Here so it becomes :)

**Comment by hea3ven** [comment]
The quarry is not the one lagging there, it's whatever happens inside CraftEventFactory.callBlockBreakEvent that takes all of the time.

**Comment by TheAndrey** [comment]
@hea3ven The quarry uses FakePlayer which throws an event of destruction of the block. Why so to do if it is possible to break the block without use of the FakePlayer?
FakePlayer is necessary only where it is impossible to do without it. For example, in autoclickers which use items because the onItemUse() method demands object instance of EntityPlayer.

**Comment by hea3ven** [comment]
like @008 said, it isneeded to throw the BreakEvent, so that other mods can react acordingly to the blocks being broken.

**Comment by TheAndrey** [comment]
Only plug-ins think that the block is broken by the real player. And the fake breaks blocks much more often (if many quarries), than real players. Big load of the one-thread server turns out.

**Comment by Kubuxu** [comment]
This is recommended behaviour, expand this list further and think about reporting it to bukkit or plugin that causes the overhead.

**Comment by TheAndrey** [comment]
All my plug-ins are well optimized. In timings everything with plug-ins well. A problem that the event is fires too often. It in fact as additional players. The server is calculated on 100 slots, and 200+ players online turn out.

**Comment by Lunatrius** [comment]
```java
if (player instanceof FakePlayer) return;
```

**Comment by TheAndrey** [comment]
@Lunatrius Very bad example.

**Comment by asiekierka** [comment]
How many times is the BlockBreakEvent being done? VisualVM shows that, not
sure if WarmRoast does.

2015-11-03 18:04 GMT+01:00 Andrey <notifications@github.com>:

**Comment by TheAndrey** [comment]
@asiekierka 
![VisualVM](http://dl1.joxi.net/drive/0001/2623/92735/151103/ec69a5e748.png)

Essentials gc:
![Essentials gc](http://dl2.joxi.net/drive/0001/2623/92735/151103/3268ea0db7.png)

**Comment by Kubuxu** [comment]
You should be able to turn on column `samples` by right-clicking the bar and checking `samples`.

**Comment by TheAndrey** [comment]
@Kubuxu Thanks. Screenshot updated.

**Comment by Lunatrius** [comment]
How is my example bad? If you don't care about block updates caused by a fake player (machines etc), just skip them...

**Comment by asiekierka** [comment]
I doubt I can actually fix this, it's a plugin performance issue. What I can do is try and make break events created a bit less often.

**Comment by TheAndrey** [comment]
@asiekierka why it is impossible to break blocks directly by means of setBlock() and getDrops()? In old BuildCraft versions was quite so. The majority of modders so do and there are no problems.
The only thing the case where is necessary the fake player - an active transport pipe. There they it is used that the installed block turned facing the player. In all other cases we can place blocks by means of setBlock().

Try to minimize use a fake of players. Use only where well not to do without them in any way (difficult actions the demanding participations of the player).

**Comment by AEnterprise** [comment]
maybe a midway solution is possible? add a config option to dissable the use of the fake player but leave it on by default as it can (and will) be used to bypass permission plugins/mods

**Comment by TheAndrey** [comment]
@AEnterprise It would be good...

**Comment by 008** [comment]
@TheAndrey you server would bee all griefed and Quarry will be griefed by Quarry

**Comment by TheAndrey** [comment]
@008 You read [my message](https://github.com/BuildCraft/BuildCraft/issues/3109#issuecomment-153394810)? I solved this problem for a long time. A fake players for me - the last century.

**Comment by SandGrainOne** [comment]
How do you identify the owner of a Quarry?

**Comment by TheAndrey** [comment]
I write down in NBT TileEntity UUID of the player who installed this block. Quarry (or other mechanism) fires custom Bukkit event which contains information about of owner of the mechanism and the block which the mechanism wants to change. My special plug-in processes this event and by means of API WorldGuard (or the friend of a plug-in of the protected zones) whether checks there is in the region an owner of the mechanism. If is - the mechanism is allowed to break the block.

Also there is the second option of check - on locations of the block of the mechanism. If the block of the mechanism and the block which wants to change the mechanism are in the same region of WorldGuard - it is allowed to change the block. Grifer will definitely not be able to place the mechanism in others region.

So safely and at the same time conveniently for players - I put mechanism and it works (nobody needs to be added to the region). :)

**Comment by SandGrainOne** [comment]
The second option will not work. Players can place the Quarry right outside the WorldGuard region and the Quarry could still eat large parts of a base. It is important that you keep the owner information.

**Comment by TheAndrey** [comment]
@SandGrainOne A year it is option works. Quarry won't be able to change units in the protected region as its block (that which placed by the player and connects to it engines) is outside the region. The rule "in the same region" isn't executed here, means the mechanism won't get access to change of blocks.

**Comment by asiekierka** [comment]
@TheAndrey FakePlayers are the Forge-sanctioned way of doing block breaking. Compatibility with Forge is our primary concern, Bukkit is secondary. We could add a config option, I suppose.

**Comment by TheAndrey** [comment]
I tell not about compatibility, and about bad use a fake of players.

**Comment by asiekierka** [comment]
It's the absolutely correct use. I'm saying that I'm breaking a block, so I
emit a break block event.

2015-11-04 15:42 GMT+01:00 Andrey <notifications@github.com>:

**Comment by TheAndrey** [comment]
Why you emit a break block event? Unless without it badly works?

**Comment by AEnterprise** [comment]
without it other mods can't prevent the quarry for from breaking blocks, for example protected blocks like a TE strongbox with an lock on it. only it's owner is allowed to break the block and not the quarry

**Comment by TheAndrey** [comment]
@AEnterprise Such blocks usually do unbreakable, so, any mechanism won't be able to break them. And why to us here events?

**Comment by asiekierka** [comment]
ForgeEssentials and pretty much all Forge protection mods?

**Comment by AEnterprise** [comment]
@TheAndrey nope that's not how most of those work as the owner can still break them, some mods also listen to the event to handle drops or do special things

**Comment by TheAndrey** [comment]
@AEnterprise It is complete of other mods in which there are mechanisms the changing blocks. They will successfully break such block because do it directly without use the player's fake. Therefore in such method of protection the sense isn't present.

**Comment by simon816** [comment]
@TheAndrey That's not how it should be done. -_-
Fake players are the correct way of going about doing this and firing the event is also a necessity if your mod is to be respected by other mods.
Whatever is causing your problem is not to do with BuildCraft, but rather something that cauldron/whatever is doing. I suggest you try without bukkit plugins and try without cauldron (use forge).

**Comment by TheAndrey** [comment]
@simon816 If to follow your logic, the fake players needs to be used where it is only possible. For example, TNT changes blocks. Why not to add the fake player to it?

**Comment by simon816** [comment]
Say players 'explode', as in there is a key on the keyboard which will explode the player and the surrounding area. Then having a fake player for TNT could make sense, since that's a player _action_ that could be _simulated_ using code.
BuildCraft uses a fake player because what's the quarry doing? breaking blocks. Players break blocks, breaking blocks in an _action_ a player chooses to do. A quarry _simulates_ the action otherwise done by players, hence the use of a fake player to represent the abilities of that player on the blocks it digs. Having a fake player gives Minecraft along with other mods the power to control what the quarry can do.
BuildCraft won't be removing it's fake player (that's been around for years), no matter how convincing of an argument you make, right @asiekierka?

**Comment by Kubuxu** [comment]
There is custom event for TNT explosion. There isn't one for BC because BC just breaks blocks and `BlockBreakEvent` as it is called is used to ensure that BC does that only in area that it should. Your performance problems aren't caused because BC does something wrong but because one of your handlers have too large overhead.

**Comment by SandGrainOne** [comment]
This projects issue list is not the right place to discuss whether forge and forge mods are doing these things in the best possible way or not.
