### ISSUE TITLE
domain buildcraft is missing 2 textures

### ISSUE THREAD

**Issue by wi-ta** [BuildCraft/BuildCraft#3110]
==================================================
  DOMAIN buildcraft
--------------------------------------------------
   domain buildcraft is missing 2 textures
     domain buildcraft has 7 locations:
       mod BuildCraft|Builders resources at C:\Users\Wilfried\AppData\Roaming\3minecraft\mods\1.7.10\buildcraft-7.1.12.jar
       mod BuildCraft|Transport resources at C:\Users\Wilfried\AppData\Roaming\3minecraft\mods\1.7.10\buildcraft-7.1.12.jar
       mod BuildCraft|Energy resources at C:\Users\Wilfried\AppData\Roaming\3minecraft\mods\1.7.10\buildcraft-7.1.12.jar
       mod BuildCraft|Silicon resources at C:\Users\Wilfried\AppData\Roaming\3minecraft\mods\1.7.10\buildcraft-7.1.12.jar
       mod BuildCraft|Robotics resources at C:\Users\Wilfried\AppData\Roaming\3minecraft\mods\1.7.10\buildcraft-7.1.12.jar
       mod BuildCraft|Core resources at C:\Users\Wilfried\AppData\Roaming\3minecraft\mods\1.7.10\buildcraft-7.1.12.jar
       mod BuildCraft|Factory resources at C:\Users\Wilfried\AppData\Roaming\3minecraft\mods\1.7.10\buildcraft-7.1.12.jar
 -------------------------
     The missing resources for domain buildcraft are:
       textures/items/triggers/trigger_machine_active.png
       textures/items/triggers/trigger_machine_inactive.png
 -------------------------
     No other errors exist for domain buildcraft
 ==================================================

**Comment by SandGrainOne** [comment]
I'm unable to recreate this issue with the version I downloaded here:
http://www.mod-buildcraft.com/pages/download.html

**Comment by iTitus** [comment]
It's caused by another mod, not BC. Maybe IC2 or Forestry?

**Comment by LuigiHutch** [comment]
I believe it is caused by IC2

**Comment by wi-ta** [comment]
THX
I will search in that direction

**Comment by wi-ta** [comment]
Hey there :-)
The solution to this problem was in my case a clean reinstall off Minecraft.
Please be sure to save your config / worlds / mods.
