### ISSUE TITLE
bug gate

### ISSUE THREAD

**Issue by lakima** [BuildCraft/BuildCraft#3114]
http://image.noelshack.com/fichiers/2015/45/1446798109-2015-11-06-09-18-07.png

everything on the pipe should be a gate and when I click on it does not show me his good interface.

http://image.noelshack.com/fichiers/2015/45/1446798399-2015-11-06-09-24-23.png

**Comment by SandGrainOne** [comment]
It looks like there is a gate on the back side from where you took  the screen shot. The sides we can see have a lens, a stone facade and a facade with some transparent material. 

If you want to open the gui of the gate you need to right click the actual gate. Not like in old BuildCraft where clicking anywhere on the pipe would be enough.

**Comment by asiekierka** [comment]
I think he means that everything should be gates, but there's some kind of
network sync issue which makes it not so.

**Comment by lakima** [comment]
yes that's right, I put a door on each side but were transformed into it

**Comment by AEnterprise** [comment]
looks like a resourcepack issue to me

can be closed

**Comment by AlexIIL** [comment]
Thats... odd. Please re-open this if its still happening now, as I've never seen it before.
