### ISSUE TITLE
Some item can't work with Auto-workbench

### ISSUE THREAD

**Issue by NyanU** [BuildCraft/BuildCraft#3116]
sorry,My english not very well :)
Minecraft version:1.7.10
Forge version:1.7.10-Forge10.13.2.1291
Related mod:
Pam's HarvestCraft 1.7.10i
BuildCraft 7.0.12

Related Item: All tools,bucket
Pam's HarvestCraft:Cooking Tools(All)

The main purpose of use buckct in Auto-workbench craft Clear-Water(Disorderly Synthesis:1*bucket=1*clear-water)
Clear-water again and again and only outputs 1(one) synthesized,very troublesome,so i want use auto-workbench to auto-craft it.

Mail feedback over this issue, but no matter how many times your address are sent to retry failure
I may not have accurately stated what I mean, but it means almost with "Similar issues:https://github.com/BuildCraft/BuildCraft/issues/2906"

**Comment by NyanU** [comment]
![issues](https://cloud.githubusercontent.com/assets/15691026/11000945/eb0e3424-84e7-11e5-8e8d-abf9ecb75de5.jpg)

**Comment by Nucleria** [comment]
According #2906, it's not supposed to. Was that changed, or is this just a misunderstanding?

**Comment by asiekierka** [comment]
It was meant to be added but was not.

2015-11-08 19:16 GMT+01:00 Nucleria <notifications@github.com>:

**Comment by NyanU** [comment]
sorry, I do not understand what you mean
1.Yes, this is a BUG
2.Issue to the same with the # 2906 ()
3.This issue should go Pam's HarvestCraft the author
4.other
5.This is not a BUG, is a deliberate design

**Comment by liach** [comment]
It means that asiekierka did not have time to add it right know. This feature might be added later.

**Comment by Nucleria** [comment]
Thanks for the clarification, asie.

**Comment by NyanU** [comment]
@liach ok,I will patiently wait

**Comment by asiekierka** [comment]
See #2906.
