### ISSUE TITLE
bc quarry lazer spawning miles away

### ISSUE THREAD

**Issue by rawrturkey** [BuildCraft/BuildCraft#3118]
![2015-11-07_15 50 23](https://cloud.githubusercontent.com/assets/15705263/11015888/529095c2-8567-11e5-9c55-4a865f46e756.png)
when i place the quarry and power it the lazer part spawns miles away and nothing happens it just sits there i've tryed land marks and everything

**Comment by asiekierka** [comment]
Screenshots?

**Comment by rawrturkey** [comment]
sorry forgot to add one just done it

**Comment by rawrturkey** [comment]
newest one i think
it seems to only be happening in the pack im playing "dimensional space"
