### ISSUE TITLE
Repair enchants don't work properly

### ISSUE THREAD

**Issue by Unknown-Zombie** [BuildCraft/BuildCraft#3119]
In 7.1.12 the change log says that Mining Robots take advantage of enchants now. Should this extend to any robot that uses a tool? I have given a Tinker's Construct tool with Repair on it to a Lumberjack Robot, but the tool doesn't actually repair itself while the robot holds it.

**Comment by asiekierka** [comment]
I meant vanilla enchants, not these. I am not sure if I can even support things like Repair correctly.

Dnia 8 lis 2015 o godz. 02:45 James A. Gilmore II <notifications@github.com> napisał(a):

**Comment by Unknown-Zombie** [comment]
Understood; it's not a big deal.

**Comment by iTitus** [comment]
If  the onUpdate(...) method of the Item is called, that TiC modifier should work, but this could also cause some problems.
