### ISSUE TITLE
< x % trigger not working with TiCon Smeltery Controller

### ISSUE THREAD

**Issue by Silwing** [BuildCraft/BuildCraft#3120]
I'm playing Regrowth 0.8.3 with Buildcraft 7.1.12 and trying to automate the TiCon smeltery.

What I want is to insert ores into the controller with Buildcraft pipes. In order to prevent overflow I am trying to use a Golden Gate with the < 50% trigger to send a signal for more resources. The problem I'm seeing is that the trigger will be active until the smeltery is completely full, not until it is 50% full. I have attached 4 screenshots showing off the Smeltery filled with blocks, not activating the trigger and the Smeltery with 1 block missing which will then activate the trigger.

My thought is that the gate trigger might not detect that each slot in the Smeltery can only contain 1 item, so with 18 slots available (as in the screenshot) it thinks there is space for 18 stacks of copper, detecting only 17 copper is clearly less than 50% of 18 stacks. However it does detect when the smeltery reports no more space for anything.

I'm not sure whether this is a TiCon specific problem or it might be general for all containers with space for less than a stack in each slot.

![2015-11-08_08 47 57](https://cloud.githubusercontent.com/assets/186144/11019333/85e05e92-85f5-11e5-91b2-849ed94be0c0.png)
![2015-11-08_08 48 05](https://cloud.githubusercontent.com/assets/186144/11019335/85e30246-85f5-11e5-9548-ffe8ffee6258.png)
![2015-11-08_08 48 12](https://cloud.githubusercontent.com/assets/186144/11019336/85e2fd5a-85f5-11e5-9563-53f03860bead.png)
![2015-11-08_08 48 16](https://cloud.githubusercontent.com/assets/186144/11019334/85e2981a-85f5-11e5-9e98-7413773015d7.png)

**Comment by Silwing** [comment]
Just found that the < 25% trigger does not work properly with JABBA Barrels either. I have a barrel with 40 stacks of copper ore with space for 128 stacks. This barrel has the <25% trigger active even though 40 stacks is more than 25% of 128 stacks.

**Comment by Silwing** [comment]
I looked a little into the code and the problem for the Smeltery at least seems to be this calculation:

float percentage = foundItems / ((float) stackSpace * (float) searchStack.getMaxStackSize());

The calculation assumes that every slot it finds which is compatible with the searchStack also has a max stack size that is the same as the maxStackSize of the searchStack. For the Smeltery that is not the case. I'm not enough into modding that I know whether it is possible to somehow get the MaxStackSize for an inventory slot. If so the stackSpace variable should count the actual space for items instead of counting the number of stacks with available space.

**Comment by AEnterprise** [comment]
the problem is that sadly it is impossible to know the max stacksize of a slot, we can only get it from the stack, not the slot that is holding the stack :/

**Comment by SandGrainOne** [comment]
The getInventoryStackLimit method should provide the size limit of the slots in an inventory.
