### ISSUE TITLE
Oil engine does not accept the Oil / Petroleum

### ISSUE THREAD

**Issue by NyanU** [BuildCraft/BuildCraft#3124]
Minecraft version:1.7.10
Forge version:1.7.10-Forge10.13.2.1291
Related mod:
BuildCraft 7.0.12

MOD contains a lot of liquid, only Gray Technology
Gregtech  1.7.10-5.08.23

OMG,This leads me to only go with a Stirling engine to those "big eaters (energy-consuming equipment)" for energy

This is somewhat similar to https://github.com/BuildCraft/BuildCraft/issues/3063  ,but Not installed PneumaticCraft
Oil / Petroleum to reach the engine is like experiencing congestion, it does not seem to be accepted

All installed mod list:                     Part of the text has been marked in English

![issues](https://cloud.githubusercontent.com/assets/15691026/11000945/eb0e3424-84e7-11e5-8e8d-abf9ecb75de5.jpg)

**Comment by AEnterprise** [comment]
you sure the oil is buildcraft oil and not oil from gregtech? gregtech fluids won't work with BC machines/engines, this is inteded by gregtech, they specificaly prevented it

**Comment by asiekierka** [comment]
Screenshots?

**Comment by NyanU** [comment]
![1](https://cloud.githubusercontent.com/assets/15691026/11033504/00bfd5a2-8727-11e5-979b-db42ea91f35c.png)
![2](https://cloud.githubusercontent.com/assets/15691026/11033506/01638490-8727-11e5-82a5-cf0f21bb27f4.png)

**Comment by NyanU** [comment]
![3](https://cloud.githubusercontent.com/assets/15691026/11033655/51c5b39e-8728-11e5-8f5f-40d6b4804e40.png)


Use bucket right-click Storage tank, unable to obtain Oil/Fuel-bucket.
Must be a fake Oil/Fuel-bucket,or get an empty drum

But,use bucket right-click a Oil(block) can get drums,fuel also

*From BaiDu-Translation,Not accurate enough (Temporarily unable to visit Google translation)

**Comment by NyanU** [comment]
Why don't try to put the fuel in the engine? New issue:

Use bucket right-click Storage tank, unable to obtain Oil/Fuel-bucket.
Must be a fake Oil/Fuel-bucket,or get an empty drum

But,use bucket right-click a Oil(block) can get drums,fuel also

*From BaiDu-Translation,Not accurate enough (Temporarily unable to visit Google translation)

**Comment by NyanU** [comment]
My friend say: If use "Gregtech Null unit"  or "IC2(exp) Gluid element"，Can be taken to fuel, but the same can not be put into the engine
