### ISSUE TITLE
omg! finally nailed that bug thats been persisting for months NEI / BC

### ISSUE THREAD

**Issue by plaguewolf** [BuildCraft/BuildCraft#3125]
version info:
forge 1492
buildcraft 7.1.* (for me the last 3 or 4 versions, including the latest 7.1.13)
buildcraft compat 7.1.2
codechickencore 1.0.7.47 (also was there for the last version or so)
NEI 1.0.5.118 (same as above, persisted through several versions)

bug description:
in NEI cheat mode, when inventory is full, and click on any item to "give to player" client hangs and crashes.

exception logs: http://pastebin.com/eYDES6Mj

i think something about NEI itemstack handling has changed and/or BC guicontainer isnt working with the changes right.

**Comment by plaguewolf** [comment]
is this something that is know? is it BC or NEI? sorry to be obnoxious bump guy...

**Comment by AEnterprise** [comment]
nei issue, seems nei thinks there are more slots in the gui then there actually are, probably a off by one coding error

**Comment by Adaptivity** [comment]
@AEnterprise [this](https://github.com/BuildCraft/BuildcraftCompat/blob/7.1.x/common/buildcraft/compat/nei/NEIGuiHandlerBC.java#L20) shouldn't [return null](https://github.com/Chicken-Bones/NotEnoughItems/blob/1.7/src/codechicken/nei/api/INEIGuiHandler.java#L18). I tried to fix it and PR but I can't build BuildcraftCompat so I can't test this. So, someone who knows how to properly build Compat should fix it.

**Comment by AEnterprise** [comment]
yeah that should indeed fix it, thought it was an nei error, never worked with an INEIGuiHandler
