### ISSUE TITLE
Duping using Recycler and Mining Well.

### ISSUE THREAD

**Issue by Cornul11** [BuildCraft/BuildCraft#3126]
https://www.youtube.com/watch?v=lYL_Muy6Gx4
In this video you can see how to dupe using the two items that i named earlier. I hope for a bug fix.
Minecraft Version 1.7.10
BuildCraft Version 7.0.16
Industrial Craft Version 2.2.751-experimental

**Comment by asiekierka** [comment]
Try with the latest version, please. 7.0.16 is about 3-4 months behind?

2015-11-09 19:05 GMT+01:00 Cornul11 <notifications@github.com>:

**Comment by Cornul11** [comment]
Yes, the bug has been fixed in the newest version.
