### ISSUE TITLE
can't add the autarchic upgrade to my gates

### ISSUE THREAD

**Issue by Turmfalke2** [BuildCraft/BuildCraft#3127]
hi,
Using 7.1.13 in regrowth modpack (the recipe for this unchanged) I am unable to upgrade my gates with pulsating chipsets.
 http://ibin.co/2MPgdKorEitj
 http://ibin.co/2MPgsJypk8DC

E:
I found what is causing it - pulsating chipsets crafted in 7.1.13 work and don't stack with chipsets from an older bc version.

**Comment by asiekierka** [comment]
If it still occurs, please re-open.
