### ISSUE TITLE
Fluid Tanks displaying liquids as white (even with their color set)

### ISSUE THREAD

**Issue by IceDragon200** [BuildCraft/BuildCraft#3128]
Hello, one of the developers from [Growthcraft](https://github.com/Alatyami/Growthcraft-1.7) here, I'd like to report a bug regarding fluid tanks.

See, we were building against 7.0.9 for awhile, until the "a new version is available" message started nagging me, so I updated to 7.1.13, sadly.

Fluid tanks stopped displaying our fluids correctly.
Due to the number of fluids we have, we used 1 texture (a white one) along with the Fluid#getColor to denote different fluids, sadly after upgrading our fluids are rendered as their base texture without color.

[Expected (From 7.0.9)](https://dl.dropboxusercontent.com/u/72618186/screenshots/minecraft/growthcraft/tanks/2015-11-14_11.02.18.png)
[Actual (Now 7.1.13)](https://dl.dropboxusercontent.com/u/72618186/screenshots/minecraft/growthcraft/tanks/2015-11-14_11.06.41.png)
  
In addition, I've noticed that the tanks use the downcased fluidName (Possibly `Fluid#getName()`) instead of unlocalized name (`Fluid#getUnlocalizedName()`)

**Comment by iTitus** [comment]
Hmm it looks like something got messed up.
The only place where there is something written to the colorRenderCache is in GuiRefinery.mouseClicked (wtf?)
The cache is also just send via the container update thing which truncates every number to short in MP.
Why does this even work?

**Comment by iTitus** [comment]
Can confirm

**Comment by iTitus** [comment]
The culprit seems to be the CoreProxy.proxy.getServerTile(...) in RenderTank

**Comment by asiekierka** [comment]
Oh, right! Because the color cache is not updated them.

Comment it out (or, if you want to keep smooth singleplayer rendering, make
it check if the worldObj is not remote and get the color from the fluid
then.)

**Comment by iTitus** [comment]
Do you mean the WAILA tooltip with that? I think that is native support.
