### ISSUE TITLE
AutoCrafting bench problem with OD and Stuff

### ISSUE THREAD

**Issue by Carbon-Ghost** [BuildCraft/BuildCraft#3129]
Basically when you set a recipe, it cannot read OD, basically if you set a crafting table with jungle wood but give it oak one, it won't accept to craft it...

**Comment by Carbon-Ghost** [comment]
^ about a bug causing memory leaks..

**Comment by AEnterprise** [comment]
the auto workbench shouldn't accept oredict equivalents, some systems might be using the fact that the item doesn't go in for crafting setups (using a clay pipe for example), especially not in the case above as it's not just accepting another time plank to make a piston but another type of wood that would give another type of plank, breaking the automation

i also don't see how this could even remotely be linked to any kind of memory leaks

can be closed

**Comment by AlexIIL** [comment]
Yeah unfortunately you will need to use a seperate auto-workbench for each type of wood.

**Comment by Carbon-Ghost** [comment]
Maybe a OD button thing where you can activate OD or deactivate it ?

**Comment by AEnterprise** [comment]
@Carbon-Ghost even then it won't work for your usecase, the oredic accept equivalents but in this case your recipe does not accept it. the junglewood recipe does not accept oak wood for the recipe

**Comment by Carbon-Ghost** [comment]
:/
