### ISSUE TITLE
Moving LandMarks with WorlEdit

### ISSUE THREAD

**Issue by Morketh** [BuildCraft/BuildCraft#3132]
Essentially i selected a region containing 2 Landmarks and used the //move command trying to move the selection 13 blocks away and received a fatal crash that shut the server off
guess you shouldn't move landmarks with world edit
crash-report here: http://ci-main.no-ip.org/minecraft/crashreports/crash-2015-11-14_15.31.19-server.txt

**Comment by asiekierka** [comment]
Link no longer works.
