### ISSUE TITLE
NPE in PipeTransportFluidsRenderer.

### ISSUE THREAD

**Issue by Geforce132** [BuildCraft/BuildCraft#3134]
Someone using my mod, SecurityCraft, posted this crashlog into my thread and asked me to fix it. It seems to be coming only from BuildCraft, so I'll post it here: http://pastebin.com/y0KxzQ4U

From what I've seen, you simply need to check if pipe (or possibly pipe.container) is null before this line:
https://github.com/BuildCraft/BuildCraft/blob/7.1.x/common/buildcraft/transport/render/PipeTransportFluidsRenderer.java#L196

**Comment by asiekierka** [comment]
Ask them to check with 7.1.13 first.

Dnia 19 lis 2015 o godz. 18:05 Geforce <notifications@github.com> napisał(a):

**Comment by Geforce132** [comment]
They just tried it, and are having the same problem.
