### ISSUE TITLE
Steam has a missing texture when inside an OpenBlocks tank

### ISSUE THREAD

**Issue by chaNcharge** [BuildCraft/BuildCraft#3142]
When there's steam inside an OpenBlocks tank or in a Railcraft steam generator, it shows the missing texture checkers. This bug only appears and reproduces if BuildCraft Compat is installed. I am using the latest version of BuildCraft and BuildCraft Compat. Also, without BuildCraft installed, the steam textures show as normal as they're supposed to.

To reproduce:
1. Get an empty tank from OpenBlocks
2. Fill it up with some steam.

Or:
1. Build a railcraft steam boiler
2. Fuel up the steam boiler
3. If you want, output the steam into a tank or just leave it in its internal tank
![2015-11-29_15 08 09](https://cloud.githubusercontent.com/assets/11594018/11460892/10ec6916-96ab-11e5-8b7b-70eaafab1e1a.png)

**Comment by dj3520** [comment]
This involves Railcraft and OpenBlocks, not Buildcraft.

**Comment by chaNcharge** [comment]
You can test it even without these mods. If you place down a steam "BLOCK", it shows as a missing texture

**Comment by AEnterprise** [comment]
buildcraft doesn't add steam so the issue lies in the mod that is adding the steam (and is thus resposible for handling it's texture)

**Comment by SandGrainOne** [comment]
If you are still sure this is BuildCraftCompat, then please register this issue with BuildCraftCompat instead.
