### ISSUE TITLE
Redstone engine is not connecting

### ISSUE THREAD

**Issue by Dis742** [BuildCraft/BuildCraft#3144]
hello on your latest build buildcraft-7.1.14 the Redstone engine is not connecting up to any of the wooden pipes see below

http://img.photobucket.com/albums/v165/flippy224/2015-11-30_20.41.00_zpst9osmam6.jpg

http://img.photobucket.com/albums/v165/flippy224/2015-11-30_20.39.09_zpsbj3odmdc.jpg

thank you for looking in to this

p.s.

i did try to regester on the build craft forum but had issues with the Security Question image on making a new account !

**Comment by AEnterprise** [comment]
redstone engines don't connect to any pipes. they will still provide power to the wooden item and fluid pipes but not to the wooden power pipe as it is basicly free power if it was able to connect to a power pipe

as for the forum security question: what was the issue with that?

**Comment by Dis742** [comment]
thanks for the quick reply
the security question would shown green but the forum would state that it was incorrect see below
http://img.photobucket.com/albums/v165/flippy224/DISTURBED74/FORUM1_zpsjkvd6pnu.jpg
http://img.photobucket.com/albums/v165/flippy224/DISTURBED74/FORUM2_zpsjbqzgtgm.jpg
as for the pipe I doubled checked and it just appeared to not connect as a gap between the pipe and engine I guess I never noticed this.
http://img.photobucket.com/albums/v165/flippy224/2015-12-02_18.25.16_zpswsbgbr4y.jpg
