### ISSUE TITLE
[Enhancement] Super Lasers

### ISSUE THREAD

**Issue by mikeloeven** [BuildCraft/BuildCraft#3145]
Simple 3x3 nesting recipe for BC Lasers 

9 lasers craft into super Laser 9X faster RF transfer to assembly table

**Comment by dj3520** [comment]
Would be great for redstone crystals. Imho 10x for super laser (9 + 1 bonus
for crafting like coal does)

However, how many of these would max out a gold/diamond kinesis pipe?

**Comment by asiekierka** [comment]
No.

2015-12-02 5:47 GMT+01:00 dj3520 <notifications@github.com>:

**Comment by mikeloeven** [comment]
well right now something has to give we have huge RF backbones and the limitation to assembly table speed is the fact that there are only so many lasers you can place around

**Comment by asiekierka** [comment]
960 * 40 RF/t is the theoretical maximum. Just make more lasers.

2015-12-02 6:17 GMT+01:00 MikeLoeven <notifications@github.com>:

**Comment by dj3520** [comment]
What's the practical max? I'd imagine a single wall of lasers more in the
area of a 12*12. Even that takes 9 seconds with perfect performance for a
redstone crystal. And that's with all of the diamonds to make them.

**Comment by asiekierka** [comment]
That's a good thing. Why rush the game needlessly?

(You can place lasers behind other lasers too.
