### ISSUE TITLE
stripe pipes stay powered even when redstone engine stopped

### ISSUE THREAD

**Issue by mvdhoning** [BuildCraft/BuildCraft#3147]
should not a stripe pipe stop working if an redstone engine is unpowered again? Now it seems to continue to break blocks. Only breaking the stripe pipe and place it again make it stop breaking.

ps i am using buildcraft in the divergence modpack

**Comment by dj3520** [comment]
Newer versions have fixed this. Please tell the modpack maker to update.

**Comment by mvdhoning** [comment]
ah yes the modpack is using 1.7.10 and this seems to be fixed in 1.7.13 as i just read :-)
