### ISSUE TITLE
Analog gates

### ISSUE THREAD

**Issue by SoniEx2** [BuildCraft/BuildCraft#3150]
Analog gates would allow analog pipewire. There would be e.g. a "redstone level" trigger and a "pipewire level" thingy. Analog gates would require a comparator.

Ideas for analog triggers:

- Inventory level (as in comparators)
- Fluid level (`inventory fluid / inventory capacity`)
- Redstone level
- Power level (`current power / pipe capacity` - this is the only trigger that makes sense to be based on pipe contents)
- Mana level (for botania)

Edit: Alternatively this could just require 4 pipewire and use the 4 to transmit a value between 0 and 15.

**Comment by dj3520** [comment]
Redstone analog is provided via the fader upgrade.

**Comment by AEnterprise** [comment]
redstone lvl trigger already exists, pipe wires do not have signal strenghts and this request is old

can be closed

**Comment by SoniEx2** [comment]
inventory/fluid/power level? (as with comparators)

**Comment by AEnterprise** [comment]
what would be the point of those you already have 25, 50, 75, 100% triggers

**Comment by SoniEx2** [comment]
Analog signal? I mean... hmm...

Why not just have a "comparator gate trigger"? It acts as a comparator so you don't need to specify what kind of inventory, and then you just specify the comparator signal. It'd be an universal gate trigger.

**Comment by AEnterprise** [comment]
again: you can already do all of that with just BC + vanilla, i don't see the use for it but if you realy realy want it make an addon

**Comment by SoniEx2** [comment]
That's not a good argument. There's a gate to check inventory fullness, yet I can do that with vanilla. A good argument is that gates can go on pipes while comparators can't.

**Comment by AEnterprise** [comment]
those gate triggers predate comparators, and BC is not about making the most compact machine possible

but i sugest we just leave it at this as this discussion is not going anywhere and neighter of us are BC devs so that's who should make the call on if this get's implemented or not

**Comment by AlexIIL** [comment]
I don't really like the idea of making pipe wire analog. I have better plans for reading more information for power, items and fluids than just 25% increments anyway. Although those will only be in 8.0.x an onwards.
