### ISSUE TITLE
java.lang.NullPointerException: Ticking block entity architect table

### ISSUE THREAD

**Issue by loordgek** [BuildCraft/BuildCraft#3153]
i was recording a forestry multiblock farm and it crashed 

https://gist.github.com/loordgek/74ae4968c1a4041b785d
you can reproduce by making a multiblock farm

**Comment by AEnterprise** [comment]
bug in the forestry blueprint integration but can be closed as this is 1.7.10, the relevant code doesn't exist on 1.8+ so the integration eighter no longer exists or has been rewriten

**Comment by AlexIIL** [comment]
Yeah unfortunately this should be in compat. Although support for 1.7.10 has nearly ended so it won't be implemented by me. Sorry.
