### ISSUE TITLE
java.lang.Throwable$WrappedPrintStream:println:-1

### ISSUE THREAD

**Issue by willstdueswissen** [BuildCraft/BuildCraft#3154]
A real big spam error:
Can you fix it?

The log:

https://gist.github.com/willstdueswissen/157577f5f867b4b3f476

**Comment by AEnterprise** [comment]
the final error heapens at mrtjp core so the fix should come from there, for now you can dissable microblock compat in BC compat to get rid of the spam

**Comment by willstdueswissen** [comment]
Okay tnak you
