### ISSUE TITLE
Client Crash Achievement Tab

### ISSUE THREAD

**Issue by aikpoppel** [BuildCraft/BuildCraft#3156]
Hey,
if i disable some machines in the config file and try to open the achievement tab the client gets crashed.
http://pastebin.com/6NTh1BvW
LG Aik

**Comment by AEnterprise** [comment]
that's a tough one, it tries to render something you dissabled for the achievement, dissabeling specific achievements might be doable for some but that will mean all achievements that folow on it will have to be dissabled as well as they don't have a parent anymore to unlock them

**Comment by AlexIIL** [comment]
No... we can just check if the parent achievement is enabled, and if it is NOT we can just use the nearest parent that is not. Its a bit ugly but it shouldn't be too big of a problem to fix.

**Comment by AEnterprise** [comment]
yeah i know but right now there is a progression in it that will get kinda lost in some cases now but nothing can be done to avoid that

**Comment by aikpoppel** [comment]
For now i use minetweaker to disable the recipes. hope you can work it out.

**Comment by AlexIIL** [comment]
Oh no sorry! It's still a bug with buildcraft, and still needs fixing so this will be open until it's fixed :)
