### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by Artmoneyse** [BuildCraft/BuildCraft#3157]
http://pastebin.com/4ddYzw7N

**Comment by SandGrainOne** [comment]
Please update to BuildCraft 7.1.14 and see if that helps.

**Comment by Artmoneyse** [comment]
BuildCraft 7.1.14 http://pastebin.com/CVDRKAQy

**Comment by AlexIIL** [comment]
Can you try with this jar? https://www.dropbox.com/s/po44m72cs71i6yy/buildcraft-7.1.15-pre2.jar?dl=1
