### ISSUE TITLE
Crash report quarry block

### ISSUE THREAD

**Issue by nynguem** [BuildCraft/BuildCraft#3158]
[crash-2015-12-15_10.59.05-client.txt](https://github.com/BuildCraft/BuildCraft/files/62553/crash-2015-12-15_10.59.05-client.txt)

plz help, i dont understand about coding and i cant play since i decide update the mod

**Comment by SandGrainOne** [comment]
QuarryPlus is marked with "Errored" during load. There are probably some dependency between QuarryPlus and BuildCraft when you updated BuildCraft. 

Look for an update to QuarryPlus or remove it and see if that helps.

Always remember to take backup of your world before updating a mod.

**Comment by AEnterprise** [comment]
yeah your QuarryPlus is outdated, the quarry was moved to the builders module

**Comment by nynguem** [comment]
tks guys, updated the quarry plus and its working :D
