### ISSUE TITLE
Knight Robots: Sword Attack Damage not Registering Properly

### ISSUE THREAD

**Issue by chemdork123** [BuildCraft/BuildCraft#3159]
This is a request to reopen a previously posted issue, #2941 "Knight robot sword damage wrong", as the issue was closed, but apparently not fully fixed.
*(confirmed BC versions 7.1.13 and 7.1.14)*

When the Knight robot attacks a mob, there are two characteristics to consider for sword damage:

1. Enchantments
2. Attack Damage

It appears that while the *Enchantments* appear to be properly registered when Knight robots attack mobs, the *Attack Damage* of the weapon does not register properly.

An example of this is seen in three separate parts of the YouTube video linked below.  A simple setup was created for a Knight robot to attack and kill a skeleton.  You would expect the mob to catch on fire when using a sword with Fire Aspect II, and you would expect a diamond sword to kill the skeleton with less hits than a wooden sword.  This is not entirely the case as you will see below.

* [Diamond Sword](http://www.youtube.com/watch?v=l2EzSUGqEcM&t=4m5s).  It takes **10 hits** to kill the skeleton.

* [Wooden Sword](http://www.youtube.com/watch?v=l2EzSUGqEcM&t=26m37s).  It takes **10 hits** to kill the skeleton.

* [Diamond Sword with Fire Aspect II Enchantment](http://www.youtube.com/watch?v=l2EzSUGqEcM&t=27m59s).  Mob **catches on fire** and is killed in less than 10 hits (due to the effect of the fire).

So it seems that the [enchantment aspect was fixed in the previous open issue](http://github.com/BuildCraft/BuildCraft/issues/2941) for Knight handling of weapons, but not for the attack damage characteristic of the weapon being used.

**Comment by asiekierka** [comment]
I guess now that I'm back I might look at these issues again.
