### ISSUE TITLE
Blueprint can't memorize almost all blocks from GregTech 6

### ISSUE THREAD

**Issue by MoXiaoFreak** [BuildCraft/BuildCraft#3162]
When I put a blank blueprint in the Architect Table,it works normally.But then I put it into a Builder,all of the blocks from GregTech6 are lost. 
  
![2015-12-19_20 08 23](https://cloud.githubusercontent.com/assets/15845740/11912897/8d9145a4-a68c-11e5-84b5-3096524e86e7.png)
![2015-12-19_20 09 02](https://cloud.githubusercontent.com/assets/15845740/11912902/c012c0ca-a68c-11e5-9ef5-8950e4025969.png)

**Comment by AEnterprise** [comment]
this is because there is no support added for those blocks, if you want the builder to support them best is to ask greg to add builder support.

the builder is basicly ignoring tileEntities without support to prevent dupe bugs
