### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Phill93** [BuildCraft/BuildCraft#3163]
Same config works on client.

https://gist.github.com/Phill93/5ab12f471aa71db3933b#file-fml-server-latest-log

**Comment by AEnterprise** [comment]
duplicate of #3154 
error is heapening due to something in mrtjp core, report there for a final fix

**Comment by Phill93** [comment]
Thank you
https://github.com/MrTJP/MrTJPCore/issues/18
