### ISSUE TITLE
Pipe Glitch and Quarry Stuttering

### ISSUE THREAD

**Issue by SirAnuse** [BuildCraft/BuildCraft#3169]
While playing on BC 7.0.9, after a certain amount of time, any pipes I placed would become Cobblestone Structure Pipes but would remain with their IDs and would drop the appropriate pipe upon destruction. So, I updated to BC 7.1.14, hoping it would fix the structure pipe glitch. I am not sure if the glitch occurs with this update, as a new problem was created - Quarry Stuttering. Quarries would mine normally (a bit slower if anything) using Stirling Engines, but would stutter during movement of the mining drill (the thing that goes around mining the blocks), making it take approximately ~4 seconds just to move across one block. Using combustion engines fixed the problem, but it is very annoying as we use Stirling Engines in survival. Here is a list of mods I have currently installed:

http://pastebin.com/X1DrjTVa

Nothing appears in the log when I place a pipe. I am hoping there is a solution for this problem, as is prohibits use of pipes and quarries (unless you have the patience of the monks of shaolin)

**Comment by AEnterprise** [comment]
if this bug was (still) present in BC alot more people would have made an issue about this by now, most likely another mod was messing things up

can be closed

**Comment by AlexIIL** [comment]
Most likely fixed by now. Although feel free to re-open this if you find it again @SirAnuse
