### ISSUE TITLE
Robots can fly through windows, and other blocks like forge multi - part pannels

### ISSUE THREAD

**Issue by luizdgarcia** [BuildCraft/BuildCraft#3172]
I was messing arround with robots and using some Picking Robots for my farm, and made some tunnels made out os forge multi blocks pannels and the can walk through it like it was not there.. the same goes for essence glass from magical crops the walk right through it.

Other thing is that sometimes the stop and than I have to restart the game and they walk again 

Thank you, and this robots are awesome =D

**Comment by chemdork123** [comment]
What's your MC version and BC version?  Do you have any other mods installed?

**Comment by AEnterprise** [comment]
this probably has something to do with the block implementations of those multipart container blocks, somehow when the robot 'asks' the block if it's a solid block it can't pass through it the block returns that it isn't a solid block and thus the robot thinks it can pass through it

**Comment by AEnterprise** [comment]
lacks information and sounds like an issue on the side of the mods that add those blocks, can be closed

**Comment by AlexIIL** [comment]
This was probably changed in 7.2.7 to use the ````isPassable```` method. The mods themselves will need to override this method if they wish to work with this.

**Comment by AlexIIL** [comment]
(Fixed in https://github.com/BuildCraft/BuildCraft/commit/febe3de1b7783291e13764b9f0f73565e4d13dad)
