### ISSUE TITLE
Quarry and filler ignoring snow blocks

### ISSUE THREAD

**Issue by tounho** [BuildCraft/BuildCraft#3173]
In BuildCraft 7.1.14 quarrys and fillers are **ignoring snow blocks** (not mining/destroying them). I think this is not intended and a bug.

**Comment by AEnterprise** [comment]
6 month old report that nobody has verified, can be closed

**Comment by AlexIIL** [comment]
...Another bug I verified and forgot about immediately :(

**Comment by AEnterprise** [comment]
well that's why i went throught the issues, to get these kind of issues fixed

**Comment by AEnterprise** [comment]
fixed in 8.0

**Comment by guyfromhere** [comment]
@AEnterprise When does version 8.0 will be released? I have same issue on Minecraft 1.8.9

**Comment by AlexIIL** [comment]
Thanks for bringing it up, its never been fixed in the 7.2.x branch and 8.0.x is no-where near ready.

(also due to 8.0.x builder code being dropped in favour of 7.2.x builder code its no longer fixed in 8.0.x)

**Comment by guyfromhere** [comment]
I'm using the actual beta for 1.8.9 and the builder works (with exception from snow blocks).

Means this concluded that we have to wait some months until it will be fixed?
