### ISSUE TITLE
Lava in tanks emits light level for the whole tank

### ISSUE THREAD

**Issue by larrythemodder** [BuildCraft/BuildCraft#3174]
Two issues here. The first is that when a large multi-block tank is created and filled with any amount of lava, every block in the tank gives off light. This looks weird when a 25-block tank has a single bucket of lava at the bottom and the top piece is giving off light.

The second issue, and this may be intentional, is that fluid pipes with lava in them do not give off light.

**Comment by AEnterprise** [comment]
the lava not emitting light in pipes is intentional iirc, little bits of lava can enter and exit pipes very quickly causing alot of lighting updates and those can be pretty intence and laggy

**Comment by larrythemodder** [comment]
That makes sense.
