### ISSUE TITLE
Unable to Create Fuel

### ISSUE THREAD

**Issue by DarianLStephens** [BuildCraft/BuildCraft#3176]
So, I've been doing some major refactoring of everything in my world, including the switch from stirling to combustion, and then from oil to fuel. I'm only having one slight problem with that last part; I seem to be unable to create fuel.
I have no idea if I'm doing anything wrong or if this is a bug, but the Refinery has power, has both back tanks filled with oil, and even has an extraction pipe leading to a tank and the very engines used to power it, and yet it's piston-things stay still.
Here are some screenshots from a creative world I made to do some testing with the issue.
![2016-01-03_14 46 49](https://cloud.githubusercontent.com/assets/15375876/12077167/ed8aafa2-b228-11e5-9eb0-8b94a6cd92df.png)
![2016-01-03_14 48 02](https://cloud.githubusercontent.com/assets/15375876/12077168/13e0f77e-b229-11e5-8b74-6236d36de34f.png)
If I'm doing something wrong, I would appreciate help. If this is a bug however, please let me know so I don't just feel like a colossal moron.

**Comment by dj3520** [comment]
I don't see anything particularly wrong. Does the kenesis pipe carry energy to the refinary? (The blue beam inside is present)

**Comment by DarianLStephens** [comment]
I am certain that they do, assuming the huge blue light travelling from the engines into the refinery when I place it is energy (Which I know it is).

**Comment by dj3520** [comment]
Could you post a list of mods you're using?

**Comment by DarianLStephens** [comment]
![industrialmods](https://cloud.githubusercontent.com/assets/15375876/12077953/e23b9742-b250-11e5-8fba-b7341c5c49d9.PNG)
For some reason, I'm getting a feeling that it could be Galacticraft... But I don't know; it's just a hunch.

**Comment by psxlover** [comment]
Are you sure what you are using is Buildcraft oil?

**Comment by DarianLStephens** [comment]
Well, it came from one of those oil spouts and the engines seem to use it fine, so I'm pretty sure.
Also, in the creative world, I got the oil I was using from a bucket in the Buildcraft creative tab.

**Comment by SandGrainOne** [comment]
Could you try and see if it helps to update GalactiCraft? Your version is a little old.
http://www.micdoodle8.com/mods/galacticraft/downloads

**Comment by DarianLStephens** [comment]
I didn't realize Galacticraft had a new version out... Everything seems to be working perfectly now! Thank you all for your help!
![2016-01-03_21 48 30](https://cloud.githubusercontent.com/assets/15375876/12078384/c246d3f8-b263-11e5-93cf-c2df2b1058d0.png)
