### ISSUE TITLE
Add custom item stack handling options for the Filler

### ISSUE THREAD

**Issue by PsionicArchon** [BuildCraft/BuildCraft#3177]
I'm pretty sure this has been a known issue for some time now. I was watching a YouTuber by the name of nonsanity who was also experiencing issues with multiparts several months ago.

Using the latest version of Buildcraft, the Filler will not place multiparts. It spews them onto the ground instead. The Builder simply deletes them.  

In past versions of Buildcraft I had no issues what so ever with auto placing multiparts using a Builder. I'm assuming the problem lies exclusively with Buildcraft and not the multipart api.

**Comment by AEnterprise** [comment]
do you have BC compat installed? that adds support for microblocks

**Comment by PsionicArchon** [comment]
The latest version of BC Compat is installed. It's only the filler and builder that appear to be having issues. Either my multiparts are deleted outright or chucked into the ground. I haven't tested robots yet to see if they're willing to autoplace multiparts.

**Comment by asiekierka** [comment]
The Filler does not support multiparts, indeed, and won't for quite some time - there is no mechanism by which it could properly support it.

**Comment by AEnterprise** [comment]
the blueprint system has been changed since, normaly the dev should implement this kind of support but forge is getting it's own mulipart system (https://github.com/MinecraftForge/MinecraftForge/pull/2984) i sugest we wait for that and add native BC support

**Comment by AlexIIL** [comment]
Yeah due to pipes most likely using the forge multipart system in 8.0.x proper support for other microblocks will be added at that time as well.

**Comment by AlexIIL** [comment]
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)
