### ISSUE TITLE
Auto Workbench does not accept items from pipes

### ISSUE THREAD

**Issue by mnybon** [BuildCraft/BuildCraft#3178]
I have encountered a bug on my friends server where the Auto Workbench will not accept items from buildcraft pipes.
I have tried wooden pipes, stone pipes and gold pipes. In every case the item goes past the auto-workbench, even if that item is part of the workbench's recipe. The workbench is in no way full. This is a problem with both old previously placed workbenches. The Buildcraft version on the server is 7.1.14.

I can't get it to recieve items from hoppers either. I have tried from the top and two sides. It does accept items if pushed via a ejector upgraded industrialcraft machine.

**Comment by AlexIIL** [comment]
That's an odd bug, could you make some screenshots of your setup please? Something strange might be happening that you haven't noticed :)

**Comment by mnybon** [comment]
![2016-01-07_20 50 37](https://cloud.githubusercontent.com/assets/10414115/12181131/b9b30d18-b580-11e5-8377-ee4f364ec52d.png)


There are a number of these, some with diamond pipes, others with stone(For round-robin).
When i remove the auto workbench and replace it with a chest, the items (Aluminium ingots in this case) are put into the chest just fine. When i put the workbench back, not so much.

**Comment by mnybon** [comment]
Ooh, and it worked before we updated to the latest version. This entire setup has been running fine for weeks until it, well, stopped working.

**Comment by SandGrainOne** [comment]
Have you defined a recipe?

**Comment by mnybon** [comment]
Yes. They are all making different kind of blocks: Aluminium, Iron, Tin, Copper, Coal, whathaveyou.

**Comment by mnybon** [comment]
And if i just place the ingots directly in the table, it crafts just fine.

**Comment by XpertikPro** [comment]
place a chest next to the automatic crafting table, connect pipe to the chest.

**Comment by smbarbour** [comment]
What version were you using prior to 7.1.14?

**Comment by n00b7** [comment]
i think container in the block is broken:

check this class:

buildcraft.factory.gui.ContainerAutoWorkbench

**Comment by AEnterprise** [comment]
@n00b7 the container has nothing to do with this, as you also said the package you should know that the container belongs with the GUI. the items don't go in at all so it isn't the gui it's the TE.
