### ISSUE TITLE
Quarry wont mine blocks.

### ISSUE THREAD

**Issue by garnerfenoms** [BuildCraft/BuildCraft#3179]
I was about to set up a quarry and i fed it power and a place to store the items and it looks like its about to mine but then it doesn't it will move the mining pick but it wont destroy the blocks it just keeps going and going but does nothing. I'm wondering if anyone else is having this problem

**Comment by AlexIIL** [comment]
What version of BuildCraft are you using?

**Comment by garnerfenoms** [comment]
im using 7.1.14. with buildcraft compat 7.1.3

**Comment by psxlover** [comment]
Singleplayer?

**Comment by garnerfenoms** [comment]
Multiplayer

**Comment by psxlover** [comment]
Did you perhaps set the quarry near the spawn point? Or is there a protection mod?

**Comment by garnerfenoms** [comment]
I did set it out where there was no protection or anything like that.

**Comment by garnerfenoms** [comment]
It seems that if i get rid of the towny plugin the quarry works just fine. im looking in the config files for anything buildcraft related

**Comment by AEnterprise** [comment]
try making the BC fake player an OP with the command, that might alow it to bypass the protection

**Comment by asiekierka** [comment]
Yes, it will. Try "/buildcraft op".

2016-01-09 11:55 GMT+01:00 AEnterprise <notifications@github.com>:

**Comment by garnerfenoms** [comment]
Its working! Thanks guys for all your help! :D
