### ISSUE TITLE
The picker robot doesn't work with other station!

### ISSUE THREAD

**Issue by Pharaoh321** [BuildCraft/BuildCraft#3180]
With the home station picker works well.Robot can pick up items and don't standing only on station.But if the robot stands on other station, it cant move more.
Warning:my english is very bad!

**Comment by Nosnamreh** [comment]
Hi there! I'm not an expert, but I'll try to help anyway.

I think the Picker needs a docking station with a gate set to "Accept items." Failing that, it may just dump items into its home dock.

Is your pipe set to accept items?

**Comment by AEnterprise** [comment]
pictures of your setup and gate configurations would help, you could also try the forums, there are alot of threads of people asking help with robot setups not working, you might be able to find an awnser there (or ask it there)

**Comment by asiekierka** [comment]
Not enough information.
