### ISSUE TITLE
[7.2.0-pre6] Crash: Compatibility issue with Tinkers' Construct (1.8.8-2.0.1)?

### ISSUE THREAD

**Issue by Xiaminou** [BuildCraft/BuildCraft#3183]
Crashed when I placed a Golden Transport pipe in a Tcon Crafting Table. I tried removing the rendering but that didn't fix it.
(reported on both githubs)
Edit: as expected, disabling Buildcraft fixed it. However it seems like the option to disable render on of Tcon's table does not work. They still render items even when the option is set to false. Which means my first theory might be right.

Crash Report: http://pastebin.com/q4hMaaiL

**Comment by AlexIIL** [comment]
Related to https://github.com/SlimeKnights/TinkersConstruct/issues/1871
