### ISSUE TITLE
Quarry builds frame then stops no arm appears either

### ISSUE THREAD

**Issue by phantom745** [BuildCraft/BuildCraft#3184]
![screenshot 9](https://cloud.githubusercontent.com/assets/4897085/12279689/3a1bedb4-b94e-11e5-9626-7bd46f7e1060.png)

**Comment by AEnterprise** [comment]
what's your BC version?

**Comment by phantom745** [comment]
Buildcraft 7.1.14

**Comment by asiekierka** [comment]
Singleplayer? Multiplayer? Is Bukkit/OptiFine/FastCraft involved?

**Comment by phantom745** [comment]
Singleplayer with Optifine though the bug still persists when Optifine is removed.

**Comment by asiekierka** [comment]
Is it close to spawn or not? I'm out of ideas.

**Comment by phantom745** [comment]
Ummm... yeah I think its like 100-200 blocks from spawn

**Comment by AEnterprise** [comment]
can you give a full modlist?

**Comment by phantom745** [comment]
[mod-list.txt](https://github.com/BuildCraft/BuildCraft/files/189718/mod-list.txt)

**Comment by AEnterprise** [comment]
that's a very long modlist, can you replicate with just BC? if not can you find the min modset to that causes this?

**Comment by phantom745** [comment]
I was assuming it was another mod not buildcraft's fault, but I have moved on so if the problems comes up again I will more thoroughly investigate it.

**Comment by AEnterprise** [comment]
since nobody has been able to verify for this long this can be closed

**Comment by AlexIIL** [comment]
Yeah, feel free to reopen this though if you do encounter it again @phantom745
