### ISSUE TITLE
[7.2.0-pre6] Crash when browsing BC Facades in JEI (compatibility issue with Chisel?)

### ISSUE THREAD

**Issue by Xiaminou** [BuildCraft/BuildCraft#3185]
Crashes whenever I browse any of the buildcraft facades.

Crash Report: http://pastebin.com/3ehjC9D6

**Comment by LuigiHutch** [comment]
Please Report Here: https://github.com/AlexIIL/Buildcraft_1.8_Issues/issues
This is where the issues for the BC 1.8 port are located
