### ISSUE TITLE
Buildcraft & Towny compatibility for 1.7.10 issues

### ISSUE THREAD

**Issue by djoveryde** [BuildCraft/BuildCraft#3186]
Hi, I have just made a Tekkit Legends server with the towny plugin added.
We have attempted to use a Quarry however it seems its unable to break the blocks. This is even outside town protection. We have tried it in various locations.
What happens is it shows the grid. Then it half builds the frame and stutters along, begins to break the block then doesnt and the grid flashes and dissapears. Then it starts again.

Im using GroupManager for the permissions.

I dont want to OP the buildcraft fake player mainly because I dont want other players ripping apart players towns or spawn.

There must be a way to fix this without making buildcraft OP

**Comment by dj3520** [comment]
Have you done /buildcraft op ?

**Comment by djoveryde** [comment]
Doesn't that allow buildcraft to bypass everything though?

**Comment by asiekierka** [comment]
It does, however it is otherwise complicated to give BuildCraft the
necessary permissions. If you can add UUIDs to Towny directly, look in the
server startup log for BC's.
15 sty 2016 11:53 "djoveryde" <notifications@github.com> napisał(a):
