### ISSUE TITLE
Miner not recognizing certain ores [1.7.10]

### ISSUE THREAD

**Issue by Nosnamreh** [BuildCraft/BuildCraft#3189]
I set up several Miner and Picker robots in a cave, and waited until they all came back to their stations for good. After surveying the cave, I found the following ores NOT mined:

-Yellorite (Big Reactors)
-Osmium (Mekanism)
-All Infused Stone (Thaumcraft)

I have Buildcraft-Compat installed, and insured the blocks were within the robots' radius. Oddly enough, the following ores WERE mined:

-Tin and Copper (Mekanism)
-Amber and Cinnabar (Thaumcraft)

If this is a repeat issue, I apologize, similarly if I'm barking up the wrong tree. Absolutely fabulous mod, can't wait to see what's added/updated for 1.8.9. :D

Edit 1: Miners were using vanilla Diamond Pickaxes

Edit 2: Have reached out to respective developers.

https://github.com/aidancbrady/Mekanism/issues/3078
https://github.com/erogenousbeef/BigReactors/issues/559
(Erogenous Beef has disappeared from modding, at least for a while. This is the issue posted to the maintainer's github: https://github.com/Tomson124/BigReactors/issues/1)
https://github.com/Azanor/thaumcraft-5/issues/323 (Azanor has upgraded the things on his end.)

**Comment by AlexIIL** [comment]
Sorry for not responding to this when I first saw it, I assume the not-mining is due to the way the blocks in the mods works- but I'll look into this a little bit to see if it really is a buildcraft issue

**Comment by hea3ven** [comment]
The miner robot can dig any block whose ore name starts with "ore": https://github.com/BuildCraft/BuildCraft/blob/7.2.x/common/buildcraft/core/properties/WorldPropertyIsOre.java#L27 . It's probable that those ores have a naming scheme that doesn't match this expectation.

**Comment by Nosnamreh** [comment]
Hmm, okay. Should I go poke Azanor, Erogenous Beef, and Aidan?

**Comment by AlexIIL** [comment]
Thanks @hea3ven, however according to https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/Mekanism.java#L926-L928 all 3 start with "ore" so I assume the issue is todo with something more than just that.

**Comment by AlexIIL** [comment]
Asking the other mod authors might be a good idea :) (In a worst case scenario we might need to add a "white-list" or something similar to allow for any custom ores to register themselves (for example from BC|Compat)

**Comment by SandGrainOne** [comment]
Isn't there ways for mods to tell each other through an API what kind of requirements there are for breaking a block? Can a robot with a wooden pick break Iron Ore?

**Comment by Nosnamreh** [comment]
Oh, oops! I should've mentioned: All Miners were given vanilla diamond pickaxes.

**Comment by AlexIIL** [comment]
Just having the requirement to be able to break a block isn't enough unfortunately, as cobblestone can be broken with just a wooden pick, but we don't want a miner to break it.

**Comment by AlexIIL** [comment]
Sorry, I forgot to ask: Is this 1.8.9 or 1.7.10? I assumed 1.7.10 but I might be wrong...

**Comment by Nosnamreh** [comment]
Oops!

1.7.10. Thaumcraft is the only mod available to the general public for 1.8.9, of those involved.

[taps foot, updates OP]

**Comment by AlexIIL** [comment]
Thanks :)

**Comment by Nosnamreh** [comment]
Maybe I'm just being stupid, but I don't see it.

http://www.curse.com/mc-mods/minecraft/buildcraft#t1:other-downloads
http://minecraft.curseforge.com/projects/buildcraft/files

I don't doubt you, I just can't find it anywhere. Where have all these new mods been uploaded? D=

**Comment by AlexIIL** [comment]
Sorry, I've kept the releases away from curse and the official BC website because its in alpha, so I've been pushing them to the forums (http://www.mod-buildcraft.com/forums/showthread.php?tid=1853&pid=18186#pid18186)

**Comment by Nosnamreh** [comment]
Oh wow. That makes sense. Color me very pleasantly surprised. =D

**Comment by Nosnamreh** [comment]
And, we're just waiting on Mekanism and Big Reactors.

**Comment by Tomson124** [comment]
As erogenousbeef seems to quit modding (at least for now), me and probably some other guys will maintain BigReactors. I recently updated it and all dependencies it had including Buildcraft, but I didn't tried it yet if that did the thing... Maybe you could do so and post me an issue on my Github repo if it is still not working.
https://github.com/Tomson124/BigReactors/releases

**Comment by Nosnamreh** [comment]
I have tested it, and it does not fix the issue. But thanks for the response and the dev update, glad I could help.

**Comment by asiekierka** [comment]
Not our issue.
