### ISSUE TITLE
Seems pumps cause ConcurrentModificationException

### ISSUE THREAD

**Issue by BlazingGamer** [BuildCraft/BuildCraft#3191]
Hello! Seems I found an issue...
I have 2 pumps in nether (maybe same chunk, maybe different, don't remember that). They both pump lava to tanks. When I go through portal to nether the game crashes with this error: http://codepad.org/u9h2fefI. I'm sure this is BC bug because before I put 2 pump - golden fp - tank constructions all worked fine. Also when I load that world after NetherPortal crash I get 1 more SAME crash, and then all seems working. Please fix or describe what do I do incorrectly!

**Comment by AlexIIL** [comment]
Hi, can you tell us what version of BC you are using? It would also be helpful to know what other mods you are using (the easiest way for you to do this would be to copy-paste the last 100 or so lines from "latest.log" into [gist](https://gist.github.com/))

**Comment by BlazingGamer** [comment]
Hello, I'm usin' BC 7.1.14 and here is mod list (took from Crash Report): http://codepad.org/iSiNl31v. Thanks in advance!

**Comment by BlazingGamer** [comment]
Also, if problem is with chunk loading, can RailCraft Anchor/BC Quarry/MFR Chunkloader fix this?

**Comment by AlexIIL** [comment]
A chunk loader might make a difference- however if you can duplicate this in a creative world (mostly so you don't have to spend resources on testing different things) I would be interested if it does make a difference. Another thing to try is just retrying to make the bug- I'm quite interested in what the other thread is doing while it crashes. (That assumes it is caused by multiple threads locking up)

**Comment by AlexIIL** [comment]
De obfuscated stack trace:
````
at Chunk.onChunkUnload()
at ChunkProviderServer.unloadQueuedChunks()
````
OnChunkUnload:
````java
...
Iterator iterator = this.chunkTileEntityMap.values().iterator();
while (iterator.hasNext())
{
    TileEntity tileentity = (TileEntity)iterator.next(); // ConcurrentModificationException
    this.worldObj.func_147457_a(tileentity);
}
...
    
````

(These are my notes to help for later if I can)

**Comment by BlazingGamer** [comment]
I know that (somewhile ago was creating mods and have decomp-workspace). I don't believe in that 
![2016-01-25_21 28 13](https://cloud.githubusercontent.com/assets/13196222/12560348/41354e44-c3ab-11e5-967d-3e9dab6b5685.png)
screenshot..

**Comment by BlazingGamer** [comment]
I believe it doesn't cause that :)

**Comment by BlazingGamer** [comment]
Nope, still crashes after fixing lava... I think it's Redstone Engines but not sure.

**Comment by AEnterprise** [comment]
can you try it without fastcraft? this type of exception is usually caused by 2 different threads modifying the same arraylist (arraylists are not threadsafe)

most likely fastcraft (or another mod) is doing something with that list of TE's in the same tick as when the chunk gets unloaded

**Comment by BlazingGamer** [comment]
Seems I found it, the problem were RedStone Engines (When I tested on creative I used Admin Engines, those are issue-3191-free). Will test with just using Energy Cell instead of Engines and then with Engines but W/Out FastCraft, then tell.

**Comment by BlazingGamer** [comment]
With using Magma Dynamo (TE4) all worked, w/out FastCraft - randomly working & not working. But I see RS engines are VERY glitching...
![2016-01-29_18 45 21](https://cloud.githubusercontent.com/assets/13196222/12680049/d7ac4b38-c6b8-11e5-9d69-0ee42fb6460e.png)

**Comment by asiekierka** [comment]
!?
