### ISSUE TITLE
Logistics Pipes and BuildcraftCompat comaptible

### ISSUE THREAD

**Issue by darkbumerang** [BuildCraft/BuildCraft#3196]
Logistics Pipes 0.9.3.70, BC Compat 7.1.13  and BC 7.1.14, minecraft 1.7.10.
Crash Error in uploaded file
[crash-2016-02-01_21.29.45-client.txt](https://github.com/BuildCraft/BuildCraft/files/112804/crash-2016-02-01_21.29.45-client.txt)
what to do?
Without BCCompat mod, game starts normally with plug logistics pipes

**Comment by asiekierka** [comment]
You're gonna need a copy of CoFHLib, my friend! Not sure why, though.
