### ISSUE TITLE
Quarry not working on my server

### ISSUE THREAD

**Issue by Mordara** [BuildCraft/BuildCraft#3202]
Build
![2016-02-08_21 42 47](https://cloud.githubusercontent.com/assets/17127522/12893838/f87c413c-ceac-11e5-8852-27d8bcac1007.png)
![2016-02-08_21 42 48](https://cloud.githubusercontent.com/assets/17127522/12893839/f87fb7f4-ceac-11e5-92c0-3ed98a4dff05.png)
![2016-02-08_21 42 48_2](https://cloud.githubusercontent.com/assets/17127522/12893837/f87afa3e-ceac-11e5-967c-2e1098b8f7d9.png)

craft I added to Privat and errors in the console no .

**Comment by dj3520** [comment]
Not completely sure what I'm seeing in the screenshots. Try /buildcraft op and see if that solves your problem.

**Comment by Mordara** [comment]
Here is a video about my problem , and the team didn't help https://www.youtube.com/watch?v=xB1k59ZttGk&feature=youtu.be

**Comment by MoreThanHidden** [comment]
'/Op [Buildcraft]' without the quotes should work.

**Comment by asiekierka** [comment]
No. Use /buildcraft op instead.-------- Wiadomość oryginalna --------Temat: Re: [BuildCraft] Quarry not working on my server (#3202)Od: "MoreThanHidden (John816)" Do: BuildCraft/BuildCraft DW: '/Op [Buildcraft]' without the quotes should work.

**Comment by MoreThanHidden** [comment]
/buildcraft op was already suggested, please advise buildcraft version and other mods or plugins.

**Comment by Mordara** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/17127522/12945939/413f5874-d00a-11e5-9e80-0e9bececb137.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/17127522/12945940/4141fa5c-d00a-11e5-8d4d-72d1212273b8.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/17127522/12945941/414297dc-d00a-11e5-8b81-9464b31bedae.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/17127522/12945942/4142e4e4-d00a-11e5-869b-0f048e4baa04.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/17127522/12945943/41434038-d00a-11e5-93d6-75bc0fec04aa.png)

**Comment by asiekierka** [comment]
Almost all of your mod versions are more than half a year old. They also have shady filenames. :-(

Dnia 10 lut 2016 o godz. 12:23 Mordara <notifications@github.com> napisał(a):

**Comment by MoreThanHidden** [comment]
It was as I thought well before 7.1x and therefore no "/buildcraft op", and it also has world guard which could also be causing build prevention depending on settings aswell :disappointed:

**Comment by Mordara** [comment]
I tried and the latest version of the mod and still not working

**Comment by MoreThanHidden** [comment]
"/buildcraft op" on the latest version will sort out the base game quarry issues, but anything could be happening with the AuthMe, Permissions EX and World Guard configs.

looks like the AuthMe is your issue though:
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/pages/how-to-install-and-initial-configuration/

**Comment by dj3520** [comment]
I had no luck with Authme in my experiences even after /buildcraft op 
and having buildcraft's fake player set to bypass Authme completely. 
Disabling it immediately saw results. In your case PermissionsEx might 
also cause problems, though I'm not sure if OP grants you building 
permissions.

**Comment by asiekierka** [comment]
Bukkit plugins are fun to work with! :D
