### ISSUE TITLE
Can i download a version of buildcraft for 1.8 ( not 1.8.x ) compatible with sponge ?

### ISSUE THREAD

**Issue by qwertyazerty** [BuildCraft/BuildCraft#3203]
All is in the title !

**Comment by AlexIIL** [comment]
Sorry, I missed this completely before! I should be able to do it tomorrow.

**Comment by AlexIIL** [comment]
This is a version that *should* work with spongeforge for 1.8. whenever you can update sponge to 1.8.9 I would highly recommend you do so (and keep in mind that you need to use a 7.2.0-migration version to update properly)

https://www.dropbox.com/s/dgi51t8tsj401wb/buildcraft-0.15-alpha-sponge-compat.jar?dl=1

**Comment by qwertyazerty** [comment]
Tanks ! I can't upgrade to 1.8.9 because all other mods I use doesn't support this....

**Comment by AlexIIL** [comment]
Sorry, I meant to say that whenever all the mods you use update to 1.8.9, I recommend that you update quickly :)

**Comment by qwertyazerty** [comment]
But there is mods made by myself and others who is updating.....

**Comment by qwertyazerty** [comment]
On server the entity quarryarm isn't registered. And when I use quarry I crash.

**Comment by AlexIIL** [comment]
Thats not good... however I'm not supporting it as its a very old version by now. (its way too much work for me)

**Comment by qwertyazerty** [comment]
I muse wait apparently....

**Comment by asiekierka** [comment]
Sorry. 1.8.0 is not supported.-------- Wiadomość oryginalna --------Temat: Re: [BuildCraft] Can i download a version of buildcraft for 1.8 ( not 1.8.x ) compatible with sponge ? (#3203)Od: qwertyazerty Do: BuildCraft/BuildCraft DW: I muse wait apparently....

**Comment by qwertyazerty** [comment]
Apparently i am going to must do it myself.... It while take à while....

**Comment by qwertyazerty** [comment]
Apparently, it si not going to have a buildcraft working 1.8 version...
