### ISSUE TITLE
TileBuilder lag

### ISSUE THREAD

**Issue by kenvix** [BuildCraft/BuildCraft#3205]
It began to lag when the chunks are loaded
![20160212140118](https://cloud.githubusercontent.com/assets/4546175/13000130/800b4fee-d191-11e5-9242-de8e31c263d5.png)

Buildcraft version: 7.1.14
KCauldron version 1.7.10-1614.175 (MC: 1.7.10)

**Comment by AEnterprise** [comment]
what is that one builder doing? is it trying to build something?

**Comment by kenvix** [comment]
Sorry,I'm not sure...

**Comment by loordgek** [comment]
is it building something bigger then 64 x 64 x 64

**Comment by asiekierka** [comment]
1. Download http://files.player.to/sampler-1.58.jar on both client and server
2. /sampler start
3. Wait a few minutes
4. /sampler stop
5. /sampler export <filename>
6. Copy <filename> from .minecraft and send it on this issue

**Comment by asiekierka** [comment]
Closed due to lag of input. (For future readers, updating KCauldron or not using KCauldron might help.)
