### ISSUE TITLE
[QUESTION] Porting To PE

### ISSUE THREAD

**Issue by CrazyWolfy23** [BuildCraft/BuildCraft#3208]
Hi, I'm a mcpe addon maker, and I was wondering if I could have permission to port this mod to minecraft: pe? I promise ill give full credits to everyone who made BuildCraft for pc. Thank you for Reading.

**Comment by asiekierka** [comment]
From who? All 150 developers? Impossible.

Read the license carefully.

2016-02-15 21:24 GMT+01:00 CrazyWolfy23 <notifications@github.com>:

**Comment by AEnterprise** [comment]
BC licencing is a bit of a clutter due to the massive amount of developers

if you want to make an addon that doesn't drag allong this license stuff from BC i sugest to base your addon on BC instead

**Comment by Techokami** [comment]
@AEnterprise He's not making an addon, he wants to port BC from the Java-based version of the game to Minecraft Pocket Edition. Which would be really painful because they're done in different programming languages... honestly it might be a better idea for @CrazyWolfy23 to create a *new* mod from scratch for Pocket Edition, using BuildCraft as a reference implementation of things like pipes?

**Comment by AEnterprise** [comment]
@Techokami yeah i know, you just said the same thing i ment, for MCPE they don't speak of 'mods' but 'addons'

**Comment by gjgfuj** [comment]
If you follow the license... There'd be no problem.

**Comment by asiekierka** [comment]
To put it in clearer terms: we hold no trademark on the BuildCraft name nor
have we patented the ideas, however the source code may only be used under
the terms of the license. We don't give endorsement blindly - if your work
is good, we'll definitely notice it. If someone shouts at you for "NOT
GETTING EXPLICIT PERMISSIONS LOLOLOL", well... Why would you need them?

2016-02-16 20:21 GMT+01:00 Sandra <notifications@github.com>:

> If you follow the license... There'd be no problem.
>

**Comment by CrazyWolfy23** [comment]
Thank you for the help. I'll start work on 'BuildCraftPE' soon.
