### ISSUE TITLE
Closed pipes don't reopen

### ISSUE THREAD

**Issue by MichaelEbert** [BuildCraft/BuildCraft#3209]
In buildcraft 1.7.14 for minecraft 1.7.10, when a gate is set to close a pipe upon some criterion (redstone signal, pipe wire signal, energy stored, anything), when that criterion becomes false, the pipe fails to reopen. This works with energy, fluid, and item pipes. The only way that I have found to reopen the pipe is to manually toggle the effect of the gate to something else.

**Comment by AlexIIL** [comment]
It works slightly differently than what you think- the close valve action just closes the pipe off whenever it is activated. It does not hold it off, so there is an open valve action that will open the pipe back up again.

**Comment by hea3ven** [comment]
That's how the trigger works, once you set the pipe to close, it will stay closed until you trigger the open action. See #2597.
