### ISSUE TITLE
Knight Robots not dropping/unloading weapons

### ISSUE THREAD

**Issue by chemdork123** [BuildCraft/BuildCraft#3211]
Knight robots are not able to drop or unload weapons... at all.  Other robots (such as the Lumberjack) are unloading/loading weapons fine, but Knight robots continue to use swords when they would theoretically be past the breaking point (based on number of hits).  Same case for wooden and stone swords, enchanted or not enchanted, and pre-damaged or new.  Creative and in survival mode.  Effectively makes knight robots useless - am I the only one having this issue?

Versions:
MC 1.7.10
BC 7.1.14
BC Compat 7.1.3
forestry 3.6.7.25
CofHCore 3.0.3-303
Thermal foundation 1.2.0-102
Thermal Expansion 4.0.3B1-218
Thermal Dynamics 1.1.0-161

**Comment by asiekierka** [comment]
Should be fixed in 7.1.16/7.2.1.

(Don't upgrade to 1.8 yet. There's bugs with migrating over 1.7.10 worlds in Forge itself to be resolved, and while Forestry might be out soon, I don't know if CoFH's mods will.)

**Comment by chemdork123** [comment]
Oh, I think I'm still going strong on season 2... although probably getting closer to doing a reset.  Thanks, this should really help make Knight robots functional.

**Comment by asiekierka** [comment]
Yes, I recommend you don't do a reset until Minecraft 1.9 - Thermal
Expansion 4.2 and BuildCraft 8.0 will likely both be breaking to worlds,
and Forestry already was with the release of 4.0.

2016-03-18 15:55 GMT+01:00 chemdork123 <notifications@github.com>:
