### ISSUE TITLE
Certain entities are not registered with Forge's EntityRegistry

### ISSUE THREAD

**Issue by Aaron1011** [BuildCraft/BuildCraft#3212]
The [SpongeForge](https://github.com/SpongePowered/SpongeForge) project relies on all mod entities being registered through Forge's `EntityRegistry`, in order to implement parts of [SpongeAPI](https://github.com/SpongePowered/SpongeAPI).

However, it seems that BuildCraft doesn't register `EntityMechanicalArm` (and possibly more entities - I haven't done an exhaustive search). If BuildCraft could ensure that all of its entities are registered through Forge, we'd greatly appreciate it!

**Comment by asiekierka** [comment]
These entities exist solely on the client side, as far as I'm aware, which
is why they are not registered.

2016-02-27 16:30 GMT+01:00 Aaron Hill <notifications@github.com>:

**Comment by asiekierka** [comment]
Why would SpongeForge need to ever manipulate EntityMechanicalArm?

**Comment by Aaron1011** [comment]
@asiekierka: In answer to your first response, it appears to be referenced in `TileQuarry`, which is referenced server-side through `BlockQuarry`.

SpongeForge doesn't directly touch any mod entities. However, by its nature of having to implement an entire plugin API, it transforms core Forge classes, such as `EntityRegistry` (code [here](https://github.com/SpongePowered/SpongeForge/blob/master/src/main/java/org/spongepowered/mod/mixin/core/fml/common/registry/MixinEntityRegistry.java).

We transform `EntityRegistry` in order to expose all registered entities through our API, and generate an `EntityType` for them. Since `EntityMechanicalArm` is not registered, it ends up without an `EntityType`, causing problems without our codebase.

**Comment by AlexIIL** [comment]
Oh woops- the arm shouldn't have been added to the world.

**Comment by AlexIIL** [comment]
No, how did this ever work in vanilla without registering it? Odd.

**Comment by AlexIIL** [comment]
Oh right, it doesn't save+load atm.

**Comment by AlexIIL** [comment]
That should fix the issue, whenever pre13 comes out.
