### ISSUE TITLE
Null values are stored in NBTTagCompound

### ISSUE THREAD

**Issue by Aaron1011** [BuildCraft/BuildCraft#3213]
In several places, BuildCraft stores `null` as a value in an `NBTTagCompound` (for example, `Box#writeToNBT`). This causes an exception when calling `NBTTagCompound#copy`, which expects all values to be non-null.

**Comment by AlexIIL** [comment]
Thanks, I was wondering where the error was coming from,

**Comment by AlexIIL** [comment]
The fix will be in pre13.

**Comment by Cleardragonf** [comment]
an where would we find this pre13?

**Comment by AlexIIL** [comment]
It's not out quite yet, sorry.
