### ISSUE TITLE
Builder builds Carpenter's blocks only in Creative mode

### ISSUE THREAD

**Issue by SpectralEye** [BuildCraft/BuildCraft#3214]
Hello.

I have lastest version of BC and Carpenter's blocks, and Builder just doesn't see Carpenter's Blocks in Survival mode, though it does that in Creative. There are no excluded mods or blocks in the config file. How can I fix it?

**Comment by LuigiHutch** [comment]
Do you have BC Compat installed? You have BC 7.1.14 correct?

**Comment by SpectralEye** [comment]
I installed BC Compact and it solved the problem. Thanks a lot!

**Comment by LuigiHutch** [comment]
Heh, no problem. Please close :)
