### ISSUE TITLE
Diamond pipes should split item stacks in weighted ratio

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildCraft#3215]
Might want to hold off until pipe rewrite.

**Comment by AEnterprise** [comment]
probably for 8.0 i guess?

**Comment by AlexIIL** [comment]
yep :)

**Comment by AlexIIL** [comment]
Implemented in https://github.com/BuildCraft/BuildCraft/commit/e6929c9437038d59103f566980a52f1f5f7db908
