### ISSUE TITLE
Auto workbench fuzzy detection bug

### ISSUE THREAD

**Issue by Droxtor** [BuildCraft/BuildCraft#3216]
![ss 2016-03-06 at 10 58 45](https://cloud.githubusercontent.com/assets/6633164/13553218/7e7ae8c8-e38a-11e5-8ffe-387434ab7f9c.png)
![ss 2016-03-06 at 10 59 06](https://cloud.githubusercontent.com/assets/6633164/13553219/7e7f04f8-e38a-11e5-8ba2-3ab27e3a8088.png)

**Comment by asiekierka** [comment]
Try BuildCraft 7.1.15, or wait a bit longer if you're on 1.8.
