### ISSUE TITLE
quarry has issue with progressive automation

### ISSUE THREAD

**Issue by whyo2** [BuildCraft/BuildCraft#3217]
so I placed a quarry (with a diamond chest on top) next to a fully charged iron generator from progressive automation and nothing happened. I then tried to put a pipe between the two and i received this crash.

https://pastee.org/6kccm

Any ideas whats happening?

**Comment by AlexIIL** [comment]
You should update to pre12. pre6 is a pretty old version by now :)

**Comment by AlexIIL** [comment]
The download links are [here](https://github.com/AlexIIL/BC-Temp-releases/releases/tag/7.2.0-pre12) and information on what they are is [here](https://github.com/AlexIIL/BC-Temp-releases/blob/master/README.md)
