### ISSUE TITLE
Older version of Forestry crash

### ISSUE THREAD

**Issue by Shadowmaster94** [BuildCraft/BuildCraft#3218]
the issue is that when using core or the normal one it does not work at all. when added to the core it simply crashes and refuses to load into the client. crashing before it reaches the main menu.

**Comment by AlexIIL** [comment]
Can we have the crash report? We can't help you without it...

**Comment by Shadowmaster94** [comment]
[crash-2016-03-08_12.40.37-client.txt](https://github.com/BuildCraft/BuildCraft/files/163659/crash-2016-03-08_12.40.37-client.txt)

there is the crash report.assuming the thing uploaded it right

**Comment by AlexIIL** [comment]
You have an older version of forestry that is not compatibly with buildcraft 7.1.14.

If you want to stick with forestry 3 the you should update to ````3.6.11```` available [here](http://minecraft.curseforge.com/projects/forestry/files/2261593) and install bc compat if you want to use the bee propolis pipe.

**Comment by Shadowmaster94** [comment]
so if i update foresty and such then if i add transport pipes to the pack of mods i'm using then it will work?

**Comment by AlexIIL** [comment]
Hopefully yes :)

**Comment by AlexIIL** [comment]
You don't *have* to add BC|Compat, however if you want to use the propolis pipe then you will have to (it was moved from forestry to bc|compat)

**Comment by Shadowmaster94** [comment]
everything is fixed there for yes this is closed.
