### ISSUE TITLE
[1.8.9] Tanks can't accept fluids from Universal Bucket.

### ISSUE THREAD

**Issue by AlgorithmX2** [BuildCraft/BuildCraft#3219]
Possible solution: net.minecraftforge.fluids.FluidUtil.interactWithTank

**Comment by asiekierka** [comment]
We're already using interactWithTank - at least in the latest source tree, so anything released after the 18th of February.

**Comment by AlgorithmX2** [comment]
Ok, I have an older build, carry on!
