### ISSUE TITLE
[Very Minor] Update copyright to 2016

### ISSUE THREAD

**Issue by dj3520** [BuildCraft/BuildCraft#3220]
Because the old notice is so last year yo
>Copyright (c) the BuildCraft team, 2011-2015

**Comment by AlexIIL** [comment]
*assigns some-one else*

**Comment by dj3520** [comment]
Is there any internal values in the code that have "2015" in them? If not I
could do a recursive replace and put in a pull request. I don't know Java
but it should be simple, no?

**Comment by AlexIIL** [comment]
Yeah, theoretically it's that simple. If it turns out we were wrong then we will spot it in the PR :)

**Comment by AEnterprise** [comment]
use a recursive search and replace that replaces the entire line, that'll prevent any code getting messed up

**Comment by asiekierka** [comment]
Nah, I'll handle it. Don't worry.

2016-03-13 10:39 GMT+01:00 AEnterprise <notifications@github.com>:

**Comment by dj3520** [comment]
Ok asie

**Comment by AEnterprise** [comment]
we're halfway the year, copyright still hasn't changed, should i do it or someone else? i guess leaving it as is isn't a good idea?

**Comment by AlexIIL** [comment]
Its too minor to matter, and hopefully they will all be changed when I relicense BC to MPLv2 with my parts as MIT.
