### ISSUE TITLE
Quarry issue

### ISSUE THREAD

**Issue by ImDimchkee** [BuildCraft/BuildCraft#3221]
Server Mod list Here - https://github.com/ImDimchkee/IEissuehelppls
Server core KCauldron1614
In sigle player everything work's fine, and on Forge server work's perfect
Quarry uses energy but nothing rly happens
Yellow frame blinking, Frame didnt building, drill thing with moving frame trying to dig something but nothing rly happens
http://imgur.com/a/3y5Y9
In some chunk's drill with moving frame didnt apear

**Comment by asiekierka** [comment]
/buildcraft op, if it doesn't work blame Cauldron

**Comment by ImDimchkee** [comment]
I've authme plugin on server btw, its can be a problem??

**Comment by asiekierka** [comment]
Yes

2016-03-13 14:15 GMT+01:00 ImDimchkee <notifications@github.com>:

**Comment by ImDimchkee** [comment]
I figured out, its AuthMe plugin. Did any other plugin with authorization function wich didnt conflict with BC? Or how i can solve this problem with AuthMe? sry for my eng)))

**Comment by ImDimchkee** [comment]
I fixed it, just add some text in authme config, ty for help

**Comment by dj3520** [comment]
Which authme version do you use? I tried 3.4 & 3.5 and the "bypass
authentication for specific users" was not working.

**Comment by ImDimchkee** [comment]
3.3.3 
Just try to dont make misstake in config.yml
Send it to ur computer and open with notepad++ it will easyer

**Comment by dj3520** [comment]
Yeah I run my own server and edit files over LAN. Guess it's broken in anything super new.
