### ISSUE TITLE
The Zone Panner does not show the world on its exterior

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3223]
BC 7.2.0

The Zone Panner does not show the world on its exterior:
![2016-01-11_21 39 09](https://cloud.githubusercontent.com/assets/9326429/12247689/0db09a78-b8ad-11e5-8594-62b5d01d16a5.png)

**Comment by AEnterprise** [comment]
is this still not showing? if not is this something to look at for 7.2.x or 8.0?

**Comment by AlexIIL** [comment]
Yeah this does need looking into, but It might be later changed to 8.0.x rather than 7.2.8.

**Comment by afdw** [comment]
Implemented in 8.0.x.
