### ISSUE TITLE
Floodgate Texture + Wrenching a Floodgate

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3224]
BC 7.2.0

When creating a floodgate it looks like this (1.8):
![2016-01-14_16 30 36](https://cloud.githubusercontent.com/assets/9326429/12330359/9bbb391e-badc-11e5-9e97-a9687f0922d6.png)

When instead it is supposed to look like this (1.7):
![2016-01-14_16 36 39](https://cloud.githubusercontent.com/assets/9326429/12330431/03caf760-badd-11e5-9819-892ab0b80a79.png)

Wrenching the sides doesn't do anything, It did crash in Pre-6

**Comment by rapus95** [comment]
Nvm i expected the upper one to be the intended texture since it somehow shows that the floodgate won't place upwards but instead fluid connections are expected to be placed on the upper side of it

**Comment by AlexIIL** [comment]
Fixed in https://github.com/BuildCraft/BuildCraft/commit/d139bfb58047a66c0064707c454f1e121d618366
