### ISSUE TITLE
Lilypads cannot be placed on Oil

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3225]
BC 7.2.0

Lilypads cannot be placed on Oil. Gfycat of evidence:
https://gfycat.com/OrganicBlondArgentinehornedfrog

**Comment by laz2727** [comment]
...but why should they?

**Comment by LuigiHutch** [comment]
because its a normal fluid (not flammable) and it is very useful whe trying to place a pump on top of a oil spout

**Comment by AlexIIL** [comment]
Not fixable without breaking the way we do fluids.

It also doesn't make much sense thematically.
