### ISSUE TITLE
Path Marker has a grey tip to it

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3228]
BC 7.2.0

A path marker has an extra grey bit to it:
![2016-03-13_17 05 21](https://cloud.githubusercontent.com/assets/9326429/13730217/f40983a4-e940-11e5-812f-297c62ec7e58.png)

**Comment by asiekierka** [comment]
@AlexIIL the Path Marker might need a separate model, or some texture hacks

**Comment by AlexIIL** [comment]
Fixed with new models for 8.0.x
