### ISSUE TITLE
Gates are missing their active animations and their active gate 'glow' is incorrect

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3230]
BuildCraft 7.2.0 

Gates are missing their active animations (such as the energy pulsar animation) and their active gate 'glow' is incorrect. See images:

1.7.10:
![2015-12-20_18 13 26](https://cloud.githubusercontent.com/assets/9326429/11919263/961f4c70-a745-11e5-92ad-b8461a652ab2.png)

1.8.8:
![2015-12-20_18 06 02](https://cloud.githubusercontent.com/assets/9326429/11919247/0b22eea6-a745-11e5-9252-8d8e97d34414.png)

In both images the gates are active. In the images, the left gates have their timer on, I just didn't take the screenshots at the right time :p

Already known, just putting it here for reference :)

**Comment by asiekierka** [comment]
Found a "fix", waiting on @AlexIIL to fix pipe rendering

**Comment by AlexIIL** [comment]
This hasn't been fixed :P

**Comment by AlexIIL** [comment]
Fixed some time ago in the 8.0.x branch.
