### ISSUE TITLE
Engines don't properly power machines on multiple sides

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3234]
BC 7.2.0

Issue from: https://github.com/AlexIIL/Buildcraft_1.8_Issues/issues/84

'If you connect 2 stone engines to a single filler it runs at the same speed as if there was only a single engine. Attaching engines to kinesis pipes fixes this.'

Another way to reproduce: Place down a quarry, power it directly with 2 stirling engines from different sides. Once the engines have heated up, one engine will continue outputting 10rf/t and the other will start outputting 3rf/t and continue building up its internal temp/ rf storage.

**Comment by asiekierka** [comment]
Actually around since BC 7.0, if not earlier. Cool!
