### ISSUE TITLE
Mining well pipe collision

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3236]
BC 7.2.0

'Colliding with a Mining Pipe will make your screen a huge texture mess: http://imgur.com/a/fCw7H'

Tested in 7.2.0 and it still occurs

Reposted from: https://github.com/AlexIIL/Buildcraft_1.8_Issues/issues/127

**Comment by AlexIIL** [comment]
Fixed in https://github.com/BuildCraft/BuildCraft/commit/774683e913138cceb9edec5f54b4d05b12e0eb61
