### ISSUE TITLE
Quarry side texture doesn't change when placing a pipe next to it

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3237]
BC 7.2.0

Quarry side texture doesn't change when placing a pipe next to it.

1.7.10
![2016-03-13_21 51 35](https://cloud.githubusercontent.com/assets/9326429/13740443/bd919eaa-e9c8-11e5-83c6-038b7eac7729.png)

1.8.8
![2016-03-13_19 28 29](https://cloud.githubusercontent.com/assets/9326429/13740452/cb44205e-e9c8-11e5-947d-945ab91e693e.png)

**Comment by LuigiHutch** [comment]
This also happens with the Mining Well

**Comment by LuigiHutch** [comment]
The quarry is also missing its back face which is supposed to have the greenish square on it, but instead it has the normal side texture on the back ot it

**Comment by AEnterprise** [comment]
high priority issue that's been 'dead' for a while now with an expired milestone

**Comment by AlexIIL** [comment]
Yeah its annoying as I tried to do this in a blockstate for 1.8.9 and MC then took a few more minutes to load up all of the different possibilities of quarry models. It will be easier in 1.9 though because mojang added "if" statements to blockstate.

**Comment by AEnterprise** [comment]
quarry is being rewritten, will be fixed
