### ISSUE TITLE
Add 1.8 additions builder support, fix rails and paintings

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3239]
BC 7.2.0

Here are a list of blocks from vanilla I have found are unsupported so far:
- [x] Armor Stands
- [ ] Banners
- [x] Rails (placed incorrectly so they instantly pop off)
- [x] Inverted Daylight Sensor
- [x] Paintings
- [x] Ore Blocks (Stone is placed instead; works as intended) 
- [x] Item Frames (placed incorrectly)

There are probably more, these are just what i have tested so far :)

**Comment by asiekierka** [comment]
Ore blocks work as intended, or at least as was intended. This is worthy of a separate discussion.

**Comment by LuigiHutch** [comment]
Also item frames are placed incorrectly
