### ISSUE TITLE
Weird lighting inside  Fluid Pipes

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3241]
BC 7.2.0

Fluids render weirdly inside fluid pipes:
![2016-03-14_11 03 20](https://cloud.githubusercontent.com/assets/9326429/13742599/8b4b4d2c-e9d4-11e5-8709-3693199e0901.png)

Fuel is travelling through the fluid pipes

**Comment by asiekierka** [comment]
The center spot seems to have incorrect lighting.

**Comment by AlexIIL** [comment]
Fixed in one of my latest commits.
