### ISSUE TITLE
Item travelling through pipes have major z-fighting issues

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3242]
BC 7.2.0

Item travelling through pipes have major z-fighting issues. See image:
![2016-03-14_11 08 30](https://cloud.githubusercontent.com/assets/9326429/13742690/3497478c-e9d5-11e5-9f37-48176b856fa0.png)

**Comment by asiekierka** [comment]
I think that has always been the case.

**Comment by AlexIIL** [comment]
It can probably be fixed by giving each item a different y-pos. Or by making the y-pos be related to how far through the pipe it is (so it bounces :P)

**Comment by LuigiHutch** [comment]
It also does it in BC for 1.7.10, so it has always been the case

**Comment by asiekierka** [comment]
"Fixed" by adding random offsets. Can't be fixed otherwise unless we add a sine wave/bobbing, but I don't like that idea.
