### ISSUE TITLE
tile.decorateblock.name is a still a thing

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3246]
BC 7.2.0

Even though blueprint viewing render is disabled, tile.decorateblock.name is still registered and appears in JEI in block and facade form:
![2016-03-15_16 33 45](https://cloud.githubusercontent.com/assets/9326429/13785558/f360d380-eacb-11e5-8d7b-0577080af5c9.png)

**Comment by AlexIIL** [comment]
Note that 
 - You cannot craft them and 
 - They only appear in JEI
 - The first one is the block breaker used by the filler

The only bug here is that there are facade versions.

**Comment by asiekierka** [comment]
It's not even a bug that there are facade versions. The only thing that should change is it be locked down to DEVELOPER_MODE, I suppose?

**Comment by AlexIIL** [comment]
What do you want me to put in the condition? I would have to separate meta 0 (builder + filler + quarry block destroying sprite) from meta 1->5 (will be used in the future) and I'm not sure I can do that easily.

**Comment by asiekierka** [comment]
Oh. In that case, keep it and hide meta 1->5 from getSubBlocks.
