### ISSUE TITLE
Weather2 mod rendering conflict

### ISSUE THREAD

**Issue by Trinitrotoluene** [BuildCraft/BuildCraft#3250]
Clouds, tornadoes and hurricanes are invisible. EDIT: Gamerule doDaylightCycle false and Optifine caused this. this issue is invalid

**Comment by AEnterprise** [comment]
does it still heapen when removing BC? also any other mods involved as i doubt BC is the main cause

**Comment by iTitus** [comment]
Can you please post a log

**Comment by asiekierka** [comment]
Or a modlist!
