### ISSUE TITLE
Dupelicate stat id at id achievement.wrench in 7.2.0

### ISSUE THREAD

**Issue by axzxc1236** [BuildCraft/BuildCraft#3251]
I have no clue which mod is Buildcraft conflict with, but I saw UCHE flag infront of Buildcraft mod in the crash report so I report it there.

https://gist.github.com/axzxc1236/00a5a5d995b2e9c0a107

**Comment by asiekierka** [comment]
BuildCraft and Extra Utilities 2 currently conflict.

**Comment by AlexIIL** [comment]
This was fixed in https://github.com/BuildCraft/BuildCraft/commit/35d87c400813630adf15d9a3928fb7b879eecd1c
