### ISSUE TITLE
Ticking Memory error 

### ISSUE THREAD

**Issue by b0bst3r** [BuildCraft/BuildCraft#3253]
http://pastebin.com/Biek1Pwf

Buildcraft 7.1.15
logisticspipes-0.9.3.99.jar
buildcraft-compat-7.1.3.jar

Full explanation here https://github.com/BevoTechPack/BevoTechPack/issues/930

**Comment by AEnterprise** [comment]
the problem is that logistic pipes uses proxies to do it's integration and those test for specific BC versions and are not updated to BC 7.1.15 yet, update LP and it should work

**Comment by davboecki** [comment]
We first need to update LP to work with BC 7.1.15.

**Comment by davboecki** [comment]
The other question is, if there shouldn't be a null check there. In case something implements the IPipeTile but at that moment doesn't have a Pipe to return for example some sort of microblock.
https://github.com/BuildCraft/BuildCraft/blob/7.1.x/common/buildcraft/transport/BlockGenericPipe.java#L425

**Comment by AEnterprise** [comment]
can't hurt to put a null check, i'm not sure if there is a case where it shouldn't have a pipe to return but during loading things in BC can sometimes return null cause they are not loaded/initialized yet

**Comment by asiekierka** [comment]
Indeed.

@davboecki - don't bother yet, BuildCraft 7.1.16 is coming in a few hours

**Comment by davboecki** [comment]
Good to know. Thanks for the heads up.

**Comment by b0bst3r** [comment]
Can I ask please, the fix to BC will fix the pipe not connecting or will it just stop the crashing? Or does Dave need to update LP to get the pipe connecting?

**Comment by asiekierka** [comment]
The crash issue is related to breaking BC pipes near LP pipes. I'm not sure if I can fix the other one.

**Comment by davboecki** [comment]
I need to update LP. The pipes don't connect because our proxy to BC get's disabled. There is an exception in the init phase that disables it. That's the reason for missing receipes and BC pipes not connecting to LP.
Look here for more updates and to find out when it was fixed: https://github.com/RS485/LogisticsPipes/issues/938
