### ISSUE TITLE
Russian translation for 7.1.15

### ISSUE THREAD

**Issue by lex1975** [BuildCraft/BuildCraft#3255]
I added a Russian translation in the latest version. And there are three changes in the translation. Changelog is attached.
[buildcraft-7.1.15_changes.txt](https://github.com/BuildCraft/BuildCraft/files/180107/buildcraft-7.1.15_changes.txt)

[ru_RU.zip](https://github.com/BuildCraft/BuildCraft/files/180108/ru_RU.zip)

**Comment by AlexIIL** [comment]
All localizations go into the https://github.com/BuildCraft/BuildCraft-Localization repository
