### ISSUE TITLE
[7.2.0-pre12] Pumps don't work

### ISSUE THREAD

**Issue by hector1104** [BuildCraft/BuildCraft#3256]
Buildcraft 1.8.9 pre 12

When I tried to pump some liquid with the pump it didn't work. I tried with the 3 engines types but none of them get any liquid. #

**Comment by AlexIIL** [comment]
What setup are you using? What liquid are you trying to pump? have you attached a lever to the pump engine?

**Comment by hector1104** [comment]
What do you mean with setup? 

I tried to pump water and yes, I used the lever to activate the engines and I made sure that engines were working as they got some temperature  (I used builcraft 1.7.2 many time ago)

**Comment by AlexIIL** [comment]
Updating to 7.2.0 beta (later than pre12) should help, it might be the case that pumps were broken in pre12.

**Comment by hector1104** [comment]
I've just donwloaded the 7.2.0 from this website and the problem seems to persist. I download also the last forge version.

https://gyazo.com/b2cfdf9fef5b99610efcd8a394ec5cf8

**Comment by AlexIIL** [comment]
You can use a redstone signal to disable pumps, so what's happening here is that the redstone signal is travelling through the engine and disabling the pump. Try moving the lever to a block next to the engine or running the engine through some kinesis pipes before going to the pump.

**Comment by hector1104** [comment]
Ahhh I see, that's new! Now is pumping but I'm still not sure about stirling engines, after a while working they become black and stop working, why is that?

And I cannot connect a lava pipe to power the Stirling engines ?

**Comment by AlexIIL** [comment]
Stirling engines only accept solid fuel. The only way to get lava into a Stirling engine is to first put it into a bucket and then you can put it in.

**Comment by dj3520** [comment]
>they become black and stop working

The engine is overheated and needs to be broken and placed again.
