### ISSUE TITLE
Pickers Not Leaving Docking Stations After Charging

### ISSUE THREAD

**Issue by DoctorToast3** [BuildCraft/BuildCraft#3259]
Pickers seem to be having an issue where they won't leave the docking station after charging. Reloading the world sometimes gets them leave the docking station, but when they come back to recharge they get stuck again. The robots also have a black square instead of the usual red one when in this "stuck" state.

I'm using Buildcraft 7.1.16, Buildcraft-compat 7.1.4, CodeChickCore 1.0.4.29, Iron Chests Mod 1.7.10, Iron Chest Minecarts 1.0.3, CodeChickenCore-1.7.10-1.0.4.29, Not Enough Items 1.0.3.74, OpenEye 0.6, and Railcraft 9.9.0.0 on Minecraft 1.7.10 and Forge 10.13.4.1558

**Comment by AEnterprise** [comment]
if their light is off they are "sleeping" and should wake up after a while to check for work again, did you wait a few minutes to give them time to finish their sleep cycle and wake up?

**Comment by dj3520** [comment]
IIRC there's a "wake up" option on gates.

**Comment by DoctorToast3** [comment]
I didn't realize that there was a sleep cycle, but I did wait for several minutes when they got "stuck". Everything seems to be working now, so I must just have been impatient and not waiting long enough for that cycle to finish!

**Comment by dj3520** [comment]
Happened to me the first time too.
