### ISSUE TITLE
Quarry in the deep dark

### ISSUE THREAD

**Issue by nifker** [BuildCraft/BuildCraft#3260]
I build a quarry in the deep dark but it doesnt place all frames the quarry is always supplied with RF.
![2016-03-20_12 29 34](https://cloud.githubusercontent.com/assets/5812753/13904166/f0553f44-ee97-11e5-8ade-145b8a3593ea.png)
![2016-03-20_12 32 30](https://cloud.githubusercontent.com/assets/5812753/13904167/f055eeb2-ee97-11e5-8f80-5cc6b5f249d6.png)
![2016-03-20_12 32 34](https://cloud.githubusercontent.com/assets/5812753/13904168/f056062c-ee97-11e5-9e03-60dfefe86212.png)

**Comment by asiekierka** [comment]
Which version of BuildCraft?

**Comment by nifker** [comment]
7.1.14 in direwolf 1.7

**Comment by asiekierka** [comment]
Try updating to 7.1.16?
