### ISSUE TITLE
NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by Recider** [BuildCraft/BuildCraft#3265]
Placing wooden pipe at tank makes server crash and world corrupt.
I was using buildcraft 7.1.14 + buildcraft-compat-7.1.3 mods, contained in Tekkit Legends modpack (minecraft version 1.7.10).
After that crash I have updated buildcraft compontents to buildcraft 7.1.16 and buildcraft-compact-7.1.4 - didn't solve this issue and still crashes with same exception.

Crashlog: http://pastebin.com/eB2iRi6m

**Comment by asiekierka** [comment]
Try disabling Project: Red compatibility in BCCompat for now.
