### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ablakely** [BuildCraft/BuildCraft#3266]
http://pastebin.com/9XMgCcmw

For some reason it works fine on my server, but when my client loads it it'll crash?
Downloaded from here: http://www.mod-buildcraft.com/pages/download.html

Only other mod I have is ComputerCraft.

**Comment by AlexIIL** [comment]
BuildCraft now requires Java 8. I guess your server has Java 8, but your client is using Java 7

**Comment by ablakely** [comment]
Ah, didn't realize that I was using OpenJDK on my laptop lol
