### ISSUE TITLE
Lenses/Filters Z-Fighting

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3267]
Tested on both BC 7.2.3 and 8.0.0 alpha 17

Lenses/Filters placed on a pipes which are passing through them causes Z-Fighting:
https://gfycat.com/PresentQualifiedArcticduck

**Comment by AEnterprise** [comment]
seems like a forgoten bug, should be an easy fix

**Comment by AlexIIL** [comment]
Yeah I just need to push out the lens + filter models. Or scale them up slightly.

**Comment by AlexIIL** [comment]
Fixed! Finally.
