### ISSUE TITLE
Quarry does not auto-rebuild its frame

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildCraft#3268]

**Comment by asiekierka** [comment]
Could not reproduce, but going to mark as "needs verification" as I have seen it happen once.

**Comment by AEnterprise** [comment]
most likely fixed in the 1.8 port as nobody had this problem so far and if not it's probably an extreme edge case

**Comment by AlexIIL** [comment]
I have seen it in my own 1.8 test worlds, and I had no idea what caused it :/

**Comment by AEnterprise** [comment]
closing as the quarry is being rewritten
