### ISSUE TITLE
[8.0.x] Facade Z-fighting

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildCraft#3272]
![](http://img.asie.pl/mR6j)

**Comment by AEnterprise** [comment]
is this still an issue? if so how can this decently be solved? to fix this of the facades will always be over another and that can cause some ugly results when people try to hide their pipes with them

**Comment by AlexIIL** [comment]
It *can* be fixed by properly splitting the block models with diagonals. Although its complicated to do so, so its waiting until 8.0.x.

**Comment by afdw** [comment]
Implemented in 8.0.x.
