### ISSUE TITLE
Is BuildCraft using the "simulate" parameter of "IEnergyProvider#extractEnergy" the wrong way around?

### ISSUE THREAD

**Issue by Lordmau5** [BuildCraft/BuildCraft#3275]
Basically this part in the PipePowerWood class:
https://github.com/BuildCraft/BuildCraft/blob/91ed2af6f46659c935df11403c885423665540da/common/buildcraft/transport/pipes/PipePowerWood.java#L111-L115

The CoFH API states the proper usage of the "simulate" parameter here:
https://github.com/BuildCraft/BuildCraft/blob/91ed2af6f46659c935df11403c885423665540da/api/cofh/api/energy/IEnergyProvider.java#L23-L24

Perhaps someone mixed it up with the IFluidHandler's "doFill" or "doDrain" parameter?

**Comment by asiekierka** [comment]
Oh, yes! Thank you very much!
