### ISSUE TITLE
Creating phased facade with a facade +pipe wire crash

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3278]
BC 8.0 alpha 31 Singleplayer

I was try to create a phased facade by inserting a facade (specifically a cactus facade) + a pipe wire into an intergration table causes a crash:

https://gist.github.com/LuigiHutch/e6475867f2fca463aa18

**Comment by AlexIIL** [comment]
That 8.0.x branch has been discontinued in favour of the new one, sorry about it.

Also you were able to make a cactus facade? waaat?

**Comment by LuigiHutch** [comment]
Thats cool, it was just a test as I saw there was a cactus facade in the creative menu
