### ISSUE TITLE
Some BUG about the pipe

### ISSUE THREAD

**Issue by zhijun1997** [BuildCraft/BuildCraft#3280]
i updated BuildCraft Mod and buildcraft-compat to 7.2.4 and 7.2.1,and i found some problem:

if i place some pipe they will invisible! they not disappear,but it is just can't visible.and i can't destroy this pipe.

my server console can't not stop to display the ERROR like this :

`A TileEntity type buildcraft.transport.TileGenericPipe has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
`

what happen ? :(

this is my server log.
[log.zip](https://github.com/BuildCraft/BuildCraft/files/193841/log.zip)

**Comment by zhijun1997** [comment]
Full ERROR:

`[Server thread/ERROR] [FML]: A TileEntity type buildcraft.transport.TileGenericPipe has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
	at buildcraft.transport.TileGenericPipe.func_145841_b(TileGenericPipe.java:266) ~[TileGenericPipe.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:368) [anj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:165) [anj.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:238) [ld.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:298) [ld.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:905) [le.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:366) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:398) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:534) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
`

**Comment by AlexIIL** [comment]
Oh woops, thanks for reporting this!

**Comment by AlexIIL** [comment]
I'm just building a Jar file that should stop the crashing, however there was an issue with saving the pipes anyway (they were invalid) so there was still a problem with pipes.

Can you try using [this](https://www.dropbox.com/s/9g8w4rk4is2yn2p/buildcraft-7.2.5-test1.jar?dl=0) file and see what errors it gives? Also what types of pipes are you trying to use?

**Comment by AlexIIL** [comment]
Also what mods are you using?

**Comment by zhijun1997** [comment]
oh. this is my mod list:

at client:
![client](https://cloud.githubusercontent.com/assets/18146816/14117007/384cd166-f615-11e5-970f-7fe9f8291c0a.png)

at server:
![server](https://cloud.githubusercontent.com/assets/18146816/14117012/40ece950-f615-11e5-9be8-9d014fba6230.png)

----
about my pipes types,actually I'm not sure what causes this problem.
i remember after updated i want to move my pipes to other place, when i place the pipe (golden pipe),and i saw the pipe invisible,i tried to remove this pipe but i can't . 

 i can jump up to this pipe ,and this pipe can block me.

BTW: i Returned to 7.2.3,now i can place the pipe again,but some pipe (place in 7.2.4) still can't not visible and indestructible.

**Comment by zhijun1997** [comment]
now i will use your new version to test ,wait a min

**Comment by zhijun1997** [comment]
oh nice ! the problem has been fix!

i can place the pipe by normally!
---
but... what happen when i join the server..?
this is BUG too or some wrong texture?
when i reconnected , it will back to normal.

![1](https://cloud.githubusercontent.com/assets/18146816/14117751/adbd3a50-f618-11e5-8b23-2ab15be9d3c9.png)

**Comment by AlexIIL** [comment]
Its defiantly a bug as that's not right :)

Did it fix itself or did using my version fix it for you? If you disconnect+reconnect do the pipes go back to normal?

**Comment by zhijun1997** [comment]
yep , this version is fix my problem ,the broken pipe is gone , thanks!!

if i found some new BUG or idea i will tell you :D

**Comment by AlexIIL** [comment]
ok, thanks :)
