### ISSUE TITLE
Disabling items crashes later when the model baker attempts to provide a model to them

### ISSUE THREAD

**Issue by SDUBZ** [BuildCraft/BuildCraft#3281]
couldnt make much sense of this hope you guys can http://pastebin.com/icxF1A9N

**Comment by AlexIIL** [comment]
Oh right- I think you might have accidently disabled facades in your config?

**Comment by AlexIIL** [comment]
It might be the case that this doesn't happen with elecore but there is a mistake in that code that you alerted me to :)

**Comment by SDUBZ** [comment]
alot of random mod bugs have happend lately and it feels like im reporting nearly everyday :/ no one told me skyblocks are so hard to make as a pack but the config was altered from the other bug with jei from before thanks for the help :D

**Comment by asiekierka** [comment]
It's not skyblocks, it's just that 1.8.9 is very early on.

**Comment by AlexIIL** [comment]
Closed via commit, 7.2.6 should be released shortly.
