### ISSUE TITLE
Disabled EnginBlock can be crafted 7.1.16

### ISSUE THREAD

**Issue by tytannial** [BuildCraft/BuildCraft#3283]
Forge version 1614 for 1.7.10 and only buildcraft loaded
In objects.cfg, I disable Redstone Engine, but the recipe still work and give a "unkown.name" item.
I put it on floor, then I want to remove it and game crash.

**Comment by tytannial** [comment]
I am sure ONLY the Enginblock can curse this bug, other disable item can't be crafted.
I disable all 4 engines but engineblock recipes can be still found in NEI

**Comment by tytannial** [comment]
![qq 20160331124630](https://cloud.githubusercontent.com/assets/11215623/14165769/22a56c30-f73f-11e5-85c3-de8c54d0a9a4.png)

**Comment by AEnterprise** [comment]
it can't realy be crafted, it's only visible in NEI because the base item still exists

JEI replaces NEI on 1.8+, if the engineblock is dissabled it won't have a valid rendering so JEI will not show it

can be closed

**Comment by AlexIIL** [comment]
Yeah disabling all engines currently doesn't disable the engine block itself, and so it doesn't disable the crafting recipe to make the engine. Which causes a game crash.

**Comment by AEnterprise** [comment]
a simple check if the engine is enabled before registering the recipe should fix it then
