### ISSUE TITLE
Pipes and Tinkers 1.8.9 don't like each other! Crash-tastic.

### ISSUE THREAD

**Issue by Corsta1994** [BuildCraft/BuildCraft#3286]
I understand the mod is still in beta and there will be issues.

I am running Buildcraft version 7.2.5 and I am having random crashes when using pipes in a crafting station from tinkers construct. It has happened twice to me in the span of a few minutes, after the crash if I restart the world that crashed, it will crash as the world loads.

The only fix I know of without using a third party inventory manager to remove said items.

Is to;
Uninstall the Buildcarft
Restart the world
Save and Quit
Reinstall the Buildcraft
Then craft everything all over again (without putting the pipes into a crafting station)

Everything else seems fine in the station besides all the types of pipes.

I just tested it again after writing the top section. Vanilla table and player inventory does not craft the game, it seems on the tinkers construct table does. I am using tinkers construct version 2.1.0.

**Comment by AlexIIL** [comment]
Apparently this can be fixed by upgrading to a later version of mantle, however if that does not work can you put the crash report here?

**Comment by Corsta1994** [comment]
I will try that thanks.

**Comment by Corsta1994** [comment]
I updated both mantle and tinkers and seems to have fixed the issue, thanks for the help.
mantle version 0.9.2
tinkers 2.2.1
