### ISSUE TITLE
Crash when i crafting pipe plug in tinkers' crafting table :( 

### ISSUE THREAD

**Issue by Mouamle** [BuildCraft/BuildCraft#3288]
http://pastebin.com/6Lk4iAqV

**Comment by AlexIIL** [comment]
Can you try updating mantle? It fixed an issue like this for someone else.

**Comment by Mouamle** [comment]
@AlexIIL  Thanks :)

**Comment by AlexIIL** [comment]
@Mazdallier As you haven't replied I'll assume that updating it fixed it. Please re-open if this isn't the case :)
