### ISSUE TITLE
Agricraft rendering conflict

### ISSUE THREAD

**Issue by CJL48** [BuildCraft/BuildCraft#3291]
With both Buildcraft and Agricraft installed, BC docking ports are not textured correctly, appearing as in the below screenshot. As far as I can tell, only docking ports are affected.
While this bug is only apparent when both BC and Agricraft are installed, I felt that I should file a bug report first for the affected mod.
Versions:
MC - 1.8.9
Forge 1.8.9-11.15.1.1764
Buildcraft 7.2.5
Agricraft 2.0.0a3
Steps to Reproduce:
Install Forge
Install both BC and Agricraft
Start Minecraft
![2016-04-06_13 32 22](https://cloud.githubusercontent.com/assets/8433790/14326477/30403d36-fbfc-11e5-94eb-f7fc2e055765.png)

**Comment by AEnterprise** [comment]
so just to be sure: you don't have any other mods installed (optifine/fastcraft/...)?

**Comment by CJL48** [comment]
I specifically tested this on an instance with no other mods. This rendering bug appeared different on my main world, with more mods installed, and didn't appear at all when optifine was installed, though there were other rendering bugs.

**Comment by AEnterprise** [comment]
alright then it's something weird that needs looking into

the other rendering bugs with optifine instaled can be ignored, nothing can be done about those

**Comment by LuigiHutch** [comment]
I would also recommend that you make an issue of this on the Agricraft issue tracker linking back here

**Comment by CJL48** [comment]
Will do.

**Comment by AlexIIL** [comment]
[Agricraft issue](https://github.com/InfinityRaider/AgriCraft/issues/620)

**Comment by AEnterprise** [comment]
fixed on the agricraft side, can be closed

**Comment by AlexIIL** [comment]
It was?

**Comment by AEnterprise** [comment]
yes, see the issue linked above on their end, atleast i asume that since they closed it recently, if not then they probably are not gona fix it at all for 1.7.10, agricraft does some rendering tweaks for it's crops iirc that are causing this

**Comment by AlexIIL** [comment]
Its for 1.8.9 :P

**Comment by AEnterprise** [comment]
can be closed, agricraft was doing rendering hacks but is no longer doing those

**Comment by AlexIIL** [comment]
*finally* got around to closing this :P
