### ISSUE TITLE
Pump related error message

### ISSUE THREAD

**Issue by mblob** [BuildCraft/BuildCraft#3292]
MC 1.8.9
Forge 11.15.1.1808
SpongeApi 4.1.0
BC 7.2.5

Got tht message when placing buildcraft pumps.

[11:18:04] [Server thread/ERROR] [Sponge]: Entity is not registered EntityResizableCuboid['unknown'/690, l='world', x=1348.25, y=62.00, z=-796.75]
[11:18:04] [Server thread/ERROR] [Sponge]: Entity is not registered EntityResizableCuboid['unknown'/691, l='world', x=1348.25, y=62.00, z=-800.75]

![2016-04-07_11 18 38](https://cloud.githubusercontent.com/assets/967684/14346455/9ea70b5e-fcb2-11e5-9f88-dc5fbad11b99.png)

And BC pump is not able to pump oil from hydraulicraft.

**Comment by jpiermarini** [comment]
@AlexIIL not sure if the BC pump not pumping oil from Hydraulicraft was part of this getting resolved, or if it is an issue with Buildcraft but we are experiencing this issue with the latest version of both Buildcraft and Hyrdaulicraft  I've requested that the Hydraulicraft guys relook at this issue https://github.com/K-4U/Hydraulicraft/issues/210

**Comment by AlexIIL** [comment]
"And BC Pump is not able to pump Oil from hydrolicraft"

I missed that bug at the bottom, please open a new issue for it so I can deal with it separately to this :)

**Comment by jpiermarini** [comment]
Thanks I'll open it now.
