### ISSUE TITLE
un otr bog sur le moteur er la rafineri dai con mai an marche

### ISSUE THREAD

**Issue by dragondamour** [BuildCraft/BuildCraft#3293]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FortuneOres Black Magic (FortuneOres-MC1.8.9-3.0.0.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6 (1).jar)
  CoreXU2 (Extra-Utilities-Mod-1.8.9.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
  RenderPlayerAPIPlugin (RenderPlayerAPI-1.8.9-1.0.jar)
  PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
  RenderPlayerAPIEnhancerPlugin (RenderPlayerAPIEnhancer-1.8.9-1.0.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 16-04-07 05:24
Description: Ticking block entity

java.lang.NoSuchMethodError: cofh.api.energy.IEnergyConnection.canConnectEnergy(Lnet/minecraft/util/EnumFacing;)Z
	at buildcraft.core.lib.engines.TileEngineBase.isPoweredTile(TileEngineBase.java:469)
	at buildcraft.core.lib.engines.TileEngineBase.switchOrientationDo(TileEngineBase.java:342)
	at buildcraft.core.lib.engines.TileEngineBase.switchOrientation(TileEngineBase.java:329)
	at buildcraft.core.lib.engines.TileEngineBase.func_73660_a(TileEngineBase.java:194)
	at net.minecraft.world.World.func_72939_s(World.java:1718)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:250)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at buildcraft.core.lib.engines.TileEngineBase.isPoweredTile(TileEngineBase.java:469)
	at buildcraft.core.lib.engines.TileEngineBase.switchOrientationDo(TileEngineBase.java:342)
	at buildcraft.core.lib.engines.TileEngineBase.switchOrientation(TileEngineBase.java:329)
	at buildcraft.core.lib.engines.TileEngineBase.func_73660_a(TileEngineBase.java:194)

-- Block entity being ticked --
Details:
	Name: buildcraft.energy.engine.stone // buildcraft.energy.TileEngineStone
	Block type: ID #2107 (tile.engineBlock // buildcraft.core.BlockEngine)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-149,69,192), Chunk: (at 11,4,0 in -10,12; contains blocks -160,0,192 to -145,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #2107 (tile.engineBlock // buildcraft.core.BlockEngine)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1718)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['dragondamoure'/4139, l='world', x=-149,42, y=69,00, z=193,37]]
	Chunk stats: ServerChunkCache: 4416 Drop: 0
	Level seed: 766608511891410875
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: -236,00,64,00,240,00 - World: (-236,64,240), Chunk: (at 4,4,0 in -15,15; contains blocks -240,0,240 to -225,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 8631040 game time, 9233692 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 74263 (now: false), thunder time: 119901 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:250)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1686475416 bytes (1608 MB) / 6616436736 bytes (6309 MB) up to 10667687936 bytes (10173 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms1g
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP 9.19 Powered by Forge 11.15.1.1808 Optifine OptiFine_1.8.9_HD_U_H5 77 mods loaded, 77 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1808.jar) 
	UCHIJAAAA	Forge{11.15.1.1808} [Minecraft Forge] (forge-1.8.9-11.15.1.1808.jar) 
	UCHIJAAAA	PlayerAPI{1.0} [Player API] (minecraft.jar) 
	UCHIJAAAA	RenderPlayerAPI{1.0} [Render Player API] (minecraft.jar) 
	UCHIJAAAA	RenderPlayerAPIEnhancer{1.0} [Render Player API Enhancer] (minecraft.jar) 
	UCHIJAAAA	CoreXU2{1} [CoreXU2] (minecraft.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (Extra-Utilities-Mod-1.8.9.jar) 
	UCHIJAAAA	JEI{2.28.7.174} [Just Enough Items] (Just-Enough-Items-Mod-1.8.9.jar) 
	UCHIJAAAA	abyssalcraft{1.9.0} [AbyssalCraft] (AbyssalCraft-1.8.9-1.9.0.jar) 
	UCHIJAAAA	adobeblocks{4.1.1.10} [Adobe Blocks] (AdobeBlocks-4.1.1.10.jar) 
	UCHIJAAAA	adobeblocksvc{1.5} [Adobe Blocks 2 Version Checker] (AdobeBlocks-4.1.1.10.jar) 
	UCHIJAAAA	advancedcapes{3.0} [Advanced Capes] (advancedcapes-3.0.jar) 
	UCHIJAAAA	ArchitectureCraft{1.3.1} [ArchitectureCraft] (ArchitectureCraft-Mod-1.8.9.jar) 
	UCHIJAAAA	archmagus{0.8.0} [Archmagus] (Archmagus-1.8.9-0.8.0.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	aura{591} [Aura Cascade] (Aura-Cascade-Mod-1.8.9.jar) 
	UCHIJAAAA	betterbuilderswands{0.5.1} [Better Builder's Wands] (Better-Builders-Wands-Mod-1.8.9.jar) 
	UCHIJAAAA	BetterSprinting{1.1.3} [Better Sprinting] (BetterSprinting  MC-1.8.8  v1.1.3.jar) 
	UCHIJAAAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1759-universal.jar) 
	UCHIJAAAA	BloodMagic{1.8.9-2.0.0-3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-3.jar) 
	UCHIJAAAA	BuildCraft|Core{7.2.5} [BuildCraft] (buildcraft-7.2.5.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.2.5} [BC Silicon] (buildcraft-7.2.5.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.2.5} [BC Transport] (buildcraft-7.2.5.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.2.5} [BC Builders] (buildcraft-7.2.5.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.2.5} [BC Energy] (buildcraft-7.2.5.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.2.5} [BC Robotics] (buildcraft-7.2.5.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.2.5} [BC Factory] (buildcraft-7.2.5.jar) 
	UCHIJAAAA	buildingbrickscompatvanilla{1.8.9-1.3.2} [Building Bricks Vanilla Compat] (BuildingBricks-1.8.9-1.3.2.jar) 
	UCHIJAAAA	buildingbricks{1.8.9-1.3.2} [Building Bricks] (BuildingBricks-1.8.9-1.3.2.jar) 
	UCHIJAAAA	caterpillar{0.0.0} [Caterpillar] (Caterpillar-Mod-1.8.9.jar) 
	UCHIJAAAA	Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
	UCHIJAAAA	chiselsandbits{mc1.8.9-v1.8.7} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.7.jar) 
	UCHIJAAAA	cyclopscore{0.5.4} [Cyclops Core] (CyclopsCore-1.8.9-0.5.4.jar) 
	UCHIJAAAA	colossalchests{1.3.3} [Colossal Chests] (ColossalChests-1.8.9-1.3.3.jar) 
	UCHIJAAAA	wonderfulwands{1.8.0} [Wonderful Wands] (CyanosWonderfulWands_1.8.9-1.8.0.jar) 
	UCHIJAAAA	DurabilityShow{2.1.2} [Durability Show] (Durability Show-1.8.9-2.1.2.jar) 
	UCHIJAAAA	ElementalItems{6.1} [Elemental Items Mod] (ElementalItemsMod_6.1-1.8.9.jar) 
	UCHIJAAAA	endores{1.0-a.009} [End Ores] (End Ores-1.0-a.009.jar) 
	UCHIJAAAA	endercrop{1.8.9-1.2} [Ender Crop] (Ender-Crop-Mod-1.8.9.jar) 
	UCHIJAAAA	ModUtilsLib{2.0.1} [ModUtilsLib] (ModUtilsLib-2.0.1-mc1.8.9.jar) 
	UCHIJAAAA	FastLadder{1.0.0} [FastLadder!] (FastLadder-1.0.0-mc1.8.9.jar) 
	UCHIJAAAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6 (1).jar) 
	UCHIJAAAA	FortuneOres{3.0.1} [FortuneOres] (FortuneOres-MC1.8.9-3.0.0.jar) 
	UCHIJAAAA	GraveStone{1.0.0} [GraveStone] (GraveStone-1.8.9-Graves-1.0.0.jar) 
	UCHIJAAAA	hgp{Release} [Horizontal Glass Panes] (hgp-1.8.9-1.0.2.jar) 
	UCHIJAAAA	IGWMod{1.2.4-4} [In-Game wiki Mod] (IGW-Mod-1.8.9-1.2.4-4-universal.jar) 
	UCHIJAAAA	infinitycraft{1.0-a.019} [Infinity Craft] (InfinityCraft-1.0-a.019.jar) 
	UCHIJAAAA	inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
	UCHIJAAAA	IronChest{6.0.119.765} [Iron Chest] (ironchest-1.8.9-6.0.119.765.jar) 
	UCHIJAAAA	kk{0.7.6} [Kingdom Keys Re:Coded] (Kingdom-Keys-Mod-1.8.9.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal.jar) 
	UCHIJAAAA	mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar) 
	UCHIJAAAA	mineralogy{2.6.0} [Mineralogy] (Mineralogy-Mod-1.8.9.jar) 
	UCHIJAAAA	moarcarts{2.0.1-12} [MoarCarts] (moarcarts-1.8.9-2.0.1-12.jar) 
	UCHIJAAAA	numina{0.4.0.131.jar} [Numina] (Modular-Powersuits-Mod-1.8.9.jar) 
	UCHIJAAAA	powersuits{1.0} [powersuits] (Modular-Powersuits-Mod-1.8.9.jar) 
	UCHIJAAAA	moreplayermodels{1.8.9} [MorePlayerModels] (More-Player-Models-2-Mod-1.8.9.jar) 
	UCHIJAAAA	Morpheus{1.8.9-2.0.57} [Morpheus] (Morpheus-1.8.9-2.0.57.jar) 
	UCHIJAAAA	cfm{3.6} [MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.6.1(1.8.9).jar) 
	UCHIJAAAA	notenoughkeys{@MOD_VERSION@} [NotEnoughKeys] (Not-Enough-Keys-Mod-1.8.9.jar) 
	UCHIJAAAA	plantmegapack{1.8.9.18} [Plant Mega Pack] (plantmegapack-1.8.9.18.jar) 
	UCHIJAAAA	PneumaticCraft{1.13.8-12} [PneumaticCraft] (PneumaticCraft-1.8.9-1.13.8-12-universal (1).jar) 
	UCHIJAAAA	rftools{4.20beta8} [RFTools] (rftools-1.8.9-4.20beta8.jar) 
	UCHIJAAAA	ropebridge{1.3} [Rope Bridge] (Rope-Bridge-Mod-1.8.9.jar) 
	UCHIJAAAA	SaltMod{1.7.f} [Salty Mod] (SaltyMod-1.8.8-1.8.9-1.7.f.jar) 
	UCHIJAAAA	scenter{1.8.9-3.4.0} [Scenter] (scenter-1.8.9-3.4.0.jar) 
	UCHIJAAAA	Schematica{1.7.7.142} [Schematica] (Schematica-1.8.9-1.7.7.142-universal.jar) 
	UCHIJAAAA	ShetiPhianCore{3.1.0} [ShetiPhian-Core] (ShetiPhianCore-1.8.9-3.1.0.jar) 
	UCHIJAAAA	SimilsaxTranstructors{1.8.8.16} [Similsax Transtructors] (SimilsaxTranstructors-1.8.8.16 (1).jar) 
	UCHIJAAAA	lteleporters{1.0.0} [Lemon's Simple Teleporters] (Simple-Teleporters-Mod-1.8.9.jar) 
	UCHIJAAAA	StorageDrawers{1.8.9-2.2.1} [Storage Drawers] (StorageDrawers-1.8.9-2.2.1.jar) 
	UCHIJAAAA	Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
	UCHIJAAAA	earth{1.0.0} [The Earth Mod] (TheEarth-1.0.0.jar) 
	UCHIJAAAA	VeinMiner{0.31.4_build.unknown} [Vein Miner] (Vein-Miner-Mod-1.8.9.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.31.4_build.unknown} [Mod Support] (Vein-Miner-Mod-1.8.9.jar) 
	UCHIJAAAA	XaeroMinimap{1.8.7} [Xaero's Minimap] (Xaeros_Minimap_1.8.7_Forge_1.8.9.jar) 
	Loaded coremods (and transformers): 
FortuneOres Black Magic (FortuneOres-MC1.8.9-3.0.0.jar)
  com.demoxin.minecraft.fortuneores.coremod.OreDictCore
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
FldLoadingPlugin (FastLeafDecay-1.8-1.6 (1).jar)
  com.olafski.fastleafdecay.FldTransformer
CoreXU2 (Extra-Utilities-Mod-1.8.9.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
RenderPlayerAPIPlugin (RenderPlayerAPI-1.8.9-1.0.jar)
  api.player.forge.RenderPlayerAPITransformer
PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
  api.player.forge.PlayerAPITransformer
RenderPlayerAPIEnhancerPlugin (RenderPlayerAPIEnhancer-1.8.9-1.0.jar)
  api.player.forge.RenderPlayerAPIEnhancerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['dragondamoure'/4139, l='world', x=-149,42, y=69,00, z=193,37]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.8.9_HD_U_H5
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 364.72
	OpenGlRenderer: GeForce GT 740/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by iTitus** [comment]
From your crashlog I would guess that some mod is shipping an outdated version of the RF-API.

**Comment by AlexIIL** [comment]
Feel free to re-open this if updating all of your mods doesn't help.
