### ISSUE TITLE
Readme issue

### ISSUE THREAD

**Issue by ntzrmtthihu777** [BuildCraft/BuildCraft#3298]
May want to add that you have to put `classifier: 'dev'` into the readme. I'd do a pr, but it seems overkill to do the entire workflow just to change a single line of text a handful of characters.

**Comment by AlexIIL** [comment]
If you are referring to 1.7.10 then yes, the 1.8.9 instructions are wrong.

Can you put more detail? I saw your IRC chat, and you seem to have mixed up the MC versions (7.2.5 is a 1.8.9 version, but railcraft is only on 1.7.10 right now so it's different)

**Comment by ntzrmtthihu777** [comment]
I'm currently away from my throne, but I am developing for 1.8.9 using BuildCraft 7.2.5, and without the dev classifier it didn't work.

**Comment by AlexIIL** [comment]
Oh, this used to work and then something broke it :(

**Comment by AlexIIL** [comment]
Turns out the 1.8.9 instructions *are* wrong. I've fixed it to work without specifing the classifier (you shouldn't depend on the "dev" version as that means that you must use the same MCP snapshot as buildcraft for it to work.)

**Comment by ntzrmtthihu777** [comment]
Glad to have spotted it then
