### ISSUE TITLE
Duplicate textures

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3300]
When i cloned the project to be able to make better suggestions, my git client complained that there are duplicates in the texture folder; especially there:
https://github.com/BuildCraft/BuildCraft/tree/7.2.x/buildcraft_resources/assets/buildcrafttransport/textures/items
some folder exist twice with different case. At least on windows both end up in the same directory since win doesn't care about the case :D

**Comment by AlexIIL** [comment]
Can you paste your git log? I don't know of any other way to get *all* files+folders that have case-insensitive duplicates.

**Comment by rapus95** [comment]
well it didn't crash it's just SmartGit showed a duplicate! tag at those dirs since windows isn't capable of having different files for same name with only different case.

**Comment by AlexIIL** [comment]
Sorry, I want to get a list of all duplicates so that I can fix them :)

**Comment by rapus95** [comment]
buildcraft_resources/assets/buildcraftfactory/models/item/autoworkbenchblock.json
buildcraft_resources/assets/buildcraftfactory/models/item/autoWorkbenchBlock.json

buildcraft_resources/assets/buildcraftenergy/models/item/*

buildcraft_resources/assets/buildcrafttransport/textures/items/pipeWire/*
buildcraft_resources/assets/buildcrafttransport/textures/items/pipewire/*

buildcraft_resources/assets/buildcrafttransport/textures/items/pipeWaterproof.png
buildcraft_resources/assets/buildcrafttransport/textures/items/pipewaterproof.png

these are all that i found so far (manually -.-)

**Comment by AlexIIL** [comment]
Sorry, I meant if it gave you a list automatically then I would like to have it, you don't have to do it manually as there might be a lot.

It might be easier (if you have git installed as a command-line tool) to clone the repo, then do ````git status```` and paste the output of that to this, as that will list *all* the files that are invalid.

**Comment by hea3ven** [comment]
I got bored :P
found duplicate: ./buildcraft_resources/assets/buildcrafttransport/textures/items/pipewaterproof.png ./buildcraft_resources/assets/buildcrafttransport/textures/items/pipeWaterproof.png
found duplicate: ./buildcraft_resources/assets/buildcrafttransport/textures/items/pipewire ./buildcraft_resources/assets/buildcrafttransport/textures/items/pipeWire
found duplicate: ./buildcraft_resources/assets/buildcrafttransport/textures/items/gatecopier ./buildcraft_resources/assets/buildcrafttransport/textures/items/gateCopier
found duplicate: ./buildcraft_resources/assets/buildcraftfactory/models/item/autoworkbenchblock.json ./buildcraft_resources/assets/buildcraftfactory/models/item/autoWorkbenchBlock.json
found duplicate: ./buildcraft_resources/assets/buildcraftenergy/models/item/bucketredplasma.json ./buildcraft_resources/assets/buildcraftenergy/models/item/bucketRedPlasma.json
found duplicate: ./buildcraft_resources/assets/buildcraftenergy/models/item/bucketoil.json ./buildcraft_resources/assets/buildcraftenergy/models/item/bucketOil.json
found duplicate: ./buildcraft_resources/assets/buildcraftenergy/models/item/bucketfuel.json ./buildcraft_resources/assets/buildcraftenergy/models/item/bucketFuel.json

**Comment by AlexIIL** [comment]
Thanks!

**Comment by rapus95** [comment]
But it nevertheless should be mentioned that the textures had different sizes :/

**Comment by rapus95** [comment]
@AlexIIL I'm too ashamed to open new issues for minor/purely optical fixes in the source code for things that i encounter while diving into the code myself
things like that:
is [that](https://github.com/BuildCraft/BuildCraft/blob/7.2.x/common/buildcraft/core/config/ConfigManager.java#L72L73) necessary? (see the else if before it)
