### ISSUE TITLE
Modularization - Settings/Configs

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3302]
Since you went back to modules in 7.2.5 consider splitting up the settings from general to module names and when clicking that you end up in the corresponding general part. An other option would be to have settings/configs for every submodule (each with the same categories; general, experimental etc)

For the storage in file i'd only split it into several "substructures"

This rather is an enhancement than an issue

**Comment by AlexIIL** [comment]
Unfortunately I can't do this for 7.x as it would require breaking existing config files. However this can happen for 8.x

**Comment by rapus95** [comment]
even though the current module question i asked in the forum rather looks like a no I'm diving into the code trying to understand the whole structure and seeing whether i can build some example module

[that](https://gist.github.com/rapus95/e0af4238664f9ea66fc6922d438a3f64)'s my current progress:

so i also had the Idea why not using some fields for the module names? (+ maybe some additional enhancements like split the config register into module & config name instead of the 1-String-version)

some thing that i might ask now: Can you enjoy/use ideas that i get when setting up my own custom module or do you rather want to do you own stuff and stop me to flood you with ideas and possible enhancements? (from my point of view)

**Comment by iTitus** [comment]
This is an Open-Source project. You can even do PRs if you like. But I suggest joining the Buildcraft IRC channel for quick and easy chatting.

**Comment by AlexIIL** [comment]
I don't think this is happening actually. Sorry.
