### ISSUE TITLE
Handling of pure code improvements (functional & optical, no formatting)

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3303]
@AlexIIL I'm too ashamed to open new issues for every minor/purely optical fix in the source code for things that i encounter while diving into the code myself - what to do in such a case? Just append all of them here?
things like that:
[that](https://github.com/BuildCraft/BuildCraft/blob/7.2.x/common/buildcraft/core/config/ConfigManager.java#L72L73) seems to be not necessary (see the else if before it)

**Comment by AlexIIL** [comment]
Closed via commit, 7.2.6 should be released shortly.

**Comment by AlexIIL** [comment]
I think I've said it before but I'll say it here to make it final: I would prefer if you tell me of little issues in IRC, or open a PR with quite a few of them. I don't really want tonnes of "3 lines of code" changes in PR's or issues.
