### ISSUE TITLE
Pipe wire does not visually update when a neighbour pipe wire is added

### ISSUE THREAD

**Issue by Squix** [BuildCraft/BuildCraft#3308]
It is simply as that : when you put 2 pipes and you want to connect them with pipe wire, you need to put 1 extra pipe wire at the intersection between the 2 pipes.

Here's the setup :

I put one pipe and a pipe wire segment on it :
![2016-04-17_20 48 43](https://cloud.githubusercontent.com/assets/6475960/14589259/df4969bc-04dd-11e6-9817-ee9555163d54.png)

I put another pipe next to it with a pipe wire on it as well :
![2016-04-17_20 50 55](https://cloud.githubusercontent.com/assets/6475960/14589263/1a472572-04de-11e6-8e17-1168ff108c25.png)

You can see that there's a gap between the 2 pipe wires ! However if I place a Gate on the pipe, everything become normal :
![2016-04-17_20 53 33](https://cloud.githubusercontent.com/assets/6475960/14589279/786219fa-04de-11e6-8447-eb75109a4d67.png)

BuildCraft version : 7.2.5
Extra mods : Optifine

**Comment by AlexIIL** [comment]
Technically it doesn't require a third, but doesn't visually update. Thanks!

**Comment by dj3520** [comment]
Does this still happen without Optifine? Also does the wire still work when
it does this?

**Comment by AlexIIL** [comment]
Yes, this is a server side logic bug, not a client side one.
