### ISSUE TITLE
Still chunkloading problems with robots 7.2.5

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3310]
This happened to me after i left the game
![2016-04-18_16 51 18](https://cloud.githubusercontent.com/assets/5960902/14609633/07a24462-058b-11e6-8cd3-8a0d4fe27e8a.png)
The two stations to the right were their "home" stations until they got somewhat disconnected probably due to a chunk unload (and reload)

**Comment by AEnterprise** [comment]
does this still heapen with the latest version? if so can you provide a log of when it heapens to try and trace this?

**Comment by AlexIIL** [comment]
Robots seem to have a tonne of odd and random issues, especially when it comes to chunkloading. They also don't log anything helpful other than "I just failed to find my home". I haven't changed any of the robot code recently so its unlikely that updating will help.

**Comment by AEnterprise** [comment]
i'd have to look at the code but is it possible this is chunk loading order issue? where the the robot is initialized but the pipe and docking station are not, if so having the robot wait a few seconds and then try again might fix it

**Comment by AlexIIL** [comment]
Possibly.
