### ISSUE TITLE
robots have problems with torches and partial/half blocks 7.2.5

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3311]
the picker robot has huge problems with items falling into half blocks (like onto chests  or pipes etc) aswell as falling into a space that is occupied by a torch
![2016-04-18_17 36 19](https://cloud.githubusercontent.com/assets/5960902/14609919/14e5d0a2-058c-11e6-95bc-de6cb5669b36.png)
![2016-04-18_17 35 59](https://cloud.githubusercontent.com/assets/5960902/14609937/1f2b172a-058c-11e6-84c1-225710086e30.png)
Edit: added screenshots

**Comment by chemdork123** [comment]
I haven't noticed this before.  Does the robot just ignore the items or does it get stuck trying to pick them up?

**Comment by AEnterprise** [comment]
are there any other mods involved? can you replicate with just BC installed?

**Comment by AlexIIL** [comment]
This DOES happen in 7.2.5. (I have encountered it)

**Comment by AEnterprise** [comment]
odd, i haven't noticed it before, i guess the robots are only checking if the blockspace is occupied rather then the bounding box of said block

**Comment by rapus95** [comment]
@AlexIIL are there any chances that this will make it into 7.2.7 aswell? :D (already digging into it to increase the chances)

**Comment by AlexIIL** [comment]
Maybe. For simple traversable blocks where they do not block at all its relatively simple- just tell the robots (and the pathfinding) to treat them like air. However for more complex blocks (slabs, stairs, pipes) it would basically require the path search algorithm to allow for inter-block searches (complex).
