### ISSUE TITLE
planter robot has strange pick behaviour

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3312]
![2016-04-18_17 56 38](https://cloud.githubusercontent.com/assets/5960902/14610650/1bf64392-058f-11e6-8535-66b6218dac7d.png)
As you can see in the background the planter robot took a sugar cane from the 2nd LAST slot (what looks pretty random) instead of a seed from the first slot. What's the default behaviour here?
In the gate I've also set "Provide Items" to "Seeds" but that neither helped...
Result was that the robot is stuck since it can't plant the sugar cane anywhere in its working area whilst 2 blocks further (behind the dirt wall) there is a whole field with nothing being planted on

(And why can these robots only carry one item at a time :/ are there any "supplier" robots that can carry the stuff for the planter robot? In contrast to the picker this is rather weak)

**Comment by chemdork123** [comment]
I've seen this behavior before, but not just with planter robots.  When given a double chest, often the items pulled are from the bottom three rows, acting as if the top three rows of the inventory just "aren't there".  Pulling items with a wooden pipe and autarchic gate or engine, for example.  Is there any issue with how the double chest inventories are handled across the board?  I haven't checked if it is side-specific to an inventory - have you?

**Comment by rapus95** [comment]
Nope haven't checked it but you might be right since my last experiment seems to happen exactly as you described it. So the question to the devs( @AlexIIL ) is now whether this is intended or not (-> bug or "feature")
I clearly didn't expect that since placing of items works from the left upper corner in all cases i have encountered until now but I'm sure that there might be some circumstances in which you need that sort of function.

**Comment by SandGrainOne** [comment]
Vanilla double chests are technically 2 completely different tile entities. Some mods ignore this completely. ItemDucts for example, will extract from or input only to the part where they are connected. To use a full double chest you need to connect 2 item ducts. One for each chest.

In BuildCraft the pipes tries to combine the two tile entities into one, but this might not have been fully implemented for all logic. Robots might be one such exception.

**Comment by AEnterprise** [comment]
this shouldn't realy be a problem in 1.8.9 and onwards if the robots use the inventory capabilities

**Comment by AlexIIL** [comment]
However all of BC uses IInventory stuffs for now, but it will be fixed for 8.0.x

**Comment by asiekierka** [comment]
Not *all* of BC - anything using the Transactor system should now at the very least support capabilities.

**Comment by AgentK9** [comment]
Try to move the pipe to the other side of the chest, if possible. That should work.

**Comment by AEnterprise** [comment]
fixed for 8.0 as mentioned above, should probably get that as milestone to be closed then or closed now
