### ISSUE TITLE
gate or engine provides the redstone power to their adjacent blocks

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3313]
![2016-04-20_19 08 40](https://cloud.githubusercontent.com/assets/5960902/14683505/5773b2c2-072b-11e6-9e18-710da16b9d0b.png)
Here the gate powers both engines (and even the repeater) thus making it hard to create some compact logic involving several different redstone engines pumping from different furnaces, chests etc
using sided output in better gates doesn't help either because for that case you need a bigger setup aswell (you can't power the engine with sided output directly since you then have to place the gate between pipe and engine)

**Comment by AlexIIL** [comment]
Oh right, BC engines are currently considered full cubes. Its kinda a big change though so

**Comment by AEnterprise** [comment]
yes but it's not at all how it has worked up till now and it will break ALOT of builds

all builds that have combustion engines with a gate for automatic shutoff to prevent overheating for example

**Comment by rapus95** [comment]
well that only works due to the high predictability of heating engines but usually one should power an engine based of its own heat what currently isn't possible...

**Comment by SandGrainOne** [comment]
I think it is best if the engines could be controlled individually with gates on the pipe they are providing power to. If this is solved by changing the engines or the strength of the redstone signal produced by the gate is less important, but changing the engines probably have the least consequences for existing builds.

**Comment by rapus95** [comment]
Mind the following situation:
![2016-05-12_21 49 45](https://cloud.githubusercontent.com/assets/5960902/15228239/7be2db12-188b-11e6-8463-005b78631c4f.png)
In that setup you can't use the foreground gate to power the engine since that would power the pump aswell... (and that'd stop the pump and retract the pipe)

**Comment by LuigiHutch** [comment]
This breaks alot of contaptions with little gain. It feels rather unnessercary change and makes engine control more unnessercary complicated as a gate could power 3 engines instead of 1 for example. This would make engine control quite counter intuitive, especially to new users.

**Comment by rapus95** [comment]
@LuigiHutch
well it'd allow some situations like the one i posted before to work - currently they don't work at all
and on the other hand
you still could power 4 engines at once:
![2016-05-24_19 20 37](https://cloud.githubusercontent.com/assets/5960902/15513367/a16e6dda-21e4-11e6-8b66-7e3a0e3b6a49.png)
![2016-05-24_19 20 41](https://cloud.githubusercontent.com/assets/5960902/15513372/a81f5586-21e4-11e6-9270-c5c8f72426b1.png)

**Comment by rapus95** [comment]
Or in an even bigger scale:
![2016-05-24_19 34 02](https://cloud.githubusercontent.com/assets/5960902/15513795/79816000-21e6-11e6-9fcb-9e795f7dd37b.png)
![2016-05-24_19 34 09](https://cloud.githubusercontent.com/assets/5960902/15513798/7b8a028a-21e6-11e6-87f1-e94eef5ea13a.png)

**Comment by rapus95** [comment]
And since i sort of consider it as bug (the original problem) it reminds me of this :D
https://xkcd.com/1172/
![image](https://cloud.githubusercontent.com/assets/5960902/15513994/47366fae-21e7-11e6-8d6b-09b631608588.png)

**Comment by AlexIIL** [comment]
I'm currently on the side of changing this in 8.0.x as engines should NOT be full blocks. It also solves the "put a redstone engine on the side of a pump and a lever on the engine" thing that I've seen a lot of.

**Comment by gjgfuj** [comment]
Yeah that's silly.

**Comment by AEnterprise** [comment]
should be fixed for 8.0 i've been told
