### ISSUE TITLE
Dupe builderBlock

### ISSUE THREAD

**Issue by Artmoneyse** [BuildCraft/BuildCraft#3316]
Video: [https://www.youtube.com/watch?v=I1_JC2GeAvw#t=346](https://www.youtube.com/watch?v=I1_JC2GeAvw#t=346)

It works with all items that can be charged.
Items from the builder is not removed and the chest appears.

**Comment by AlexIIL** [comment]
When you say ALL items that can be charged what items have you tested with? What mods are they from? Did you do this in creative mode or a server set to creative mode?

**Comment by Artmoneyse** [comment]
dupe work on:
buildcraft-7.1.16
buildcraft-7.1.14
Dupe works in a creative mode and survival.
For dupe can use any that can be charged on the modification industrialcraft 2 experimental
Dupe can:
- quantum armor (ic2)
- nano armor (ic2)
- jetpack (ic2)
- graviTool (GraviSuite)
- vajra (GraviSuite)

and any other things which are charged.
Dupe essence is that things from the builder is not spending if there are items that are charged. Sorry for bad english.

**Comment by LuigiHutch** [comment]
Just tested with BC 7.2.6 and can reproduce in a survival world.

Steps to reproduce:
Record a blueprint with a chest with some pickaxes inside
Place a builder with the blueprint in and fill the builder with the contents inside and power it

The result: The chest is placed and filled with the required pickaxes. The pickaxes are also left inside the builder which results with twice the amount of pickaxes; a set in the chest and a set in the builder

**Comment by AEnterprise** [comment]
is this fixed? if not it should probably be looked at soon as it's a dupe bug?

**Comment by Artmoneyse** [comment]
Bug not fixed. Builder not check meta item.

**Comment by AEnterprise** [comment]
i'm guessing this isn't fixed yet?

**Comment by evernife** [comment]
Suggestion:

Make a blacklist for blocks that should not be coppied :/
So we just need to put them there!

**Comment by AlexIIL** [comment]
@evernife its better to actually fix the bugs than add a blacklist. Especially as this affects vanilla items as well.

**Comment by afdw** [comment]
@evernife There is whitelist for blocks, so no blacklist is needed.

**Comment by evernife** [comment]
I had not read that properly, forget it...

I will remove all vanilla chests... that may solve my problem, as a temporary action

**Comment by AlexIIL** [comment]
Remove all vanilla chests from what? This most likely affects every inventory that contains a damaged tool as well, not just a vanilla chest.

**Comment by evernife** [comment]
I think this does not copy blocks from all mods, just vanilla ones...

At least in my server it copy only vanilla blocks...
So, for me, i till solve :D

**Comment by AlexIIL** [comment]
@evernife Are your sure you are having the same problem as this particular dupe bug?

**Comment by evernife** [comment]
Pretty similar, but with draconic chests...

**Comment by LuigiHutch** [comment]
Bc only supports vanilla blocks unless you have Bc compat. If you have bc compat, these blocks are supported by the builder and may also dupe items: http://www.mod-buildcraft.com/pages/faq.html (see compat question)

**Comment by evernife** [comment]
1.7.10 suport ?
