### ISSUE TITLE
Lumberjack Robot

### ISSUE THREAD

**Issue by Lancer005** [BuildCraft/BuildCraft#3317]
I am using buildcraft 7.1.16 and compat 7.1.4 i am using lumberjack, gatherer, planter and leaf cutter all robots work with no issue except for the lumberjack he picks up ax and does not move from station when i toggle for red signal they all return to base including lumberjack but when I turn off signal all go back to work except the lumberjack... tree type using oak and birch.

**Comment by rapus95** [comment]
as far as i found out the robot won't consume its axe thus you must somehow allow the robot to drop its old axe and pick up a new one

**Comment by Lancer005** [comment]
this issue happens as soon as the robot picks  up an axe for the first time. from a chest that contains both axe and shears for both the leaf cutters and lumberjacks. also tried setting up there own chest that contains only axes and once the pick one up they sit on the port and act like they are stuck.. tried this on several different games with same conditions... will try downgrading to older version to see if the issues is with the newer version or with a installed mod... 

thank you

**Comment by rapus95** [comment]
I finally encountered it now aswell as you can see in the link
