### ISSUE TITLE
Wooden kinesis pipe on tank

### ISSUE THREAD

**Issue by Daniel2612** [BuildCraft/BuildCraft#3318]
We are using the beta version of buildcraft for minecraft 1.8.9. When we put a wooden kinesis pipe onto a tank an put a motor under the pipe and start it, nothing is working. Next to the wooden pipe are golden kinesis pipes, going to a motor. Please help us!

**Comment by laz2727** [comment]
This setup is wrong on so many levels. Screenshot, please?

**Comment by Daniel2612** [comment]
![2016-04-25_21 06 01](https://cloud.githubusercontent.com/assets/18666198/14795656/b75a438e-0b29-11e6-84be-01dabd9fced9.png)
On the right you see the tank and the wooden pipe and on the left there is the motor the pipe goes to.

**Comment by laz2727** [comment]
I don't really play with bc that much anymore, but I think you need to use
energy acceptor pipe addon there.

**Comment by Daniel2612** [comment]
But the energy acceptor pipe addon is for transfering EU to RF, isnt it? 
Everything works how we do it, using the pump and pumping oil to a tank, but pumping the oil out of the tank like shown in the screenshot does not work

**Comment by laz2727** [comment]
No, I mean the little square thing from vanilla bc. It's placed on pipe's
side.
Refinery automatically outputs iirc.

It might be a good idea to wait for someone who knows what they're doing.

**Comment by SandGrainOne** [comment]
Those are Fluid pipes and not Kinesis pipes.

I can see nothing wrong with how the pipes and the redstone engine are used in the picture. It should be working if you have remembered to switch the lever.

**Comment by Daniel2612** [comment]
Sorry yes I use fliud pipes. 
It's really strange, everything works fine, but when we have to use wooden pipes, it doesnt work. Are there mods bc isnt compatible with?

**Comment by dj3520** [comment]
I'm also not seeing anything wrong with your setup. Does this happen with emerald pipes as well? Autoauric gates?  Power adapters? What specific version of Buildcraft are you using? Finally could you post what mods you're using when seeing this behavoir, and whether this is on a server, LAN or single-player world.

**Comment by Daniel2612** [comment]
Hey, yes it happens with emerald pipes as well. 
We use Buildcraft 7.2.5 Beta on Minecraft 1.8.9 and play over LAN. And here is a screenshot of all the mods we use: 
![modscreenshot](https://cloud.githubusercontent.com/assets/18666198/14820690/fab80dc0-0bc7-11e6-97f5-d990db457576.PNG)
I'm going to try to test this in a singleplayer world and tell you if there is the same problem.
It's really disappointing, we where searching for oil for so long and then we can't pump it out of the tanks

**Comment by SandGrainOne** [comment]
Could it be redstonepaste? Please try without.

**Comment by Daniel2612** [comment]
I hope it's not! So many things are made with redstonepaste in our world...

**Comment by laz2727** [comment]
Just start using Project Red.

2016-04-26 20:42 GMT+05:00 Daniel2612 <notifications@github.com>:

**Comment by SandGrainOne** [comment]
If it's redstonepaste causing issues it's probably not an incompatibility as such, but that you simply need to power the engine in a slightly different way. Try for example to place a block next to the engine and have the lever on that.

**Comment by dj3520** [comment]
>you simply need to power the engine in a slightly different way

Can you confirm the engine's animation is running? If so it's being powered correctly. The lever directly next to it (as so in the screenshot) should be working.

>Just start using Project Red.

If there's a 1.8.9 version somewhere please let me know.

**Comment by laz2727** [comment]
Yeah, i deleted the message because there's none, and probably won't be for
some time (they have to move from one API to another).



2016-04-26 21:48 GMT+05:00 dj3520 <notifications@github.com>:

**Comment by dj3520** [comment]
That's unfortunate. I use projectred a lot in my 1.7.10 world.

**Comment by Daniel2612** [comment]
I got the problem!!!
The Mods below (the upper one belongs to the other) caused the failure!
![fehlermods](https://cloud.githubusercontent.com/assets/18666198/14828098/b84ffd26-0be5-11e6-9259-ae1a946241b3.PNG)
What a luck that I didn't used it yet =)

**Comment by AEnterprise** [comment]
@Daniel2612 you might wana report it to @mcjty then as this means he's breaking vanilla redstone behaviour and i doubt that's the intention

**Comment by McJty** [comment]
Those versions of rftools and mcjtylib are ancient. Please update if they are causing issues

**Comment by AgentK9** [comment]
Some of those mods also look kinda weird. Where are you downloading them from?

**Comment by AEnterprise** [comment]
also just a hunch but can you try without optifine? i MAY be working but optifine messes with rendering so the engine might be active but just not rendering active due to it
