### ISSUE TITLE
Buildcraft compat 7.1.4 is missing on curse

### ISSUE THREAD

**Issue by Kupferdrache** [BuildCraft/BuildCraft#3319]
hi while I was working on upgradeing our modpack files on curse I saw, that you missed to upload the 7.1.4 compat zip to curse. Because curse don't permit using third party overrides on listed mods, this situation is very inconviend. This Issue is blocking the update of DragTech IV 0.8.6 on curse.

**Comment by AEnterprise** [comment]
uploaded to curse, sorry for that

**Comment by Kupferdrache** [comment]
No prob, thanks for the quick reply
