### ISSUE TITLE
7.2.5 Render error in the list GUI

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3320]
When opening the gui of the list item every enchanted item in the upper row of the player inventory has a render bug exactly then when you don't mouse-over any of the buildcraft slots or the upper row of the player inv (while all other slots are rendered fine in either case) (in the pictures it's the pickaxe)

![2016-04-29_19 45 16](https://cloud.githubusercontent.com/assets/5960902/14924620/b252f184-0e43-11e6-89d2-7bcaef7f954f.png)
(Mouse not over one of the two rows of slots)
![2016-04-29_19 45 21](https://cloud.githubusercontent.com/assets/5960902/14924623/b46637e2-0e43-11e6-81ec-2df85679cff5.png)
(Mouse over the 4th slot of the 2nd row)

**Comment by dj3520** [comment]
What version and is Optifine used?

**Comment by rapus95** [comment]
7.2.5 and optifine

**Comment by AEnterprise** [comment]
try reproducing without optifine, if optifine is the cause we can't realy fix it due to the heavy rendering changes it does

**Comment by rapus95** [comment]
happens without optifine aswell (exact same behaviour)
