### ISSUE TITLE
7.2.6 Architect Table gui doesn't show up for longer than half a second

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3324]
When i try to open the gui of the architect table it opens and closes immediately after. (you can find this out by repeatedly clicking on it so the flickering becomes more visible)
Tested on two different computers, w/ and w/o optifine. Happens in all cases.

**Comment by LuigiHutch** [comment]
It only does this if there isn't a land marked area defined for the architect table to read. I believe this is intentional

**Comment by rapus95** [comment]
oh i expected it to transform some map location into a blueprint but i have to place it next to a location marked by land marks, thanks
