### ISSUE TITLE
6.2 - kinetic pipes bug

### ISSUE THREAD

**Issue by androx102** [BuildCraft/BuildCraft#3325]
Hi, i use this mods: 
BuildCraft 6.2
NuclearCraft
When i use kinetic pipes from BuildCraft, they don't transfer any RF energy. Enginees connected without pipes to machines work correctly.

**Comment by AlexIIL** [comment]
BuildCraft 6.2 is a very old version- the latest in the 6.x branch is 6.4.9, while the latest for 1.7.10 is 7.1.16.

**Comment by asiekierka** [comment]
We do not support ancient BuildCraft versions, especially as since 6.2
there was at least one breaking RF change and multiple changes to the power
transmission code which fixed bugs.

2016-05-02 14:21 GMT+02:00 AlexIIL <notifications@github.com>:

**Comment by androx102** [comment]
I play on the server where we use forge 10.13.2.1230, we can't hange the version because it's only this. What version of Buildcarft should i use ?

**Comment by AEnterprise** [comment]
why can't you change the forge version? any server host i know allows it (most even have an automated system for it)

**Comment by androx102** [comment]
because my host have only one version (10.13.2.1230) in offert
PS. Sory for my english, but i'm not the best in learning languages i'm better in math :P

**Comment by asiekierka** [comment]
You should email support about installing a newer version. If that fails, look for a host which cares about their customers getting a good modding experience.
