### ISSUE TITLE
Zone planner map wrong

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3327]
![2016-05-03_22 08 07](https://cloud.githubusercontent.com/assets/5960902/14996729/b5c50fe2-117b-11e6-8979-6072f11d13ea.png)
in the zone planners right half of the map there's a rectangle made of a lot of water and some "sandy" edge/corner
![2016-05-03_22 09 18](https://cloud.githubusercontent.com/assets/5960902/14996735/b71983fa-117b-11e6-8741-3a28d36480f4.png)
Here you see a sharp edge between stone and water (except 1 row of stone over the water at the left side)
These pictures don't really fit (i also tested replacing the zone planner, it didn't help)

**Comment by asiekierka** [comment]
Replacing the zone planner won't help as it's a slightly hacky global cache of the map area.

**Comment by afdw** [comment]
Probably fixed in 8.0.x
