### ISSUE TITLE
7.2.6 NPE Crash with robots and leather helms

### ISSUE THREAD

**Issue by Gelles** [BuildCraft/BuildCraft#3329]
Messing with robots for the first time, discovered I could put helmets on them, but crashed when I put a leather helmet on a robot (dyed or undyed - crash log is from undyed).

Crash logs:
http://paste.ee/p/mhV0a
http://paste.ee/p/v2gUW

**Comment by AlexIIL** [comment]
Fixed as of a commit between 7.2.6 and now, sorry for not saying. 7.2.7 will go out *soon*.
