### ISSUE TITLE
Buildcraft Cauldron

### ISSUE THREAD

**Issue by Gumbo379** [BuildCraft/BuildCraft#3330]
I am playing BuildCraft on a cauldron server(hosted by me)with my friend. But every time I open the server, I get a message saying that BuildCraft was not tested on Cauldron servers and that it may cause lag. We would be happy if BuildCraft was compatible with Cauldron servers.

**Comment by asiekierka** [comment]
We would be happy if Cauldron didn't make far-reaching changes to the engine which break mods' expectations of the engine in ways which cannot currently be solved. We can only mitigate some of them.

Hint: Other mods don't warn you. They may, and probably will, often fail silently in subtle ways.
