### ISSUE TITLE
render error: landmarks not showing their "connections" from any distance

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3331]
![2016-05-05_15 13 17](https://cloud.githubusercontent.com/assets/5960902/15044357/7c9e1d44-12d4-11e6-80bd-28414307bad1.png)
moving half a block backwards:
![2016-05-05_15 13 20](https://cloud.githubusercontent.com/assets/5960902/15044358/7dfd7e1e-12d4-11e6-85fc-aa22f536e818.png)

Rotating the camera didn't change anything in both places
It's on max distance (placing the landmark at the sand blocks position won't allow connecting them)

**Comment by dj3520** [comment]
OptiFine?

**Comment by AlexIIL** [comment]
No this is just part of the way the marker system has worked. I'm completely revamping it for 8.0.x though so it should be fixed then.

**Comment by AlexIIL** [comment]
*slaps forehead*

Oh right, there are 3 methods that control if a tile should render, ````isGlobalRenderer```` which ignores chunk boundries, ````getRenderBoundingBox```` which is the biggest AABB that it contains, and ````getMaxRenderDistanceSquared```` which defaults to 4096 (64*64).

**Comment by AlexIIL** [comment]
Sort-of fixed by now, although it doesn't work properly if both land marks are unloaded when looking at them.
