### ISSUE TITLE
7.2.6 Again pump render error

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3335]
As in #3299. It happens (as far as i can see) only if the "pipe" is very long but now there are even two different configurations (both happen w/o optifine aswell):
a) angle dependent:
![2016-05-12_20 53 51](https://cloud.githubusercontent.com/assets/5960902/15226896/063ae87e-1885-11e6-9e4e-7686f6da4ae3.png)
![2016-05-12_20 53 54](https://cloud.githubusercontent.com/assets/5960902/15226898/07c476b0-1885-11e6-9cb7-d2caa604edb8.png)

b) distance dependent:
![2016-05-12_20 53 02](https://cloud.githubusercontent.com/assets/5960902/15226912/10b27c90-1885-11e6-8a82-d5d79a1cbcc2.png)
![2016-05-12_20 53 07](https://cloud.githubusercontent.com/assets/5960902/15226916/130eaf2c-1885-11e6-8645-88659da781c3.png)
(Farther away renders correct)

**Comment by AlexIIL** [comment]
This requires pumps to render in the TESR rather than with an entity. No idea if this will happen in 7.2.7 or not.

**Comment by AlexIIL** [comment]
Fixed in 8.0.x by #3384
