### ISSUE TITLE
Crash when clicking on Neotech generator

### ISSUE THREAD

**Issue by Zhaulus** [BuildCraft/BuildCraft#3337]
Attempted to attach an emerald power pipe to a Neotech Coal Generator, caused me to crash. when I attempted to reload instance froze at a black screen with GUI.
[crash-2016-05-13_23.45.11-server.txt](https://github.com/BuildCraft/BuildCraft/files/264369/crash-2016-05-13_23.45.11-server.txt) , 
[crash-2016-05-13_23.48.12-server.txt](https://github.com/BuildCraft/BuildCraft/files/264370/crash-2016-05-13_23.48.12-server.txt)

**Comment by asiekierka** [comment]
7.2.0-pre10 uses an unofficial, incompatible version of the RF API. Please
update.

2016-05-14 7:13 GMT+02:00 Zhaulus <notifications@github.com>:

**Comment by Zhaulus** [comment]
Will do, thank you for the prompt reply
