### ISSUE TITLE
[1.7.10] Builder will not place seared bricks

### ISSUE THREAD

**Issue by AgentK9** [BuildCraft/BuildCraft#3338]
I was trying to make a blueprint to put into my survival world (from creative) and this is what happened:

![image](https://cloud.githubusercontent.com/assets/11563088/15269153/9b794922-19c4-11e6-9a8a-9684aba5eb61.png)

I also had some other things in there (it was basically a smeltery built into the wall)

**Comment by AgentK9** [comment]
the other pic:
![image](https://cloud.githubusercontent.com/assets/11563088/15269157/c2a6ea54-19c4-11e6-8abf-090a590b70da.png)

**Comment by LuigiHutch** [comment]
I believe the seared blocks are tile entities so they are therefore not supported by default. This support would need to be added by tinkers itself or via BCCompat

**Comment by AEnterprise** [comment]
as they form the smeltery they would indeed be TE's

**Comment by AgentK9** [comment]
So should I post it on TC's side or BCCompat's or what?

**Comment by AEnterprise** [comment]
you can but i doubt you'll be able to use them in a 1.7.10 blueprint as that's bugfixes only for them, they might be able to do it for 1.8/1.9

**Comment by AgentK9** [comment]
ok.
