### ISSUE TITLE
Buildcraft Server Crash

### ISSUE THREAD

**Issue by Tech180** [BuildCraft/BuildCraft#3339]
# Full Crash
---- Minecraft Crash Report ----

WARNING: coremods are present:
 ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
 OpenModsCorePlugin (OpenModsLib-1.8.9-0.9.1.21.jar)
 CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
 FMLPlugin (InventoryTweaks-1.60-40.jar)
 IC2core (industrialcraft-2-2.3.243-ex18.jar)
 Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 5/13/16 7:14 PM
 Description: Ticking block entity

java.lang.NoSuchMethodError: cofh.api.energy.IEnergyConnection.canConnectEnergy(Lnet/minecraft/util/EnumFacing;)Z
 at buildcraft.transport.PipeTransportPower.isPowerSource(PipeTransportPower.java:166)
 at buildcraft.transport.PipeTransportPower.canPipeConnect(PipeTransportPower.java:131)
 at buildcraft.transport.Pipe.canPipeConnect(Pipe.java:106)
 at buildcraft.transport.TileGenericPipe.canPipeConnect_internal(TileGenericPipe.java:810)
 at buildcraft.transport.TileGenericPipe.canPipeConnect(TileGenericPipe.java:836)
 at buildcraft.transport.TileGenericPipe.computeConnection(TileGenericPipe.java:877)
 at buildcraft.transport.TileGenericPipe.computeConnections(TileGenericPipe.java:862)
 at buildcraft.transport.TileGenericPipe.initialize(TileGenericPipe.java:601)
 at buildcraft.transport.TileGenericPipe.func_73660_a(TileGenericPipe.java:396)
 at net.minecraft.world.World.func_72939_s(World.java:1718)
 at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
 at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
 ---------------------------------------------------------------------------------------

-- Head --
 Stacktrace:
 at buildcraft.transport.PipeTransportPower.isPowerSource(PipeTransportPower.java:166)
 at buildcraft.transport.PipeTransportPower.canPipeConnect(PipeTransportPower.java:131)
 at buildcraft.transport.Pipe.canPipeConnect(Pipe.java:106)
 at buildcraft.transport.TileGenericPipe.canPipeConnect_internal(TileGenericPipe.java:810)
 at buildcraft.transport.TileGenericPipe.canPipeConnect(TileGenericPipe.java:836)
 at buildcraft.transport.TileGenericPipe.computeConnection(TileGenericPipe.java:877)
 at buildcraft.transport.TileGenericPipe.computeConnections(TileGenericPipe.java:862)
 at buildcraft.transport.TileGenericPipe.initialize(TileGenericPipe.java:601)
 at buildcraft.transport.TileGenericPipe.func_73660_a(TileGenericPipe.java:396)

-- Block entity being ticked --
 Details:
 Name: net.minecraft.src.buildcraft.transport.GenericPipe // buildcraft.transport.TileGenericPipe
 Block type: ID #389 (tile.pipeBlock // buildcraft.transport.BlockGenericPipe)
 Block data value: 0 / 0x0 / 0b0000
 Block location: World: (-962,68,-274), Chunk: (at 14,4,14 in -61,-18; contains blocks -976,0,-288 to -961,255,-273), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
 Actual block type: ID #389 (tile.pipeBlock // buildcraft.transport.BlockGenericPipe)
 Actual block data value: 0 / 0x0 / 0b0000
 Stacktrace:
 at net.minecraft.world.World.func_72939_s(World.java:1718)
 at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

-- Affected level --
 Details:
 Level name: world
 All players: 1 total; [EntityPlayerMP['Tech180'/31495, l='world', x=-963.39, y=67.00, z=-274.93]]
 Chunk stats: ServerChunkCache: 808 Drop: 0
 Level seed: -2578346856297874001
 Level generator: ID 00 - default, ver 1. Features enabled: true
 Level generator options: 
 Level spawn location: -12.00,64.00,252.00 - World: (-12,64,252), Chunk: (at 4,4,12 in -1,15; contains blocks -16,0,240 to -1,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
 Level time: 27035660 game time, 28618838 day time
 Level dimension: 0
 Level storage version: 0x04ABD - Anvil
 Level weather: Rain time: 63040 (now: false), thunder time: 27077 (now: false)
 Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
 Stacktrace:
 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
 at java.lang.Thread.run(Unknown Source)

-- System Details --
 Details:
 Minecraft Version: 1.8.9
 Operating System: Windows 10 (amd64) version 10.0
 Java Version: 1.8.0_91, Oracle Corporation
 Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
 Memory: 1410609680 bytes (1345 MB) / 2199912448 bytes (2098 MB) up to 2863661056 bytes (2731 MB)
 JVM Flags: 2 total; -Xms2G -Xmx3G
 IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
 FML: MCP 9.19 Powered by Forge 11.15.1.1902 40 mods loaded, 40 mods active
 States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
 UCHIJAAAA mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
 UCHIJAAAA FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9-universal.jar) 
 UCHIJAAAA Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9-universal.jar) 
 UCHIJAAAA OpenModsCore{0.9.1.21} [OpenModsCore] (minecraft.jar) 
 UCHIJAAAA Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
 UCHIJAAAA Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
 UCHIJAAAA Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
 UCHIJAAAA Automagy{2.0.2} [Automagy] (Automagy-1.8.9-2.0.2.jar) 
 UCHIJAAAA bagginses{2.1.5b} [Bagginses] (Bagginses-1.8.9-2.1.5b.jar) 
 UCHIJAAAA ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha-0.0.2.jar) 
 UCHIJAAAA intangible{0.0.25} [Intangible] (intangible-1.8.9-0.0.25.jar) 
 UCHIJAAAA JEI{2.28.18.186} [Just Enough Items] (jei_1.8.9-2.28.18.186.jar) 
 UCHIJAAAA BloodMagic{1.8.9-2.0.0-20} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-20.jar) 
 UCHIJAAAA Botania{r1.8-299} [Botania] (Botania-unofficial.r1.8-299.jar) 
 UCHIJAAAA BuildCraft|Core{7.2.6} [BuildCraft] (buildcraft-7.2.6.jar) 
 UCHIJAAAA BuildCraft|Silicon{7.2.6} [BC Silicon] (buildcraft-7.2.6.jar) 
 UCHIJAAAA BuildCraft|Transport{7.2.6} [BC Transport] (buildcraft-7.2.6.jar) 
 UCHIJAAAA BuildCraft|Builders{7.2.6} [BC Builders] (buildcraft-7.2.6.jar) 
 UCHIJAAAA BuildCraft|Energy{7.2.6} [BC Energy] (buildcraft-7.2.6.jar) 
 UCHIJAAAA BuildCraft|Robotics{7.2.6} [BC Robotics] (buildcraft-7.2.6.jar) 
 UCHIJAAAA BuildCraft|Factory{7.2.6} [BC Factory] (buildcraft-7.2.6.jar) 
 UCHIJAAAA IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
 UCHIJAAAA BuildCraft|Compat{7.2.1} [BuildCraft Compat] (buildcraft-compat-7.2.1.jar) 
 UCHIJAAAA Chameleon{1.8.9-1.1.2} [Chameleon] (Chameleon-1.8.9-1.1.2.jar) 
 UCHIJAAAA ChestTransporter{2.2.1} [Chest Transporter] (ChestTransporter-2.2.1-MC1.8.9.jar) 
 UCHIJAAAA chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6.jar) 
 UCHIJAAAA ElecCore{1.4.271} [ElecCore] (ElecCore-1.8.9-1.4.271.jar) 
 UCHIJAAAA deepresonance{1.1.4beta23} [DeepResonance] (deepresonance-1.8.9-1.1.4beta23.jar) 
 UCHIJAAAA gravestone{1.1.4} [Gravestone] (Gravestone Mod 1.1.4.jar) 
 UCHIJAAAA IC2{2.3.243-ex18} [IndustrialCraft 2] (industrialcraft-2-2.3.243-ex18.jar) 
 UCHIJAAAA inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
 UCHIJAAAA journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
 UCHIJAAAA mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar) 
 UCHIJAAAA OpenMods{0.9.1.21} [OpenMods] (OpenModsLib-1.8.9-0.9.1.21.jar) 
 UCHIJAAAA PneumaticCraft{1.13.8-12} [PneumaticCraft] (PneumaticCraft-1.8.9-1.13.8-12-universal.jar) 
 UCHIJAAAA Psi{beta-23} [Psi] (Psi-beta-23.jar) 
 UCHIJAAAA StorageDrawers{1.8.9-2.6.4} [Storage Drawers] (StorageDrawers-1.8.9-2.6.4.jar) 
 UCHIJAAAA tconstruct{1.8.9-2.2.1.jenkins1005} [Tinkers' Construct] (TConstruct-1.8.9-2.2.1.jar) 
 UCHIJAAAA WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.8.x-1.1.6.jar) 
 UCHIJAAAA wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.171.jar) 
 Loaded coremods (and transformers): 
 ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)

 OpenModsCorePlugin (OpenModsLib-1.8.9-0.9.1.21.jar)
 openmods.core.OpenModsClassTransformer
 CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
 com.rwtema.extrautils2.asm.ClassTransformerHandler
 FMLPlugin (InventoryTweaks-1.60-40.jar)
 invtweaks.forge.asm.ContainerTransformer
 IC2core (industrialcraft-2-2.3.243-ex18.jar)

 OpenModsLib class transformers: [movement_callback:ENABLED],[map_gen_fix:FINISHED],[player_render_hook:ENABLED]
 Class transformer null safety: all safe
 Pulsar/tconstruct loaded Pulses: 
 - TinkerCommons (Enabled/Forced)
 - TinkerWorld (Enabled/Not Forced)
 - TinkerTools (Enabled/Not Forced)
 - TinkerSmeltery (Enabled/Not Forced)
 - TinkerGadgets (Enabled/Not Forced)
 - TinkerOredict (Enabled/Forced)
 - TinkerIntegration (Enabled/Forced)
 - TinkerFluids (Enabled/Forced)
 - TinkerMaterials (Enabled/Forced)

Profiler Position: N/A (disabled)
 Player Count: 1 / 4; [EntityPlayerMP['Tech180'/31495, l='world', x=-963.39, y=67.00, z=-274.93]]
 Is Modded: Definitely; Server brand changed to 'fml,forge'
 Type: Dedicated Server (map_server.txt)

## Crash (Cause)
Details:
 Name: net.minecraft.src.buildcraft.transport.GenericPipe // buildcraft.transport.TileGenericPipe
 Block type: ID #389 (tile.pipeBlock // buildcraft.transport.BlockGenericPipe)
 Block data value: 0 / 0x0 / 0b0000
 Block location: World: (-962,68,-274), Chunk: (at 14,4,14 in -61,-18; contains blocks -976,0,-288 to -961,255,-273), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
 Actual block type: ID #389 (tile.pipeBlock // buildcraft.transport.BlockGenericPipe)
 Actual block data value: 0 / 0x0 / 0b0000
 Stacktrace:
 at net.minecraft.world.World.func_72939_s(World.java:1718)
 at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

**Comment by AlexIIL** [comment]
One of your mods has an older version of the RF api- you should update all of your mods.

**Comment by AlexIIL** [comment]
(closed as I haven't heard back)
