### ISSUE TITLE
Pump doesn't work with Hydraulicraft oil

### ISSUE THREAD

**Issue by jpiermarini** [BuildCraft/BuildCraft#3340]
BC pump not pumping oil from Hydraulicraft was part of this getting resolved, We are experiencing this issue with the latest version of both Buildcraft and Hyrdaulicraft I've requested that the Hydraulicraft guys relook at this issue https://github.com/K-4U/Hydraulicraft/issues/210

**Comment by AEnterprise** [comment]
weird as the pump doesn't differentiate between fluids, it should pump any fluid unless it encounters another fluid then it was pumping

**Comment by AEnterprise** [comment]
@jpiermarini does this still heapen? if so can the pump pump up water or lava?
