### ISSUE TITLE
Builder not placing flowing water in survival mod

### ISSUE THREAD

**Issue by stevenlr** [BuildCraft/BuildCraft#3341]
First of all, sorry if you're not accepting bug reports for the 1.7.\* versions anymore.

So my builder is simply not able to place flowing liquid blocks in survival mode. In creative everything is fine. My tanks are full and everything else is built correctly.
Also the builder does place the static water blocks, just not the flowing ones, so it differs from #2929 in that sense.

Here are my blueprints::
https://drive.google.com/open?id=0Bxk2czVxi6eESmhob3l6NWkxVU0
https://drive.google.com/open?id=0Bxk2czVxi6eEc1B5dHp6d1RoYVk

Cheers

**Comment by XFactHD** [comment]
Flowing liquid blocks won't ever be placed by anything, they are generated by the source block once a block update happens. Because of the speed of the builder, it does not cause block updates when placing a block to prevent lags. The fluid should fix itself as soon as you place a block next to the fluid block.

**Comment by stevenlr** [comment]
> Flowing liquid blocks won't ever be placed by anything

Well actually they are placed by the Builder in creative mode.
Plus you have to consider the fact that the flowing blocks are listed in the required blocks in the blueprint.

If it is in fact intentional, it seems like it makes using liquids pretty tedious with the builder. Nobody would like to go manually updating blocks after the process is done.
Maybe it would be possible to trigger a block update on each source block after the whole building process is done then.

**Comment by AlexIIL** [comment]
It *does* send a block update to the placed blocks, it would be wrong not too. (Block updates do NOT cause lag, they are a necessary part of making sure everything in the world is correct and you don't get a fluid block without additional flow. They are also extremely common in minecraft)

Does the builder stop building (the blueprint moves down into the inventory and the building tape vanishes) or does it just hang?

**Comment by stevenlr** [comment]
It just hangs, in the required materials panel, the flowing blocks are still listed and the blueprint remains in the upper slot.
However I'm not 100% sure about whether the frame disappears or not, but I guess it doesn't since the builder hangs.
I'll have to check tonight and I'll get back to you when I know more.

**Comment by stevenlr** [comment]
@AlexIIL here's a video of the process: https://www.youtube.com/watch?v=jsLjztwmO54

Note that the blueprint was created with Rotate=Off, Excavate=On and Mode=Survival.

**Comment by SandGrainOne** [comment]
The Architect table should probably not record flowing fluids. Blocks like that should not be a part of the blueprint. The Builder could trigger a block update on the source blocks when the construction is complete.

**Comment by XFactHD** [comment]
@AlexIIL I must have overlooked something then.

**Comment by AlexIIL** [comment]
(This happens in the 1.8.9 version as well, so I don't have a problem with taking it)
