### ISSUE TITLE
pb Server Vs single player

### ISSUE THREAD

**Issue by croziors** [BuildCraft/BuildCraft#3345]
hello
in single serveur i have http://imgur.com/8jiPbhQ
in my serveur online i have http://imgur.com/ySPclQr i can t craft quarry in online serveur
i don t know why 
i use buildcraft-7.1.16.jar

**Comment by AgentK9** [comment]
Is it a modpack?

**Comment by croziors** [comment]
yes is modpack

**Comment by croziors** [comment]
http://163.172.137.62/TechGalac-V1.0.B.zip

**Comment by AgentK9** [comment]
The modpack probably has the quarry recipe disabled. This is not a bug.

**Comment by croziors** [comment]
no see you are two picture one single player second on my serveur the name of quarry is not same !

**Comment by Bersham** [comment]
First, is this _your_ private modpack or someone elses? All I can find about "TechGalac" is on the FTB forum thread [http://forum.feed-the-beast.com/threads/mod-pack-techgalac.151691/](url).

Second, if the FTB link is correct in listing the mods installed, you will need to check in the Minetweaker and Modtweaker config files to see if the recipe has been edited.

Third, if you ask for help on bugs, these guys and gals won't be able to help without log files. They will need log files from your single player game and your server game.

[https://paste.ee/](url) or [https://pastenib.com/](url) are good sites to upload your log files.

**Comment by AlexIIL** [comment]
@Bersham (I edited your comment to fix URL's)

**Comment by croziors** [comment]
what  log you need where ?

**Comment by Bersham** [comment]
I'm not doing the work for you bud.

[.minecraft](http://minecraft.gamepedia.com/.minecraft)

**Comment by AEnterprise** [comment]
as nobody else seems to have this problem it's a user error or modpack issue, OP isn't providing any further info so should be closed

**Comment by croziors** [comment]
i have update BC not it s ok

**Comment by AEnterprise** [comment]
@croziors then provide the info we need, a modlist at the very least, a run log, if it includes minetweaker/modtweaker/any other that changes recipes remove them or check their configs

without basic information we can't help you
