### ISSUE TITLE
Builder unable to place polished stone brick slabs

### ISSUE THREAD

**Issue by icecharger** [BuildCraft/BuildCraft#3352]
It says on the bc compat page on curse that it adds support for forge multipart which I believe is the mod that allows forge microblocks to exist. But in game on my local server when I try to place microblocks with the buildcraft builder it still spits out the error

[17:12:32] [Server thread/WARN] [BuildCraft]: Location: 190, 169, 1324 - Block: ForgeMultipart:block@0
[17:12:32] [Server thread/WARN] [BuildCraft]: Placed block does not match expectations! Most likely a bug in BuildCraft or a supported mod. Removed mismatched block.

and deletes the block immediately. When I look at it, the block is placed correctly for a split second and then disappears. This is contradictory to the curse page and even in game with the [waila tooltip](http://prntscr.com/b82xr4) for builder compatibility turned on it says it is compatible. I tried updating bc compat on server and client, nothing changed. I was thinking maybe this has to do with that polished stone brick originates from tinkers' construct? This is in 1.7.10

**Comment by AEnterprise** [comment]
BC compat bugs should be reported on the BC compat tracker.

but as this is 1.7.10, all involved mods are currently moving to 1.9.4 i don't think this will get fixed as it's not a major gamebreaking bug

**Comment by AEnterprise** [comment]
should be closed, 1.7.10 isn't getting new features or mod integrations
