### ISSUE TITLE
Lasers render only from a specific angle (as with pumps & quarry before)

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3355]
![2016-05-25_22 30 36](https://cloud.githubusercontent.com/assets/5960902/15555367/bbb7c18e-22c8-11e6-9b36-699dba14759a.png)
![2016-05-25_22 30 33](https://cloud.githubusercontent.com/assets/5960902/15555368/bbcec6e0-22c8-11e6-96f0-b046f79041d3.png)

**Comment by asiekierka** [comment]
Only when the lasers are in view. Sounds like incorrect TESR render
bounding box. (It should probably match the laser's maximum range)

2016-05-25 22:33 GMT+02:00 Aaron <notifications@github.com>:

**Comment by AlexIIL** [comment]
No, the TESR needs to override ````forceTileEntityRender````. Gotta love 1.8.9 sometimes (sarcasm).
