### ISSUE TITLE
[Bug Report] [MC1.8.9/BC7.2.6] Placing a BC Pipe next to an Improved Blast Furnace from Immersive Engineering casues crash on SMP/Integrated Server

### ISSUE THREAD

**Issue by WilliamLC98** [BuildCraft/BuildCraft#3356]
[Log (fml-server-1.txt)](https://github.com/BuildCraft/BuildCraft/files/283858/fml-server-1.txt), The part you probably want to see most stars at line 6776.

I just finished making two Improved Blast Furnaces (Immersive Engineering) in my world and was ready to start automating them with BuildCraft pipes, but as soon as I placed a wooden transport pipe in front of it, the server crashed. And since my base was chunkloaded, it would not load backj up successfully. Luckily,  thanks to FTBUtilities I have a more recent backup then what my host makes. Thought I'd report this. Unfortunately, due to a feature my host has enabled by default (That I forgot to/didn't think to turn off), Multicraft insisted my server reboot immediately, several times in a row, so I lost the log for the original crash, and I'm in no hurry to do it again, so hopefully with the log and information I've provided you guys will be able to reproduce and fix this bug.

**Comment by AEnterprise** [comment]
this is a known bug, just update IE and you'll be able to hook up pipes to it again

**Comment by AlexIIL** [comment]
I'm assuming its fixed (by updating IE) so I'm going to close this.

Feel free to re-open if that did not fix it though :)

**Comment by AEnterprise** [comment]
this has indeed been fixed on the IE side
