### ISSUE TITLE
Integration table "voids" power

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3357]
![2016-05-26_16 25 55](https://cloud.githubusercontent.com/assets/5960902/15577915/b43bcf90-235e-11e6-80cf-c8f26391d21e.png)
As you can see here the Integration table gets energy but it can't use it since the output slot is already occupied.
A moment later the energy just vanished...
![2016-05-26_16 25 56](https://cloud.githubusercontent.com/assets/5960902/15577955/d9c48d1a-235e-11e6-9ff3-8c44467bfeae.png)

**Comment by AlexIIL** [comment]
That's intentional- all BC machines lose power over time. The issue seems to be that energy is pushed into the table when it cannot accept it.

**Comment by rapus95** [comment]
assembly doesn't lose power
not 800 per second

**Comment by AlexIIL** [comment]
oh right- the integration table doesn't stop requesting power when it cannot make the next item.

**Comment by rapus95** [comment]
@AlexIIL the stored value (of like the assembly table) doesn't decrease over time if nothing happens means there is no loss of energy (in 7.2.6)

**Comment by AEnterprise** [comment]
the assembly table retains power because people lost to much power when canceling the creation of a crystal for a chipset
