### ISSUE TITLE
Quarry Causing Crash

### ISSUE THREAD

**Issue by Malefactor** [BuildCraft/BuildCraft#3358]
Set up my land markers, put the quarry down, get the "frame blueprint", connect a power source and immediately crash. If i remove BC Builders mod which deletes quarry, i can get back in game. Otherwise, it crashes at reentry. This is 100% able to be reproduced, as well, i have taken out Optifine (to see if that was the issue) as well as other mods recently updated (NEI / More Commands and ChickenCore ect). It's still happening without those mods in. Only other mod that is new is Gregtech5 Unofficial, which i would dread trying to remove simply because of what a hassle it is to reinstall... I would basically have to go fresh.

 Error report

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 5/26/16 11:50 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.mrnobody.morecommands.util.NBTSettingsManager.loadSettings(NBTSettingsManager.java:219)
	at com.mrnobody.morecommands.util.SettingsManager.<init>(SettingsManager.java:241)
	at com.mrnobody.morecommands.util.NBTSettingsManager.<init>(NBTSettingsManager.java:172)
	at com.mrnobody.morecommands.core.CommonProxy.createSettingsManagerForPlayer(CommonProxy.java:356)
	at com.mrnobody.morecommands.core.ClientProxy.createSettingsManagerForPlayer(ClientProxy.java:172)
	at com.mrnobody.morecommands.util.ServerPlayerSettings.<init>(ServerPlayerSettings.java:108)
	at com.mrnobody.morecommands.command.AbstractCommand.getPlayerSettings(AbstractCommand.java:486)
	at com.mrnobody.morecommands.command.server.CommandBreakspeed.onEvent(CommandBreakspeed.java:32)
	at com.mrnobody.morecommands.command.server.CommandBreakspeed.onEvent(CommandBreakspeed.java:18)
	at com.mrnobody.morecommands.event.EventHandler.post(EventHandler.java:218)
	at com.mrnobody.morecommands.event.EventHandler$ForgeEventHandler.post(EventHandler.java:340)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_604_ForgeEventHandler_post_Event.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:89)
	at net.minecraft.entity.player.EntityPlayer.getBreakSpeed(EntityPlayer.java:855)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:138)
	at net.minecraft.block.Block.func_149737_a(Block.java:643)
	at buildcraft.core.lib.utils.BlockUtils.getBlockHardnessMining(BlockUtils.java:193)
	at buildcraft.core.lib.utils.BlockUtils.isUnbreakableBlock(BlockUtils.java:208)
	at buildcraft.core.lib.utils.BlockUtils.canChangeBlock(BlockUtils.java:175)
	at buildcraft.builders.TileQuarry.createColumnVisitList(TileQuarry.java:400)
	at buildcraft.builders.TileQuarry.findTarget(TileQuarry.java:325)
	at buildcraft.builders.TileQuarry.createUtilsIfNeeded(TileQuarry.java:128)
	at buildcraft.builders.TileQuarry.func_145845_h(TileQuarry.java:195)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.mrnobody.morecommands.util.NBTSettingsManager.loadSettings(NBTSettingsManager.java:219)
	at com.mrnobody.morecommands.util.SettingsManager.<init>(SettingsManager.java:241)
	at com.mrnobody.morecommands.util.NBTSettingsManager.<init>(NBTSettingsManager.java:172)
	at com.mrnobody.morecommands.core.CommonProxy.createSettingsManagerForPlayer(CommonProxy.java:356)
	at com.mrnobody.morecommands.core.ClientProxy.createSettingsManagerForPlayer(ClientProxy.java:172)
	at com.mrnobody.morecommands.util.ServerPlayerSettings.<init>(ServerPlayerSettings.java:108)
	at com.mrnobody.morecommands.command.AbstractCommand.getPlayerSettings(AbstractCommand.java:486)
	at com.mrnobody.morecommands.command.server.CommandBreakspeed.onEvent(CommandBreakspeed.java:32)
	at com.mrnobody.morecommands.command.server.CommandBreakspeed.onEvent(CommandBreakspeed.java:18)
	at com.mrnobody.morecommands.event.EventHandler.post(EventHandler.java:218)
	at com.mrnobody.morecommands.event.EventHandler$ForgeEventHandler.post(EventHandler.java:340)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_604_ForgeEventHandler_post_Event.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:89)
	at net.minecraft.entity.player.EntityPlayer.getBreakSpeed(EntityPlayer.java:855)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:138)
	at net.minecraft.block.Block.func_149737_a(Block.java:643)
	at buildcraft.core.lib.utils.BlockUtils.getBlockHardnessMining(BlockUtils.java:193)
	at buildcraft.core.lib.utils.BlockUtils.isUnbreakableBlock(BlockUtils.java:208)
	at buildcraft.core.lib.utils.BlockUtils.canChangeBlock(BlockUtils.java:175)
	at buildcraft.builders.TileQuarry.createColumnVisitList(TileQuarry.java:400)
	at buildcraft.builders.TileQuarry.findTarget(TileQuarry.java:325)
	at buildcraft.builders.TileQuarry.createUtilsIfNeeded(TileQuarry.java:128)
	at buildcraft.builders.TileQuarry.func_145845_h(TileQuarry.java:195)

-- Block entity being ticked --
Details:
	Name: Machine // buildcraft.builders.TileQuarryCompat
	Block type: ID #941 (tile.machineBlock // buildcraft.builders.BlockQuarryCompat)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (213,72,70), Chunk: (at 5,4,6 in 13,4; contains blocks 208,0,64 to 223,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #941 (tile.machineBlock // buildcraft.builders.BlockQuarryCompat)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Casey's World
	All players: 1 total; [EntityPlayerMP['Malefactor2000'/5031, l='Casey's World', x=210.47, y=72.00, z=70.77]]
	Chunk stats: ServerChunkCache: 1089 Drop: 0
	Level seed: 4695326923547025081
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1064770496 bytes (1015 MB) / 2626408448 bytes (2504 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 7, tcache: 92, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D4 84 mods loaded, 84 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	eplus{1.7.2-2.0.4} [Enchanting Plus] (14151574912_Enchanting-Plus-Mod-1.7.10.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.0.0} [Thaumcraft] (Thaumcraft-1.7.10-4.2.0.0.jar) 
	UCHIJAAAA	ForbiddenMagic{1.7.10-0.51} [Forbidden Magic] (14166334602_Forbidden-Magic-Mod-1.7.10.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (_Iron-Chests-Mod-1.7.10.jar) 
	UCHIJAAAA	IC2{2.2.821-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.821-experimental.jar) 
	UCHIJAAAA	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
	UCHIJAAAA	AdvancedMachines{59.0.2} [Advanced Machines] (advanced-machines-59.0.2.jar) 
	UCHIJAAAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (Advanced-Solar-Panels-Addon-1.7.10 (1).jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJAAAA	bdlib{1.9.3.107} [BD Lib] (bdlib-1.9.3.107-mc1.7.10.jar) 
	UCHIJAAAA	BiomesOPlenty{2.0.2} [Biomes O' Plenty] (BiomesOPlenty-1.7.2-2.0.2.903-universal.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.16} [BuildCraft] (buildcraft-7.1.16-core.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.16} [BC Builders] (buildcraft-7.1.16-builders.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.16} [BC Energy] (buildcraft-7.1.16-energy.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.16} [BC Factory] (buildcraft-7.1.16-factory.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.16} [BC Robotics] (buildcraft-7.1.16-robotics.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.16} [BC Silicon] (buildcraft-7.1.16-silicon.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.16} [BC Transport] (buildcraft-7.1.16-transport.jar) 
	UCHIJAAAA	Forestry{4.2.12.60} [Forestry for Minecraft] (forestry_1.7.10-4.2.12.60.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.3-112.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.2-240.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.1.5} [BuildCraft Compat] (buildcraft-compat-7.1.5.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
	UCHIJAAAA	Railcraft{9.12.1.0} [Railcraft] (Railcraft_1.7.10-9.12.1.0.jar) 
	UCHIJAAAA	MagicBees{2.4.3} [Magic Bees] (magicbees-1.7.10-2.4.3.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.375.jar) 
	UCHIJAAAA	numina{0.4.0.131} [Numina] (Numina-0.4.0.131.jar) 
	UCHIJAAAA	powersuits{0.11.0.300} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.300.jar) 
	UCHIJAAAA	Mystcraft{0.12.3.01} [Mystcraft] (mystcraft-1.7.10-0.12.3.01.jar) 
	UCHIJAAAA	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V13b.jar) 
	UCHIJAAAA	CritterPet{1.0} [Critter Pet] (CritterPet 1.7.10 V13a.jar) 
	UCHIJAAAA	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(21feb16).jar) 
	UCHIJAAAA	DimensionalAnchors{59.0.3} [Dimensional Anchors] (dimensional-anchor-59.0.3.jar) 
	UCHIJAAAA	DragonMounts{r39} [Dragon Mounts] (Dragon-Mounts-Mod-1.7.10.jar) 
	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAAAA	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar) 
	UCHIJAAAA	DynamicTransport{0.1.2.0} [Dynamic Transport] (Dynamic-Transport-Mod-1.7.10.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.38} [EnderStorage] (EnderStorage-1.7.10-1.4.7.38-universal.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.375.jar) 
	UCHIJAAAA	gendustry{1.6.2.127} [GenDustry] (gendustry-1.6.2.127-mc1.7.10.jar) 
	UCHIJAAAA	TwilightForest{2.2.3} [The Twilight Forest] (twilightforest-1.7.2-2.2.3.jar) 
	UCHIJAAAA	gregtech{MC1710} [GregTech] (gregtech-5.09.21.jar) 
	UCHIJAAAA	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212-Core-1.7.10.jar) 
	UCHIJAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.7.10.jar) 
	UCHIJAAAA	pixelmon{3.5.0} [Pixelmon] (Pixelmon-1.7.10-3.5.1-universal.jar) 
	UCHIJAAAA	ivsevs{3.1.0} [IVsEVs] (IVsEVs-1.7.10-3.2.0.jar) 
	UCHIJAAAA	LogisticsPipes{0.9.3.121} [Logistics Pipes] (logisticspipes-0.9.3.121.jar) 
	UCHIJAAAA	marvelcraftuniverse{1.1} [Marvel Craft Universe Mod] (Marvel Craft Universe Mod B1.1.jar) 
	UCHIJAAAA	mrnobody_morecommands{1.7} [MoreCommands] (MoreCommands-1.7.10-1.7.jar) 
	UCHIJAAAA	NEIAddons{1.12.13.38} [NEI Addons] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.13.38} [NEI Addons: Developer Tools] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.13.38} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.13.38} [NEI Addons: Botany] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.13.38} [NEI Addons: Forestry] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.13.38} [NEI Addons: Crafting Tables] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.13.38} [NEI Addons: Ex Nihilo] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	UCHIJAAAA	PixelExtras{1.0.5} [PixelExtras] (pixelmonextras-universal-1.7.10-1.0.5.jar) 
	UCHIJAAAA	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHIJAAAA	safeplace{1.1} [SafePlace] (SafePlace-1.1.jar) 
	UCHIJAAAA	SolarFlux{1.7.10-0.8b} [Solar Flux] (SolarFlux-1.7.10-0.8b.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	trainercommands{1.0.0} [Pixelmon Trainer Commands] (TrainerCommands-1.7.10-1.0.0.jar) 
	UCHIJAAAA	Translocator{1.1.2.16} [Translocator] (Translocator-1.7.10-1.1.2.16-universal.jar) 
	UCHIJAAAA	treasuremob{V0.1 - 1.7.10} [Treasure Mob] (Treasure-Chest-Mod-1.7.10.jar) 
	UCHIJAAAA	wondertrade{3.1.0} [Wonder Trade] (WonderTrade-1.7.10-3.2.0.jar) 
	UCHIJAAAA	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	UCHIJAAAA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	McMultipart{1.1.0.309} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.1.0.309} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.1.2-325
	ThermalFoundation: -[1.7.10]1.2.3-112
	ThermalExpansion: -[1.7.10]4.1.2-240
	NetherOres: -[1.7.10]2.3.1-22
	ThermalDynamics: -[1.7.10]1.1.0-161
	List of loaded APIs: 
		* appliedenergistics2|API (rv2) from DragonAPI 1.7.10 V13b.jar
		* Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
		* BiomesOPlentyAPI (1.0.0) from BiomesOPlenty-1.7.2-2.0.2.903-universal.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.16-core.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.16-core.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.16-core.jar
		* BuildCraftAPI|core (1.0) from Railcraft_1.7.10-9.12.1.0.jar
		* BuildCraftAPI|crops (1.1) from Railcraft_1.7.10-9.12.1.0.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.1.16-core.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.16-core.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.16-core.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.16-core.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.16-core.jar
		* BuildCraftAPI|items (1.1) from Railcraft_1.7.10-9.12.1.0.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.1.16-core.jar
		* BuildCraftAPI|lists (1.0) from Railcraft_1.7.10-9.12.1.0.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.16-core.jar
		* BuildCraftAPI|recipes (4.0) from buildcraft-7.1.16-core.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.16-core.jar
		* BuildCraftAPI|statements (1.1) from Railcraft_1.7.10-9.12.1.0.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.16-core.jar
		* BuildCraftAPI|tiles (1.2) from Railcraft_1.7.10-9.12.1.0.jar
		* BuildCraftAPI|tools (1.0) from Railcraft_1.7.10-9.12.1.0.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.1.16-core.jar
		* CoFHAPI (1.7.10R1.0.2) from buildcraft-7.1.16-core.jar
		* CoFHAPI|block (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|core (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|energy (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|fluid (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|inventory (1.7.10R1.0.1) from buildcraft-compat-7.1.5.jar
		* CoFHAPI|item (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|modhelpers (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|tileentity (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|transport (1.7.10R1.0.1) from buildcraft-compat-7.1.5.jar
		* CoFHAPI|world (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|audio (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|gui (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|gui|container (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|gui|element (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|gui|slot (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|inventory (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|render (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|render|particle (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|util (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|util|helpers (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|util|position (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|world (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|world|feature (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* ForestryAPI|apiculture (4.8.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|core (5.0.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|world (2.1.0) from forestry_1.7.10-4.2.12.60.jar
		* Galacticraft API (1.1) from GalacticraftCore-1.7-3.0.12.375.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.2.127-mc1.7.10.jar
		* IC2API (1.0) from industrialcraft-2-2.2.821-experimental.jar
		* minechemAPI (1.7.10R1) from DragonAPI 1.7.10 V13b.jar
		* Mystcraft|API (0.1) from mystcraft-1.7.10-0.12.3.01.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|carts (1.6.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|core (1.5.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|electricity (2.0.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|locomotive (1.1.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|signals (2.3.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|tracks (2.3.0) from Railcraft_1.7.10-9.12.1.0.jar
		* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.12.1.0.jar
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Malefactor2000'/5031, l='Casey's World', x=210.47, y=72.00, z=70.77]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_D4
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.5.0 NVIDIA 364.72
	OpenGlRenderer: GeForce GTX 465/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by XOR19** [comment]
It's an bug in mrnobody_morecommands MoreCommands, but it seems that they fixed it 7 days ago, so try to update MoreCommands, even if the version number is still 1.7 and try again.

**Comment by Malefactor** [comment]
will do, and thank you if this works... heck, if More Commands is the issue, i'll just get rid of it if i have to... cause seriously, IC2, BC, GT, TE and Pixelmon are the must have's... and without a Quarry, all of those are pretty much worthless, cause i ain't taking the time to mine for all that manually *lol*
