### ISSUE TITLE
harvester somehow ignores a single place

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3359]
![2016-05-28_12 38 15](https://cloud.githubusercontent.com/assets/5960902/15626883/2b36d068-24d1-11e6-9b59-a877089772a0.png)
the sugar cane behind the picker is somehow ignored while all around are harvested regularly (thus no other one is 3 blocks tall)

**Comment by rapus95** [comment]
@AlexIIL fixed with the new 7.2.7 version

**Comment by AlexIIL** [comment]
I... that's good?

Although it will probably happen again at some point :/

**Comment by hea3ven** [comment]
It probably was fixed by a restart, it sounds like it was an orphanated resource.
