### ISSUE TITLE
ticking  entity

### ISSUE THREAD

**Issue by Excepto** [BuildCraft/BuildCraft#3361]
im running the 1.7.10 pack and i get an error about a ticking identity. Ive been told its an issue with buildcraft.
[techniclauncher_2016-05-20.txt.txt](https://github.com/BuildCraft/BuildCraft/files/289969/techniclauncher_2016-05-20.txt.txt)

**Comment by AlexIIL** [comment]
A mod is editing the list of recipes available while the server is running, causing BuildCraft to crash. Not something that we can fix, you should ask who created your pack what mod might be doing that.

**Comment by AlexIIL** [comment]
I've notified the pack dev here (https://github.com/xJon/The-1.7.10-Pack/issues/1137) and hopefully we can work out what is causing it.

**Comment by Excepto** [comment]
As far as I remember I used auto-crafting tables for creating compressed cobblestone or dirt from extra-utilities. Should I go to them with that?
