### ISSUE TITLE
[7.2.7] Block update causes pump pipes to disapear

### ISSUE THREAD

**Issue by MPDR200011** [BuildCraft/BuildCraft#3364]
I noticed this problem when i saw that the stirling engine that was powering a pump was overheating. When I checked i noticed that whenever an update happened near a pump (placing an engine next to it or even redstone updates) it would retract the suction pipes and wouldn't work anymore until i destroyed it and replaced it again.
![2016-06-07_14 30 47](https://cloud.githubusercontent.com/assets/4912677/15859563/8e9a8f98-2cbd-11e6-87e7-692781a0ddfd.png)
![2016-06-07_14 30 50](https://cloud.githubusercontent.com/assets/4912677/15859575/9ab5bc30-2cbd-11e6-98d0-0b0d2d8a68ac.png)

The same thing but with an engine
![2016-06-07_14 33 22](https://cloud.githubusercontent.com/assets/4912677/15859587/ac84cb40-2cbd-11e6-8b44-4c28b2b4d946.png)
![2016-06-07_14 33 25](https://cloud.githubusercontent.com/assets/4912677/15859594/b05fb39c-2cbd-11e6-8608-4bf1a154911d.png)

The engine is working but the pump isn't pulling fluid:
![2016-06-07_14 33 48](https://cloud.githubusercontent.com/assets/4912677/15859614/c2bd301e-2cbd-11e6-9021-68c8cf82322e.png)

Test with redstone updates:
![2016-06-07_14 36 45](https://cloud.githubusercontent.com/assets/4912677/15859633/d173a50c-2cbd-11e6-81ca-79804045e7e4.png)
![2016-06-07_14 36 51](https://cloud.githubusercontent.com/assets/4912677/15859637/d3e5f222-2cbd-11e6-97bd-bf4a89341a6a.png)

Besides buildcraft, I am also running optifine, the ender tanks mod and the multistorage mod. Don't know if this is a bug or something that I caused, so I'm open to suggestions.

**Comment by SandGrainOne** [comment]
Redstone turns off the Pump. This is by design.

The special case with redstone power through an engine is considered a bug and will be fixed. The redstone power going into an engine should not affect the Pump.

**Comment by MPDR200011** [comment]
> Redstone turns off the Pump. This is by design.

The special case with redstone power through an engine is considered a bug and will be fixed. The redstone power going into an engine should not affect the Pump.

**Comment by MPDR200011** [comment]
Ok, thanks for clearing that up for me :D 
Looks like i will have to connect them through a conductive pipe for the time being.

**Comment by SandGrainOne** [comment]
You can also power the engine through a block. Gate -> block -> engine. Should work.
