### ISSUE TITLE
Enhancement/Feature: Lenses & "wanna go there" interaction

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3365]
Mind that case:
![2016-06-07_21 54 09](https://cloud.githubusercontent.com/assets/5960902/15872555/5e212f06-2cfa-11e6-825a-ece7f9e2da7a.png)
The placement of the lense doesn't seem to make sense here. That's what this is about.
Proposed operation:
a) chest not full -> Item gets (colored and) stored in the chest. (As it works right now)
b) chest full -> Item gets colored since it "wants" to go that way but since it can't go there the logic is looking for another movement direction. Result: On full chests the item gets colored and moves on (thus you later can decide of which items you already have enough and which items just weren't sorted.

**Comment by LuigiHutch** [comment]
Why not just place a clay pipe inbetween the diamond pipe and the chest so the items will try and insert into the chest. If it is full, put a lens on the direction it would go if it is full and deal with the painted item from there

**Comment by LuigiHutch** [comment]
It just seems rather unnessercary as we can do that now with the tools we already available and adds unnessercary complexity

**Comment by rapus95** [comment]
Typical usecase (8 sides like them -> 8*4*5=160 pipes):
![2016-06-07_23 22 42](https://cloud.githubusercontent.com/assets/5960902/15875350/c8de2d00-2d07-11e6-87d1-ba535db21a07.png)

**Comment by LuigiHutch** [comment]
Why not do a design like this: 
![2016-06-25_22 37 06](https://cloud.githubusercontent.com/assets/9326429/16359261/5bf85694-3b25-11e6-8024-8546e72327fc.png)

and the diamond pipes gui look like this: 
![2016-06-25_22 35 44](https://cloud.githubusercontent.com/assets/9326429/16359253/299f3758-3b25-11e6-9529-a8b1aa0fa001.png)

Its tilable, faily simple and seems to do what you want it to do without any modifications to the mod?

**Comment by AlexIIL** [comment]
This was implemented a while ago in 7.99.x. I'm not sure which version it was first introduced in though.
