### ISSUE TITLE
7.2.7 Rendering of pipes; shadowing errors

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3366]
looks like shadowing error; it happens not everywhere, but 
![2016-06-09_21 36 36](https://cloud.githubusercontent.com/assets/5960902/15948652/448bec26-2ea2-11e6-86c9-9490283a1063.png)
Some more pictures with changed setups to help nailing it down (only seems to happen in pipes that are north-south longer than 2 parts)
![2016-06-10_00 31 46](https://cloud.githubusercontent.com/assets/5960902/15948729/be912fc2-2ea2-11e6-80a3-7ecdbf9a9116.png)
![2016-06-10_00 31 50](https://cloud.githubusercontent.com/assets/5960902/15948733/c1653ce8-2ea2-11e6-9abf-ffc6cdf6c6c6.png)
![2016-06-10_00 32 08](https://cloud.githubusercontent.com/assets/5960902/15948735/c33101ce-2ea2-11e6-8d85-0425440a8d78.png)

**Comment by AEnterprise** [comment]
maybe fixed with #3410 ?

**Comment by rapus95** [comment]
i guess it is (pretty unprobably that the same bug appears after a whole rewrite again)
