### ISSUE TITLE
7.2.7 Rendering errors - pipe wire

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3367]
Having a gate setup like that:
![2016-06-10_00 38 00](https://cloud.githubusercontent.com/assets/5960902/15948865/9146a15e-2ea3-11e6-8e89-e906e92269f9.png)
When having red on and enabling yellow that's the result (focus on the blue pipe wire):
![2016-06-10_00 17 07](https://cloud.githubusercontent.com/assets/5960902/15948808/33933108-2ea3-11e6-82a9-0ea4015bbeae.png)
Once i force a block update (like opening the gui) everything's working (no more render bug)

**Comment by afdw** [comment]
Probably fixed in 8.0.x
