### ISSUE TITLE
7.2.7 Lazuli (and maybe other) pipe coloring unpredictable (almost)

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3368]
No matter what color you select in the gate once the right event occurs the color usually is not the selected one... (but always the same)

**Comment by AEnterprise** [comment]
still an issue?

**Comment by rapus95** [comment]
well, if no one changed the code, then yes, it still is an issue
vive le déterminisme :D

**Comment by AEnterprise** [comment]
@AlexIIL did you get arround to this one yet? cause it's a fairly annoying bug :P

**Comment by AlexIIL** [comment]
In my dev environment the lazuli pipe works perfectly but the dazuli pipe inverts the colour. Is this the same behaviour as in 7.2.7 or have I half-fixed it and forgot about it
