### ISSUE TITLE
[1.9.4] ETA for BuildCraft on Minecraft 1.9.4

### ISSUE THREAD

**Issue by miuirussia** [BuildCraft/BuildCraft#3369]
Some ETA for BuildCraft on Minecraft 1.9.4? Lack commits worrying(

**Comment by LuigiHutch** [comment]
When it's ready! A lot of BC is being rewritten atm by Alex and is having almost daily commits on the 8.0.x branch. So be patient :)

**Comment by AlexIIL** [comment]
Specifically the https://github.com/BuildCraft/BuildCraft/tree/8.0.x branch. Also no, there is not an ETA, however it is being worked on.
