### ISSUE TITLE
Issue with defining locations for robots [1.7.10, 7.1.16]

### ISSUE THREAD

**Issue by Pizza-man007** [BuildCraft/BuildCraft#3370]
I am trying to create a tree farm using the robots to plant the trees and collect the logs/saplings. The picker robots work perfectly; Picking up the logs/saplings and depositing them in the chest. But for some reason the planter refuses to work. I have the area set for him. And there is plenty of grass for him to plant on. The chest that the pickers put the saplings into is set to provide items and has lots of saplings in it. But the planter hasn't even moved yet. I tried giving him seeds as well and tilled some dirt in his area and he wouldn't plant those either. It is frustrating because I have seen other people with this mod pack make the same farm. Help! Screenshots...
https://1drv.ms/i/s!AjGaWzbLG3UMinUjvxu0FykqxW2J
https://1drv.ms/i/s!AjGaWzbLG3UMinj67GU_hu_1dLNa
https://1drv.ms/i/s!AjGaWzbLG3UMinfLvQRVH-1kettP
https://1drv.ms/i/s!AjGaWzbLG3UMinnlDpf07gRY-ShS
https://1drv.ms/i/s!AjGaWzbLG3UMinaSojU5JIExDAEG
https://1drv.ms/i/s!AjGaWzbLG3UMinQe_g1mx2yW_caO

**Comment by Pizza-man007** [comment]
Update: the issue is with the location maps. When I took the map out of the AND gate and allowed it to work without a defined area, it worked. It got up, took a sapling out of a chest and placed it on the grass. I set up a few more tests in another world and locations don't seem to work there either....Mod version is 7.1.16 for minecraft 1.7.10.

**Comment by hea3ven** [comment]
It looks like the chests are outside of the working area, you need to make another map location that includes the chests/pipes, and set it up as the 'Load/Unload Area' for the robots.

**Comment by Leytek** [comment]
Gate with "Provide items" action must be located in "Work in area" zone. Or you should set "Load/Unload in area" action in robot's home station's gate and define area where you place chest whith saplings or you can define only a gate with "Provide items" action by right-clicking on it with Map Location in hands.

**Comment by Leytek** [comment]
Gate with "Provide items" action must be located in "Work in area" zone. Or you should set "Load/Unload in area" action in robot's home station's gate and define area where you place chest whith saplings or you can define only a gate with "Provide items" action by right-clicking on it with Map Location in hands.

**Comment by Pizza-man007** [comment]
oooooh, okay. I kind of thought they would see the chests anyway. okay. thanks ill fix that.

**Comment by Pizza-man007** [comment]
okay so I did that. I used land marks to create a 1x3x5 area around the chest and used that map as the "Load/Unload in area" map. but the planter still goes wherever the heck he wants. So far it has only placed one sapling in the desired area. The pickers are working fine...but that is probably cause I told them to only pick up wood/saplings.

**Comment by AEnterprise** [comment]
are you sure the docking station is in that area? as that's what they look for

**Comment by hea3ven** [comment]
Did you re-add the original working area to the robots?

**Comment by Pizza-man007** [comment]
yes. first I was using the original zone planer map. for the work area and a landmark map for the unload/load area. Then I tried editing the zone planner map to include the chests and just put that in the "work in area" section.

**Comment by Pizza-man007** [comment]
I didn't clarify very well. the planter is waking up now. It can find the chests. And gets saplings out of them. But then it goes off and plants it somewhere far away. I checked the map and I didn't specify any area except the chests and the dirt area. Recently it has been planting a little closer but, still not where I want it to. https://1drv.ms/i/s!AjGaWzbLG3UMinsjcinlaCtpCKae

**Comment by AEnterprise** [comment]
but is the dirt area still set as working area? seperate from it's load/unload area?

**Comment by Pizza-man007** [comment]
Yes it is. I just finished creating landmark maps for both areas. Now there is no way that I have accidentally marked a different area. The planter finds the chests, takes out saplings. And then goes up he side of the mountain to plant it.

**Comment by Pizza-man007** [comment]
Location screenshots:
https://1drv.ms/i/s!AjGaWzbLG3UMinsjcinlaCtpCKae
https://1drv.ms/i/s!AjGaWzbLG3UMinzdjHvRrTUemuNd

**Comment by Pizza-man007** [comment]
ah whatever. I'm just going to get a use golem to do it instead. Thanks anyway.

**Comment by Amelia-** [comment]
What I always have to do to get planter robots to work properly with an area defined with landmarks is make sure the actual blocks they need to plant on are included in the defined area, not just the space above them.
Make one block deep holes on each corner of the area and place the landmarks in there and it should work. You may even need to make a 2 or 3 block high area to make the pickers work with the same area.
You can remove the holes with the landmarks afterwards so they can be used a space for planting as well.

**Comment by Pizza-man007** [comment]
in my most recent screenshot it should show that I did put the landmarks down one block so that it encompasses the dirt. as for the pickers. I have them set to only pick up oak wood so there aren't any issues. When I take that filter away they go all over the place (just like the planter) and pick up eggs and stuff. I honestly feel like it is either a bug with the maps, or an incompatibility in my modpack that is messing it up. It is an unofficial modpack and thus, has lots of little bugs. Though, my friend is using the same one and planters work for him. So, I don't know.

**Comment by AEnterprise** [comment]
can you make the working area box bigger to also include the block above the dirt where the saplings should be placed? possible the robots need that in their zone as well to work
