### ISSUE TITLE
[1.7.10] Lumber jack and Leaf Cutter robots

### ISSUE THREAD

**Issue by Leytek** [BuildCraft/BuildCraft#3371]
I have tree farm with one Planter, two Lumber jacks, three Leaf Cutters and five Pickers. Planter and Pickers work fine, but sometimes one of Lumber jacks or Leaf Cutters gets lost somewhere and i can find it dead usually after reloading, somewhere near the farm, outside working area.
![2016-06-15_02 45 29](https://cloud.githubusercontent.com/assets/2747898/16063820/b917dcb6-32a4-11e6-8d91-3fa06573e110.png)
Settings in gates are pretty simple. It's just "Work in area" actions.

**Comment by AEnterprise** [comment]
alot of things are rewritten in BC 8 (for MC 1.9 though) so this might be fixed then although knowin ght exact cause is almost impossilbe.

most likely scenario is that they got stuck in trees, tried to go to another recharge station (close from where they where) but ran out of power allong the way, if that's the case it's almost impossible to fix

**Comment by Leytek** [comment]
Why this does not happen with Pickers ? They sometimes get stuck in the leaves and lost energy, but they stay there before i pick them and they never leave working area.

**Comment by AEnterprise** [comment]
are you sure the working area for those robots is correct? it seems like you have them hooked to different gates

**Comment by Leytek** [comment]
Working area is correct. All robots except planter have same working area. I will try to catch the moment when robot getting lost.
