### ISSUE TITLE
crash- MC 1.7.10, latest stable BC, Forestry

### ISSUE THREAD

**Issue by zacekjakub** [BuildCraft/BuildCraft#3373]
Hello,

we have the latest 1.7.10 stable version of BC, using own modpack. Forestry is included. Crafting wood gear, the client just crash. The recipe is not in TMI nor CraftGuide. Could you help me please? Thank you.

[crash-2016-06-19_18.52.38-client.txt](https://github.com/BuildCraft/BuildCraft/files/322408/crash-2016-06-19_18.52.38-client.txt)

**Comment by AEnterprise** [comment]
what exactly are you clicking? the crashlog doesn't mention BC but NEI is in the stacktrace, can you replicate with just BC? if not try updating your mods or removing them one by one untill you find the combination that crashes

**Comment by zacekjakub** [comment]
Thank you, trying. If I create new world on my localhost, it works. I am trying to implement NEI on the server side now. But it worked all the time, this is our first issue.

**Comment by zacekjakub** [comment]
Without NEI. :)

[crash-2016-06-19_19.52.12-client.txt](https://github.com/BuildCraft/BuildCraft/files/322429/crash-2016-06-19_19.52.12-client.txt)

**Comment by AEnterprise** [comment]
alright it seems to some invalid data on an itemstack, the wooden gear is a component for alot of things and that version is out a while so if it was just BC then it would have been found earlier.

you still have a large modlist, can you trim it down to the min set of mods required to cause the crash? most likely another mod is messing with the recipe

**Comment by AEnterprise** [comment]
closing due to lack of information
