### ISSUE TITLE
Update to 1.10 already.

### ISSUE THREAD

**Issue by VerbosePotato** [BuildCraft/BuildCraft#3374]
Test issue.

**Comment by AlexIIL** [comment]
You what?

Nope.

**Comment by VerbosePotato** [comment]
Huh. SO I can't re-open this.

**Comment by AlexIIL** [comment]
That's not good then. I've been giving people bad advice for a while then :P

**Comment by AEnterprise** [comment]
yeah you can't re-open but he can, to prevent people keeping issues forced open
