### ISSUE TITLE
[from forum] Refinery crash

### ISSUE THREAD

**Issue by AlexIIL** [BuildCraft/BuildCraft#3376]
[forum link](http://mod-buildcraft.com/forums/index.php?topic=166.0)

I added 4 refineries to my world to produce Biodiesel, and the server crashed after they ran for a little while. They are powered by Fluxducts, and input/output of Ethanol/Biodiesel use Fluiducts. Both of these are from Thermal Expansion (I think).

Now the server crashes on startup (the refineries are in a chunk loaded area).

Description: Ticking block entity
````
java.lang.NullPointerException: Ticking block entity
	at buildcraft.factory.TileRefinery.func_145845_h(TileRefinery.java:106)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
````

Here is the full crash report: http://pastebin.com/8Ekx3D17

Things I have tried:
Updating to buildcraft-compat-7.1.5 (was 7.1.3)
Buildcraft appears to be up to date already buildcraft-7.1.16
Removed FastCraft (optifine is not installed)
I found another post on this forum that referenced IC2 additional pipes, but I don't see anything similar to that installed.

Any help would be greatly appreciated. Thanks in advance.

-Veylen

**Comment by AEnterprise** [comment]
looking at the code here is the crashing line:
https://github.com/BuildCraft/BuildCraft/blob/7.1.x/common/buildcraft/factory/TileRefinery.java#L106

looks like the mod that is adding that recipe (forestry most likely) is returning null instead of a CraftingResult, if i recal correctly from when i last worked with this for BCA you are not suposed to do that but return a CraftingResult with no actual results

**Comment by JoshHawley** [comment]
Another thing that I tried was putting a drum from extra utilities in between the stills(forestry) and the refinery(buildcraft). It has not crashed since then, and so I suspect that it is related to forestry.

-- Veylen

**Comment by AEnterprise** [comment]
most likely a faulty recipe being added
