### ISSUE TITLE
[8.0.x] [Suggestion] Watts should be Joules

### ISSUE THREAD

**Issue by adudney** [BuildCraft/BuildCraft#3381]
As 1 Watt = 1 Joule / Second, 1 Watt / Tick = 1 Joule / Second / Tick, which is seemingly incorrect.

- https://github.com/BuildCraft/BuildCraft/blob/8.0.x/common/buildcraft/api/mj/IMjReciever.java#L15
- https://github.com/BuildCraft/BuildCraft/blob/8.0.x/common/buildcraft/api/mj/IRedstoneReceiver.java#L12
- https://github.com/BuildCraft/BuildCraft/blob/8.0.x/common/buildcraft/core/tile/TileEngineRedstone_BC8.java#L13
- https://github.com/BuildCraft/BuildCraft/blob/8.0.x/common/buildcraft/energy/tile/TileEngineStone_BC8.java#L19 and https://github.com/BuildCraft/BuildCraft/blob/8.0.x/common/buildcraft/energy/tile/TileEngineStone_BC8.java#L61
- https://github.com/BuildCraft/BuildCraft/blob/8.0.x/src_old_license/buildcraft/transport/PipeTransportPower.java

**Comment by AlexIIL** [comment]
Yeah those are leftovers from when I planned MJ to be passed around as true watts (or "I give you X watts for the foreseeable future"). I'll fix the comments where "watts" is used instead of "joules" :)
