### ISSUE TITLE
Cofh mod mess up with BuildCraft

### ISSUE THREAD

**Issue by runescapejon** [BuildCraft/BuildCraft#3393]
Hello so i am crashing using Tesseract from Thermal Expansion mod its because of It's including parts of the API it shouldn't be and it's getting all screwed up. i had test it by have server with Thermal expansions mod and adding 1 by 1 and i had found it 
here is the crash report http://pastebin.com/pxGPwNp3

**Comment by AEnterprise** [comment]
this crash is not caused by BC, this is COFH crashing. It indeed might be due to an api conflict but BC does not ship that part of the api so it must be one of the other mods you have loaded

**Comment by runescapejon** [comment]
i had already submit an issue on there earlier they said its another mod so i scan through the mod list and only one came up a clear indication that it is buildcraft you can read this crash report and see the mod list  http://pastebin.com/52wEbc2t but about the issue i made on the other issue you can read them here 
https://github.com/CoFH/Feedback/issues/1206

**Comment by AEnterprise** [comment]
i think you have missmatched versions of cofh core and the mods that use it, i am looking at the 7.1.x branches of BC and BCC and neighter includes the `cofh.api.transport` package, only the `cofh.api.energy` package

you can confirm this yourself by opening the BC jar with 7zip/winrar and looking through it, you won't find that package in the jar

**Comment by runescapejon** [comment]
Sorry I don't understand because it look like i have the right version these are the versions i currently have install https://gyazo.com/e0fec7d4c8861891ccbb581b5ecc5502

**Comment by AEnterprise** [comment]
what i mean is that this can't be caused by buildcraft as that does not ship the part of the api that is crashing, if you only have BC and cofh mods then i suspect your cofh core is outdated for the cofh mods you have or the other way around

**Comment by runescapejon** [comment]
i do have the latest one just check and yes i do have the latest version of cofh core

**Comment by runescapejon** [comment]
it seem i didn't put CoFHLib reason why i didn't put it because i was following the installation on this page http://mods.curse.com/mc-mods/minecraft/thermalexpansion#t1:description i guess its there fault for putting outdated information

**Comment by runescapejon** [comment]
the problem came back and CoFHlib core didn't do anything at all, Buildcraft mod including something that they should not be.

**Comment by AlexIIL** [comment]
Can you post a new crash log? It might differ from the old one

**Comment by runescapejon** [comment]
http://pastebin.com/JXfMg84Q

**Comment by AlexIIL** [comment]
You most likely have mismatched versions of one of the cofh mods.

Please note that this *still* is not caused by buildcraft though.

**Comment by AEnterprise** [comment]
same problem, some mod is shipping an outdated version of the COFH ender api, definatly not buildcraft

**Comment by runescapejon** [comment]
I don't understand i have the, all update that latest one's that are on curse page's

**Comment by AlexIIL** [comment]
@runescapejon sorry, I was wrong about COFH being the wrong version. What I should have asked is have you changed your mod list (or updated any mods) between when you got it working a few weeks ago and now? I ask as it looks like one of your mods is shipping with an older version of a COFH API (so what @AEnterprise said)

**Comment by runescapejon** [comment]
Reason why it work few week's ago because i had an old version of Buildcraft, When i update it the problem started, i was confusing myself because few week's i was messing with BuildCraft version and i had mismatch version once i fixed the problem COFH mod's started problem's  happen between Buildcraft.
Cofh api i don't understand, when i take out Buildcraft the COFH problem goes away so It's not other mods as fair from my understanding, Sorry for any confusion 


BuildCraft - 7.1.16
BuildCraft - 7.1.3

**Comment by AEnterprise** [comment]
@runescapejon it simply can NOT be buildcraft itself, buildcraft doesn't even touch that part of the api, it seems to be a mod loading order issue. most likely the mod that is actually causing this is saying to forge it has to be loaded before buildcraft or right after it.

if mods do not need to be loaded before/after a specific mod they are loaded in alphabetical order, this mod is normaly loading after cofh lib so that api is loaded as forge finds it first, when adding buildcraft said mod is declaring it needs to be loaded before (or more likely right after) buildcraft, this causes a shift in the order of the mod list to load, that mod is now loaded before cofh lib causing forge to load the outdated api

**Comment by runescapejon** [comment]
So i had take out Cofh lib and the problem went away, It's weird because before I added cofhlib it was happening but thanks tho
