### ISSUE TITLE
Filler in the Nether - Crash

### ISSUE THREAD

**Issue by evernife** [BuildCraft/BuildCraft#3395]
Having [this crash](http://pastebin.com/TNzuAC7G) when someone use the Filler in the nether, this does not occuer everytime, but, sometimes crash the server :C

**Comment by AlexIIL** [comment]
Do you know what size the filler was set up with?

**Comment by evernife** [comment]
Not the size, but the heigh it was in the nether "224" as mentioned in the crashreport.

687,224,25

The players had bypassed the nether upper bedrock

**Comment by evernife** [comment]
in my server, the markers are limited to 21blocks of distance
