### ISSUE TITLE
what is this, i dont even. missing quarry.

### ISSUE THREAD

**Issue by plaguewolf** [BuildCraft/BuildCraft#3396]
at first i thought that i had somehow derped up and set the filters for NEI in such a way that the quarry wasn't showing up. but no, it appears that something is deliberately removing the quarry recipe.

i added quarry plus, because the BC quarry is a component of its recipe, in hopes to get the recipe for BC quarry, but upon checking the recipe, i find that its missing entirely.

since i have some 200 mods installed, doing a binary split check thingy is annoying AF, so i was hoping to check in here, in case someone knew if a specific mod has removed the quarry recipe.

relevant info, i play with gregtech unofficial 5.09.21, even though i know GT isnt removing it, as that was the first thing i checked (ie, launched with only BC, IC2, GT, and NEI).

meh, id appreciate some feedback, maybe even a way i can lookup what recipes are changed, like a way to dump the entire recipe table to database/spreadsheet

**Comment by AlexIIL** [comment]
Does this happen if you remove quarry plus? Also does the quarry exist as a block, and can you craft it even though the recipe doesn't show?

**Comment by plaguewolf** [comment]
yeah see, thats the thing, i looked up the gregtech quarry recipe on wiki, and tried to craft it, and it doesn't work, and quarry plus has nothing to do with it disappearing, i just used that in a simple test, because i couldn't think of anything else that uses the BC quarry as a recipe.

my next step will be to use minetweaker to make a custom recipe for MC stick = BuildCraft:Builders:machineBlock>

**Comment by AEnterprise** [comment]
if you have minetweaker check the scripts first to make sure there isn't one loaded that is removing the BC quarry recipe

if that's not the cause you can try looking through your log to see if whatever is removing the recipe is nice enough to log a message about it, a binary search is the only other way to find out what mod is removing the recipe

**Comment by plaguewolf** [comment]
yeah... sigh, imma have to do the binary search, troublesome.

i'll be sure to post when i figure out whats doing it.

**Comment by plaguewolf** [comment]
well poop. NuclearCraft. and i liked that mod. now to find out if its intentional, or a conflict.

**Comment by plaguewolf** [comment]
well this is weird, and makes me feel downright silly. 
made a test instance, with only BC, NEI, and NuclearCraft, and the quarry is there. but renamed into machine base.

:facepalm:

**Comment by AEnterprise** [comment]
sounds like there is a localization conflict then

**Comment by plaguewolf** [comment]
mmmhmmm. guess im gonna close the issue.

https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/resources/assets/nc/lang/en_US.lang#L57
tile.machineBlockNC.name=Machine Base
