### ISSUE TITLE
Conductive pipes wont work?

### ISSUE THREAD

**Issue by oMufassa** [BuildCraft/BuildCraft#3399]
I've been playing Tekkit Classic, and when I try to hook my combustion engine to the Wooden Conductive Pipes, it doesnt push the power through.... The Engine has fuel and water, it IS pumping, but nothing is happening with the pipe. Im trying to hook it to an Energy Link but the blue line doesnt come up in the pipes.... ALSO I tried the same setup on single player creative and it WORKED.. Any suggestions?

**Comment by AEnterprise** [comment]
i have no idea what BC version is in tekkit classic exactly but i do know that it's ancient, if you are sure the setup is exactly the same can you check the block that is supposed to recieve the power to check if it recieves or not? might be a syncing issue

if not screenshots might help but i don't think we'll be able to do much as the version is realy old

**Comment by oMufassa** [comment]
![capture](https://cloud.githubusercontent.com/assets/20627422/17085368/ede0bdfa-518a-11e6-95ce-03fdf6a04743.JPG)
![capture2](https://cloud.githubusercontent.com/assets/20627422/17085369/f1f027b4-518a-11e6-8e31-bbf32838253d.JPG)

**Comment by AEnterprise** [comment]
what is the block you are hooking the power from and is it actually accepting power? try replacing the block with something that can store the energy or a machine, if you see a bit of powerflow then it works, it is possible the machine just isn't in need of power

**Comment by oMufassa** [comment]
I am trying to use a combustion engine to conver to EU power and store energy into an MFSU, the block you see is and Energy Link...... Maybe there is another way to do this? I know now that the pipes do work with a combustion engine because i used them to power a quarry

**Comment by AEnterprise** [comment]
seems this issue was forgotten: if you can use the engine and pipes to power a quarry the issue is not on BC's end, i suspect you misconfigured the energy link or it is bugged
