### ISSUE TITLE
MFSU Bug

### ISSUE THREAD

**Issue by oMufassa** [BuildCraft/BuildCraft#3400]
Any way to reset a MFSU so i dont have to break it lose all my energy when it bugs out and stops emmitting energy... Tekkit Classic.... Everything is set up correctly, just when i leave the world it stops emmitting, only when i place it down again does it work

**Comment by dj3520** [comment]
The MFSU is from Industrial Craft 2, not Buildcraft. Also, use an IC2 electric wrench in lossless mode.
