### ISSUE TITLE
Zone planner map blank!

### ISSUE THREAD

**Issue by 2fast4u2** [BuildCraft/BuildCraft#3401]
The zone planner's map is blank on the exterior and the gui. Also, the zonemap folder is empty!
![image](https://cloud.githubusercontent.com/assets/18731441/17200931/5202fab8-543e-11e6-9355-5b6580a71e8e.png)
![image](https://cloud.githubusercontent.com/assets/18731441/17200935/66febaa6-543e-11e6-8f8b-eacb8ed7ed75.png)

**Comment by AEnterprise** [comment]
i'm guessing you are on 1.8.9 (if not please post you MC and BC versions with what other mods are installed)

if so the zoneplanner isn't ported yet but it being worked on

**Comment by 2fast4u2** [comment]
Buildcraft 7.0.11
Minecraft 1.7.10
other mods here
![image](https://cloud.githubusercontent.com/assets/18731441/17236423/ba8abdcc-54fd-11e6-91a7-c02346f209e2.png)

**Comment by AEnterprise** [comment]
that's a very outdated version of buildcraft, please update to the latest for 1.7.10 (7.1.16) and try again, the bug is most likely already fixed

**Comment by dj3520** [comment]
Just adding my two cents...Galacticraft is on revision 462. Those file
dates are misleading.

**Comment by AEnterprise** [comment]
@dj3520 i know, the dates are from a few days ago but the file versions are alot older, that's just when his modpack was downloaded

**Comment by 2fast4u2** [comment]
If i upgrade the version, will it cause conflicts with the world?

**Comment by AEnterprise** [comment]
no upgrading your mods should not cause a problem

**Comment by AlexIIL** [comment]
It shouldn't break your world, but you should keep in mind that the 7.0.x -> 7.1.x update had a few build-breaking changes (like quartz fluid pipes no longer connect to stone and cobble fluid pipes.

The zone planner exterior was added in the 7.1.x update.

Just so you know @AEnterprise the 7.2.x branch for 1.8.9 has *everything* working and ported. Except for minor bugs. (The only reason it's beta is that it cannot transfer 1.7.10 worlds atm.)

**Comment by AEnterprise** [comment]
@AlexIIL alright, thought there where still a few things remaining that didn't quite work like they used to

**Comment by AEnterprise** [comment]
still an issue? if so will this get fixed on 7.2.x or 8.0.x?

**Comment by afdw** [comment]
@AEnterprise It's probably outdated. In 8.0.x zone planner was rewritten from scratch.

**Comment by AEnterprise** [comment]
@afdw alright i'll asume this is fixed then as i presume it would be found in testing if it was broken
