### ISSUE TITLE
[1.8.9] Lumberjack robots don't recognize IC2 rubber trees

### ISSUE THREAD

**Issue by KKyang** [BuildCraft/BuildCraft#3402]
The Planter robots can plant rubber samplings but the Lumberjack robots don't cut down the rubber tree.

IC2 accepts rubber wood to make rubbers. (An alternative way to using a treetap.)

The workaround in #3106 doesn't work because Forestry and IC2 crops are not supported in MC 1.8+.

**Comment by AEnterprise** [comment]
do you have BC compat installed? if not try if it makes the robots recognize the tree. If not open an issue on the IC2 issue tracker asking them to provide support for it, the robot api allows for registering special trees

**Comment by KKyang** [comment]
Yes. I have Buildcraft compact installed and still not working in SSP.

**Comment by AEnterprise** [comment]
best thing you can do is to ask the ic2 devs to implement BC compatibility

**Comment by AEnterprise** [comment]
ic2 or BCC needs to add compat so closing this for now

@AlexIIL should i open a ticket for BCC or the ic2 tracker?
