### ISSUE TITLE
Missing BC Version on Curse

### ISSUE THREAD

**Issue by DragScorpion** [BuildCraft/BuildCraft#3404]
The Version 7.1.17 is missing on Curse

**Comment by AEnterprise** [comment]
i uploaded it to curse yesterday but the files where rejected, currently contacting curse to find out why

also sorry i didn't upload earlier, somehow i forgot :/

**Comment by AEnterprise** [comment]
files are on curse, can be closed

**Comment by AlexIIL** [comment]
Thanks :)
