### ISSUE TITLE
Issue with Builder Robot on server

### ISSUE THREAD

**Issue by NaveNO** [BuildCraft/BuildCraft#3405]
So, I made a test blueprint of some blocks. I configured all Emerald Gates, set working area with chest included. Everything is perfect. But when I start robot, it flew away a bit and started rotating. This happens only on a server. In singleplayer everything is perfect.

Here are screenshots:
http://prntscr.com/c0b5n6
http://prntscr.com/c0b7cn
http://prntscr.com/c0b7g1
http://prntscr.com/c0b7rt
http://prntscr.com/c0b827

**Comment by AlexIIL** [comment]
What BC version are you using? Also, do you use any other mods on the server that you don't on the client? (For example thermos or other bukkit-type mods)

**Comment by NaveNO** [comment]
BuildCraft 7.1.16 and I am not the owner of a server. But I know, that there is liteloader with WorldEdit installed. Thats all I know..

**Comment by NaveNO** [comment]
No idea how to fix that?

**Comment by AlexIIL** [comment]
No :(

**Comment by AlexIIL** [comment]
I'll clarify that a bit: I have no idea why a robot would just start to go somewhere else other than if there was another task for the robot to do elsewhere. Where does the robot go, if anywhere? Or does it just stop in midair without doing anything?

**Comment by NaveNO** [comment]
Well, firstly it took off from a docking station, then flew away from marked building zone and started rotating all the time. I placed my blueprint into construncion mark, but robot cant see that. Also it ignored chest with items. P.S. As I notised, it happens  only on server. In singleplayer it was building very good.

**Comment by AlexIIL** [comment]
Can you try to replicate the server yourself (so grab all the mods that you have in singleplayer, but with a forge server) and see if the behaviour still happens? (Or at best get the server files directly from the server owner) So you can test to see what causes this - whether its BC by itself on a server that fails, or whether it happens when you add a lot of mods back in.

**Comment by NaveNO** [comment]
Well, I recreated forge server with all mods. And builder robot is working fine! That is strange -_- And @AlexIIL one more question - why robot is taking only 1 block? Cant it take more blocks?

**Comment by AlexIIL** [comment]
Sounds like there is some other difference between the server and your local server, maybe there is a difference in the map, or the robot was in a bad state on the server and it needed placing down again. (And you could try rebuilding the robot infrastructure from scratch to see if you you had made a mistake when you placed it down).

The robot builder needs a buff - a single block is a tiny amount :/

**Comment by NaveNO** [comment]
Okey, I will notify a server owner and rebuild robots infrastructure ;)

**Comment by AEnterprise** [comment]
is this still an issue?

**Comment by NaveNO** [comment]
I can`t say exactly, caurse BuildCraft isn`t updated on a server. Let me know, if I can somehow test it out.

**Comment by asiekierka** [comment]
The Builder Robot is not likely to get further fixes in 1.7.x/1.8.x, I'm afraid, due to its low usefulness and other major flaws.
