### ISSUE TITLE
[1.7.10] Seemingly random crashing

### ISSUE THREAD

**Issue by dj3520** [BuildCraft/BuildCraft#3406]
With no one logged in my server is repetitively crashing. I've tried overwriting the world from a backup a few days old but the issue persists.

I've put the relevant crash reports [on my server for viewing here](http://net.dj3520.net:8000/servitup/BC-crash/) (opens in browser, not download) as well as the last fml-server-latest.log (old ones are deleted just before startup)

[Mod listing and versions](http://net.dj3520.net:8000/minecraft/modlist.btm)

I would try to give more information but I'm not sure what the issue is.

**Comment by AlexIIL** [comment]
It looks like something went wrong with the buffer refreshes for some of the tiles, and all of them seem to be valid indexes.

(Index 2, size 6 is valid, right? Or am I really confused?)

Although after a bit of looking, it looks like world.getTileEntity is crashing, so I think KCauldron is to blame here (try updating it?)

**Comment by AEnterprise** [comment]
@AlexIIL index 2 size 6 is valid yes

**Comment by dj3520** [comment]
KCauldron updated to 1.7.10-1614.201 and has yet to crash. Wasn't updating because I had seen some strange behaviors before, but so far everything looks as though it's fine (after a bit of fixing in-game.)
