### ISSUE TITLE
Quarries hang when trying to break blocks from The Aether II

### ISSUE THREAD

**Issue by TheDeviantCrafter** [BuildCraft/BuildCraft#3407]
When attempting to build a quarry in the overworld, it works normally.

When using the same set up in The Aether, it gets stuck and tries to break the same block indefinitely, causing some pretty nasty FPS lag. It seems to involve client-server packet spam, because trying to open chests in the area lags, but it's fine once you stop rendering the area. Also, no "running X ms behind!" messages appear in console.

Early in development (or perhapse it's optional) you could only use Aether tools. So when you break a block, it checks your tool type, and then decides if it broke or not. I'm guessing quarries are not sure how to deal with that.

One report says that this does NOT happen on multiplayer servers, So far only SSP worlds have been affected.

Other details:

Minecraft version: 1.7.10
Forge version: 10.13.4.1614
Aether version: 1.7.10-1.6
Buildcraft version: 7.1.16

**Comment by AEnterprise** [comment]
sounds like th bug is on the Aether side, it works on regular servers so that proves BC quarries can break them, somehow they have a incorrect server side check that doesn't fire in singleplayer i suspect

**Comment by AEnterprise** [comment]
closing as it seems like the bug is from Aether and no further info has been given
