### ISSUE TITLE
Gates cause constant chunk re-renders when active

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3409]
BC 7.2.7
Forge 11.15.1.1902

While testing to see how performant BC pipes are in the newer versions, I built a 16x16 cube of transport pipes. This causes a bit of framerate lag which is understandable as it is only a little bit less performant than fences. But when active activating a gate on a wooden transport pipe, my framerate will immediately drop to 0/1 fps and will stay like this until I deactivate the gate. I have spoken to Alex and it is believed that when a gate is active it causes constant chunk re-renders.

Just making an issue here as a reminder to alex who already knows about it :)

Thanks,
- LuigiHutch

**Comment by AEnterprise** [comment]
is this still an issue?

**Comment by AlexIIL** [comment]
Yep.

**Comment by LuigiHutch** [comment]
Fixed in 7.99
