### ISSUE TITLE
Pipe lighting inconstistant compared to BC 7.1.X

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3410]
BC 7.2.7
Forge 11.15.1.1902

Pipes look alot brighter (and imo worse) in the 7.2.X builds compared to the 7.1.X builds.
Images for comparison: http://imgur.com/a/Mgq3g. They are all taken looking west.

I believe this is unintended so I believe it is a bug, if it is intended it can be closed.

Thanks,
 - LuigiHutch

**Comment by AEnterprise** [comment]
i think this is due to the lighting changes in the redering code, they improved the lighting for partialy seethrough models like these pipes alot

**Comment by AlexIIL** [comment]
This took a while to figure out what was happening, but after I implemented the 8.0.x pipe model baker it became obvious: I didn't apply face-darkening to the pipes! Unfortunately this won't be fixed in 7.2.x, but it is fixed for 8.0.x. Which is nice.
