### ISSUE TITLE
Engines stuck placed upwards MAC

### ISSUE THREAD

**Issue by Chloe97** [BuildCraft/BuildCraft#3412]
Hi, 
Playing version 1.8 and every time engines are placed they are stuck upright. I understand there is a way to change this if I were using a PC but have not found a way to fix for MAC. 
Thanks.

**Comment by AlexIIL** [comment]
Hi, what specific version of Buildcraft are you using? (Basically if you are playing on minecraft 1.8.9 with Buildcraft version 7.2.6 or not)

**Comment by AEnterprise** [comment]
what exactly do you mean with a way to fix on a PC but not on MAC? the only MAC i know is an OS but i doubt that is what you ment, can you clarify?

**Comment by Chloe97** [comment]
Minecraft 1.8 with the 1.8 version of BuildCraft. the .jar file is called buildcraft-0.10-alpha.jar

**Comment by Chloe97** [comment]
Sorry everyone, I do lack tech talk. I am using my mac desktop. I have googled my question, being everytime i place engines they are stuck facing upright, even placed side-by-side. When I searched i came across a youtube video for a PC on how to fix but I cant seeing as im on mac and cant access those files. I will copy and paste the video i found. https://www.youtube.com/watch?v=tXvYWNp6oyM

**Comment by AlexIIL** [comment]
@Chloe97 That's a very old version of Buildcraft, can you try creating a new installallation with BC 7.2.7 (download from here http://mod-buildcraft.com/pages/download.html) and see if it still happens?

(Also note that engines can only be rotated towards a valid power receiving blocks, like a wooden kinesis pipe or a pump, and you can rotate them with a wrench.)

Unfortunately that video is very old, so I don't think it will be helpful. Unless you are using minecraft BETA 1.8.

**Comment by Chloe97** [comment]
So I was trying to place it next to a pump- could that be my problem?
Thanks for the speedy replies guys! Appreciate it :)

**Comment by AEnterprise** [comment]
@Chloe97 the file path mentioned in that video is indeed a windows only path, your minecraft folder should be at '/Library/Application Support/minecraft' on mac

@AlexIIL he is using minecraft beta 1.8 looking at the video

**Comment by Chloe97** [comment]
Thanks guys! All fixed thanks to the different instalment. Thanks for all the help!
