### ISSUE TITLE
Initialization crash-other mods present

### ISSUE THREAD

**Issue by DoomShark** [BuildCraft/BuildCraft#3413]
Game crashes during initialization. Not sure if it's because of other mods installed or not. Here's a list of them:
   Custom NPCs
   Ex Nihilo 2
   Extra Utilities 2
   Highlands
   Intangible
   JEI
   Journey into the Light
   Lemon's Simple Teleporters
   Mythical Blessings
Crash Report:
[crash-2016-08-11_09.25.55-client.txt](https://github.com/BuildCraft/BuildCraft/files/413442/crash-2016-08-11_09.25.55-client.txt)

**Comment by AlexIIL** [comment]
Unfortunately BuildCraft requires Java 8 rather than Java 7 or 6. So if you upgrade Java from 7 to 8 (and make sure MC is using Java 8) it will work fine.
