### ISSUE TITLE
Buildcraft 7.1.16 and 7.1.17 world generation issue.

### ISSUE THREAD

**Issue by MasterGamerPL** [BuildCraft/BuildCraft#3414]
Generator generate this water structure.
![2016-08-12_18 39 43](https://cloud.githubusercontent.com/assets/20995127/17629759/5b02341e-60bc-11e6-8205-d1a8c2b42c16.png)
This structure is 1x1 and go down to bedrock.
Water in bedrock is impossible to delete

**Comment by robin4002** [comment]
This is not a bug but a feature.
It's a water spring block. You can disable it in the configuration file. (worldgen.generateWaterSprings)

**Comment by MasterGamerPL** [comment]
Thanks
