### ISSUE TITLE
lag problem

### ISSUE THREAD

**Issue by runescapejon** [BuildCraft/BuildCraft#3415]
Hello there a lag problem here the log's http://pastebin.com/KxbsJXBb

**Comment by AEnterprise** [comment]
thanks for your report but i see 3 problems here:

1) you are running thermos, that makes some very serious edits to the way minecraft and forge work and can produce issues like this
2) the 2nd line of that log is asking you to report it at https://github.com/CyberdyneCC/Thermos/issues, if you opened an issue there and they said to report it here please link that issue and/or give the reason they said to report it here
3) while buildcraft is indeed in the thread dumps it is on seperate threads, your server has been killed by the server watchdog, that means that the main thread become unresponsive, from the log it looks like it tried to unload the world and got stuck

**Comment by runescapejon** [comment]
Thanks you, the reason why i wanted to report here instead of Thermos it's because i read the log's and saw that it's BuildCraft problem, i never gave it a tho that it could have be thermos problem also 
i'll go ahead and report it there also
