### ISSUE TITLE
support 1.10.2?

### ISSUE THREAD

**Issue by Javacym** [BuildCraft/BuildCraft#3416]
BC support mc1.10 now?

**Comment by afdw** [comment]
No. Please wait. Only 1.8 now.

**Comment by AEnterprise** [comment]
Buildcraft supports 1.8.9, a 1.9 version is in the works, from there the jump to 1.10 should be minor

also please don't ask for specific timings, buildcraft is a very large and complex mod, updating it takes time

**Comment by asiekierka** [comment]
A rewrite is happening. It will take time. Lots of it.
