### ISSUE TITLE
Quarry does not work

### ISSUE THREAD

**Issue by Arobcher** [BuildCraft/BuildCraft#3417]
I'm on the server adds Authme, leading to the quarry can not destroy the box, you need to Authme \ config in UnrestrictedName add a user name, how do I add?
![094652p1yey3rr5zrfym48 png thumb](https://cloud.githubusercontent.com/assets/11995478/17700746/a3423c70-63f9-11e6-870c-0440a24bbd0b.png)

**Comment by asiekierka** [comment]
"/buildcraft op" might help. If not, you might need to grab the BuildCraft
user UUID from the server startup logs and force AuthMe to consider it as
not requiring login.

2016-08-16 15:18 GMT+02:00 Arobcher <notifications@github.com>:

**Comment by Arobcher** [comment]
How do I set up in the server log or above Authme

**Comment by AEnterprise** [comment]
assuming you got this fixed, if not you'll want to ask support from the Authme community on how to configure that correctly
