### ISSUE TITLE
[1.8.9] Buildcraft makes Localized Weather & Stormfronts v2.3.11 not render any storms

### ISSUE THREAD

**Issue by killerbigpoint** [BuildCraft/BuildCraft#3418]
I tried to run minecraft with only those 2 mods and it didn't render the storms created from Localized Weather. Then if i removed Buildcraft it rendered them flawlessly

**Comment by killerbigpoint** [comment]
By the way: im using Buildcraft 7.2.7 Beta AND i also tried with Buildcraft 7.2.7 Compat but no luck

**Comment by AEnterprise** [comment]
are you still having this issue? if so did you try reporting it to Localized weather? are there any other mods involved?

**Comment by killerbigpoint** [comment]
Yes im still having this issue, and yes i only used the weather mod and buildcraft. I will try to report it to the weather mod's developer

**Comment by AEnterprise** [comment]
@killerbigpoint any update on this?

**Comment by AEnterprise** [comment]
closing due to lack of information and it's very doubtfull BC is the root cause of the issue as there are no rendering hacks in BC
