### ISSUE TITLE
Landmark Dupe Glitch

### ISSUE THREAD

**Issue by dogemanmcgee** [BuildCraft/BuildCraft#3421]
Nothing major - can't really be abused into duping other items..as far as I know. 

https://www.youtube.com/watch?v=2qTh9erQaLo

Also can the reviewer of this check my question on this ticket:
https://github.com/BuildCraft/BuildCraft/issues/2129

**Comment by AEnterprise** [comment]
that's a weird bug, what MC and BC version is this?

**Comment by dogemanmcgee** [comment]
This is 1.7.10 FTB Infinity Evolved, and my buildcraft is 7.1.16

**Comment by AEnterprise** [comment]
@AlexIIL is this fixed for BC 8.0 with the rewrite or still a problem? i'm also guessing we won't see a fix on the 7.1.x branch?

**Comment by AEnterprise** [comment]
almost definatly was caused by another mod messing with the builder, if someone can reproduce this and provide a modlist with 7.99.3 we can take a look
