### ISSUE TITLE
Builder Lag

### ISSUE THREAD

**Issue by dogemanmcgee** [BuildCraft/BuildCraft#3422]
It's become a huge problem for me and it's annoying many people on the server I play on. Here's what happens: I start building a massive (200x200x150, there are also no modded blocks in the build!) build and if I decide to right click on my builder, everyone on the server gets a "timed out" error and the server is unresponsive for the next ~10 secs, depending on how long I kept the builder screen open. This also happens in single player but is much more detrimental in multiplayer. My best theory is that it's having trouble rendering such a big build, because the timeout scales down greatly when the build is smaller. It could also have something to do with chunkloading.

**Comment by AEnterprise** [comment]
i'm asuming this is with the same BC versions as your other issue (#3421) ? if so how did you make a blueprint that is that large? did you use an addon or the composite blueprints? if it's an addon please try without that addon

can you provide a server log of when this is heapenening? and what are the server run arguments? might be running low on ram

**Comment by dogemanmcgee** [comment]
Yeah, same version. I made it by changing the config to landmarks being able to be 200 blocks, no addons.

I don't have the server log, it's not my server and I don't have a server to try it on. I think you're right on it running low on ram, though. The only thing the console says during the time (i'm told) is that it says it's running behind.

**Comment by AEnterprise** [comment]
alright, can you ask the sever owner if he can investigate? the problem isn't purely BC as it works fine for others. granted there might be optimalizations that can be done to midigate it but most of the time it is the server barely keeping up with regular playing and then more intense things like the builder can lag

a workaround could be to split the blueprint in multiple smaller ones

**Comment by dogemanmcgee** [comment]
The server can keep up with ~8 players pretty fine, rare lagspikes. I'll try to get into contact with the owner, granted it will take a while. Yeah, I'm trying the blueprint splitting now. Thanks
