### ISSUE TITLE
[1.8.9] Builder crash when removing it while a landmark path attached

### ISSUE THREAD

**Issue by Sp3rw3r** [BuildCraft/BuildCraft#3424]
Minecraft crashed when I removed a builder. The builder was attached to a path created by landmarks to repeat the building.

**Comment by AlexIIL** [comment]
Can you upload the crash report to pastebin or gist and post the link here? (There is very little that I can do without one)

**Comment by Sp3rw3r** [comment]
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 1-9-16 13:56
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property BuildCraftProperty [name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]] as it does not exist in BlockState{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
	at buildcraft.builders.TileBuilder.iterateBpt(TileBuilder.java:329)
	at buildcraft.builders.TileBuilder.func_73660_a(TileBuilder.java:563)
	at net.minecraft.world.World.func_72939_s(World.java:1718)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
	at buildcraft.builders.TileBuilder.iterateBpt(TileBuilder.java:329)
	at buildcraft.builders.TileBuilder.func_73660_a(TileBuilder.java:563)

-- Block entity being ticked --
Details:
	Name: buildcraft.builders.Builder // buildcraft.builders.TileBuilder
	Block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-168,4,-66), Chunk: (at 8,0,14 in -11,-5; contains blocks -176,0,-80 to -161,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1718)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

-- Affected level --
Details:
	Level name: Copy of 1.8.9
	All players: 1 total; [EntityPlayerMP['Sp3rw3r'/1431, l='Copy of 1.8.9', x=-164,78, y=5,01, z=-65,37]]
	Chunk stats: ServerChunkCache: 349 Drop: 0
	Level seed: -9201743238800413869
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -129,00,4,00,-39,00 - World: (-129,4,-39), Chunk: (at 15,0,9 in -9,-3; contains blocks -144,0,-48 to -129,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 125321 game time, 125321 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 3470 (now: false), thunder time: 8072 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 74771288 bytes (71 MB) / 674918400 bytes (643 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJAAAA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJAAAA	BuildCraft|Core{7.2.7} [BuildCraft] (buildcraft-7.2.7.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.2.7} [BC Silicon] (buildcraft-7.2.7.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.2.7} [BC Transport] (buildcraft-7.2.7.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.2.7} [BC Builders] (buildcraft-7.2.7.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.2.7} [BC Energy] (buildcraft-7.2.7.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.2.7} [BC Robotics] (buildcraft-7.2.7.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.2.7} [BC Factory] (buildcraft-7.2.7.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Sp3rw3r'/1431, l='Copy of 1.8.9', x=-164,78, y=5,01, z=-65,37]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by AEnterprise** [comment]
@Sp3rw3r please do not put crashlogs like that, put them on pastebin or gist instead, makes them alot easier to read, i've edited it out of your post and replaced with a link so the issue isn't a wall of text

**Comment by Sp3rw3r** [comment]
oh i just did that myself too

**Comment by AEnterprise** [comment]
unable to reproduces on 1.11.2 and with all the reworking of the builder i don't think can heapen anymore, if it does occur again feel free to open a new issue
