### ISSUE TITLE
[1.8.9] Crash related to assembly table/laser being adjacent to Immersive Engineering metal press

### ISSUE THREAD

**Issue by Boy-Blue** [BuildCraft/BuildCraft#3425]
Playing on [Eldritch Revolution](https://github.com/belathus/eldritch_revolution/issues/6) modpack.

Forge: forge-1.8.9-11.15.1.1902-1.8.9-universal
Buildcraft: 7.2.7
Immersive Engineering: 0.8-32

Crash log:
http://pastebin.com/LB9488XE

In game setup:
http://puu.sh/qRPe9/68329e94a3.png

It seems to be the table not being able to decide where to output.

Moving the table, so that it is only adjacent to the chest not chest and metal press seems to have fixed this.

http://puu.sh/qRPDg/3f20c61937.png

**Comment by AlexIIL** [comment]
Can you try updating to the latest Immersive Engineering? I've heard of this bug before with the way IE used to handle caps, so it might be the same bug as that.

**Comment by AEnterprise** [comment]
indeed, looks like that bug indeed, i know there was a 2nd round of fixing that in IE recently
