### ISSUE TITLE
Robots sink through bedrock if the docking station is broken

### ISSUE THREAD

**Issue by Baughn** [BuildCraft/BuildCraft#3429]
...while they're on it. This was with the robots set to "Go to station". Two of them, on two separate stations. They just... sank.

(1.7.10)

**Comment by LuigiHutch** [comment]
BC version? Mod list? Reproducible? If so, how could someone reproduce it?

**Comment by Baughn** [comment]
Fair points, I was a bit rushed last night.

BC version: 7.1.17, md5 8b6a20bce409fff6cdc5d22c4d122f5a.

Mod list: Large. I haven't checked if it'd happen with just BC. If you want the complete list... https://madoka.brage.info/ServerPack.xml, or https://github.com/Erisia/builder/tree/master/manifests

You can reproduce it with:
- A single wooden extraction pipe. (Probably any would do.)
- With a charged robot on a docking station.
- And a quartz OR gate (or, probably, any gate) with an active "Go to station" command.

Then just pickaxe the pipe. The robot will sink.

**Comment by LuigiHutch** [comment]
Tested with BC 7.1.17 and BC 7.2.7,  I am able to reproduce using the steps provied in both versions.

Here is a log when the error occurs: https://gist.github.com/LuigiHutch/ae6389d1b0277d85bc42d2f4fc7877eb

**Comment by AEnterprise** [comment]
alright thanks for verifying that

sounds like the robots are getting shut down correctly when they no longer have a docking station and float down to land on the ground but are failing to detect the ground and continue falling
