### ISSUE TITLE
auto workbench stops making tools

### ISSUE THREAD

**Issue by Sp3rw3r** [BuildCraft/BuildCraft#3430]
When I put materials for multiple axes in a auto workbench, it stops making tools after the 2nd.
The tools were immediately removed with a hopper since tools don't stack.
Once I looked into the inventory of the auto workbench, it resumed crafting for one more tool.

The same issue did not occur when I was crafting stack able items like wooden sticks,

**Comment by AEnterprise** [comment]
sounds like a duplicate to https://github.com/BuildCraft/BuildCraft/issues/3307 what version of BC are you using?

**Comment by Sp3rw3r** [comment]
1.8.9.  Looks like same issue except it occurs also with vanilla items.
Setup: chest, hopper and auto workbench. some stacks of stone and sticks in workbench. Pattern for axe.

**Comment by LuigiHutch** [comment]
What BC version?, not MC version :P

**Comment by Sp3rw3r** [comment]
bc 7.2.7

**Comment by AEnterprise** [comment]
yep, this is fixed then but no release has been made yet
