### ISSUE TITLE
investigate performance

### ISSUE THREAD

**Issue by AEnterprise** [BuildCraft/BuildCraft#3431]
some profiling will have to be done on BC 8.0 more specificaly the automated ways of placing and breaking blocks (filler, builder, quarry) seem to have been causing lag in the past on servers

**Comment by thomas15v** [comment]
https://github.com/BuildCraft/BuildCraft/blob/5c902744046198b8ed90d0f39d5c03907984f21d/common/buildcraft/core/blueprints/BptBuilderBase.java#L259

This event is called for every time something ticks a block. Like for the break animation. With bukkit it filled our coreprotect database in to the gigabytes in no time :/.

**Comment by asiekierka** [comment]
That's impressive. I did not know about that. Mind opening up an issue for
1.7.10 and explicitly tagging me in the title so I don't forget? (I'm not
really maintaining BuildCraft anymore, but this sounds horrifying)

2016-10-04 22:17 GMT+02:00 Thomas Vanmellaerts <notifications@github.com>:

**Comment by liach** [comment]
Ref #3109

**Comment by thomas15v** [comment]
@asiekierka #3437

**Comment by AEnterprise** [comment]
even spam has been fixed, closing this one as well
