### ISSUE TITLE
Invisible pipes and Quarry crash (1.7.10)

### ISSUE THREAD

**Issue by Willeboy** [BuildCraft/BuildCraft#3433]
Help!
When I place down pipes they are invisible and when I place down a Quarry, it crashes!
Any Ideas How I can fix this?

**Comment by AntonBoch1244** [comment]
@Willeboy Drop here crash-log.

**Comment by Willeboy** [comment]
@AntonBoch1244 Ok wait a second

**Comment by Willeboy** [comment]
@AntonBoch1244 It does not come up any crash reports whatsoever. The thing is, is that when I place the quarry down it close down minecraft, takes me back to the technic launcher and when I relog into the world it turns me back to the point where I was, before I had put down the quarry (sorry for bad english)

**Comment by AntonBoch1244** [comment]
Minecraft Version: ?
Forge: ?
BuildCraft Version: ? (try on latest version)

**Comment by Willeboy** [comment]
Minecraft Verison: 1.7.10
Forge: ForgeMultipart-1.7.10-3.6.11.2
Buildcraft Verison: buildcraft-7.1.18 and buildcraft-compat-7.1.3

**Comment by AntonBoch1244** [comment]
Steps to reproduce that error.

**Comment by Willeboy** [comment]
1. Put down a Quarry
2. It crashes

**Comment by AEnterprise** [comment]
@Willeboy that's not the forge version you provided, forgemulitpart is a seperate mod that has nothing to do with forge (it just has a misleading name)

to find the crash report: http://forums.technicpack.net/topic/58025-how-to-get-a-crash-report-so-people-can-help-you-better/

**Comment by AntonBoch1244** [comment]
@Willeboy check other mods this not problem of BuildCraft mod.(Reproducing w/o crash result)

**Comment by Willeboy** [comment]
Ok thanks for the help :)

**Comment by Willeboy** [comment]
@AEnterprise @AntonBoch1244  I found out what it was now.......
It was the damage indicators mod that made the quarry crash (Don't ask me why)
Thanks for the help and have a good day!

**Comment by AntonBoch1244** [comment]
@AEnterprise, Close that issue.
