### ISSUE TITLE
crash the game when you turn on career

### ISSUE THREAD

**Issue by Gaimeboss** [BuildCraft/BuildCraft#3436]
Hello dear developers of this beautiful fashion, but I have arisen, though not only me many problems, and it is a game crash after the engine is turned on connected to the career. Please release an update to fix this error so that I could continue to play to my map

**Comment by AEnterprise** [comment]
we will need more info to be able to help you and fix this crash: the crashlog so we know what is crashing exactly, that will also show us what BC, and MC versions as well as other mods involved.

without that we we can't fix this as we don't even know what to fix

**Comment by AEnterprise** [comment]
@Gaimeboss any update on this, if not i will have to clue this issue due to a lack of information

**Comment by AEnterprise** [comment]
closing due to the lack of any info
