### ISSUE TITLE
[1.8.9] {Modpack Issue} Buildcraft crashing when pumping items out of chest

### ISSUE THREAD

**Issue by Kaydax** [BuildCraft/BuildCraft#3441]
Crashlog: http://pastebin.com/LbEnrPxk

I removed and readded every mod, 1 by 1, and i still get this error

**Comment by AlexIIL** [comment]
One of your mods (I'm sorry but I don't know which one) is shipping an older version of the RF API.

The best way to solve this would be to remove all RF-related mods except for BC and re-adding them all, 1 by 1. (I'm assuming that you only repeatedly removed and added a mod at a time, but you probably should remove all of them and then add them back up indervidually)

**Comment by Kaydax** [comment]
I will retry that and get back to you

**Comment by Kaydax** [comment]
Done. Found out it was ExtraUtils that was causing the problem

**Comment by AlexIIL** [comment]
Hopefully updating it should fix it... unless there wasn't an updated ExtraUtils made for 1.8.9, in which case making it work might be a little trickier
