### ISSUE TITLE
Engine problem. [1.7.10]

### ISSUE THREAD

**Issue by MacTirom** [BuildCraft/BuildCraft#3442]
I have a problem on my multiplayer server with the engines.

When I place the redstone, creative, stirling, combustion engines and they turn on my internet to download with a lot of power and I can automatically as long as I am in the chunk of the machine nothing more because my Internet is not good and the full power is 260kb / s. I tested this at a friend with a download of 1.1mb / t and this consumes also 260kb / s with the Engines but has no problems since he still has three-thirds of the Internet free.

**Comment by MacTirom** [comment]
In the version: BuildCraft 7.1.18

**Comment by AEnterprise** [comment]
so what is your problem? that while the engines are running your internet no longer keeps up?

**Comment by MacTirom** [comment]
i can't play on multiplayer server's with buildcraft.

**Comment by AEnterprise** [comment]
but your friends can and it's just your internet? if that's so you could try lowering the buildcraft update frequency in the server config but other then that i doubt we can do anything about it as you'll run into the same problem with other mods

**Comment by MacTirom** [comment]
But i can't change my internet because i'm living in a village.

**Comment by AEnterprise** [comment]
as i said: there is already a config to have BC do less network updates but if that's not enough we can't fix it, same as you probably can't play some other games without alot of lag

**Comment by asiekierka** [comment]
We'd need more proof of it being specifically BuildCraft. Try Opis.

**Comment by AEnterprise** [comment]
alright did some digging and it seems that vanilla minecraft uses about 30-50kB/s modded can go up to 80-120kB/s depending on the mods and what is involved.

@MacTirom is buildcraft the only mod you are using? if not can this be reproduced with only buildcraft?

**Comment by MacTirom** [comment]
I'm using Traincraft, Buildcraft & Railcraft.

**Comment by AEnterprise** [comment]
@MacTirom can you reproduce with only buildcraft and/or profile with opis to find what exactly causes you to lose connection?
