### ISSUE TITLE
Crash when removing block where adjacent gate has an active trigger provided by that block

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3450]
Buildcraft 8.0.0 (self compiled): Commit 19c641e0a4e7a13b1bbfbe1aaa7369f7cad18af8

Crash when removing a block where the adjacent gate has an active trigger provided by that block. I did this with a BC tank

Crash Log: https://gist.github.com/LuigiHutch/7c1c99d4907dcec6ff006ece18b43c26

Thanks,
- LuigiHutch

**Comment by AlexIIL** [comment]
Should be fixed in the next commit, whenever that goes up.

**Comment by AlexIIL** [comment]
(Also I think I'll keep issues open until the fix has been pushed out so we can verify them)
