### ISSUE TITLE
Planter robot not respecting provide item filter and will take first plantable item

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3451]
BC 7.1.18 and 7.2.7

The planter robot doesn't respect provide item filter and will take first plantable item available nearest the top left slot. Images for proof:

![2016-11-16_14 57 59](https://cloud.githubusercontent.com/assets/9326429/20355545/8c8bc3e4-ac19-11e6-852a-79b2b851f38a.png)

![2016-11-16_14 58 03](https://cloud.githubusercontent.com/assets/9326429/20355553/9218aa2a-ac19-11e6-88a3-0640e49c53fe.png)

Even though the provide items filter only says provide seeds, it will provide carrots first as they are nearest the slot in the top left even though they are not in the filter. 

Thanks,
 - LuigiHutch

**Comment by AlexIIL** [comment]
The picker robot? As in the one that picks up items off the ground? (Or do you mean the planter?)

**Comment by LuigiHutch** [comment]
Yeah, I meant planter xD

**Comment by asiekierka** [comment]
@LuigiHutch Did you ever check to see if this has been fixed in 7.1.19?

**Comment by LuigiHutch** [comment]
Tested in 7.1.20 and I can confirm, Fixed!
