### ISSUE TITLE
Quarry Destroys Adventure Backpacks

### ISSUE THREAD

**Issue by Flexico** [BuildCraft/BuildCraft#3452]
The backpacks from the <a href="http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2252109-wip-adventure-backpack-mod-beta-0-8c-updated">Adventure Backpacks mod</a> can be placed on the ground as blocks, but when a quarry digs them up, they seem to just disappear. When a player wearing a backpack dies, it gets placed as a block instead of being dropped as an item. I died in my quarry, and while it sucked up most of my inventory, the backpack had vanished. I tested it on another backpack and the same thing happened.

**Comment by AEnterprise** [comment]
if the backpack is placed in the word, does it drop when you break manually or is it one of those backpack mods where you need to click it to pick it up?

this sounds like when the backpack is broken it doesn't drop as an item or is not returning the correct drops in the function that BC uses to determine them

**Comment by Flexico** [comment]
You hold left-click to break it like any block. I'm pretty sure the fastest tool for digging them is an axe, but any tool will work.

**Comment by SandGrainOne** [comment]
And what happens when it is broken? Is it placed in your inventory or dropped on the ground?

**Comment by Flexico** [comment]
It's dropped on the ground.

**Comment by AEnterprise** [comment]
closing as this won't get fixed on 1.7.10 and should not heapen in future versions (8.0.x), if this returns then feel free to make a new issue at that time
