### ISSUE TITLE
Dropbox link from version.txt has been blocked (V. 3.4.3)

### ISSUE THREAD

**Issue by tijoba7** [BuildCraft/BuildCraft#3461]
When i start the modpack it says, it cant open: https://dl.dropboxusercontent.com/u/44760587/buildcraft/version.txt

**Comment by AlexIIL** [comment]
What version of buildcraft are you using?

**Comment by tijoba7** [comment]
Version 3.4.3

**Comment by AlexIIL** [comment]
Oh right sorry I missed that.

Nothing we can do about it unfortunately, that's a very old version.

**Comment by tijoba7** [comment]
another question i am using a tekkit lite server with the MC version 1.4.7 can  I use another version of buildcraft?

**Comment by AlexIIL** [comment]
From looking at http://www.mod-buildcraft.com/releases/BuildCraft/ version 3.4.3 is the latest version available for 1.4.7 (3.5.0 was for mc 1.5.1, and I assume that newer versions for 1.4.7 weren't released after that)

**Comment by tijoba7** [comment]
okay thank you for your help.

**Comment by AEnterprise** [comment]
this is impossible to fix as the dropbox file no longer exists, the link has even been blocked by dropbox for being used to much automaticaly

the switch in version checking was made after but the old BC versions still look for that file, you can get rid of it by dissabling the version checking in the config

**Comment by tijoba7** [comment]
I also tried this yesterday but i can't find the version check....

**Comment by AEnterprise** [comment]
should be in the config, unless that version didn't have an option to turn it off yet, not sure as it's been so long
