### ISSUE TITLE
[8.0.x] BC Transport crash on the server.

### ISSUE THREAD

**Issue by mrAppleXZ** [BuildCraft/BuildCraft#3464]
Forge: 12.18.2.2151.
BC: latest 8.0.x build (commit f101e1f52480754d8f594a3100c070484a561ca3).
latest.log: http://pastebin.com/ZaJa53vZ
crash-report: http://pastebin.com/LckDwbbM

**Comment by afdw** [comment]
Check on this build: [buildcraft-8.0.0-alpha.zip](https://github.com/BuildCraft/BuildCraft/files/630133/buildcraft-8.0.0-alpha.zip)
