### ISSUE TITLE
[8.0.x] Auto workbench Duplication

### ISSUE THREAD

**Issue by kruthers** [BuildCraft/BuildCraft#3468]
When crafting in a auto workbench any recipy will only require 1 item to craft. E.g. if crafing a diamond block in the workbench once you make the ghost recipy you only need to put in 1 diamond to start the carfting process alowing you to get 8 extra diamonds for free.

This also works with complex recipies (ones that require more then 1 item). E.g. if crafting a auto workbench in a auto workbench all you would need to put in is 1 gear and 1 crafting table instead of 2 gears and 1 crafting table.

**Comment by kruthers** [comment]
The game also crashes when you shift click items out of them into you inventory

**Comment by AEnterprise** [comment]
8.0.x is not released yet officially so this might be fixed or not, please provide the commit used to build your version so we can see if this is fixed or not

**Comment by AlexIIL** [comment]
Yeah I broke autoworkbenches sometime ago and never got around to fixing them

**Comment by forReason** [comment]
The shiftclick also crashes the game when trying to put any fuel into the steamengine this probably refers to the second issue 

"The game also crashes when you shift click items out of them into you inventory"

**Comment by AlexIIL** [comment]
shiftclicking crashes every BC inventory atm.

**Comment by forReason** [comment]
Shiftclicking bug split into seperate issue:  #3479
