### ISSUE TITLE
7.2.x modules don't quite work right

### ISSUE THREAD

**Issue by AlexIIL** [BuildCraft/BuildCraft#3474]
currently core depends on builders :/

http://pastebin.com/9ztigDhy

**Comment by afdw** [comment]
I'm at the moment rewriting it, so are there any other issues?

**Comment by AlexIIL** [comment]
This doesn't affect 8.0.x

**Comment by afdw** [comment]
Oh, OK, but 8.0.x should be checked, I think there many issues like this in it.

**Comment by AEnterprise** [comment]
sorry for the spam in the issue, we where testing integration with discord
