### ISSUE TITLE
Gray GUIs in version 7.1.19

### ISSUE THREAD

**Issue by nathodood** [BuildCraft/BuildCraft#3478]
So I am trying to use combustion engines and diamond sorting pipes and whatnot, yet I get gray GUIs for some reason.
![screenshot 1](https://cloud.githubusercontent.com/assets/25068439/21871720/07cb7358-d832-11e6-9006-e48c57247693.png)

**Comment by AEnterprise** [comment]
this works fine with just BC so you must have another mods that is messing up the gui.

do you have any mods like optifine (or similar) that change the way things are rendered, if so try if the problem goes away when you remove it
