### ISSUE TITLE
[8.0 Alpha Build 2] Shift-Clicking in a BuildCraft Block crashes game

### ISSUE THREAD

**Issue by NinjaKap** [BuildCraft/BuildCraft#3479]
Hello!
I found the new Alpha Build 2 for BC 8.0.0, and decided to give it a shot.

The Engine Texture is glitched and names messed up, but still functional. I placed one down, and shift-clicked coal blocks in; it crashed my game.

I did the same in a combustion engine (to move around inv), and crashed game.

I tried again in the Quarry Block, and it, again, crashed.

Not sure if you're "looking for" bugs yet, just thought I'd put this here (in-case you didn't know!)

Thanks for all you've done, and can't wait to mess around with the final release!

**Comment by afdw** [comment]
> I tried again in the Quarry Block, and it, again, crashed.
When? What you was doing?

**Comment by NinjaKap** [comment]
I opened the Quarry (as it now as a GUI in 8.0), and wondered if the new items are a filter. I couldn't put anything in, and tried shift-clicking, when it crashed.

**Comment by afdw** [comment]
You should put frames in it

**Comment by NinjaKap** [comment]
Ah, okay.

**Comment by forReason** [comment]
as seen in the reference above, the issue not only affects engines but every shift-click interaction. #3468 were two issues so i referenced the shift click here to get a clean, separate issue

**Comment by AlexIIL** [comment]
Should be fixed by the commits mentioned above.
