### ISSUE TITLE
Is there a way to get buildcraft 8.0?

### ISSUE THREAD

**Issue by Joshwoo70** [BuildCraft/BuildCraft#3480]
Jus curious. i am able to deal with crashes and breaking stuff. just don't know where to get it...

**Comment by afdw** [comment]
See https://github.com/BuildCraft/BuildCraft/issues/3472 for example. But there are Jenkins builds [here](https://jenkins.ra-doersch.de/job/BuildCraft/job/BuildCraft/job/8.0.x/2/) and if you want you can build it yourself.

**Comment by Joshwoo70** [comment]
thanks!
