### ISSUE TITLE
Robots go into "Dead status" 1.7.10 Build# 7.1.19

### ISSUE THREAD

**Issue by Ryudragon2** [BuildCraft/BuildCraft#3481]
every time my robots are running alot of them go into dead status and some of them disapper and go up to the roof of my house i do have admin world anchors to keep the chunks loaded

![2017-01-18_12 42 00](https://cloud.githubusercontent.com/assets/10014757/22078058/6060c348-dd7c-11e6-9fbc-1f99693c22f0.png)

![2017-01-18_12 49 01](https://cloud.githubusercontent.com/assets/10014757/22078095/819e3518-dd7c-11e6-8c7a-4e2e49a7a5df.png)

**Comment by AEnterprise** [comment]
is there a recharging station available at all timees for all the robots to go back to and recharge? it looks like they ran out of power

also you have way to many chunkloaders up there then needed, i think those have a  range of 3x3 chunks centered arround the chunkloader

**Comment by dj3520** [comment]
Railcraft 9.7.0.0
>Increase the area that Anchor Carts keep chunkloaded from 3x3 chunks to 5x5 chunks in order to help reduce chunkloading derived issues for moving Trains.

Not sure if this only applies to carts or not. Putting on trackman's goggles with the anchor setting spawns purple particles showing you the range of the anchor.

Also there might be messages about the robots in the server log and why they've shut down.

**Comment by AEnterprise** [comment]
eighter an issue with that setup or the AI (not sure without more testing) but since robots need to be ported and will be looked at then this will probably be fixed then
