### ISSUE TITLE
Facade and glass pane connection request

### ISSUE THREAD

**Issue by Mysterizon** [BuildCraft/BuildCraft#3482]
Hey, 

I would like to request a feature if it's possible that the feature could be added to the buildcraft version for 1.7.10. Any block can connect the glass pane, but facades do not connect with glass pane. I am sure you know what feature I am asking for. Thank you for taking your time to read this request.

**Comment by AEnterprise** [comment]
having glass panes connect to facades would indeed be usefull for hiding your pipes but i'm afraid 1.7.10 is critical bugfixes only so might be for future versions

**Comment by LuigiHutch** [comment]
Sounds like a reasonable idea to me, This may be of use for when Facades are reimplimented into 8.0.x:
https://github.com/MinecraftForge/MinecraftForge/pull/3437

**Comment by asiekierka** [comment]
Not possible to implement in 1.7.10.
