### ISSUE TITLE
[BuildCraft 8.0] compilation error

### ISSUE THREAD

**Issue by valentin616** [BuildCraft/BuildCraft#3484]
I want to try BuildCraft 8. So I wanted to compile it. But an error occurs.

buildcraft/transport/pipe/behaviour/PipeBehaviourSeparate.java:21: error: cannot find symbol
return other.getClass() == getClass();

symbol:   method getClass()
location: class PipeBehaviourSeparate
:compileJava FAILED

I'm on Linux/Debian,I use java8 and compile with Gradle.

**Comment by AlexIIL** [comment]
That sounds like you haven't cloned the API submodule
