### ISSUE TITLE
Auto Workbench blocked

### ISSUE THREAD

**Issue by ExDomino** [BuildCraft/BuildCraft#3485]
Hello, when the Auto Workbench has a recipe that requires two or more items, the Auto Workbench can be blocked because filled with only one item that the recipe needs. Example: to craft a Coal Ball (IndustrialCraft), you need 8 Coal Dust and 1 Flint. The Auto Workbench's buffer can be filled with Coal Dust, preventing the Flint to be used in the recipe, and the whole system is blocked!

**Comment by AEnterprise** [comment]
you can use gates to detect when that's gona heapen and shut off the coal dust input to work arround that

gona leave this up to @AlexIIL if this is a design flaw that needs fixing or not

**Comment by AEnterprise** [comment]
gona close this as working as intended, buildcraft is a mod about automating everything and overcomming the chalanges, this can be perfectly automated with just BC and some gates to detect what it needs
