### ISSUE TITLE
ZonePlanner crashes when Full Screen activated

### ISSUE THREAD

**Issue by LachimHeigrim** [BuildCraft/BuildCraft#3488]
I'm using BuildCraft on MineYourMind Regrowth server. Client contains the following BC versions: buildcraft-7.1.19.jar, buildcraft-compat-7.1.5.jar.

Reproduce steps:
1. Place Zone Planner in the world
2. Load zone from Map Location item
3. Activate full screen using FS button.

Client crashes with the attached logs:
[2017-01-27-2.log.gz](https://github.com/BuildCraft/BuildCraft/files/735695/2017-01-27-2.log.gz)

[crash-2017-01-27_16.57.24-client.txt](https://github.com/BuildCraft/BuildCraft/files/735693/crash-2017-01-27_16.57.24-client.txt)

**Comment by AEnterprise** [comment]
does the same crash heapen when you do the same when you are already in fullscreen before opening the zone planner?

**Comment by LachimHeigrim** [comment]
Actually it does.

I tested exactly these steps:
( 0. Break Zone Planner block with pickaxe)
1. Place Zone Planner in world
2. Activate ZP's UI with right-click
3. Go to fullscreen using 'FS' button
4. About 3-5 seconds later the client crashes

Similar stack trace as before: 
[crash-2017-01-29_10.18.06-client.txt](https://github.com/BuildCraft/BuildCraft/files/737397/crash-2017-01-29_10.18.06-client.txt)

**Comment by AEnterprise** [comment]
that's not what i ment: does it crash when you switch steps 2 and 3? if you go to fullscreen before you open the zoneplanner GUI?

**Comment by LachimHeigrim** [comment]
Sorry I don't understand what you mean. In order to display the 'map' in full screen I first need to open the Zone Planner UI which contains the 'FS' button for step 3. Is there any way to do it in reverse order?

Just to avoid confusion by 'go to full screen' I mean 'enlarge the Zone Planner's map to full screen' functionality provided by Zone Planner. Not enlarging (or changing the size of) my Minecraft client screen in any way.

**Comment by AEnterprise** [comment]
ah then i misunderstood, i thought you ment MC fullscreen, in that case this is definatly a bug

**Comment by AlexIIL** [comment]
Does this happen in single-player?
