### ISSUE TITLE
BuildCraft pipes losing items and liquid

### ISSUE THREAD

**Issue by LachimHeigrim** [BuildCraft/BuildCraft#3489]
I'm using BuildCraft pipes on MineYourMind Regrowth server. Client contains the following BC versions: buildcraft-7.1.19.jar, buildcraft-compat-7.1.5.jar.

It seems both item pipes (cobblestone, golden, wooden) as well as liquid pipes (cobblestone, golden, emerald) lose items when player moves a lot between chunks. Would guess a persistence problem on chunk unloading. 

Screenshot: short pipe that occasionally 'loses' an ingot worth of metal:
![2017-01-27_17 25 14](https://cloud.githubusercontent.com/assets/9980755/22378564/59df5c96-e4b6-11e6-930f-7471d87ab3f0.png)

It's hard to describe exact problem mechanics. My base is spread over larger area so I'm moving frequently between chunks and either find and ingot worth of molten metal was 'lost' when pumping from TC smeltery to TC basin, or one or more buckets got lost in Botania manafarm. Since the issue happens more frequently with slower (cobble) pipes and longer pipe section, I'd suspect the persistence on chunk unload is the problem.

**Comment by asiekierka** [comment]
Is the server in question using Cauldron/KCauldron/Thermos/[insert Forge+Bukkit amalgation here]?

**Comment by AEnterprise** [comment]
can you provide game logs of when this heapened? there might be an indication in there

**Comment by LachimHeigrim** [comment]
@asiekierka Any way I can find that information for you from logs or client info? Not familiar with how to check server type reliably.

@AEnterprise it happens during game session. I tend to notice it 2-3 times in 3 RL hours, but it may be more frequent. Glanced through logs but not seeing anything suspicious. Still attaching logs from several days as requested.

[2017-01-23-1.log.gz](https://github.com/BuildCraft/BuildCraft/files/736669/2017-01-23-1.log.gz)
[2017-01-23-2.log.gz](https://github.com/BuildCraft/BuildCraft/files/736670/2017-01-23-2.log.gz)
[2017-01-24-1.log.gz](https://github.com/BuildCraft/BuildCraft/files/736671/2017-01-24-1.log.gz)
[2017-01-24-2.log.gz](https://github.com/BuildCraft/BuildCraft/files/736672/2017-01-24-2.log.gz)
[2017-01-25-1.log.gz](https://github.com/BuildCraft/BuildCraft/files/736673/2017-01-25-1.log.gz)
[2017-01-25-2.log.gz](https://github.com/BuildCraft/BuildCraft/files/736674/2017-01-25-2.log.gz)

Also after reporting I started to look at chunk boundaries a bit more and noticed I placed the pipe through chunk boundary. Could be useful for reproduction. Earlier screenshot with chunk borders on:
![2017-01-28_03 54 42](https://cloud.githubusercontent.com/assets/9980755/22393876/fdb171ce-e510-11e6-8442-1cc936af7388.png)

**Comment by dj3520** [comment]
@LachimHeigrim Those all seem to be client-side logs (except one of them,) which won't help unless you can reproduce the issue in a single player world (which would also rule out any forge+bukkit combo) If you aren't the one running the server then you might need to get on contact with the person that does in order to get logs. If you can it might be easiest to bring that person here.

**Comment by LachimHeigrim** [comment]
Let me ping the MineYourMind staff via ticket, they are usually very helpful and responsive. Let's see if we can get any info from them.

**Comment by LachimHeigrim** [comment]
No answer from staff yet. Still I started collecting timestamps of when I notice items missing so that we can potentially try to get matching server logs.

@asiekierka I noticed in (unrelated) crash-log, the following info for the MyM Regrowth server type:
`Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:3f991ad:unknown) <- kcauldron,cauldron,craftbukkit,mcpc,fml,forge`

See this issue's crash log: https://github.com/BuildCraft/BuildCraft/issues/3488

**Comment by asiekierka** [comment]
This kind of issue sounds very similar to the kinds of issues we've attributed to Cauldron/KCauldron/Thermos before, and, as such, I am not willing to look into it further unless proof is provided that this behaviour happens without them as well.
