### ISSUE TITLE
[8.0.x] Phantom GUI slots don't behave correctly outside of a dev environment

### ISSUE THREAD

**Issue by AlexIIL** [BuildCraft/BuildCraft#3493]
Might be a method with a broken method name vs obfuscated name.

https://www.youtube.com/watch?v=QmmUpDDX4f8

**Comment by AEnterprise** [comment]
what forge version you using? i know there where some issues and fixes of this in the past with forge

if you have a recent version i putting the method names on the forge forums, someone will recognize it if it's a clash

**Comment by LuigiHutch** [comment]
I was using Forge 13.20.0.2226 when I discovered this.

**Comment by AlexIIL** [comment]
From some more testing it looks like this was caused by comparing itemstacks to null in https://github.com/BuildCraft/BuildCraft/blob/afe5114b83124c601714f40345023e59805d7b5e/common/buildcraft/lib/gui/ContainerBC_Neptune.java#L90. I have no idea how it worked in a dev before, so we might come across another related problem later.

**Comment by AlexIIL** [comment]
(Fixed)
