### ISSUE TITLE
Robots by another name

### ISSUE THREAD

**Issue by TehStoneMan** [BuildCraft/BuildCraft#3494]
OK, it's just kind of a random thought I had today, but it seems to me that Buildcraft robots operate very much like modern day drones.
I know that the robots have been around a lot longer, but I was wondering if there was any thoughts about renaming them?

**Comment by AEnterprise** [comment]
they are named robots yes but i don't think renaming them to drones realy makes a difference, if anything it would cause more confusion with players as thye suddenly have a completely different name

also they don't realy look like drones

**Comment by dj3520** [comment]
the opencomputers drones look more like drones than the buildcraft robots

**Comment by AlexIIL** [comment]
This discussion really belongs on the forums, not this issue page.

(I don't really want to change the name of something unless it massively changes from its previous state)

**Comment by afdw** [comment]
> This discussion really belongs on the forums, not this issue page.
Can you please give link to it?

**Comment by AlexIIL** [comment]
The bc forums are here http://mod-buildcraft.com/forums/index.php

**Comment by afdw** [comment]
I mean to topic, I can't find it.

**Comment by AlexIIL** [comment]
Oh, no-one has opened a topic for I think yet.

(I meant that the bc forums would be a better place to continue the discussion if anyone has anything to add to it, not that a simalir topic already existed)
