### ISSUE TITLE
Crash 7.1.20 stable (rendering issue)

### ISSUE THREAD

**Issue by zakhad** [BuildCraft/BuildCraft#3496]
When I'm using auto crafting table IV and mouse over (FloodGate/Pump) item the game crashes, every other item I had on my list is fine within the auto crafting table selection that I had (Over 500 items).

There is no issue manually crafting them and spawning them via NEI, they work as intended. It's very annoying to just have your game crash because of this these items. I'm not trying to come across negative i'm just reporting a bug hoping for a fix, I appreciate all that you do :)

http://pastebin.com/n7j5tpSE

![crashh](https://cloud.githubusercontent.com/assets/5264667/22867939/eaff967c-f187-11e6-9bbc-07b736547ae3.jpg)

https://github.com/Elecs-Mods/CraftingTable-IV

**Comment by AEnterprise** [comment]
looks like it is getting parsed the oredict wildcard metadata and not liking that, BC should probably handle and protect that but it's also a metadata that normaly should be translated to 0

**Comment by asiekierka** [comment]
@zakhad While we can and are going to fix this, please report to the ACTIV devs as it is also a bug on their side - see the @AEnterprise comment above.
