### ISSUE TITLE
1.11.2 BuildCraft 8.x  Whole suite of issues

### ISSUE THREAD

**Issue by SuperCoder7979** [BuildCraft/BuildCraft#3499]
![2017-02-19_12 24 21](https://cloud.githubusercontent.com/assets/25208576/23104620/59e851e8-f69f-11e6-964c-a01428600041.png)
This is a huge list of bugs and issues that I found when I was (and still am) playtesting BuildCraft 1.11.2. I hope you try to fix these bugs, but no pressure. :)

- [x] The engines don't auto orient.

- [x] Whenever  you rightclick a tank with a bucket, it places the contents of the buckets down and puts it in the tank, effectively duplicating liquid.

- [x] The pump sucks out liquid WAY too fast. I managed to empty an oil deposit in ~30 seconds.

- [x] Stirling Engines Output 333.333 million MJ per tick. This maybe causing the bug above.

- [x] Oil spawns too frequently. I have attached a screenshot to give you an example.

- [x] Kenesis Pipes don't show their blue animation inside them.

Expect this list to grow as I test more blocks and Items from BuildCraft!

**Comment by LuigiHutch** [comment]
1) Engines aren't finished
2) Already known
3) Pump works incorrectly but is fixed in a pr from @afdw which should come soon
4) Engines aren't finished
5) Already known
6) Kinesis pipes aren't finished and don't work at all

Most things don't work at all so I would recommend waiting till closer to release before reporting minor bugs such as these.

**Comment by AEnterprise** [comment]
tagging as 'bug' because they are bugs but as @LuigiHutch pointed out, BC 8 is far, far from complete so this isn't high priority (yet)

thanks though for being willing to test

**Comment by AlexIIL** [comment]
5 fixed in https://github.com/BuildCraft/BuildCraft/commit/daa1e1211617012bb06d52c94f1d0dff6e2987e6

**Comment by SuperCoder7979** [comment]
Great, so now the world has more water than oil.

**Comment by SuperCoder7979** [comment]
Also you might want to do something about oil's viscosity being much lower in 1.11.2 than in 1.7.10

**Comment by SuperCoder7979** [comment]
I have just compiled the latest Github repository, and I found some changes with the way that oil spawns. Oil now spawns less frequently in oceans (yay!), but desert oil pools has the same low spawn rate as the normal oil well. I am an amateur programmer so I may be catastrophically wrong with this, but you may be able to get around spawn rates by making a separate spawn frequency for all three types of oil well. (Take this with a grain of salt.)

**Comment by AlexIIL** [comment]
@SuperCoder7979 there was a config option to change the biomes where oil probabilities would be, its just not hooked up yet

**Comment by Enter03** [comment]
Hello! There isn't any "information" "Q&A" thread/issue so I will post my question here;

What about 1.10(.2) version? Will there be any Buildcraft for this version? I very need it (I think that other players still play on 1.10 and not all mods has been updated to 1.11), I'm running small server for my friends and we can't play without Buildcraft it's very funny/good-to-play mod.

Thanks for info, and for creating this awesome mod.

**Comment by asiekierka** [comment]
@Enter03 No plans for an official 1.10 BuildCraft release exist.

I have explained my reasoning in the comments [here](https://minecraft.curseforge.com/projects/buildcraft).

**Comment by Enter03** [comment]
@asiekierka 

Oh... thanks for info :'(

**Comment by MissPotato** [comment]
As Asie's post isn't a direct hyperlink, I've screenshot'd the post Asie is in reference to. http://i.imgur.com/DlF4cyV.png

**Comment by AlexIIL** [comment]
1 fixed in (TODO: Insert commit from ages ago here)

**Comment by afdw** [comment]
2 should be fixed in my branch

**Comment by mgdgfbhevdyeh** [comment]
Hey guys I want know How about 1.10.2?Why BCTEAM want to update to 1.11.2 don't 1.10.2???

**Comment by asiekierka** [comment]
@mgdgfbhevdyeh Please read [this](https://minecraft.curseforge.com/projects/buildcraft?comment=167) for a good explanation.

**Comment by AlexIIL** [comment]
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)
