### ISSUE TITLE
engines not working {1.7.10}

### ISSUE THREAD

**Issue by redstonermoves** [BuildCraft/BuildCraft#3501]
none of the engines are working i'm using this with railcraft {removed adfly link to blocked insecure/infected site} {1.7.10} #3501

**Comment by asiekierka** [comment]
What version of BuildCraft?

**Comment by AEnterprise** [comment]
alright as asie pointed out: we're gona need some version numbers and more details on what exactly is not working

your original comment had an addfly link in there (those NOT for bugreporting) and when i had a antivirus scanner tool check the link alarms started ringing so i don't know what your intention was with that link but i sugest you don't try that again. This is a bugtracker for fixing bugs, not a place for you to drop random addfly links in an attempt to earn money and definatly not the place to try infect other computers so i removed the link

also why did you edit your post and just put in a link to this report itself?

**Comment by asiekierka** [comment]
@AEnterprise How do you know it's his link, though? He might've copied it from a website. I mean, even [CovertJaguar's own website](www.railcraft.info/releases/9-12-2-0) still provides adf.ly URLs as the primary mirror.

Don't assume malice.

**Comment by redstonermoves** [comment]
... umm i don't know why your virus thingy went off but it is not fake

**Comment by AEnterprise** [comment]
@asiekierka i checked the destination of the adfly link after the add and that isn't a site that is infected (anti virus warnings), and the link is in his bug report so he has to have put it there and i seriously doubt he just copied the first random link he found somewhere and that turns out to be infected

**Comment by redstonermoves** [comment]
7.1.20 1.7.10 is the version

**Comment by redstonermoves** [comment]
and also i like how quickly you guys replied

**Comment by AEnterprise** [comment]
@redstonermoves you sure? what was suposed to be behind the link then? also please just link directly to things you want to link especially in things like bug reports

could you also provide info like screenshots of the setup that isn't working?

**Comment by redstonermoves** [comment]
getting link

**Comment by redstonermoves** [comment]
https://www.dropbox.com/s/8lds3e7qignscug/2017-03-05_15.49.03.png?dl=0

**Comment by redstonermoves** [comment]
4 screen shot

**Comment by redstonermoves** [comment]
and look i'm sorry if i was the thing that i messed up

**Comment by asiekierka** [comment]
@AEnterprise Yes, certain adf.ly ads *do* contain malicious code - that is a huge part of the reason why people dislike the service.

**Comment by asiekierka** [comment]
As for the screenshot, you need a *Wooden Kinesis Pipe* to extract power from an engine. Not just any old one.

Not to mention that those are Fluid Pipes, not Kinesis Pipes.

**Comment by redstonermoves** [comment]
ok xD 1 hour later

**Comment by redstonermoves** [comment]
ok, I'm sorry I'm kinda new to buildcraft. I have never completely understood it
