### ISSUE TITLE
BC 7.1.20 AutoWorkbench Dupe (NBT checking)

### ISSUE THREAD

**Issue by TheAndrey** [BuildCraft/BuildCraft#3503]
AutoWorkbench does not compare NBT items.
https://www.youtube.com/watch?v=rfqad_-kMmY&t=2m26s

I fixed it activating the check here: https://github.com/BuildCraft/BuildCraft/blob/7.1.x/common/buildcraft/factory/TileAutoWorkbench.java#L340

Why don't you use **ItemStack.areItemStackTagsEqual()** in here?
https://github.com/BuildCraft/BuildCraft/blob/7.1.x/common/buildcraft/core/lib/inventory/StackHelper.java#L205-L207
If the first item is missing NBT, it will return true, which is not good.

**Comment by AEnterprise** [comment]
is this the case for 8.0.x as well @AlexIIL ?

**Comment by asiekierka** [comment]
Ouch! Thanks, @TheAndrey !

**Comment by asiekierka** [comment]
@AlexIIL 8.0.x *should* use areItemStackTagsEqual as that also checks capabilities!

**Comment by usernameak** [comment]
Still works on 7.1.23
