### ISSUE TITLE
Crash with NEI and BCC when looking up clock timer gate

### ISSUE THREAD

**Issue by dj3520** [BuildCraft/BuildCraft#3504]
Crash client-side only when looking up recipe for basic gate with clock timer.
Buildcraft 7.1.20
BCC 7.1.6
NEI 1.0.5.120

[Server-side mod list](http://net.dj3520.net:8000/minecraft/modlist.btm)

[crash-2017-03-08_18.05.05-client.txt](https://github.com/BuildCraft/BuildCraft/files/829221/crash-2017-03-08_18.05.05-client.txt)

**Comment by asiekierka** [comment]
This is a BuildCraftCompat issue.

**Comment by dj3520** [comment]
My bad, forgot that's a separate repo.
