### ISSUE TITLE
Builder Crash 7.1.20

### ISSUE THREAD

**Issue by derwolfYT** [BuildCraft/BuildCraft#3505]
Here is a crash report:
---- Minecraft Crash Report ----
// Oh no

Time: 11/03/17 06:59 PM
Description: Post-rendering entity in world

java.lang.IllegalStateException: Already tesselating!
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
	at net.minecraft.client.renderer.entity.Render.func_76975_c(SourceFile:143)
	at net.minecraft.client.renderer.entity.Render.func_76979_b(SourceFile:304)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:302)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:716)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1596)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1334)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
	at net.minecraft.client.renderer.entity.Render.func_76975_c(SourceFile:143)
	at net.minecraft.client.renderer.entity.Render.func_76979_b(SourceFile:304)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:302)

-- Entity being rendered --
Details:
	Entity Type: Chicken (net.minecraft.entity.passive.EntityChicken)
	Entity ID: 369757
	Entity Name: Chicken
	Entity's Exact location: 243.38, 68.00, 388.47
	Entity's Block location: World: (243,68,388), Chunk: (at 3,4,4 in 15,24; contains blocks 240,0,384 to 255,255,399), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderChicken@15b0e92
	Location: 8.60,-4.37,6.01 - World: (8,-5,6), Chunk: (at 8,-1,6 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: -81.5625
	Delta: 0.71779263
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:716)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1596)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1334)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['der_wolf_YT'/369863, l='MpServer', x=234.77, y=72.37, z=382.46]]
	Chunk stats: MultiplayerChunkCache: 81, 90
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (220,64,252), Chunk: (at 12,4,12 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8560 game time, 8560 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 43 total; [EntityChicken['Chicken'/437006, l='MpServer', x=285.47, y=63.00, z=364.63], EntityChicken['Chicken'/437007, l='MpServer', x=284.56, y=67.00, z=393.53], EntityXPOrb['Experience Orb'/427788, l='MpServer', x=216.44, y=62.25, z=334.34], EntityChicken['Chicken'/437004, l='MpServer', x=283.81, y=75.00, z=391.59], EntityChicken['Chicken'/437005, l='MpServer', x=282.47, y=75.00, z=390.91], EntityBat['Bat'/438034, l='MpServer', x=176.63, y=14.00, z=428.50], EntityBat['Bat'/438035, l='MpServer', x=173.16, y=15.00, z=424.59], EntityBat['Bat'/438032, l='MpServer', x=175.25, y=14.23, z=427.44], EntityBat['Bat'/438033, l='MpServer', x=177.63, y=14.00, z=429.34], EntityItem['item.item.cornseeds'/438545, l='MpServer', x=234.75, y=68.13, z=386.53], EntityClientPlayerMP['der_wolf_YT'/369863, l='MpServer', x=234.77, y=72.37, z=382.46], EntityBat['Bat'/437794, l='MpServer', x=195.25, y=28.10, z=403.75], EntityXPOrb['Experience Orb'/430382, l='MpServer', x=215.09, y=62.25, z=338.06], EntityXPOrb['Experience Orb'/430380, l='MpServer', x=216.75, y=62.25, z=337.66], EntityXPOrb['Experience Orb'/430381, l='MpServer', x=216.50, y=62.25, z=336.00], EntityXPOrb['Experience Orb'/428586, l='MpServer', x=214.75, y=62.25, z=330.44], EntityXPOrb['Experience Orb'/430379, l='MpServer', x=215.44, y=62.25, z=337.75], EntityItem['item.item.cornseeds'/437571, l='MpServer', x=289.41, y=63.13, z=357.75], EntitySpider['Spider'/437332, l='MpServer', x=21.84, y=-38.62, z=29.34], EntityChicken['Chicken'/369757, l='MpServer', x=243.38, y=68.00, z=388.47], EntityItem['item.item.tomatoseeds'/412764, l='MpServer', x=208.13, y=68.13, z=330.75], EntityChicken['Chicken'/369783, l='MpServer', x=291.50, y=69.00, z=307.50], EntityChicken['Chicken'/369788, l='MpServer', x=280.50, y=68.00, z=315.50], EntityChicken['Chicken'/369785, l='MpServer', x=280.50, y=68.00, z=312.50], EntityChicken['Chicken'/369784, l='MpServer', x=290.50, y=68.00, z=309.50], EntityChicken['Chicken'/369787, l='MpServer', x=280.50, y=68.00, z=312.50], EntityChicken['Chicken'/369786, l='MpServer', x=280.50, y=68.00, z=313.50], EntityChicken['Chicken'/369796, l='MpServer', x=307.50, y=70.81, z=383.50], EntitySquid['Squid'/437653, l='MpServer', x=180.66, y=47.00, z=446.84], EntityPig['Pig'/436902, l='MpServer', x=232.94, y=67.00, z=408.03], EntityPig['Pig'/436900, l='MpServer', x=251.72, y=68.00, z=396.22], EntityPig['Pig'/436901, l='MpServer', x=267.19, y=66.00, z=405.09], EntityPig['Pig'/436899, l='MpServer', x=235.97, y=67.00, z=404.53], EntityChicken['Chicken'/436910, l='MpServer', x=235.41, y=69.00, z=371.44], EntityChicken['Chicken'/436911, l='MpServer', x=238.47, y=68.00, z=385.53], EntityBat['Bat'/437930, l='MpServer', x=176.25, y=14.00, z=422.49], EntityBat['Bat'/437938, l='MpServer', x=186.56, y=35.00, z=333.25], EntityBat['Bat'/437939, l='MpServer', x=202.59, y=28.79, z=403.59], EntityChicken['Chicken'/436912, l='MpServer', x=225.16, y=66.38, z=391.53], EntityBat['Bat'/437936, l='MpServer', x=195.77, y=24.15, z=401.98], EntityXPOrb['Experience Orb'/426940, l='MpServer', x=218.34, y=62.25, z=338.72], EntityXPOrb['Experience Orb'/426941, l='MpServer', x=216.28, y=62.25, z=337.97], EntityXPOrb['Experience Orb'/428518, l='MpServer', x=215.56, y=62.25, z=333.41]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 247909624 bytes (236 MB) / 873033728 bytes (832 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_D1 92 mods loaded, 81 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAAAAAAA	da3dsoulASMFix{0.1.0} [DA3DSOUL ASM Fixes] (minecraft.jar) 
	UCHIJAAAAAAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	Covers1624Core{1.7.10-1.0} [Covers1624 Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAAAAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAAAAAAA	BinniePatcher{1.8.2} [Binnie Patcher] (minecraft.jar) 
	UCHIJAAAAAAAAA	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJAAAAAAAAA	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Core{7.1.20} [BuildCraft] (buildcraft-7.1.20.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Factory{7.1.20} [BC Factory] (buildcraft-7.1.20.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Transport{7.1.20} [BC Transport] (buildcraft-7.1.20.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Energy{7.1.20} [BC Energy] (buildcraft-7.1.20.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Silicon{7.1.20} [BC Silicon] (buildcraft-7.1.20.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Builders{7.1.20} [BC Builders] (buildcraft-7.1.20.jar) 
	UCHIJAAAAAAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAAAAAAA	ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.5-115.jar) 
	UCHIJAAAAAAAAA	ThermalExpansion{1.7.10R4.1.4} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.4-247.jar) 
	UCHIJAAAAAAAAA	Additional-Buildcraft-Objects{MC1.7.10-BC7.1release4.0.9} [Additional Buildcraft Objects] (ABO-MC1.7.10-BC7.1release4.0.9.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Robotics{7.1.20} [BC Robotics] (buildcraft-7.1.20.jar) 
	UCHIJAAAAAAAAA	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCHIJAAAAAAAAA	Forestry{4.2.2.50} [Forestry for Minecraft] (forestry_1.7.10-4.2.2.50.jar) 
	UCHIJAAAAAAAAA	LogisticsPipes{0.9.3.128} [Logistics Pipes] (logisticspipes-0.9.3.128.jar) 
	UCHIJAAAAAAAAA	additionalpipes{4.7.0} [Additional Pipes] (additionalpipes-4.7.5.jar) 
	UCHIJAAAAAAAAA	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
	UCHIJAAAAAAAAA	AdvancedMachines{59.0.2} [Advanced Machines] (advanced-machines-59.0.2.jar) 
	UCHIJAAAAAAAAA	BinnieCore{2.0-pre14} [Binnie Core] (binnie-mods-2.0-pre14.jar) 
	UCHIJAAAAAAAAA	Botany{2.0-pre14} [Botany] (binnie-mods-2.0-pre14.jar) 
	UCHIJAAAAAAAAA	ExtraBees{2.0-pre14} [Extra Bees] (binnie-mods-2.0-pre14.jar) 
	UCHIJAAAAAAAAA	ExtraTrees{2.0-pre14} [Extra Trees] (binnie-mods-2.0-pre14.jar) 
	UCHIJAAAAAAAAA	Genetics{2.0-pre14} [Genetics] (binnie-mods-2.0-pre14.jar) 
	UCHIJAAAAAAAAA	BuildCraft|Compat{7.1.6} [BuildCraft Compat] (buildcraft-compat-7.1.6.jar) 
	UCHIJAAAAAAAAA	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) 
	UCHIJAAAAAAAAA	bcadditions{2.2.5} [BuildCraft Additions] (BuildcraftAdditions-1.7.10-2.2.5.jar) 
	UCHIJAAAAAAAAA	DimensionalCore{1.0.7} [DimensionalCore] (DimensionalCore-1.7.10-1.0.7.jar) 
	UCHIJAAAAAAAAA	dyndyn{0.2.1} [Dynamic Dynamos] (DynamicDynamos-0.2.1.jar) 
	UCHIJAAAAAAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAAAAAAA	EnderIO{1.7.10-2.3.0.427_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.427_beta.jar) 
	UCHIJAAAAAAAAA	enderioaddons{0.10.11} [Ender IO Addons] (EnderIOAddons-1.7.10-2.3.0.427_beta-0.10.11.54_beta.jar) 
	UCHIJAAAAAAAAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCHIJAAAAAAAAA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
	UCHIJAAAAAAAAA	eng_toolbox{1.2.3.0} [Engineer's Toolbox] (EngineersToolbox-1.2.3.0-BETA.jar) 
	UCHIJAAAAAAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAAAAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAAAAAAA	FortuneOres{2.0.5} [FortuneOres] (FortuneOres-MC1.7.10-2.0.5.jar) 
	UCHIJAAAAAAAAA	HEXeco{1.0.0} [HEXeco] (HEXeco 2.0.0-Pre-03.jar) 
	UCHIJAAAAAAAAA	legacyfarms{1.1} [Legacy Farms] (legacyfarms-1.0-32.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAAAAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAAAAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJAAAAAAAAA	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) 
	UCHIJAAAAAAAAA	Mo' Shiz{1.62.2} [Mo' Shiz] (Mo' Shiz v1.62.2.jar) 
	UCHIJAAAAAAAAA	modtweaker2{0.9.6} [Mod Tweaker 2] (ModTweaker2-0.9.6.jar) 
	UCHIJAAAAAAAAA	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAAAAAAA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAAAAAAA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAAAAAAA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAAAAAAA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAAAAAAA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAAAAAAA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAAAAAAA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJAAAAAAAAA	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	UCHIJAAAAAAAAA	pipeaddition{1.0.0} [Pipe Addition] (PipeAdditions 1.0.0.jar) 
	UCHIJAAAAAAAAA	RedstoneArsenal{1.7.10R1.1.2} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.2-92.jar) 
	UCHIJAAAAAAAAA	RArm{1.7.10-1.2.0-41} [Redstone Armory] (RedstoneArmory-1.7.10-1.2.0-41.jar) 
	UCHIJAAAAAAAAA	ResonantToolbox{1.0.9} [Resonant Toolbox] (ResonantToolbox-1.7.10-1.0.9.jar) 
	UCHIJAAAAAAAAA	simplyjetpacks{1.5.3} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.3.jar) 
	UCHIJAAAAAAAAA	rfdrills{1.7.3} [RFDrills] (RFDrills-1.7.10-1.7.3.jar) 
	UCHIJAAAAAAAAA	ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.0-171.jar) 
	UCHIJAAAAAAAAA	WolfCore{1.0.0} [WolfCore] (Wolfcore.jar) 
	UCHIJAAAAAAAAA	XaeroBetterPvP{1.12} [Better PVP Mod] (BetterPvP_1.12_Forge_1.7.10.jar) 
	UCHIJAAAAAAAAA	FMPIntegration{1.0} [FMPIntegration] (fmpintegration-1.2.2-1.7.10.jar) 
	UCHIJAAAAAAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UD	XRay{v9.0} [XRay] (minecraft.jar) 
	UD	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.2.9606 Compatibility Profile Context' Renderer: 'ATI Radeon HD 4250 Graphics '
	CoFHCore: -[1.7.10]3.1.3-327
	ThermalFoundation: -[1.7.10]1.2.5-115
	ThermalExpansion: -[1.7.10]4.1.4-247
	MineFactoryReloaded: -[1.7.10]2.8.1-174
	NetherOres: -[1.7.10]2.3.1-22
	RedstoneArsenal: -[1.7.10]1.1.2-92
	ThermalDynamics: -[1.7.10]1.2.0-171
	EnderIO: Found the following problem(s) with your installation:
                  * Optifine is installed. This is NOT supported.
                  * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from buildcraft-7.1.20.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: ATI Radeon HD 4250 Graphics  GL version 3.2.9606 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [TFR Songs.zip, Robot fix.zip, LogPipesTPack(1.0r).zip, Lol.zip, Der Engines.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D1
	Render Distance Chunks: 4
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 3.2.9606 Compatibility Profile Context
	OpenGlRenderer: ATI Radeon HD 4250 Graphics 
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 3

**Comment by asiekierka** [comment]
Disable anything involving multicore rendering/chunk loading in OptiFine.
