### ISSUE TITLE
Robots In BC7.x.x have BC6.x.x robot Textures

### ISSUE THREAD

**Issue by derwolfYT** [BuildCraft/BuildCraft#3506]
Really, the robots seem to have the same textures of BC6.x.x
I made a resource pack to fix that thing 
https://minecraft.curseforge.com/projects/buildcraft-robot-fix
(Copy and paste Bcuz GitHub search on its internal engine)
Please check that

**Comment by AlexIIL** [comment]
I don't plan on changing the robot textures for BC8, and BC7 defiantly won't be changing at this late stage.
