### ISSUE TITLE
Sensor of any Gate (AND/OR) issue

### ISSUE THREAD

**Issue by Mysterizon** [BuildCraft/BuildCraft#3507]
Hello,

The issue is when I use either OR/AND of any gate from "basic" to "diamond", I used the gate with glowstone lamp to make a street lamp. I set up the gate to send redstone signal to the glowstone lamp at night time. it caused flicking/glitching, I am not sure what word to describe the issue. what happened is that it goes on and off every second. It doesn't matter which set up I used in either night time or daylight. 

Please take a look at these sensor gates. 

Additional information: 

I am using Buildcraft 7.1.18 and latest forge for 1.7.10. 

a few more issue: when i setup the gate to be active at daylight to send the redstone signal, but when it's night time and is still active. even it should be turned off. but it's not turned off.

**Comment by AEnterprise** [comment]
the light triggers don't know the difference between natural sunlight and light emited from a lamp, so when your gate turns on the lamp that causes the light level to go above the required value, turning it off again

same is probably heapening for your other setup

the best way would be to have a seperate gate in a different location not to close to the lamp that sends out a red pipe wire to the gate connected to the lamp to turn it on/off

**Comment by Mysterizon** [comment]
Oh right. I didn't think of it. of course, I didn't noticed it was the lamp that caused the light other than sunlight.  Thank you for clearing it up the issue, so i will close the issue.
