### ISSUE TITLE
[8.0.x] Crash related to WAILA (HWYLA) when breaking pipe wires

### ISSUE THREAD

**Issue by starg09** [BuildCraft/BuildCraft#3509]
This happens on a build made up to commit [38c1339e3638d435e9f52ebe9b18bf39e471c06a](https://github.com/BuildCraft/BuildCraft/commit/38c1339e3638d435e9f52ebe9b18bf39e471c06a). Forge version is 2260. Using HWYLA 1.8.10-B23.

Steps to reproduce:

* Place any type of wire.
* Place a wire on it (any color, doesn't appear to affect the outcome)
* Break the pipe or the wire with a left click, either in survival or creative.

Now, if you break it in creative mode it simply crashes the game, and once back the wire/pìpe+wire is gone. If you do it in survival, though, you do recover the wire item (and the pipe, if you broke it as well).

[Crash report](https://gist.github.com/starg09/f3c198d538303ba61991116dc5631e8f)

[Video of the crash](https://gfycat.com/NaturalAgonizingChinesecrocodilelizard)

**Comment by afdw** [comment]
Please try this commit from my branch: https://github.com/afdw/BuildCraft/commit/da911b1bb057a0196aafdc7ae4c2fc37dd52024d

**Comment by starg09** [comment]
Seems to be working perfectly by applying that commit! :smile:

**Comment by starg09** [comment]
By the way, @afdw while trying to build from your branch (since it seems to be more active than the main one, and I didn't notice). I noticed you seem to have marked it to use the Buildcraft-API submodule from Buildcraft instead of your own, which breaks the submodule updating (and therefore, compiling).

You may wanna update that so it uses yours by default 😛

**Comment by afdw** [comment]
@starg09 I don't want to do it because one day I'll send PR, and changing `.gitmodules` can cause problems. Maybe it should be added to `.gitignore`.
And yes, my fork contains all commits form main repo.

**Comment by AEnterprise** [comment]
is this still an issue?

**Comment by afdw** [comment]
No, as it's fixed.
