### ISSUE TITLE
[8.0.x] Mining any pipe with a pickaxe makes it also drop a Sandstone Kinesis Pipe

### ISSUE THREAD

**Issue by starg09** [BuildCraft/BuildCraft#3510]
This happens on a build made up to commit 38c1339e3638d435e9f52ebe9b18bf39e471c06a. Forge version is 2260.

[Video of what happens](https://gfycat.com/BlankFairGoldeneye). Breaking it bare-handed works as intended, using any pickaxe causes a Sandstone Kinesis Pipe to drop, and using other tools/items while breaking doesn't seem to trigger this.

**Comment by afdw** [comment]
Please try this commit: https://github.com/afdw/BuildCraft/commit/894281acc643733e82d8c5a6d4cc7210d08fdf11

**Comment by starg09** [comment]
Sorry, read this but forgot to reply! Tried to compile a build on your fork, but it seems to fail right now...

**Comment by afdw** [comment]
Yes: irc://irc.esper.net:6667#buildcraft

**Comment by AEnterprise** [comment]
should be fixed with https://github.com/BuildCraft/BuildCraft/commit/bfe93606dfbb6933c90087f2458a76192c1b3d90
