### ISSUE TITLE
[7.2.x] Command Based Pipe placing crashes or otherwise fails

### ISSUE THREAD

**Issue by dsmiller95** [BuildCraft/BuildCraft#3511]
When I set up a command block to place any pipe with the /setblock command; it seems like 1 of two things happen:

1. If the pipe is replacing most other blocks, then it looks like nothing happens at all. The pipe is "placed" , but it is never rendered nor is it possible to interact with it. It only takes up space, preventing other blocks from being placed in its spot
2. If the pipe is replacing another pipe, then the pipe displays as a cobblestone structure pipe. It is visible in the world, but it cannot connect to other pipes of any type. It becomes a game crash hazard: if debug mode is open and the player looks at the pipe, then it will crash the game.

I'm planning on picking up this issue myself to work on it, I'm posting it as an issue for completeness' sake and to get any info about similar problems and/or input from any of the devs

Screenshots:

Before using the /setblock command. The Target is the center pipe
![2017-03-27_15 00 15](https://cloud.githubusercontent.com/assets/3212309/24375467/fa7ef402-12fd-11e7-8bb6-e612f3e8bc8d.png)

After running `/setblock 392 4 -1270 buildcraft|transport:pipeBlock 0`
![2017-03-27_14 54 29](https://cloud.githubusercontent.com/assets/3212309/24375233/39e6f6ea-12fd-11e7-8b98-8af369ac1286.png)

Breaking the bugged block and replacing it with grass
![2017-03-27_14 54 37](https://cloud.githubusercontent.com/assets/3212309/24375234/39e778b8-12fd-11e7-9704-1b7a6dcc6cb1.png)

After Running the same `/setblock 392 4 -1270 buildcraft|transport:pipeBlock 0` command
![2017-03-27_14 54 47](https://cloud.githubusercontent.com/assets/3212309/24375232/39e5d8be-12fd-11e7-94d6-30d757a2f994.png)

After attempting to place a block in the bugged square, an outline appears where the pipe should be rendering
![2017-03-27_14 54 56](https://cloud.githubusercontent.com/assets/3212309/24375231/39e4f2f0-12fd-11e7-9599-63e37032d019.png)

**Comment by AEnterprise** [comment]
marking as enhancement as it isn't completely a bug, you are setting the block to the generic "pipeBlock" but that's shared accross all the pipes, currently there is no way to tell said pipe block what type it is so it assumes some default values
