### ISSUE TITLE
Buildcraft Kinesis Pipe + Railcraft Steam Engines 

### ISSUE THREAD

**Issue by Mysterizon** [BuildCraft/BuildCraft#3515]
Hello, 
I am currently using 
**-Minecraft 1.7.10**
-Buildcraft 7.1.18 
-Railcraft 9.12.2.0
-Forge 10.13.4.1614

I am sure you have noticed Railcraft Steam engines are referred to Industrial Steam Engine or Commerical Steam Engine, where they generated RF per ticks and the engine stored the RF in the engine. It does not matter which kinesis pipe I am using to get highest RF from the engine to another machine that require the RF. its always low as 40RF/t even it is supposed to be 80RF/t or 320RF/t. 

no matter what setup I have tried. It seems that the problem is within Buildcraft pipes or Railcraft. I dont know which one. 

Let me know if you need more information. That's all i can think of.

**Comment by dj3520** [comment]
Unable to reproduce with Buildcraft 7.1.20.

**Comment by Mysterizon** [comment]
oh. i see that Buildcraft wasn't updated in Curse Program. let me run some test

**Comment by AEnterprise** [comment]
oh the curser version being outdated is my fault, i was sure i did it but apearently not, will fix now

expect the curse versions to be up to date with release in an hour or so (depinding on curse apoval times at this hour)

**Comment by Mysterizon** [comment]
Okay, I have tested it with the latest Buildcraft, Version 7.1.21. It looks like the issue have been resolved. 

this issue is now closed.
