### ISSUE TITLE
The quarry doesn't do anything in version 7.99.0 (1.11.2)

### ISSUE THREAD

**Issue by Iggykoopa** [BuildCraft/BuildCraft#3517]
The quarry doesn't do anything in version 7.99.0.

**Comment by afdw** [comment]
Try to right click it and put frames in its inventory.

**Comment by Iggykoopa** [comment]
No, it was just the power source I was using. I figured that out on my own
and just forgot to say that when I found it out.

**Comment by afdw** [comment]
Anyway, it's not too obvious that quarry now require frames, it breaks old habits of players.

**Comment by AEnterprise** [comment]
that won't be to bad once BC 8 is released, it's a major version number increase so people usually realise mechanics might have changed

also what's the status of the guide book? that would help alot as well

**Comment by afdw** [comment]
There are other ways to balance quarry sizes: more energy consumption, lubricant that increases its speed. And I currently not sure which will be better.

**Comment by dj3520** [comment]
Why not both?

**Comment by afdw** [comment]
Both what? There are 3 ways I know.

**Comment by dj3520** [comment]
I only saw two in your post
>more energy consumption, lubricant that increases its speed

**Comment by afdw** [comment]
Third is "quarry require frames which are obtainable".

**Comment by dj3520** [comment]
For me that would come down to cost I suppose.

**Comment by afdw** [comment]
No, not 1.7.10, but 1.11. It's all about 8.0.x branch.

**Comment by dj3520** [comment]
Yes I know. The reference to 1.7.10 is specifically for the costless-frames. They seem to appear out of nowhere.

**Comment by athrake** [comment]
guys i know i will sound silly but i couldn't find how to craft a frame. and i didnt want to open a new issue for it. could you help me please?

**Comment by AlexIIL** [comment]
@athrake  Its not survival ready atm, so there is no recipe.

**Comment by athrake** [comment]
oh i see. thank you for that sir. i presume that is the answer of why i cant craft quarry as well. @AlexIIL

**Comment by AEnterprise** [comment]
gona close this as it's not realy a bug, for the recipes see #3527
