### ISSUE TITLE
Curse Updates

### ISSUE THREAD

**Issue by reteo** [BuildCraft/BuildCraft#3519]
I just discovered that BuildCraft is not updating on Curse; as of right now, the 1.7.10 version of BuildCraft is [7.1.21](https://www.mod-buildcraft.com/buildcraft-7121.html), while the latest version on Curse (for the same MC version) is [7.1.18](https://minecraft.curseforge.com/projects/buildcraft/files?filter-game-version=1738749986%3a5).

**Comment by asiekierka** [comment]
@AEnterprise

**Comment by AEnterprise** [comment]
yes i know, i was notified yesterday that 7.1.20 was missing but then i saw you where going to push the 7.1.21 update so decided to wait untill today

**Comment by AEnterprise** [comment]
uploaded

**Comment by LuigiHutch** [comment]
shouldn't BC 7.99.0 be marked as alpha of curse? not beta

**Comment by asiekierka** [comment]
It should.

**Comment by AEnterprise** [comment]
i did put it as alpha, on it the initial upload of it i accidentaly marked as beta but edited to alpha right away, if i try to edit it again says it's an alpha and the files is treated as such, the beta is a display issue

**Comment by AlexIIL** [comment]
Can you please remove 7.99 from curse? Its not ready for that level of scrutiny yet.

**Comment by AEnterprise** [comment]
@AlexIIL as i said on curse now: the alpha state prevents it from being seen on mods.curse.com (what still most of the users use to download) and their client doesn't show it eighter

as for putting it on curse: the only thing that would have heapened if i wouldn't put it on there is that even more users would complain about it not being on there, everyone is looking for it and it is available on the main site

**Comment by AlexIIL** [comment]
@AEnterprise thanks for clarifying, I had forgotten that curse treated alpha as such :)
