### ISSUE TITLE
Game crashes when searching @buildcraft in jei (1.11.2)

### ISSUE THREAD

**Issue by Cuplex17** [BuildCraft/BuildCraft#3520]
I don't know if this is an issue due to buildcraft itself or with jei rendering.

**Comment by afdw** [comment]
What is version of JEI? Is it latest?

**Comment by AEnterprise** [comment]
most likely rendering, could you provide a crashlog? also how many items (aproximatly) does one page of JEI show for you?

**Comment by afdw** [comment]
Latest is `jei_1.11.2-4.3.1.260.jar`.

**Comment by afdw** [comment]
Works for me on dev environment, please send log.

**Comment by Cuplex17** [comment]
Apparently, the crash report says that the rendering is caused by a different mod. But it crashes when I search up buildcraft things. Don't know if its related but I'll put the crash report anyway. Might just be the modpack I'm playing.

[crash-2017-04-12_14.26.50-client.txt](https://github.com/BuildCraft/BuildCraft/files/915395/crash-2017-04-12_14.26.50-client.txt)

**Comment by afdw** [comment]
Please try without Astral Sorcery.

**Comment by Cuplex17** [comment]
The game still crashes. Even without Astral Sorcery.

[crash-2017-04-12_14.55.45-client.txt](https://github.com/BuildCraft/BuildCraft/files/915447/crash-2017-04-12_14.55.45-client.txt)

**Comment by AEnterprise** [comment]
can you try without optifine?

**Comment by afdw** [comment]
And please try without BuildCraft.

**Comment by Cuplex17** [comment]
Without buildcraft, it works fine but without optifine, the world wouldn't load. My guess is that it is just a compatibility issue with another mod and rendering in jei. I also tried just playing with buildcraft and jei and it works fine.

**Comment by AEnterprise** [comment]
closing as it's an optifine problem
