### ISSUE TITLE
[7.99] NoSuchMethodError: buildcraft.api.tools.IToolWrench.wrenchUsed

### ISSUE THREAD

**Issue by Dykam** [BuildCraft/BuildCraft#3522]
Using BC 7.99 on Minecraft 1.11.2 using Forge 13.20.0.2282.

Trying to change the direction of an Iron Pipe using a Wrench.

https://gist.github.com/Dykam/aae46dd80e64c87318f809754400751e

(Sidenote, I had to spawn in a Redstone Engine to craft a Pipe Pulsar for the wooden pipe, as the recipe didn't work, though reading the source I can't figure out why).

**Comment by asiekierka** [comment]
Another mod in your pack might be providing an outdated version of the BuildCraft API. Could you please try with just BuildCraft?

**Comment by Dykam** [comment]
Alright, I will, though that will be a bit later.

It's my own "pack", using the Curse (now Twitch) launcher to pick mods. Recently added BC and everything appears up to date. But I'll check using just BC when I have time.

**Comment by Dykam** [comment]
Resolved, Solar Flux Reborn includes a single BuildCraft class, wrecking BuildCraft itself.

Here's the (mislicenced code drop) source: https://github.com/MrDimkasStudio/SolarFluxReborn/blob/4946cf/src/main/java/buildcraft/api/tools/IToolWrench.java

I'll issue a bug report with that repository. Any idea of a workaround, besides patching it up myself (code drop is outdated even)?

**Comment by asiekierka** [comment]
@Dykam They'll probably have to fix it themselves.

**Comment by Dykam** [comment]
The solution seems to be to rip out support. I don't have a very high view of the author, also re: ripping out the licence from the original Solar Flux.

Oh well, that would fix it.
