### ISSUE TITLE
Missing recipes

### ISSUE THREAD

**Issue by SambalMinion** [BuildCraft/BuildCraft#3527]
Hi guys,

I'm running a homebrew modpack on a forge server and am encountering an issue where some BC recipes are not registering in the client. I am seeing two things:

- JEI/JER lists the uses of the items for crafting other items, but not the recipes to craft them.
- Items can be obtained through creative mode or /give, but cannot be crafted.

Let me know if there is anything I could do to make debugging this easier on you guys.

**Versions:**

- BC 7.99.0
- MC 1.11.2
- Forge 13.20.0.2282

**I have tested on:**
Issues persists across all three environments.

- A fresh profile, with only Buildcraft.
- Single-player version of my modpack.
- Multiplayer version of same modpack on a LAN server.

**Tests:**
My tests haven't been exhaustive, but I have tried several items and can conclude the following:

- No recipe in JEI/JER = not craftable.
- Affects all three engines. (None are craftable, although the BC_Transport pipe pulsar is.)
- Of BC_Silicon, only the laser is craftable.
- Of BC_Factory, the two gels show up as item.gel.name / item.waterGel.name and are not craftable. The rest works fine.
- Some of BC_Transport works; filters, lenses, pipe wires and the light sensor do not work.
- Four blocks (tile.decorated.destroy.name, same for blueprint, template, paper, leather and laser_back) are available through creative and show up in JEI, but do not have recipes associated with them.
- Paint brushes have recipes.
- The List does not have a recipe.

**Logs:**
No client logs - sorry, bit new to the game. Server outputs the following on startup:
```
[08:36:16] [Server thread/WARN] [FML]: ****************************************
[08:36:16] [Server thread/WARN] [FML]: * Unknown recipe class! buildcraft.lib.recipe.NBTAwareShapedOreRecipe Modders need to register their recipe types with net.minecraftforge.oredict.RecipeSorter
[08:36:16] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.getPriority(RecipeSorter.java:241)
[08:36:16] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:176)
[08:36:16] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:55)
[08:36:16] [Server thread/WARN] [FML]: *  at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
[08:36:16] [Server thread/WARN] [FML]: *  at java.util.TimSort.sort(Unknown Source)
[08:36:16] [Server thread/WARN] [FML]: *  at java.util.Arrays.sort(Unknown Source)...
[08:36:16] [Server thread/WARN] [FML]: ****************************************
```

**Comment by AEnterprise** [comment]
it's an early alpha build so there are indeed things that do not have a recipe yet

the warning from the log is semi related, seems the custom BC recipe isn't being registered completely with forge yet

**Comment by AlexIIL** [comment]
A lot of recipes have been added in commits since 7.99.0 - whenever 7.99.1 is released that should fix *most* of them. However note that some items will be made in the assembler so the recipes for them will only be visible in the guide book - JEI compat for those will go in https://github.com/BuildCraft/BuildCraftCompat instead.

I'll fix the recipe sorting though - I'm not sure why I've been sitting on that for so long :/

**Comment by afdw** [comment]
@AlexIIL When you want to release 7.99.1?

**Comment by AEnterprise** [comment]
@AlexIIL that's called putting off minor non game crashing things :P anyways it's on your TODO now

**Comment by ETStarLight** [comment]
I only wants to know why BC doesn't have the version of MC1.10.2.
As we all know，even IC doesn't have gone on 1.11.2,in 1.11.2 there's  nearly no mod can play together with BC;and nearly all great mods have the version of 1.10.2.
I heard that there's not big changes from1.10.2to1.11.2，so I still hope 1.10.2BC8.

**Comment by AEnterprise** [comment]
@ETStarLight please don't just comment on a random issue with an unrelated question

also please use the search before asking a question (and tbh i'm getting tired of everyone asking that same question just over and over again):  #3529

**Comment by asiekierka** [comment]
@ETStarLight IC2 and Forestry are both available on 1.11.2, what are you talking about? (Also, what AEnterprise said)

**Comment by ETStarLight** [comment]
OK，I'm sorry for my rush.I just like BC very much and it's necessary for me:D.
I'm sorry brothering you.I only thought about there's more mods for1.10.2than1.11.2.

**Comment by asiekierka** [comment]
@ETStarLight There are more mods for 1.10.2, yes. However, the team decided to target 1.11.2 a long time ago and, as of now, are planning on sticking to it.

**Comment by SambalMinion** [comment]
@AEnterprise @AlexIIL Thanks for the comprehensive answer, I'll happily wait for 7.99.1 and will retry when that becomes available through Twitch/Curse (Twurtch?).
I assembled my modpack entirely through the Twurtch Client. The alpha version is indeed visible there, as noted previously in #3523. Hope Twurtch gets it together ;-)

**Comment by valentin616** [comment]
I tested in 7.99.1 and all engines have their craft in jei.

**Comment by AlexIIL** [comment]
Don't add recipes for blocks or items that aren't done yet

**Comment by afdw** [comment]
They will be disabled in not-BCLib.DEV environment, why not add recipes?

**Comment by AEnterprise** [comment]
as long as they are dissabled outside of dev i think recipes are fine, if they are added now we can let them sink in and think about it a bit and tweak if needed

**Comment by AEnterprise** [comment]
re-opening as reference, some things still don't have a recipe
