### ISSUE TITLE
[Question] Buildcraft 8 --> Only 1.11 or 1.10

### ISSUE THREAD

**Issue by mister-man** [BuildCraft/BuildCraft#3529]
Hallo together,

I found these for BC8: "The eighth major release of BuildCraft! Currently developing on Minecraft 1.11.2"
Is there any chance to use BC on 1.10, because other importend mods are avalible for 1.10 but not for 1.11.2

Thanks a lot :)

**Comment by AEnterprise** [comment]
no there wil not be a 1.10 version, we do not have enough developers or time to maintain 2 minecraft versions and since BC8 is still in early alpha stage 1.11 is the target, by the time we can move on to regular releases 1.11 should be the main MC version unless the community already moved to 1.12
