### ISSUE TITLE
Disabling cobblestone pipe and its crafting dependencies in objects.cfg creates invalid recipe crash on loading

### ISSUE THREAD

**Issue by TheWildMind** [BuildCraft/BuildCraft#3533]
Just a crash I came across while building my modpack. 
Disabling cobblestone pipe and its crafting dependencies in objects.cfg creates invalid recipe crash on loading.
I added buildcraft for its builder machine which is just excellent.

[crash-2017-04-28_01.34.25-client.txt](https://github.com/BuildCraft/BuildCraft/files/963204/crash-2017-04-28_01.34.25-client.txt)
[objects.zip](https://github.com/BuildCraft/BuildCraft/files/963206/objects.zip)

Regards,

**Comment by AEnterprise** [comment]
looks like you missed dissabeling something that needs a dissabled item

if you only need/want the builder you could use the modules and only install the core and builder modules

**Comment by TheWildMind** [comment]
Thank you for the words of advise. The modular install works like a charm. Its exactly what I wanted!

It also solves a second issue I had which was adding Buildcraft to an existing GC world ^^
_I was getting the classic 4 missing blocks (oil blocks from GC) errors on world loading.
(Although I thought it was fixed with the latest versions of GC and BC, but for some reason I still got it. I can share my logs if need be.)._

Regards,

**Comment by AEnterprise** [comment]
gona close this then as it's a 1.7.10 issue and the recipe system got changed for 8.0
