### ISSUE TITLE
Galacticraft frozen fuel problem

### ISSUE THREAD

**Issue by Aragrohl** [BuildCraft/BuildCraft#3534]
This happened when using the 78 Beta galacticraft build and the 7.99.1 alpha buildcraft build, here's the log.
[crash-2017-04-30_19.56.52-client.txt](https://github.com/BuildCraft/BuildCraft/files/966927/crash-2017-04-30_19.56.52-client.txt)

**Comment by AEnterprise** [comment]
looks like the BC fluidrenderer is choking on the galacticraft fuel, might be an issue on their side but the code should probably be made more robust so it doesn't completely crash

**Comment by Aragrohl** [comment]
Ok should I go post it to their github page?

**Comment by AEnterprise** [comment]
looking more at it BC is purposely crashing atm when it fails to map a texture, i'm not exactly sure if it's a BC issue or that something is wrong with that fluid

@AlexIIL are you sure this is the route we want to take in this case?  wouldn't it be better to use the missing texture texture instead so atleast the game can load? that texture should be indication enough that something needs fixing without breaking things on launch

**Comment by AlexIIL** [comment]
Its alpha. Its crashing so that I can pick up where code doesn't work rather than just logging an error as then they wouldn't get reported.

**Comment by radfast** [comment]
thanks guys, just confirming this is not a Galacticraft issue :)  (it was reported to us as well)

@AlexIIL   anything we can do to help on Galacticraft's side, please comment on https://github.com/micdoodle8/Galacticraft/issues/2660 -  I can also give you my Skype privately so you can contact me directly if you need it

**Comment by AlexIIL** [comment]
@radfast I haven’t looked into it yet but it is almost certainly a BC logic bug. I'll post more details when I've looked into it though.

**Comment by radfast** [comment]
@AlexIIL   I think it's likely that what has happened here is that Galacticraft also registers a fluid with the same name ```fuel```  and as you know, the Forge fluid system picks one of the two mods registering the fluid as the "default" fluid for that name.

I'm actually not sure how Forge picks between the mods, but I guess in this case it picked us first ... ;)

If there's some parameter I can change when Buildcraft is present, to tell it to give your fluid priority, I don't mind doing that.  Obviously we want full compatibility between our two mods.

**Comment by AlexIIL** [comment]
nonono, its a bug in buildcraft's texture duplication + expansion code. Basically, for every fluid's still sprite it creates a new sprite called ````"buildcraftlib:fluid_" + srcLocation.toString().replace(':', '_') + "_convert_frozen"````, and if it fails to stitch this *new* sprite to the map (as no other mod should use the buildcraftlib namespace) then it crashes. I guess what's happening here is they you have two fluids that both use the same sprite (and so I'll tweak the impl to not recalculate a new sprite if its already done it)

**Comment by radfast** [comment]
frozen fluids, sounds like fun.

We have a Liquid Nitrogen Canister item.  If the player activates the item on a water block, it turns it into Ice.  Maybe I can extend this to freeze all your fluids too :)

**Comment by AlexIIL** [comment]
Its used for making the flow effect in fluid pipes - it doesn't look quite right if we use the still image directly, so we double the size of the first frame.

**Comment by radfast** [comment]
I'll leave you to it, you're welcome to get in touch if any future compatibility issues arise.

**Comment by AlexIIL** [comment]
@radfast Sure, thanks for being friendly about this :)

@Aragrohl In theory commit https://github.com/BuildCraft/BuildCraft/commit/ade5f9b1eb67a4ff9789d3d804fe010e4523c3f9 should have fixed it, so please can you either build + test this yourself or wait until 7.99.2 and retest it to make sure its fixed :)

**Comment by AEnterprise** [comment]
@Aragrohl you can grab build 164 from the jenkins to test with

http://vps1.oldguys.eu/jenkins/job/BuildCraft-8.0.x/

**Comment by Aragrohl** [comment]
@AEnterprise @AlexIIL @radfast Sorry for the bother, I might have been a bit hasty posting it to the Galacticraft github and yes it works with build 164 and build 78 of Galacticraft thanks guys.

**Comment by AlexIIL** [comment]
@Aragrohl The error message isn't that helpful atm, it should really of said the BC texture that failed to overwrite rather than the Galacticraft one, but thanks for verifying :)

**Comment by Hypsellis** [comment]
I het the saùe crash with lightningcraft https://pastebin.com/ZNcw6CPC

**Comment by AEnterprise** [comment]
@Hypsellis yes that is the same crash and it has been fixed, you can eighter use that jenkins builld or wait for the next release

**Comment by Hypsellis** [comment]
Nah it's fine I will wait the next release. ;)
