### ISSUE TITLE
Crash on dedicated server

### ISSUE THREAD

**Issue by kenijey** [BuildCraft/BuildCraft#3536]
[crash-2017-05-01_17.55.07-server.txt](https://github.com/BuildCraft/BuildCraft/files/968066/crash-2017-05-01_17.55.07-server.txt)
dunno which mod causes, forge 2285. thanks

**Comment by AEnterprise** [comment]
literalascension is throwing the error but i'm not sure if BC is not respecting the method contract or if that mod is assuming a contract doesn't exist and i don't have a modding environment on this laptop to check it

**Comment by kenijey** [comment]
okay let me delete that mod and test.

**Comment by afdw** [comment]
https://github.com/BuildCraft/BuildCraft/commit/7855814ebfee3a21e299ec91c4937391bae53a25 should fix issue with literalascension.

**Comment by kenijey** [comment]
uhm, yes it works without literalascension; but it seems like u guys fix it ^^ so i'm waiting for the new release. thanks!

**Comment by afdw** [comment]
You can also wait for [Jenkins build](https://jenkins.rttr.info/job/BuildCraft/job/BuildCraft/job/8.0.x/) with this commit which should be available earlier.

**Comment by kenijey** [comment]
oh! thanks so much for the jenkins link. didn't aware f this

**Comment by AEnterprise** [comment]
asked arround and you are indeed not suposed to pass in null to that function
