### ISSUE TITLE
Pump is not working with engine 1.11.2 [ BC 7.99.1]

### ISSUE THREAD

**Issue by athrake** [BuildCraft/BuildCraft#3539]
![2017-05-01_22 18 05](https://cloud.githubusercontent.com/assets/28269950/25591305/ad03975c-2ebc-11e7-872c-0cbb94a2fdb4.png)

When I attach a combustion engine to my pump and give redstone signal to the engine, the pipe of the pump that goes into the liqud goes back in. Is this a bug or am I doing something wrong?

**Comment by AEnterprise** [comment]
is it possible your redstone signal is also traversing to the pump? a redstone signal will dissable the pump and cause it to retract it's hose

**Comment by athrake** [comment]
I uploaded a screenshot of how i try to do it. I believe it is not reaching to the pump.

**Comment by afdw** [comment]
Have you any source blocks under pump?

**Comment by AEnterprise** [comment]
can you replace that torch with a block and put a lever on top of that? the engine might be carrying a weak redstone signal to the pump

**Comment by athrake** [comment]
![2017-05-01_22 29 06](https://cloud.githubusercontent.com/assets/28269950/25591676/2c0e7df4-2ebe-11e7-8d7b-aba3c056024f.png)

Still nothing, sir.

**Comment by LuigiHutch** [comment]
Replace the iron pipes with either cobble/stone/quartz or gold fluid pipes. Iron fluid pipes 'as stated on their tooltip' are for piping the fluids in a certain direction so the water is flowing into the pipe then back into the pump as the iron pipe is facing that direction.
You can also use a wrench to change the fluid pipes rotation

**Comment by athrake** [comment]
![2017-05-01_22 32 17](https://cloud.githubusercontent.com/assets/28269950/25591763/9d9f13e8-2ebe-11e7-8145-477f771167fd.png)


Thank you sir, problem solved!

**Comment by AEnterprise** [comment]
alright, that's a note for the future manual: pumps turn off and retract hose when internal tank is full now

**Comment by LuigiHutch** [comment]
No problem! Here is a playlist of tutorials for if you get stuck again for BuildCraft which are fairly upto date:
https://www.youtube.com/playlist?list=PLPCqiTnvx2GsE8t96c7CAepx9tDo7TgzN

Bare in mind that BC for 1.11.2 is in alpha so there will be alot of missing features/bugs compared to these but they should help :)
