### ISSUE TITLE
Crash(game won't start)

### ISSUE THREAD

**Issue by kenijey** [BuildCraft/BuildCraft#3541]
[crash-2017-05-02_09.40.22-client.txt](https://github.com/BuildCraft/BuildCraft/files/969614/crash-2017-05-02_09.40.22-client.txt)
please help...

**Comment by AEnterprise** [comment]
duplicate of #3534 

please search for your issue next time and make a more descriptive issue please.

**Comment by kenijey** [comment]
oh sorry
