### ISSUE TITLE
Implement additional filler patterns

### ISSUE THREAD

**Issue by Prototik** [BuildCraft/BuildCraft#3555]
- [x] Circle
- [x] Round
- [x] Sphere
- [x] Ball
- [x] Triangle
- [x] Pentagon
- [x] Hexagon
- [x] Octagon

**Comment by LuigiHutch** [comment]
What about some 2d shapes which extend in a direction you set it such as:
- Triangle
- Pentagon
- Hexagon
- Octagon

Similar to the way the openblocks building guide does it.

**Comment by Prototik** [comment]
@LuigiHutch nice idea, added to tasklist

**Comment by AlexIIL** [comment]
Should be implemented in 7.99.8: https://www.mod-buildcraft.com/buildcraft-7998-alpha.html.
