### ISSUE TITLE
Buildcraft crashing with Neotech

### ISSUE THREAD

**Issue by IchigoGames** [BuildCraft/BuildCraft#3556]
crashing bug with buildcraft and Neotech i know bc is still in alpha i just wanted to make sure this got reported.

minecraft 1.11.2 
forge 2294
buildcraft-7.99.1

https://pastebin.com/kGBDeYEQ

**Comment by LuigiHutch** [comment]
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3534
