### ISSUE TITLE
Incompatible with Xaero's minimap

### ISSUE THREAD

**Issue by freitorsk** [BuildCraft/BuildCraft#3557]
It appears that 7.99.1 is currently incompatible with the most popular minimap mod. The game crashes when I try to run them simultaneously. Crash report is included. 
[crash-2017-05-06_19.13.47-client.txt](https://github.com/BuildCraft/BuildCraft/files/981001/crash-2017-05-06_19.13.47-client.txt)

**Comment by AEnterprise** [comment]
The crash is on Xaero's side of things, looks like he's failing to determine the color from a texture to show, there is nothing we can do about this, you will need to report this to him to get it fixed
