### ISSUE TITLE
Builder doesn't work on the server [1.7.10] [v7.1.21]

### ISSUE THREAD

**Issue by 0othomio0** [BuildCraft/BuildCraft#3559]
Builder works in singleplayer, but it doesn't works on the server

**Comment by AEnterprise** [comment]
is there anything permission related on the server that might be blocking it from building? things like sponge or other permission plugins?

also make sure you are not building in the area arround spawn that is protected

**Comment by 0othomio0** [comment]
Yes, i have server on the Thermos with PermissionEx

**Comment by 0othomio0** [comment]
I deleted PermissionEx, but the problem did not disappear

**Comment by LuigiHutch** [comment]
try /buildcraft op

**Comment by 0othomio0** [comment]
How to do it?

**Comment by 0othomio0** [comment]
Just write?

**Comment by LuigiHutch** [comment]
just type that in the chat ingame

**Comment by 0othomio0** [comment]
Don't works

**Comment by LuigiHutch** [comment]
are you op on the server?

**Comment by 0othomio0** [comment]
Yes

**Comment by AEnterprise** [comment]
any other mods/plugins that might be related to permissions, please try to reproduce this with just BC

if it still heapens it is most likely an issue with thermos

**Comment by asiekierka** [comment]
@0othomio0 Permissions were always a problem. Thermos will probably break BuildCraft in other ways as well - we don't recommend using it.

**Comment by AEnterprise** [comment]
gona assume this is a permissions setup issue as it works on a regular forge server and others have gotten it to work just fine with permission plugins
