### ISSUE TITLE
No kinetic pipes

### ISSUE THREAD

**Issue by tattila8** [BuildCraft/BuildCraft#3566]
I cant craft kinetic Pipes in Buildcraft 7.99.2

I use All the mods 2 v0.62

Please help!

**Comment by LuigiHutch** [comment]
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3523. Also, why the hell are the alpha's in a public modpack?!?!

**Comment by AEnterprise** [comment]
@LuigiHutch because modpack makers gladly ignore alpha tags or work around them to get the newest mods in their packs, even if they are unstable
