### ISSUE TITLE
The Distiller is missing an item model

### ISSUE THREAD

**Issue by playhazard** [BuildCraft/BuildCraft#3567]
Distiller(Refinery) stops working during use after a few minutes of being active.

Only fix is to save, quite and reload.

Inventory icon is also missing.

**Comment by AEnterprise** [comment]
when it stops working does it still have fluids and energy in it's internal buffers?

**Comment by afdw** [comment]
You probably closed this as accident.

**Comment by AEnterprise** [comment]
@playhazard is it accepting the input or rejecting it? if it's rejecting what are the internal buffer statuses? are the full/empty/paritally filled?

**Comment by playhazard** [comment]
I'll take a look next time I have it happen but oil is full and stops flowing in because its full.

Typically the combustion engines stop functioning as well, regardless of whether you remove and replace them.

I assume the lower rear section with a sort of brownish buffer level is power?

**Comment by AlexIIL** [comment]
The lower rear section is a tank containing (most likely) Heavy Oil, and the top tank most likely contains Gaseous Fuel.

**Comment by playhazard** [comment]
Ok it appears that the conversation from heavy oil to gas is stalling. I took a screenshot

[http://imgur.com/wXgRdvx](url)

**Comment by AlexIIL** [comment]
Looks like the bottom tank is full. Can you try putting a wooden fluid pipe below it and pumping the fluid out?

**Comment by LuigiHutch** [comment]
you have to pump that fluid out the bottom of the distillery, as it now has 2 outputs

**Comment by playhazard** [comment]
That appears to have fixed the problem, I didn't realise I needed to drain both tanks. Thanks!

The missing icon is still an issue though.
