### ISSUE TITLE
Crash with Tinkers Installed 1.11.2

### ISSUE THREAD

**Issue by RedBullSlurpie** [BuildCraft/BuildCraft#3568]
So basically it wont load up to the main menu if I have Tinkers and BC installed at the same time. Latest versions from both mod as of today, and latest forge.
Forge Version- 13.20.0.2296
TC Version- 2.7.0.12
BC Version- 7.99.3
MC Version- 1.11.2
Crash log- https://pastebin.com/kypa7FGU

**Comment by LuigiHutch** [comment]
Actually update to 7.99.3, you are on 7.99.1. Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3534

**Comment by AEnterprise** [comment]
crash reports states you are running 7.99.1, please update to 1.99.3, already fixed
