### ISSUE TITLE
buildcraft-7.99.1 and up

### ISSUE THREAD

**Issue by net4fun4ever** [BuildCraft/BuildCraft#3569]
Hi, i can't seem to load the new alpha versions of the mod, the buildcraft-7.99.0.jar works great, but everything above crashes. I dont think this is a build issue. There is yust something wrong with my config.

[crash-2017-05-12_11.13.52-client.txt](https://github.com/BuildCraft/BuildCraft/files/995616/crash-2017-05-12_11.13.52-client.txt)

**Comment by AEnterprise** [comment]
it's a problem with another mod, someone is still returning `null` instead of an empty itemstack for pickblock

can remove mods until you find the cullpit and report it there?

**Comment by net4fun4ever** [comment]
Sure, i will find it and post it here. Tnx for the quick reply

**Comment by net4fun4ever** [comment]
Found it, Biomes O' Plenty mod is the fault here. Tryed the new beta, still no go.

**Comment by AEnterprise** [comment]
ok, you'll want to report it to their issue tracker then to fix
