### ISSUE TITLE
low FPS

### ISSUE THREAD

**Issue by woodzykiler** [BuildCraft/BuildCraft#3572]
sponge 1.11.2, 
with this mod installed the client drops down to 6-10 FPS on a client that has 32 mods, and 3GB ram.
with this mod Not installed FPS is a stable 40-60.
Please note; no items from this mod are placed in world and the fps still drops

**Comment by LuigiHutch** [comment]
BC version?
Forge Version?
Client log?
Try removing sponge and see of that helps

**Comment by AEnterprise** [comment]
if there is no items from BC placed in the world i doubt it's BC causing this directly, can you try increasing your ram allocation? depending on the modlist 3GB might only barely be enough (causing the GC to heapen more often and more agressively)

a debug crash (hold F3 + C for 10-15 seconds) might give us more info (put it on pastebin/gist and link here) or you could try some profiling if you know how to do that

**Comment by AEnterprise** [comment]
any update on this?

**Comment by AEnterprise** [comment]
closing due to lack of info
