### ISSUE TITLE
7.99.3 buildcraftfactory:distiller has no model for inventory

### ISSUE THREAD

**Issue by 0142929** [BuildCraft/BuildCraft#3574]
using buildcraft-7.99.3.jar

[Client thread/ERROR] [FML/]: Exception loading model for variant buildcraftfactory:distiller#inventory, normal location exception:                                                                                                 ░
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model buildcraftfactory:item/distiller with loader VanillaLoader.INSTANCE, skipping

![clipboard01](https://cloud.githubusercontent.com/assets/896793/26027428/8874efea-3816-11e7-9282-3e28113f51a9.jpg)

and few other problems:

and some others like that:

[Client thread/ERROR] [FML/]: Exception loading model for variant buildcraftcore:engine#facing=west,stage=yellow,type=iron
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model buildcraftcore:engine#facing=west,stage=yellow,type=iron with loader VariantLoader.INSTANCE, skipping

[Client thread/ERROR] [FML/]: Exception loading model for variant buildcraftcore:engine#facing=south,stage=yellow,type=stone
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model buildcraftcore:engine#facing=south,stage=yellow,type=stone with loader VariantLoader.INSTANCE, skipping

**Comment by LuigiHutch** [comment]
This is fixed for the next update :D

**Comment by 0142929** [comment]
great :)
