### ISSUE TITLE
Quarry turns any type fluid pipe into emerald fluid pipe[7.99.3][1.11.2]

### ISSUE THREAD

**Issue by playhazard** [BuildCraft/BuildCraft#3575]
Any type fluid pipe turns into emerald fluid pipe when mined by a quarry.

EDIT: Any type of pipe(transportation or fluid) becomes emerald fluid pipe

**Comment by AEnterprise** [comment]
sounds like eighter a duplicate or related to #3510

**Comment by LuigiHutch** [comment]
That also means that the Wooden Diamond fluid pipe has the wrong name ;)
