### ISSUE TITLE
Issue with Buildcraft Schematic Registry

### ISSUE THREAD

**Issue by Daminer5** [BuildCraft/BuildCraft#3581]
Got a slight issue with the Schematic Registry and i spent about an hour looking through forums trying to figure out this issue. Generally i find a fix for most and i figure out some on my own... any ideas?

[Crash report](https://pastebin.com/DmRgrmrr)

**Comment by AlexIIL** [comment]
It looks like BuildCraftSchematics (seperate mod, mod jar is ````[Buildcarft Schematic Mod] (bsm-1.7.10-0.3.0.jar)````) is looking up an older/different version of the BC schematic API.
Can you try removing it to check if it is the cause?

**Comment by Daminer5** [comment]
Well thats odd it was working before and i hadn't updated anything. Trying what you suggested now.

**Comment by Daminer5** [comment]
well that fixed the issue
