### ISSUE TITLE
Facades have broken code

### ISSUE THREAD

**Issue by tahg** [BuildCraft/BuildCraft#3582]
Not sure what the issue is. Seems to only involve extrautils resources, but I'll keep an eye out.
See trace here: https://pastebin.com/3x69sjRv

and here for a slightly different trace: https://pastebin.com/8XPUiyER

**Comment by afdw** [comment]
Can you please say your ExtraUtilities version?

**Comment by mezz** [comment]
extrautils2-1.11.2-1.4.1

**Comment by AlexIIL** [comment]
ExtraUtilities ````PropertyEnumSimple.parseValue```` isn't implemted equally to ````PropertyEnumSimple.getName(prop)```` - the map creation does this:
````java
      this.nameToValue.put(t.toString(), t);
      this.propertyNames.put(t, t.toString().toLowerCase());
````

**Comment by mezz** [comment]
I think it's important for the facades to be resistant to all kinds of nasty errors, ideally disabling and blacklisting the facade when an error is encountered.

**Comment by afdw** [comment]
OK, will do.

**Comment by AlexIIL** [comment]
Yes, but that doesn't mean that there aren't issues elsewhere as well. I can fix the first log issue, hopefully that fixes the second logged issue as well.

**Comment by mezz** [comment]
Sounds good, we will also try to forward the ExtraUtilities2 error to RWTema.

**Comment by AlexIIL** [comment]
thanks

**Comment by tahg** [comment]
Same issue, only involving Vanilla and BC, when trying to open the creative search GUI
https://pastebin.com/La8aPAb9

**Comment by AlexIIL** [comment]
@tahg That's using more than just vanilla + BC...

**Comment by AlexIIL** [comment]
@tahg Can you remove extra utils 2 and try to reproduce it?

**Comment by tahg** [comment]
Ok, removing ExU fixes the issue with the creative bar. I guess it just wasn't apparent in the stack trace.  Not sure if that ultimately fixes the first two issues, but probably.
