### ISSUE TITLE
Missing oil :( I lost all my oil wells

### ISSUE THREAD

**Issue by ZeroT01erance** [BuildCraft/BuildCraft#3586]
After update from 7.99.0 -> 7.99.3
![2017-05-16_17 09 18](https://cloud.githubusercontent.com/assets/17812947/26110363/c823762a-3a5a-11e7-98f2-e9fbcef38d23.png)

**Comment by AEnterprise** [comment]
was there anything in your logs or any warnings from forge when loading up the world?

we might want to check if this also heapens with older versions to the recent ones to see if this needs fixing or not

**Comment by ZeroT01erance** [comment]
MISSING BLOCKS/ITEMS
buildcraftenergy:fluid_block_oil

**Comment by AlexIIL** [comment]
@ZeroT01erance We'll need the whole log file, not just an extract

**Comment by ZeroT01erance** [comment]
http://www.mediafire.com/?j1071jydjpr8v

**Comment by AlexIIL** [comment]
Thanks - I'll add a remap entry for oil and fuel.

**Comment by AlexIIL** [comment]
(This is fixed in dev, and will be pushed out in 7.99.4 soon.)

**Comment by AlexIIL** [comment]
Note: If you don't replace the blocks where the oil was then they *should* revert to oil. However you might need to revert to a backup if that doesn't work

**Comment by AlexIIL** [comment]
ok after looking into this this seems to be a bit of a deeper problem than the first fix,,,

**Comment by ZeroT01erance** [comment]
This is my first experience play with mods. And I do not understand much. Why did the texture disappear from these elements
![2017-05-16_22-13-21](https://cloud.githubusercontent.com/assets/17812947/26123870/308ea2be-3a85-11e7-89ae-513b4eec1f58.jpg)

**Comment by AlexIIL** [comment]
If this is your first time with mods then I can only recommend removing buildcraft: its still in alpha, which means that a lot of things aren't done yet or will crash your game or break your world in unexpected ways.

The texture issue is a bug with buildcraft (those items didn't exist in 7.99.0 so there wasn't anything to be broken. It was also a mistake on my part to register those items - they will be gone in 7.99.4).

**Comment by ZeroT01erance** [comment]
I backuped my world before. I will continue playing with 7.99.4, may be I found new bugs. Good luck :)
