### ISSUE TITLE
Filler not working

### ISSUE THREAD

**Issue by hbq0449** [BuildCraft/BuildCraft#3588]
![image](https://cloud.githubusercontent.com/assets/1421459/26166342/c1e0ab82-3b65-11e7-9c87-64cc80e2668e.png)
with bc 7.99.3 
forge 13.20.0.2296

interface has no pattern sellect.  
Hope it can be fixed next test version.

**Comment by AlexIIL** [comment]
*Currently* the filler must be placed next to a Volume Marker with the "Filling Planner" addon added to one of its corners. Both can be changed with the Marker COnnector.

This is temporary behaviour though, it will be changed soon (although probably not for 7.99.4 as that's a bit too close right now)

**Comment by AlexIIL** [comment]
Should be fixed in 7.99.8: https://www.mod-buildcraft.com/buildcraft-7998-alpha.html.
