### ISSUE TITLE
Crashes after placing diamond pipe (or connecting it to other pipe) 1.7.10

### ISSUE THREAD

**Issue by DingoFPS** [BuildCraft/BuildCraft#3589]
The title says it all 
[crash-2017-05-17_20.44.04-client.txt](https://github.com/BuildCraft/BuildCraft/files/1008752/crash-2017-05-17_20.44.04-client.txt)

**Comment by AEnterprise** [comment]
caused by optifine rendering hacks, nothing we can do about that

you could try using a different optifine version

**Comment by asiekierka** [comment]
Disabling everything pertaining to multicore rendering or chunk loading in OptiFine also helped, in my experience.
