### ISSUE TITLE
Minecraft blocks when loading

### ISSUE THREAD

**Issue by Hypsellis** [BuildCraft/BuildCraft#3590]
I don't why, but when BuildCraft is present, Minecraft always blocks when loading at the 6th step without generating any crash report. Here is the log https://pastebin.com/CmzQZv49

**Comment by AEnterprise** [comment]
we actually had someone talk to us about this on discord yesterday and it is an recipe sorting problem

@AlexIIL would the enum -> class change be enough to fix this or do we need to report this to forge as well?

**Comment by AlexIIL** [comment]
Its an issue where BuildCraft doesn't register the recipe with the sorter, and forge's default method will loop infinitely if it goes past all of its other defaults.

**Comment by Hypsellis** [comment]
It still doesn't work, the game still freeze while loading.

**Comment by AlexIIL** [comment]
Can you upload a new crash report?

**Comment by Hypsellis** [comment]
Ok it seems to work now, Curse had downloaded the old version. >___<
