### ISSUE TITLE
reworking the IItemhandler

### ISSUE THREAD

**Issue by loordgek** [BuildCraft/BuildCraft#3592]
hi

i am reworking the IItemhandler https://github.com/loordgek/itemhandlerV2/tree/master/src/main/java/loordgek/itemhandlerv2/itemhandler

if you have ideas plz put hem here https://github.com/MinecraftForge/MinecraftForge/issues/3344

**Comment by AEnterprise** [comment]
please use our discord for asking questions like this in the future, this is for tracking bugs

**Comment by loordgek** [comment]
ok to discord we go

**Comment by AEnterprise** [comment]
discord.gg/QZAtRuM

**Comment by loordgek** [comment]
ty
