### ISSUE TITLE
BuildCraft 7.99.3 Still no kinesis Pipes 

### ISSUE THREAD

**Issue by HardCostKill3R** [BuildCraft/BuildCraft#3593]
I've installed BuildCraft 7.99.3 for 1.11.2 and there are no Kinesis pipes and there are other missing items/ recipes.

**Comment by afdw** [comment]
Yes, still no kinesis pipes. Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3516 and https://github.com/BuildCraft/BuildCraft/issues/3523.
