### ISSUE TITLE
Looking at a pipe with a Tinkers hammer in hand causes client crash.

### ISSUE THREAD

**Issue by xannor** [BuildCraft/BuildCraft#3596]
I dont know if this is something Tinkers is doing wrong or something you guys did not expect.

Crash Report:
https://gist.github.com/xannor/33b122125b0b1e482145d20a8f409f92#file-crash-2017-05-20_21-04-42-client-txt

I have only had the issue with the hammer not with other tinkers tools, though I have not tested all of them. I can reload and as long as the hammer is not the first tool to come up or I look away quick enough I can work around it.

**Comment by AlexIIL** [comment]
Defiantly our bug: we shouldn't be accessing an array with an unknown index
