### ISSUE TITLE
Transport pipe Index out of range exception

### ISSUE THREAD

**Issue by Swornh** [BuildCraft/BuildCraft#3597]
The Setup: A Stirling engine direct facing a pump, above a lava lake, output direct into cobble stone fluid pipe, into tinkers smelter tank and "smelter tank".

working fine after empty the lake, then crash from nothing...
Game won't start again.

[crash-2017-05-21_01.52.34-client.txt](https://github.com/BuildCraft/BuildCraft/files/1016689/crash-2017-05-21_01.52.34-client.txt)

**Comment by afdw** [comment]
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3596.
