### ISSUE TITLE
Buildcraft 1.11.2 problem

### ISSUE THREAD

**Issue by Jik74** [BuildCraft/BuildCraft#3598]
when I'm playing minecraft version 1.11.2. then when i'm wating  the loading appear a message like this "Buildcraft Lib is missing mods or remove buildcraft lib.
forge 13.20.0.2296(but i'm using forge 13.20.0.2228)" and this is fml.latest log  https://drive.google.com/open?id=0BxXJGV63iQnURmZOUktFOFJfbDA) and sorry for my bad grammar :3

**Comment by afdw** [comment]
Log link looks broken. And can you post screenshot of your launcher settings?

**Comment by Jik74** [comment]
that was i'm reparing :3

**Comment by AEnterprise** [comment]
you need to update your forge to atleast .2296 like the message sais, BC won't work with anything older
