### ISSUE TITLE
Quarry not picking up dropped items 1.11.2

### ISSUE THREAD

**Issue by MoonCutter2B** [BuildCraft/BuildCraft#3599]
Not sure if this is a bug or a changed feature but I think I remember the quarry picking up any "extra" items  when breaking a block. E.g. picking up all dropped items when breaking a chest and stuff from mobs that die down there. I can see the drill head slowly pushing the items around but not picking them up.
1.11.2, latest Forge, my own build of 7.99.4 (no changes, just the build). SSP.

**Comment by AEnterprise** [comment]
since 7.99.4 doesn't exist please include the commit hash you used to build, there have been changes since 7.99.3 (probably won't impact but we like to know in case we do need the info)

also is this with any chest (including just a vanilla chest) or with other chests?

**Comment by LuigiHutch** [comment]
What? it should pick up an items in there which are thrown in by hand or collected from a broken chest.

**Comment by AEnterprise** [comment]
i'm just asking for the chest type because not all chests spawn in the items themselfs, some just return it as drops

**Comment by MoonCutter2B** [comment]
this was a vanilla singel chest, (from rogue like dungeons I think)
same happened when it broke a sun flower
and a saw it a dirt block - but I think that block was dropped down when I was leveling the area at the top.

**Comment by MoonCutter2B** [comment]
will build with latest (83cb3ba..349575c) and see what happens

**Comment by playhazard** [comment]
I have had the same experience with 7.99.3, I specifically placed wooden chests with items for the quarry to break as a test and the chests were collected but none of the items that were inside were picked up.
