### ISSUE TITLE
Game breaking bug, Vanilla Maps CTD around Oil [1.11.2][7.99.3]

### ISSUE THREAD

**Issue by playhazard** [BuildCraft/BuildCraft#3600]
Using vanilla maps in game causes a game breaking bug around oil deposits and can potentially break your save as well preventing you from reloading the game whilst still having the map in hand.

Luckily, I was able to swap my held item whilst the game was loading but on my test world to recreate the problem, it broke again and I was unable to reload it.

I haven't tested how the vanilla maps handle other buildcraft entities but could be a similar problem.

**Comment by AEnterprise** [comment]
can you please provide a crash log?

**Comment by LuigiHutch** [comment]
Already fixed in dev
