### ISSUE TITLE
The pump doesn't perform well over large bodies of fluids

### ISSUE THREAD

**Issue by PandaPaw** [BuildCraft/BuildCraft#3603]
Hi
Im using Buildcraft 7.99.3 and forge 13.20.0.2304.

I placed the pump in the Nether and started it with 4 redstone engins and the TPS droped down to 2 in like 5sec.

If you need/want more info just write it down and ill try my best to get it to you.

**Comment by AlexIIL** [comment]
Thanks! (No more info needed, I've reproduced it indev.)

**Comment by NerdCraft** [comment]
wow
![2017-05-23_20 24 33](https://cloud.githubusercontent.com/assets/13489837/26380619/01fdb2e8-3ff6-11e7-90e5-1681d21ab476.png)
![2017-05-23_20 25 03](https://cloud.githubusercontent.com/assets/13489837/26380618/01f0d6e0-3ff6-11e7-8bd0-6f45c1ce4f98.png)
