### ISSUE TITLE
Thank you developers.

### ISSUE THREAD

**Issue by tia79** [BuildCraft/BuildCraft#3605]
I have been wanting to try this for 1.11.2 for so many months. My dream is coming to a reality. I just wanted to let you guys know you are doing a good job so keep it up. Its more of a praise to you than a bug report but its needed to in a time like this :)

Much thanks

**Comment by AEnterprise** [comment]
first of al: thanks you for the thanks :) it is nice to see people apreciate all that the dev team has done

that being said this is an issue tracker and this isn't realy an issue so i'm gona have to close this but feel free to jump on our discord to have a chat ( discord.gg/QZAtRuM ) :)
