### ISSUE TITLE
1.11.2 Questions

### ISSUE THREAD

**Issue by Jigokusaru** [BuildCraft/BuildCraft#3612]
I do apologize for the inconvenience of this message but i do wish to know a few things.
1. Are gates not fully implemented? if so I might me miss using them, I tried to put a redstone engine next to it and it wasn't powered.
2.  Are conductive pipes removed or being added?
3.  Are the engines other then redstone not fully implemented?

**Comment by LuigiHutch** [comment]
As of 7.99.3:
1) Gates aren't fully implimented but are there and can be used but are missing a fair few actions/triggers
2) KINESIS pipes are not implimented and will be reimplimented in a future alpha
3) All the engines are implimented, they have a few issues but work for the most part

**Comment by AEnterprise** [comment]
please use our discord ( discord.gg/QZAtRuM ) or irc channel (#buildcraft) for questions like this in the future
