### ISSUE TITLE
7.99.4: Gates do note out put a redstone signal

### ISSUE THREAD

**Issue by Jigokusaru** [BuildCraft/BuildCraft#3613]
![screenshot1](https://cloud.githubusercontent.com/assets/23660999/26468381/34a7ad1a-4164-11e7-911d-201cbd3b9e22.png)
![screenshot2](https://cloud.githubusercontent.com/assets/23660999/26468596/10d550d0-4165-11e7-809a-eeaee008afc9.png)

The gate does not out put a signal even though conditions are met and redstone is selected as the action.

**Comment by Elec332** [comment]
This is still an issue on 7.99.4

**Comment by AEnterprise** [comment]
yeah nobody looked at this yet, i might once i'm done with tinkering with the builder

**Comment by AlexIIL** [comment]
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)
