### ISSUE TITLE
The conductive pipes are not  there.

### ISSUE THREAD

**Issue by heylljnf** [BuildCraft/BuildCraft#3615]
When I try to craft the conductive pipes, they won't show up and I cannot craft them.

**Comment by LuigiHutch** [comment]
Duplicate of: https://github.com/BuildCraft/BuildCraft/issues/3593, https://github.com/BuildCraft/BuildCraft/issues/3523, https://github.com/BuildCraft/BuildCraft/issues/3540 and https://github.com/BuildCraft/BuildCraft/issues/3612

**Comment by AlexIIL** [comment]
(They haven't been finished yet)
