### ISSUE TITLE
7.99.3|1.11.2 Stirling Engine eats buckets.

### ISSUE THREAD

**Issue by Jigokusaru** [BuildCraft/BuildCraft#3619]
I was using the Stirling Engine to power the Distiller, and when i added a bucket of lava to the engine the bucket was removed from the input slot.

**Comment by AlexIIL** [comment]
Its fixed in a seperate branch, it should be pushed soon-ish

**Comment by Jigokusaru** [comment]
Separate branch? not sure what that means but ok.

**Comment by AEnterprise** [comment]
@Jigokusaru it just means he has done it but the code has not been pushed to github

**Comment by AlexIIL** [comment]
Fixed in main. Basically it will defiantly be included in 7.99.4 now.
