### ISSUE TITLE
blocks not available after update to latest version (v1.7.10)

### ISSUE THREAD

**Issue by Boarschti42** [BuildCraft/BuildCraft#3621]
I recently installed latest buildcraft mod for v1.7.10 (Modlist later). After this update of the mod, some recepies are no longer working as expected (for example Underground biomes constructs Rhyolite cobblestone to Rhyolite cobble slab). Before installing this update (i had some other issues before) all worked as expected. After installation, i just get a cobblestone slab.
If we just remove buildcraft, all works fine again. 

Here is the (litte large) modlist:

- AncientTrees-1.7.10-1.6.4.jar
- animalsPlus-1.2.jar
- antiqueatlas-1.7.10-4.2.10+BOP.jar
- AppleCore-mc1.7.10-1.1.0.jar
- appliedenergistics2-rv3-beta-6.jar
- AutoSapling-1.1.jar
- backpack-2.0.1-1.7.x.jar
- BetterFoliage-MC1.7.10-2.0.4.jar
- BiblioCraft[v1.11.5][MC1.7.10].jar
- BiblioWoods[BiomesOPlenty][v1.9].jar
- BiblioWoods[ExtraBiomesXL][v1.4].jar
- BiomesOPlenty-1.7.10-2.1.0.2027-universal.jar
- Bookshelf-1.7.10.jar
- buildcraft-7.1.21.jar
- buildcraft-compat-7.1.6.jar
- Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar
- ChickenChunks-1.7.10-1.3.4.19-universal.jar
- Chisel-2.9.5.11.jar
- CodeChickenCore-1.7.10-1.0.7.47-universal.jar
- CoFHCore-[1.7.10]3.1.4-329.jar
- CustomMobSpawner 3.3.0.zip
- CustomNPCs_1.7.10d(21feb16).jar
- Decocraft-2.3.6.1_1.7.10.jar
- DrZharks MoCreatures Mod v6.3.1.zip
- EasyCrafting-1.7.10-2.0.1.16.jar
- EnchantingPlus-1.7.10-3.0.2-d.jar
- extrabiomesxl_1.7.10-3.16.2.jar
- ExtraButtons-1.7.10.1.jar
- ExtraCells-1.7.10-2.3.14b197.jar
- Farseek-1.0.11.jar
- GardenStuff-1.7.10-1.7.0-fixed-textures.jar
- Gravestone-Mod-1.7.10.jar
- GUIAPI-1.0.5.jar
- GUILib.jar
- hopperductmod-1.7.10-1.3.2.jar
- HungerOverhaul-1.7.10-1.0.0.jar
- InventoryTweaks-1.59-dev-152.jar
- KoreSample-1.7.10-1.3.2.jar
- liteloader-1.7.10.jar
- LitWR-1.7.10-1.0.8.jar
- Mantle-1.7.10-0.3.2b.jar
- MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar
- mod_MAtmos_29ub4_mc1.7.10.litemod
- NotEnoughItems-1.7.10-1.0.5.120-universal.jar
- Pam's HarvestCraft 1.7.10Lb-fixed-textures.jar
- plantmegapack-4.33-1.7.10-1492.jar
- RecipeAPIv1.1.jar
- RedstonePasteMod-1.7.10-1.6.2.jar
- ruins.txt
- ruins_log.txt
- Ruins-1.7.10-15.4.1.jar
- secretroomsmod-1.7.10-4.7.1.null.jar
- ShadersModCore-v2.3.31-mc1.7.10-f.jar
- SimpleRefinement-mc1.7.10-1.0.jar
- StorageDrawers-1.7.10-1.9.4.jar
- StorageDrawers-BiomesOPlenty-1.7.10-1.1.1.jar
- Streams-0.1.6.jar
- TConstruct-1.7.10-1.8.8.jar
- Thaumcraft-1.7.10-4.2.3.5.jar.deactivated
- ThermalDynamics-[1.7.10]1.2.1-172.jar
- ThermalExpansion-[1.7.10]4.1.5-248.jar
- ThermalFoundation-[1.7.10]1.2.6-118.jar
- UndergroundBiomesConstructs-1.7.10-0.8-beta49.jar
- VeganOption-mc1.7.10-0.2.0.jar
- Waila-1.5.10_1.7.10.jar

**Comment by AEnterprise** [comment]
buildcraft doesn't modify recipes or anything so very unlikely that BC is the root cause, also MC 1.7.10 is extremely outdated and has almost no support

you might want to check your logs for errors that might explain the missing recipes

and for future reference: if you provide a modlist please make it a list, not a wall of text that is extremely hard to read

**Comment by Boarschti42** [comment]
Thank you for your answer!
I Updated the mod list. Why 1.7.10.. I dont know if you ever heard about "life in the woods", a modpack. 
I just updated all mods to the latest version. I send this issue here, because it happened after the update of this mod, I think it is a cross reference, but there is no error or something like this in the logs. Nothing that points to this.

**Comment by AEnterprise** [comment]
The modpack doesn't matter, 1.7.10 still remains equally outdated

I agree that this is a cross mod issue, but without logs or stacktraces that point to a part of BC this is extremely hard to track down so i'm afraid we will not be able to help you with this as it we have already moved up 4 MC versions

**Comment by AlexIIL** [comment]
@AEnterprise 1.7.10 isn't obsolete until 8.0.x is released as stable actually.

@Boarschti42 can you try downgrading buildcraft to the last version? It might be that you updated more than just buildcraft.

**Comment by Boarschti42** [comment]
@AlexIIL I tried downgrading buildcraft (from 7.1.21 to 7.1.20) and the crafting works. I had another issue i cannot remember anymore before updating buildcraft. So it seems, that there is an issue after updating. 
Do you have an idea?

**Comment by AlexIIL** [comment]
That's strange. If you don't run into any of the issues fixed in 7.1.21 (https://mod-buildcraft.com/buildcraft-7121.html) then the simplest solution will be to stay on 7.1.20.

Alternatively you could try to narrow down the mods that interact to cause this by removing a few mods at a time and seeing if the problem goes away - if it does then it is likely to be related to one of them.
