### ISSUE TITLE
Quarry doesn't checks for blocks in prev dug area

### ISSUE THREAD

**Issue by Goofybud16** [BuildCraft/BuildCraft#3622]
I ran into the following issue: 

* Build a quarry, engines, etc and let it dig a few layers
* Stop it
* Fill the first layer it dug down
* Start it

The quarry will keep digging where it left off, resulting in the arm/head phasing through solid blocks. It waits until it finishes the layer to go back up and get the blocks on the top layer.

This is on Alpha 7.99.3/MC 1.11.2.

**Comment by afdw** [comment]
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html).
