### ISSUE TITLE
Quarry Duplicates Shulker Boxes

### ISSUE THREAD

**Issue by Goofybud16** [BuildCraft/BuildCraft#3623]
This was tested on BC 7.99.3 w/ MC 1.11.2.

To reproduce:

* Place a quarry, engines, pipes to a chest.

* Place a Shulker Box within the area that the Quarry will mine.

* Start the quarry.

When the quarry mines the shulker box, it will both drop it and send it down the pipe to the chest. The box which ends up in the chest does not have the contents, however the one dropped on the ground does. Both shulker boxes, however, are valid (usable) items, effectively duplicating the shulker box.

**Comment by AEnterprise** [comment]
Since I'm done with the autocrafting mind if I take a look at this tomorrow?
