### ISSUE TITLE
Hand Rendering Incorrect after Quarry Placed

### ISSUE THREAD

**Issue by Goofybud16** [BuildCraft/BuildCraft#3624]
BC 7.99.3 + 7.99.4 / MC 1.11.2

Screenshots showing problem: http://imgur.com/a/sJ7e5

Once a quarry is placed, held items will "phase through" blocks when you are close enough to said block. Removing the quarry makes this issue go away.

[Mods](https://gist.github.com/Goofybud16/ba138157e5a74064169f94836a3c4066)

[Specs](https://gist.github.com/Goofybud16/50376faedf7d0f5fb35f29749b204e20)

**Comment by AEnterprise** [comment]
can you remove optifine and see if the bug persists?

**Comment by Goofybud16** [comment]
I just checked, the issue does not appear with Optifine removed.

**Comment by AEnterprise** [comment]
you'll have to report it on the optifine issue tracker then to get this fixed as optifine messes with rendering we can't fix it from our end

**Comment by asiekierka** [comment]
@sp614x

**Comment by sergigb2012** [comment]
I turned the optifine option FAST RENDER: OFF and the bug is aparently fixed

**Comment by ohusq** [comment]
This still issue still exists in **2026** and disabling fast render turned my screen into black pixels of different colors.

**Comment by asiekierka** [comment]
OptiFine modifies Minecraft's rendering pipeline in undocumented ways. Without sp614x's assistance, there is very little we can legally do to fix or debug issues it introduces, no matter whether it's 2017 or 2026.

**Comment by BigGame2004** [comment]
Only thing I can really say is that some of optifine's graphics settings will mess with the way BC renders's it's pipes and engines, can't tell you which does what but resseting OF's setting back to default and only re-enabling the stuff you want one by one is your best bet.
