### ISSUE TITLE
[1.11.2][7.99.3] Facade Crash on start

### ISSUE THREAD

**Issue by Tencao** [BuildCraft/BuildCraft#3627]
https://paste.ee/r/zPu7t

Forge version - 13.20.0.2308
Buildcraft build - 7.99.3

Summary of crash - Crashes on load due to nullpointer on isValidFacadeState in buildcraft transport module.

**Comment by AEnterprise** [comment]
looks like we are checking properties of another block that is eigther returning null in it's list of valid states or null as block for that state

i'll add some safety checks to prevent this in the future (with logging the offender so it can be fixed at the source) in a bit

**Comment by Devilswarchild** [comment]
Forge Version- 13.20.0.2309
BC Build 7.99.3

Summary of Crash - Crashes almost halfway through Forge load...

attached is the crash report
[crash-2017-05-29_15.28.55-client.txt](https://github.com/BuildCraft/BuildCraft/files/1036609/crash-2017-05-29_15.28.55-client.txt)

**Comment by AlexIIL** [comment]
@Devilswarchild can you open a new issue with that crash? This is a different crash...

**Comment by Tencao** [comment]
Sadly this bug is still a thing

https://paste.ee/r/lTYg6

Build 7.99.4

**Comment by AlexIIL** [comment]
Looks like be error handling code didn't work quite right: it was meant to say which block caused that crash

**Comment by AEnterprise** [comment]
does this issue still heapen? if so please provide a new crashlog (old one has expired)

**Comment by Tencao** [comment]
I've been running the latest 1.12 build and no, I have not experienced this since.
