### ISSUE TITLE
API dependency crash

### ISSUE THREAD

**Issue by AlexIIL** [BuildCraft/BuildCraft#3628]
Original report by @Devilswarchild

Forge Version- 13.20.0.2309
BC Build 7.99.3

Summary of Crash - Crashes almost halfway through Forge load...

attached is the crash report
[crash-2017-05-29_15.28.55-client.txt](https://github.com/BuildCraft/BuildCraft/files/1036609/crash-2017-05-29_15.28.55-client.txt)

**Comment by AlexIIL** [comment]
@Devilswarchild can you please upload the entire log? It has some additional useful information that we need to determine which mod is shipping the old BC API.

**Comment by AlexIIL** [comment]
(Specifically we need the "fml-client-latest.log file)

**Comment by Devilswarchild** [comment]
[fml-client-latest.zip](https://github.com/BuildCraft/BuildCraft/files/1036720/fml-client-latest.zip)

**Comment by AlexIIL** [comment]
Thanks

**Comment by AlexIIL** [comment]
You seem to have a lot of 1.7.10 or 1.8.9 only mods installed - can you try removing them (or disabling them) as they might be causing the issue. [list here](https://gist.github.com/AlexIIL/73b46c9a0632d25ece043aa637ba75d8).

**Comment by Devilswarchild** [comment]
that shouldn't have worked.... cause as far as i know those mods I removed are still technically working and I would hate to have to leave them out of my mods list

**Comment by AlexIIL** [comment]
Mods that are built for 1.7.10 or 1.8.9 won't work on 1.11.2 unfortunately. Forge seems to be removing them early from the mod list (as the modid now needs to be lowercased as of 1.11.2) so they might have worked before.

That being said you have older versions of some mods that have been updated to 1.11.2, although I don't know which versions are the latest with which ones.

**Comment by Devilswarchild** [comment]
well dynamic lights is the newest version for 1.11.2

**Comment by AlexIIL** [comment]
I don't think that's a list of only the mods that are from a different version actually, it looks like its also got a few more. Its a bit strange that dynamic lights is there actually.

**Comment by Devilswarchild** [comment]
indeed it is

**Comment by Devilswarchild** [comment]
is there anyway to code Bc to ignore those mods so to speak so that they dont conflict with it?

**Comment by AlexIIL** [comment]
We can't - however if you opened the jar files of those mods and removed the folder "buildcraft/api" then they wouldn't override the BC API. This does men that you have to go through every jar in your mod folder  individually though. You might want to start with the ones that are in the [list](https://gist.github.com/AlexIIL/73b46c9a0632d25ece043aa637ba75d8).

**Comment by Devilswarchild** [comment]
and how would I open said ".jar" files?

**Comment by liach** [comment]
Use decompressing apps like 7zip or winrar

**Comment by AlexIIL** [comment]
What operating system are you using?

(Any program that can open and edit ".zip" files will be able to open it - a workaround is to rename "file.jar" to "file.zip" and then windows will open it automatically)

**Comment by LuigiHutch** [comment]
Just make a copy of your instance then remove the mods that aren't for 1.11.2. It would be a whole lot simpler

**Comment by Devilswarchild** [comment]
Im using windows 10 pro

**Comment by Devilswarchild** [comment]
so ive gone from the top of the list and binnies mods is the only one with a buildcraft/api folder

**Comment by Devilswarchild** [comment]
and simpleting that folder isnt going to mess up the mod is it?

**Comment by AlexIIL** [comment]
It *might* do - so to be on the safe side you might want to make a copy of it somewhere if it messes things up

**Comment by Devilswarchild** [comment]
lol
too late for that. but i can always go redownload that version if need be

**Comment by Devilswarchild** [comment]
also none of the others from that list have a bc folder...so it was just binnies mod

**Comment by Devilswarchild** [comment]
so i deleted that from binnie mods...tried it again...still crashed. put the others back in and yet it still crashed...wth

**Comment by Devilswarchild** [comment]
nvm figured out what the problem was....stupid windows...I didnt tell you to add "copy.jar" files to the folder

**Comment by Devilswarchild** [comment]
also found an updated copy of binnie mods as well

**Comment by Devilswarchild** [comment]
yup the "binnie-mods-2.0-pre14" file did the trick. bc nolonger crashes

**Comment by Devilswarchild** [comment]
now to take the time and go through all the ones that work and see if there are any newer files lol

**Comment by AEnterprise** [comment]
if you realy want to have mod files for different MC versions in the same folder make subfolders named after the MC version they should be loaded in

forge will load all mods that are directly in the mods folder and if there is a subfolder who's name matches the MC version you are starting it will also load the mods in that folder (but not from folders for a different MC version)
