### ISSUE TITLE
Cannot See Quarry Head until you Look at the Frame

### ISSUE THREAD

**Issue by Goofybud16** [BuildCraft/BuildCraft#3630]
When you first load into a world, if you are looking at a quarry's mining head (but not the frame), it will not appear visually. The blocks will still break, but the head will not appear. It does appear once you look at the frame, however.

[Screenshots](https://imgur.com/a/Z7vx6)

Version 7.99.4 | MC 1.11.2

[Mods](https://gist.github.com/Goofybud16/ba138157e5a74064169f94836a3c4066)

[Specs](https://gist.github.com/Goofybud16/50376faedf7d0f5fb35f29749b204e20)

**Comment by AEnterprise** [comment]
seems this issue was overlooked but its not heapening from what i see so most likely it's optifine messing with things
