### ISSUE TITLE
Cannot Open Combustion Engine UI While Holding Item

### ISSUE THREAD

**Issue by Goofybud16** [BuildCraft/BuildCraft#3631]
When holding any item (even items which may not be inserted into a combustion engine, such as a pickaxe), right clicking the combustion engine will do nothing other than swing the held item. The Sterling engine will open the UI when holding an item, however.

7.99.4 / 1.11.2

[Mods](https://gist.github.com/Goofybud16/ba138157e5a74064169f94836a3c4066)

[Specs](https://gist.github.com/Goofybud16/50376faedf7d0f5fb35f29749b204e20)

**Comment by MissPotato** [comment]
Strangely, in 7.99.4 you can open the interface if you right click on the engine with a pipe and the pipe can not be placed on that side. (Ie: Right clicking south side where you have a lever with pipe in hand.)

**Comment by AlexIIL** [comment]
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)
