### ISSUE TITLE
Fail on Open interfaces

### ISSUE THREAD

**Issue by Mxater** [BuildCraft/BuildCraft#3636]
I using BuildCraft 7.99.4 in MC 1.11.2, and when I open any interface like crafting table, option menu. The game crash. 
This don't happen with BC 7.99.3

[crash-2017-05-31_17.10.27-client.txt](https://github.com/BuildCraft/BuildCraft/files/1042953/crash-2017-05-31_17.10.27-client.txt)

**Comment by afdw** [comment]
Please update JEI.

**Comment by Mxater** [comment]
Greats, Works.
Thanks.
