### ISSUE TITLE
Mining Well can't connect to Wooden pipe

### ISSUE THREAD

**Issue by Mxater** [BuildCraft/BuildCraft#3637]
I using BuildCraft 7.99.4 in MC 1.11.2, I try to connect a Wooden pipe With a Mining Well, but this dont work.
With another machines its works.
Mining Well
![2017-05-31 17_31_49-minecraft 1 11 2](https://cloud.githubusercontent.com/assets/4630666/26655157/97d3a656-4627-11e7-9478-a1ee1ae888ea.png)
Quarry
![2017-05-31 17_32_08-minecraft 1 11 2](https://cloud.githubusercontent.com/assets/4630666/26655158/992a91e0-4627-11e7-9972-eb4ab6095c06.png)

**Comment by AlexIIL** [comment]
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)
