### ISSUE TITLE
[7.1.22] Missing localization

### ISSUE THREAD

**Issue by TheAndrey** [BuildCraft/BuildCraft#3638]
I downloaded the latest version from the website and there's no localizations.
![default](https://cloud.githubusercontent.com/assets/6772452/26700579/275c38a0-471e-11e7-8d92-92422af84b9d.png)

**Comment by AlexIIL** [comment]
Oh right, I forgot that I changed the way lang builds in 1.8+ and so didn't include it when I built 7.1.22. I'll push a fix shortly

**Comment by AlexIIL** [comment]
Fixed on the site (a little while ago) and on curseforge (just now)
