### ISSUE TITLE
crash at rendering screen

### ISSUE THREAD

**Issue by Hypsellis** [BuildCraft/BuildCraft#3639]
I get this crash randomly while playing. https://pastebin.com/MhwTuvxt
I use Minecraft 1.11.2, Forge 13.20.0.2310, BuildCraft 7.99.4.

**Comment by afdw** [comment]
It's NEI bugs, it passes `null` to `@Nonnull lItemStack stack`.

**Comment by Hypsellis** [comment]
So I should report to NEI.

**Comment by afdw** [comment]
Probably yes.

**Comment by AEnterprise** [comment]
closing as this is an NEI bug, see the issue on their end for when it would be fix
