### ISSUE TITLE
Quarry can't work with other power sources (1.11.2 ; 7.99.4)

### ISSUE THREAD

**Issue by djkir** [BuildCraft/BuildCraft#3641]
I tried to attach the Converter of forestry and wires from other mods and the quarry is not working. But if to connect directly the original engines from buildcraft quarry working. I haven't found the original electrical wires in buildcraft

**Comment by AEnterprise** [comment]
At present time BC only works with it's own power system (MJ) so is not compatible with forestry or other mods that use RF, FE or similar

I assume that you are refering to the kinetic pipes when you say "electrical wires in buildcraft", those have not been ported yet and are being worked on
