### ISSUE TITLE
[1.11.2] 7.99.4 Crash after POSTInit

### ISSUE THREAD

**Issue by Terpo** [BuildCraft/BuildCraft#3644]
BC 7.99.4 with Forge 2304
full modlist https://gist.github.com/Terpo/333becf5ecdf70f4389c668ba0279c85
crashlog: https://gist.github.com/Terpo/b74cb3830121d20d7890f367b8aab5a7

Does only happen on the client instance, not on the server.

**Comment by AlexIIL** [comment]
I *want* to say that this is a duplicate (as I've seen that crash before), however I can't find it. This was fixed in https://github.com/BuildCraft/BuildCraft/commit/e808136fce52d921d7645368994d17bc039df0f3, and will be fixed publicly whenever 7.99.5 is released.

**Comment by Terpo** [comment]
Thanks, was trying to find a duplicate but could not find one. If its already fixed in dev I will try to bake my own version of bc for the moment :)

**Comment by AlexIIL** [comment]
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)
