### ISSUE TITLE
[1.11.2] 7.99.4 Crash when clicking a pipe with wrench

### ISSUE THREAD

**Issue by LeoN3K0** [BuildCraft/BuildCraft#3645]
Every time I use wrench on any type of pipe I crash, here is report. [crash-2017-06-02_23.55.39-client.txt](https://github.com/BuildCraft/BuildCraft/files/1049400/crash-2017-06-02_23.55.39-client.txt)

**Comment by AEnterprise** [comment]
it looks like one of the other mods you have installed is shipping an outdated version of the BC api causing BC to try to use a method that doesn't exist in the older API that got loaded as a result

please check the jars of the mods you have installed looking for any buildcraft api folders inside and remove them. If you find the mod that was shipping the outdated api please ask that mod to stop shipping the api

**Comment by AEnterprise** [comment]
closing as there is nothing we can do about this from our end
