### ISSUE TITLE
Millenare - Buildcraft conflict

### ISSUE THREAD

**Issue by Link-Jon** [BuildCraft/BuildCraft#3646]
I don't know if anyone has said this yet so ima say it, Millenare and Buildcraft have clashing ids..... idk if you would actually re-update like 1.7.10 (cuz that's where I know it exsists and now that I think about this post is rlly stupid... sorry about that. but anyone making a personal modpack like me ull have to manually change the ids. I did that once before and they worked perfectly

**Comment by AlexIIL** [comment]
Which ID's are clashing? What BC version, MC version, and Millenare version are you using?

**Comment by AEnterprise** [comment]
@Link-Jon please provide the required info or i will have to close this due to lack of information

**Comment by AEnterprise** [comment]
closing due to lack of information
