### ISSUE TITLE
[1.11.2]The game crash when trying to make a wooden gear

### ISSUE THREAD

**Issue by MerryLeo** [BuildCraft/BuildCraft#3649]
I'm playing on a server with my friends. And my game crash every time I try to make a wooden gear in survival mode the game crash and says "The game crashed whilst rendering screen". The server is using Buildcraft 7.1.22. I noticed that it only does this in multiplayer. I would like to know if it's just the server that has a problem. 

Here's the log; [crash-2017-06-04_15.36.27-client.txt](https://github.com/BuildCraft/BuildCraft/files/1050657/crash-2017-06-04_15.36.27-client.txt)

Here's the list of mod that the server is using; [modslist.txt](https://github.com/BuildCraft/BuildCraft/files/1050659/modslist.txt)

There was nothing in the server log.

**Comment by afdw** [comment]
BuildCraft 7.1.22? It's not, you're running 7.99.4.

**Comment by MerryLeo** [comment]
Yeah, I should have been more specific, I'm using 7.99.4. The server is running 7.1.22.

**Comment by AEnterprise** [comment]
euh no that's not how this works, you cannot be running 7.1.22 and connecting to a server running 7.99.4

**Comment by MerryLeo** [comment]
That's just it. I think my friend simply took another version of buildcraft. I'm gonna try again with the correct version.

**Comment by AEnterprise** [comment]
he took another version? so he is trying to run 7.1.22 on a MC 1.11.2 server? if that's the case the mod will just be rejected on loading and not load at all, hence the crash, you are crafting an item that doesn't exist on the server

**Comment by MerryLeo** [comment]
Yeah, I don't know how the mod even ran.

**Comment by AEnterprise** [comment]
simple: it didn't. ask your server admin to install the correct BC version and you should be fine

**Comment by MerryLeo** [comment]
Well, sorry for wasting your time guys.
