### ISSUE TITLE
[crash, server] Building oil Station in oil field.

### ISSUE THREAD

**Issue by kjl2875** [BuildCraft/BuildCraft#3650]
forge-1.11.2-13.20.0.2312-universal.jar

seed: 5654556177424684123

[crash-2017-06-05_10.44.04-server.txt](https://github.com/BuildCraft/BuildCraft/files/1050914/crash-2017-06-05_10.44.04-server.txt)

![2017-06-05_10 53 24](https://cloud.githubusercontent.com/assets/29188361/26767774/e2f95aa4-49dd-11e7-850f-80aca88f4dfe.png)

**Comment by AEnterprise** [comment]
it looks like the watchdog killed your server because it was not responding. Currently the pump can have a major impact on your tps so it probably lagged your game to death

**Comment by kjl2875** [comment]
Understand. I will be careful cycle structure.

OIL PUMP->Oil->X
X.1->OilEngine
X.2->OIL TANK
WATER PUMP->WATER->OilEngine
(OilEngine words in same OilEngine.)

**Comment by AEnterprise** [comment]
the issue mainly is that your water pump is hooked directly to the massive ocean so the determining of what blocks to try and such up is getting out of control: it is kinda scanning the entire ocean (or most of it) :P that just eats up so much ticktime your server is having issues

as a workaround you might want to try making a 3x3 infinite source and put the pump over that for now

**Comment by kjl2875** [comment]
OK. Works well.
![screenshot](https://cloud.githubusercontent.com/assets/29188361/26784830/7fdadca6-4a3a-11e7-8bec-14beb05ae3fa.jpg)

**Comment by AlexIIL** [comment]
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)
