### ISSUE TITLE
conflict with Biomes O' Plenty

### ISSUE THREAD

**Issue by Hypsellis** [BuildCraft/BuildCraft#3657]
There is a conflict between BOP and BuildCraft which causes Minecraft to crash when creating a world https://pastebin.com/3kiPeg42

**Comment by Hypsellis** [comment]
Oh it seems this issue has been reported already, sorry for having reported it again, I close this one.

**Comment by AEnterprise** [comment]
does this heapen every time when generating a new world? if so then it is not the same as #3640 
if it is heapening every time you want to report it to BOP as then they are parsing an invalid biome ID to generate terrain

**Comment by Hypsellis** [comment]
Yes it happens at each generation with Biomes O' Plenty 6.1.0.2239 and upper versions.

**Comment by AEnterprise** [comment]
yes this is an issue in BOP itself, BC is crashing because they are triggering worldgen with a biome ID that doesn't exist
