### ISSUE TITLE
Where is the old 1.10.2 branch?

### ISSUE THREAD

**Issue by Fungie2134** [BuildCraft/BuildCraft#3659]
Anything is in the title, I would like to try updating it.

**Comment by AEnterprise** [comment]
as i said on your comment on the other issue: there is no old 1.10.2 branch, we skipped that and went straight to 1.11.2, you will need to start from the 8.0.x branch and backport

**Comment by asiekierka** [comment]
Nonono.

There is an old 1.10.2 branch - you'd have to find the right commit in the 8.0.x branch, but you'd be missing so many bugfixes and content it'd probably be easier to backport from latest.

**Comment by Fungie2134** [comment]
I tried it, and yes I think it will be easier to start from the 1.11.2 branch.
