### ISSUE TITLE
[1.11.2] Crafttweaker support for Assembly Table

### ISSUE THREAD

**Issue by Skillotic0703** [BuildCraft/BuildCraft#3665]
Could you add crafttweaker support for the assembly table please?

**Comment by AlexIIL** [comment]
Not until we are at a stable release, and then it will be going into compat. However with 1.12 having custom recipes its likely they we'll be able to move assembly table recipes into JSON, so crafttweaker support is unlikely.

**Comment by Skillotic0703** [comment]
Ok thank you for answer!
