### ISSUE TITLE
[1.11.2] 7.99.4 Distiller bucket insertion 

### ISSUE THREAD

**Issue by MissPotato** [BuildCraft/BuildCraft#3666]
When right clicking on the distiller, the liquid is placed as a block next to the side of user's interaction. This empties the bucket, but does not insert the fluid into the distiller. Which is the opposite of happens with the Combustion Engine. 

Edit: Can reproduce with only buildcraft installed.

**Comment by AEnterprise** [comment]
this has been adressed in 7.99.8
