### ISSUE TITLE
7.99.4 diamond pipes

### ISSUE THREAD

**Issue by Raghalin** [BuildCraft/BuildCraft#3667]
I've noticed that String, Arrows, and Spider Eye will not always be properly sorted.
I have a diamond sorter pipe set up with blue and green sorted outputs, and yellow flow through.
the items will randomly go in any of the 3 directions even when set as blue.

does not cause crash (i think, hasn't happened anyways)

**Comment by AlexIIL** [comment]
Can you screenshot your diamond pipe GUI and in-world and put them here? I can't reproduce in dev.

**Comment by Raghalin** [comment]
not sure if it's #1 trying to piss me off due to knowing I'm sitting here ready to F2, or #2 because i realized that I had set green and blue as outputs while green was actually the input with blue and black being outs, with yellow as pass through. 

when i had green as output, items would enter, but after that particular sorter, the items labeled with a green would be tossed in random directions with other sorters even when they didn't have the itemex having only Granite on a blue would also let bone or arrows into the chest

**Comment by AEnterprise** [comment]
cannot reproduce this, this eighter got fixed or there is information missing, if you can still make this heapen please provide screenshots of your setup and settings
