### ISSUE TITLE
Distiller input not extractable

### ISSUE THREAD

**Issue by sanyo111** [BuildCraft/BuildCraft#3669]
The distiller doesnt work well, i cannot take out the oil

**Comment by LuigiHutch** [comment]
Can you explain more what you are trying to do? Also post some screenshots of your setup please!

**Comment by MissPotato** [comment]
I ran into the the same problem. Kind of related to #3666 the distiller just doesn't like buckets in general. If my assumption is correct - they mean they can't extract the raw oil from the input using buckets.

**Comment by xpatryk89** [comment]
3 months and it now too dont work

**Comment by AEnterprise** [comment]
making the input of a distiller extractable is not a high priority right now, there are other things being worked on. i personaly also don't see much use for extracting the input, if you didn't want to process it, why did you put it in the distiller in the first place?

**Comment by dj3520** [comment]
Accident? Or perhaps you're attempting to use a distiller for multiple fluids instead of making multiple distillers.

**Comment by AEnterprise** [comment]
accident would be one use indeed i didn't think of (derp)

as for the using multiple fluids: you can already do that quite easely, currently the distiller only accepts inputs if it's fully processable (so only in amounts that do not leave any fluid in the input tank)

if you use a clay pipe for the insertion and an overflow tank (or 2 depding on how much steps you want to do in a single one) and setup a system where any overflow that isn't accepted at that time by the distiller can be collected (and is then extracted after x seconds or when the distiller is ready to accept again)

**Comment by dj3520** [comment]
Let's say I do the most complex refining, reusing the same distiller. That should be upwards of 4 different fluids being cooled or heated. But let's also say I intend to switch what I'm using to heat/cool as well, reusing hot/cool products as well. Something complicated like that is bound to run into a situation where there isn't enough to process all of what you have, leaving you a bit of extra. That extra gets stuck, and currently requires breaking and replacing the ends of the distiller.

**Comment by AEnterprise** [comment]
@dj3520 the distiller is a single block, i assume you mean the heat exchanger? that's an entirely different thing

**Comment by dj3520** [comment]
whoops, yes I do

**Comment by AlexIIL** [comment]
Fixed in https://github.com/BuildCraft/BuildCraft/commit/8da8232151add3365128df40873fcecd601a03c4 and https://github.com/BuildCraft/BuildCraft/commit/e9ae26fc482cd8ceaab9e4d7f7f3d7d1ccb3fffb (So now the distiller + heat exchanger can be interacted with buckets, and drop the contained fluids when broken)

**Comment by AlexIIL** [comment]
Should be implemented in 7.99.8: https://www.mod-buildcraft.com/buildcraft-7998-alpha.html.
