### ISSUE TITLE
[SMP] Quarry not picking up any blocks

### ISSUE THREAD

**Issue by Zayyir** [BuildCraft/BuildCraft#3670]
[Screenshot](http://prntscr.com/fjec2m)
In multiplayer it doesn't pick up anything, drops, blocks, items, anything.

Mods installed:
- IC2
- Buildcraft
- Biomes O' Plenty
- Energy Converters

**Comment by AEnterprise** [comment]
what version of minecraft and buildract are you running? also is this on a reguar forge server or running bukkit/spigot/sponge/... ?

**Comment by Zayyir** [comment]
1.11.2 Forge server with spongeforge as one of the mods on the server (forgot to add that my bad), using the 7.99.4 release version on the website

**Comment by afdw** [comment]
Can you try to remove SpongeForge?

**Comment by Zayyir** [comment]
Well, that worked, it's okay now, can there be possible compatibility?

**Comment by AEnterprise** [comment]
@Zayyir sorry missed your question earlier: for compat you'll want to talk to the spongeforge devs, they are changing things that prevents the quarry from getting the drops. Once the quarry picks up drops on the ground again it will be less of a problem as well
