### ISSUE TITLE
Game freeze when placing quarry

### ISSUE THREAD

**Issue by Xander0406** [BuildCraft/BuildCraft#3671]
when i place a quarry in my world it freezes minecraft and I have to open task manager and quit it.

**Comment by AEnterprise** [comment]
What BC and MC version is this? Also if it heapens again could you collect and upload a threaddump with a tool like visualVM?

**Comment by Xander0406** [comment]
It is version 1.11.2 buildcraft version 7.99.4 alpha but I found out the problem was that optimize was outdated. I don't know how optimize caused it
