### ISSUE TITLE
7.99.4 Diamond Pipe WildCard Sorting does not work.

### ISSUE THREAD

**Issue by thefrasca** [BuildCraft/BuildCraft#3674]
When using diamond pipe for filtering and leaving 1 open path for wildcard, the wildcard items (items not explicitly listed on the pipe UI) go to a random exit.

I have tested this with 1 cobble stone in each row as well as the config below.  This appears to be true when only 1 explicitly defined exit is defined as well.

![2017-06-15_14 57 34](https://user-images.githubusercontent.com/4819276/27197610-e02aa2c2-51dc-11e7-819b-927b1c8a17c1.png)

**Comment by AEnterprise** [comment]
i cannot reproduce this at all, can you try this again with 7.99.6? if you can reproduce please provide pictures of the setup you used to reproduce so we can replicate it in dev

**Comment by AEnterprise** [comment]
he closed it because neighter me or him could still reproduce this issue anymore
