### ISSUE TITLE
(1.11.2) crash when loading the game

### ISSUE THREAD

**Issue by Hypsellis** [BuildCraft/BuildCraft#3676]
I started to rencently get this crash when trying to load the game. https://pastebin.com/Hk7YPwp5

**Comment by AEnterprise** [comment]
looks to be fixed in e808136fce52d921d7645368994d17bc039df0f3

**Comment by AlexIIL** [comment]
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)
