### ISSUE TITLE
[1.11.2] Crash on start

### ISSUE THREAD

**Issue by Sejoslaw** [BuildCraft/BuildCraft#3677]
Minecraft has crashed on start.
[Crash report](https://pastebin.com/nXLDnPKU)

It looks like it's crashing on:
`[19:55:30] [Client thread/ERROR] [FML]: Caught exception from BuildCraft (buildcraftcore)
java.lang.NoClassDefFoundError: buildcraft/lib/client/reload/ReloadManager
    at buildcraft.lib.client.reload.LibConfigChangeListener.run(LibConfigChangeListener.java:30) ~[LibConfigChangeListener.class:?]`

**Comment by AEnterprise** [comment]
is it possible you are running normal BC instead of the dev version in your workspace?

**Comment by AlexIIL** [comment]
@Sejoslaw if you want to use Buildcraft in a dev environment then you'll have to build the dev jar yourself - it's not published on the website as I cannot recommends developing an add on for Buildcraft at the moment.

**Comment by Sejoslaw** [comment]
Ou okok. Thank You.
Yes, I'm using the 7.99.4 build, downloaded from the website.

**Comment by AEnterprise** [comment]
gona close this as fixed then
