### ISSUE TITLE
Quarry tries to mine Bedrock

### ISSUE THREAD

**Issue by Holzstock** [BuildCraft/BuildCraft#3680]
The Quarry tries to mine Bedrock and Lava, since these blocks cannot be mined, the quarry gets stuck until the block is destroyed manually. This doesn't happen with water-blocks. (11.2-version)

**Comment by AlexIIL** [comment]
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)
