### ISSUE TITLE
Pipes don't always stay connected to tile entities when loading

### ISSUE THREAD

**Issue by AlexIIL** [BuildCraft/BuildCraft#3684]
I have no idea what's causing this... perhaps we could try saving the connection status and just assuming its correct?

**Comment by AEnterprise** [comment]
when is the connection tested? maybe we're testing it before the other TE has finished loaded and exposes its capabilities

**Comment by AlexIIL** [comment]
Caused by not force-loading the neighbouring chunk. I'll investigate not doing this later.

**Comment by AlexIIL** [comment]
Fixed in a previous commit.

**Comment by AlexIIL** [comment]
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)
