### ISSUE TITLE
Missing Textures on Pipes

### ISSUE THREAD

**Issue by Gyromax** [BuildCraft/BuildCraft#3685]
Hi,

i have serveral Pipes which are showing the Missing-Texture-Icon (the purple/black one). I first thought it was due to my Server lagging, but even after getting better Hardware and without lags, the Problem remains. As u can see in the Screenshots below.
The interesting Part of the missing Textures is, that the Pipes and even the Gates / Pipe Pulsars if added will funktion as i set them beforehand. Also the Textures are there when i'm building and running around. But they are vanished after i log off and in again. If they are in that state i can't dismantle em, use the gates / pulsars or add new Pipes. But they will still send Items / Liquids through.

Hope u can maybe tell me a way to solve this.
I'm using Buildcraft-Version 7.99.4 and Forge-Version 1.11.2-13.20.0.2315 with Minecraft 1.11.2.
Also i have some more Mods installed. But i've just recently startet the Server so i've been using only Buildcraft, Harvestcraft (Version 1.11.2h) and Tinker's Construct for now to get the Basic Recource-Supply up and Running.
The Problem keeps even if i delete Optifine out of my mods.

Thanks in advance!

If u need more Information just tell me what u need and i'll try to get it.

And here the Screenshots:
![2017-06-24_13 54 45](https://user-images.githubusercontent.com/29234456/27509453-8d06b1ee-58fd-11e7-8875-27565f823421.png)
![2017-06-24_13 54 55](https://user-images.githubusercontent.com/29234456/27509454-8d08b4bc-58fd-11e7-9bb1-bbc6281fcb61.png)
![2017-06-24_13 55 05](https://user-images.githubusercontent.com/29234456/27509456-8d09ce88-58fd-11e7-94c9-92c2265851e2.png)
![2017-06-24_13 55 19](https://user-images.githubusercontent.com/29234456/27509455-8d099d46-58fd-11e7-8685-b16d86d1ab24.png)
![2017-06-24_13 55 25](https://user-images.githubusercontent.com/29234456/27509457-8d0a2dec-58fd-11e7-8a3e-8a4a1e5673de.png)

**Comment by AlexIIL** [comment]
If the pipes are still functioning server side then it means that they are failing to send over to the client properly - I'm not quite sure what causes it, and I don't think I log anything at the moment when this happens so I might not be able to help you.

However it might force update the pipe if you place a block down next to them?

**Comment by Gyromax** [comment]
Just rembered what i forgot to post above.
I use the Vanilla-Textures and the ressources given by the mods.
I've already tried reloading the ressources with F3+T.

And i've just now tried your suggestion, sadly with no effect. I tried placing Earth next to the Pipes and around it.

**Comment by Gyromax** [comment]
Have found a Way to at least remove them. If i mine another "visible" Pipe or a Stone next to the buggy Pipes with the Hammer from Tinkerscraft (3x3 AoE), the Pipes will be removed even if i can't remove em directly.
Was just a Coincidence while i was growing my Storage-Lair ;o)
I've tried removing all Pipes from the last Screenshot in the Opening-Post, replaced them, set the Gates / Pulsars and logged out / back in. Same Problem keeps staying.
Also some newly build Pipes have turned to the Missing Textures with me online, just switching Dimensions (i have a Chunkloader keeping them loaded)...

**Comment by AEnterprise** [comment]
so far i only have been parially able to reproduce this
it seems to heapen if a block in the affected chunk(s) is throwing an error during loading. This causes the data not be deserialized properly, resulting in the correct block being there but it's data being corrupted

**Comment by afdw** [comment]
@Gyromax have you any blocks from HarvestCraft? If yes, please try to remove them and try again.

**Comment by Gyromax** [comment]
sorry, haven't looked on Github for a while.
Yes, there are Blocks from Harvestcraft nearby the affected Pipes, namely some Apiarys, Groundtraps and Fishtraps.
I've tried removing them and got the Textures back. Looks like u found the Problem and i'll have to do another Bug-Report over at HarvestCraft ;o)
Thanks for ur help!

**Comment by AEnterprise** [comment]
alright, sadly there isn't anything realy we can do about this from our end against things like this where we do not get our data back from NBT, i think the current behaviour with the broken textures is probably best  as that clearly shows to users something is going wrong somewhere

**Comment by AEnterprise** [comment]
closing this as this is other mods (accidentaly) corrupting NBT data so there is very little that can be done against that
