### ISSUE TITLE
Filler not clearing anything

### ISSUE THREAD

**Issue by Swandar** [BuildCraft/BuildCraft#3686]
First things first don't try to have me try something else. I've read every single comment relating to this issue. I've done everything right. I put everything the right why. You need to just bring back the old way of using the filler, with the 9 squares and putting the glass to clear. Because this new damn way just isn't working. I've never had any problems with the old filler. Not to mention you're the only mod I really ever have any problems with. I don't know if you all are just a bunch of incompetent coders or something but this is getting really old really fast. You're kinda like Space Engineers, every update you mess something up. The only feature that even remotely works right is the filling option. Everything else just starts up and stops after deleting a few blocks, except for the clear option. I've looked up video after video. But it seems no one will do a video on 7.1.22 because it's a broken update or some shit. I'm sick of spending time and time again having to clear something out by hand, that takes a few hour when I should be able to it in a few seconds using the filler. Here a bright idea for you. Get rid of the filler and replace it with blocks representing the options you can choose from in the filler. Because of your idiocy, I'm going to have download older versions of BC till I find a filler that works properly. Thanks for wasting my bloody time

**Comment by Swandar** [comment]
Nevermind. I'll just use MC Edit. At least that's never let me down

**Comment by asiekierka** [comment]
>First things first don't try to have me try something else.

You just did that yourself.

>You need to just bring back the old way of using the filler, with the 9 squares and putting the glass to clear.

No? The front-end user experience has no relation to the multiple rewrites done to the filler code on the back-end. This wouldn't change anything.

>Not to mention you're the only mod I really ever have any problems with. I don't know if you all are just a bunch of incompetent coders or something but this is getting really old really fast.

We're not forcing you to use BuildCraft, but, as per your request, we won't recommend other mods either, as that would involve "trying something else". I was the sole 1.7.10 developer for most of that version's lifetime, and unfortunately I am no longer willing to devote my time and resources to BuildCraft. There's many reasons for that and I won't get into them here.

>The only feature that even remotely works right is the filling option. Everything else just starts up and stops after deleting a few blocks, except for the clear option.

There could be many reasons for that - ranging from power consumption issues, lack of proper resources, or even a simple bug we haven't caught.

>But it seems no one will do a video on 7.1.22 because it's a broken update or some shit.

The filler logic did not change massively for a while. Videos for 7.0.x or 7.1.x should work fine.

>I'm sick of spending time and time again having to clear something out by hand, that takes a few hour when I should be able to it in a few seconds using the filler.

No, the filler will still take (Width*Height*Depth)/20 seconds at the very least, and that's assuming a perfect energy source and blocks which are inexpensive to break.

>Because of your idiocy, I'm going to have download older versions of BC till I find a filler that works properly.

The last version of BuildCraft with both the old filler code and meeting your stability standards is 4.2.2 (Minecraft 1.6.4).

>Thanks for wasting my bloody time

Thank you for unnecessary hostility to a bunch of unpaid hobbyists. You're welcome.

**Comment by AEnterprise** [comment]
thanks for your feedback, we'll take it into consideration

7.1.x is still the most stable branch of BC at this time, if it is a buggy mess as you claim it is then this is due to bugs that we don't know about and people not reporting them

the filler is not suposed to be an instant clearing machine like mcedit, it saves the player time but at the cost of power (and thus resources and infrastructure), please do not try comparing it to mcedit

if BC no longer matches what you beleive it should be then i'm sorry but you do not make this mod, while we do listen to community feedback we cannot please everyone

if you have any more we'd be happy to listen to it if it is brought to us in a constructive way, insults do not help your case at all

**Comment by asiekierka** [comment]
>if BC no longer matches what you beleive it should be then i'm sorry but you do not make this mod

Correction: You can always (as long as you follow the terms of the license) fork the mod to introduce whatever changes to the mod you want.

**Comment by AEnterprise** [comment]
he can, it just wont be any offical BC version
