### ISSUE TITLE
[7.99.4] Crash when breaking rotated quarry

### ISSUE THREAD

**Issue by qwertyasdef** [BuildCraft/BuildCraft#3687]
After breaking a quarry rotated 180 degrees, the game continues as if nothing happened, but the quarry and any block you break afterwards doesn't drop items. Upon trying to save and quit, the game freezes and doesn't save.

It's not a directional bug, because I tried placing quarries facing every direction and none of them crashed unless they were rotated 180 degrees from their initial orientations. An unrotated quarry or a quarry rotated 90 degrees from its original state drop normally. Only a quarry rotated to face the opposite direction from how it was placed causes this issue.

Steps to reproduce:

1. Place a quarry in the world.

2. Rotate it 180 degrees. The BC wrench won't rotate it. I tested the TE crescent hammer and the Forestry wrench.

3. Break the quarry.

**Comment by afdw** [comment]
Probably https://github.com/BuildCraft/BuildCraft/issues/3553? What BC version are you running?

**Comment by AlexIIL** [comment]
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)
