### ISSUE TITLE
[1.11.2] NPE Crash Updating Screen Events 

### ISSUE THREAD

**Issue by Morpheus1101** [BuildCraft/BuildCraft#3688]
Forge *.2315
BC 7.99.4

crash log @ https://puu.sh/wtBjY/048ba19abb.txt

**Comment by AEnterprise** [comment]
i'm sorry for the delay but this seems to slipped through the cracks and got missed

It seems someone has a block that somehow is returning things in such a way that a null blockstate slipped through the safety checks, we probably need to add an aditional one

**Comment by Morpheus1101** [comment]
All good, we cant always allow for every event that may occur.  I neglected to mention that this only occured when trying to view the BC creative TAB

**Comment by AEnterprise** [comment]
does this still heapen?

**Comment by Morpheus1101** [comment]
No
