### ISSUE TITLE
[7.99.4] Pipes not working with IC2 water mill.

### ISSUE THREAD

**Issue by Nurfey** [BuildCraft/BuildCraft#3693]
Hello, 

I was working in my world trying to make an automatic water-mill refill system for IC2 with the use of buildcraft pipes. Then I found out that the pipes DO connect to the water mill, but they can't extract or implement anything into the water mill, I have tried all sides and multiple pipes they all don't work.

Hope this gets fixed.

My apologies if my English was not 100% correct, my first language is Dutch.

Kindest regards,
Nurfey

**Comment by AEnterprise** [comment]
could you post some pictures of your setup? are they not connection visually or just not inserting/extracting anything

if they don't connect visually it is most likely IC2 not exposing item capabilities

**Comment by Nurfey** [comment]
Sure, take a look:

The setup: http://prntscr.com/fp6zfp
Different pipes connecting: http://prntscr.com/fp6zoi


As you can see all pipes connect to every side, but in the setup it goes to the water mill, and then drops the water bucket. I have tried the same thing to all sides of the water mill to see if it makes any difference, but it doesn't. I have tried alternative items (like water cells instead of water buckets, what works too) but it still drops the item.

**Comment by AEnterprise** [comment]
the pipes connect so IC2 is exposing item capabilities, can you extract things out of it on any side with a regular wooden pipe? if not then the machine is not allowing extraction and you will want to report it on the IC2 issuetracker

if you can extract it with a regular wooden pipe from any side this is the same bug as #3681

**Comment by Nurfey** [comment]
No, I can't extract or implement anything with any pipe. I will report this to the issuetracker aswell then, sounds like a good idea. Thank you for your help!

**Comment by qwertyasdef** [comment]
Just making sure, but do you have watermillAutomation set to true in your IC2 config?

**Comment by AEnterprise** [comment]
closing as this seems to be IC2 not allowing extracting the items, if this does turn out to be an BC issue just let me know and i'll reopen this then
