### ISSUE TITLE
Fuel change maintains previos MJ/t

### ISSUE THREAD

**Issue by DragonwrathI** [BuildCraft/BuildCraft#3696]
A little one I just found. I manually removed heavy from two combustion engines and added gaseous fuel but they maintain the 2 MJ/t rate of the heavy oil. The gaseous fuel is also being consumed at the heavy oil rate of consumption.

**Comment by AlexIIL** [comment]
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)
