### ISSUE TITLE
Update to 1.12.

### ISSUE THREAD

**Issue by SourcePowered** [BuildCraft/BuildCraft#3699]
Update to 1.12, please.
I think 1.12 will be a huge Mod version, equivalent to 1.7.10's status.
1.10.2 and 1.11.2 both have different flaws and deficiencies, and 1.12 has perfected all of them.

**Comment by AEnterprise** [comment]
a 1.12 update is in the works but given the current alpha state and all the new things in 1.12 it takes time to finish a move to 1.12

**Comment by SourcePowered** [comment]
Update to 1.12.2, please. I think it's time now.

**Comment by AEnterprise** [comment]
as previously stated: it is already being worked on

**Comment by mcsnetworks** [comment]
AlmuraDev team is also willing to assist.  Just give us a PM in #Almura or #SpongeDev

Thanks,

**Comment by ogurets** [comment]
Sorry if it's obvious - will the new 8.0.x version be compatible with already released versions of IC2 for 1.12?

**Comment by AEnterprise** [comment]
compatible in what way? you should be able to install and use them together like any 2 other forge mods

**Comment by ogurets** [comment]
I mean - will BC pipes (liquid ones, especially) and electric engine work with IC2 machines? Or IC2 developers should update their mod to BC 8.0.x API first?

**Comment by AlexIIL** [comment]
The item and fluid pipes use minecraft and forge API's for iteracting with IC2 - neither mod needs to depend on each other to make that work. BC doesn't have an electric engine (I think that's part of forestry?) so I can't really answer that properly.
