### ISSUE TITLE
remove fakeworld for getting requirements

### ISSUE THREAD

**Issue by YOYOK9** [BuildCraft/BuildCraft#3700]
So I am building a 1.11.2 server and am having an issue with bc transport on boot up.
I am using the latest version of buildcraft for 1.11.2
https://pastebin.com/crrfb3uz

Forge: forge-1.11.2-13.20.1.2388
Spongeforge: 1.11.2-2315-6.1.0-BETA-2432 
Buildcraft: 7.99.4
(doesn't crash if spongeforge is not installed but is needed)

**Comment by AEnterprise** [comment]
known issue, our fake world is not compatible with sponge

**Comment by YOYOK9** [comment]
Any ways to get around this or any fixes in play for next update? Don't want to pull buildcraft from the server... or sponge

**Comment by AEnterprise** [comment]
it is being worked on, work is being done but it is a massive change to how some aspects work so cannot garantee when this will be done

there are no other ways of getting arround this, we have a fakeworld that claims to be a server world but realy isn't so it is incompatible with forge at this point

**Comment by YOYOK9** [comment]
What is the fake world used for? Out of curiosity. Is it something that is truly needed? It has been a while since I have full tested with buildcraft.

**Comment by AEnterprise** [comment]
at this point in time is needed, the fake world is used for getting info from blocks in ways that require a world. This includes extracting properties for facades and part of determining what the blueprint requirements are to re-create a block

**Comment by YOYOK9** [comment]
ah okay. Makes sense.

**Comment by bhi-elliot** [comment]
Thank you for linking my duplicate issue.
Does this mean that facades and blueprints should not be used until this is resolved? Will it crash the server or corrupt anything if facades are used?
Thank you!

**Comment by AlexIIL** [comment]
I think the facade issue was fixed in 7.99.5 - although facades only use a fakeworld in init, so if you can load up the game then facades are fine. Blueprints however will almost certainly crash with sponge right now.

**Comment by bhi-elliot** [comment]
Understood. Thank you.
