### ISSUE TITLE
Crashes whenever i place a block

### ISSUE THREAD

**Issue by Luxray997** [BuildCraft/BuildCraft#3703]
whenever i place a BC block in any world, the Minecraft crashes. If i go back into the world, it just crashes again. I can still play without BC by taking the mod out of the mod folder and loading my world. I am using minecraft 1.6.4, Forge 9.11.1.1345, and Buildcraft 4.2.2

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 7/5/17 3:37 PM
Description: Ticking tile entity

java.lang.NoSuchMethodError: net.minecraft.world.World.getTotalWorldTime()J
	at buildcraft.api.core.SafeTimeTracker.markTimeIfDelay(SafeTimeTracker.java:27)
	at buildcraft.api.power.PowerHandler.applyPerdition(PowerHandler.java:291)
	at buildcraft.api.power.PowerHandler.update(PowerHandler.java:284)
	at buildcraft.api.power.PowerHandler$PowerReceiver.update(PowerHandler.java:436)
	at buildcraft.core.TileBuildCraft.func_70316_g(TileBuildCraft.java:59)
	at buildcraft.factory.TileQuarry.func_70316_g(TileQuarry.java:151)
	at net.minecraft.world.World.func_72939_s(World.java:2209)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1921)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at buildcraft.api.core.SafeTimeTracker.markTimeIfDelay(SafeTimeTracker.java:27)
	at buildcraft.api.power.PowerHandler.applyPerdition(PowerHandler.java:291)
	at buildcraft.api.power.PowerHandler.update(PowerHandler.java:284)
	at buildcraft.api.power.PowerHandler$PowerReceiver.update(PowerHandler.java:436)
	at buildcraft.core.TileBuildCraft.func_70316_g(TileBuildCraft.java:59)
	at buildcraft.factory.TileQuarry.func_70316_g(TileQuarry.java:151)

-- Tile entity being ticked --
Details:
	Name: Machine // buildcraft.factory.TileQuarry
	Block type: ID #1503 (tile.machineBlock // buildcraft.factory.BlockQuarry)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (255,56,176), Chunk: (at 15,3,0 in 15,11; contains blocks 240,0,176 to 255,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #1503 (tile.machineBlock // buildcraft.factory.BlockQuarry)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2209)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCCorePlayerSP['awesome25075'/280, l='MpServer', x=258.17, y=57.62, z=176.55]]
	Chunk stats: MultiplayerChunkCache: 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-56,64,256), Chunk: (at 8,4,0 in -4,16; contains blocks -64,0,256 to -49,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 117979 game time, 39713 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 105 total; [EntitySkeleton['Skeleton'/516, l='MpServer', x=332.00, y=35.00, z=115.59], EntityZombie['Zombie'/517, l='MpServer', x=323.00, y=30.00, z=131.53], EntitySkeleton['Skeleton'/520, l='MpServer', x=327.06, y=22.00, z=210.00], Firefly['Firefly'/523, l='MpServer', x=319.99, y=59.16, z=236.57], Firefly['Firefly'/526, l='MpServer', x=323.69, y=63.08, z=225.66], EntityCreeper['Creeper'/530, l='MpServer', x=329.00, y=64.00, z=239.94], EntityGib['unknown'/1810, l='MpServer', x=342.86, y=36.00, z=243.49], EntityGib['unknown'/1811, l='MpServer', x=341.75, y=36.00, z=241.78], Firefly['Firefly'/532, l='MpServer', x=321.66, y=63.71, z=229.72], EntityGib['unknown'/1812, l='MpServer', x=342.86, y=36.00, z=242.55], EntitySkeleton['Skeleton'/533, l='MpServer', x=328.78, y=28.00, z=243.31], EntityGib['unknown'/1813, l='MpServer', x=342.85, y=35.00, z=243.65], EntityZombie['Zombie'/534, l='MpServer', x=335.78, y=35.00, z=240.25], EntityGib['unknown'/1814, l='MpServer', x=342.13, y=36.00, z=242.66], EntitySpider['Spider'/535, l='MpServer', x=319.66, y=36.00, z=251.97], EntityGib['unknown'/1815, l='MpServer', x=341.36, y=35.00, z=242.59], EntityAnt['Ant'/281, l='MpServer', x=264.28, y=74.00, z=183.40], EntityRainbowAnt['Rainbow Ant'/282, l='MpServer', x=273.66, y=69.00, z=180.32], EntityAnt['Ant'/283, l='MpServer', x=268.16, y=72.00, z=176.63], EntityZombie['Zombie'/542, l='MpServer', x=338.50, y=12.00, z=123.53], EntityZombie['Zombie'/544, l='MpServer', x=333.00, y=35.00, z=114.63], GCCorePlayerSP['awesome25075'/280, l='MpServer', x=258.17, y=57.62, z=176.55], EntityZombie['Zombie'/549, l='MpServer', x=338.56, y=30.00, z=208.75], EntityZombie['Zombie'/550, l='MpServer', x=338.53, y=35.00, z=213.97], EntityCreeper['Creeper'/555, l='MpServer', x=341.31, y=63.00, z=229.09], EntityZombie['Zombie'/556, l='MpServer', x=340.00, y=63.00, z=229.38], EntitySpider['Spider'/558, l='MpServer', x=338.25, y=64.00, z=236.97], EntityCreeper['Creeper'/560, l='MpServer', x=327.34, y=64.00, z=250.50], EntitySpider['Spider'/306, l='MpServer', x=183.88, y=64.00, z=98.16], EntityCreeper['Creeper'/307, l='MpServer', x=183.00, y=63.00, z=140.13], EntitySquid['Squid'/313, l='MpServer', x=205.38, y=58.34, z=174.53], EntitySquid['Squid'/314, l='MpServer', x=207.03, y=57.00, z=169.75], EntitySquid['Squid'/317, l='MpServer', x=216.09, y=56.97, z=166.31], EntitySquid['Squid'/318, l='MpServer', x=207.38, y=58.00, z=181.91], EntitySkeleton['Skeleton'/320, l='MpServer', x=238.17, y=65.00, z=105.82], EntityCreeper['Creeper'/321, l='MpServer', x=235.50, y=39.00, z=112.50], EnderKnight['Ender Knight'/322, l='MpServer', x=238.50, y=40.00, z=118.50], EntityGib['unknown'/1604, l='MpServer', x=318.63, y=22.00, z=261.29], EntityGib['unknown'/1605, l='MpServer', x=317.86, y=21.00, z=259.50], EntitySkeleton['Skeleton'/326, l='MpServer', x=227.69, y=37.24, z=194.28], EntityGib['unknown'/1606, l='MpServer', x=318.83, y=21.00, z=259.82], EntityGib['unknown'/1607, l='MpServer', x=318.18, y=21.00, z=260.85], EntityBlock['unknown'/1863, l='MpServer', x=244.50, y=56.45, z=171.45], EntityGib['unknown'/1608, l='MpServer', x=318.78, y=21.00, z=260.85], EntityBlock['unknown'/1864, l='MpServer', x=244.45, y=56.50, z=171.45], EntityGib['unknown'/1609, l='MpServer', x=317.69, y=21.00, z=260.43], EntityBlock['unknown'/1865, l='MpServer', x=244.50, y=60.45, z=171.45], EntityBlock['unknown'/1866, l='MpServer', x=254.45, y=56.50, z=171.45], EntityBlock['unknown'/1867, l='MpServer', x=244.50, y=56.45, z=181.45], EntityBlock['unknown'/1868, l='MpServer', x=244.45, y=56.50, z=181.45], EntityBlock['unknown'/1869, l='MpServer', x=254.45, y=56.50, z=181.45], EntityBlock['unknown'/1870, l='MpServer', x=244.50, y=60.45, z=181.45], EntityBlock['unknown'/1871, l='MpServer', x=244.45, y=56.45, z=171.50], EntityBlock['unknown'/1872, l='MpServer', x=254.45, y=56.45, z=171.50], EntityBlock['unknown'/1873, l='MpServer', x=244.45, y=60.45, z=171.50], EntityGib['unknown'/1618, l='MpServer', x=336.31, y=38.00, z=259.90], EntityBlock['unknown'/1874, l='MpServer', x=254.45, y=60.45, z=171.50], EntityGib['unknown'/1619, l='MpServer', x=337.15, y=39.00, z=259.69], EntityGib['unknown'/1620, l='MpServer', x=337.83, y=38.00, z=258.48], EntityGib['unknown'/1621, l='MpServer', x=338.45, y=39.00, z=259.59], EntityGib['unknown'/1622, l='MpServer', x=336.88, y=39.00, z=260.58], EntityGib['unknown'/1623, l='MpServer', x=337.71, y=39.00, z=259.59], EntitySpider['Spider'/346, l='MpServer', x=243.25, y=40.00, z=123.22], EnderKnight['Ender Knight'/347, l='MpServer', x=243.56, y=40.00, z=120.03], EntitySkeleton['Skeleton'/349, l='MpServer', x=252.09, y=17.00, z=130.41], EntityRainbowAnt['Rainbow Ant'/353, l='MpServer', x=249.41, y=71.00, z=172.63], EntityAnt['Ant'/354, l='MpServer', x=248.98, y=74.00, z=192.10], EntityAnt['Ant'/356, l='MpServer', x=248.56, y=74.00, z=188.51], EntitySquid['Squid'/360, l='MpServer', x=256.50, y=59.38, z=225.72], EntityZombie['Zombie'/384, l='MpServer', x=265.41, y=21.00, z=100.31], EntitySkeleton['Skeleton'/386, l='MpServer', x=266.50, y=29.00, z=131.50], EntityCreeper['Creeper'/387, l='MpServer', x=263.50, y=72.00, z=164.50], EntityAnt['Ant'/389, l='MpServer', x=268.47, y=70.00, z=191.50], EntityAnt['Ant'/392, l='MpServer', x=271.47, y=66.00, z=191.69], EntityAnt['Ant'/393, l='MpServer', x=266.93, y=72.00, z=187.44], EntitySkeleton['Skeleton'/1423, l='MpServer', x=57.50, y=-20.62, z=13.91], EntityGib['unknown'/1452, l='MpServer', x=238.67, y=65.00, z=105.07], EntityGib['unknown'/1453, l='MpServer', x=237.09, y=65.00, z=106.27], EntityGib['unknown'/1454, l='MpServer', x=236.60, y=65.00, z=106.05], EntityGib['unknown'/1455, l='MpServer', x=238.61, y=64.00, z=104.48], EntityGib['unknown'/1456, l='MpServer', x=237.61, y=65.00, z=106.63], EntityGib['unknown'/1457, l='MpServer', x=238.16, y=65.00, z=106.87], EntityItem['item.item.bone'/435, l='MpServer', x=282.78, y=64.13, z=118.88], EntityItem['item.item.arrow'/436, l='MpServer', x=287.66, y=64.13, z=115.63], EntityGib['unknown'/1462, l='MpServer', x=183.74, y=63.00, z=140.95], EntityGib['unknown'/1463, l='MpServer', x=182.59, y=62.75, z=139.41], EntityLunaMoth['Moth'/440, l='MpServer', x=272.25, y=64.01, z=192.15], EntityGib['unknown'/1464, l='MpServer', x=183.85, y=63.00, z=141.55], EntityGib['unknown'/1465, l='MpServer', x=182.20, y=62.75, z=140.79], EntityGib['unknown'/1466, l='MpServer', x=183.85, y=63.00, z=139.52], EntityRainbowAnt['Rainbow Ant'/443, l='MpServer', x=271.53, y=66.00, z=191.34], EntityGib['unknown'/1467, l='MpServer', x=182.82, y=62.75, z=141.13], EntitySpider['Spider'/466, l='MpServer', x=290.00, y=25.00, z=240.97], EntityCreeper['Creeper'/467, l='MpServer', x=297.50, y=19.00, z=246.06], EntityZombie['Zombie'/479, l='MpServer', x=315.94, y=27.00, z=140.59], EntityZombie['Zombie'/480, l='MpServer', x=314.50, y=31.00, z=134.50], EntityZombie['Zombie'/481, l='MpServer', x=313.47, y=32.00, z=137.03], EntitySkeleton['Skeleton'/482, l='MpServer', x=319.47, y=21.00, z=156.84], WaterDragon['Water Dragon'/483, l='MpServer', x=324.31, y=62.05, z=180.44], EntitySkeleton['Skeleton'/485, l='MpServer', x=313.50, y=20.00, z=217.31], EntityZombie['Zombie'/486, l='MpServer', x=323.50, y=20.00, z=235.46], EntityZombie['Zombie'/487, l='MpServer', x=311.50, y=21.00, z=214.50], EntityZombie['Zombie'/488, l='MpServer', x=313.84, y=20.00, z=220.41], Hydrolisc['Hydrolisc'/490, l='MpServer', x=309.06, y=61.31, z=231.69], EntityZombie['Zombie'/492, l='MpServer', x=317.50, y=38.00, z=252.06]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2312)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:856)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 252775832 bytes (241 MB) / 683073536 bytes (651 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 33860 (1896160 bytes; 1 MB) allocated, 1323 (74088 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 6, tallocated: 62
	FML: MCP v8.11 FML v6.4.50.1,345 Minecraft Forge 9.11.1.1345 44 mods loaded, 44 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{6.4.50.1,345} [Forge Mod Loader] (minecraftforge-9.11.1.1345.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{9.11.1.1345} [Minecraft Forge] (minecraftforge-9.11.1.1345.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AppliedEnergistics-Core{rv13.c} [AppliedEnergistics Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{0.9.0.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.6.1.9} [Not Enough Items] (NotEnoughItems-1.6.4-1.6.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct-Preloader{0.0.1} [Tinkers Corestruct] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{v5.2(1.6.4)} [bspkrsCore] (BspkrsCore-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TreeCapitator{Forge 1.6.4.r06} [Treecapitator] ([1.6.4]TreeCapitator.Forge.1.6.4.r06.Universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Agriculture{1.0.0} [Agriculture] (Agriculture-1.6.2-1.1.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AppliedEnergistics{rv13.c} [Applied Energistics] (AppliedEnergisticsMod1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{4.1.0} [BuildCraft] (buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{4.1.0} [BC Builders] (buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{4.1.0} [BC Energy] (buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{4.1.0} [BC Factory] (buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{4.1.0} [BC Transport] (buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{4.1.0} [BC Silicon] (buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{2.0.0.5} [CoFH Core] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHLoot{2.0.0.5} [CoFH Loot] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHMasquerade{2.0.0.5} [CoFH Masquerade] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHSocial{2.0.0.5} [CoFH Social] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHWorld{2.0.0.5} [CoFH World] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DamageIndicatorsMod{2.9.2.4} [Damage Indicators] (Damage-Indicators-Mod-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderStorage{1.4.3.6} [EnderStorage] (EnderStorage-1.6.4-1.4.3.6-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	UniversalElectricity{3.0.0} [Universal Electricity] (Universal-Electricity-3.0.0.1-dev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.0.0.219} [Forge Multipart] (ForgeMultipart-universal-1.6.4-1.0.0.219.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalExpansion{3.0.0.7} [Thermal Expansion] (ThermalExpansion-3.0.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2{2.0.397-experimental} [IndustrialCraft 2] (industrialcraft-2_2.0.397-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftCore{2.0.14} [Galacticraft Core] (Galacticraft-1.6.4-2.0.14.1084.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftMars{2.0.14} [Galacticraft Mars] (Galacticraft-Planets-1.6.4-2.0.14.1098.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	iChunUtil{2.4.0} [iChunUtil] (iChunUtil2.4.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.56} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{5.4.1.702} [Iron Chest] (Iron-Chests-Mod-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MobDismemberment{2.0.0} [MobDismemberment] (MobDismemberment2.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Morph{0.7.1} [Morph] (Morphing-Mod-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Natura{2.1.14} [Natura] (Natura_mc1.6.X_2.1.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OreSpawn{164.20} [OreSpawn] (orespawn164v20a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PortalGun{2.0.2} [PortalGun] (Portal-Gun-Mod-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Waila{1.4.5} [Waila] (Waila_1.4.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.6.X_1.5.5.7} [Tinkers' Construct] (TConstruct_mc1.6.4_1.5.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	telepads{1.6.4 v5} [Teleportation Pads] (TelePadsMod1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.0.0.219} [Minecraft Multipart Plugin] (ForgeMultipart-universal-1.6.4-1.0.0.219.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.0.0.219} [Forge Microblocks] (ForgeMultipart-universal-1.6.4-1.0.0.219.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct Environment: Sane and ready for action. Bugs may be reported.
	Launched Version: 1.6.4-Forge9.11.1.1345
	LWJGL: 2.9.0
	OpenGL: GeForce GTX 950/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Pack: Default
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 3207 (179592 bytes; 0 MB) allocated, 792 (44352 bytes; 0 MB) used

**Comment by AlexIIL** [comment]
While you say you're using buildcraft 4.2.2, your log says that you're using buildcraft 4.1.0 - can you try redownloading 4.2.2 from http://www.mod-buildcraft.com/releases/BuildCraft/4.2.2/buildcraft-A-1.6.4-4.2.2.jar

**Comment by AlexIIL** [comment]
I'm closing this as hopefully that resolves the issue -- feel free to comment more if that didn't work though, or something else broke.
