### ISSUE TITLE
No Buildcraft versions for 1.10.2

### ISSUE THREAD

**Issue by border999** [BuildCraft/BuildCraft#3710]
I just want a version of buildcraft for my 1.10.2 modpack

**Comment by dj3520** [comment]
Code is open source. If you're that desperate, backport it to 1.10.2

**Comment by asiekierka** [comment]
Either way, a backport to 1.10.2 would take up significant development resources which the team cannot currently afford due to more pressing priorities - such as providing the best user experience and porting to 1.12 - and is not planned.
