### ISSUE TITLE
Guide images crashing

### ISSUE THREAD

**Issue by Chocohead** [BuildCraft/BuildCraft#3711]
Changing all the parsing/loading of the guide pages to when the book is first opened has broken the loading of images on pages.

When `MarkdownPageLoader` parses an image, it will use `loadDefaultImage` or `loadSizedImage`, both will produce a `TextureResourceHolder` and register it with the `ResourceRegistry`. The original design looks like that would then load all the images during the resource reload after post-init. But now that the parsing of the pages is much later, `ResourceRegistry` will never load the images (which can be seen as `TextureResourceHolder#load` is never called). This causes the textures to never be given a size, which then [crashes](https://ghostbin.com/paste/tjzw9) in `GuideImage` as it tries to scale them.

This can be caused by putting `![anything]` in a page, the contents of the brackets isn't important as the texture is never loaded thus the path never followed.

**Comment by AlexIIL** [comment]
...dammit. Admittedly I've never actually tested images before so I'm not too surprised that they don't work.

**Comment by AlexIIL** [comment]
Also changing the load order was probably not a great idea either - it was done to allow facade swap recipes to load, so I'll probably have to do them differently.

**Comment by AlexIIL** [comment]
Looking back through it quite a feeble things are done oddly, I'll probably take another pass at the loader *at some point*.

**Comment by Chocohead** [comment]
I can work around it in the mean time, if the needed `TextureResourceHolder`s are manually added to the `ResourceRegistry` it seems to all load fine. It's [quite loud](https://ghostbin.com/paste/9h87x) when failing to find a translated version of the image though.

**Comment by AlexIIL** [comment]
Unfortunately you're going to have to wait about 2 weeks minimum for me to get back to my dev environment and release a fix for it... sorry.

Failing to find a translation of an *image* shouldn't really add anything to the log, I'll remove that code too...

**Comment by AlexIIL** [comment]
This *should* be properly fixed in https://github.com/BuildCraft/BuildCraft/commit/d1a0b7ba376419fe36a782c662dfbd17625b3562, and will be released in 7.99.7 shortly.
