### ISSUE TITLE
Client Crashes When Quarry has Water Placed Next To It

### ISSUE THREAD

**Issue by janagyjr** [BuildCraft/BuildCraft#3712]
Win7 x64
Dell Precision T3500
Xeon W3550
FirePro V5900
12GB RAM

MC and Forge versions in crash report

https://gist.github.com/janagyjr/916e2bd4393845a623c293a89ef7f6d2

I cannot log in, and I do not want to do a rollback if I can help it. This is on a VIP server. All I did was accidentally place water via a bucket next to a quarry.

**Comment by AlexIIL** [comment]
Can you try either disabling any multi core rendering settings in optifine, or if that doesn't work removing it temporarily?

**Comment by janagyjr** [comment]
I can temp disable it, sure.

**Comment by janagyjr** [comment]
Reporting issue to optifine, first time I've ever had an issue with it.

Everything is going fine now
