### ISSUE TITLE
Where is conductive pipes?

### ISSUE THREAD

**Issue by Lafayette13** [BuildCraft/BuildCraft#3713]
Where is conductive pipes? May be I'm stupid and missed an update, but I don't know how to make and from where to get them.
![2017-07-09_00 02 19](https://user-images.githubusercontent.com/30009172/27989088-2af86612-643a-11e7-9ec7-15f874b0aeaa.png)
![2017-07-09_00 02 38](https://user-images.githubusercontent.com/30009172/27989090-2af9c020-643a-11e7-9749-4736cd0d7b21.png)
![2017-07-09_00 03 14](https://user-images.githubusercontent.com/30009172/27989089-2af9776e-643a-11e7-8967-7e78a87d582b.png)

**Comment by DragonwrathI** [comment]
if you update to [https://www.mod-buildcraft.com/buildcraft-7995-alpha.html](url) you can find them under 'kinesis pipes'

**Comment by AEnterprise** [comment]
they are called kinesis pipes (though i guess they got translated to conductive in russion apearently? not sure if there is a better word) and have indeed been added back in 7.99.5, recipes for them in 7.99.6 ( https://www.mod-buildcraft.com/releases/BuildCraft/7.99.6/buildcraft-7.99.6.jar )
