### ISSUE TITLE
[7.99.6] Crash on startup: conflict with mekanism

### ISSUE THREAD

**Issue by Xiaminou** [BuildCraft/BuildCraft#3716]
[crash-2017-07-09_16.59.09-client.txt](https://github.com/BuildCraft/BuildCraft/files/1133838/crash-2017-07-09_16.59.09-client.txt)

I'm not sure which one is responsible so I'm reporting on both.

**Comment by LuigiHutch** [comment]
Thanks for the report! This is actually a Mekanism issue, see: https://github.com/aidancbrady/Mekanism/issues/4513 for details

**Comment by Xiaminou** [comment]
Damn I'm so bad, every time I take a look at the list of issues and search, and half the time I just miss them somehow...

**Comment by AEnterprise** [comment]
fixed on mekanisms side
