### ISSUE TITLE
Combustion engines+ pipes

### ISSUE THREAD

**Issue by Goldsmack** [BuildCraft/BuildCraft#3718]
I don't know if I'm missing blocks or the videos and websites I've visited are a little dated but I can't get more than five (faces of the quarry) combustion engines to work. On der internit, I was informed that I needed a Wooden Conductive Pipe along with a 'coloured piece'? neither of which are in my creative inventory.
![mimi](https://user-images.githubusercontent.com/30028990/27997711-401403b4-64f6-11e7-846a-73d204061daa.PNG)
 I've tried using other all the other pipes which are in the attachment below and still to no avail. I'm sorry for your time and thanks for helping :) ps: The mod is very well made

**Comment by LuigiHutch** [comment]
Thanks for the report! Kinesis Pipes were missing as the mod is still in aloha, they have been readded in 7.99.6 so please update to that version to access them :)

**Comment by AEnterprise** [comment]
the color is not requried here, just kinesis pipes to transfer the power. You can make any itempipe with colored glass (and then upgrade that to fluid/kinesis pipes retaining that color). Colored pipes will ony connect to uncollored pipes or pipes of the same color (you can also use a brush)
