### ISSUE TITLE
No recipe for kinesis pipe

### ISSUE THREAD

**Issue by ToKaTpoHb** [BuildCraft/BuildCraft#3719]
I tried to craft kinesis pipe, as describen in [this](http://ftb.gamepedia.com/Wooden_Kinesis_Pipe) resource, but this happend:
![screenshot from 2017-07-10 16-13-05](https://user-images.githubusercontent.com/11059471/28019939-48f4ff02-658b-11e7-88e7-e5ea1d7a2bff.png)

**Comment by ToKaTpoHb** [comment]
Official minecraft launcher, no other mods.

**Comment by LuigiHutch** [comment]
Thanks for the report! Kinesis Pipes were missing as the mod is still in alpha, they have been readded in 7.99.6 so please update to that version to access them :)

**Comment by ToKaTpoHb** [comment]
Where i can download 7.99.6?

**Comment by LuigiHutch** [comment]
https://www.mod-buildcraft.com/buildcraft-7995-alpha.html it says 7.99.5 but the download link is for 7.99.6

**Comment by ToKaTpoHb** [comment]
Im feeling really stupid, but i cant find download button there...

**Comment by LuigiHutch** [comment]
Ah, that hasn't been updated yet. here is a direct link: https://www.mod-buildcraft.com/releases/BuildCraft/7.99.6/buildcraft-7.99.6.jar

**Comment by ToKaTpoHb** [comment]
Thanks

**Comment by LuigiHutch** [comment]
No problem, hopefully we can get the downloads page updated soon :)
