### ISSUE TITLE
BuildCraft 1.11.2 auto workbench throws bucket 

### ISSUE THREAD

**Issue by stdio2016** [BuildCraft/BuildCraft#3725]
When the recipe contains bucket, auto workbench will throw away empty bucket, even if chests and pipes are nearby.
I can't prevent auto workbenches from throwing my bucket. Is it a bug?
Video: https://youtu.be/L-AgO7fNY-g

**Comment by AEnterprise** [comment]
Yes it will throw buckets out because it only has 1 output slot, the crafting output will fill up the slot leaving nowhere for the bucket to be stored so it is thrown out in the world.

for more 'complex' crafting recipes that have extra outputs like buckets you can use the advanced crafting table, that has more output slots

**Comment by stdio2016** [comment]
But advanced crafting table doesn't work in 1.11.2 😢

**Comment by AEnterprise** [comment]
it should work, what doesn't work for you?

**Comment by stdio2016** [comment]
Advenced crafting table is fully charged (500/500MJ) but does not craft a pickaxe
![minecraft 1 11 2 2017_7_12 10_15_18](https://user-images.githubusercontent.com/17265792/28122069-ba921d5a-674f-11e7-8c05-93b43d52affc.png)

**Comment by AlexIIL** [comment]
Which version of Buildcraft are you using?

**Comment by stdio2016** [comment]
7.99.6

**Comment by AlexIIL** [comment]
...maybe that broke at some point :(

@AEnterprise I think that https://github.com/BuildCraft/BuildCraft/blob/8.0.x/common/buildcraft/factory/util/IAutoCraft.java#L59 should probably call `addToBestAcceptor` rather than `drop` to fix the primary issue.

**Comment by AEnterprise** [comment]
currenty taking a look at them where things go wrong, already added the `addToBestAcceptor` it was in the old code but i missed it when rewriting it

**Comment by stdio2016** [comment]
I opened an issue for Advenced crafting table because it is different bug.
See #3726
