### ISSUE TITLE
Wooden extraction pipe only pulls one item at a time

### ISSUE THREAD

**Issue by DragonwrathI** [BuildCraft/BuildCraft#3727]
I am using a wooden extraction pipe to pull from a Galacticraft Astro Miner Base.
I first set up two redstone engines directly into the same wooden pipe (wooden transport doesn't seem to take kinesis pipes atm) but was not keeping up with incoming items.
I then setup a Stirling Engine and the extraction was actually slower than the 2 Redstone engines.

To make sure it wasn't a Mod conflict I set up a separate test with a single vanilla chest, a single wooden pipe followed by 3 gold pipes and powered it with a Stirling Engine.
I witnessed the same results. One item at a time roughly once per second. Reading the Wiki, it says the better the engine the more items extracted at once: 1 for redstone, 24 for Stirling and a stack for combustion.
I understand this may be in a state of change with 8.0.x just wanted to pass on what I'm seeing.

**Comment by AlexIIL** [comment]
For some reason I hadn't opened an issue for this, thanks for making it :)

**Comment by AlexIIL** [comment]
I can't guarantee that the numbers listed on the wiki will be the final numbers used, but it will be closer.

Note for other devs: this is partially fixed already on my pump additions branch.

**Comment by DragonwrathI** [comment]
Glad to help, wish I could do more.
Java is beyond me, never done anything beyond text based ladder logic.

**Comment by AlexIIL** [comment]
Fixed in #3810.

**Comment by AlexIIL** [comment]
Should be implemented in 7.99.8: https://www.mod-buildcraft.com/buildcraft-7998-alpha.html.
