### ISSUE TITLE
Cannot fill up stacked fluid containers

### ISSUE THREAD

**Issue by JawaB** [BuildCraft/BuildCraft#3729]
1.11.2 - BC 7.99.6
I cannot fill up an empty IC2 universal capsule by right-clicking on a BC tank full of lava

**Comment by robertmiaowu** [comment]
I met this bug as well. I can get from and put into the tank with any liquid by using bucket. But I cannot do so using IC2 universal fluid cell. I hope this bug can be fixed soon because it is so annoying that I can only use 7.99.4 version right now.

**Comment by AlexIIL** [comment]
@robertmiaowu did it work in 7.99.4, but stop working in 7.99.5/7.99.6?

**Comment by robertmiaowu** [comment]
@AlexIIL yes, it did work in 7.99.4, but stop working in 7.99.6, and I have not tried 7.99.5 yet.

**Comment by AlexIIL** [comment]
Ok, that gives a good starting point for testing in dev then :)

**Comment by robertmiaowu** [comment]
That sounds great!

**Comment by JawaB** [comment]
I also just noted that 1 capsule does fill up - but bunch of them do not

**Comment by AlexIIL** [comment]
If that's the case then i assume that it would happen with any stackable fluid container, such as capsules from forestry.

**Comment by JawaB** [comment]
> If that's the case then i assume that it would happen with any stackable fluid container, such as capsules from forestry

Yes, I can confirm that - a bunch of wax capsules does not fill up while individual capsules do.

**Comment by AlexIIL** [comment]
Should be implemented in 7.99.8: https://www.mod-buildcraft.com/buildcraft-7998-alpha.html.
