### ISSUE TITLE
builder doesn't need resources

### ISSUE THREAD

**Issue by traso56** [BuildCraft/BuildCraft#3730]
i've just tried the builder and it's amazing but it doesn't consume resources at all so i can easily cheat

I don't supply any block
http://i.imgur.com/leFnGuU.png

Building
http://i.imgur.com/CnrLyKv.png

Done
http://i.imgur.com/pwWlb94.png

i'm in survival mode using BC 7.1.22 for minecraft 1.7.10 forge version 1614

**Comment by LuigiHutch** [comment]
Was the world created in creative?

**Comment by traso56** [comment]
it was but, is it possible to disable it? because i made a survival world in creative to customize it

**Comment by LuigiHutch** [comment]
do /defaultgamemode survival

**Comment by traso56** [comment]
i will try it thanks

**Comment by traso56** [comment]
i tried it and it didn't work i made a new world in survival to try, cheated the items and it works right but i need to disable it in my current world :(

**Comment by AEnterprise** [comment]
if the command doesn't work you're gona have to use an external program like MCEdit to change the world type from creative to survival

we might want to look at adding a config (though that will be 1.11.2 or 1.12, not 1.7.10) that makes the builder use resources in a creative world

**Comment by traso56** [comment]
noted, that may explain the rolling machine issue too...

**Comment by AEnterprise** [comment]
currently the builder needs resources in creative in 7.99.6, i'm thinking we might keep it like that, will see what the other devs think
