### ISSUE TITLE
RF Support?

### ISSUE THREAD

**Issue by HickGamer** [BuildCraft/BuildCraft#3731]
Has RF support been fully dropped for the moment? or is there a mod that enables rf support in buildcraft?

**Comment by AEnterprise** [comment]
at this time there is no RF support at all, nor do we plan on doing any form of RF -> MJ conversion at this time, this also falls under 'mod compat' and most of that we will take a look at once we get closer to stable

**Comment by HickGamer** [comment]
ok so it sounds like it will be a while before even mod compat will be used
for mj-rf conversion?

**Comment by AEnterprise** [comment]
yes, also MJ and RF are very different powersystems so while MJ -> RF might be a thing without addons, RF -> MJ probably will not be in BC

**Comment by HickGamer** [comment]
ok i cant wait to see that be a thing! i was kinda dissapointed to see bc
engines and kinesis pipes not work with rf te's
