### ISSUE TITLE
Can't load custom Resource Packs

### ISSUE THREAD

**Issue by TopatoFX** [BuildCraft/BuildCraft#3733]
currently using 1.11.2
[logbc.txt](https://github.com/BuildCraft/BuildCraft/files/1149861/logbc.txt)

**Comment by AEnterprise** [comment]
@TopatoFX figured out it was the mcmeta of items in the resource pack being messed up causing the data to be currupt and MC to choke

the BC function in the stacktrace is just a bouncer to relay the call to the current sprite of that swappable
