### ISSUE TITLE
why can't I use gate? There is no output

### ISSUE THREAD

**Issue by robertmiaowu** [BuildCraft/BuildCraft#3734]
I'm using 7.99.6 right now. I find it said the bug 'Gates do not output a redstone signal' is fixed. But I cannot use the gate as well. As shown below, I cannot choose anything on the right. I want to know whether the gate is still under construction.
![2017-07-15_00 23 23](https://user-images.githubusercontent.com/30131913/28236408-ec5d77b2-68f3-11e7-9508-7360def8323e.png)

**Comment by LuigiHutch** [comment]
The icons are hidden under NEI/JEI. I believe it was control-o to hide it.

The panel will be moved away from the icons once JEI support is added which will be released in bc compat once the mod is out of alpha

**Comment by robertmiaowu** [comment]
oh, I find it! Thanks a lot!
