### ISSUE TITLE
Distiller output cannot be extracted

### ISSUE THREAD

**Issue by zainmajx** [BuildCraft/BuildCraft#3737]
Hi guys,

I'm new to the BuildCraft modpack (playing on 1.11.2) and I'm having trouble with the distillery (it was oil refinery in older versions, can't find an up to date guide)

The refinery accepts oil coming from a tank, running through a wood fluid pipe connected to a cobblestone fluid pipe (so order is Tank -> Wooden fluid pipe -> Cobblestone fluid pipe -> Distiller)

Problem stems from that, when i try to extract the fuel, which I can see in the Distiller, it just doesn't come out. I made sure that I used a wooden fluid pipe, and I powered the distillery with 3 Stirling engines - I even tried in creative mode with Combustion engines but the oil turned Fuel refuses to come out.

Is this a bug or has the way to extract fuel from the distiller changed in the Alpha version? Apologies if it has I am new.

**Comment by LuigiHutch** [comment]
BC refining has been completely redone. Here is a basic guide about how the new blocks work: http://imgur.com/a/AXUOX

**Comment by zainmajx** [comment]
Actually, has anyone made a video walk through for this guide?

**Comment by LuigiHutch** [comment]
Not that I know of, It is very new and I don't think many people have touched the mod due to its alpha state and things are still subject to change

**Comment by zainmajx** [comment]
sorry to bother you again, I set up the distiller and it looks like its working. I insert oil (cool) into the distiller and it output gaseous fuels (cool) but the liquid isn't enough for a bucket. Is there any way to change gaseous to regular? @LuigiHutch

**Comment by LuigiHutch** [comment]
No. Gaseous fuel is the last fluid in the processing chain and there is no way to go back up the processing chain. You will have to heat up the heavy/dense oil fluid you have and distill that into a fuel source (I can't remember which ones you will get)

Remember there are now a range of fuels that can be produced so you will have to use different combinations of the distiller and heat exchanger to try and figure out what's the best way to get the fuel you want.

**Comment by zainmajx** [comment]
@LuigiHutch Oh ok, that's pretty interesting, I'll experiment with the fuel types. TY for your help!
