### ISSUE TITLE
BC Quarry is doing something quite strange...

### ISSUE THREAD

**Issue by MarkisJr** [BuildCraft/BuildCraft#3739]
NOTE: I am playing on 1.11.2 with the mod being installed in this pack:
https://www.technicpack.net/modpack/the-good-old-days.737843

Vid of what happens:
https://www.youtube.com/watch?v=koFLN5iz51s&feature=youtu.be

Help would be awesome!!

**Comment by AEnterprise** [comment]
is this BC 7.99.6 with the kinesis pipes and recipes? the pack sais latest but this looks to me like 7.99.5 as this was fixed for 7.99.6

**Comment by MarkisJr** [comment]
Ok, I'll check

**Comment by MarkisJr** [comment]
Yes, the current version is 7.99.5, I'll ask dev if he can update to 7.99.6 asap. Cheers!
