### ISSUE TITLE
Quarry cannot handle non breakable fluids

### ISSUE THREAD

**Issue by Jude314** [BuildCraft/BuildCraft#3740]
I was using a quarry when it ran into some oil from galacticraft.  It then froze, and glitched back up to the top of the last fluid it hit. Please fix this.

**Comment by AEnterprise** [comment]
what BC/MC version are you using, can you provide screenshots or a video/gif of what heapens?

**Comment by Jude314** [comment]
I am using v1.11.2 of Minecraft and v7.99.6 of BC. Also, in the GIF, when I found the bug before, it would go back up to the top of the water and slowly make its way back down again. Although, that may have been another issue.

(The GIF does not represent my MC framerate)
![bug](https://user-images.githubusercontent.com/30223844/28271909-f1d40cf2-6ad7-11e7-8407-f0e79ecfabd0.gif)

**Comment by AEnterprise** [comment]
the quarry returning to the top i don't know what that would have been but the quarry does indeed stop when he gets to oil instead of skipping it

**Comment by AEnterprise** [comment]
so more details on this: if a fluid has a viscosity if over 1000 it is not skippable but but it is also not breakable, this case is not covered in the current logic of the quarry, the boxiterator is not advanced forward and it is not initiating a break task

it should skip the block in terms of breaking but should not be allowed to break the blocks under it (like in prev versions)

probably needs some of the task starting logic reworked for this

**Comment by Jude314** [comment]
Thank you very much for addressing this, I just want to express my gratitude for all of the hard work and development goes into these mods. Also, will this fix be coming out in BC's 1.12 version? Or will it be coming out with another patch to the 1.11.x version?

**Comment by AlexIIL** [comment]
Should be fixed in 7.99.8: https://www.mod-buildcraft.com/buildcraft-7998-alpha.html.
