### ISSUE TITLE
[1.11.2] [7.99.6] InvocationTargetException

### ISSUE THREAD

**Issue by bhi-elliot** [BuildCraft/BuildCraft#3741]
Hi there,

Not sure if this is causing problems, but the following messages come up in server log upon start. It happens twice during boot up.
Hope this helps!
[Pastebin](https://pastebin.com/UydkkgBn)

**Comment by AEnterprise** [comment]
currently BC is not fully compatible with sponge, it is being worked on

technicaly duplicate of #3700 (though it's one of those cases where you probably won't find it unless you knew it already)

**Comment by bhi-elliot** [comment]
Thank you for your work on this. Sounds like a big one.
Much appreciated.
