### ISSUE TITLE
Crash on loading screen, i think its a incompatible mod

### ISSUE THREAD

**Issue by WhyGamer** [BuildCraft/BuildCraft#3742]
I am using the next mods

Damage indicators 3.2.3
Treecapitor 2.0.4
Advanced Solar Paionels ADDON-IC2
Aether2 1.6
Appliedenergistics2-rv2-stable
ArchimedesShips-1.7.1
backpacks 2.0.1
BiomesOPlenty 2.1.0.1067
Carpenters-Blocks-Mod
ChickenChunks 1.3.4.19
chocolatequest-1.0
CodeChickenCore-1.0.7.46
Decocraft 1.10
DynamicLights
Enchanting-Plus-Mod
EnderStorage 1.4.7.33
ExtrabiomesXL
Extra-Utilities-Mod
GalacticraftCore 3.0.11.333
Galacticraft-Planets 3.0.11.333
gilded-games-util 1.9
Gravitation-Suite-ADDON-IC2
IChunUtil 4.2.2
industrialcraft-2 2.2.827
Infernal-Mobs-Mod
Iron-Chests-Mod
Mantle 0.3.2
MapWriter-Mod
meteors 2.1.13.1
MicdoodleCore 3.0.11.333
More-Bows-2-Mod
More-Furnaces-Mod
Morph-Beta 0.9.1
NotEnoughtItems 1.0.5.110
OpenBlocks 1.4.4
OpenModsLib 0.8
OptiFine
Orespawn 20.3
Pam's HarvesCraft
Portal-Gun-Mod
SoundFilters 0.8
TConstruct 1.8.5
Thaumcraft 4.2.3.5
Twilight-Forest-Mod
UpdateCheckerMod
Waila 1.5.10
Wild-Caves-Mod

I really dont know why this is happening, but i want to play with a friend

**Comment by AlexIIL** [comment]
Can you upload the crash report to gist.github.com, and put a link to it here? Otherwise we have no way of helping.
.

**Comment by AEnterprise** [comment]
Closing for a lack of information, if you provide the requested information we can re-open and take another look at this.
