### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Technorico** [BuildCraft/BuildCraft#3746]
I understand the choice to skip version 1.10, but could you do another mod, only with your quarry and landmarks and related stuff?

Sorry for terrible English, but I'm not a mother tongue

**Comment by AEnterprise** [comment]
no we will not go back, only porting quarry and requirements is completely pointless, there are plenty of other mods you can use that have their own form of quarry

BC is also much more then just the quarry, only porting the quarry and not the rest would cause a bigger outrage in the community then there already is today about this subject

also in the future please ask your questions in our discord so we can focus on bug reports here: https://discordapp.com/invite/QZAtRuM
