### ISSUE TITLE
Volume Box broken

### ISSUE THREAD

**Issue by TheArchitect02** [BuildCraft/BuildCraft#3751]
The Volume Box's name has changed to _item.volume_box.name_ and it cannot be destroyed or resized.

BC Version: 7.99.5

**Comment by LuigiHutch** [comment]
Yes it can. Right click a corner of it with a marker connector to resize it and shift right click it with a marker connector to destroy it

**Comment by AEnterprise** [comment]
volume box works (but indeeds needs localizing), also the latest version of BC is 7.99.6, it adds a few missing recipes so you might want to update
