### ISSUE TITLE
Buildcraft quarry wont work

### ISSUE THREAD

**Issue by calser** [BuildCraft/BuildCraft#3756]
The buildcraft quarry wont connect to anything and also wont get any power from engines

**Comment by AEnterprise** [comment]
what engines are you using? BC version? maybe a screenshot of your setup? if you are using the latest BC release for MC 1.11.2 and not using BC engines (directly or with kinesis pipes) you will not be able to power your quarry, BC uses MJ now and so far only a few addons support it

**Comment by calser** [comment]
Thanks for the help it worked! i connected some stirling engines with buildcraft pipes.
still i am sad that i could not connect it with thermal foundation conduits, will this be a possibility in the future?

**Comment by LuigiHutch** [comment]
No, not without a converter mod anyway. BC is an MJ mod and has no plans to add any RF -> MJ conversion at this time.
