### ISSUE TITLE
I can't take refined oil out of destiller

### ISSUE THREAD

**Issue by RecctMemes** [BuildCraft/BuildCraft#3757]
When i go to draw the fuel from the refinery it doesnt do anything, and i am using liquid pipes and engines.  Yet it doesn't work?

**Comment by LuigiHutch** [comment]
Im guessing you are on 7.99.6? You have to extract fluids out the top and bottom of the distiller. See this basic guide on the new distiller and heat exchanger: http://imgur.com/a/AXUOX
