### ISSUE TITLE
Can't connect anything to buildcraft quarry

### ISSUE THREAD

**Issue by Diamond45123** [BuildCraft/BuildCraft#3758]
Build number : 7.99.6
I can't connect anything to it! wireless senders from extra utilites aren't working. Mekanism Universal wires aren't working too.. Help?

**Comment by LuigiHutch** [comment]
Duplicate of: https://github.com/BuildCraft/BuildCraft/issues/3708. Use BC engines or use some converter mod

**Comment by Diamond45123** [comment]
wait, so i can't use the energy cubes that can be filled with MJ?

**Comment by LuigiHutch** [comment]
Mekanism doesn't use MJ, it uses 'joules' which is its own internal power system and is not compatible with BC's MJ

**Comment by Diamond45123** [comment]
Ooh. lol i seem stupid now. Thanks. I used a energy converter and it worked.
