### ISSUE TITLE
Robots not charging when docking station has power? BC version 7.1.22

### ISSUE THREAD

**Issue by force2525** [BuildCraft/BuildCraft#3759]
![image](https://user-images.githubusercontent.com/30555434/28746720-f7bdb036-74d3-11e7-9650-1591b03dbf3c.png)

**Comment by dj3520** [comment]
try putting it on a kinesis pipe that isn't an extractor

**Comment by force2525** [comment]
I've tried gold, diamond, quartz and emerald same result.

**Comment by AEnterprise** [comment]
did you pot those other pipes directly on the energy cell or with a wooden kinesis pipe in between?

**Comment by force2525** [comment]
They were all on the cell only tried wooden pipes last. The pipes and docking stations are getting power i just can't work out why it isn't going into the robots.

**Comment by force2525** [comment]
Could it be part of Project Ozone 2 Kappa mode?

**Comment by LuigiHutch** [comment]
Put a normal kinesis pipe next to the wooden kinesis pipe so they connect. Then put the docking station and the robot on that normal kinesis pipe and it should work

**Comment by force2525** [comment]
OMG that works. Thanks so much
