### ISSUE TITLE
Conductive tubes

### ISSUE THREAD

**Issue by superkakamil** [BuildCraft/BuildCraft#3760]
Conductive tubes do not connect to motors from other modes.
![2017-07-30_08 51 31](https://user-images.githubusercontent.com/30565528/28751351-76e2f764-7505-11e7-8464-a8b757ee76a2.png)

**Comment by LuigiHutch** [comment]
This is because 'kinesis pipes' transport MJ and not RF. Forestry, like almost all other mods atm, do not support MJ and will not until BC reaches a stable release and we stop making breaking changes to the api.

The forestry team said they will most likely support it once we reach 8.0.0

**Comment by KiraAmano** [comment]
Does this also apply to the buildcraft engines not hooking up to their autofarms?

**Comment by AEnterprise** [comment]
yes, Buildcraft and forestry currently do not use the same powersytem so they cannot connect to one another

**Comment by KiraAmano** [comment]
Thanks for the timely responses! Glad to know I wasn't screwing something up when trying to connect the engines

**Comment by Anora** [comment]
hope this is fixed soon I always used Buildcraft engines to power all my RF based machines

**Comment by AEnterprise** [comment]
@Anora there isn't realy anything to 'fix' here. Buildcraft has moved back to using and producing MJ. Forestry (and other mods integrating with BC) might add compat to be powered with MJ as well but that is up to the authors of those mods

if you realy want to use MJ to power all your RF machines you probably want to look into adding an conversion mod

**Comment by Anora** [comment]
never needed to do that before

**Comment by LuigiHutch** [comment]
That's because in 1.7.10 BC actually used rf. 

That is not the case anymore. This is an intentional design decision and there are plans on changing it.

**Comment by SalvadorScalia** [comment]
https://ftbwiki.org/Electrical_Engine


this is the true

**Comment by AEnterprise** [comment]
@SalvadorScalia that wiki is oudated and no longer acurate

**Comment by SalvadorScalia** [comment]
@AEnterprise sorry, I did not want to confuse the subject anymore.
