### ISSUE TITLE
Quarry stops before bedrock by 8 blocks.

### ISSUE THREAD

**Issue by Diamond45123** [BuildCraft/BuildCraft#3765]
Title says it. I just got a new extreme reactor. and then i gone to my quarry to find that it finished but it didnt reach bedrock! ( i knew it finished because any type of engine isn't working also)
my set up : http://i.imgur.com/PLYqTRW.png

**Comment by Diamond45123** [comment]
After testing more, the quarry quickly replaces the frames although it doesn't break blocks

**Comment by AEnterprise** [comment]
what BC version are you using? the quarry not moving does not mean it's ready by definition, could you check the block the drill is trying to mine? if it's a fluid block this is most likely a case of #3740

**Comment by Diamond45123** [comment]
Buildcraft version 7.99.6. There are no fluids in 5th way except water which quarries have no problem on mining on.

**Comment by Diamond45123** [comment]
In the way*

**Comment by AEnterprise** [comment]
alright could you then (in creative) bring up the F3 debug info and look at the quarry and provide a screenshot of it (if the info doesn't all fit please reduce the your gui scale in the settings for the screenshot), as well as a screenshot of where the drill is and what it should be trying to break

**Comment by Diamond45123** [comment]
It was trying to break destablized redstone.. I tried removing it out of its way but i didnt work and for the screenshot i don't have access to my computer right now.

**Comment by AEnterprise** [comment]
destabilized redstone is indeed a fluid it cannot break, try putting a block it can break (like cobble or so) in the position the destabilized redstone was (or a block before it if that doesn't help), it should give it a 'reset' and try again, also if there is anymore destabilzed redstone best to move that out of the way as well

**Comment by Diamond45123** [comment]
Keep in mind that this isn't a fluid it's a block called destablized redstone ore. Although I will try what you said when I have access to my computer

**Comment by Diamond45123** [comment]
Okay, so. I got into my world and broke the quarry and replaced it and then it placed all the frames.. it gone down to the EXACT location and stopped. I tried 'resetting' it. It just broke the block i placed and gone to the exact location and stopped. i tried removing every block in its current path and replacing it with stone but nope, doesn't work too. ((yes im using a creative engine cause im not wasting my stuff on that))
what it is trying to break : http://i.imgur.com/bHtKSiG.png
debug : http://i.imgur.com/8DCvena.png
It seems like the quarry has no power in the client??

**Comment by AEnterprise** [comment]
somehow the quarry logic there is failing to start a task there so there is something causing it to mess up

**Comment by Diamond45123** [comment]
Soo, what do i do? :O

**Comment by AEnterprise** [comment]
i don't think there is anything you can do atm yourself, are you playing on publicly available modpack?

**Comment by Diamond45123** [comment]
No, i made it.

**Comment by Lynxn** [comment]
If I may comment: Even though said block is an or, when the or breaks it let's out a bit of fluid and the quarry may not like that since it can't go through the destabilized redstone fluid.

**Comment by Diamond45123** [comment]
I removed all those from its path soo..

**Comment by AEnterprise** [comment]
if it lets out a bit of fluid when you break it that's probably why it got stuck. now you got rid of all those blocks and fluid blocks try placing a block one layer (y-level) above where it got stuck

**Comment by AlexIIL** [comment]
Should be fixed in 7.99.8: https://www.mod-buildcraft.com/buildcraft-7998-alpha.html.
