### ISSUE TITLE
IFacadePluggable and IFacadeItem

### ISSUE THREAD

**Issue by rikka0w0** [BuildCraft/BuildCraft#3773]
Seems that IFacadePluggable has been deprecated...
IFacadeItem represents a facade item, however that's no way to know if the facade is hollow or not.

If isHollow() method is added to IFacadeItem it would be very helpful.

PS: I'm working on a mod which is designed to work closely with BuildCraft facades and machines

**Comment by AEnterprise** [comment]
the api has been reworked alot so it is entirely possible we some things got missed

i'll see if we can add in the hollow method for the next update

for the rest we should probably do a full api review at the end of the alpha stage

**Comment by AlexIIL** [comment]
@rikka0w0 I've got a better representation in the commit linked, will that API work? (or do you need anything else / have I missed anything)

**Comment by rikka0w0** [comment]
The new façade API looks pretty well
Thanks for spending time on fixing this problem
