### ISSUE TITLE
1.11.2 Game crashes when IC2 construction foam is being tried to put into BC tank

### ISSUE THREAD

**Issue by Supermantvis** [BuildCraft/BuildCraft#3774]
**Buildcraft** version: 7.99.6
**Forge** version: 1.11.2-13.20.1.2429

Link to crashreport or log (on pastebin or gist, please don't put the entire log here) :
[12:46:15] [Thread-11/INFO]: [STDOUT]: Block file not found: buildcraftenergy:fluid_block_oil_heat_0

Singleplayer/multiplayer: Both

Additional information: Game freezes/crashes when IC2 construction foam is being tried to put into BC tank, either manually by using IC2 cells or via fluid canning machine block with fluid ejectors to BC tank.
Is there a simple way I could fix this in text/config file myself??

**Comment by AlexIIL** [comment]
Can you upload your entire log file or crash to https://gist.github.com/, it looks like you've just pasted one of the lines in the log instead.

**Comment by Supermantvis** [comment]
Hi AlexIIL,

Is that ok? I'm doing this first time

https://gist.github.com/Supermantvis/323499a0e8d3cb421abb8204c8283460

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by AEnterprise** [comment]
almost that's a log but not the one we are looking for, can you upload `latest.log` from that folder or the most crash report file from the `crash-reports` folder?

**Comment by Supermantvis** [comment]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Supermantvis** [comment]
Here's the one I've uploaded to *gist.github*:
https://gist.github.com/Supermantvis/c888a69533f71f8a359eb29ee953c2ae

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by AEnterprise** [comment]
replying via email in this case isn't working very well, the first was just you avast signature, the second is the link to the gist but that doesn't contain the crash, can you provide the crashlog?

**Comment by Supermantvis** [comment]
There's no crash report


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Supermantvis** [comment]
The game just frezes, you can move around but only you, anything else is
frozen and can't access inventory nor any block UI's

**Comment by Supermantvis** [comment]
And it looks like BC tank won't accept any IC2 cell liquid. . . .

**Comment by AEnterprise** [comment]
this isn't a chat, please just put it all in 1 email/message or join the discord if you want to chat.

if the game freezes but didn't crash on its own could eighter use the sampler mod to get a stall report, or use a tool like visualVM to get a threaddump when the game is frozen?

**Comment by Supermantvis** [comment]
Where or how can I join you guys?

**Comment by XxZajoZzO** [comment]
https://discord.gg/vRX7uV

**Comment by AEnterprise** [comment]
still waiting on response from IC2 (https://bt.industrial-craft.net/view.php?id=2255)
