### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ArtElleys** [BuildCraft/BuildCraft#3775]
Hello, thank you for being there that you support the mod, I just because of it and continue to play in Minecraft. Because I like to look at the resources running through the pipes)))

But still I like to look not only at the pipes, but I like all the processes in general.

So I would like to suggest, most likely you have already been offered or you will not do it, but I'll still write.

Multi-block structures. Every time playing in your mod, I'm very pleased with the pipes, but from that very moment nothing has changed in principle (well, except for robots). Your mod is super, but I want to see production ...

I here recently was at the slag-block factory (produces a heater for houses). So, I saw how this happens, we take basalt, then we melt it in a giant oven, to magma. Then all this is thrown into the centrifuge. After the magma is formed a fiber, and the residual metals fly into another tube. After this, the fiber is collected, compacted, cut and packed. And all this goes on a conveyor belt and with the help of robots. And the standing of such plants, it would be super ....

1) Revisit the quarry so that it costs more, because if you only play for default in your mod, you can reach it in a couple of hours and then not bathe.
By the way, yes, I could say that such things are better to propose to other mododels, such as Fashion Industrial Craft, but I do not like it and do not like that your mod is a plus to it, and not all the fashion is a plus to you.
2) Redo all the machines that exist now in multi-block structures, with the ability to see a certain production process, and divide the processes into components.
3) The ability to change the standard kraft (as an example, to create a diamond picks, you need on the gates, create a laser from a diamond cutter and in a special machine to create a drill for a quarry). Why I am very interested in changing the standard equipment, because, with a common pick, when a large team of players plays, the quarry becomes unnecessary.
4) All on the same topic. It would be interesting if the stove and workbench were changed. Maybe I just played enough of other mods like TerraFirmaCraft, Gregtech, Applied Energistics (By the way, it seems to be closed or something like that, because I would very much like that some of the messages from there can be found by someone who grabbed and used it), Taumcraft The trouble of mods was closed). And in general a lot of cool mods are closed, only your mod remains (Mod old man). Tinkers' Construct (But with the arrival of new owners, and the advent of new versions, without addons.) In the mod it became not interesting to play).

So that's just probably you can help)))

Rest

1) Add the gears to the game (you have them as a craft, there are some models, but they are not independent designs).

2) Add more mechanical structures, for example a water wheel, a millstone (and a mill in addition), a gate and a lifting bridge, and so on.

Thank you for reading and hearing me.

**Comment by LuigiHutch** [comment]
Thanks for the suggestions but the issue tracks isn't really the place for suggestions, that would be better suited for the discord. 

As for some of the suggestions:
There is no point in turning single blocks into multi blocks just for the sake of it, there will have to be a reason to do so.

Making the quarry more expensive is pointless, it's the power needed to power it is the real progress gate

Changing recipes can be done by other mods like mine tweaker, no need to natively support it.

**Comment by AEnterprise** [comment]
like luigi said: thanks but this isn't the best place

for multiblocks: alot of BC is already kind of a multiblock, they might all be single blocks but they need others to work (quarry places frames, tables need lasers, ...)

point 4 about the workbench also doesn't make sense to me, i guess it got lost in translation

point 1 of rest i guess you are asking to be able to place gears in the world? this would not make sense eighter, they wouldn't do anything (except being decorative), and making them turn would server no purpose, we are not going to make a gear turning based power system

adding those mechanical structures is probably not gona heapen eighter, a water wheel and mill are passive powergen (big nope), gates and lifting bridges are extremely complex and woudn't realy fit into BC, there are a few other mods that can do this already if you want this
