### ISSUE TITLE
1.11.2 - quarry erroneously waste a lot of time and energy after solid block reappears in the mining area

### ISSUE THREAD

**Issue by Akiraru** [BuildCraft/BuildCraft#3776]
**Buildcraft** version: 7.99.6
**Forge** version: 1.11.2-13.20.1.2429

In case a solid block is placed in the area that the quarry mined already (a few layers above for example), after it's demolition the mining tip does not go to the next solid block available using the shortest path - but instead it goes sequentially all through the empty areas, block by block and layer by layer.

**Comment by AlexIIL** [comment]
Should be fixed in 7.99.8: https://www.mod-buildcraft.com/buildcraft-7998-alpha.html.
