### ISSUE TITLE
The distiller does not work

### ISSUE THREAD

**Issue by Herobrine31956** [BuildCraft/BuildCraft#3782]
**Buildcraft** version: 7.99.7
**Forge** version: 1.11.2
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: 

Additional information:the distiller dose not work for me.the oil goes in the false tank.

**Comment by AEnterprise** [comment]
are you sure it's not going into the input tank? the distiller doesn't work like the old refinery. Are you using it correctly (see http://imgur.com/a/AXUOX for a guide or some of the builds in the showcase channel of the discord  https://discord.gg/v4geqgA )

if that doesn't help you fix it can you show some screenshots of your setup so we can see what's going on?

**Comment by HenrikoMagnifico** [comment]
I love the guy making this this fork, I really appreciate it! Although are there any news on when the next update will be released here on GitHub? Transportation pipes are making the game crash right now making most things pointless!

**Comment by AEnterprise** [comment]
are you still having issues with the distiller?

**Comment by Herobrine31956** [comment]
No

Von meinem iPad gesendet

Am 26.08.2017 um 16:11 schrieb AEnterprise <notifications@github.com<mailto:notifications@github.com>>:


are you still having issues with the distiller?
