### ISSUE TITLE
Assembly Table & Integration Table recipes not detected by JEI

### ISSUE THREAD

**Issue by jdkorv11** [BuildCraft/BuildCraft#3785]
The title pretty much has all the information. Recipes for the assembly and integration tables are not shown by JEI (Just Enough Items) which makes it exceedingly difficult to figure out how to make some items (pipe pulsars, pipe wires, facades, etc.)

I'm yet to figure out how to make items whose recipe has changed (eg. pulsating chip-set, pipe pulsar) from older versions of buildcraft as there is no in-game way to look up the recipes for these tables and there (understandably) are not yet user docs for buildcraft 8. Some method of looking up assembly and integration table recipes in game, either by supporting JEI, or having a guide book of some kind, would be a huge help for exploring that part of buildcraft

**Comment by AEnterprise** [comment]
there already is a guide book in the works (available ingame but not alot of content yet)

JEI integration is also something that's planned but since we are still in alpha we want to focus on BC itself before looking into to much mod compat
