### ISSUE TITLE
Crash on Wooden Pipe and Redstone Engine interaction

### ISSUE THREAD

**Issue by romacm** [BuildCraft/BuildCraft#3786]
**Buildcraft** version: 7.1.22
**Forge** version: 10.13.4.1614

Additional information:
Game crashes when I append Redstone Engine to Wooden Pipe.
[crash-2017-08-23_04.46.08-client.txt](https://github.com/BuildCraft/BuildCraft/files/1244030/crash-2017-08-23_04.46.08-client.txt)

**Comment by AEnterprise** [comment]
you are missing the RF api, BC 7.1.22 requires it, please add COFH core or any other mod that ships the RF api
