### ISSUE TITLE
Goggle duplication

### ISSUE THREAD

**Issue by JustWannaFly** [BuildCraft/BuildCraft#3789]
Holding goggles in the players hand and then shift + right clicking to equip them will result in equipping the goggles and having a duplicated pair left in the hand

**Buildcraft** version: [dev build](https://github.com/BuildCraft/BuildCraft/pull/3788/commits/3e065a1dc7266bd9dd1c20e1c6e70d26329a9c0f)
Singleplayer/multiplayer: observed on single player, haven't checked multiplayer

**Comment by AEnterprise** [comment]
is it possible you where in creative?

**Comment by JustWannaFly** [comment]
...oops... forgot that was a thing. Only happens in creative mode and not in survival.
