### ISSUE TITLE
It just crashes becausen of a conflict but idk what one it is.

### ISSUE THREAD

**Issue by BlueYoshi68** [BuildCraft/BuildCraft#3791]
`---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 8/27/17 1:36 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: logger
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: logger
	at buildcraft.BuildCraftCore.loadConfiguration(BuildCraftCore.java:276)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 161409656 bytes (153 MB) / 764383232 bytes (728 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D6 94 mods loaded, 94 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UCH	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCH	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCH	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCH	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UCH	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCE	BuildCraft|Core{7.1.22} [BuildCraft] (buildcraft-7.1.22.jar) 
	UCE	BuildCraft|Energy{7.1.22} [BC Energy] (buildcraft-7.1.22.jar) 
	UCH	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCH	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.462.jar) 
	UCH	SpaceCore{4.1.9} [4Space Core] (4Space-4.1.9.jar) 
	UCH	ExoCore{0.1.2} [4Space Exoplanets Core] (4Space-4.1.9.jar) 
	UCH	ExoElipse{0.1.2} [4Space Exoplanets Elipse] (4Space-4.1.9.jar) 
	UCH	SpaceCallisto{4.1.9} [4Space Callisto] (4Space-4.1.9.jar) 
	UCH	SpaceEuropa{4.1.9} [4Space Europa] (4Space-4.1.9.jar) 
	UCH	SpaceVenus{4.1.9} [4Space Venus] (4Space-4.1.9.jar) 
	UCH	SpaceIo{4.1.9} [4Space Io] (4Space-4.1.9.jar) 
	UCH	SpaceMercury{4.1.9} [4Space Mercury] (4Space-4.1.9.jar) 
	UCH	SpacePluto{4.1.9} [4Space Pluto] (4Space-4.1.9.jar) 
	UCH	divinerpg{1.4.1.3} [DivineRPG] ([1.7.10][SMP]DivineRPG-1.4.1.3.jar) 
	UCH	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
	UCH	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCH	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCH	advancedgenetics{1.5.8} [Advanced Genetics] (advancedgenetics-1.7.10-1.5.8.jar) 
	UCH	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCH	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCH	AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-1.7.10-1.5.0.jar) 
	UCH	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) 
	UCH	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCH	BetterSprinting{1.1.3} [Better Sprinting] (BetterSprinting  MC-1.7.10  v1.1.3.jar) 
	UCH	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCH	betterstorage{0.9.4.111} [BetterStorage] (BetterStorage-1.7.10-0.9.4.111.jar) 
	UCH	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) 
	UCH	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCH	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCE	BuildCraft|Transport{7.1.22} [BC Transport] (buildcraft-7.1.22.jar) 
	UCE	BuildCraft|Factory{7.1.22} [BC Factory] (buildcraft-7.1.22.jar) 
	UCE	BuildCraft|Silicon{7.1.22} [BC Silicon] (buildcraft-7.1.22.jar) 
	UCE	BuildCraft|Robotics{7.1.22} [BC Robotics] (buildcraft-7.1.22.jar) 
	UCE	BuildCraft|Builders{7.1.22} [BC Builders] (buildcraft-7.1.22.jar) 
	UCH	Railcraft{9.12.2.0} [Railcraft] (Railcraft-Mod-1.7.10.jar) 
	UCH	UniversalElectricity{@MAJOR@.@MINOR@.@REVIS@} [Universal Electricity] (universal-electricity-mod-1.7.10.jar) 
	UCH	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCH	CarpentersBlocks{3.3.8} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8 - MC 1.7.10.jar) 
	UCH	ChestTransporter{2.0.6} [Chest Transporter] (ChestTransporter-1.7.10-2.0.6.jar) 
	UCH	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar) 
	UCH	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCH	cookingbook{1.0.140} [Cooking for Blockheads] (cookingbook-mc1.7.10-1.0.140.jar) 
	UCH	CustomMainMenu{1.1} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.1.jar) 
	UCH	Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281.jar) 
	UCH	DefenseTech{1.0.1} [DefenseTech] (DefenseTech-1.7.10-1.0.1.46.jar) 
	UCH	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCH	ThermalExpansion{1.7.10R4.1.4} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.4-247.jar) 
	UCH	DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2h.jar) 
	UCH	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) 
	UCH	endercore{1.7.10-0.2.0.36_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.36_beta.jar) 
	UCH	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCH	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCH	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
	UCH	Forestry{4.2.16.64} [Forestry for Minecraft] (forestry_1.7.10-4.2.16.64.jar) 
	UCH	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.462.jar) 
	UCH	gendustry{1.6.3.132} [GenDustry] (gendustry-1.6.3.132-mc1.7.10.jar) 
	UCH	lootbags{2.0.16} [Loot Bags] (LootBags-1.7.10-2.0.16.jar) 
	UCH	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCH	mcheli{0.10.6} [MC Helicopter] (mcheli) 
	UCH	MekanismGenerators{9.1.0} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.0.281.jar) 
	UCH	MekanismTools{9.1.0} [MekanismTools] (MekanismTools-1.7.10-9.1.0.281.jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCH	VoltzEngine{0.27.4.345} [VoltzEngine] (VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar) 
	UCH	mffs{0.50} [Modular Forcefield System] (Mffs-1.7.10-0.0.50b20170204132137-universal.jar) 
	UCH	numina{0.4.0.131} [Numina] (Numina-Mod-1.7.10.jar) 
	UCH	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
	UCH	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCH	powersuits{0.11.0.301} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.301.jar) 
	UCH	reborncore{1.0.0.8} [RebornCore] (RebornCore-1.0.0.8-universal.jar) 
	UCH	ResourceLoader{1.3} [Resource Loader] (ResourceLoader-MC1.7.10-1.3.jar) 
	UCH	rftools{4.23} [RFTools] (rftools-4.23.jar) 
	UCH	techreborn{0.7.19.1115} [TechReborn] (TechReborn-1.7.10-0.7.19.1115-universal.jar) 
	UCH	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UCH	tc{4.3.0_002} [Traincraft] (TrainCraft-4.3.0_002.jar) 
	UCH	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	UCH	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCH	voxelmap{1.7.10} [VoxelMap No Radar] (Zans-Minimap-No-Radar-Mod-1.7.10.jar) 
	UCH	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
	UCH	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon HD 7560D'
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.4-247
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.2.1-172
	List of loaded APIs: 
		* AgriCraftAPI (1.0) from AgriCraft-1.7.10-1.5.0.jar
		* Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
		* BiomesOPlentyAPI (1.0.0) from BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar
		* BloodMagicAPI (1.3.3-13) from BloodMagic-1.7.10-1.3.3-17.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.22.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.22.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.22.jar
		* BuildCraftAPI|core (1.0) from Railcraft-Mod-1.7.10.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.1.22.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.1.22.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.22.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.22.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.22.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.22.jar
		* BuildCraftAPI|items (1.1) from Railcraft-Mod-1.7.10.jar
		* BuildCraftAPI|library (2.0) from Railcraft-Mod-1.7.10.jar
		* BuildCraftAPI|lists (1.0) from Railcraft-Mod-1.7.10.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.22.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.1.22.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.22.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.1.22.jar
		* BuildCraftAPI|tablet (1.0) from Railcraft-Mod-1.7.10.jar
		* BuildCraftAPI|tiles (1.2) from Railcraft-Mod-1.7.10.jar
		* BuildCraftAPI|tools (1.0) from Railcraft-Mod-1.7.10.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.1.22.jar
		* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.8 - MC 1.7.10.jar
		* ChiselAPI (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Carving (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Rendering (0.1.1) from Chisel-2.9.5.11.jar
		* CoFHAPI (1.7.10R1.0.10) from Mffs-1.7.10-0.0.50b20170204132137-universal.jar
		* CoFHAPI|block (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381.jar
		* CoFHAPI|core (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from RebornCore-1.0.0.8-universal.jar
		* CoFHAPI|fluid (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|inventory (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|item (1.7.10R1.0.10) from Mffs-1.7.10-0.0.50b20170204132137-universal.jar
		* CoFHAPI|modhelpers (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|tileentity (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|transport (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381.jar
		* CoFHAPI|world (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|audio (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|container (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|element (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|slot (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|inventory (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|render (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|render|particle (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|util (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|util|helpers (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|util|position (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|world (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|world|feature (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* ComputerCraft|API (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|FileSystem (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Lua (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Media (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Peripheral (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Permissions (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Redstone (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Turtle (1.75) from ComputerCraft1.75.jar
		* DraconicEvolution|API (1.2) from Draconic-Evolution-1.7.10-1.0.2h.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* ForestryAPI|apiculture (4.8.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|core (5.0.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|fuels (2.0.1) from TechReborn-1.7.10-0.7.19.1115-universal.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|world (2.1.0) from forestry_1.7.10-4.2.16.64.jar
		* Galacticraft API (1.3) from GalacticraftCore-1.7-3.0.12.462.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.3.132-mc1.7.10.jar
		* IC2API (1.0) from industrialcraft-2-2.2.827-experimental.jar
		* McJtyLib (1.8.1) from mcjtylib-1.8.1.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* MekanismAPI|reactor (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* MekanismAPI|recipe (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.7.10-9.1.0.281.jar
		* RailcraftAPI|bore (1.0.0) from TrainCraft-4.3.0_002.jar
		* RailcraftAPI|carts (1.6.0) from TrainCraft-4.3.0_002.jar
		* RailcraftAPI|core (1.5.0) from Railcraft-Mod-1.7.10.jar
		* RailcraftAPI|crafting (1.0.0) from TrainCraft-4.3.0_002.jar
		* RailcraftAPI|electricity (2.0.0) from TrainCraft-4.3.0_002.jar
		* RailcraftAPI|events (1.0.0) from TrainCraft-4.3.0_002.jar
		* RailcraftAPI|fuel (1.0.0) from TrainCraft-4.3.0_002.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft-Mod-1.7.10.jar
		* RailcraftAPI|items (1.0.0) from Railcraft-Mod-1.7.10.jar
		* RailcraftAPI|locomotive (1.1.0) from Railcraft-Mod-1.7.10.jar
		* RailcraftAPI|signals (2.3.0) from Railcraft-Mod-1.7.10.jar
		* RailcraftAPI|tracks (2.3.0) from Railcraft-Mod-1.7.10.jar
		* reborncoreAPI (1.0.0.8) from RebornCore-1.0.0.8-universal.jar
		* techrebornAPI (0.7.19.1115) from TechReborn-1.7.10-0.7.19.1115-universal.jar
		* Thaumcraft|API (4.2.2.0) from Railcraft-Mod-1.7.10.jar
		* VoltzEngineAPI (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|crafting-items (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|data (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|energy (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|energy-items (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|event (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|explosive-items (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|explosives (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|items (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|recipe (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|tile (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|tools (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* VoltzEngineAPI|weapons (0.10.0) from VoltzEngine-1.7.10-0.27.4b345-dev-universal.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.200.1062.1004
	OpenGlRenderer: AMD Radeon HD 7560D
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4`

**Comment by AEnterprise** [comment]
There was an issue template, if you report bugs in the future please fill that in and link to the crashlog instead of this wall of text.

As for the crash itself: looks like one of your mods is providing an outdated api, try updating them or removing the buildcraft folder from the jars

**Comment by BlueYoshi68** [comment]
Any idea which one? and what build craft "folder"?

**Comment by afdw** [comment]
`* BuildCraftAPI|core (1.0) from Railcraft-Mod-1.7.10.jar` this one maybe?

**Comment by BlueYoshi68** [comment]
oh. maybe

**Comment by BlueYoshi68** [comment]
ill try
it

**Comment by AEnterprise** [comment]
yeah also that filename does not sound like it's from an official source, most likely from an non official site that rehosts it

**Comment by BlueYoshi68** [comment]
which one rail craft or buildcraft?

**Comment by AEnterprise** [comment]
railcraft

**Comment by BlueYoshi68** [comment]
i got it from curse so idk

**Comment by BlueYoshi68** [comment]
https://minecraft.curseforge.com/projects/railcraft/files/2299713

**Comment by AEnterprise** [comment]
well unless you renamed the file yourself (i don't see why you would do that though) the filename doesn't match the name of the file you linked

**Comment by BlueYoshi68** [comment]
weird

**Comment by BlueYoshi68** [comment]
alright
now im still crashing
https://pastebin.com/nemkZd9S

**Comment by BlueYoshi68** [comment]
It still crashes for some reason
[https://pastebin.com/nemkZd9S](url)

**Comment by AEnterprise** [comment]
please do not just spam the issue tracker with asking the same again before anyone even had a chanse to look at it (it's also not a chat)

please try with just buildcraft installed, if it doesn't crash then it's another mod shipping an outdated API, you can then use a binary search (remove half the mods at a time to see in what half it is, then split again and again until you find it)

**Comment by BlueYoshi68** [comment]
Yeah im sorry, didnt mean to. But i think i figured it out.
