### ISSUE TITLE
Improve laser targetting

### ISSUE THREAD

**Issue by AEnterprise** [BuildCraft/BuildCraft#3793]
Currently lasers are constantly looking for targets when they realy don't have to. It would be much better to only iterate once on the first tick to do an initial collection of targets, after that it could listen to block changes in the world to add/remove target locations

this would mean alot less ticktime for the lasers and we can probably also lose the requirement of blocks implementing the interface because we will not be requesting TE's often anymore

@JustWannaFly interested in taking a look at this?

**Comment by iTitus** [comment]
Superseded by #3796

**Comment by AEnterprise** [comment]
Nope. That one made it sync only when needed. This is about not constantly looking for laser targets

**Comment by iTitus** [comment]
Then I could take a look at this too

**Comment by JustWannaFly** [comment]
I just submitted a pull request that completes this so there shouldn't be a need to look into it further

**Comment by JustWannaFly** [comment]
This is now fixed in dev [commit](https://github.com/BuildCraft/BuildCraft/commit/3398f90eb7e7e9600330af652dad4c3d27b83da8)

**Comment by AlexIIL** [comment]
Should be fixed in [7.99.8](https://www.mod-buildcraft.com/buildcraft-7998-alpha.html).
