### ISSUE TITLE
Filler causes crash on placement [BC 7.99.7]

### ISSUE THREAD

**Issue by dj3520** [BuildCraft/BuildCraft#3797]
**Buildcraft** version: 7.99.7
**Forge** version: 13.20.1.2454 
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : https://paste.ee/p/4bvqc
Singleplayer/multiplayer: Singeplayer, Creative (others not tested)

Additional information:
Crash on placing the filler block in the world.

**Comment by afdw** [comment]
Looks like it was fixed in https://github.com/BuildCraft/BuildCraft/commit/96ad84fc04dc4fe874c0adbe2acfb8cdf97cfd62.

**Comment by AEnterprise** [comment]
was it? on that line you only removed a null check yet the crash is that something was null so i doubt it's fixed
