### ISSUE TITLE
red block outline under textures

### ISSUE THREAD

**Issue by fartmamn** [BuildCraft/BuildCraft#3798]
[Minecraft 1.11.2 2017-08-30 2_20_17 PM.zip](https://github.com/BuildCraft/BuildCraft/files/1264817/Minecraft.1.11.2.2017-08-30.2_20_17.PM.zip)

*Buildcraft** version: 7.997
**Forge** version: 1.11.2-13.2.1.2386
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: Singleplayer

Additional information: a video of the problem in the zip file
[Minecraft 1.11.2 2017-08-30 2_20_17 PM.zip](https://github.com/BuildCraft/BuildCraft/files/1264829/Minecraft.1.11.2.2017-08-30.2_20_17.PM.zip).

**Comment by afdw** [comment]
Set Options -> Video Settings -> 3D Anaglyph to OFF.
