### ISSUE TITLE
blast furnace [1.11.2]

### ISSUE THREAD

**Issue by RaStreet** [BuildCraft/BuildCraft#3799]
**Buildcraft** version: 7.99.7(last)
**Forge** version: 1.11.2
Additional information:

blast furnace does not work. I craft, set, connect Solid fuel heat generator, liquid generator - 
0 reactions. The oven does not work, does not heat up.

**Comment by dj3520** [comment]
Buildcraft does not have a blast furnace. Please check which mod your blast furnace is from and report to them.

**Comment by RaStreet** [comment]
ic2, sry.
