### ISSUE TITLE
Redstone comparator on tank does not update.

### ISSUE THREAD

**Issue by dj3520** [BuildCraft/BuildCraft#3800]
**Buildcraft** version: 7.99.7
**Forge** version: 13.20.1.2454
No crash = N/A
Singleplayer/Multiplayer: Singleplayer, Creative (others not tested)
Redstone comparator does not update when connected to buildcraft tank. One can force this to update by toggling the comparator's mode (compare/subtract). Additionally, the "Redstone comparator" variable assessable through Integrated Dynamics (v 1.11.2-0.8.4) also has this issue and does not update.

EDIT: Integrated Dynamics variable "Fluid Fill Ratio" does update properly.

**Comment by AEnterprise** [comment]
we probably need to notify or mark something dirty when the fluid lvl updates

the fluid fill ratio probably works fine because that's something integrated ynamics calculates on its own so doesn't depend on us notifying of a change

**Comment by AlexIIL** [comment]
Should be fixed in [7.99.8](https://www.mod-buildcraft.com/buildcraft-7998-alpha.html).
