### ISSUE TITLE
Containers needs a method for setting phantom slots.

### ISSUE THREAD

**Issue by faceofcat** [BuildCraft/BuildCraft#3801]
**Buildcraft** version: 8.0.x
**Forge** version: 1.11
Additional information:

Containers needs a method, on client side, for setting phantom slots... something like:
```java
void setPhatomSlots(List<ItemStack> slots) { ... }
```

this would be quite useful in integrating the auto crafting thingies with JEI.

**Comment by AlexIIL** [comment]
Should be fixed in [7.99.8](https://www.mod-buildcraft.com/buildcraft-7998-alpha.html).
