### ISSUE TITLE
all bucket have the same id

### ISSUE THREAD

**Issue by maternsci** [BuildCraft/BuildCraft#3806]
Helo,
all bucket (oil, Fuel and more) in the game have the same Id (in game ID: forge:bucketfilled).
so how can i change the IDs, that every filled bucket have his own ID?

**Buildcraft** version: 7.99.7
**Forge** version: 1.11.2-13.20.1.2476

Singleplayer

**Comment by faceofcat** [comment]
isn't this how forge buckets work?

**Comment by maternsci** [comment]
i don't now how the forge work.
i have search for a list with all the ID's from Buildcraft in the minecraft folder, but don't find it.

the problem:
i will set a command (example: /give) for oil bucket in the command block. but every bucket has the same ID (#4096), so i can't set this command.
every Item or Block has his own ID, but the different buckets have all the same.

sry, my english isn't very good :/

**Comment by faceofcat** [comment]
/give @p forge:bucketfilled 1 0 {FluidName:"oil",Amount:1000}
/give @p forge:bucketfilled 1 0 {FluidName:"oil_heat_1",Amount:1000}
/give @p forge:bucketfilled 1 0 {FluidName:"oil_heat_2",Amount:1000}

**Comment by maternsci** [comment]
Thank you very much.

Is there a list, where i can find this Information of all the items ans Blocks drin buildcraft?

**Comment by faceofcat** [comment]
for items/blocks you can just see their ids in the tooltips (make sure to press F3+H to enable advanced tooltips)...
for fluids... either guess it's name... or wait for someone actually working on BC to reply :)

**Comment by maternsci** [comment]
Yeah,  in the tooltip i find the Name "forge:bucketfilled" and the Number but the rest was missing. :D

Ok, than i must wait  :)

Thank you for help me so fast.

So i can Close this question.

**Comment by AEnterprise** [comment]
for oil the name you need is most likely 'buildcraftenergy:fluid_block_oil_heat_0'. if that doesn't work i sugest getting an oil bucket and using an NBT editor or such to look at the tag what data you need to set on it

**Comment by maternsci** [comment]
My new Problem -.-
i will set the Oil bucket in a dispenser with the command Block, but it doesn't work without an error.

Command:
/blockdata ~2 ~ ~ {Items:[{Slot:0,Count:1,Damage:0,id:forge:bucketfilled{FluidName:"oil",Amount:1000}}]}

Output:
[19:16:28] NBT-Daten aktualisiert zu: {x:509,y:63,z:-421,Items:[0:{Slot:0,Count:1,id:"forge:bucketfilled{FluidName:\"oil\",Amount:1000}",Damage:0}],id:"minecraft:dispenser",Lock:""}

**Comment by AEnterprise** [comment]
that output isn't an error, if it doesn't work then the nbt tag probably isn't correct

i sugest just putting a bucket of oil into the dispencer yourself and then using nbt explorer to inspect what the exact data is you want on the block

**Comment by afdw** [comment]
`/blockdata ~2 ~ ~ {Items:[{Slot:0,Count:1,Damage:0,id:forge:bucketfilled,nbt:{FluidName:"oil",Amount:1000}}]}` I think?

**Comment by afdw** [comment]
`/blockdata ~2 ~ ~ {Items:[{Slot:0,Count:1,Damage:0,id:forge:bucketfilled,tag:{FluidName:"oil",Amount:1000}}]}` I think?

**Comment by liach** [comment]
The fluid info is not a part of id, but a part of its nbt tag compound.

**Comment by maternsci** [comment]
@ afdw:  i have test yours, but it don't work.

ich look with the nbtexplorer.
here are 2 pictures.

one is the oil bucket in my inventory

the other picture are the data from forge.

![unbenannt](https://user-images.githubusercontent.com/31876986/30342027-965d8418-97f8-11e7-997e-400643514cd6.PNG)
![unbenannt1](https://user-images.githubusercontent.com/31876986/30342026-965bbd9a-97f8-11e7-9946-17088862d3d1.PNG)
