### ISSUE TITLE
Energy generation not working with Forestry

### ISSUE THREAD

**Issue by Platypus007** [BuildCraft/BuildCraft#3808]
**Buildcraft** version:  7.99.7
**Forge** version:  1.11.2-13.20.1.2476
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) :  no crash
Singleplayer/multiplayer:  multiplayer

Additional information:
Forestry version: 1.11.2-5.3.4.165
I'm not sure if I should report it here or at Forestry, but the main thing is:
neither does the engines nor does the kinesis pipes connect to the machines of forestry. 
![2017-09-13_20 37 55](https://user-images.githubusercontent.com/10195476/30394565-b291e3ce-98c3-11e7-8b35-43aaf3436b88.png)

**Comment by iTitus** [comment]
Forestry switched to RF, BuildCraft now uses MJ again

**Comment by AEnterprise** [comment]
correct, forestry will most likely implement compat later once we reach beta and the api and mechanics are pretty much final

**Comment by LuigiHutch** [comment]
Thanks for the report! This is a duplicate of #3760
