### ISSUE TITLE
Crashing after using a fair few pipes [BC 7.99.7]

### ISSUE THREAD

**Issue by sexontoast** [BuildCraft/BuildCraft#3811]
**Buildcraft** version: 7.99.7
**Forge** version:  forge-1.11.2-13.20.1.2454
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : https://pastebin.com/A3JX4sRm
Singleplayer/multiplayer: Multiplayer

Additional information:
Server 8 x CPU, 32Gb Ram, SSD

Issue seems to be since I setup a large length of pipes (running oil) Approx 140 blocks long

When I try and load into the server I receive a "tick can't keep up" then the server crashes as per the log above.

This had been running perfectly for the past week or so.
Last crash is with a more customised start-up config, as I tried to self resolve the issue. Prior had been the basic java memory, no gui and launch.

Happy to upload a copy of the world.

**Comment by sexontoast** [comment]
Using MCedit, deleting the Pump chunk, fixes the world if that helps.

**Comment by AEnterprise** [comment]
the issue isn't the pipeline but the pump, it seems that got stuck in an infinite loop maybe?

how long after starting the server does it crash? what was the pump pumping and how does the area with the liquid look?

@afdw you worked on the pump, would this already be fixed for newer versions or does this need a look?

**Comment by sexontoast** [comment]
Within 15 seconds the game crashes, though its completely unresponsive to that point,
After removing the pump, and replacing it occurred again.

Maybe its the oil source ? I had pumped 3-4 other oil sources + countless lava ponds without issue.

Would uploading a copy of the world / map assist ?

**Comment by AEnterprise** [comment]
15 seconds? the watchdog should not be kicking in that fast did you lower the max ticktime in the server.properties config? if so bump it up higher again, if it's already at the default 60000 try dissabeling it by setting it to 0

**Comment by sexontoast** [comment]
Have not modified it,

Its stock as stock,

#Minecraft server properties
#Sun Sep 17 16:54:18 AEST 2017
max-tick-time=60000
generator-settings=
force-gamemode=false
allow-nether=true
gamemode=0
enable-query=false
player-idle-timeout=0
difficulty=3
spawn-monsters=true
op-permission-level=4
announce-player-achievements=true
pvp=true
snooper-enabled=true
level-type=DEFAULT
hardcore=false
enable-command-block=false
max-players=20
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
server-port=25565
server-ip=10.0.0.100
spawn-npcs=true
allow-flight=false
level-name=world
view-distance=14
resource-pack=
spawn-animals=true
white-list=false
generate-structures=true
online-mode=true
max-build-height=256
level-seed=
prevent-proxy-connections=false
motd=A Minecraft Server
enable-rcon=false

**Comment by AEnterprise** [comment]
in that case the watchdog is bugging out, changing the max-tick-time to 0 should dissable the watchdog, if that allows your server to load up normaly it's just a problem with minecraft itself

**Comment by sexontoast** [comment]
I should have expanded on my last response,
The server only crashes once the client joins, once the client has joined it takes around 15s. Removing the pump fixes the issues.

**Comment by AEnterprise** [comment]
that's probably because the player is causing the pump to load, did you try setting it to 0 and then logging in (and giving it a bit more time)

the watchdog can be a bit buggy and kill when not needed, if that doesn't allow you to get in the world there is an issue with the pump we need to dig deeper into

**Comment by sexontoast** [comment]
Didn't help,
Only fix is to remove that pump from that particular oil sprite,

Any chance its the oil source causing this ? I used pumps for heaps of things, and this is the first time I have hit the issue.

**Comment by AEnterprise** [comment]
is the watchdog still killing it or does it now just hang forever?

**Comment by AEnterprise** [comment]
no response for quite a while, gona assume this is resolved
