### ISSUE TITLE
Oil generated in the End and the Nether

### ISSUE THREAD

**Issue by Johan3F** [BuildCraft/BuildCraft#3812]
*Buildcraft** version: 7.66.7
**Forge** version: 13.20.1.2386
Singleplayer/multiplayer: Multiplayer

Additional information: Oil is being generated in the end even in the middle of the void, not only on floating islands. I'm attaching images to prove it

![screenshot_20170917_150441](https://user-images.githubusercontent.com/26611444/30521182-f12922be-9bbb-11e7-925b-c02847779f7f.png)
![screenshot_20170917_150500](https://user-images.githubusercontent.com/26611444/30521184-f12ef464-9bbb-11e7-8bc0-057accbd8efa.png)
![screenshot_20170917_150530](https://user-images.githubusercontent.com/26611444/30521183-f12dc198-9bbb-11e7-84b8-e4097609571a.png)
![screenshot_20170917_150540](https://user-images.githubusercontent.com/26611444/30521185-f1301c4a-9bbb-11e7-8ef0-598acbbcdef6.png)

**Comment by AlexIIL** [comment]
I'm having trouble duplicating this: can you also post the world seed that you are using, as well as the coordinates of any of the oil spouts?

**Comment by Johan3F** [comment]
Sure thing!
- Map seed: 3829598836628152597
- Oil spring generated on the void at coordinates: X: 642  Y: 68  Z: 2235

If you need another oil spring that is not generated on the void itself, let me know, I'll go and find one for you.

Just to mention it: This is a pure survival server. I never used creative. I heard that survival can create some issues

**Comment by AEnterprise** [comment]
another set of coords in the nether: #3824

**Comment by FrancisDaPugtato** [comment]
As I am going thru the configuration file, the end is not under the biomes that oil shouldn't spawn. `# Biome registry names (e.g. 'minecraft:hell','minecraft:jungle') of biomes that should never generate oil.
    S:excludedBiomes <
        minecraft:hell
        minecraft:sky
     >
`

**Comment by AEnterprise** [comment]
it is in the blacklist, the sky biome is the biome used in the end (and hell is the nether)

**Comment by FrancisDaPugtato** [comment]
Oh yeah, I just found that. Sorry

**Comment by AEnterprise** [comment]
didn't this get fixed for BC 7.99.8?

**Comment by Johan3F** [comment]
I can't test it anymore. Our server just moved on to different mods and they reset the map anyway

**Comment by AEnterprise** [comment]
should be fixed
