### ISSUE TITLE
fuel dasnt work on engine 7.99.7

### ISSUE THREAD

**Issue by xpatryk89** [BuildCraft/BuildCraft#3823]
**Buildcraft** version: 7.99.7
**Forge** version: 13.20.1.2429
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: 

Additional information:
Hello i use galacticraft 4.0.0.117 and when i spill fuel and take in to bucket i has galacticraft fuel and i cant use it on engine can you solve it?

**Comment by AEnterprise** [comment]
most likely galacticraft is also registering fuel and forge is using it as the dominant fuel yet it's not registered in the registry as fuel?

**Comment by AEnterprise** [comment]
Closing for a lack of information, if you provide the requested information we can re-open and take another look at this.
