### ISSUE TITLE
1.11.2 miner with ejector upgrade ejects everything even ov scanner and pipe while in use.

### ISSUE THREAD

**Issue by tateman10** [BuildCraft/BuildCraft#3826]
**Buildcraft** version: 7.99.7
**Forge** version:  13.20.1.2454
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer:  When using ejector upgrade on miner it ejects everything including drill, mining pipe, and OV scanner, during miner operation. 

Additional information:

**Comment by tateman10** [comment]
Sorry this is during single player.  Ejector upgrade works as expected on other machines.

**Comment by AlexIIL** [comment]
Are you using the IC2 miner? Neither of BuildCraft's closest machines (the quarry or the mining well) use a drill, or an OV scanner...

**Comment by tateman10** [comment]
Ah yes wrong bug report. I apologize for being confused.
