### ISSUE TITLE
Null NBT being stored

### ISSUE THREAD

**Issue by Tencao** [BuildCraft/BuildCraft#3831]
**Buildcraft** version: 7.99.8
**Forge** version: 14.23.0.2512
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : https://paste.ee/r/zkU8Y
Singleplayer/multiplayer: Multiplayer

Additional information: It appears based on past discussions that this bug is also present on both the 1.11.2 and 1.12 builds. This has been tested with the most recent commits as of this posting and I shall continue to test on every commit until I can confirm the issue is resolved.

**Comment by Tencao** [comment]
@afdw Can confirm this has fixed it

**Comment by AlexIIL** [comment]
Should be fixed in [7.99.8](https://www.mod-buildcraft.com/buildcraft-7998-alpha.html).
