### ISSUE TITLE
Pipes not showing blocks sometimes

### ISSUE THREAD

**Issue by FrancisDaPugtato** [BuildCraft/BuildCraft#3832]
**Buildcraft** version: 7.99.7
**Forge** version: 13.20.1.2513  (1.11.2)

Link to crash report or log (on Pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: SinglePlayer 1.11.2

Additional information:
![2017-10-22_15 39 13](https://user-images.githubusercontent.com/33008186/31865602-6609cb44-b73f-11e7-9786-7fcac592a68e.png)
![2017-10-22_15 41 40](https://user-images.githubusercontent.com/33008186/31865611-84c6c4ba-b73f-11e7-82dd-c8907096f258.png)

**Comment by FrancisDaPugtato** [comment]
Its going form the quarry into the chest, and then the from the chest into the storage

**Comment by AEnterprise** [comment]
do you have any mods that change rendering (optifine and the like) installed?

**Comment by FrancisDaPugtato** [comment]
No

**Comment by FrancisDaPugtato** [comment]
Sometimes it starts flashing, and sometimes it comes back

**Comment by FrancisDaPugtato** [comment]
![2017-10-22_16 55 03](https://user-images.githubusercontent.com/33008186/31866190-c5d7691e-b749-11e7-86bb-35c3db301dee.png)

**Comment by AEnterprise** [comment]
can you upload a forge log from when this heapens and also a debug crash report (hold F3 + C for about 10s ingame without having any gui's open)

**Comment by FrancisDaPugtato** [comment]
Hard to find but sure...

**Comment by FrancisDaPugtato** [comment]
In an hour prob

**Comment by AlexIIL** [comment]
What happens specifically? Do items vanish for a short time in pipes before continuing? Do the items actually reach their destination (so are they inserted into the chest at the end?

**Comment by FrancisDaPugtato** [comment]
They are in there, moving. They don't disappear- just they are not showing up in the pipes. They're still being transported, just are invisable. It got fixed when I reloaded the chunk btw

**Comment by FrancisDaPugtato** [comment]
https://pastebin.com/7u7YUgXZ

I have updated back to 1.12.2 so I won't be able to show you the Debug crash report. Sorry! :( IF you really need it, I can pull it back up if you want me to.

**Comment by AlexIIL** [comment]
I'm not sure how useful that would be... nothing is logged atm related to that...

**Comment by FrancisDaPugtato** [comment]
Do you need any other investigation? I could go back to 1.11.2 and check the Debbuger crash report with the same settings. (I am not a mod expert but it would be logic that the Debugger crash report would have disappeared)

**Comment by AEnterprise** [comment]
does this still heapen to you on 7.99.12?

**Comment by AEnterprise** [comment]
closing as this seems to have been fixed and no responses
