### ISSUE TITLE
Red Paintbrush gets damaged in Creative

### ISSUE THREAD

**Issue by FrancisDaPugtato** [BuildCraft/BuildCraft#3834]
**Buildcraft** version: 7.99.7
**Forge** version: 13.20.1.2513
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: Singleplayer
![2017-10-22_17 44 51](https://user-images.githubusercontent.com/33008186/31866653-db1d280c-b750-11e7-8571-6b1a2d5ddf7e.png) 
![2017-10-22_17 45 01](https://user-images.githubusercontent.com/33008186/31866662-ef4ad0f4-b750-11e7-9b13-a49e6a577b2b.png)

Additional information:
No rendering mods, BC is the only one. 1.11.2. 
Luigi said it was a bug.

> FrancisDaPugtato - Today at 5:41 PM
Would a red paintbrush getting it's utility bar going down in Creative mode count as a bug?
LuigiHutch - Today at 5:42 PM
Taking damage in creative mode? Yes
FrancisDaPugtato - Today at 5:43 PM
Okie let me report it

> 
^^^Discord

**Comment by AEnterprise** [comment]
yup that is a bug, not a very major one (as you can easely grab a new one in creative) but still a bug

not sure when we will look into fixing this (though if someone else wants to fix it and submit a PR they definatly can, just let us know)

**Comment by ron-popov** [comment]
Can we close this issue now ?

**Comment by AEnterprise** [comment]
we leave issues open but mark as fixed until a release is out with the fix

**Comment by AEnterprise** [comment]
fix was released but issue wasn't closed yet
