### ISSUE TITLE
Server crash upon placing a pipe

### ISSUE THREAD

**Issue by lelodragneel** [BuildCraft/BuildCraft#3835]
**Buildcraft** version: 7.1.22
**Forge** version: forge-1.7.10-10.13.4.1614-1.7.10-universal

https://pastebin.com/qya93x2i

Additional information:
Placed a Stone Transport Pipe from BC Transport and the server instantly crashes. If I restart the server, it will instantly crash when I login (in the same chunk).

**Comment by AEnterprise** [comment]
looks like an compat issue

@asiekierka do you still want to support 1.7.10 ?

**Comment by AlexIIL** [comment]
I still do, especially for small things like this...

**Comment by AlexIIL** [comment]
Duplicate of #3265, this should be continued at BuildCraft/BuildCraftCompat#59
