### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by tony2013fl** [BuildCraft/BuildCraft#3836]
**Buildcraft** version: 
**Forge** version: 
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: 

Additional information:
i get a crash whenever i use buildcraft and after googleing it seems im not the only one. please eather pull it from downloads or fix it. its no good to anyone if it cant be used

**Comment by DaMatrix** [comment]
send the crash report and fill out the issue template, otherwise nobody can and will help you.

**Comment by AEnterprise** [comment]
So which of the 214 BC releases made is crashing for you? we also need the other information in the template to be able to help you.
B
uildcraft is a tech mod not a magic mod. As such none of us are skilled enough with crystal balls to be able to see the missing information
