### ISSUE TITLE
Quarry Corrupts world when placed

### ISSUE THREAD

**Issue by Trhod17** [BuildCraft/BuildCraft#3839]
**Buildcraft** version: 7.1.22
**Forge** version: 1.7.10: 1614
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : https://pastebin.com/CzUUKQJD
Singleplayer/multiplayer:  singleplayer

Additional information: i placed the quarry, the game crashed and now i cant access my world anymore

**Comment by AEnterprise** [comment]
did you alter your config by chanse? it looks like the quarry battery max ended up being 0

this would heapen if the break energy or mining multiplier has been set to 0

to get back in your world (cause that TE battery is now corrupt) you can enable the setting in forge config to remove erroring TE's, load up, save and turn it back off

**Comment by Trhod17** [comment]
i havent touched the configs

**Comment by AEnterprise** [comment]
can you try removing the config so it gets regenerated? then if you get rid of the crashing block things should work fine again

**Comment by AEnterprise** [comment]
@asiekierka do you have more work (planned)? if not we might wana consider releasing your fixed to BC and BCC

**Comment by asiekierka** [comment]
No. I've already told Alex to release it.
