### ISSUE TITLE
No Chatroom

### ISSUE THREAD

**Issue by ron-popov** [BuildCraft/BuildCraft#3841]
I would like to contribute and i think that a chat room of some sort, like gitter or slack would make it easier for people to pitch ideas, get help while contributing to the project, or just making it easier to ask short questions regarding the mod.

**Comment by LuigiHutch** [comment]
As stated in the Issue template you removed, we have a discord chat room located here: https://discord.gg/v4geqgA

or #buildcraft on espernet irc

**Comment by DaMatrix** [comment]
there's a discord, it's under "Links" on the website

**Comment by AEnterprise** [comment]
there is one: https://discord.gg/v4geqgA

fyi: that link was also in the issue template when you created that issue

**Comment by AlexIIL** [comment]
On the buildcraft [website](https://mod-buildcraft.com/) there is a link to our [Discord](https://discord.gg/v4geqgA) chat room, perhaps that would be useful?

**Comment by ron-popov** [comment]
ok, thanks.
