### ISSUE TITLE
distiller

### ISSUE THREAD

**Issue by Dmitry1001001** [BuildCraft/BuildCraft#3844]
**Buildcraft** version: 7.99.8
**Forge** version: 13.20.1.2386
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: singleplayer

Additional information: After a few minutes the oil refinery stops. The internal menu does not open. Oil is poured into the wrong reservoir.
![2017-11-16 13 52](https://user-images.githubusercontent.com/33719184/32888071-252342da-cad7-11e7-892e-38609ef23e62.jpg)

**Comment by AEnterprise** [comment]
oil is going into the right resevoir, the distiller isn't the old refinery and worlks slightly different, see this guide: http://imgur.com/a/AXUOX

**Comment by Dmitry1001001** [comment]
Wow thank you for the help !
