### ISSUE TITLE
Petroleum is invisible in 1.7.10

### ISSUE THREAD

**Issue by VIOLATOR1** [BuildCraft/BuildCraft#3846]
****Buildcraft** version: Buildcraft 7.1.22 for Minecraft 1.7.10
**Forge** version: 1.7.10 - 10.13.4.1614
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : There are no logs.
Singleplayer/multiplayer: Singleplayer**

_Additional information: I was mining some iron on my cave and then i fall into invisible petroleum.
Not using Optifine._

**Comment by AlexIIL** [comment]
Can you try picking it up with a bucket to see what it is? (Or try in creative mode, whichever is easiest)

**Comment by AEnterprise** [comment]
also can you provide a modlist (easiest is a debug crash, hold F3+c ingame for 10s and upload and link the crash)? if it is BC oil then another mod is most likely messing with it

**Comment by VIOLATOR1** [comment]
The debug log is here: https://pastebin.com/SWGqbMAE

And i can pick up it with a bucket, and then drop it in another place but it is still invisible.
![542c64634145604c883d9541285cf624](https://user-images.githubusercontent.com/33812634/32995250-3fbeca06-cd48-11e7-916b-dad848aca7eb.png)

**Comment by AEnterprise** [comment]
the picking up in a bucket was to confirm it is from buildcraft, can you check that the bucket is a bc oil bucket and not oil or anything else black from another mod?

**Comment by VIOLATOR1** [comment]
It's from BC Energy.

![2017-11-19_16 22 16](https://user-images.githubusercontent.com/33812634/32995417-0c8ae596-cd4a-11e7-8f12-4b1c3e14b8d2.png)

**Comment by AEnterprise** [comment]
does this heapen with just BC? if not then another mod is messing with the oil rendering somehow and you'll wana triage your mods to find the culpit then

**Comment by AEnterprise** [comment]
this doesn't heapen with just BC installed so another mod must be messing with the rendering, try removing mods to see what mod is causing it to go invisible
