### ISSUE TITLE
NullPointer when hovering over sub options of wire signal

### ISSUE THREAD

**Issue by SirIntellegence** [BuildCraft/BuildCraft#3847]
**Buildcraft** version: 7.99.8 alpha
**Forge** version: 1.11.2-13.20.1.2429
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer:  Single Player
Stacktrace (Obtained via NetBeans):
https://pastebin.com/SBKi4ktC

Additional information:
Item in question:
![image](https://user-images.githubusercontent.com/3401182/33002241-2e08b88a-cd70-11e7-87c4-a395409d7d4f.png)

![image](https://user-images.githubusercontent.com/3401182/33002055-f73711a4-cd6e-11e7-9e72-024037eb7ab6.png)
The game crashes and throws a null pointer when you hover over the blank elements to the right of the signal +/- entries. This happens regardless of the side that the signal indicator is on.

**Comment by AlexIIL** [comment]
Fixed in https://github.com/BuildCraft/BuildCraftAPI/commit/ef50ab8a7d99db11b8122e8c0ba8d025a1174450

**Comment by AlexIIL** [comment]
Should be fixed in 7.99.8.1 and 7.99.12
