### ISSUE TITLE
7.99.12-Pre2 - Server Side loading error

### ISSUE THREAD

**Issue by Dockter** [BuildCraft/BuildCraft#3849]
I know you folks are in heavy development.  I was finally able to compile this tonight and it seemed to run fine on the client but crashes in a server environment.

Here's the log that may assist you:  https://gist.github.com/Dockter/95158e22a91f08097523776649d8c0aa

Thanks for working so hard on 1.12.x

**Comment by Dockter** [comment]
Update, I pulled and built this change out. Server starts now but each world errors with the following error:

https://gist.github.com/Dockter/0d7c46c2685c97bc01cd7d9bb5041952

Appears some sort of achievement is being registered incorrectly.

**Comment by AlexIIL** [comment]
Goggles are disabled out of a dev environment, and for some reason we have an advancement for them. Its looks like its a warning rather than a fatal error, so I'll probably leave it for now.

**Comment by Dockter** [comment]
Yeah, just seem to print a nasty thread dump when it encounters them.  I'll proceed on with testing.

Thx.

**Comment by AlexIIL** [comment]
Fixed in 7.99.12-pre3
