### ISSUE TITLE
Crash On Startup Due To Outdated CoFH API

### ISSUE THREAD

**Issue by InsomniaKitten** [BuildCraft/BuildCraft#3851]
**Buildcraft version:** [7.1.23](https://www.mod-buildcraft.com/buildcraft-79912-alpha-buildcraft-79981-alpha-buildcraft-7123-stable-buildcraftcompat-717-stable-buildcraftcompat-7990-alpha.html)
**Forge version:** [1.12.2-14.23.0.2551](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.0.2551/forge-1.12.2-14.23.0.2551-changelog.txt)
**Crash report:** [gist/8973f12ed3891f3fc1008784295dac36](https://gist.github.com/InsomniaKitten/8973f12ed3891f3fc1008784295dac36)

Game crashes during startup alongside CoFH Core + dependants, due to outdated CoFH API classes being repacked in the jar.

**Comment by AlexIIL** [comment]
You need to download [7.99.12](https://mod-buildcraft.com/releases/BuildCraft/7.99.12/buildcraft-7.99.12.jar) rather than 7.1.23

**Comment by InsomniaKitten** [comment]
Oh oops, my bad. Ngl the changelog blog post is a bit confusing :P

**Comment by AlexIIL** [comment]
Yeah, sorry about that :/ I'll update the download links to be more specific as to which version they are for.
