### ISSUE TITLE
Pipe Item Models Have Incorrect Lighting

### ISSUE THREAD

**Issue by InsomniaKitten** [BuildCraft/BuildCraft#3853]
**Buildcraft version:** [7.99.12](https://www.mod-buildcraft.com/buildcraft-79912-alpha-buildcraft-79981-alpha-buildcraft-7123-stable-buildcraftcompat-717-stable-buildcraftcompat-7990-alpha.html)
**Forge version:** [1.12.2-14.23.0.2551](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.0.2551/forge-1.12.2-14.23.0.2551-changelog.txt)

The item models for pipes appear to not have any standard item lighting, which results in them looking very bright and standing out from other items.

**Comment by Dockter** [comment]
This could tied to this change in forge recently:

https://github.com/MinecraftForge/MinecraftForge/commit/23ea237f2c3c9f627150d4cff52fc2b6735ecc81

**Comment by LuigiHutch** [comment]
Nope, they have been like this for quite a while. Also related: https://github.com/BuildCraft/BuildCraft/pull/3747

**Comment by AlexIIL** [comment]
It looks like a lot of custom models have incorrect lighting, such as the engines.

**Comment by AlexIIL** [comment]
Looks like ````ModelItemSimple.isGui3d```` needs to return true for pipes and engines.
