### ISSUE TITLE
Crash when placing Architect Table

### ISSUE THREAD

**Issue by 3TUSK** [BuildCraft/BuildCraft#3854]
**Buildcraft** version: 7.99.12  
**Forge** version: 14.23.0.2552  
Link to crashreport or log (on pastebin or gist, please don't put the entire log here):  
[Client-side](https://paste.ee/p/EVixq) [Server-side](https://paste.ee/p/u8wFm)
Singleplayer/multiplayer: Singleplayer  
Additional information:
* Mod list can be found in crash-report.
* The Architect Table was placed next to a formed, 2-dimensional, rectangular marked zone (created by landmark). Only air and light-blue glazed terracotta blocks are present in that zone. 
* I can still get into the world, but the game would still freeze for a while and crash with the same stacktrace.
* Searching previous issues with "architect table" as keyword didn't reveal anything similar.

**Comment by AEnterprise** [comment]
can you try and see if this also heapens with just BC installed and no other mods? the client stacktrace makes me think something is messing with the rendering

server error seems weird but since it's the integrated one it most likely is just a side effect of the client thread crashing

**Comment by 3TUSK** [comment]
Successfully replicated with only BuildCraft: https://paste.ee/p/06x5X
