### ISSUE TITLE
Standing on top of quarry frame while it moves causes you to glitch into the frame

### ISSUE THREAD

**Issue by TheDeviantCrafter** [BuildCraft/BuildCraft#3855]
This behaves exactly the same as when you attempt to stand on a ghost block. Standing on the part of the frame that doesn't move is fine, but if you stand on the part that does and it moves under you feet, you fall slightly and stand inside of the quarry frame.

This causes you to jump up and down quickly. You also move very slowly if you're trying to escape the block.

**Buildcraft** version: 1.12.2-14.23.0.2552
**Forge** version: 7.99.12
Singleplayer/multiplayer: Singleplayer

Additional information:

Affects both survival and creative players. If it moves out from under you, you will still fall as expected.

**Comment by AEnterprise** [comment]
might be a rounding thing when moving that causes you to 'fall' inside the box as it's moving? that or MC not liking that you are on a bounding box without any entity or block directly around you

**Comment by Wupp** [comment]
On top of this, the quarry arm leaves an invisible hitbox (which behaves like a normal block, not a ghost block) at the location where the arm spawns. This doesn't move with the quarry arm, but will stay in its position until a relog occurs and the hitbox is moved to wherever the quarry arm is when loaded.

I'm using Buildcraft version 7.99.12, Forge version 1.12.2-forge1.12.2-14.23.0.2550, and am playing in singleplayer

**Comment by AEnterprise** [comment]
@afdw is this now fixed?

**Comment by afdw** [comment]
@AEnterprise I think yes.
