### ISSUE TITLE
Config option for pumps to remove water

### ISSUE THREAD

**Issue by davqvist** [BuildCraft/BuildCraft#3857]
**Buildcraft** version: 7.99.12
**Forge** version: 2549
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: 

Additional information:
As talked about in the discord, there doesn't seem to be a config option for pumps to actually remove the water which is a balancing issue when water is set to finite in a pack. It would be nice if you could add that config option. Thanks very much.

**Comment by AlexIIL** [comment]
Added in https://github.com/BuildCraft/BuildCraft/commit/e1b097c0adb683fef726f980f1d35b9bd1a5bde2, will be released in 7.99.13.
