### ISSUE TITLE
crash when placing recipe in autoworkbench 1.12

### ISSUE THREAD

**Issue by mvdhoning** [BuildCraft/BuildCraft#3859]
When opening a placed autoworkbench the crafting progress bar is already running.
When placing a recipe (say for a furnace) minecraft crashes.

**Buildcraft** version: 7.99.12
**Forge** version: forge-14.23.0.2544
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
https://pastebin.com/fb2kTQ2g

Singleplayer: yes

**Comment by AlexIIL** [comment]
What recipe was in the inventory before you placed the furnace recipe? Can you reproduce with just buildcraft?

**Comment by mvdhoning** [comment]
i just placed the autoworkbench, so there was no initial recipe.
will try to make a setup with only buildcraft.

**Comment by mvdhoning** [comment]
with only buildcraft the crafting procesbar is not automaticaly running
and it is possible to place a recipe
guess i have to go on a trial and error hunt to find the offending mod :-(

**Comment by mvdhoning** [comment]
found the offending mod:
https://minecraft.curseforge.com/projects/ancient-warfare-2

**Comment by AEnterprise** [comment]
sounds like acient warfare is doing something funky with a recipe handler that is claiming to be a valid recipe without anything in the inventory

**Comment by mvdhoning** [comment]
release 2.4.12 of aw2 seems to fix the wierd autoworkbench behaviour :-)
