### ISSUE TITLE
[1.12.2] Oil Missing Textures

### ISSUE THREAD

**Issue by BrisingrAerowing** [BuildCraft/BuildCraft#3860]
**Buildcraft** version: 7.99.12
**Forge** version: 2552
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : N/A
Singleplayer/multiplayer: Singleplayer

Additional information: Haven't checked anything else for missing textures yet. This was noticed with a cool oil well in an ocean.

**Comment by AEnterprise** [comment]
can you reproduce with just BC? some other mod might be messing with rendering or oil

**Comment by BrisingrAerowing** [comment]
Yup, it's another mod. I'll see which one is conflicting (I only have a couple that add oil).

**Comment by BrisingrAerowing** [comment]
Found the culprit: [The Disenchanter Mod](https://minecraft.curseforge.com/projects/the-disenchanter-mod). It add a disenchantment table. The missing texture showed the TileEntity name for the table, so I assumed that was causing this.

I'll go ahead and report this to them.
