### ISSUE TITLE
Filler has no texture when placed 1.12

### ISSUE THREAD

**Issue by mvdhoning** [BuildCraft/BuildCraft#3861]
Placing a filler in the world shows a black/purple squared block.  With some debug text on top about placement. It does not look like a Filler and there is no gui that can be opened.

Buildcraft version: 7.99.12
Forge version: forge-14.23.0.2544

Singleplayer: yes

Additional information:
Buildcraft is the only mod loaded.

**Comment by mvdhoning** [comment]
When placing landmarks first it does show gui. But still not proper texture on it.

**Comment by LuigiHutch** [comment]
Have you got some screenshots?

**Comment by mvdhoning** [comment]
screenshot: ![image](https://thuis.vanderhoning.net/images/fillernotexture.png)

**Comment by yujukitten** [comment]
I am receiving a similar issue with Filler though Mine is a server Issue. When as a Client I try and log in I get errors and denied access :

_**[09:15:36] [main/WARN]: Texture buildcraftbuilders:textures/filler/parameters/face_west.png with size 0x0 will have visual artifacts at mip level 0, it can only support level -1. Please report to the mod author that the texture should be some multiple of 16x16.**_

there are 5 others of these face_down, face_east. face_up, face_north, face_south 

[latest.log](https://github.com/BuildCraft/BuildCraft/files/1532058/latest.log)

I tried turning off filler block and the item filler planner in hopes it might work but I still receive the error.

**Comment by AlexIIL** [comment]
Unfortunately the "buildcraftbuilders:textures/filler/parameters/face_west.png" errors aren't related to the filler's block texture, but todo with one of the parameters for modifying the patten that is used for actually filling an area.

Also, wow, how have I not noticed this before... this is broken in dev as well, I have no idea why I thought it wasn't...

**Comment by yujukitten** [comment]
XD  well glad we could point something out ! And already a dev fix sweet cannot wait to be able to try it been fighting for 20 hours thought it was something I did XD

**Comment by AlexIIL** [comment]
For some reason I never thought to place it down in a test world... In theory you can temp-fix it by adding a resource pack with https://github.com/BuildCraft/BuildCraft/blob/8.0.x/buildcraft_resources/assets/buildcraftbuilders/blockstates/filler.json instead of the [current](https://github.com/BuildCraft/BuildCraft/blob/daa3bdb9b1113811437cb09defadcf424ca205f8/buildcraft_resources/assets/buildcraftbuilders/blockstates/filler.json) version.

**Comment by yujukitten** [comment]
Ok I will attempt to figure out how to do that and see if I can get in ! thanks so much ! 

And truly there is so much to check and look out for somethings are easy to pass by I am sure.
