### ISSUE TITLE
Disappearing Items

### ISSUE THREAD

**Issue by TechFreak101** [BuildCraft/BuildCraft#3862]
**Buildcraft** version: 7.99.12
**Forge** version: 14.23.0.2549
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : N/A
Singleplayer/multiplayer: Single

Additional information:
I have a world with multiple mods. I created this world originally without buildcraft and everything ran smoothly, no glitches or anything. Right after installing buildcraft, every time I log in/out or go through a portal, items (so far armour stands, crafting benches(vanilla and other mods, and furnaces) have disappeared. However they don't completely disappear, it's almost like they are invisible. I can't use them, see them, nor place any blocks where they previously were.

**Comment by AEnterprise** [comment]
can you please provide a log of when this heapens? that might have some clue's as to what's going on here

**Comment by AEnterprise** [comment]
Closing for a lack of information, if you provide the requested information we can re-open and take another look at this.
