### ISSUE TITLE
1.12.2 crash 

### ISSUE THREAD

**Issue by 5kedone** [BuildCraft/BuildCraft#3864]
**Buildcraft** version: 7.99.12
**Forge** version: 1.12.2 - 14.23.0.2552
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : https://pastebin.com/R3ktpK7h
Singleplayer/multiplayer: 
single player
Additional information:
i have removed xnet before you ask and tried that then it just blames another mod instead, but if i remove buildcraft all is well, will check with mj and see if he is still using an old buildcraft API

**Comment by AEnterprise** [comment]
this isn't a problem with any 1 mod specificaly you have installed, the issue is you have to many mods installed, the game only supports up to 4096 block IDs and all the mods together are using more then 4096 IDs. sadly the only fix is eighter removing one or more mods to stay below the limit

**Comment by 5kedone** [comment]
its okay I sorted to now and yeah that was issue I installed NotEnoughiIDs to raise the limit, at first I thought I was going to have edit configs like in the old days to juggle the ids about lol
