### ISSUE TITLE
[1.12]GUI of the Assembly Table is covered with part of JEI items.

### ISSUE THREAD

**Issue by SihenZhang** [BuildCraft/BuildCraft#3866]
Minecraft Version: 1.12.2
Forge Version: 14.23.0.2554
Buildcraft Version: 7.99.12
JEI Version: 4.8.3.126
Singleplayer/Multiplayer: Singleplayer

Additional Information:
![](https://i.imgur.com/8dOh97v.png)

**Comment by AEnterprise** [comment]
not something we can fix in BC itself due to the 'no external deps' policy but afaik @faceofcat fixed this in compat (not released for 1.12 yet but will come)

**Comment by AlexIIL** [comment]
No, he didn't. Or at least it was never in bc compact 7.99.0. I'll leave this open until it's fixed in compat.

**Comment by AlexIIL** [comment]
https://github.com/BuildCraft/BuildCraftCompat/commit/687ae392e6fa7af869e458f3ce4650c73ef9d624
