### ISSUE TITLE
Texture flickering and FPS drop on mining well when it's complete - likely turning on and off rapidly

### ISSUE THREAD

**Issue by TheDeviantCrafter** [BuildCraft/BuildCraft#3869]
**Buildcraft** version:  7.99.12
**Forge** version: 1.12.2-14.23.1.2554
Link to crashreport or log: https://pastebin.com/8TSdwcej
Singleplayer/multiplayer: Singleplayer

Additional information:

When a mining well has finished its job, it seems like it's rapidly switching from on to off. The F3 screen shows an "isComplete = true" value, which flickers to "isComplete = false" for one frame several times per second.

It also occasionally renders the mining pipe for a single frame. The bottom texture also flickers when the camera is moving, but is still (although glitchy looking) when standing still.

This only happened in my flatland testing world when it had power, but had drilled all the way down to bedrock. If it was still drilling, or if it has just been placed but didn't have any power, it worked as expected with no FPS loss or texture flickering.

F3 screen and texture: https://i.imgur.com/E6vaLD5.png

**Comment by ahertghegfbhrt** [comment]
I have that exact same problem. Did you find any solution?

**Comment by AEnterprise** [comment]
sadly there is no solution from a players perspective, this is an issue that needs to be fixed in the code

**Comment by Dockter** [comment]
I can confirm that I am seeing this as well.  Using Build 7.99.17-pre1.  Attached is a profiler screenshot showing the hotspot.

http://www.almuramc.com/images/bc-pump-issue.png
