### ISSUE TITLE
1.12.2 -- Bug -- Journeymap display issue w/BC 7.9.9.12

### ISSUE THREAD

**Issue by bcampbell2858** [BuildCraft/BuildCraft#3870]
**Buildcraft** version:  7.9.9.12
**Forge** version:  14.23.0.2551

**No Crash**

**Single Player**

**Additional information:**

After installing BC for MC 1.12.2, the display for fullscreen Journeymap isn't working properly.  It just displays a solid blue screen (I've attached a picture).  I've double checked and removed BC and the map works properly again.  An interesting note...when on that blue screen, my MC toolbar is present, yet despite being hidden, I can mouse over where the Journeymap icons would be and get the JM tool tip info.

![2017-11-26](https://user-images.githubusercontent.com/28824820/33239917-bd5e4040-d27a-11e7-934d-fb9f4bc3dd66.png)

Thanks for your hard work!

**Comment by AEnterprise** [comment]
this is a realy weird one, can you provide a full modlist (or a debugcrash would have that info)?

did you also open a ticket about this with journeymap? if not can you do that and link back here? i don't see how BC itself would be messing with their map gui but they might have an idea

**Comment by bcampbell2858** [comment]
Will do, I'll get back to you shortly

**Comment by bcampbell2858** [comment]
These are from the \logs folder....hope they are what you need:  
[fml-client-latest.log](https://github.com/BuildCraft/BuildCraft/files/1503901/fml-client-latest.log)
[latest.log](https://github.com/BuildCraft/BuildCraft/files/1503902/latest.log)

Will post link to Journeymap discussion shortly

**Comment by AEnterprise** [comment]
looks like you have optifine installed, can you try removing that? it's a very likely candidate to be messing up the map

**Comment by bcampbell2858** [comment]
Optifine disabled.  So far so good.  Pretty weird.  I didn't really think to check optifine considering the problems started after installing the new BC (although it was hours later, not immediate...and intermittent at first).  I wouldn't close the ticket quite yet...give it to the end of the day and I'll check back in if I have further issues.  

Thanks for your help!

**Comment by AEnterprise** [comment]
i suspect the introduction of BC has somehow caused optifine to misbehave in a way that affects journeymap (not the first time optifine would corrupt sprites when other mods get added with custom stuff), sadly there is not much we can do from our end about it though

**Comment by bcampbell2858** [comment]
Its all good, would much rather have BC installed than optifine!

Thanks!

**Comment by bcampbell2858** [comment]
FYI, I have yet to see any further issues with Journeymap.  Thanks again for your extremely quick help.
