### ISSUE TITLE
leadstone fluxduct can't connect to quarry

### ISSUE THREAD

**Issue by LizzardWizard** [BuildCraft/BuildCraft#3872]
**Buildcraft** version: 7.99.12
**Forge** version: 14.23.0.2552
Link to crashreport or log: none
Singleplayer/multiplayer: multiplayer

Additional information: tried using coal generator, did not work

**Comment by LuigiHutch** [comment]
Thanks for the report. This is actually a duplicate of #3760

**Comment by SalvadorScalia** [comment]
+1 
Leadstone Fluxduct  can not connect to quarry.
