### ISSUE TITLE
BuildCraft Silicon crashes game and server

### ISSUE THREAD

**Issue by EliSauder** [BuildCraft/BuildCraft#3873]
**Buildcraft** version: 7.99.12
**Forge** version: 1.12.2-14.23.0.2552

Crash Reports:
Server:
https://gist.github.com/EliSauder/6d0058392511965b1ad7b65e20964e1a#file-crash-2017-11-26_15-58-19-server-txt

Client:
1. (w/silicon) https://gist.github.com/EliSauder/fa55fb7fa80cad988910ba9c2040705f#file-crash-2017-11-26_15-58-13-client-txt

2. (w/o silicon) https://gist.github.com/EliSauder/9e2aefebac2eff3ac47967c1d046fc3e#file-crash-2017-11-26_16-21-54-client-txt

Additional information:
I had no problem running the server till I added in all of the build craft alpha mods. After it crashed and i looked through the report and saw the silicon module giving an error I removed it. I then restarted the server and it started up fine. But when i started up my client it crashed with all of the other modules giving errors. (second crash report)

**Comment by AlexIIL** [comment]
It looks like silicon has a dependency on factory when it shouldn't, and lib has a dependency on silicon when it shouldn't. Can you try downloading the the factory module (or replacing all of the current ones with the all jar)?

**Comment by EliSauder** [comment]
The all jar as in the one that has them all in one?

**Comment by EliSauder** [comment]
If so then it loads up fine. I still haven't tested all of the machines and cross compatibility but it doest crash the game on start up 👍

**Comment by EliSauder** [comment]
So far nothing has gone wrong got a quarry running with a pump and multiple engines and pipes and no crashing seems like the all in one version works fine. Only issues I see are that some of the item names aren't showing up right in game.

**Comment by AEnterprise** [comment]
if i find the time i'll see if i can do some magic with a script and/or gradle to get an automated test that splits the modules and compiles them seperately with only a dep on lib so this kind of intermodule dep would pop up before release

**Comment by AlexIIL** [comment]
That wouldn't actually help, as modules are allowed to softly depend on other modules anyway for compat, but they need to wrap them in is this module loaded checks.

**Comment by EliSauder** [comment]
Maybe it is the load in order? Like some of the modules are loading in while there still isn't compatibility  since the core mod hasn't been loaded?

**Comment by AlexIIL** [comment]
Nope. Even if the load order was wrong, the classes are made loadable before pre-init (for every mod).

**Comment by EliSauder** [comment]
Ah gotcha
