### ISSUE TITLE
game crash when breaking heat exchanger 

### ISSUE THREAD

**Issue by puffpants** [BuildCraft/BuildCraft#3874]
**Buildcraft** version: 7.99.12
**Forge** version: 14.23.1.2554
Link to crashreport or log: https://pastebin.com/Bqvb7TCP
Singleplayer/multiplayer: only play single player

**Comment by AlexIIL** [comment]
Fixed in https://github.com/BuildCraft/BuildCraft/commit/56566469b9853822b9e7b5331370bad8319c2719

**Comment by AlexIIL** [comment]
(We leave issues open until the version with the fix is out)
