### ISSUE TITLE
Carbon rotors magically repair themselves(visual bug)

### ISSUE THREAD

**Issue by BoomBap420** [BuildCraft/BuildCraft#3875]
**Buildcraft** version: 7.1.23
**Forge** version: 10.13.4.1614-1.7.10
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: Singleplayer(Maybe both)

Additional information:
I recently changed rotors on my wind generators and stored all the almost broken rotors in a chest. Today when I checked inside the chest, all the rotors were completely repaired. Now this is just a visual bug and when you put them in a wind generator they will actually have correct damage values again.
This only seemed to happen with carbon rotors. I tried with iron and didn't happen. Didn't try all the rotors tho.
How to replicate: Get a carbon rotor with some damage, put it in a chest, relog.

**Comment by AEnterprise** [comment]
buildcraft does not have any rotors, wind generators or similar, the might be from IC2? check what mod they are from and report there

**Comment by BoomBap420** [comment]
lol. I'm an idiot. Sorry, wrong mod :D
