### ISSUE TITLE
[1.12.2] Crash on Game start

### ISSUE THREAD

**Issue by MasterEnderman** [BuildCraft/BuildCraft#3876]
**Buildcraft** version: 7.99.12
**Forge** version: 14.23.1.2556
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : https://pastebin.com/UjEAWS8h
Singleplayer/multiplayer: Singleplayer

**Comment by AEnterprise** [comment]
issue with the covens mod not handeling oredict wildcard metadata
