### ISSUE TITLE
Crash when opening Creative search tab: Updating Screen Event's

### ISSUE THREAD

**Issue by Shiz0id** [BuildCraft/BuildCraft#3877]
Minecraft: 1.11.2
Buildcraft** version: 7.99.8.1
Forge** version: 13.20.1.2530
Link to crashreport : https://pastebin.com/yVdjL2Fw
Singleplayer/multiplayer: Multiplayer, but this only crashes clients, the server is unaffected

**Comment by HorizonsMC** [comment]
Happens with far more than the creative search tab.

I've had it happen when joining the game and happen when using conflicting commands when GUIs open.

This should be fixed ASAP as you can use it to dupe blocks with the carry on mod if you purposefully abuse it to crash.

**Comment by AEnterprise** [comment]
if another mod is causing dupe's as a result of the game crashing you wana report that to that mod as that mod is probably doing something funky then

it's crashing cause somehow a null blockstate is being written to NBT, seems like some mod is managing to get past earlier safety checks yet return null there, if you could narow down the mod (or even block(s)) causing this it would help a lot

@AlexIIL could you maybe add some aditional safety checks at that points to stop it from crashing but log what block is misbehaving?

**Comment by AlexIIL** [comment]
@Shiz0id and @HorizonsMC, can you retry with this testing jar: [7.99.13-pre1](https://www.mod-buildcraft.com/releases/testing/BuildCraft/7.99.13-pre1/buildcraft-7.99.13-pre1.jar)?

**Comment by AlexIIL** [comment]
Update, pre-2 has been uploaded as pre-1 didn't work quite right.

**Comment by HorizonsMC** [comment]
Unable to test on 1.12.2 because of this crash.

https://pastebin.com/5jW6HwPZ

**Comment by AlexIIL** [comment]
Thanks for testing - I should probably have mentioned, but I moved the crashing code to post-init so that it would crash quickly rather than waiting for a while. I've uploaded [7.99.13-pre3](https://www.mod-buildcraft.com/releases/testing/BuildCraft/7.99.13-pre3/buildcraft-7.99.13-pre3.jar) to fix the first crash (looks like some tests broke immediately)

**Comment by AlexIIL** [comment]
Actually it looks like I made a mistake in pre-3: please don't test it quite yet, its broken.

**Comment by HorizonsMC** [comment]
New crash: https://pastebin.com/Vb4et2v1

**Comment by AlexIIL** [comment]
Thanks. That's odd, I'll do some testing with forestry for a bit...

**Comment by HorizonsMC** [comment]
I removed forestry and all my bee mods and it gave me the same error with extrautils on a different block.

**Comment by AlexIIL** [comment]
Ok here's [pre-4](https://www.mod-buildcraft.com/releases/testing/BuildCraft/7.99.13-pre4/buildcraft-7.99.13-pre4.jar), which doesn't seem to be crashing with forestry or extra utils any-more. although it has a lot of log spam with nonconforming properties.

**Comment by AlexIIL** [comment]
Ok, looks like extra utils wasn't ported quite carefully enough (the method "IProperty.parseValue" used to be client side only, however in newer versions it was changed to be on the server as well), and it looks like @rwtema didn't spot that small change. Unfortunately it doesn't look like he'll be back anytime soon.

**Comment by HorizonsMC** [comment]
Anyway to skirt around the issue or will buildcraft be incompatible with EXU2 till they can fix the mistake?

**Comment by AEnterprise** [comment]
since the first report he generated pointed at forestry does that mean the same issue is present there?

**Comment by AlexIIL** [comment]
@HorizonsMC it means that you won't be able to make any facades from extra utils blocks.

@AEnterprise possibly a slightly different issue, I think I'll need to look into it a bit more.

**Comment by AEnterprise** [comment]
alright, just making sure there aren't any issues in other mods that should be forwarded

**Comment by AlexIIL** [comment]
It likely will need to be, I just want to make sure that ````IProperty.getName(value)```` is actually meant to mirror ````IProperty.parseValue(name)````, and its actually a big issue if they don't.

**Comment by AlexIIL** [comment]
@HorizonsMC Thanks for the heads up with locale names conflicting - although note that I don't get notifications on edits, so I might have missed that :/

**Comment by AlexIIL** [comment]
In theory all crashes should now be fixed in [7.99.13-pre5](https://www.mod-buildcraft.com/releases/testing/BuildCraft/7.99.13-pre5/buildcraft-7.99.13-pre5.jar)

**Comment by HorizonsMC** [comment]
Sorry for the late reply, I was busy today, just grabbed  7.99.13-pre8 and it's giving a new crash on both client and server.

https://pastebin.com/uZpu3zTZ

**Comment by AlexIIL** [comment]
That's fixed by https://github.com/TheCBProject/CodeChickenLib/pull/119. (Hopefully they pull it and release it soonish)

**Comment by HorizonsMC** [comment]
Okay, got CodeChickenLib-1.12-3.1.4.327-universal which should have the fix for the old crash and_ I'm running 7.99.13-pre9 and here is a new crash with Integrated Dynamics.

https://pastebin.com/8fmwwgap

**Comment by AlexIIL** [comment]
I should probably have already linked the PR but that was fixed by https://github.com/CyclopsMC/IntegratedDynamics/pull/442

**Comment by kreezxil** [comment]
I'm using 7.99.12 in my curseforge pack and got this error on the client side. It happens when you use the creative search button.

client crash report: https://gist.github.com/kreezxil/fa711dbebbe722a6e42893cde1360108

**Comment by AlexIIL** [comment]
@kreezxil Can you retry with [7.99.13-pre10](https://www.mod-buildcraft.com/releases/testing/BuildCraft/7.99.13-prereleases/buildcraft-7.99.13-pre10.jar)?

**Comment by AEnterprise** [comment]
sounds like this was #3990 and thus should be fixed? also no reply for a long time

if this does heapen again let us know
