### ISSUE TITLE
Possible eleccore conflict. 7.99.12

### ISSUE THREAD

**Issue by border999** [BuildCraft/BuildCraft#3880]
Close up seeing this, but please. There does appear to be some form of referencing issue that occurs when eleccore 1.12.2-1.8.433 and buildcraft 7.99.12 are in the same modpack. Just wanted to bring the possibility to your attention. This may be entirely on their side if you're certain it's not on yours.

**Comment by AEnterprise** [comment]
please provide more information on this issue, 'possible referencing issue' doesn't tell us anything, please provide screenshots if it's a visual issue or more detail on what exactly is heapening (logs also might help)

**Comment by AlexIIL** [comment]
Is this https://github.com/Elecs-Mods/ElecCore/issues/127?

**Comment by AEnterprise** [comment]
might be though nothing there is pointing to BC specificaly in the reports, seems somewhere something in an event handler of eleccore is returning a null world? not sure what exactly they are doing

**Comment by AlexIIL** [comment]
It looks like they cache something (block update positions?) earlier, and then it crashes when trying to handle them later down the line. Unfortunately there's little that we can do about this without more info narrowing down exactly the interaction that causes it, or if one of the elec-core devs takes a look at it.

**Comment by border999** [comment]
I'll give you a stripped down version of my last load up log. (Striped because optifine makes thousands of lines of the log) World loads up, but (assuming that you weren't tabbed into it when it loaded up) When you resume the game, it shuts down the world with some form of exception error. I will also say it may be possible that buildcraft is simply slowing down the game so much that other errors start to occur.

**Comment by border999** [comment]
https://gist.github.com/border999/4e9bdfccac9ee3d3b38d61947d2de3be

**Comment by AlexIIL** [comment]
That log doesn't have any exceptions at the end of it or a crash report indicating that it crashed or shutdown. Was that on a server, or is the log file truncated?

**Comment by border999** [comment]
truncated

**Comment by AlexIIL** [comment]
Unfortunately most of the log is just startup info, which isn't related to this problem. Can you upload just the *end* of the log? (Although I probably won't be able to help much, as it's waiting for @Elec332 to check what's causing the crash in eleccore)

**Comment by border999** [comment]
Alright, I'll see how far I can trim it down.

**Comment by border999** [comment]
https://pastebin.com/vTyQ9Jyx

**Comment by border999** [comment]
also seems to be throwing a rather large error on tracking Extra Utilities based items if I'm reading this correctly.

**Comment by AEnterprise** [comment]
still nothing pointing to BC in any way, the only errors in there are extra utils related, MC not being able to connect its sessionserver advancement related errors (guessing some recipes got removed or otherwise messed with)

but nothing that sheds a light on this issue, best to wait for @Elec332 at this point to take a look at the issue from his side

**Comment by border999** [comment]
Indeed. I will also say that I only bring this up to you because these issues only began to occur after adding buildcraft to my pack.

**Comment by AEnterprise** [comment]
it might be BC but nothing is pointing directly at BC so without more info on what the exact cause is we can't realy do anything

**Comment by FrancisDaPugtato** [comment]
border did you update Forge as well?  Update Extra Utils as well. This was a major bug I faced too, but its fixed in the latest update of extra utils and forge.

**Comment by border999** [comment]
define "Latest"

**Comment by Aquaeyes** [comment]
Newest?

**Comment by border999** [comment]
the crash seems to be resolved, anyone else that had this issue getting the same result?

**Comment by Isolonice** [comment]
It happends when i unload a world with sponge (even with lastest forge and EU):
https://pastebin.com/MnW7hrfc

**Comment by border999** [comment]
per the actual issue for which this discussion is about, that while the "latest" versions of forge and Extra Utilities 2 solve the problem of being unable to enter the world. The crash still occurs every so often and I have yet to identify if It's something I'm doing or if it's something under the hood catching on something else and crashing.

**Comment by AEnterprise** [comment]
i'm gona close this as not a BC issue for now then, if someone finds proof pointing directly at a part of BC feel free to comment and we can look at it at that time
