### ISSUE TITLE
The buckets are doubled in the combustion engine

### ISSUE THREAD

**Issue by Bryanbetatester** [BuildCraft/BuildCraft#3886]
**Buildcraft** version: 7.99.12
**Forge** version: 14.23.1.2555
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: Singleplayer

Additional information: When you select the water tank in the combustion engine with a bucket the bucket is doubled

**Comment by AlexIIL** [comment]
Just to check, is the bucket still doubled if you close and re-open the engine GUI? In dev it looks like its just a client desync

**Comment by AlexIIL** [comment]
Ok, yes, this is very buggy atm
