### ISSUE TITLE
Pipe and other textures not loading.

### ISSUE THREAD

**Issue by Jmari0** [BuildCraft/BuildCraft#3887]
**Buildcraft** version: 7.99.8
**Forge** version: 1.11.2-13.20.1.2386
**Singleplayer**
![2017-12-01_21 13 41](https://user-images.githubusercontent.com/34179912/33512108-e04ab5ea-d6dd-11e7-9384-e4ea74216043.png)
![2017-12-01_21 25 38](https://user-images.githubusercontent.com/34179912/33512125-4a89c004-d6de-11e7-99c8-158bb30f65ea.png)
![2017-12-01_21 25 44](https://user-images.githubusercontent.com/34179912/33512127-590cda12-d6de-11e7-85ce-be094e2c61db.png)
![2017-12-01_21 25 50](https://user-images.githubusercontent.com/34179912/33512129-6083a244-d6de-11e7-8005-47113fe12f02.png)
![2017-12-01_21 26 07](https://user-images.githubusercontent.com/34179912/33512131-6856b90c-d6de-11e7-965e-6894d56dae16.png)
![screenshot_20171201212836](https://user-images.githubusercontent.com/34179912/33512143-a514a778-d6de-11e7-986e-35524d6ad9ea.png)
Additional information:

I restarted my game and the pipes and other textures failed to load.

**Comment by AEnterprise** [comment]
can you try without optifine? that is known to mess with rendering

also there is a newer version of BC available: 7.99.8.1

**Comment by Jmari0** [comment]
Worked with optifine before... now it doesnt...

Going to try the new version.

**Comment by Jmari0** [comment]
Figured it out, in Optifine, when you turn on anisotropic filtering, the pipes fail to render. (This happened on the newer version of Buildcraft 7.99.8.1)

**Comment by AEnterprise** [comment]
glad you figured it out, if it's an optifine issue there sadly isn't anything we can do about it, you'll want to report it to the optifine devs
