### ISSUE TITLE
Refining Oil bug?

### ISSUE THREAD

**Issue by MSA-i** [BuildCraft/BuildCraft#3892]
**Buildcraft** version: 7.99.12
**Forge** version: 1.12.2.-14.23.1.2555

Singleplayer
 
![2017-12-05_13 26 16](https://user-images.githubusercontent.com/25800827/33590185-14fcb230-d9c1-11e7-8cf4-e6a70d1aafac.png)

Additional information:
using OptiFine_1.12.2_HD_U_C6

**Comment by AEnterprise** [comment]
looks like it is working just fine but it is now the distiller and doesn't work exactly the same, see this guide: http://imgur.com/a/AXUOX
