### ISSUE TITLE
Textures not showing 1.12.2

### ISSUE THREAD

**Issue by NexVoid** [BuildCraft/BuildCraft#3894]
**Buildcraft** version: 1.12.2 
**Forge** version: 14.23.1.2559 
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: Singleplayer 

Additional information: Very few textures are showing.  Some eventually load (somewhat).

**Comment by LuigiHutch** [comment]
Thanks for the report! Have you got some screenshots? Do you have optifine installed? if so try removing that

**Comment by NexVoid** [comment]
Yes, I have optifine I will take that off and try again.

**Comment by LuigiHutch** [comment]
Also try turning Anisotropic Filtering off in optifine

**Comment by NexVoid** [comment]
It still doesn't work.

**Comment by NexVoid** [comment]
![buildcraft](https://user-images.githubusercontent.com/34281082/33620835-3b834ba0-d9a6-11e7-9248-8f26f540e7a1.PNG)

**Comment by NexVoid** [comment]
![buildcraft 2](https://user-images.githubusercontent.com/34281082/33620964-9eeb3446-d9a6-11e7-90b0-7712f751b144.PNG)
This is with optifine and anisotropic filtering off.

**Comment by AlexIIL** [comment]
Can you list the mods that you are using? It looks like one of them doesn't clear a renderer properly...

**Comment by NexVoid** [comment]
Only two mods. BuildCraft and optifine.

**Comment by NexVoid** [comment]
![buildcraft 3](https://user-images.githubusercontent.com/34281082/33621248-61e04162-d9a7-11e7-8937-10494fd45472.PNG)
I reloaded my textures and turned anisotropic filtering to 16.

**Comment by AlexIIL** [comment]
Ok, so it looks like optifine doesn't quite like how we register our pipe textures, as its moving them around. Can you upload your fml-client-latest.log file to https://gist.github.com/, as that might contain more information.

**Comment by NexVoid** [comment]
sure

**Comment by AlexIIL** [comment]
Also, does this happen in-world? If so this might be related to https://github.com/sp614x/optifine/issues/1042

**Comment by NexVoid** [comment]
do you mean in a loaded world that I am playing on as in-world? If so yes.

**Comment by NexVoid** [comment]
<script src="https://gist.github.com/NexVoid/82a09dd50ed9ed1575d87d501e8eeb7b.js"></script>

**Comment by AlexIIL** [comment]
As in placed as a block.

**Comment by NexVoid** [comment]
oh, Some do and some don't. I will add a screenshot.

**Comment by NexVoid** [comment]
![2017-12-05_10 41 50](https://user-images.githubusercontent.com/34281082/33621712-f7569088-d9a8-11e7-9f42-16fbdb6fe9c6.png)
The engine is not showing correctly in my hot bar but shows when I place it. But the pipes are not right. And when I reload my textures with F3 + T the textures for the items change.

**Comment by AlexIIL** [comment]
Ok, according to the log optifine is encountering a lot of errors when stitching some of buildcraft's textures. That might be todo with our custom class "AtlasSpriteSwappable", so I'll try adding a config to disable that (although that will disable some other things, like fluid textures and colourblind alternative textures without manual reloading)

**Comment by NexVoid** [comment]
I found that it is all optifine. I took it off and everything looks good. But is there still a way to use optifine. I don't need it but I would like to.

**Comment by AlexIIL** [comment]
I'm in the middle of making a temp-fix for it - I'll upload a testing jar shortly, which is to check to see if it does actually fix it. (If it does that means you can use both).

**Comment by NexVoid** [comment]
ok thanks

**Comment by AlexIIL** [comment]
Can you try with [7.99.13-pre7](https://www.mod-buildcraft.com/releases/testing/BuildCraft/7.99.13-pre7/buildcraft-7.99.13-pre7.jar), but disable the config option "display.useSwappableSprites" in order to test it properly.

**Comment by NexVoid** [comment]
yes

**Comment by NexVoid** [comment]
with optifine?

**Comment by AlexIIL** [comment]
Yes, with optifine. (I'm assuming that 7.99.12 works properly without optifine installed anyway)

**Comment by NexVoid** [comment]
yes

**Comment by NexVoid** [comment]
It still does't work correctly. Also should I turn anisotropic filtering off?

**Comment by AlexIIL** [comment]
Woops, looks like I made a mistake and didn't actually hook up the config file properly :(

**Comment by AlexIIL** [comment]
Ok, here's [pre8](https://www.mod-buildcraft.com/releases/testing/BuildCraft/7.99.13-prereleases/buildcraft-7.99.13-pre8.jar), which should actually work this time...

Try with anisotropic filtering off as well perhaps?

**Comment by NexVoid** [comment]
It works with and without anisotropic filtering 8 and 16.

**Comment by AlexIIL** [comment]
Oh good. In which case the fix will be included with 7.99.13 (as well), which probably isn't too many days away now. The pre8 jar should be stable though.

**Comment by NexVoid** [comment]
Thank you so much.

**Comment by taketh3** [comment]
404 not found, can you give me another link?

**Comment by taketh3** [comment]
Hi, it's 404 not found, can you give another link?

**Comment by AEnterprise** [comment]
you can download the latest version (that includes this fix) at https://www.mod-buildcraft.com/pages/download.html
