### ISSUE TITLE
Crash with Mekanism Generators 1.12.2

### ISSUE THREAD

**Issue by Eggonomicon** [BuildCraft/BuildCraft#3896]
**Buildcraft** version: 7.99.12
**Forge** version: 14.23.1.2555

https://pastebin.com/i0hRL8Eg

Singleplayer/multiplayer: (Both) Crash on startup

Additional information:
Conflic between Buildcraft and Mekanism Generators.

**Comment by AlexIIL** [comment]
See https://github.com/aidancbrady/Mekanism/issues/4827

**Comment by Eggonomicon** [comment]
Just noticed it. 
Thank you.

**Comment by AEnterprise** [comment]
closing as the fixed mekanism version has been out for a bit
