### ISSUE TITLE
Fluids do not get transferred between tanks when using ExtraUtilities' fluid transfer and retrieval nodes but are instead deleted

### ISSUE THREAD

**Issue by Brandon-Gui123** [BuildCraft/BuildCraft#3897]
**Buildcraft** version: 7.99.13-pre8
**Forge** version: 1.12.2-14.23.1.2555
Singleplayer/multiplayer: Singleplayer

Additional information:
Running Extra Utilities 2 Version 1.12-1.6.8
When a fluid transfer node is set-up as shown below, the fluid level of the tank next to the transfer node goes down but no fluid shows up in the other tank.
![2017-12-07_10 04 39](https://user-images.githubusercontent.com/34325463/33695112-7cc64202-db36-11e7-9986-75f8ca76541f.png)
When a fluid retrieval node is used as shown below, the fluid level in the tank will also go down and the fluid will be deleted.
![2017-12-07_09 43 56](https://user-images.githubusercontent.com/34325463/33695199-f37879c4-db36-11e7-9810-ec648cf9885b.png)
This bug applies to all fluids and appears to not affect the Extra Utilities 2 Storage Drums.

**Comment by AlexIIL** [comment]
Can you retry with [7.99.13-pre9](https://www.mod-buildcraft.com/releases/testing/BuildCraft/7.99.13-prereleases/buildcraft-7.99.13-pre9.jar)?

**Comment by Brandon-Gui123** [comment]
The problem's solved! Now there are no more fluid losses.
