### ISSUE TITLE
Crash during mod loading when starting BuildCraft with other mods

### ISSUE THREAD

**Issue by Brandon-Gui123** [BuildCraft/BuildCraft#3899]
**Buildcraft** version: 7.99.13-pre9
**Forge** version: 1.12.2-14.23.1.2555
Link to crash report: [https://gist.github.com/Brandon-Gui123/209d0b2e312fa9c2857a36dab827d356](https://gist.github.com/Brandon-Gui123/209d0b2e312fa9c2857a36dab827d356)

Additional information:
The crash didn't occur when BuildCraft was taken out from the "mods" folder.

Other mods present:
-BiomesOPlenty-1.12.2-7.0.1.2302-universal
-CodeChickenLib-1.12-3.1.3.313-universal
-CoFHCore-1.12.2-4.3.7.25-universal
-CoFHWorld-1.12.2-1.0.2.10-universal
-EnderZoo-1.12.1-1.4.0.49
-extrautils2-1.12-1.6.8 (Extra Utilities 2)
-jei_1.12.2-4.8.5.133 (Just Enough Items)
-OptiFine_1.12.2_HD_U_C7
-RedstoneFlux-1.12-2.0.1.2-universal
-ThermalCultivation-1.12.2-0.1.2.8-universal
-ThermalDynamics-1.12.2-2.3.7.14-universal
-ThermalExpansion-1.12.2-5.3.7.31-universal
-ThermalFoundation-1.12.2-2.3.7.18-universal

**Comment by AEnterprise** [comment]
related to #3877 , issue in codechickenlib that has been fixed (but no update released for it yet)
