### ISSUE TITLE
Buildcraft Energy & Fluid - IllegalArgumentException

### ISSUE THREAD

**Issue by SirTwsted** [BuildCraft/BuildCraft#3902]
**Buildcraft** version: 7.99.12
**Forge** version:  14.23.1.2555
**Minecraft** version: 1.12.2

**Link to crashreport or log (on pastebin or gist, please don't put the entire log here) :** 
https://pastebin.com/dbMftfcp

**Singleplayer/multiplayer:**  Single Player

**Additional information:**
I am using the 7 different independent packages.
And no, I am NOT using the Compat version - Yet.... as its not released for 1.12.2

**Comment by AEnterprise** [comment]
looks like an issue in sensorcraft, somehow it's rendering is getting associated with the oil block and when building the models that goes wrong

**Comment by AlexIIL** [comment]
This might be related to #3882.

@SirTwsted can you try with [7.99.13-pre9](https://www.mod-buildcraft.com/releases/testing/BuildCraft/7.99.13-prereleases/modules/)?

**Comment by SirTwsted** [comment]
@AlexIIL ok, have to give me a bit of time tho.
but ill try the Pre versions and let you know if I break anything.

**Comment by SirTwsted** [comment]
@AlexIIL  - I broke It again....
Caught exception from BuildCraft Transport
Caused by: java.lang.NumberFormatException: For input string: ""
.
https://pastebin.com/tBWUmbHT
.
MC v1.12.2
Tested with (buildcraft 7.99.13-pre9) "7 separate packages"
Using Forge v14.23.1.2555

**Additional Notes:**
When I use (buildcraft-lib-7.99.13-pre9) and (buildcraft-core-7.99.13-pre9)
I thought these go together, I guess not  :(
Anyways, I disabled the (buildcraft-lib-7.99.13-pre9) and just used (buildcraft-core-7.99.13-pre9)
with the additional packages and I got the crash posted above.

**Comment by AlexIIL** [comment]
Ah. Unfortunately it looks like you're encountering some WIP stuff related to #3877. (Which can be temp-fixed by removing codechickencore or (updating it from their maven?))

Core includes lib (as there's no reason not to), which just means that you don't have to download lib if you need core.

**Comment by SirTwsted** [comment]
ok, let me know if you need another guinea pig test  :P

**Comment by AEnterprise** [comment]
@SirTwsted do you still have this issue? the crashes should be fixed from codechickenlibs end if you update it

**Comment by AlexIIL** [comment]
Should have been fixed.
