### ISSUE TITLE
"Caught exception from BuildCraft Transport"

### ISSUE THREAD

**Issue by JackSLR783** [BuildCraft/BuildCraft#3903]
**Minecraft** version: 1.12.2
**Buildcraft** version: 7.99.13-pre9
**Forge** version: 14.23.1.2555
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : https://pastebin.com/CVstU9jV
Singleplayer/multiplayer: Singleplayer

Additional information:
This issue randomly started when I launch minecraft. It has happened before, but has somehow fixed itself.

**Comment by AlexIIL** [comment]
Fixed in https://github.com/TheCBProject/CodeChickenLib/pull/119 -- I have no idea what their release schedule is, but updating to a version that was released after the 5th of December should fix it.

**Comment by JackSLR783** [comment]
Okay thanks!

**Comment by DeadSix27** [comment]
@AlexIIL With CCL updated I run into this issue with integrateddynamics:
https://gist.github.com/DeadSix27/9c0d39f957c162a9cdd8d3e606ea660a

**Comment by LuigiHutch** [comment]
As stated in https://github.com/BuildCraft/BuildCraft/issues/3877, that was already fixed and just waiting for a release: https://github.com/CyclopsMC/IntegratedDynamics/pull/442

**Comment by DeadSix27** [comment]
@LuigiHutch ah, silly me didn't expect another issue for that. Thanks for pointing it out

**Comment by AEnterprise** [comment]
closing as fixed integrated dynamics version has been released
