### ISSUE TITLE
Robots

### ISSUE THREAD

**Issue by MathiasOB** [BuildCraft/BuildCraft#3904]
**Buildcraft** version: 7.99.12 Alpha
**Forge** version: 
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: 

Additional information: 
 
There are no robots in this version. The pieces to make them are not available either, such as redstone board, crafting the integration table does not work, and the redstone crystal will not be created in the assembly table as it should.

**Comment by AEnterprise** [comment]
duplicate of 3755
they will return later
