### ISSUE TITLE
Machines can't connect with other mods.

### ISSUE THREAD

**Issue by Mxater** [BuildCraft/BuildCraft#3906]
**Buildcraft** version: 7.99.12
**Forge** version: 14.23.1.2562
Singleplayer/multiplayer: Singleplayer

Additional information:
I cant connect any other mods items with BC Machines. Example: Energy Cell (Thermal Expansion), Electric engine (Forestry). This item cant provide RF to machines.

![image](https://user-images.githubusercontent.com/4630666/33801913-0bd094e8-dd49-11e7-82dd-9784358a6c98.png)

thank you very much

**Comment by FrancisDaPugtato** [comment]
Have you tried BC Compat? Go to the BC Discord and ask for the BC Compat 1.12.2pre link. Also, BC is not RF anymore in any BC 7.99.x, and we are switching back to mJ.

**Comment by AEnterprise** [comment]
BC is indeed using a MJ again, and MJ <-> RF conversion is not a thing

compat won't help you in this case, the only way right now to make MJ is with BC engines
