### ISSUE TITLE
1.11.2 - Client crashes in the loading phase of the mods

### ISSUE THREAD

**Issue by TheusKhan** [BuildCraft/BuildCraft#3908]
**Buildcraft** version: Buildcraft 7.99.8.1 (buildcraft-7.99.8.1.jar)
**Forge** version: forge1.11.2-13.20.1.2386
Pastebin: https://pastebin.com/kDuT85md
Singleplayer/multiplayer: Singleplayer

Additional information:
The client closes during the loading phase of the mods when it is with BuildCraft. It started after an unexpected stop on my computer today. I have several mods, but when I try to start the game with BuildCraft the game crashes.
However, when I try to start without BuildCraft the game starts normally.

**Comment by FrancisDaPugtato** [comment]
Wow that was fast Alex. Could this be a CodeChickenLib thing since it has it mentioned in there?

**Comment by AlexIIL** [comment]
Can you upload the "config/buildcraft/gui.json" file please?

@FrancisDaPugtato no, its not.

**Comment by AlexIIL** [comment]
A temporary workaround should be to delete the "config/buildcraft/gui.json" file. I'm interested in its contents though, as theoretically it shouldn't have just turned from a normal JsonObject into a string...

**Comment by TheusKhan** [comment]
Yeah, maybe gui.json is corrupted. Here is:
[gui.zip](https://github.com/BuildCraft/BuildCraft/files/1550046/gui.zip)

**Comment by AlexIIL** [comment]
463 bytes of nulls. That's odd, perhaps BC has a bug with saving? I'm not sure how we should handle that, as we'd still like to save data to it...

**Comment by TheusKhan** [comment]
Lately I've been having problems with my PC, more specifically with RAM. I've 6 GB of RAM but some of them are corrupting the data and causing my computer to shut down.
This isn't the first problem I went through with BuildCraft because of RAM.
Another problem is that my worlds are being corrupted. I've found a quick solution to this which is to delete the .minecraft\saves\(WORLD NAME)\data\BCMod-Permissions.dat file.

**Comment by TheusKhan** [comment]
If the problem occurs again, I'll create a new topic.

**Comment by TheusKhan** [comment]
I deleted the file "config/buildcraft/gui.json" and it worked, my game is loading normally now. Thank you. You guys are pretty fast.

**Comment by AlexIIL** [comment]
I still need to change it to not throw an error and crash :p
