### ISSUE TITLE
Auto Workbench kills FPS

### ISSUE THREAD

**Issue by davqvist** [BuildCraft/BuildCraft#3911]
**Buildcraft** version: 7.99.12
**Forge** version: 2561
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: Multiplayer

Additional information:
Just only when placing down the Auto Workbench, FPS gets about cut in half, with like 3+ of them, game is practically unplayable. Not sure what info to give you beside of that, let me know if you have questions.

**Comment by AlexIIL** [comment]
Looks like the new autoworkbench tick() function is taking a lot longer than it should...

**Comment by AlexIIL** [comment]
Looks like someone thought it was a good idea to check the crafting slots every tick for a new recipe.

**Comment by AEnterprise** [comment]
oh right my bad, at the time there where issues with how slot handlers worked and detecting changes, seems i forgot to go back and fix fix that, it shoudn't be affecting fps though, only tps

**Comment by AlexIIL** [comment]
It also ran on the client, which is run in the same thread as the renderer

**Comment by AEnterprise** [comment]
hmm that's a oversight on my part then, it shoudn't run that on the client at all

**Comment by ecolortest** [comment]
what fps? 1 fps?

**Comment by AlexIIL** [comment]
@ecolortest if you placed down enough, eventually you'll reach 1fps
