### ISSUE TITLE
1.7.10 crash w/ buildcraft/api/gates/ITriggerProvider

### ISSUE THREAD

**Issue by boeing186** [BuildCraft/BuildCraft#3915]
**Buildcraft** version: 7.1.23
**Forge** version: 10.13.4.1558
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
https://pastebin.com/L0GrcaFX
Singleplayer/multiplayer: single

Additional information:

**Comment by AEnterprise** [comment]
it looks like one of your other mods is shipping an outdated BC api, best would be to see if all mods are up to date and if they are to, remove mods to find what it is and remove the api from that mod so the newer (correct) one gets loaded

**Comment by boeing186** [comment]
Thank you so much, it worked! I think it was AE2. I was using RV2 and some early alpha version
