### ISSUE TITLE
Translate to Russian version 7.99.12

### ISSUE THREAD

**Issue by Podrepny** [BuildCraft/BuildCraft#3916]
**Buildcraft** version: 7.99.12
**Forge** version: any
Singleplayer/multiplayer: any

Additional information:
File put to "buildcraft_1.12.2_7.99.12.jar\assets\buildcraft\lang\ru_RU.lang"

[ru_RU.lang.txt](https://github.com/BuildCraft/BuildCraft/files/1566047/ru_RU.lang.txt)

**Comment by LuigiHutch** [comment]
See https://github.com/BuildCraft/BuildCraft-Localization/issues/293

**Comment by AEnterprise** [comment]
sniped by luigi

**Comment by AlexIIL** [comment]
(Also note that this is the wrong repository: localization requests should be submitted as pull requests to https://github.com/BuildCraft/BuildCraft-Localization/pulls.)
