### ISSUE TITLE
Crash when load

### ISSUE THREAD

**Issue by ecolortest** [BuildCraft/BuildCraft#3918]
**Buildcraft** version: 7.1.14
**Forge** version: 13.20.1.2563
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) :  https://pastebin.com/SpGKP6xv
Singleplayer/multiplayer: 
Additional information:

**Comment by AEnterprise** [comment]
Buildcraft 7.1.14 is extremely outdated (was released about 2 years ago), please update to the lastest version for 1.7.10 (7.1.13)

also looking at the filename in the report this file was not downloaded from any official source, please check the offical site (https://www.mod-buildcraft.com/) or CF page for updates and use those

**Comment by AlexIIL** [comment]
It looks like you accidentally specified the wrong BC version: you are using "7.99.8.1", but wrote "7.1.14". Was the log file from a different game instance, or was that just a mistake when creating the issue?

**Comment by AlexIIL** [comment]
@AEnterprise additionally it looks like you made a mistake in your own comment - I'm pretty sure that "7.1.14" came after "7.1.13", not before :p .

@ecolortest from the log file it looks like you don't have the api code (in the jar file there should be an "buildcraft/api" folder). Redownloading might fix that.

**Comment by ecolortest** [comment]
@AlexIIL what is api forder? and were api file be put?

**Comment by AEnterprise** [comment]
it should be in the buildcraft jar, but as above i sugest you remove the file you have and download the latest version for your MC version from the official site

**Comment by ecolortest** [comment]
@AEnterprise how to add api forder?

**Comment by AEnterprise** [comment]
you do not add it yourself, as above i recomend you remove the file and grab it from the site as those are the official releases

**Comment by ecolortest** [comment]
i has use offical but same like this (im use minecraft 1.11.2)

**Comment by AEnterprise** [comment]
can you upload a new crashreport?
