### ISSUE TITLE
minecraft crashes when a quarry gets created 

### ISSUE THREAD

**Issue by August5** [BuildCraft/BuildCraft#3920]
**Buildcraft** version: 7.99.8.1
**Forge** version: 1.11.2
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: hamachi server

Additional information:

**Comment by AlexIIL** [comment]
Can you upload the crash report to https://gist.github.com/?

**Comment by AEnterprise** [comment]
Closing for a lack of information, if you provide the requested information we can re-open and take another look at this.
