### ISSUE TITLE
Some pipes are missing recipes.

### ISSUE THREAD

**Issue by AlexIIL** [BuildCraft/BuildCraft#3921]
The stripes pipe and emzuli pipes don't have recipes at the moment in 7.99.8.1. I haven't checked 7.99.12 yet.

**Comment by chris-x86-64** [comment]
I can see that those recipes are not present in 7.99.12 (Minecraft 1.12.2).
Confirmed using JustEnoughItems-- the recipe guide won't show.

**Comment by AlexIIL** [comment]
Ok, if they weren't in 7.99.12 then I doubt they were in 7.99.13 either.

**Comment by AlexIIL** [comment]
It turns out this was fixed long ago... (The recipes are in 7.99.24 anyway)
