### ISSUE TITLE
[1.11.2] Client Crashes When Crafting Tank

### ISSUE THREAD

**Issue by alphawolf918** [BuildCraft/BuildCraft#3922]
Crash Report: https://pastebin.com/BKWHVtWY

**Buildcraft** version: 7.99.8.1
**Forge** version: 1.11.2-13.20.1.2391
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: Multiplayer

Additional information:
When we craft a tank and try to grab it, the game crashes with a NullPointerException, referencing an issue about it rendering the screen.

**Comment by AEnterprise** [comment]
could you try removing optifine?

**Comment by alphawolf918** [comment]
Well, we could, but some of our users actually really need it and we would prefer not to. So if a fix could be implemented, that would be best. I might be able to do that temporarily, but I would much prefer them getting along as we've never had this issue before with other versions. It's only when we try to grab the tank from the crafting menu that it crashes.

**Comment by AEnterprise** [comment]
well the tank renders fine for normal crafting, i suspect this is the old bug again where optifine and tinkers construct crafting tables don't get allong and crash

**Comment by alphawolf918** [comment]
We tried it in a regular crafting bench, too - same result. So I don't think TConstruct has much to do with it, though I won't rule out its involvement somehow. Do you think you could implement a fix for this? If not then we do have other tanks that we can use, I just wanted to bring this to your attention because if something like this occurred with my own mods, I'd want to know so I could fix it.

**Comment by AEnterprise** [comment]
sadly this is something that is crashing in a place we can't do anything about, most likely it's optifine doing something else that is causing this as the stacktrace shows the crash occurs in `EntityRenderer.updateCameraAndRender`

**Comment by AEnterprise** [comment]
gona close this as an optifine issue, given the stacktrace and the very weird place it's crashing in there is nothing that can be done from this end to fix it without getting detailed info from the optifine dev (or it being fixed from that end)
