### ISSUE TITLE
Bugged quarry Alpha

### ISSUE THREAD

**Issue by TijsDeBelie** [BuildCraft/BuildCraft#3923]
**Buildcraft** version: 7.99.12
**Forge** version: 1.12.2
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : https://pastebin.com/8JnnwdKj
https://imgur.com/a/3v3Nr
Singleplayer/multiplayer: 
Singleplayer
Additional information:
First part of the log is from when I started it and joined a server (vanilla) so after that joined a singleplayer world I newly created. 

Started with placing the lanmarkers down and they connected nicely, after placing down the quarry and powering it up with creative engine(set to max) the frame from the quarry bugged out and didn't start to mine. 

game mechanics also froze and was not able to interact with landmarks I placed, they did not connect, also picking up blocks didn't work while inventory was empty. Game crashed shortly after

**Comment by AlexIIL** [comment]
Fixed in https://github.com/BuildCraft/BuildCraft/commit/a9e8d0062f3c892b3a4be36ac73b37f1f613230c
