### ISSUE TITLE
Redstone gates do not activate/deactivate signal properly

### ISSUE THREAD

**Issue by Ghent** [BuildCraft/BuildCraft#3925]
Gates do not seem to properly activate/deactivate redstone signals when changing state.  Please see gif for example.

https://i.imgur.com/FnyGRgW.gif

**Buildcraft** version:
buildcraft-7.99.13-pre10.jar commit a0000f70c236644b4e26541b3570878c5721e987

**Forge** version: 
forge-1.12.2-14.23.1.2566-universal.jar

Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: Both

Additional information:

**Comment by AlexIIL** [comment]
This should now be fixed in https://www.mod-buildcraft.com/buildcraft-79913-alpha-buildcraft-79982-alpha-buildcraftcompat-79913-alpha.html
