### ISSUE TITLE
the filler is not working, and i don't have a chance to craft it.

### ISSUE THREAD

**Issue by humberbp** [BuildCraft/BuildCraft#3927]
**Buildcraft** version: 
**Forge** version: 
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: 

Additional information:

**Comment by AEnterprise** [comment]
incomplete and re-submitted as #3928 

for future reference you can click the pecil in the top right of your report to edit it if you forgot to fill in the issue
