### ISSUE TITLE
The filler is not working and don't have a craft.

### ISSUE THREAD

**Issue by humberbp** [BuildCraft/BuildCraft#3928]
**Buildcraft** version: 7.99.8.1
**Forge** version: 1.11.2
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: 

Additional information:

**Comment by AEnterprise** [comment]
not all blocks are available in survival yet because they are not completely finished, for help on getting things setup feel free to join our discord server where people can help you
