### ISSUE TITLE
[1.12.2] Forge loading error with mods

### ISSUE THREAD

**Issue by daKINGofPANDAS** [BuildCraft/BuildCraft#3930]
**Buildcraft** version: 7.99.12
**Forge** version: 1.12.2
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: Single and Multiplayer

Additional information:
Mods in use: Buildcraft, CodeChikenLib, Hwyla, IronChest, jei, Mantle, Pam's HarvestCraft, SubLib, TelePads, Tinkers-Construct, TreeCapitator, VeinMiner, and Xaeros-Minimap. ( All mods are up to date and running with forge 1.12.2)

The problem started after I tried to add Thermal Expansion and all of its dependants. I kept crashing on stage 3 of the forge loader when its initializing the mod assets. Heres the error: 

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 12/21/17 5:30 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
    at buildcraft.lib.client.render.fluid.SpriteFluidFrozen.load(SpriteFluidFrozen.java:76)
    at net.minecraft.client.renderer.texture.TextureMap.loadTexture(TextureMap.java:145)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:110)
    at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:91)
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:168)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at buildcraft.lib.client.render.fluid.SpriteFluidFrozen.load(SpriteFluidFrozen.java:76)
    at net.minecraft.client.renderer.texture.TextureMap.loadTexture(TextureMap.java:145)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:110)
    at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:91)
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:168)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.12.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 129503592 bytes (123 MB) / 385875968 bytes (368 MB) up to 1073741824 bytes (1024 MB)
    JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.42 Powered by Forge 14.23.1.2581 33 mods loaded, 33 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

    | State | ID                  | Version           | Source                                          | Signature                                |
    |:----- |:------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
    | UCH   | minecraft           | 1.12.2            | minecraft.jar                                   | None                                     |
    | UCH   | mcp                 | 9.42              | minecraft.jar                                   | None                                     |
    | UCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.1.2581.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
    | UCH   | forge               | 14.23.1.2581      | forge-1.12.2-14.23.1.2581.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
    | UCH   | mercurius_updater   | 1.0               | MercuriusUpdater-1.12.2.jar                     | None                                     |
    | UCH   | buildcraftlib       | 7.99.12           | buildcraft-7.99.12.jar                          | None                                     |
    | UCH   | buildcraftcore      | 7.99.12           | buildcraft-7.99.12.jar                          | None                                     |
    | UCH   | buildcraftbuilders  | 7.99.12           | buildcraft-7.99.12.jar                          | None                                     |
    | UCH   | buildcraftenergy    | 7.99.12           | buildcraft-7.99.12.jar                          | None                                     |
    | UCH   | buildcraftfactory   | 7.99.12           | buildcraft-7.99.12.jar                          | None                                     |
    | UCH   | buildcraftrobotics  | 7.99.12           | buildcraft-7.99.12.jar                          | None                                     |
    | UCH   | buildcraftsilicon   | 7.99.12           | buildcraft-7.99.12.jar                          | None                                     |
    | UCH   | buildcrafttransport | 7.99.12           | buildcraft-7.99.12.jar                          | None                                     |
    | UCH   | codechickenlib      | 3.1.5.331         | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
    | UCH   | redstoneflux        | 2.0.1             | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
    | UCH   | cofhcore            | 4.3.7             | CoFHCore-1.12.2-4.3.7.25-universal.jar          | None                                     |
    | UCH   | cofhworld           | 1.0.2             | CoFHWorld-1.12.2-1.0.2.10-universal.jar         | None                                     |
    | UCH   | waila               | 1.8.20            | Hwyla-Mod-1.12.1 (1).jar                        | None                                     |
    | UCH   | ironchest           | 1.12.2-7.0.32.819 | IronChest-1.12.jar                              | None                                     |
    | UCH   | jei                 | 4.8.5.136         | jei_1.12.2-4.8.5.136.jar                        | None                                     |
    | UCH   | mantle              | 1.12-1.3.1.21     | Mantle-1.12-1.3.1.21.jar                        | None                                     |
    | UCH   | harvestcraft        | 1.12.2a           | Pam's HarvestCraft 1.12.2a.jar                  | None                                     |
    | UCH   | subcommonlib        | 1.2.0.1           | SubLib-1.12.jar                                 | None                                     |
    | UCH   | telepads            | 1.11.2-1.0.2.1    | TelePads-Mod-1.12.jar                           | None                                     |
    | UCH   | thermalfoundation   | 2.3.7             | ThermalFoundation-1.12.2-2.3.7.18-universal.jar | None                                     |
    | UCH   | thermalexpansion    | 5.3.7             | ThermalExpansion-1.12.2-5.3.7.31-universal.jar  | None                                     |
    | UCH   | tconstruct          | 1.12-2.7.3.30     | Tinkers-Construct-Mod-1.12.1.jar                | None                                     |
    | UCH   | bspkrscore          | at_0.9            | TreeCapitator-Mod-1.12.jar                      | None                                     |
    | UCH   | treecapitator       | at_0.9            | TreeCapitator-Mod-1.12.jar                      | None                                     |
    | UCH   | veinminer           | 0.38.1            | VeinMiner-1.12-0.38.1.639+134fb1e (1).jar       | None                                     |
    | UCH   | veinminermodsupport | 0.38.1            | VeinMiner-1.12-0.38.1.639+134fb1e (1).jar       | None                                     |
    | UCH   | xaerominimap        | 1.14.4            | Xaeros_Minimap_1.14.4_Forge_1.12.jar            | None                                     |
    | UCH   | xray                | 1.4.0             | xray-1.12.2-1.4.0.jar                           | None                                     |

    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4836' Renderer: 'Intel(R) HD Graphics 620'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerHarvestTools (Enabled/Forced)
        - TinkerMeleeWeapons (Enabled/Forced)
        - TinkerRangedWeapons (Enabled/Forced)
        - TinkerModifiers (Enabled/Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - TinkerModelRegister (Enabled/Forced)
        - wailaIntegration (Enabled/Not Forced)

    Launched Version: 1.12.2-forge1.12.2-14.23.1.2581
    LWJGL: 2.9.4
    OpenGL: Intel(R) HD Graphics 620 GL version 4.5.0 - Build 22.20.16.4836, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: Rodrigo's Pack [8x8] [1.12].zip
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 4x Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz

-----------------------------------------------------------------------------------------------------

But, when I removed the mods it worked again. So thinking it was just those mods that were screwed up I tried to download a different mod and got the same error. It just doesn't make sense to me, and if anyone could help that would be great.

**Comment by AEnterprise** [comment]
please follow the issue template and put the crashlog somewhere else and link it instead of pasting it in the report

can you remove the xray mod and see if that fixes it?

**Comment by AlexIIL** [comment]
I *think* that this has been fixed in dev. But I'm not sure, I'll ask you to recheck with 7.99.13 when its released.

**Comment by afdw** [comment]
And it's already released.
