### ISSUE TITLE
Duplicate @SideOnly(Side.Client) annotation in FluidManager.java

### ISSUE THREAD

**Issue by Dockter** [BuildCraft/BuildCraft#3931]
Error exists within latest version of 8.0.x

Package: buildcraft.lib.flud
Class:  FludManager.java

Line: 54, you have a duplicate @SideOnly(Side.Client) annotation that Gradle freaks out about during compiling.

**Comment by AEnterprise** [comment]
there is only a single one there: https://github.com/BuildCraft/BuildCraft/blob/6f612cce94b6fb7a0b4ed637ee6394254d347e8e/common/buildcraft/lib/fluid/FluidManager.java#L52-L54

recent git history doesn't show any duplicate sideonly annotaion being pressent for months
