### ISSUE TITLE
Can't power a quarry with RF

### ISSUE THREAD

**Issue by LaughinTucker75** [BuildCraft/BuildCraft#3933]
**Buildcraft** version: 7.99.12
**Forge** version: 14.23.1.2562 for 1.12.2
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: SP

Additional information:  I am having some issues with trying to power my quarry.  I'm used to Tekkit with easy connection between TE energy cells and the quarry providing easy portable power, however, i can't get it to work at all with the new updates. I've tried fluxduct, kinesis pipes and direct transfer but nothing. Have they completely removed the crossover forcing you to use extremely inefficient engines?

**Comment by AEnterprise** [comment]
yes BC has moved back to MJ and there is no direct conversion

there currently are no plans of navively allowing this behaviour again. And within the MJ ecosystem the engines are not (nor where they every) extremely efficient, you (and a lot of other people) just became used to the rediculous amounts of RF some other mods generate
