### ISSUE TITLE
Heat exchanger recipes unknown, and cannot be found

### ISSUE THREAD

**Issue by Cavillous** [BuildCraft/BuildCraft#3934]
**Buildcraft** version: Latest as of 24 dec 2017
**Forge** version: Latest as of 24 dec 2017
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : No data
Singleplayer/multiplayer: Singleplayer

Additional information:
It's lovely you've put the heat exchange mechanics in place but I can't find its recipe looking online.

**Comment by LuigiHutch** [comment]
BC Compat with JEI integration for 1.12 hasn't been released yet so I would recommend just expirmenting with it for now.

Recipes also aren't displayed in the guide book so this is still a valid issue :)

This may help if you havn't seen it already: http://imgur.com/a/AXUOX

**Comment by AEnterprise** [comment]
recipes will be added to the guide book later

also please do not use 'lastest' in bug reports, it's much easier if you put the exact number (also in case you think it's latest but it realy isn't)

also without an MC version we can't know what version exactly you mean
