### ISSUE TITLE
7.9.9.13 Crash game.

### ISSUE THREAD

**Issue by damir84** [BuildCraft/BuildCraft#3936]
**Buildcraft** version: 7.9.9.13
**Forge** version: 1.12.2-forge1.12.2-14.23.1.2581
Link to crashreport or log : https://pastebin.com/b5V4NmgY
Singleplayer

Additional information:
[b5V4NmgY.txt](https://github.com/BuildCraft/BuildCraft/files/1585996/b5V4NmgY.txt)

**Comment by AEnterprise** [comment]
this is an issue in codechickenlib that has been fixed, please update that mod

**Comment by LuigiHutch** [comment]
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3903. Update CodeChickenLib

**Comment by damir84** [comment]
Updated Codechicken and it works. Thank you!
