### ISSUE TITLE
[BC Transport] Crash on Loading Phase 5 of 7

### ISSUE THREAD

**Issue by hayesj1** [BuildCraft/BuildCraft#3939]
**Buildcraft** version: 8.99.13
**Forge** version: 14.23.1.2556

[crash report](https://gist.github.com/hayesj1/e48b001cdba6963640d59df7a93bd3c4)

Singleplayer

Additional information:
Crash on loading phase 5/7. Just updated from 8.99.12, first time loading BC 8.99.13 & BC compat 8.99.13. Tried a two more times and got the same same crash both times. i'm using the bundled BC(as in not modular) jar.

**Comment by AlexIIL** [comment]
Can you try updating codechickenlib?

**Comment by hayesj1** [comment]
that fixed it, Thanks!
