### ISSUE TITLE
Clear Glass bug, not crashing

### ISSUE THREAD

**Issue by Raghalin** [BuildCraft/BuildCraft#3942]
**Buildcraft** version: 7.99.12
**Forge** version: 1.12.2 - 14.23.1.2555

multiplayer: 
#1 when pouring from smeltery, if you look away then look back.  the white box frame for the glass appears and you can see the blue coloring filling while the block is in the cooling stage.

#2 if standing to close to where block is placed, the clear glass is 'used' (counter drops by 1) but no clear glass is actually placed.  aka you could place a 64 stack into 1 block and still not have a block apear.

sorry if this isn't enough info, I'm clueless about coding.

**Comment by AEnterprise** [comment]
these are tinkers construct things, please report the issues to them

**Comment by Raghalin** [comment]
GACK.  ya sorry.  I shouldn't try emailing anyone after staying up till 6am.
