### ISSUE TITLE
dup bug with auto workbench (might be a dup issue)

### ISSUE THREAD

**Issue by Trixz2018** [BuildCraft/BuildCraft#3944]
auto workbench, when crafting with buckets it returns double the buckets. EX: water bucket crafted into fresh water from pam's harvestcraft.
**Buildcraft** version: 7.99.13
**Forge** version: 14.23.1.2566
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer:  SP

Additional information:

**Comment by AEnterprise** [comment]
pam's harvestcraft fresh water is suposed to return the bucket (it does the same if you craft it in a regular crafting table)

**Comment by Trixz2018** [comment]
its not suppose to give you more back, like if i auto craft it with one bucket, i get 2 buckets back

**Comment by Trixz2018** [comment]
so there for there is bug with the auto workbench

**Comment by AEnterprise** [comment]
ah i misunderstood then

**Comment by AlexIIL** [comment]
Did the same thing happen in 7.99.12?

**Comment by Trixz2018** [comment]
i do not know, i didnt test 7.99.12

**Comment by Stokykyle** [comment]
This is also the case for when using ProjectE and the AutoWorkbench i have found when inserting the philosopher's stone into it duplicates the philosopher's stone and fills it's inventory with them and this is using Buildcraft version 7.99.13
