### ISSUE TITLE
More pipe events required

### ISSUE THREAD

**Issue by AlexIIL** [BuildCraft/BuildCraft#3945]
Specifically:

 - [ ] Invalidate: Called by (and only by) TileEntity.invalidate (by request of @multiplemonomials)
 - [ ] Validate: Called by (and only by) TileEntity.validate (in order to mirror Invalidate, although I'm not sure when this will be used)
 - [ ] Chunk Unload: Called by (and only by) TileEntity.onChunkUnload (by request of @multiplemonomials)

**Comment by multiplemonomials** [comment]
Any way I could also get PipeEvent.NeighborBlockChange, called by `Block.onNeighborBlockChange()`?

**Comment by multiplemonomials** [comment]
Actually wait never mind, I just noticed that `Pipe.markForUpdate()` is already called when redstone changes.
