### ISSUE TITLE
Auto-crafting tables 1.12.2 multiplayer bug

### ISSUE THREAD

**Issue by BiohazardShell** [BuildCraft/BuildCraft#3948]
**BuildCraft** version: 7.99.13
**Forge** version: 14.23.1.2555
Link to crash report or log:  no crash / no log output found useful
Singleplayer or multiplayer: multiplayer
Additional information: 

Will attempting to make an auto firework crafting machine I end up finding out that all the tables were linked. the first table was normaly design to craft the firework core and then the second adds the fade and the last one the rocket plus the duration. 
The bug appears to make the first crafting table craft the whole rocket .
however, it actualy was the rocket I was trying to get as a result.
So the crafting mechanism work but the final item comes out of the first autocrafting table.
Not the output expected.

(Sorry for the bad explaination , I'm better at responding to questions. So please ask me.)
P.S. if needed I can recreate the situation and record it on video.

mods running at the same time:

- Airsupport 0.3.0
- torohealth 1.12.2-11
- Currency 1.12.0 1.2.5
- Xaeros minimap 1.13.8
- defilelands 1.0.0
- RoguelikeDungeons 1.7.2
- worldedit 6.1.8 forge
- buildcraft 7.99.13
- joshuas christmas 1.12.2

**Comment by AEnterprise** [comment]
the autocrafting hs been reworked for 7.99.13, it seems some things got messed up in the process

**Comment by AlexIIL** [comment]
Can you add images of all autocrafting tables and your entire setup?

**Comment by AlexIIL** [comment]
Ok, it looks like fireworks are implemented as a *stateful* recipe - we need to call ````matches()```` before calling ````getCraftingResult()```` for some annoying reason :/
