### ISSUE TITLE
Gates require additional viewing of GUI to activate after initial viewing

### ISSUE THREAD

**Issue by Ghent** [BuildCraft/BuildCraft#3949]
**BuildCraft** version: 
7.99.13

**Forge** version: 
forge-1.12.2-14.23.1.2566-universal

Link to crash report or log: 
Singleplayer or multiplayer: 
Additional information: 
I haven't tested with all gates, but with the basic gate, once you place and configure it, you must open it again for redstone signals to activate as configured.

**Comment by AlexIIL** [comment]
I'm having trouble reproducing - is your setup similar to this:

![2017-12-28_20 19 12](https://user-images.githubusercontent.com/3751138/34422307-96fa27ce-ec0c-11e7-8cfb-0d4bc834032d.png)
![2017-12-28_20 19 18](https://user-images.githubusercontent.com/3751138/34422319-a25719f6-ec0c-11e7-8637-aab16573769c.png)
(Both of the gates are setup with Redstone -> wire or wire -> redstone)

**Comment by Ghent** [comment]
I cannot reliably reproduce this.  I will reopen as necessary.  Sorry about that!
