### ISSUE TITLE
Chisel blocks not working for facade

### ISSUE THREAD

**Issue by Azuxul** [BuildCraft/BuildCraft#3954]
**BuildCraft** version: 7.99.13
**Forge** version: 14.23.1.2565
Singleplayer or multiplayer: multiplayer
Additional information: 

Chisel version : MC1.12-0.1.1.24

Hi,

When i try to use facade make with chisel blocks, block is transparency on facade.

Screenshot:
![2018-01-01_01 33 22](https://user-images.githubusercontent.com/11092555/34464869-d9e820ac-ee93-11e7-9754-dbf2f5a0883d.png)

**Comment by AlexIIL** [comment]
Do the chisel blocks as facades look correct while held in-hand?

**Comment by Azuxul** [comment]
Yes, item rendering is correct, see the screenshot.
![2018-01-01_11 04 09](https://user-images.githubusercontent.com/11092555/34466915-9c44da24-eee3-11e7-85b8-c8ed5f8905bb.png)
