### ISSUE TITLE
BC facade errors in forge server console.

### ISSUE THREAD

**Issue by RikoDEV** [BuildCraft/BuildCraft#3957]
**BuildCraft** version: 7.99.13
**Forge** version: 14.23.1.2582
**Error log**: https://hastebin.com/raw/zecidotemo
**Mod list**: https://hastebin.com/raw/hunubisera
Singleplayer or multiplayer: multiplayer
Additional information: I receive errors in the console on my forge server

**Comment by Astharok** [comment]
I have a similar error. It is in server side.

Minecraft version: 1.12.2
BuildCraft version: 7.99.14
Forge version: 14.23.1.2583
Error log: https://hastebin.com/adasiyehuf.vbs

**Comment by AEnterprise** [comment]
do you have the latest forestry? this should have been fixed in that already

**Comment by Astharok** [comment]
Wow Thank you. did not noticed there was a new version in curseforge. I was downloading it from another site. Fixed!

**Comment by afdw** [comment]
Immersive Engineering was fixed a while ago, Extra Utilities also seems to work on latest versions:
![image](https://user-images.githubusercontent.com/7559560/36451625-b730fc00-16a2-11e8-9f9e-e1de391cc3bf.png)
