### ISSUE TITLE
Remove tablet leftovers in 1.12+

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildCraft#3959]
buildcraft.api.tablet, not sure if anything else. Since BuildCraft now has a guide book, these are unnecessary - the Tablet was meant to be a guide book of sorts.

**Comment by AlexIIL** [comment]
Thanks for pointing that out.

**Comment by asiekierka** [comment]
https://github.com/BuildCraft/BuildCraft/tree/8.0.x/buildcraft_resources/assets/buildcraftcore/tablet

https://github.com/BuildCraft/BuildCraft/blob/8.0.x/buildcraft_resources/assets/buildcraftcore/textures/gui/tablet.png

You missed a few.

**Comment by asiekierka** [comment]
Also, this only pertains to the tablet fonts, so can be removed as well: https://github.com/BuildCraft/BuildCraft/blob/8.0.x/buildcraft_resources/LICENSE.DEJAVU

**Comment by afdw** [comment]
And probably https://github.com/BuildCraft/BuildCraft/blob/8.0.x/misc/genfont.sh

**Comment by asiekierka** [comment]
Yes!
