### ISSUE TITLE
Minecraft 1.12.2 buildcraft texture bug

### ISSUE THREAD

**Issue by pablopatataxdxd** [BuildCraft/BuildCraft#3960]
**BuildCraft** version: 7.99.13
**Forge** 1.12.2-forge1.12.2-14.23.1.2555
Link to crash report or log: 
Singleplayer or multiplayer: single player
Additional information: I try to turn it off but i cant, https://gyazo.com/438b932be6bbd8c43dd7aa26995c164b

**Comment by AlexIIL** [comment]
You'll have to save and quit to title before changing the use swappable sprites option.

**Comment by pablopatataxdxd** [comment]
But i cant click on the option

**Comment by AlexIIL** [comment]
Even if you exit your world?

**Comment by AlexIIL** [comment]
if that doesn't work then try changing it manually in the config file at ````config/buildcraft/main.cfg````, then restart minecraft.

**Comment by pablopatataxdxd** [comment]
OK i switch of but it dont change nothing

**Comment by AlexIIL** [comment]
Oh, ok. Can you try removing optifine for a moment? I'd like to see if its optifine not quite working with BC that's causing it.

**Comment by pablopatataxdxd** [comment]
Ok i will try

**Comment by pablopatataxdxd** [comment]
Thx for all, it was optifine

**Comment by Adaptivity** [comment]
@AlexIIL this is most likely cause by outdated optifine. Using optifine C9 pre+Forge 2587+Buildcraft 7.99.14 (useSwappableSprites disabled) and anisotropic filtering enabled I have no problems with pipe textures nor other BC textures. So, this is just user error.

**Comment by AEnterprise** [comment]
should be fixed with the useSwappableSprites config option
