### ISSUE TITLE
Reduced framerate

### ISSUE THREAD

**Issue by MINECRAFTBC** [BuildCraft/BuildCraft#3961]
**BuildCraft** version: 7.99.13
**Forge** version: 14.23.1.2555
**Optifine** version: 1.12.2_hd_u_c7
Singleplayer or multiplayer: single

Hello, due to BC FPS fell by half! What could be the problem? Thx.

With BC:
https://i.imgur.com/qezoYcR.png
Without BC:
https://i.imgur.com/SAbt8wK.png

**Comment by AlexIIL** [comment]
Can you find the expensive element with buildcraft by using the debug pie (Shift+F3)? If its ````root.tick.textures.AtlasSpriteFluid```` then you're experiencing #3616.

**Comment by MINECRAFTBC** [comment]
I do not know what is this..

https://i.imgur.com/pB14LmE.png

**Comment by AlexIIL** [comment]
https://minecraft.gamepedia.com/Debug_screen#Profiler_graph - when the graph is open, press 1-9 to go into one of the areas, or 0 to exit. Can you navigate to "root.tick.textures.AtlasSpriteFluid" and take another screenshot?

(And no, it's nothing todo with tps)

**Comment by MINECRAFTBC** [comment]
I do not find "root.tick.textures.AtlasSpriteFluid"

https://i.imgur.com/z6SMkQj.png

**Comment by AlexIIL** [comment]
Can you turn off HD textures or increase your gui scale temporarily? It's very difficult to read the text at the moment. (Although I think if you press 2 directly from that screen then it will take you into "root.tick")

**Comment by MINECRAFTBC** [comment]
Here:
https://i.imgur.com/ncdIF8R.png

**Comment by MINECRAFTBC** [comment]
And how to increase your scale?

**Comment by AlexIIL** [comment]
Can you re-upload that image as a direct ping file rather than a jpeg file? The compression is making it impossible to read the text...

You can increase scale from the options menu > graphics settings

**Comment by MINECRAFTBC** [comment]
https://i.imgur.com/QdyWoFf.png

**Comment by AlexIIL** [comment]
Thanks! That confirms it, its definitionally fluid sprites being the issue rather than a new thing. Can you try using the [static fluid resource pack](https://www.mod-buildcraft.com/releases/Misc/packs/buildcraft_fluid_still.zip), as that should stop BC fluids from animating.

**Comment by MINECRAFTBC** [comment]
Many thanks!! Close.

**Comment by AlexIIL** [comment]
(Note that its still technically an issue, but this duplicates #3616 so I'll track its status there. At some point the static resource pack should become obsolete)
