### ISSUE TITLE
Pump Crashes Game!

### ISSUE THREAD

**Issue by DonkeyMonkey** [BuildCraft/BuildCraft#3962]
When i run the pump(ANY LIQUID), it will flow to the pipes and then crash!
It says on the crash log, Description: Rendering Entity in the World, java.lang.IllegalStateException: Already tesselating!
CrashLog --> https://pastebin.com/gEd56xgm

**BuildCraft** version:                          7.1.10 
**Forge** version:                                 10.13.4.1614
Singleplayer or multiplayer:                  SinglePlayer
Additional information:
2560 / 4000 RAM for Minecraft
Processor:   AMD Sempron(tm) 140 processor 2.70 ghz
RAM:           4GB
64BIT OS

**Comment by AEnterprise** [comment]
looks like an optifine issue, try removing that

also BC 7.1.10 is extremely outdated (by about 2 years), please update to the latest version (7.1.23) as that has many bugfixes and improvements

**Comment by DonkeyMonkey** [comment]
Turns out... it was an optifine issue, i dont want to remove optifine so i did is, i turn the chunk loading to default instead of smooth. And now its working fine. Thnx! :)

**Comment by DonkeyMonkey** [comment]
is there anyway i can fix this problem without messing with optifine or removing optifine?.. i've already updated buildcraft, thnx in advance

**Comment by AEnterprise** [comment]
not from our end, this is optifine messing with fundementals of how things render and that goes wrong sometimes with other mods

you can try contacting the optifine dev but i doubt 1.7.10 is still supported
