### ISSUE TITLE
Thumbnails are not appearing in JEI

### ISSUE THREAD

**Issue by SharinganHokage** [BuildCraft/BuildCraft#3963]
**BuildCraft** version: 7.99.13
**Forge** version: 1.12.2
Link to crash report or log: no crash it's just no images appears in JEI is it a bug from your mod? [image](https://s13.postimg.org/leuclk5dj/2018-01-06_15.20.43.png)
Singleplayer or multiplayer: singleplayer
Additional information: Also some machines don't have any crafting recipe, but for now can you fix the image bug?

**Comment by AEnterprise** [comment]
do you have optifine? if so try removing it, that will probably fix it

**Comment by SharinganHokage** [comment]
Yeah **Optifine** was the issue!
Thanks a lot you just saved me.

**Comment by LuigiHutch** [comment]
Some recipes in 7.99.x may seem missing and do not show in JEI, that is either because they are assembly table recipes or they are blocks which aren't ready to be used in survival.

**Comment by Adaptivity** [comment]
Same as #3960 
@SharinganHokage try updating optifine to preview version and disable useSwappableSprites in BC config.

**Comment by AEnterprise** [comment]
should be fixed with the useSwappableSprites config option
