### ISSUE TITLE
Obsidian Pipes are not working properly

### ISSUE THREAD

**Issue by bigbearjeff63** [BuildCraft/BuildCraft#3967]
Obsidian pipes should not connect to each other. Thus, their collecting ability goes away.

**BuildCraft** version: 7.99.13
**Forge** version: 1.12.2-14.23.1.2582
Multiplayer: on Private server

![obsidian pipe issue](https://user-images.githubusercontent.com/35222954/34696320-f54c6dca-f493-11e7-81c7-3297ee8da08a.jpg)

I hope this information helps.
Bigbearjeff

**Comment by AlexIIL** [comment]
Fixed in https://github.com/BuildCraft/BuildCraft/commit/f350cba650c032738bacaa69e6316e519b9808ea, will be released in 7.99.14 (or possibly 7.99.14-pre2)
