### ISSUE TITLE
Items Disabled

### ISSUE THREAD

**Issue by Atephious** [BuildCraft/BuildCraft#3968]
**BuildCraft** version:7.99.13 
**Forge** version: forge-1.12.2-14.23.1.2582-universal
Link to crash report or log: 
Singleplayer or multiplayer: Both
Additional information: 
The game does not crash. But when i try to make a wooden gear or anything from buildcraft the game tells me the items are disabled. If i click on the item say i put in sticks to make a gear a tooltip pops up when hovering saying  item is disabled. We tried to play it on single player to see if it was a config file mis match. but to no avail it still happens. when i look in the .cfg files the top one is empty. just says "#configuration file".*EDIT:  We have a lot of other mods installed too*
![2018-01-08_20 13 13](https://user-images.githubusercontent.com/13809824/34700332-884331c4-f4b0-11e7-9700-29dac0e845d5.png)

**Comment by FrancisDaPugtato** [comment]
You mean 7.99.13? xDD

**Comment by FrancisDaPugtato** [comment]
Which software system do you use? (Or if you know how, try to erase the config options

**Comment by Atephious** [comment]
which config options would i delete?

**Comment by Atephious** [comment]
i dont know if it matters but we also have buildcraft compat downloaded because we were told it worked to help buffer the problems with redstoneflux.

**Comment by AlexIIL** [comment]
I don't think either forge or Buildcraft show that message ("This item is disabled"), I'd assume that another mod is doing that. Can you upload a mod list to [gist](https://gist.github.com) from a [crash report](https://minecraft.gamepedia.com/Crash#Manual_initialization) (hold f3 + c for 10 seconds) or log file?

**Comment by AEnterprise** [comment]
closing for a lack of information, this also isn't a BuildCraft bug as we don't do things like this, some other mod in the pack is replacing the recipe to do this
