### ISSUE TITLE
Pipes won't work

### ISSUE THREAD

**Issue by PigLordRule** [BuildCraft/BuildCraft#3972]
**BuildCraft** version:latest
**Forge** version: don't know
Link to crash report or log: 
Singleplayer or multiplayer: singleplayer
Additional information:

**Comment by AEnterprise** [comment]
this issue basicaly tells us nothing, please provide all needed information : BC and forge versions, a description as to what's heapening (pictures might help as well if you have trouble describing it)

for versions if you realy don't know where to find them i sugest you go in your world (with no gui's or chat open) and hold F3+C for 10-15s, this force a debug crash, then go to your MC folder and upload the latest crashreport from your crashreports folder

**Comment by AEnterprise** [comment]
Closing for a lack of information, if you provide the requested information we can re-open and take another look at this.
