### ISSUE TITLE
Crash on 1.12

### ISSUE THREAD

**Issue by DashGit** [BuildCraft/BuildCraft#3973]
**BuildCraft** version: 7.99.13
**Forge** version: 14.23.1.2555
Link to crash report or log: https://pastebin.com/Nm5P0ifq
Singleplayer or multiplayer: Singleplayer (client only)

**Comment by afdw** [comment]
Try to update CodeChicken Lib.

**Comment by covers1624** [comment]
Yes, I pushed a CCL update weeks ago in order to fix this crash..

**Comment by DashGit** [comment]
Hmm. I tried updating it and now it's a different crash message. Also, of note is the fact that it works perfectly on the server now. 

https://pastebin.com/pyCXuZFb

**Comment by DashGit** [comment]
Thanks very much for the help. That fixed it.
