### ISSUE TITLE
Mekanism cables do not connect to the BuildCraft quarry

### ISSUE THREAD

**Issue by collinator24** [BuildCraft/BuildCraft#3975]
I have done this in the past, but in the 1.12.2 update, it seems to not be working, as the universal cable doesn't even connect to the quarry.

**Comment by collinator24** [comment]
Running Latest Mekanism, And Latest Buildcraft

**Comment by LuigiHutch** [comment]
Thanks for the report! This is actually a Mekanism issue, see here for details: https://github.com/aidancbrady/Mekanism/issues/4821

**Comment by collinator24** [comment]
Right, thank you. Hopefully, they fix this soon!
