### ISSUE TITLE
Lag?

### ISSUE THREAD

**Issue by Hadi10000** [BuildCraft/BuildCraft#3976]
My game became so lagy and it isn't from my computer because my spcs are good

**Comment by AEnterprise** [comment]
please provide all info requested in the template to start, is it only when you do some things with some blocks or all the time?
pc specs are also not everything, just giving MC to much or to little ram can also kill performance

**Comment by AEnterprise** [comment]
Closing for a lack of information, if you provide the requested information we can re-open and take another look at this.
