### ISSUE TITLE
The filtered buffer doesn't work nicely with the inventory level trigger

### ISSUE THREAD

**Issue by AlexIIL** [BuildCraft/BuildCraft#3977]
Specifically: setting a buffer for one slot and then leaving the rest blocked (or filtered but empty) will confuse the trigger into thinking that all of the blocked slots are actually free for usage.

**Comment by SandGrainOne** [comment]
When I initially made the Filtered Buffer I removed support for all or at least most of the normal inventory triggers. I think it has been back and forth at least once after that, but I haven't kept track lately.
