### ISSUE TITLE
oil in flat worlds spawns in at its normal depth even when the world is lower than its spawn depth

### ISSUE THREAD

**Issue by ColossalNuke** [BuildCraft/BuildCraft#3984]
oil in flat worlds spawns in at its normal depth even when the world is lower than its spawn depth

**Comment by LuigiHutch** [comment]
Thanks for the report, this I believe is actually a duplicate of https://github.com/BuildCraft/BuildCraft/issues/3837

**Comment by ColossalNuke** [comment]
I just looked at #3837, and it is in fact a duplicate
