### ISSUE TITLE
hide unregistered blocks from facades

### ISSUE THREAD

**Issue by AEnterprise** [BuildCraft/BuildCraft#3990]
BuildCraft version: 7.99.14-pre4
Forge version: N/A
Link to crash report or log: N/A
Singleplayer or multiplayer: multiplayer only
Additional information: 
When players join a server with content mods installed on the client that the server doesn't have forge unregisters those blocks. This results in null blocks for facade states

**Comment by AlexIIL** [comment]
Partially fixed: this still needs testing.
