### ISSUE TITLE
Buildcraft Facecade crashing server everytime we use the search bar in creative

### ISSUE THREAD

**Issue by DarkMatterXCIX** [BuildCraft/BuildCraft#3991]
BuildCraft version: 
Forge version: 
Link to crash report or log: 
Singleplayer or multiplayer: 
Additional information:

**Comment by AEnterprise** [comment]
missing all the required info from the template so i can only guess what's going on so here are some options that might cause this:

- you have outdated versions of codechickenlib/integrated dynamics, update those if present
- you are on a server and youc lient has content mods that are not on the server, remove those or add the mods to the server
- something else, use the search on the issues for other causes and fixes mentioned before
