### ISSUE TITLE
Crash when in creative mode

### ISSUE THREAD

**Issue by shdwdrake8** [BuildCraft/BuildCraft#3999]
BuildCraft version: 7.99.14
Forge version: 14.23.1.2600
Link to crash report or log: https://pastebin.com/wdGGjDC4
Singleplayer or multiplayer: Multiplayer
Additional information: Crash when going into creative mode and selecting the "search" button.

I removed the mod for now, I need to go live by Friday but I hope this is something that can be resolved so I can add it back to my server. Thanks for your hard work.

**Comment by AEnterprise** [comment]
can you try with 7.99.15-pre4? that has improved logging but i suspect this is a case of you having content mods on the client that are not installed on the server (#3990)

**Comment by shdwdrake8** [comment]
I'm sorry, I'm needing to launch my server like today and don't have the time to test it myself. If nobody else has the issue I can cross the bridge later when I try to get it live again. Wanted to give an opportunity to see if it was on your side and make you aware of it. Thanks for your consideration and great work on an awesome mod!

**Comment by AlexIIL** [comment]
It's been an issue before (for example the linked issue), however we'd like to see if the same fix that worked for that also fixes this.

Thanks for reporting though, hopefully when 7.99.15 actually releases you won't encounter this again :)

**Comment by AEnterprise** [comment]
any update on this? does the bug still heapen if the client and server have the exact same modlist (and versions)?

**Comment by AEnterprise** [comment]
closing as this is almost surely a duplicate and no more info was provided
