### ISSUE TITLE
client side crash on server when clicking on facade creative menu or clicking search bar

### ISSUE THREAD

**Issue by DarkMatterXCIX** [BuildCraft/BuildCraft#4007]
BuildCraft version: 7.99.14
Forge version: 14.23.1.2605
Link to crash report or log: https://pastebin.com/yG47rHY9
Singleplayer or multiplayer: Multiplayer
Additional information: this does not happen every time, but when it starts it doesn't stop on my server. One, it corrupts my world, Two, I have to uninstall build craft, and then play on a new world, then bring back in build craft and it works completely fine for a while, then comes back, also i don't have any facades on any pipes on the server or anything, its just the creative tab that will crash this is what MC says after crash on the launcher :The game crashed whilst updating screen events
Error: java.lang.IllegalStateException: Writing facade block state

Thanks much and if u could release a fix soon that'd be awesome! my friends love this mod and we hope to keep it, but our server is unplayable as of rn

**Comment by AEnterprise** [comment]
this looks like #3990 : please take a look at the mods installed on the client and server and make sure all content mods from the client are also added to the server

**Comment by DarkMatterXCIX** [comment]
Yes I have gone back and checked, randomly for NO reason it will take a random thing like say a planet called Neptune, take it's blocks, and go crazy, it is a buuodcraft bug for sure, no other mod is cause it even when I ran the mods alone it would do It with other MC blocks.. do u have a bug fix by a chance?

**Comment by DarkMatterXCIX** [comment]
I have talked to multiple developers showing them the crash log, they have all agreed it's just a bug for Build Craft, please can u look into this and release a patch? It's one of my favorite mods me and my friends thoroughly enjoy playing on my server

**Comment by AlexIIL** [comment]
Yes, this is (theoretically) fixed in dev. It's untested though, so it will take a little while for the fix to be out.

**Comment by DarkMatterXCIX** [comment]
Can u release a alpha patch so I can atleast implement it onto server? I know it's a lot to ask but the boys r waiting to get back on our survival world and work on getting our first quarry

**Comment by AEnterprise** [comment]
the patch is required clientside and this bug has NO impact on survival at all, is only a problem on the creative tabs

**Comment by AlexIIL** [comment]
Oh, looks like I fixed it a while ago. 7.99.15-pre4 should contain the fix then. Download it from the [main testing page](https://www.mod-buildcraft.com/pages/tests.html)

**Comment by AEnterprise** [comment]
pre4 doesn't contain it yet, that was released the 17, the fix was made on the 21st

**Comment by DarkMatterXCIX** [comment]
yes, i have the most previous release, but if you guys could get it on the testing page I could use it and tell you the outcome.

**Comment by AlexIIL** [comment]
Oh woops... thanks. In which case the next state ish testing build will probably be released Ina few days.

**Comment by DarkMatterXCIX** [comment]
okay awesome! thank for the reply guys! incredible mod keep it up, will check back in a few days!

**Comment by AEnterprise** [comment]
gona close this as this is a duplicate and we don't need 2 tickets for the same thing, please let us know in #3990 if the fix works or not once the pre-release is out
