### ISSUE TITLE
stirling engine and redstone engine

### ISSUE THREAD

**Issue by Grinroth** [BuildCraft/BuildCraft#4008]
BuildCraft version: 7.99.14
Forge version: 1.12.2-14.23.1.2607
Link to crash report or log: no crash report mad no log found for the issue
Singleplayer or multiplayer:  Single Player
Additional information: 
not sure if this has been reported yet but when i place lava bucket, coal, or saplings in the stirling engine nothing happens, and the redstone engine will not flip when you try to place it also you can not access it like i said not sure if this an old issue but i did not see it in the other posts any help with this.

**Comment by AEnterprise** [comment]
engines need a redstone signal to work, redstone engines have no interface as they don't need one
to rotate engines use a wrench
feel free to stop by on the discord (https://discord.gg/v4geqgA) for questions on how things work
