### ISSUE TITLE
Itemducts make items disapear.

### ISSUE THREAD

**Issue by Maliinky** [BuildCraft/BuildCraft#4013]
Bug : 
1.) itemduct/servo taking more items out of the chest then needed, 
2.) at times it takes no items out, even though the furnace is empty
3.) when it does take items out of the chest, then as they travel from the itemduct into the furnace, they are not placed into the furnace, but rather disapear. Sending a signal to the servo that more items are needed, and so it sends more items, but none of them are placed into the furnace, just disappear. 

To replicate : I have a minecraft vanila furnace set up, 1 furnace, 3 chests (2 input, coal and clay) 1 output (bricks). (all going in and out of regular minecraft chest) . Clay input on the top side, coal input on the back side, and brick output from bottom. I have tried to use the 1st tier servo, and the electrum servo and they both exhibit the same bug.

BuildCraft version: 7.99.14
Forge version:  1.12.2-14.23.1.2064
Link to crash report or log: 
Singleplayer or multiplayer:  multiplayer
Additional information:

**Comment by AEnterprise** [comment]
itemducts, servo's and all those things are not part of BuildCraft but rather the cofh thermal suite
