### ISSUE TITLE
Assembly Table provides incorrect recipes

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#4014]
BuildCraft version: 7.99.15-pre4
Forge version: 1.12.2-14.23.1.2590
Link to crash report or log: N/A
Singleplayer or multiplayer: Both

![2018-02-02_23 00 52](https://user-images.githubusercontent.com/9326429/35758686-2684ea56-086d-11e8-88af-388a87d9f8ab.png)

As shown in the image above, when inserting the materials to make a gold gate with the quartz modifier,  the Assembly Table displays both nether brick gates and iron gates with the quartz modifer instead of the correct gold gate

**Comment by AlexIIL** [comment]
...Why haven't I fixed this yet? This looks pretty major...
