### ISSUE TITLE
Oil is still spawning with it disabled in configs

### ISSUE THREAD

**Issue by Saereth** [BuildCraft/BuildCraft#4017]
BuildCraft version: 7.99.14
Forge version: 
Singleplayer or multiplayer: Both
Additional information: 14.23.26.11

Turning oil off in worldgen is still creating underground oil lakes with oil hot blocks

    # Should any oil sprouts or lakes generate, at all?
    B:enableOilGen=false

then creating a fresh world:
https://imgur.com/a/jSu8x

**Comment by Saereth** [comment]
update; completely disabling buildcraft worldgen 

    # Should BuildCraft generate anything in the world?
    B:enable=false

still results in those pools spawning
https://imgur.com/a/R4Jlo

**Comment by AlexIIL** [comment]
Can you retry with *just* buildcraft (no other mods)

**Comment by Saereth** [comment]
Does not occur with just BC so I started going through the modlist, looks like Pnuematicraft is causing this. Mystery solved.
