### ISSUE TITLE
Leadstone Fluxduct "Leadstone Energy Conduit"  Quarry

### ISSUE THREAD

**Issue by SalvadorScalia** [BuildCraft/BuildCraft#4021]
The Leadstone Fluxduct (Leadsotne Energy Conduit) ...

Los Leadstone Fluxduct no conectan a la quarry.

BuildCraft version: 7.99.14
Forge version: 14.23.2.2611
Link to crash report or log: none
Singleplayer or multiplayer: S/M
Additional information:

**Comment by AEnterprise** [comment]
this is intentional, BC is using RF instead of MJ again since 1.11+

also please do not open an issue and comment on 2 older ones that already explained this is intended behaviour

**Comment by SalvadorScalia** [comment]
@AEnterprise sorry, I did not want to confuse the subject anymore.
