### ISSUE TITLE
Wires are turning off on world load / not saving state on world save / whatever.

### ISSUE THREAD

**Issue by Dimanper** [BuildCraft/BuildCraft#4022]
Wires are turning off on world load / not saving state on world save / whatever.
In configurations like (if red_wire == 1 then red_wire = 1) in logic gates, wires turn off on world load, making memory cells, flip-flops, etc based on gates logic pretty much useless in many cases.

BuildCraft version: Works properly in 7.1.23 (1.7.10). Doesn't work (turn off on world load) in 7.99.8.2 (1.11.2), 7.99.15-pre6 (1.12.2) (tested on all three versions).
Singleplayer or multiplayer: Tested only in singleplayer.

**Comment by Dimanper** [comment]
I am sorry, but what is the point of reopening this issue, if this is already fixed in pre7? To close it once .15 will come out?

**Comment by afdw** [comment]
Yes, we currently only add the label and close issues when doing release.
