### ISSUE TITLE
cant open chests

### ISSUE THREAD

**Issue by leoad14** [BuildCraft/BuildCraft#4023]
BuildCraft version: 1.12.2
Link to crash report or log: 
Singleplayer or multiplayer: single
Additional information:

**Comment by jburkej1** [comment]
Is there room above the chest for it to open, it needs it least a 1/2 block.

**Comment by AEnterprise** [comment]
not an issue on the BC side

if you heapen to have optifine then update optifine as that has caused this for people in the past
