### ISSUE TITLE
[1.12.2]Biome Tests Don't Seem to Properly Work for Oilgen Exclusion

### ISSUE THREAD

**Issue by Vyraal1** [BuildCraft/BuildCraft#4025]
**BuildCraft version:** 7.99.14
**Forge version:** 2613
**Link to crash report or log:** https://gist.github.com/Vyraal1/ad9f841f10bf5af7d4d72a0fb1de50b6
**Singleplayer or multiplayer:** Both 
**Additional information:** 
Main.cfg = https://hastebin.com/kujicoyebe.bash
Modpack = https://minecraft.curseforge.com/projects/interaction

**Comment by Vyraal1** [comment]
Just came across the idea that this might actually be Pnematiccraft oil generation rather than Buildcraft's, I'll investigate tonight and see if that fixes the issue.

**Comment by AlexIIL** [comment]
Relevant log lines:
````
Unknown biome name detected in buildcraft config!
Unknown biomes: 
   - minecraft:
````

I think this means that forge can't read the config properly. I'm not sure why it would only read "minecraft:" though, rather than the complete biome...

**Comment by Vyraal1** [comment]
Verified that it was my mistake, PneumaticCraft was also generating underground oil lakes which I didn't catch on to at first since it will default to BC Oil. Everything else seems to work perfectly fine, as for the log error, I can't seem to reproduce it anymore either.
