### ISSUE TITLE
7.2.8 version for 1.7.10 minecraft version

### ISSUE THREAD

**Issue by gustavogmb** [BuildCraft/BuildCraft#4026]
I've downloaded the 7.2.8 verstion last year  at the beginning of 2017 for 1.7.10 minecraft version, but today I went to the website and for the 1.7.10 version jus there is the 7.1.23 version of the mod, what happen here?

**Comment by AlexIIL** [comment]
7.2.8 is for minecraft 1.8.9. I'm not sure how it could have worked in 1.7.10, but [7.1.23](https://www.mod-buildcraft.com/releases/BuildCraft/7.1.23/buildcraft-7.1.23.jar) should be the latest correct version.
