### ISSUE TITLE
Missing @sideonly(Side.CLIENT)

### ISSUE THREAD

**Issue by Dockter** [BuildCraft/BuildCraft#4028]
Build:  7.99.15-pre7
Date: 2/14/2018

Issue: https://github.com/BuildCraft/BuildCraft/blob/e32fee2e2e16b876aacdeb0a53e1aebe24acbaca/common/buildcraft/lib/BCLibEventDist.java#L187

Resolution:  You need to isolate this method from the server with a @SideOnly(Side.CLIENT).  This method got called on the server and then crashed when trying to get client class EntityPlayerSP.

Test:  I've created this patch and tested locally with success.

**Comment by AEnterprise** [comment]
yeah that's a easy to fix bug

since you have made and tested these changes localy would you mind making a quick PR? (unless alex/afdw gets to it before)
