### ISSUE TITLE
Empty string input?

### ISSUE THREAD

**Issue by ColonelJN** [BuildCraft/BuildCraft#4030]
BuildCraft version: 7.99.14
Forge version: 14.23.2.2611
Link to crash report or log: https://pastebin.com/q8uqK1Y8
Singleplayer or multiplayer: Single
Additional information: This is an odd one. The game was paused while I stepped away to help one of my kids, came back to an unresponsive window. Killed it, got this. Didn't see anything related in the issue tracker, might not have searched for the right thing though. Looks like it might be an interaction with CodeChickenLib, but not too sure on that. ( odd that this says during mod loading, as the crash happened well after initial load.)

**Comment by afdw** [comment]
Try to update CodeChickenLib.

**Comment by covers1624** [comment]
Yes, you are running ancient CCL, Later versions have fixed this issue.

**Comment by ColonelJN** [comment]
Makes sense. I don't have a very high update cycle. Thanks!
