### ISSUE TITLE
[1.12.2] Duplicate Files Detected by Forge?

### ISSUE THREAD

**Issue by MokahTGS** [BuildCraft/BuildCraft#4034]
BuildCraft version: 7.99.15
Forge version: 2611
Link to crash report or log: Screenshot: https://www.dropbox.com/s/bvyli3pyqzpj02s/buildcraft1.jpg?dl=0
Singleplayer or multiplayer: SP
Additional information: Looking in my mod folder there is only one copy of the buildcraft files.

**Comment by AEnterprise** [comment]
you do have a double instalation:
you have both the full jar file as all the seperate modules (that are all shipped together in the full jar download)

remove the seperate modules and MC will be able to start

**Comment by MokahTGS** [comment]
Ah...this is confusing.  Did I miss that instruction on the module pages?

**Comment by AlexIIL** [comment]
I don't think the BC website or curseforge actually explicitly says that ````buildcraft-7.99.15```` includes all of the modules (except for compat).
