### ISSUE TITLE
Error On Startup

### ISSUE THREAD

**Issue by BSKCorp** [BuildCraft/BuildCraft#4040]
BuildCraft version: 7.99.14
Forge version: 1.12.2-14.23.2.2616
Link to crash report or log: 
[fml-junk-earlystartup.log](https://github.com/BuildCraft/BuildCraft/files/1737991/fml-junk-earlystartup.log)

Singleplayer or multiplayer: Multi
Steps to reproduce: Load Server
Additional information: Start at line 1932. Also from skimming through Possibly something to do with IC2? First time running the mod for 1.12.2 Just sharing info to help development. Let me know if you need any other information.

**Comment by AEnterprise** [comment]
seems some IC2 blocks don't serialize and deserialize properly

shouldn't realy affect anything other then that those blocks won't be used for facades for sure

**Comment by AlexIIL** [comment]
From looking though it it would seem that IE also has this problem.

**Comment by AEnterprise** [comment]
the IE issue for booleans has been reported to them in the past and already fixed on their end

**Comment by Chocohead** [comment]
You have to use at least IC2 2.8.30 for state serialisation to be implemented.

**Comment by BSKCorp** [comment]
Thanks for the replies guys and the quick fix. Will let you know if anything else goes down.
