### ISSUE TITLE
Game Crashes when right clicked the Steam Engine

### ISSUE THREAD

**Issue by ImperfMage** [BuildCraft/BuildCraft#4041]
BuildCraft version: buildcraft-7.99.15
Forge version: Minecraft Version:1.12.2 (modded) forge-14.23.2.2615
Link to crash report or log: [Link to the crash log](https://gist.github.com/ImperfMage/d85ae539876d6f3301391f8f16cd2d4e)
Singleplayer or multiplayer: Single Player
Steps to reproduce: Right Click on the steam engine while it's connected to the quarry
Additional information: 
What happened was that I had finished setting up the quarry with a few steam engines and was about to put fuel inside then when i right clicked the steam engine the game crashed

**Comment by AlexIIL** [comment]
Update buildcraft compat to 7.99.14.

**Comment by AEnterprise** [comment]
assuming this is solved, if not feel free to comment with more info
