### ISSUE TITLE
Redstone  engines crash

### ISSUE THREAD

**Issue by wussler** [BuildCraft/BuildCraft#4042]
BuildCraft version: 7.99.15
Forge version: 14.23.1.2587
Link to crash report or log: https://pastebin.com/krNAAJFZ
Singleplayer or multiplayer: multiplayer
Steps to reproduce: After leaving on redstone engines for several days, chunkloaded the game crashes.
Additional information: Workaround is to remove said engines with the editor.

It has already happened twice with 7.99.14: https://pastebin.com/sByLqTk1

**Comment by AEnterprise** [comment]
i suspect moving world might be messing with this? somehow there is no advancementmanager attached to the world

**Comment by AEnterprise** [comment]
Unable to replicate, one of the other mods is definatly messing up the world
