### ISSUE TITLE
Wooden Fluid pipe not retaining face value when against two outputs

### ISSUE THREAD

**Issue by Tencao** [BuildCraft/BuildCraft#4043]
BuildCraft version: 7.99.16-pre1
Forge version: 14.23.2.2618
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Place a combustion engine, a wooden fluid pipe ontop, and a tank above that
Additional information: The wooden pipe will not remember it's facing value when saving and reloading a save, causing it to reset to the top output. A picture showcasing this can be found below.

![](https://cdn.discordapp.com/attachments/309218760814886922/415490936584405003/unknown.png)

**Comment by AlexIIL** [comment]
7.99.16-pre1 hasn't been released yet. Which commit was it built from?

Can you also retest this in 7.99.15: I've seen this bug before, and fixed it in a previous version.

**Comment by Tencao** [comment]
Tested on 7.99.15 and confirmed not present. As for the build, it's the one linked in discords #testing channel released yesterday, and was also present in my port which is running from the latest commits, I'm unsure when the bug showed up.

**Comment by Tencao** [comment]
Tested with https://github.com/BuildCraft/BuildCraft/commit/3cbf70c4010302ea3e772eb45b4554a7db252145 and confirmed fixed

**Comment by AlexIIL** [comment]
As this was fixed in dev before a release was made I'll just keep this closed.
