### ISSUE TITLE
Problem with Fluid Transport Pipe

### ISSUE THREAD

**Issue by NatsuDess** [BuildCraft/BuildCraft#4045]
Hi there,
I come to signal a bug when I use a tank an a wooden fluid transport pipe for give lava at one lava generator of other mod. the lava don't go at the machine

BuildCraft version: 7.99.8.1
Forge version: 13.20.1.2588 for 1.11.2
Link to crash report or log: 
Singleplayer or multiplayer: Multiplayer
Steps to reproduce: tank of Buildcraft and wooden tfluid transport pipe of bc transport and magmatic generator of extrautilities 2
Additional information:

**Comment by AEnterprise** [comment]
can you provide pictures of your setup? fluid pipes work fine so most likely something isn't hooked up right

**Comment by NatsuDess** [comment]
yes, at the begin, When I installed the setup, it worked, but after one moment, he dont
Picture follow message
![2018-02-22_22 21 46](https://user-images.githubusercontent.com/36741664/36564848-fec1fb14-181e-11e8-8030-932754b4ee13.png)
![2018-02-22_22 21 49](https://user-images.githubusercontent.com/36741664/36564849-fedd64a8-181e-11e8-86c3-0ddc43f53703.png)
![2018-02-22_22 21 52](https://user-images.githubusercontent.com/36741664/36564850-fef764b6-181e-11e8-95de-a8ff32235197.png)
![2018-02-22_22 22 01](https://user-images.githubusercontent.com/36741664/36564851-ff1066a0-181e-11e8-88bd-e33bced7603e.png)

**Comment by AEnterprise** [comment]
yeah i see your problem: wooden pipes do not extract on their own. They need to be powered, you can use a redstone engine next to it or put a pipe pulsar on the pipe itself (see guide book for recipe)
