### ISSUE TITLE
Facades interacting badly with The Erebus

### ISSUE THREAD

**Issue by Zer0Lyfe** [BuildCraft/BuildCraft#4047]
BuildCraft version: 
1.12.2 - v7.99.15v
Erebus Version 1.12.2 - v1.0.18
Forge version: 
14.23.2.2619
Link to crash report or log: 
https://gist.github.com/Zer0Lyfe/7b594218ae9f7711d3e5f9a8f56a33b2

Singleplayer or multiplayer: 
I tested it in singleplayer but most probably both 

Steps to reproduce: 
start-up a world with The Erebus and BuildCraft and crashes when world loads up.
Additional information:

**Comment by AlexIIL** [comment]
It looks like erebus blindly assumes that all stacks are valid:

**Comment by AlexIIL** [comment]
It looks like erebus blindly assumes that all stacks are valid:
https://github.com/ganymedes01/TheErebus/blob/mc1.12/src/main/java/erebus/items/block/ItemBlockEnum.java#L29 I'll open an issue on their tracker to see what they think of it.

**Comment by Zer0Lyfe** [comment]
ok. thank you Alex

**Comment by vadis365** [comment]
Thanks for the report :+1:

**Comment by vadis365** [comment]
The problem exists in the damage value of an item for a blocks' drops when broken here:
https://github.com/ganymedes01/TheErebus/blob/mc1.12/src/main/java/erebus/blocks/BlockRedGem.java#L65
The block is using that value (11) in magic number terms to set the meta of the dropped item here:
https://github.com/ganymedes01/TheErebus/blob/mc1.12/src/main/java/erebus/blocks/BlockRedGem.java#L77
This is pretty much the same way vanilla drops items like lapiz from it's ore blocks - although I'm using the block state's enum for the condition and not a specific block.

**Comment by vadis365** [comment]
can close this if you want - fixed in Erebus \o/

**Comment by Zer0Lyfe** [comment]
Thank you Vadis.
