### ISSUE TITLE
Wire management system for pipes

### ISSUE THREAD

**Issue by Ghent** [BuildCraft/BuildCraft#4048]
Hi,

A feature request I have would be to have a "wire management" system for pipes, so that more than 4 wire colors can be on one pipe.  Instead of laying the wire itself, you could lay the management item and then it could take many more wires.

Or, as an alternative, a "crystal" wire that could have colors turned on and off through a GUI.  Not sure if either of these ideas goes against the tenor of buildcraft's ideals, so I thought I'd throw it out there and see :)

Thanks again!

**Comment by jburkej1** [comment]
Crystal wire sounds like Fiber optics, where you can have 100's if not 1000's of channels on the same line at the same time, you would have to have a pair one out one return.

**Comment by AlexIIL** [comment]
Sorry for not closing this earlier, but this was implemented fully in 7.99.something :p
(Oh, and I think you've played with them before too, so I'm mostly just closing this for book-keeping.

Although I'm not really that sure what a "crystal" wire would be, but I don't think it's related to the issue title?
