### ISSUE TITLE
Crude Blast Furnace not working

### ISSUE THREAD

**Issue by Legendeternal** [BuildCraft/BuildCraft#4050]
BuildCraft version: 
Forge version: 
Link to crash report or log: 
Singleplayer or multiplayer: SP
Steps to reproduce: Put block of coal coke in crude blast furnace.  Put iron ingots in left slot.
Additional information: Tried breaking the furnace and rebuilding it a couple of times.  No help.

**Comment by Ghent** [comment]
What buildcraft version are you using?

**Comment by Legendeternal** [comment]
I had just updated the pack to 3.1.5. I rolled back to 3.1.4, and it started working again. 


Sent from Yahoo Mail for iPhone


On Friday, February 23, 2018, 11:01 PM, Ghent <notifications@github.com> wrote:


What buildcraft version are you using?

**Comment by AEnterprise** [comment]
the crude blast furnace is not part of BuildCraft, you are probably talking about the IE one, please report there (and fill in the template this time for them if you want help): https://github.com/BluSunrize/ImmersiveEngineering
