### ISSUE TITLE
BC and AE2 not working together

### ISSUE THREAD

**Issue by orbitkatsss** [BuildCraft/BuildCraft#4054]
So I was playing and just got some engines going to power my house and tried hooking the kinesis pipes to power my ME system through my  energy acceptor and the kinesis pipes wont connect to the energy acceptor. I have tried using all different types of pipes and nothing seems to work. is this how it is supposed to be? if so, how can I connect my kinesis pipes to an ME system/Energy Acceptor

BuildCraft version: 1.12.2

**Comment by LuigiHutch** [comment]
BuildCraft in 1.11+ has moved back to using its own MJ power system which is NOT compatible with RF or AE's internal power system. However, due to BuildCraft being in alpha no other mods support it, or should support it, as we are still making breaking changes to the API.

**Comment by orbitkatsss** [comment]
oh ok so is there a mod where i can transfer the mj into rf? or into another output type?

**Comment by AEnterprise** [comment]
there are a few power converter mods on curseforge you can use
