### ISSUE TITLE
Can't open chest

### ISSUE THREAD

**Issue by troopertoper** [BuildCraft/BuildCraft#4059]
BuildCraft version: 7.99.15
Forge version: 14.23.2.2624
Link to crash report or log: N/A (did not crash)
Singleplayer or multiplayer: singleplayer
Steps to reproduce: 
Additional information: Cannot open chests (trapped and normal) on any gamemode (creative, survival etc.). Buildcraft and Optifine are the only mods installed.

**Comment by AEnterprise** [comment]
known optifine issue, remove or update it
forge changed things and optifine is conflicting with it
