### ISSUE TITLE
[Crash] Buildcraft Transport and Bonsai Trees 

### ISSUE THREAD

**Issue by joselitosn** [BuildCraft/BuildCraft#4061]
Placing a Hopping Bonsai on top of any item pipe crashs the game immediately. The save can not be loaded again as the game keeps crashing.

Minecraft 1.12.2 - Singleplayer
BuildCraft version: 7.99.15
Bonsai Trees 1.0.3-b67
Forge version: 14.23.2.2624
[Crash report](https://pastebin.com/Umag87Yu) and [log](https://pastebin.com/kEPLwgZ1)

**Comment by AlexIIL** [comment]
Can you link to the hopping bonsai curse page or github issues page? I think one of it's implementations of `ICapabilityProvider.getCapability` is broken.

**Comment by AlexIIL** [comment]
Can I assume that https://github.com/thraaawn/BonsaiTrees is correct?

**Comment by joselitosn** [comment]
Maybe specifically this file...

https://github.com/thraaawn/BonsaiTrees/blob/master/src/main/java/org/dave/bonsaitrees/tile/TileBonsaiPot.java

**Comment by AlexIIL** [comment]
Yes, that would be it. Thanks.

**Comment by AlexIIL** [comment]
Hopefully they take a look at it soon :)

**Comment by joselitosn** [comment]
Hey, thank you! 🎉

Until the mod author releases a bugfix, I compiled a fixed version and was able load my save. ✌

But unfortunately i just found out I can't use vanilla hoppers https://github.com/BuildCraft/BuildCraft/issues/1737.

So for anyone that is using a block or machine which dumps items automatically, use a Chute instead. It can dump directly into a pipe.
