### ISSUE TITLE
in 1.8.9 the wrench could be used to reposition stairs.

### ISSUE THREAD

**Issue by jburkej1** [BuildCraft/BuildCraft#4068]
Any chance it could be added back in. Tried it in 1.11.2 as well and it didn't work there. 

thanks

BuildCraft version: 7.99.15
Forge version: 8.0.99.99
Link to crash report or log: 
Singleplayer or multiplayer: Single Player
Steps to reproduce: 
Additional information: tried it in MC 1.11.2 as well

**Comment by asiekierka** [comment]
Shouldn't falling back to Block.rotateBlock work?

**Comment by iTitus** [comment]
reopen until release?
