### ISSUE TITLE
Electrical engine is not working

### ISSUE THREAD

**Issue by cegar37** [BuildCraft/BuildCraft#4070]
**BuildCraft version:** 7.99.15
**Forge version:** 14.23.2.26.13
**Link to crash report or log:** 
**Singleplayer or multiplayer:** Both
**Steps to reproduce:** 
follow this diagram (like on this screenshot : https://www.noelshack.com/2018-10-4-1520467347-2018-03-08-01-01-03.png)

[MFSU (charged)]---[Electrical engine][Quarry]
............................................................|
...........................................[Redstone lever]

**Additional information:** 
The electrical engine is charging and send output (but is not moving)
(https://www.noelshack.com/2018-10-4-1520467360-2018-03-08-01-00-56.png)
but the quarry won't work.

I tried with the update for minecraft 1.7.10 and that work (I did exactly the same things).

Can you help me ?

**Comment by cegar37** [comment]
Thank you for your answer.

I'll try what you said.

But that's not the "Electrical engine" role ? (Or that was ?)
I was able to make it work (like on the screenshot) in 1.7.10, that have changed with the new updates (/Minecraft version) ?

**Comment by LuigiHutch** [comment]
BuildCraft in 1.11+ has moved back to using its own MJ power system which is NOT compatible with RF (which forestry and the electrical engine produced). However, due to BuildCraft being in alpha no other mods support it, or should support it, as we are still making breaking changes to the API.

**Comment by LuigiHutch** [comment]
Also a duplicate of https://github.com/BuildCraft/BuildCraft/issues/3760
