### ISSUE TITLE
Redstone Engine doesn't work wit Quarry. It works fine with Pump

### ISSUE THREAD

**Issue by TakumiMotor** [BuildCraft/BuildCraft#4072]
BuildCraft version: 1.12.2 (BuildCraft 7.99.15)
Forge version: 1.12.2-14.23.2.2611
Link to crash report or log: 
Singleplayer or multiplayer: both
Steps to reproduce: put redstone engine in the Quarry and use a lever make it works
Additional information: The Pump works fine with Redstone Engine

**Comment by gjgfuj** [comment]
I'm fairly sure that the redstone engine is not supposed to run quarries.

**Comment by TakumiMotor** [comment]
I think remember I have used it 1.7.5 (server) and it worked.

**Comment by AEnterprise** [comment]
this is intentional, only some low powered things can accept the free power from a redstone engine (like a pump or extraction pipe)

this has pretty much always been the case
