### ISSUE TITLE
Buggy fluid shards

### ISSUE THREAD

**Issue by Cyakat** [BuildCraft/BuildCraft#4075]
BuildCraft version: 7.99.15
Forge version: 1.12.2-14.23.2.2611
Link to crash report or log: 
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Place a fragile water shard into a Compression Dynamo (Thermal Expansion)
Additional information: When the water shard is placed in, Minecraft bugs out and you cant place or break anything and opening containers doesn't work either.

**Comment by AEnterprise** [comment]
sounds like an issue with TE, did you report this to them as well?

**Comment by Cyakat** [comment]
No I have not, but I will tell them. Thanks for the help!

**Comment by KingLemming** [comment]
This is not an issue with TE. If it were, literally everything would cause it. That doesn't happen - it's only your shards.

**Comment by AEnterprise** [comment]
@KingLemming that may be but we don't have this issue in our own containers or with other mods, so it's a specific interaction in this case. Do you have any idea on what might be getting stuck in an infinite loop here?

**Comment by KingLemming** [comment]
https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/block/dynamo/BlockDynamo.java#L231

Here's the method called when a block is activated. I am literally deferring to Forge's FluidHelper.

**Comment by AEnterprise** [comment]
i guess maybe this is some weird interaction due to the shards not being allowed to be filled

**Comment by KingLemming** [comment]
Should mention, I can't actually seem to make this happen. So it's entirely an unverified report.

I just know that there's nothing in my own code that would cause it. (And again, my own testing just showed it to work fine.)

**Comment by AlexIIL** [comment]
@KingLemming thanks for testing, that should help quell the blame game.

@Cyakat Can you reproduce this again? if so, can you upload your "fml-client-latest.log" [here](gist,github.com) and link back to it?

**Comment by AEnterprise** [comment]
just tried this myself and was also unable to make this heapen, seems a 3rd mod is indeed involved, nor do i see things in the code on eighter side that would explain this

**Comment by AEnterprise** [comment]
Closing for a lack of information, if you provide the requested information we can re-open and take another look at this.
