### ISSUE TITLE
Quarry mining sounds can be heard from a long distance

### ISSUE THREAD

**Issue by kouwei32** [BuildCraft/BuildCraft#4078]
BuildCraft version: 7.99.15 Alpha

Forge version: 14.23.2.2627

Link to crash report or log: N/A

Singleplayer or multiplayer: SP

Steps to reproduce: 1. Build a quarry. 2. Power it. 3. Start walking away from the quarry. 4. Listen.

Additional information: This bug is self-explanatory. It may also caused by me being on Venus (Galacticraft) at the time of the bug occurring.

**Comment by AEnterprise** [comment]
the quarry itself doesn't make sounds (except when you place it down then it makes an anvil sound), block breaking sounds are emitted by vanilla so if you hear them from to far away that will indeed be another mod messing with the volumes
