### ISSUE TITLE
Option to change the frequency of oil spouts

### ISSUE THREAD

**Issue by MarioSMB** [BuildCraft/BuildCraft#4080]
It would be nice if the frequency of these spouts could be adjusted (or even disabled without affecting pools).

**Comment by LuigiHutch** [comment]
As you havn't specified what version you are on:

- If you are on BC for MC 1.7.10, those configs are already there
- If you are on BC for 1.11.2+, those configs have not been ported yet. The configs that are missing are:

>
    Should BuildCraft generate water springs?
    B:generateWaterSprings=true

    How high should be the probability of an oil well generating?
    D:oilWellGenerationRate=1.0

PS: Please don't remove the issue template next time

**Comment by LordGolias** [comment]
I can have a take on this.

**Comment by AlexIIL** [comment]
@LordGolias please do :)

(This is fairly closely related to #3966, so if you want to do this you can probably do that one at the same time)
