### ISSUE TITLE
Mining Well can break oil & fuel

### ISSUE THREAD

**Issue by FrostQ** [BuildCraft/BuildCraft#4082]
BuildCraft version: 7.99.15
Forge version: 14.23.2.2611
Link to crash report or log:  None
Singleplayer or multiplayer:  Both
Steps to reproduce: Mining Well
Additional information: 

https://www.youtube.com/watch?v=PEBGvnFUlL8
![javaw 14-03-2018 17-04-20-745](https://user-images.githubusercontent.com/36822613/37415011-bb7d2d1a-27aa-11e8-9acf-057aa71f2e63.png)
-Can not break Water and Lava

**Comment by LordGolias** [comment]
I can reproduce this for oil at different temperatures, other fuels and at other temperatures and residue. It does not break Lava nor Water, so it seems to be an issue of the BC fluids only.
