### ISSUE TITLE
BuildCraft block loadig error

### ISSUE THREAD

**Issue by DeadMazay2000** [BuildCraft/BuildCraft#4087]
BuildCraft version: 
Forge version: 
Link to crash report or log: 
Singleplayer or multiplayer: 
Steps to reproduce: 
Additional information:

**Comment by AlexIIL** [comment]
Can I assume that opening this was a mistake? (and all details are in #4088 )

**Comment by AEnterprise** [comment]
closing as duplicate of 4088
