### ISSUE TITLE
BuildCraft block loading error

### ISSUE THREAD

**Issue by DeadMazay2000** [BuildCraft/BuildCraft#4088]
BuildCraft version: 
Forge version: 
Link to crash report or log: 
Singleplayer or multiplayer: 
Steps to reproduce: 
Additional information:

**Comment by DeadMazay2000** [comment]
When i put buildcraft mod in my mods folder, and launch minecraft, some game blocks and items not working. For example: iron and some other blocks is black (not all). Some buildcraft tubes and gates are invisible.

**Comment by AlexIIL** [comment]
Can you fill in the details above? (Use the pencil icon to change it)

Also, are you using optifine?

**Comment by DeadMazay2000** [comment]
Yes i am.

**Comment by AlexIIL** [comment]
What version of minecraft and buildcraft are you using?

Also, can you check to make sure you are using the latest versions of buildcraft for your minecraft version ( buildcraft 7.1.23 for minecraft 1.7.10, 7.99.15 for minecraft 1.12.2), and the latest version of optifine?

**Comment by DeadMazay2000** [comment]
Yes, the latest version of optifine. I will check the version of buildcraft.

**Comment by DeadMazay2000** [comment]
7.99.15 same thing.

**Comment by AlexIIL** [comment]
Ok, can you try changing the buildcraft config option `useSwappableSprites` to `false`? (You can either change this in the config file `config\buildcraft\main.cfg`, or in game by going to the main menu, then `mods > buildcraft > config > Display > useSwappableSprites`

**Comment by DeadMazay2000** [comment]
Version of minecraft 1.12.2

**Comment by DeadMazay2000** [comment]
I am using tlauncher, can it affect the error?

**Comment by AlexIIL** [comment]
I don't think the launcher will affect the error. However this sort of issue has been reported before, and changing [useSwappableSprites](https://github.com/BuildCraft/BuildCraft/issues/4088#issuecomment-374024991) to false has fixed it before.

**Comment by DeadMazay2000** [comment]
Thanks.

**Comment by DeadMazay2000** [comment]
Now mod is working.

**Comment by DeadMazay2000** [comment]
Do you have your own site with this mod?

**Comment by AlexIIL** [comment]
Would you mean the buildcraft site? (https://mod-buildcraft.com)
