### ISSUE TITLE
version

### ISSUE THREAD

**Issue by matejmraz1** [BuildCraft/BuildCraft#4090]
there arent any versions of minecraft 1.12.1!!! i must have it!

**Comment by covers1624** [comment]
What? Why on earth are you using 1.12.1? And requests like this don't go down well with authors, mods will be released when they are for the versions they are.

**Comment by AEnterprise** [comment]
we are not gona be backporting to 1.12.1, all mods for 1.12.1 have an update for 1.12.2 already and pretty much all mods for 1.12.1 will just work

**Comment by matejmraz1** [comment]
ok i'v have it


2018-03-19 9:10 GMT+01:00 AEnterprise <notifications@github.com>:
