### ISSUE TITLE
Filler don't works

### ISSUE THREAD

**Issue by PenguinMaster** [BuildCraft/BuildCraft#4091]
BuildCraft version: 7.99.14
Forge version: 14.23.2.2611 (recommended)
Link to crash report or log: N/A
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Right click on a filler
Additional information: The interface don't want to open, even with a crouch click

**Comment by AEnterprise** [comment]
please update to 7.99.15, you might need a compat test build from discord, we had issues with this before that should be fixed

**Comment by afdw** [comment]
GUI of filler will not open if it hasn't properly set up volume box or marker box.
