### ISSUE TITLE
Advancement warning for goggles

### ISSUE THREAD

**Issue by MarioSMB** [BuildCraft/BuildCraft#4093]
BuildCraft version: 7.99.15 
Forge version: 1.12.2-14.23.2.2629 
Link to crash report or log: https://pastebin.com/vWsk66h3 
Singleplayer or multiplayer: Tested on a dedicated server, probably affects both sides 
Steps to reproduce: Occurs on server launch 
Additional information: This warning appears multiple times in the log

**Comment by AEnterprise** [comment]
thanks for the report but this issue has been reported already: #3865
