### ISSUE TITLE
Everything disappeared!!!!!!!

### ISSUE THREAD

**Issue by Xamponin** [BuildCraft/BuildCraft#4097]
BuildCraft version: 7.99.15
Forge version: 1.12.2
Link to crash report or log: 
Singleplayer or multiplayer: MULTIPLAYER(private server)
Steps to reproduce: 
Additional information: 
We entered the world and everything we had placed disappeared leaving invisible blocks and floating levers, but everything about the chests such as pipes, engines and etc remained. I hope it is solved and I understand that it is an alpha, but it is a world in survival and we have to do everything less badly that we do not reach the laser and others.
THANKS.

**Comment by AEnterprise** [comment]
can you provide a modlist and log? also if you have any render mods like optifine please try without those, they are known to cause issues like this

**Comment by AlexIIL** [comment]
Do you have any backups? Did you update/add/remove any mods before and after this stopped working? Also, which blocks vanished? It seems odd that pipes and engines would stay (modded blocks)

**Comment by jburkej1** [comment]
I had a similar issue where chests were invisible. I restarted my computer and everything was back. when I restarted Java told me there was an update as well.

**Comment by AEnterprise** [comment]
Closing for a lack of information, if you provide the requested information we can re-open and take another look at this.
