### ISSUE TITLE
1.7.10 crash

### ISSUE THREAD

**Issue by ecolortest** [BuildCraft/BuildCraft#4099]
BuildCraft version: 7.1.23
Forge version: 0.13.4.1614
Link to crash report or log: 
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: https://pastebin.com/7eQS74HR
Additional information:  Crash in stable

**Comment by AEnterprise** [comment]
it seems somehow the jar is containing the 1.12 api (ITooltipFlag did not exist back then), checking files

**Comment by AEnterprise** [comment]
files all look fine, where did download the file from? it seems to not have been compiled correctly

can you re-download from the site (https://www.mod-buildcraft.com/pages/download.html) and try again?

**Comment by ecolortest** [comment]
i download from this official site
