### ISSUE TITLE
Trying to delete SSP world it does't delete

### ISSUE THREAD

**Issue by Aynjul** [BuildCraft/BuildCraft#4101]
BuildCraft version: 7.99.15
Forge version: 14.23.2.2634
Singleplayer
Steps to reproduce: I did it just by trying to delete my world

**Comment by AEnterprise** [comment]
very unlikely to be a BC error as we don't modify anything related to that, please provide a log

**Comment by Aynjul** [comment]
After totally reloading I was able to delete it. There was no log.

**Comment by AEnterprise** [comment]
gona close this then, if it heapens again please check the log to see what heapened
