### ISSUE TITLE
1.7.10 Crash

### ISSUE THREAD

**Issue by ecolortest** [BuildCraft/BuildCraft#4103]
BuildCraft version: 7.1.23
Forge version: 10.13.4.1558
Link to crash report or log: https://pastebin.com/hjx0dfk5
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: 
Additional information: I has re download the mod but crash with different crash reason

**Comment by AEnterprise** [comment]
your config file has values that are not allowed, miningMultiplier is not allowed to be 0 or less, please set it to a higher value or remove the config file so a new default one can be generated

also does this mean #4099 is solved and can be closed?

**Comment by ecolortest** [comment]
ok

**Comment by ecolortest** [comment]
also how to set that i want change that

**Comment by AEnterprise** [comment]
you can change the value in the config file with a text editor, the file you are looking for is `main.cfg` and is in the buildcraft folder of the config folder

**Comment by ecolortest** [comment]
i cant find miningmultipler

**Comment by ecolortest** [comment]
at the main.cfg

**Comment by AEnterprise** [comment]
it's in there, you can also just remove the file so it generates a fresh one

**Comment by ecolortest** [comment]
ok
