### ISSUE TITLE
Shift Rightclicking sticks on the ground borks things

### ISSUE THREAD

**Issue by DotOfNotGot** [BuildCraft/BuildCraft#4104]
BuildCraft version: 7.99.15
Forge version:  forge-14.23.2.2635
Link to crash report or log: It didn't crash
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Shiftrightclick a stick on the ground with an empty hand
Additional information: When i shiftrighclicked a stick on the ground my hand vanished from the first person view and i couldn't change to hold something else or get my inventory up. When i went into thirdperson view i had a bunch of iceblocks on me. I couldn't see the stick in my hotbar but it was there. If this happens to someone just rightclick the ground and it gets placed.

**Comment by AEnterprise** [comment]
please provide a log from when this heapens (latest.log from the logs folder)

also can you reprode this with just BC and no other mods? as i highly doubt BC is causing this

**Comment by AEnterprise** [comment]
this does not sound like a BC issues, if is when playing sevtech please report to the pack author instead: https://github.com/Darkosto/SevTech-Ages/issues
