### ISSUE TITLE
Destabilized Clathrate vs quarry MC 1.12.2

### ISSUE THREAD

**Issue by jburkej1** [BuildCraft/BuildCraft#4105]
When the quarry encounters a Destabilized Clatherate block it will break it and and the block acts like a water block and will fill the available empty blocks, if broken with a pick axe the released liquid while quickly drain away leaving the ore pieces. 
compat 7,99.14, cofh core 4.3.1.05, cofh world 1.1.1.12
![2018-03-28_22 04 15](https://user-images.githubusercontent.com/35736037/38066527-5c1d64fc-32d6-11e8-8696-8bc45a61fe2a.png)
![2018-03-28_22 04 50](https://user-images.githubusercontent.com/35736037/38066542-6cee5e9e-32d6-11e8-98d9-662a85afc268.png)
![2018-03-28_22 04 50_2](https://user-images.githubusercontent.com/35736037/38066543-6e0fc024-32d6-11e8-80f1-94b996a8c8a3.png)

BuildCraft version: 7.99.15
Forge version: 8.0.99.99
Link to crash report or log: 
Singleplayer or multiplayer: 
Steps to reproduce: 
Additional information:

**Comment by AEnterprise** [comment]
did you also report this to the COFH team? does this also heapen with any other automated blockbreakers?

the BC quarry should be breaking blocks the same ways as players do

**Comment by covers1624** [comment]
To clarify how it spawns, on world gen, it will generate a full block here and there inside the vein, when a block is broken it will spawn a partial block of fluid and it will drain away because its obviously not a full block. I think this is just user error not understanding how it is generated in world. @KingLemming can probably fill in more / correct me.

**Comment by jburkej1** [comment]
I haven't reported it to cofh yet but plan to. I wanted to get some more screen shots and see if I can do a screen capture video of it. What I am seeing is two behaviors one, a redstone block is broken by the quarry and red liquid comes out and spreads and stays and continues to spread until the source block is filled or picked up with a bucket. the other is I break a redstone ore block with a pick, red liquid comes out and quickly drains away leaving the ore pieces. it's no big deal and to be honest the only reason I have the mod is because it was one of the recommended mods to be able to use the BC tank mod.

**Comment by AEnterprise** [comment]
any update on this?

**Comment by KingLemming** [comment]
Just to clarify, this does not happen with any other automated block breaker. This is a problem with the quarry.

**Comment by AEnterprise** [comment]
it should be working just like any other automated block breaker though, as far as i can see it calls the exact same functions

**Comment by jburkej1** [comment]
I have been watching and it does seem like I was wrong, the block isn't being broken by the quarry, the block was already a full block of liquid, the quarry just exposed it. It does stay and spread just like water or lava. The quarry will ignore any blocks under the red liquid. One interesting thing is if there is water above the level of the red liquid you can't see the red liquid unless you walk or swim through it. It looks pink and can be picked up with a bucket if you can narrow down the source block. One note I installed the full Thermal dynamics mod and it doesn't seem to be happening as often as when I only had those pieces needed for the BC tank mod. I haven't yet posted it on their site yet.

**Comment by KingLemming** [comment]
^ Okay, this sounds reasonable. I'll admit that I didn't load up a Quarry and check, I loaded up some other automated block breakers to see if this happened.

I took the report at face value, probably should not have. Apologies.

**Comment by AEnterprise** [comment]
closing this then as there is nothing to be fixed
