### ISSUE TITLE
Unable to craft Salted Hide 

### ISSUE THREAD

**Issue by Moronicoscar** [BuildCraft/BuildCraft#4107]
Whenever I put the necessary items in the working stump to craft the salted hide and use the crafting rock against the working stump the item does not combine together. Even though I properly placed the necessary items to make the salted hide along with the items in the proper order on the working stump. 

Might I add I was able to successfully craft the salted hide numerous times yesterday. However today for some reason I was unable to craft it whatsoever. Which is rather strange due to the fact that I was able to craft it yesterday without any further issues.

BuildCraft version: 7.99.15
Forge version: 14.23.2.2635 
Link to crash report or log: N/A 
Singleplayer or multiplayer: Singleplayer
Steps to reproduce:  N/A
Additional information: N/A

**Comment by AEnterprise** [comment]
none of these items are related to BuildCraft in any way, please report this to the mod that adds those items
