### ISSUE TITLE
BuildCraft doesn't connect with Thermal Expansion

### ISSUE THREAD

**Issue by K4ST0** [BuildCraft/BuildCraft#4108]
BuildCraft version: 7.99.15
Forge version: 8.00.99.99
Singleplayer or multiplayer: single 
Thermal Expansion version: 5.3.10.15
Thermal Dynamics version: 2.3.10.4
![2018-04-01_12 43 04](https://user-images.githubusercontent.com/37975223/38171877-a09ba28e-35aa-11e8-912a-efa885cb869e.png)
![2018-04-01_12 43 10](https://user-images.githubusercontent.com/37975223/38171878-a0b64972-35aa-11e8-925f-745011f230a5.png)

Pipes from TE doesn't connect with machines from BC 
Whats wrong?

**Comment by AEnterprise** [comment]
BuildCraft is designed to provide a challenge to players, of which power generation is no exception. RF mods generally remove said challenge, so we brought back MJ in order to encourage players to generate power in more interesting ways.

**Comment by Muqluk** [comment]
Well, that just means I guess I uninstall it and/or fork and build it in myself then.

The challenge the vast majority of players want is 'not' related to 'power' - we start using mods to eliminate the more annoying parts of the game, not to add more annoying tedious mediocrity.

**Comment by AEnterprise** [comment]
the goal of this change was not to make things more tedious but more interesting and fun (also keep in mind mechanics will change)

if you realy wana use RF for hooking everything up to a single OP generator you can always use conversion mod

**Comment by 9551-q** [comment]
hello i would love if there would be version that would support it so it would work i would be very happy for that and i think i would be the only one
