### ISSUE TITLE
When I add buildcraft to my mods, minecraft crashes on launch

### ISSUE THREAD

**Issue by DarkArachnid** [BuildCraft/BuildCraft#4112]
I get this error message when trying to launch after installing buildcraft:
The game crashed whilst generating mipmaps for frame
Error: java.lang.ArrayIndexOutOfBoundsException: 5
Other Mods I Have:
codechickenlib
enderstorage
ic2
invtweaks
ironchest
jei
mantle
optifine
tconstruct
treechopper
xaeros_minimap
Is this a mod conflict or something else?
if so can anyone help with it?
(im using minecraft 1.12.2)

**Comment by AlexIIL** [comment]
Can you upload the full crash report to https://gist.github.com and post a link back here?

**Comment by DarkArachnid** [comment]
when i click "view crash report" nothing shows up.. can i find it manually in the minecraft directory?

**Comment by DarkArachnid** [comment]
ok i think i found the crash report https://gist.github.com/DarkArachnid/60d543f98d4666f04b45f7b1cc61c791

**Comment by AEnterprise** [comment]
looks like another instance of optifine messing up the rendering, not sure if this is something we can/want to try and guard against on our side (if that's even possible)

**Comment by DarkArachnid** [comment]
Turns out turning mipmap levels down to 0 lets me use both optifine and buildcraft
