### ISSUE TITLE
Paxel Mining Issues

### ISSUE THREAD

**Issue by CrimWasHere** [BuildCraft/BuildCraft#4120]
BuildCraft version: 1.12.2
Forge version: 14.23.2.2651
Link to crash report or log: None
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Paxel is unable to mine marble (breaks it) even though it says it is a diamond level pick. When used on sandstone, has no problem mining full blocks and slabs but has issues with stairs and walls.
Additional information: First noticed after installing and uninstalling resource pack: Soartex Fanver - Modded.

**Comment by AEnterprise** [comment]
BC doesn't add any paxel or marble, please report this to the mod that adds said paxel
