### ISSUE TITLE
Age 0 - Pressing your luck (Horse Press) Quest progression not updating

### ISSUE THREAD

**Issue by MetaBender** [BuildCraft/BuildCraft#4121]
BuildCraft version: 7.99.15
Forge version: 14.23.2.2651
Link to crash report or log: None
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Age 0 - Pressing Your Luck {Horse Press} Quest progression wont update
Additional information: I created the "Horse Press" item twice but the quest wont update.

**Comment by AEnterprise** [comment]
this has nothing to do with BuildCraft at all, please report this to the modpack author
