### ISSUE TITLE
Iron Pipes do not function

### ISSUE THREAD

**Issue by polski-g** [BuildCraft/BuildCraft#4124]
BuildCraft version: 
**NOT using full version**
buildcraft-compat-7.99.14
buildcraft-core-7.99.15
buildcraft-transport-7.99.15

Forge version: 14.23.2.2654
Link to crash report or log: n/a
Singleplayer or multiplayer: Single
Steps to reproduce: [https://i.imgur.com/e0vOPLI.png](image)
Additional information: 

Click iron pipe with wrench does nothing. All 3 junction points remain solid and items enter the iron pipe, then are returned to the source.

**Comment by polski-g** [comment]
Nevermind, at some point BC was changed to require clicking on the target destination.

**Comment by AlexIIL** [comment]
Actually clicking on the centre of the pipe should change the direction, but it looks like this is bugged so that clicking the centre of an iron pipe only changes the direction if it is already facing a direction.
