### ISSUE TITLE
[MMD] Textures Missing

### ISSUE THREAD

**Issue by samip5** [BuildCraft/BuildCraft#4126]
Related information can be found on the other issue.

Related: MinecraftModDevelopment/New-MMD-Public-Pack#54

**Comment by AlexIIL** [comment]
1. Update to 7.99.16, some of the texture issues might have been fixed
2. The rest of the texture issues will likely be addressed later. For some reason we don't have an existing issue for this.

**Comment by samip5** [comment]
Alright, but now you do have an issue for it. :)

**Comment by LordGolias** [comment]
@samip5, would it be possible for you to identify exactly which textures are missing? It would help anyone in adding them.

**Comment by samip5** [comment]
@LordGolias, the missing textures are/were:

- textures/filler/parameters/face_north.png
- textures/filler/parameters/face_west.png
- textures/filler/parameters/face_east.png
- textures/filler/parameters/face_south.png
- textures/filler/parameters/face_up.png
- textures/filler/parameters/face_down.png

P.S These seem to be fixed in build 7.99.16.
