### ISSUE TITLE
TileFilteredImporter Crashes

### ISSUE THREAD

**Issue by PulzHF** [BuildCraft/BuildCraft#4131]
BuildCraft version: 7.1.23 (1.7.10)
Forge version: 1614

Link to crash report or log: https://pastebin.com/haggVHDE (Server)
Singleplayer crash log: https://pastebin.com/yrjsNWnS

Singleplayer or multiplayer: Multiplayer- I imagine this happens on Singleplayer too

Steps to reproduce: Not sure, but this has happened many times over the last few months

Additional information: 
I used to be able to use NBTExplorer to remove the tile entities in the affected chunk, but now, NBT is no longer able to read the region files associated with these crashes. Forcing me to delete the region file.

This is for my Modpack "[The New Tekkit Classic](https://www.technicpack.net/modpack/tc-redux.786294)"

**Comment by AlexIIL** [comment]
I *think* this is a bug in projectred, but someone would need to look into this properly.

**Comment by AEnterprise** [comment]
looks like a project red inventory is claiming it has more slots then it actually has

**Comment by PulzHF** [comment]
As an update, I can now reproduce the error.

This seems to be a ProjectRed issue, as with the Filtered Importer, if any blocks are sent via piping to the sides of the Importer (the sides that aren't for the input/output) it will crash the client. On a server, this also produces a crash.
I did not that if the piping is set up to directly enter the incorrect side, the block will not be sent. But this can be changed if you fix the piping (to make the block move into the pipe) and then connect pipes to the sides of the F.Importer, so that the item travels to the side- causing the crash.

**Comment by covers1624** [comment]
This is PR, but as 1.7 isn't supported, it won't be backported.

**Comment by AEnterprise** [comment]
since this is a project red issue we cannot fix this from this end, sorry. we can only go on what info the TE exposes and nothing we can do if that is incorrect
