### ISSUE TITLE
gates not recognizing gaseous fluid levels

### ISSUE THREAD

**Issue by jburkej1** [BuildCraft/BuildCraft#4133]
I am trying to use gates to turn on a wire when the gaseous fuel in a tank reaches 25%. Regardless of the trigger I use the gate powers the wire unless the tank is full. My guess is I am not using the gate correctly or not using the right trigger. If this is a known issue I apologize for re-posting it.  BC .15 had the same behavior. 

MC 1.12.2, forge 14.23.1.2599, BC 7.99.16
BuildCraft version: 7.99.16
Forge version: 14.23.1.2599
Link to crash report or log: 
**Singleplayer** or multiplayer: 
![2018-04-19_20 06 30](https://user-images.githubusercontent.com/35736037/39024251-ab8bf420-440d-11e8-8048-9574b0bda4f6.png)
![2018-04-19_20 06 55](https://user-images.githubusercontent.com/35736037/39024253-ad19f364-440d-11e8-9220-f4fad12bef49.png)
![2018-04-19_20 07 06](https://user-images.githubusercontent.com/35736037/39024256-ae43a60e-440d-11e8-9df8-269692490d69.png)

Steps to reproduce: 
Additional information:

**Comment by AlexIIL** [comment]
I think this might be due to the fluid trigger only reading from a single tank block rather than the whole stack. Can you try with just a single tank block? (Also, can you try with a gate with at least one trigger parameter and add a fluid filter to the first parameter slot?)

Note that neither case are grounds to disregard this issue

**Comment by jburkej1** [comment]
it seams to work ok with non gaseous. I will try it with a single block and also a standard BC tank and not the diamond.

**Comment by jburkej1** [comment]
Does seem to be related to multiblock tanks. when I tested a basic gate and an Iron And gate with and without the hot fuel parameter it worked fine. when I add the 2nd block it powered the wire regardless of what less than full condition I set. I am going to confirm that gates work with the non gaseous fluids tomorrow. 
thank you.

**Comment by jburkej1** [comment]
it seems that gates work as I guess they are supposed to with non gaseous liquids in multi block tanks. I hope that helps figure out whats going on with the gates.
