### ISSUE TITLE
dendrites of oil wells appear on top of trees

### ISSUE THREAD

**Issue by LordGolias** [BuildCraft/BuildCraft#4134]
BuildCraft version: 7.99.17
Forge version: 8.0.99.99
Link to crash report or log: 
Singleplayer or multiplayer: both
Steps to reproduce: find a oil well close to a tree
Additional information: 

Image with example:

![2018-04-20_05 42 40](https://user-images.githubusercontent.com/16410441/39029792-f565102c-445d-11e8-81d2-aecd362e4b03.png)

I think that the oil blocks of the dendrites should appear on the floor, as dendrites naturally form as a consequence of pressure from too much fluid on the same location (the center).

**Comment by QuantumStatement** [comment]
Duplicate of #4002

**Comment by AlexIIL** [comment]
...right.
