### ISSUE TITLE
Unmergeable item

### ISSUE THREAD

**Issue by RiftomeR** [BuildCraft/BuildCraft#4137]
Please add a way to make TravellingItem unmergeable. Sometimes it's really important.

**Comment by LuigiHutch** [comment]
Thanks for removing the issue template, thats really descriptive and helpful!

Got any actual usecases where that would actually be useful?

**Comment by AlexIIL** [comment]
Merge mechanics can probably be tweaked - is there a specific use-case where this makes a difference? (Perhaps splitting later, as normal pipes don't auto-split already merged stacks...)

**Comment by RiftomeR** [comment]
It will be very useful in [this project](https://github.com/RiftomeR/itemtraffic).

**Comment by AEnterprise** [comment]
mind giving some more context and exact use cases?

**Comment by AlexIIL** [comment]
if you're referring to https://github.com/RiftomeR/itemtraffic/blob/master/src/main/java/riftomer/itemtraffic/behaviours/PipeBehaviourBasic.java#L135-L164 then you probably need to use both `PipeEventItem.Split` and `PipeEventItem.FindDest` to manually split up the stack into sub-stacks, and then find a destination for every sub-stack.

**Comment by RiftomeR** [comment]
Yes, i will do it. Thank you.
