### ISSUE TITLE
Machines don't accept RF anymore

### ISSUE THREAD

**Issue by SharperC** [BuildCraft/BuildCraft#4146]
BuildCraft version: 7.99.16
Forge version: 14.23.2.2627
Link to crash report or log: N/A (there is nothing relvant in it)
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: N/A
Additional information: All machines don't accept RF anymore, i'm not sure if this is a bug or ment to be because the old versions used to accept RF.

**Comment by AEnterprise** [comment]
this is indeed an intentional change, BC is using MJ again, more changes/mechanics will follow soon

**Comment by SharperC** [comment]
ok good to know x3
