### ISSUE TITLE
The paintbrush doesn't have a recipe

### ISSUE THREAD

**Issue by AlexIIL** [BuildCraft/BuildCraft#4151]
It looks like this was lost in the 1.12 port, and was never moved over to `JSON`. I think we'll come back to JSON recipes in 1.13 when we have a proper (sane) system for making colouring recipes in a single file rather than 16 different ones.

For now all this means is that someone needs to move this function: https://github.com/BuildCraft/BuildCraft/blob/0c6280732f153c8983e70f555a79a585611c214a/common/buildcraft/core/BCCoreRecipes.java#L9-L65 into an event handler like this:
````java
@SubscribeEvent
public static void registerRecipes(RegistryEvent.Register<IRecipe> event) {
    // Code goes here
}
````

**Comment by AlexIIL** [comment]
Duplicate of #4149 .

How did I miss that????

**Comment by iTitus** [comment]
Vanilla and Forge encourage generation of recipe JSON via code. 1.13 will ship the generators and stuff that vanilla uses.

**Comment by iTitus** [comment]
Maybe we get some saner stuff then ;)
