### ISSUE TITLE
Bear Claw Image, it doesnt show the image of a bear claw, but the name and items exist 

### ISSUE THREAD

**Issue by Franche150** [BuildCraft/BuildCraft#4152]
BuildCraft version: 
Forge version: 
Link to crash report or log: 
Singleplayer or multiplayer: 
Steps to reproduce: 
Additional information:

**Comment by AEnterprise** [comment]
this does not sound like a BuildCraft issue, if you are playing sevtech ages please report to the pack author instead: https://github.com/Darkosto/SevTech-Ages/issues
