### ISSUE TITLE
WEIRD bug with ICBM Classic

### ISSUE THREAD

**Issue by Bryanbetatester** [BuildCraft/BuildCraft#4156]
BuildCraft version: 7.99.16
Forge version: 14.23.3.2677
Link to crash report or log: 
Singleplayer or multiplayer: singleplayer
Steps to reproduce: Place a tier 3 launch pad, then break it an in the same location place a pipe
Additional information: When the bug is active the game goes 3x faster, here a image:
![2018-05-04_19 47 56](https://user-images.githubusercontent.com/34108139/39657438-d67c2604-4fd5-11e8-8852-ae504824d290.png)

**Comment by AEnterprise** [comment]
looks like an ICBM classic issue, typical example of the mod leaving the block TE behind when the block is broken
