### ISSUE TITLE
Using MiniMap in a lower stage of the Game

### ISSUE THREAD

**Issue by Romancc** [BuildCraft/BuildCraft#4157]
BuildCraft version: 7.99.15
Forge version: 14.23.2.2651
Link to crash report or log: none
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: While sprinting you can enable the MiniMap for short moment by pressing the key the is assigned to the MiniMap (default: "J")
Additional information:

**Comment by AEnterprise** [comment]
this does not sound like a BuildCraft issue, if you are playing sevtech ages please report to the pack author instead: https://github.com/Darkosto/SevTech-Ages/issues
