### ISSUE TITLE
Engines and Kinesis Pipes Issue

### ISSUE THREAD

**Issue by KethTheMeifwa** [BuildCraft/BuildCraft#4158]
I was messing around with buildcraft for the first time, and I placed the quarry. After reading that the more power it had given to it, the faster it went I thought... there has to be a faster way then just 3 engines connected to it! So I found the Kinesis pipes. After connecting more engines via wooden kinesis pipes I tried all of the other ones (cobblestone, stone, gold, ect) and the engines placed on their back like they were not there! Also, if you placed 2 wooden kinesis pipes next to each other they would stay separate.
![2018-05-05_09 57 24](https://user-images.githubusercontent.com/30805331/39664571-d858b9ae-504a-11e8-8179-de9479e87fa3.png)
![2018-05-05_09 57 33](https://user-images.githubusercontent.com/30805331/39664572-d8696f6a-504a-11e8-90f7-d534c41cd7a6.png)
![2018-05-05_09 57 46](https://user-images.githubusercontent.com/30805331/39664574-df342312-504a-11e8-8827-2520f31e08af.png)
BuildCraft version: 7.99.16
Forge version: 14.23.3.2655
Link to crash report or log: 
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Connect a wooden pipe to a quarry, then connect an engine to it. Repeat with the other types of Kinesis pipes, and you will see that the engine doesn't connect.
Additional information:

**Comment by AlexIIL** [comment]
Yes, wooden kinesis pipes won't connect to other wooden kinesis pipes. However you can connect wooden kinesis pipes to other types of kinesis pipes, which will allow you to connect multiple engines.

**Comment by KethTheMeifwa** [comment]
Yes I noticed that just now, is that a feature or a bug?

**Comment by AlexIIL** [comment]
Feature (technically), although unlike item and fluid pipes kinesis pipes don't really need a specific extraction pipe for anything.

**Comment by KethTheMeifwa** [comment]
Ok
