### ISSUE TITLE
Pumps can no longer interact with Ender IO Dimensional Transceivers

### ISSUE THREAD

**Issue by PraiseJoko** [BuildCraft/BuildCraft#4159]
Placing a Pump next to an Ender IO Dimensional Transceiver no longer works. The pump is unable to receive power from the Transceiver, regardless of the Transceiver's I/O settings (Push, Pull, None) nor can the pump output fluids into the Transceiver.

BuildCraft version: 7.99.16
Forge version: 1.12.2-14.23.3.2655
Ender IO version: 1.12.2-5.0.24
Ender Core version: 1.12.2-0.5.22
Java version: jre1.8.0_171
Link to crash report or log: Doesn't crash, thankfully. :)
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Place a Pump next to a Dimensional Transceiver or vice versa and watch as absolutely nothing happens. Change the Dimensional Transceiver's I/O settings to your heart's content, and nothing continues to happen. Break the blocks, place them back down in any order, and still nothing.
Additional information: Yes, the Transceiver has appropriate channels for energy and fluids, and it's send/receive channel settings are correct. The same Transceiver works fine with other blocks, machines, tanks, and the like, including Ender IO, Thermal Expansion and Mekanism.
A Buildcraft Pump connected to a Dimensional Transceiver or a Tesseract was my go-to method of cleaning up world oil spawns in all my Minecraft 1.7.10 games - it worked perfectly then.
Thermal Expansion version: 1.12.2-5.4.2.27
Thermal Foundation version: 1.12.2-2.4.1.15
Mekanism version: 1.12.2-9.4.5.340
Note: I remember reading a forum post mentioning that Ender IO has changed the communications library it uses as part of the mod's update from Minecraft 1.7.10 to later versions. Think this might be why it's stopped working?

**Comment by AEnterprise** [comment]
BC no longer uses RF but MJ, as such the dimensional transiever can't power it, you'll need to use (redstone) engines for power. it should still be able to output fluids to it
