### ISSUE TITLE
Forestry engines don't conect to BC wooden kinesis pipes

### ISSUE THREAD

**Issue by Jamon3Y** [BuildCraft/BuildCraft#4161]
BuildCraft version: 7.99.16
Forge version: 14.23.3.2678
Link to crash report or log: It doesn't crash the game
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Try to use a forestry engine with a BC wooden pipe
Additional information: 
Nothing else to add. 
However im not sure if this is a forestry thing or a BC thing, but, it is the pipes not reacting to Forestry, so i guess i'll post it here

EDIT: sorry, i put the BC version on the forge blank space
Forestry version is 5.8.0.284, in case its relevant

**Comment by AEnterprise** [comment]
right now this is intended, BC uses MJ, forestry uses RF

compat may be looked at later (although it won't be RF->MJ convertion)

**Comment by Jamon3Y** [comment]
I see, i thought BC used the same energy as forestry since their machines looked the same
silly me haha
Thanks for your help
