### ISSUE TITLE
Crashing when loading world with pipes

### ISSUE THREAD

**Issue by Nicazer** [BuildCraft/BuildCraft#4166]
I was playing on a survival world, and set up a quarry. When I went to place pipes, about three or four pipes down my game lagged severely, then the game crashed without creating a report. When I try to join the world my game crashes, continuing to not provide a report.
Further testing shows that the Forge version does not matter.

BuildCraft version: 7.1.22/7.1.18
Forge version: 1.7.10-Forge 10.13.4.1564-1.7.10
Singleplayer Survival world
Steps to reproduce: Place down item pipes. Try stone or cobblestone, they are what I had available when the issue occurred.
Additional information: 
Crash only happens about 75% of the time I place a pipe, not sure if that is relevant to anything.

**Comment by AlexIIL** [comment]
Can you find and upload a crash report or your latest log file? One should either be in the "crash-reports" or "logs" folders, next to the save and resource pack folders.

**Comment by Nicazer** [comment]
[crash-2018-05-16_15.55.40-client.txt](https://github.com/BuildCraft/BuildCraft/files/2015085/crash-2018-05-16_15.55.40-client.txt)
Sorry I forgot to even think about that.

**Comment by asiekierka** [comment]
This is a known issue with OptiFine. You MUST disable any form of multi-core chunk loading/rendering.
