### ISSUE TITLE
Feature request: Add RF

### ISSUE THREAD

**Issue by BinaryVigilante** [BuildCraft/BuildCraft#4170]
Hi,

Buildcraft is a mod that I personally really love playing with! Or, it was anyway. When I play with industry in Minecraft, I like the idea of having multiple industry mods that can both help each other in certain situations, and also because each industry mod is different, each mod most likely has something the other hasn't got.

So I used to play with Buildcraft together with other industrial mods. but Buildcraft is no longer a mod that I would have in my industrial world. The reason why, is that the energy type that Buildcraft has is not compatible with any of the other industry mods. Most industrial mods either only have or are compatible with Redstone Flux. But Buildcraft isn't.

I'd suggest that either replace MJ with RF or make Buildcraft compatible with RF. I really want to use Buildcraft in my modpacks, but I don't because it just doesn't fit in because it only has it's own energy system.

Please, please add RF to Buildcraft again! I'd love to see that so much! I really love Buildcraft, but it doesn't fit with other industry mods.

Have a great day/night!

Best regards
Binary Vigilante

**Comment by AlexIIL** [comment]
MJ isn't finished yet, and it doesn't make much sense to just rip it out in favour of RF before it's even finished. Likewise, it doesn't make much sense to me to implement RF compat instead of working on MJ and the rest of the missing content.

**Comment by BinaryVigilante** [comment]
I didn't say to rip it out. I'm not saying that MJ is bad, I'm saying that people aren't going to be able to use Buildcraft as they have done before or are used to.

In my case, I combined Buildcraft, Thermal Expansion, and Forestry, and they make a very good team. I used Buildcraft to pump oil, make that oil into refined fuel and then run that through engines, that then powered my base. I can't do that anymore, because no other mods are using MJ.

It's okay if Buildcraft is the only industry mod that you have, but it's not mixing well with others because no one is using MJ.

I'm just saying and suggesting that buildcraft should at least add RF so that it can function with other mods. Maybe it would be possible to make it so that you could turn RF on/off in the config file. And if RF is set to on, Redstone Flux would then be required in order for Buildcraft to work.

I'm not saying in anyway that I think MJ is bad, I'm just saying that if Buildcraft is to be put in modpacks and stuff like that, then I think RF is needed as no one else is using MJ.

Have a great day/night!

Best regards
BinaryVigilante

**Comment by BinaryVigilante** [comment]
Oh wait, there is a power converter? I haven't found one yet. Neither did I know that Buildcraft was in alpha.

Thanks for the help! I will try and search for a converter then!

Btw., I think Buildcraft is a great mod! I really love playing with it! It was just the MJ thing I was thinking about and maybe give some ideas ;)

Have a fantastic day/night!

Best regards!

**Comment by BinaryVigilante** [comment]
Hey @AlexIIL, do you have a link for a power converter mod for Minecraft 1.12.2? I have been searching and searching but have found nothing. If you know a power converter mod, please let me know! :D

Thanks in advance! Have a nice day/night!
Kind regards!
