### ISSUE TITLE
Not launching game

### ISSUE THREAD

**Issue by JTC2000Official** [BuildCraft/BuildCraft#4171]
https://pastebin.com/jUfBpTvg 

BuildCraft version: 7.99.17
Forge version: forge-14.23.3.2673
Link to crash report or log: https://pastebin.com/jUfBpTvg 
Singleplayer or multiplayer: Before launching the game
Steps to reproduce: Put in ALL buildcraft mods made by CovertJaguar on the twitch launcher and launch the game
Additional information: It got duplicates just by downloading them directly from the Twitch launcher once

**Comment by AlexIIL** [comment]
The "buildcraft-7.99.17.jar" files contains all modules (except compat), so you don't need to download every module separately. You'll probably want to either remove the "buildcraft-7.99.17.jar" file or remove every other one to make it work.
