### ISSUE TITLE
creative engines produce no worthwhile amount of power.

### ISSUE THREAD

**Issue by Too-DAMN-Much** [BuildCraft/BuildCraft#4173]
pretty self explanatory really, i've had up to 75 creative engines powering a single maximum size quarry and the result was an absolutely pathetic operation speed.

**Comment by AEnterprise** [comment]
not sure how you did 75 did you chain them? if so then that doesn't work and only the one directly on the quarry was providing power

if you used kinesis pipes: those are a bit buggy atm and you probably had loops in the pipes, this messes up routing

also you just need a single one on the quarry itself, it starts out at low power but you can ramp that up by shift clicking it with a wrench

**Comment by Too-DAMN-Much** [comment]
i tried connecting it directly to the quarry first and it didn't seem to do anything, so i tried the standard buildcraft piping with golden and wooden pipes.

that wrench thing ought to be documented somewhere, somewhere easy to find, maybe a tooltip if shift is held, literally had no clue that was a thing.
