### ISSUE TITLE
Pipes not connecting.

### ISSUE THREAD

**Issue by BigCasper** [BuildCraft/BuildCraft#4174]
BuildCraft version: 7.99.8.2 (1.11.2)
Forge version: 1.11.2-13.20.1.2386
Multiplayer
Pipes do not connect with non-buildcraft stuff. (Forestry and Botania in my case)

**Comment by iTitus** [comment]
What types of pipe are you trying to connect to which blocks?

**Comment by AEnterprise** [comment]
if you're trying to connect kinesis pipes it won't work, BC uses MJ again

**Comment by Homosanians** [comment]
What changed? I was able to connect electric engines from forestry to BC pipes before.
![image](https://user-images.githubusercontent.com/35880220/40653054-a8ca1a56-6342-11e8-8165-edd0a3ed8bef.png)

**Comment by BigCasper** [comment]
@iTitus I've tried to connect a Forestry engine and a Botania Mana Fluxfield. Both don't want to connect.
@AEnterprise Do you know a solution to that then?

**Comment by AEnterprise** [comment]
BC uses MJ so directly connecting won't work, you'll need a power converter mod

also keep in mind the MJ mechanics are going to change completely soon
