### ISSUE TITLE
MC crashed after the creation of a new world

### ISSUE THREAD

**Issue by Allnorm** [BuildCraft/BuildCraft#4175]
BuildCraft version: 7.99.17
Forge version: Forge 14.23.3.2655 
Link to crash report or log: https://drive.google.com/file/d/1CUrWeZ-VcTuwZoz0ng56TNESUXgjU2fu/view?usp=sharing
Singleplayer or multiplayer: SP
Additional information: I created new world and MC crashed after it.

**Comment by AlexIIL** [comment]
> java.lang.IllegalAccessError: tried to access method javax.vecmath.Matrix3d.compute_svd([D[D[D)V from class javax.vecmath.Matrix4f

I have no idea what could be causing that...

**Comment by Chocohead** [comment]
It's the Real Train Mod, see micdoodle8/Galacticraft#3393

**Comment by AlexIIL** [comment]
In which case there's nothing we can do about it, unfortunatly.
