### ISSUE TITLE
Sometimes contents of Chest next to crafting station will disappear

### ISSUE THREAD

**Issue by CJProcks123** [BuildCraft/BuildCraft#4176]
BuildCraft version: Latest
Forge version: Latest
Link to crash report or log: 
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Put chest next to crafting station and put items in then using crafting station to craft.
Additional information:

**Comment by AlexIIL** [comment]
Crafting station? I don't think buildcraft has a crafting station. What does it look like?

**Comment by AEnterprise** [comment]
this does not sound like a BuildCraft issue, if you are playing sevtech ages please report to the pack author instead: https://github.com/Darkosto/SevTech-Ages/issues

otherwise please report to tinkers as they add the crafting station
