### ISSUE TITLE
[Request] Auto-Hide Facades

### ISSUE THREAD

**Issue by Sanofus** [BuildCraft/BuildCraft#4178]
I'm not sure if this is a bug or not but it might be very important because BC facades have a much amount and fill JEI. That is very annyoing if you look up a thing and 3 pages are just facades. Maybe this could be changed like Thermal Dynamics does to avoid flooding screen with facades.

**Comment by LuigiHutch** [comment]
Thanks for the request. This would actually be a BC Compat issue as JEI integration (as with all mod integration) is located there. Please request this to https://github.com/BuildCraft/BuildCraftCompat Thanks!

**Comment by Sanofus** [comment]
I think this could be closed than?
