### ISSUE TITLE
Spam INFO log output 20 times/second leads to server lag requiring restart

### ISSUE THREAD

**Issue by Shadowrs** [BuildCraft/BuildCraft#4185]
BuildCraft version: 7.99.17 (& bc compat 7.99.14)
Forge version: forge-1.12.2-14.23.4.2705-universal

Link to crash report or log: https://pastebin.com/raw/EswDKLHG  -- Not a stacktrace, spam [INFO] println

Singleplayer or multiplayer: multiplayer

Steps to reproduce: Add 6 point-to-point Fluid Teleport Pipes, have pipes fill up with liquid (destination tank or engine is full) and the INFO log level message is printed 10+ times per second. This eventually fills up the MC Server GUI text pane and after 1h30 (keep in mind my pc is brand new 8700k 16GB DDR4) it causes major server lag and eventually requires a server restart. Can be avoided by using the "nogui" option, where windows cmd output buffer is limited and messages are quickly discarded. 

Additional information: Not a mem leak based on the server not exceeding 2GB ram, it's just the buffer of the GUI getting too large. Also I've actually destroyed all my fluid pipes and I'm still getting the message. I don't believe I've forgotten about a pipe somewhere. Is there a way to flush the Additional Pipes system or dump pipe locations? Thanks for reading!

**Comment by AEnterprise** [comment]
nothing we can do about that though, Additional Pipes isn't part of buildcraft, you'll need to report this on the AP issue tracker: https://github.com/tcooc/AdditionalPipesBC
