### ISSUE TITLE
Not being able to use RF sucks. Fix it please.

### ISSUE THREAD

**Issue by Pulverizer** [BuildCraft/BuildCraft#4186]
Either stop the switch to MJ and stay with RF, allow both to work with being run through a converter or make it a config option.

**Comment by AEnterprise** [comment]
MJ mechanics are not fully implemented are will change completely in the future, there are currently no plans to return to RF or have native conversion, you can use an external conversion mod if you really don't want MJ right now until the mechanics are implemented
