### ISSUE TITLE
red stone engine turned into black color. I tried to hit whit wrench and it didnt work ?? help

### ISSUE THREAD

**Issue by Jack767799** [BuildCraft/BuildCraft#4190]
BuildCraft version: 7.99.14
Forge version: 14.23.3.2655 
Link to crash report or log: 
Singleplayer or multiplayer: Single player 
Steps to reproduce: 
Additional information: HELP ASSAP

**Comment by therealfarfetchd** [comment]
The engine only outputs power if it actually needs to pull an item/fluid out. If it doesn't it just stays there and heats up. It will still work fine. (although, I don't know if this is intentional behavior or not, but it's definitely not a problem)

**Comment by Jack767799** [comment]
![2018-06-09_04 26 32](https://user-images.githubusercontent.com/38232860/41176989-ff434b14-6b94-11e8-8793-11f883eb4514.png)
???

**Comment by therealfarfetchd** [comment]
Oh, then I have no idea. Sorry

**Comment by Jack767799** [comment]
still ty for your time

**Comment by jburkej1** [comment]
turn off one of the engines, if you are using a standard wooden extraction pipe one is enough, running two 
can cause them to over heat and turn black. Wood/Diamond pipe extracts material faster but after awhile the engines will turn black as well. I had this same behavior pulling oil from tanks to go into distillers.

**Comment by Jack767799** [comment]
ty :D 💯

**Comment by AEnterprise** [comment]
yeah, both engines where just providing to much power combined, causing neither of them to be able to get out of the overloaded state visual
