### ISSUE TITLE
Quarry not taking RF from other sources

### ISSUE THREAD

**Issue by CodingKid124** [BuildCraft/BuildCraft#4201]
BuildCraft version: 7.99.17
Forge version: 14.23.4.2708
Link to crash report or log: 
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Put any RF emitting device (not a buildcraft one) like a solar panel, and the quarry will not work.
Additional information:

**Comment by AlexIIL** [comment]
After 7.99.0 buildcraft produces and consumes MJ, which is different to (and separated from) RF.
