### ISSUE TITLE
Rf to Mj 

### ISSUE THREAD

**Issue by Raamusbbi2704** [BuildCraft/BuildCraft#4206]
Rf to mj so there not are a problem white the most mods mj are dead now com on make rf its better for the mod 

BuildCraft version: 7,99,17
Forge version: forge-14.23.4.2709
Link to crash report or log: 
Singleplayer or multiplayer:  singleplayer/multiplayer

**Comment by AlexIIL** [comment]
MJ (in it's current iteration) is new, and still in alpha status. In the future it should be more interesting and actually separated.

For now you can use a converter mod to get RF <-> MJ.
