### ISSUE TITLE
Facade Lighting Bugged

### ISSUE THREAD

**Issue by Starflight164** [BuildCraft/BuildCraft#4208]
![capture2](https://user-images.githubusercontent.com/40528301/41815580-e1a93072-7734-11e8-87b8-f6d7cd102199.PNG)

![2018-06-23_22 18 49](https://user-images.githubusercontent.com/40528301/41815550-1f4d6804-7734-11e8-85ad-19ae8d4f0e33.png)

**Comment by afdw** [comment]
https://github.com/BuildCraft/BuildCraft/issues/3779

**Comment by Starflight164** [comment]
Sorry, I realized after I made the issue that someone already had it.
