### ISSUE TITLE
unable to craft Planner, builder, filler, electonic libary

### ISSUE THREAD

**Issue by Matthewgod1** [BuildCraft/BuildCraft#4211]
I'm unable to craft items that were able to in pervious versions

BuildCraft version: 7.99.17
Forge version: 14.23.4.2709
Link to crash report or log: 
Singleplayer or multiplayer: 
Steps to reproduce: 
Additional information:

**Comment by AlexIIL** [comment]
Yes, these items aren't finished yet so they aren't craftable in survival

**Comment by LuigiHutch** [comment]
Thanks for the report! This is actually a duplicate of https://github.com/BuildCraft/BuildCraft/issues/3941 and https://github.com/BuildCraft/BuildCraft/issues/4076
