### ISSUE TITLE
Feature suggestion: Blacklist for fluid shards

### ISSUE THREAD

**Issue by alexZrAl** [BuildCraft/BuildCraft#4220]
Hi,

I came up with this idea after breaking a tank full of water and got fragile water shards all over the place. Truly it is nice to have these little shards for saving precious fluids (e.g. fuel, liquid UU matter) when a BC machine/pipe containing them is accidentally broken, but not all liquids are that important. For example, water can be duplicated using the infinite water source technique, so there is no much point using the liquid shards to save these water. The water shards can also cram the player's inventory and make it difficult for the player to pick up items, usually the broken BC machine on the ground.

This fluid shard feature can be further polished by allowing players to prevent certain fluid shards (e.g. fragile water shards) from spawning using a blacklist in the mod configurations. The actual interface could be implemented in a way similar to how players exclude certain biomes from generating oil.

Version of the mod I'm using: 7.99.17

**Comment by Generalcamo** [comment]
Not all mod installations have infinite water. It's also not very intuitive to have some fluids use this mechanic and others not use this mechanic for no apparent reason.
