### ISSUE TITLE
Crash with Charset Patches

### ISSUE THREAD

**Issue by Generalcamo** [BuildCraft/BuildCraft#4233]
BuildCraft version: 7.99.17
Forge version: 2725
Link to crash report or log: https://gist.github.com/Generalcamo/b454816b179499229318e8fccf3182eb
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Place an engine down
Additional information: Caught in dev environment, but probably the case in a normal installation too

**Comment by asiekierka** [comment]
>in dev environment
That crash is specific to a dev environment.

**Comment by asiekierka** [comment]
Oh, right, I know why.

For coremods I develop, you need to manually run them through [BON2](https://ci.tterrag.com/job/BON2/) before they will work correctly. This is true for all coremods I develop. deobfCompile in build.gradle *might* work.

Notably, though, you *shouldn't* need CharsetPatches for any development...? It's only optional features.

**Comment by Generalcamo** [comment]
I was testing some mod integrations. Apologies for the false report though, did not know about that.

**Comment by asiekierka** [comment]
Generally, if you see crashes pertaining to missing fields/methods with weird field_.../func_... names in a *deobfuscated* environment, they'll be related to either an incorrect Minecraft version (somehow...) or the fact specific reflection/coremod logic was not tested with a dev environment properly.
