### ISSUE TITLE
Buildcraft corrupting multiplayer worlds?

### ISSUE THREAD

**Issue by Priority6** [BuildCraft/BuildCraft#4234]
![mods](https://user-images.githubusercontent.com/41526233/43040746-8399549c-8d11-11e8-9179-c91d09bc6a20.png)
(All the mods used in modpack above)
The server I go on is having a massive problem where buildcraft quarries corrupt the world, they can be the normal size, two chunks wide, or 2 blocks wide, doesn't matter, after a while, they _will_ corrupt the server

BuildCraft version: 7.1.23 (In 1.7.10)
Forge version: 1.7.10-1.2.0.345
Link to crash report or log: NULL (unavailable) 
Multiplayer
Steps to reproduce: 1.) Make a quarry
2.) Power it with an industrial steam engine
3.) Let it run for a while
4.) Server will be down and needs a **complete** **reset**
Additional information: Server is ran with NFO
I can't get the crash logs since the owner won't give them to me, so I need any and _all_ solutions, including basic ones!
Please and thank you.

**Comment by AlexIIL** [comment]
What do you mean by corrupt the world? Does the server crash, and then always crash whenever it gets started up again?

**Comment by Priority6** [comment]
> What do you mean by "corrupt the world"? Does the server crash, and then always crash whenever it gets started up again? Or does it affect the world in more minor and odd ways?

Basically by corrupting the world I mean when the server crashes, it cannot start back up, and the server is officially dead unless we do a full server wipe, usually this happens after we add mods, but the server owner now blames buildcraft quarries for it. I'm assuming just to put the blame on something instead of accepting that it's the mod's he added plus the fact that he doesnt back up the worlds after 1 previous wipe.

**Comment by AEnterprise** [comment]
considering in all these years i have never heard about quarries corrupting worlds by just running this seems extremely unlikely

feel free to point the server owner here as without any crashlogs  i doubt we can find what went on or how to fix this

**Comment by iTitus** [comment]
Can you give us a log please. The crash log and the startup log.
Tip: you most likely don’t need a full reset. Try turning on ‚removeErroring(Tile)Entities‘ on in your Forge config for one startup routine. This will try to remove erroring objects from the world. If this doesn’t work you could still use NBTExplorer or MCEdit to just delete one chunk (section) or just one quarry block/entity

**Comment by Priority6** [comment]
`Can you give us a log please. The crash log and the startup log.
Tip: you most likely don’t need a full reset. Try turning on ‚removeErroring(Tile)Entities‘ in your Forge config for one startup routine. This will try to remove erroring objects from the world. If this doesn’t work you could still use NBTExplorer or MCEdit to just delete one chunk (section) or just one quarry block/entity

PS: And do regular backups ;)`

I can't provide the logs sorry, the owner refuses to give them to me for a reason. Also, plugins don't work on the server, they've only worked 1/1000 times we have started up the server. And all of us said to backup the world after the 1st complete wipe and the 2 almost 3 hour rollback, but he didn't listen.

**Comment by AlexIIL** [comment]
We've discussed this a bit on discord - I think the recomendation was to try removing tickdynamic and see if that helped?

Other than that there's not much we can really do to help if the server owner doesn't want to provide anything.
