### ISSUE TITLE
Offer for career expansion

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [BuildCraft/BuildCraft#4237]
Friends, I'm sorry if I'm writing to that channel, but still.
Did you, by any chance, plan to accelerate your career? No, it does not work, but it does not dig it fast enough.
I have 2 sentences, which maybe already sounded, but still.

1. Accelerate the drill itself depending on the power of the engines - i.e. increase its current limit.
2. Make 2 more versions of the drill.
2.1. Improved version of the drill - in this role there are already 2 drills instead of one. Each drill divides the carcass's territory in half and extracts its side.
2.2. Advanced version of the drill - as in the version with two drills, only here is 4 borax. They will also divide the territory into 4 parts and work in their field.

If the second option is too complicated in programming, can you just use the first option?
In principle, this is all I wanted to offer)

**Comment by AlexIIL** [comment]
Hi, did you translate this from a different language? While we don't have a "career" in Buildcraft we do have a "quarry".

I currently plan to implement your first suggestion anyway, although that will be released with the MJ power system changes.

(Also did you mean to close this? This is a valid issue)

**Comment by xxxLEOPARDxxx** [comment]
Yes, I translated from Russian.
It is very good that you continue to develop this wonderful mod!
I closed this question at the request of LuigiHutch.
In fact, this question is relevant, but if the work is in this direction, then I see no reason to keep it "open";)
