### ISSUE TITLE
Bugs With Heat Exchanger

### ISSUE THREAD

**Issue by Bigdbigd03** [BuildCraft/BuildCraft#4242]
Running BuildCraft version 7.99.17 on Forge version 14.23.4.2705, I encountered multiple bugs with the heat exchanger. If you put heavy oil in the heat exchanger and then switch it with lava (these specific fluids are in my case. I am not saying they are the only ones), it will still run oil, although it theoretically has none. So you can heat up your fluids without cooling any fluids. For the second one, you can just break the middle heat exchange block and it still runs fine. The last one makes the annoying one, when you break a heat exchange block and replace it, no pipes reconnect. This was in singleplayer.

![2018-08-02_19 22 02](https://user-images.githubusercontent.com/20918683/43619174-91e79f94-969a-11e8-8383-20907f001141.png)
![2018-08-02_19 24 18](https://user-images.githubusercontent.com/20918683/43619203-ad5c0dfa-969a-11e8-84b5-11645d2fc051.png)
![2018-08-02_20 46 34](https://user-images.githubusercontent.com/20918683/43619214-b686e080-969a-11e8-8b6c-280aa11b5af7.png)

EDIT: Two screenshots contain OpenBlocks tanks, but that's because I prefer them. They have nothing to do with the bug.

**Comment by jburkej1** [comment]
if you change fluids into any input you might have to break the exchanger block and readd it. Something residue for a lack of a better name is left and blocks it.

**Comment by AlexIIL** [comment]
I think this might have been fixed in 7.99.19 or 7.99.20?

**Comment by Bigdbigd03** [comment]
In 7.99.22 I cannot recreate any of these issues.

**Comment by AlexIIL** [comment]
Ok, thanks!
