### ISSUE TITLE
RF Power problems

### ISSUE THREAD

**Issue by GmanAtheist** [BuildCraft/BuildCraft#4243]
BuildCraft version: 1.12.2
Forge version: 14.23.4.2747
Link to crash report or log: 
Singleplayer or multiplayer: Single
Steps to reproduce:  RF powe from other mods do not connect to BC Quarry or machines. 
Additional information:

**Comment by Generalcamo** [comment]
Completely intentional, Buildcraft no longer uses RF (nor Forge Energy) and instead uses its own MJ again.

**Comment by GmanAtheist** [comment]
So, No way to store Energy then. Buildcraft has become racist. :-p lol

**Comment by AlexIIL** [comment]
That's certainly one way of putting it 😝
