### ISSUE TITLE
java.lang.NullPointerException: Exception in server tick loop 	at buildcraft.core.BCCoreEventDist.onWorldTick(BCCoreEventDist.java:27)

### ISSUE THREAD

**Issue by Pa4ok** [BuildCraft/BuildCraft#4245]
BuildCraft version: buildcraft-7.99.17
Forge version: 1.12.2-14.23.4.2739
spongeForge: 1.12.2-2705-7.1.0-BETA-3383.jar
Link to crash report or log: https://gist.github.com/Pa4ok/3fc3c4c15c231cf08d42bfa885374877
Singleplayer or multiplayer: multiplayer

**Comment by AlexIIL** [comment]
That's odd... it looks a bit like the world is null in `WorldTickEvent`.

Does this happen instantly when you start the server or does it only happen randomly?

**Comment by Pa4ok** [comment]
no, randomly
at that time was no restart
i found this crash report few days later

**Comment by AlexIIL** [comment]
Oh ok. I'm not really sure what could have caused that but I'll add a null check so that it won't say anything about it in the future.
