### ISSUE TITLE
Buildcraft 7.1.23 Facade Unbalanced Brackets

### ISSUE THREAD

**Issue by josh6025** [BuildCraft/BuildCraft#4248]
BuildCraft version: 7.1.23
Forge version: 1.7.10-10.13.4.1614
Singleplayer or multiplayer: multiplayer
Steps to reproduce: Give yourself a facade
Additional information: Error message

Data tag parsing failed: Unbalanced brackets: {type:0b,states:[0:{metadata:0b,hollow:0b,block:"minecraft:stone",transpare

List of mods on the server

- additionalpipes-4.7.7
- buildcraft-7.1.23
- CodeChickenCore-1.7.10-Recommended
- industrialcraft-2-2.2.828-experimental
- IronChestMinecarts-1.0.4
- Iron-Chests-Mod-1.7.10
- irontank-1.7.10-1.1.15.65
- Not-Enough-Items-1.7.10-Recommended
- Railcraft_1.7.10-9.12.2.0
- worldedit-forge-mc1.7.10-6.1.1-dist

**Comment by AlexIIL** [comment]
How are you giving yourself a facade? Did you run a command or use a mods GUI? or from the creative menu?

**Comment by asiekierka** [comment]
Sounds like the chat box cannot fit the full facade tag?

**Comment by asiekierka** [comment]
I think what is happening is that NEI is using the "/give" command instead of its own protocol. Either way, that's probably not our issue.
