### ISSUE TITLE
Guidebook lag

### ISSUE THREAD

**Issue by deusversus** [BuildCraft/BuildCraft#4249]
I can't open the guidebook without a lagspike; the client freezes for about 15-20 seconds before opening the guidebook.

BuildCraft version: 7.99.17
Forge version: 2747
Link to crash report or log: n/a
Singleplayer or multiplayer: Multiplayer
Steps to reproduce: Open the Guidebook
Additional information: n/a

**Comment by Bigdbigd03** [comment]
For me it's about 2-5 seconds, but it is a thing.

**Comment by Bigdbigd03** [comment]
I opened it about 4 times in 2 worlds.

**Comment by AlexIIL** [comment]
I'm not entirely sure where the performance issue is so I'll add some profiling to 7.99.18-pre1 and then ask you to send the resulting profiler logs back here. So it will probably take a few days.

**Comment by AlexIIL** [comment]
After a bit of analysis it looks like it scans the item and statement registries everytime you open the gui, and populates a search object, which takes up quite a while. I'll try moving that code to the main reload() sequence to see if that speeds it up a bit.

**Comment by AlexIIL** [comment]
This should be fixed in [the 7.99.18-pre1 prerelease](https://www.mod-buildcraft.com/pages/tests.html), or you can wait until 7.99.18 itself gets released.

**Comment by deusversus** [comment]
Many thanks.
