### ISSUE TITLE
Googles Server Issue

### ISSUE THREAD

**Issue by DEViANCEVxXXxM** [BuildCraft/BuildCraft#4253]
BuildCraft version: BuildCraft 7.99.17
Forge version: 14.23.4.2756
Link to crash report or log: https://hastebin.com/elujaloyat.rb
Singleplayer or multiplayer: server logs
Steps to reproduce: run server

**Comment by LuigiHutch** [comment]
Thanks for the report! This is actually a duplicate of #3865,  #3979, #4093, #4213 and #4244.
