### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by AstralPie123** [BuildCraft/BuildCraft#4259]
hello i have a problem that if i have the core and robotics mod enabled the core mod crashes the game
BuildCraft version: 1.11.2
Forge version:1.11.2 
Singleplayer or multiplayer: singleplayer
Steps to reproduce: what
Additional information: what?!?!?!

**Comment by AEnterprise** [comment]
could you provide a crashlog?
also 1.11.2 is your minecraft version, not your BC or forge version

**Comment by AEnterprise** [comment]
closing this issue due to a lack of information, feel free to reply if you do have the information (crash log, actual version numbers, ...) and we can take another look then
