### ISSUE TITLE
Guide book contents pages don't display the full tooltip

### ISSUE THREAD

**Issue by AlexIIL** [BuildCraft/BuildCraft#4263]
Was working in 7.99.17, then broken in 7.99.18.

**Comment by Bigdbigd03** [comment]
you closed it and opened it in the same minute

**Comment by AlexIIL** [comment]
Yes, the commit referenced this issue so it closed it, however I only want to close issues when the fix has been released, so I needed to re-open it.

**Comment by Bigdbigd03** [comment]
Oh (Off topic but eh) well that means you can close the Guidebook lag one now that 7.99.18 is released.
