### ISSUE TITLE
Quarry will not accept RF from Draconic Evolution or Xnet

### ISSUE THREAD

**Issue by Cleardragonf** [BuildCraft/BuildCraft#4267]
BuildCraft version: 7.99.18
Forge version: 1.12.2-14.23.4.2760
Link to crash report or log: 
Singleplayer or multiplayer: multiplayer
Steps to reproduce: attempt to add a IO Crystal to the quarry and it doesn't recognize it.  Add a connector and it doesn't recognize it...but a Engine recognizes the Connector.
Additional information:

**Comment by AEnterprise** [comment]
BuildCraft in 1.11+ has moved back to using its own MJ power system which is NOT compatible with RF. However, due to BuildCraft being in alpha no other mods support it, or should support it, as we are still making breaking changes to the API
