### ISSUE TITLE
Machines Incompatible with other mod power sources.

### ISSUE THREAD

**Issue by KilledBySandvich** [BuildCraft/BuildCraft#4274]
Any Buildcraft machine will only accept Buildcraft power. No other power supply like Thermal Expansion, Immersive Engineering, Extreme Reactors, etc. will connect or be used.

BuildCraft version: 7.99.18, latest at time of report.
Forge version: 14.23.2705
Link to crash report or log: Not a crash
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Try to connect any Buildcraft machine to another mods power lines/blocks.
Additional information: 
Even kinetic pipes will not connect to other mods blocks, only Buildcraft.
I know I'm using an older version of Forge, but I highly doubt that that's the problem.

**Comment by scagood** [comment]
BuildCraft (since 1.11) has moved back to MJ, all these mods are using RF which is incompatible.
BuildCraft's MJ is still very much in alpha. mod support will no doubt come in the future.

Duplicate list; #4267 #4243 #4170 #4159 #4108 #4073 #4054 #3933 #3890 #3863 #3828 #3827 #3760
