### ISSUE TITLE
Mod interaction issue: Liquid Duplication glitch involving Fragile Fluid Shards and TechReborn Thermal Generators

### ISSUE THREAD

**Issue by coderbot16** [BuildCraft/BuildCraft#4275]
BuildCraft version: 7.99.17
Forge version: 14.23.4.2705
Link to crash report or log: Not Applicable (not a crash, and no relevant messages printed in log)
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: 

1. Install BuildCraft, Reborn Core, and TechReborn.
2. Place down a BuildCraft tank, and place a bucket of lava into it.
3. Break the tank, releasing 2 fragile fluid shards with lava.
4. Place a lava fluid shard into the Thermal Generator.
5. Observe that the tank fills without draining the fluid shard.

Additional information: 
I am not sure if this is the fault of TechReborn or BuildCraft. I reported it here first, since fluid containers containing less than a bucket's worth of liquid are nonstandard, although if BuildCraft is not at fault I will post it at TechReborn's github instead. 

Note that this is a liquid duplication glitch rather than just infinite energy as it is possible to extract fluid back from the Thermal Generator by placing empty fluid containers in the input instead of filled ones.

![2018-09-29_21 37 01](https://user-images.githubusercontent.com/22420959/46253403-e805c780-c42f-11e8-8ba6-e5961895ac8f.png)
![2018-09-29_21 37 15](https://user-images.githubusercontent.com/22420959/46253404-e9cf8b00-c42f-11e8-8bc2-1bbaffcbe7cf.png)

**Comment by AlexIIL** [comment]
In theory our fluid shards should work properly (and forge's fluid API's don't mandate specific container sizes) so I think this is probably related to how tech reborn handles fluids in items. Can you open an issue with them as well?

**Comment by coderbot16** [comment]
Ok, will do. The shards do appear to work properly with the Geothermal Generator, so I'll open an issue with TechReborn.

**Comment by coderbot16** [comment]
It appears that this was an issue in TechReborn/Reborn Core, observed in https://github.com/FTBTeam/FTB-Continuum/issues/369. Updating to the latest version of those mods fixes this issue.
