### ISSUE TITLE
hi my forge 1.12.2 forge 1.12.2-14.23.4.2705 when i`m in multiplayer

### ISSUE THREAD

**Issue by Ashisgood1** [BuildCraft/BuildCraft#4282]
i join this network play.pokemayhem.com 
but when i am in the 2 one before neo is tourned in brown and nothing happend 
just glitching and brown like i say try to fixed this issues to forge 1.12.2-13 something to fixed that or 
i need to play something else then this 

i crying not to play in that network

**Comment by AlexIIL** [comment]
Hi, I'm not quite sure what you are asking? Does the server use buildcraft in some way?

**Comment by AEnterprise** [comment]
a quick look at the site and i have not found any reference to buildcraft at all, seems to just run pixelmon

**Comment by AEnterprise** [comment]
Closing for a lack of information, if you provide the requested information we can re-open and take another look at this.
