### ISSUE TITLE
Buildcraft Lib crash with nullpointer exception

### ISSUE THREAD

**Issue by karakufire** [BuildCraft/BuildCraft#4285]
BuildCraft version: ~v2.4.5 <- It's not build craft's version!~ 7.99.18
Forge version: 14.23.5.2772
Link to crash report or log: https://pastebin.com/byUB6M45
Singleplayer or multiplayer: Single
Steps to reproduce: maybe same mods installation
Additional information: Coremods conflict?

What caused this crash? I can't guess reason from this crash report, written only "from Buildcraft Lib"

**Comment by AlexIIL** [comment]
Can you try temporarily updating to 7.99.19-pre4 (https://mod-buildcraft.com/pages/tests.html)? That should give more information in the crash report.

**Comment by karakufire** [comment]
Installed 7.99.19-pre4, Successfully launched.

**Comment by AlexIIL** [comment]
I'll assume this was fixed in the 7.99.19 release itself - please comment again if it isn't.
