### ISSUE TITLE
BuildCraft causing server to freeze/crash

### ISSUE THREAD

**Issue by RohanJagpal** [BuildCraft/BuildCraft#4286]
BuildCraft version: 7.1.255
Forge version: I am using KCauldron 1.7.10-1614.201 which includes Forge 1.7.10-1614
Link to crash report or log: https://pastebin.com/bdmUVexK
Singleplayer or multiplayer: Multiplayer
Steps to reproduce: Start server
Additional information: When I start my server using KCauldron, everything seems fine until BuildCraft is started. Although there is no crash report, the output freezes, my FTP client disconnects and I can no longer do anything through my PuTTy connection. To get any functionality back I have to restart my VPS.
Server Details: https://gyazo.com/18a2213f8afc8eebb4ba58eccbbbc748
Mods folder: https://gyazo.com/a9284539c414c288f4d67caa5292adc4
Server root folder: https://gyazo.com/32dfecb11e07cf7c852b235e4c0e22ca
I have hosted servers in the past and haven't had an issue with BuildCraft, however now I come here for help and I would like to thank you in advance for what support I may get in return

- Rohan

**Comment by therealfarfetchd** [comment]
If you actually have to restart the box the server is running on to get access to it back something is going very wrong. Especially if the JVM manages to bring down the system...

**Comment by AlexIIL** [comment]
Can you try replicating this issue locally? (I.E. cloning the server root folder on your own computer and running it from there.)

**Comment by AEnterprise** [comment]
also your screenshot shows you have 7.1.22, can you try updating to 7.1.23? doubt it'lll fix it but always better to run latest versions

**Comment by RohanJagpal** [comment]
@AlexIIL I'll get this done as soon as I can and report back if anything changes.

**Comment by RohanJagpal** [comment]
Solved the issue. Thanks for trying to help guys.
