### ISSUE TITLE
Right click on a Wooden fluid pipe with a YetaWrench of EnderIO

### ISSUE THREAD

**Issue by EvoWebFrance** [BuildCraft/BuildCraft#4288]
BuildCraft version: 7.99.18
Forge version: 14.23.5.2770
Link to crash report or log: https://1drv.ms/t/s!AlxEbPeMguZpgYJDVQzzcm2HmOq7eQ
Singleplayer or multiplayer: SinglePlayer
Steps to reproduce: Right click on a Wooden fluid pipe with a YetaWrench of EnderIO
Additional information:

**Comment by AlexIIL** [comment]
In theory this should now be fixed in [7.99.19-pre7](https://mod-buildcraft.com/pages/tests.html), could you test it to make sure it is now fixed?
