### ISSUE TITLE
Server Join Error.

### ISSUE THREAD

**Issue by Midnight-Vortex** [BuildCraft/BuildCraft#4289]
BuildCraft version: 7.99.18
Forge version: 1.12.2 - 14.23.5.2768
Link to crash report or log: https://pastebin.com/8RvYbQWc
Singleplayer or multiplayer:  Multiplayer
Steps to reproduce: 
Additional information:

**Comment by scagood** [comment]
`[15:41:07] [Thread-39/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.bibliocraftmod.com/vcheck/version.txt`

This doesn't seem to be anything to do with buildcraft :+1:

**Comment by Midnight-Vortex** [comment]
oh sry i have see buildcraft on the top
