### ISSUE TITLE
Worse than Cancer

### ISSUE THREAD

**Issue by system-operator** [BuildCraft/BuildCraft#4293]
https://i.postimg.cc/T1gTjvTg/new.png

Please add an option to a build available on Curse to DISABLE THIS SPAM. I get you need money, and coding sucks and is time consuming. But why pass that along to your users?

I can understand SP mode, but this is a multiplayer server, where we need Buildcraft as a dependent and its literally disabled otherwise.  There is no reason for this. I have removed the emitter in the code, but can't use it on Curse. Ridiculous. 

It's just gonna get the axe.

**Comment by AlexIIL** [comment]
What are you referring to here? "Cancer" isn't very descriptive.

**Comment by AEnterprise** [comment]
The warning has nothing to do with money at all, it just warns the user that BuildCraft currently is in an alpha state

If you can't deal with an mod in alpha warning you about the alpha status then you probably shouldn't be using it

It sounds like whatever mod has a hard dep on BuildCraft in your pack is either an addon (but then disabling makes no sense) or a mod that is doing dependencies very wrong

**Comment by system-operator** [comment]
Great. So my only choice is: SPAM ALL MY USERS. 

Awesome!

**Comment by AlexIIL** [comment]
Yes, And I've changed my mind since then.

Also, why would you need to release it without source?

**Comment by AEnterprise** [comment]
also just FYI, even though the BC licence allows you to recompile without said warning, CurseForge does NOT allow you to upload mods that are already on there by someone else seperatly

releasing without source is also a bad idea as people have no clue what you changed
and you would be making a new mirror that i doubt you'll keep updated forever, just confusing user later down the line why there are multiple and one isn't updated anymore

**Comment by system-operator** [comment]
Don't give a shit. Remove the spam. CurseForge won't know its Buildcraft.  I will call it "assCraft".
