### ISSUE TITLE
Right click on EnderIo Enhanced Combustion Generator with liquid stone pipe

### ISSUE THREAD

**Issue by EvoWebFrance** [BuildCraft/BuildCraft#4305]
BuildCraft version: **7.99.19-pre7**
Forge version: **14.23.5.2770**
Link to crash report or log: https://1drv.ms/t/s!AlxEbPeMguZpgYJVMur8vLBZnsUvBA
Singleplayer or multiplayer: **multiplayer**
Steps to reproduce: **Right click on an Enhanced Combustion Generator from EnderIO with Liquid Stone Pipe for coolant liquid (water)**
Additional information: **I must break the pipe connected to the generator to have the GUI. If a Liquid Stone Pipe is connected to the generator, the client is crashing.**

Thank you for all.

Regards

**Comment by AlexIIL** [comment]
I *think* this might be caused by how enderIO renders tile entities as covers? Can you open an [enderIO issue](https://github.com/SleepyTrousers/EnderIO/issues/new) as well, I think it would be useful to see what they make of this.

**Comment by EvoWebFrance** [comment]
No problem, I will post a new EnderIO issue.
Sorry I thought it was a problem with BC...

**Comment by EvoWebFrance** [comment]
@AlexIIL : no problem for me, I really love both mods and only want to make them interroperable !!!

**Comment by HenryLoenwind** [comment]
As the FastTESR runs in an environment where (a) the GL state for the TESR's render pass is not set up and and (b) the draw order is not z-sorted, I wouldn't use workarounds to render in there anyway.

Note that you can switch between fast and normal at runtime as `tileEntityIn.hasFastRenderer()` is the determining factor. So if you know you only have static stuff that can be batched, return true there. That way you you are fast if you can be.
