### ISSUE TITLE
Crash on Server Startup

### ISSUE THREAD

**Issue by BSKCorp** [BuildCraft/BuildCraft#4306]
BuildCraft version: 7.99.19
Forge version: 14.23.5.2768
Link to crash report or log: https://pastebin.com/Uni5BY0n
Singleplayer or multiplayer: Multiplayer
Steps to reproduce: 
Additional information: Is working on a different machine running Windows 10. I am using Lubuntu 18.04. This was a direct copy from the windows machine that was/is running the mod in a server configuration with no problem.

**Comment by AlexIIL** [comment]
I'm not sure what's going on there - it looks like it can't find the trove library?

At first I'm not sure what to make of this other than your server might be missing some libraries, but then I tested the latest prerelease against an MC server and it crashed with a different error so I'll have too see what's causing that -:(

**Comment by AlexIIL** [comment]
Oh well - fortunately I did find that I was using a library that isn't present in the server *anyway* so hopefully this is fully fixed.
