### ISSUE TITLE
9.4.3 where is my questing ???

### ISSUE THREAD

**Issue by japanza123** [BuildCraft/BuildCraft#4310]
BuildCraft version: 7.99.5 
Forge version: 
Link to crash report or log: i cant see any quest in better questing
Singleplayer or multiplayer:  singleplayer
Steps to reproduce: 
Additional information:

**Comment by AEnterprise** [comment]
not sure how this would be a BC bug, does the bug go away when you remove BC?

also 7.99.5 is pretty old, the latest version is 7.99.20

**Comment by japanza123** [comment]
am very confuse about version am try to uninstall and install from game on font page on web but still same problem , so can u give me a link download a full game ? please

**Comment by japanza123** [comment]
hello guys who have file DefaultQuests.json
may be i copy ur file maybe i can see my quest pleseeeee

**Comment by AEnterprise** [comment]
all 7.99.x versions are alpha (content wise)

to install stoneblock follow the instructions on the mod page? if it's on curseforge you need the twitch client

DefaultQuests.json is not a file made or related to buildcraft at all, you wana contact the modpack maker if you use one, or the mod maker if it's from a mod
