### ISSUE TITLE
Façade: Smooth Opal does not apply coordinate-based colors from GeoStrata

### ISSUE THREAD

**Issue by InitHello** [BuildCraft/BuildCraft#4314]
BuildCraft version: 7.1.23 for 1.7.10
Forge version: 10.13.4.1614
Link to crash report or log: https://i.imgur.com/Opv2L28.png
Singleplayer or multiplayer: Probably both, definitely single.
Steps to reproduce: Craft façade. Place. Look.
Additional information: There are two notable ethnically Mongolian populations, off the top of my head, in Siberia. The Buryat people, with around half a million individuals, and the Kalmyks at nearly a quarter million.

**Comment by InitHello** [comment]
@AlexIIL thanks for the attention. If it matters, I care very little about this report, it's a cosmetic issue at worst.

**Comment by AlexIIL** [comment]
Ok, good to know. Unfortunately it's been quite a while since I developed the 1.7.10 version of buildcraft so it's unlikely that I will look into fixing this in the future.

**Comment by InitHello** [comment]
All good. If I bother to learn java I might take a stab at it, but java is ... not python, php, perl, Apple ][ Basic, or similar to any other language I already know, so dot dot dot.

**Comment by InitHello** [comment]
I was mistaken. The problem is AE2, the colors render when facades are covering BC pipes. 

(screenshot)[https://i.imgur.com/YIv1UR1.png]
