### ISSUE TITLE
Feature Request: oil spawn whitelist

### ISSUE THREAD

**Issue by mr2013** [BuildCraft/BuildCraft#4315]
Some mods add essentially infinite dimensions, making a spawn blacklist futile at best. I'd like to request a feature to optionally flip a switch on the list, making it a whitelist instead.

**Comment by Bigdbigd03** [comment]
![image](https://user-images.githubusercontent.com/20918683/55299510-3c026080-5401-11e9-80da-8d9f662421e6.png)
if this was done then, is it still in dev?

**Comment by AlexIIL** [comment]
Oh right no I forgot to close this after releasing [7.99.21](https://mod-buildcraft.com/buildcraft-79921.html).
