### ISSUE TITLE
Crash with Little Tiles

### ISSUE THREAD

**Issue by BaccarWozat** [BuildCraft/BuildCraft#4317]
Crash during loading with Little Tiles. When either BC or LT is removed it doesn't crash.

Relevant line is
> java.lang.Error: Incorrect number of fields! (Expected 2, but got [private boolean net.minecraft.client.renderer.BufferBuilder.field_78939_q, public boolean net.minecraft.client.renderer.BufferBuilder.field_179010_r, public boolean net.minecraft.client.renderer.BufferBuilder.littleTilesAdded])

BuildCraft version: 7.99.20
Forge version: 2768
Link to crash report or log: [Pastebin](https://pastebin.com/Q8ysrHiZ)
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Install BC 7.99.20-all and [Little Tiles](https://minecraft.curseforge.com/projects/littletiles) and [its coremod](https://minecraft.curseforge.com/projects/creativecore). Attempt to start client.
Additional information: This may already have been reported elsewhere (not on Github) by CreativeMD, author of Little Tiles. He claims it is a BC issue.

**Comment by AlexIIL** [comment]
Already fixed in dev, I'm not sure where this was originally reported but it apparently wasn't on github?

Can you test with 7.99.21-pre2 from the tests page? (https://mod-buildcraft.com/pages/tests.html)

**Comment by AlexIIL** [comment]
(specifically since commit https://github.com/BuildCraft/BuildCraft/commit/76e6c48a4ebf9d46192d87ed2061a140d41a4518)

**Comment by BaccarWozat** [comment]
Seems to work now, thanks a lot for the help!

**Comment by AlexIIL** [comment]
Oh er I like to keep issues open until the fix is actually released publicly. (As then it might be more visible to others who have this crash too)

**Comment by AlexIIL** [comment]
(Fixed in 7.99.21, although I forgot to go round closing all of the fixed bugs then).

**Comment by Bhart11** [comment]
so how do you resolve the issue
