### ISSUE TITLE
Quarry does not pick up items (1.12.2)

### ISSUE THREAD

**Issue by Roodypoo0123** [BuildCraft/BuildCraft#4320]
BuildCraft version: 7.99.19
Forge version: 14.23.4.2759
Link to crash report or log: N/A
Singleplayer or multiplayer: Multiplayer (not tested in SP)
Steps to reproduce: Drop an item in the mining shaft passage while the quarry is active, the item will be ignored. Put a chest with items in it, while the chest is picked up, the items coming out of it upon destruction are ignored.
Additional information: Seems to be related to #3599, but as the issue is closed I am not sure wether I should post again in the existing ticket or open a new one.

**Comment by AlexIIL** [comment]
Ok so a while ago @afdw added some code to explicitly disable this. I'm not sure if I want to keep that behaviour though.

**Comment by Roodypoo0123** [comment]
Whenever I looked in my quarry collection chest, I always did with that Christmas feeling wondering what surprise I might found in there. Would it be a stack of rails from an unexpected mine shaft, a lucky bit of treasure from a hidden dungeon chest, or a juicy steak from an unlucky drowned cow ? It always brought a funny thought about the story of how that item got in there.

If it's not a performance matter, I think balance won't suffer a little random item collection. 
That said, I only play solo or friends-only multiplayer. I don't know a bit about griefing and balance. Maybe an opt-out for people willing to disable it ? Or a pricey quarry module extension for enabling the feature ?

Or an opt-in with some guide on how to enable it because I suck at configuring mods and whatnot.

**Comment by AlexIIL** [comment]
It would technically be an optimisation to revert the change to pick up everything, although I don't think it's much of a performance hotspot *anyway*.

I'll revert it back unless someone else has a problem with it.

**Comment by DAmNRelentless** [comment]
For me it doesn't output any items anymore. I am playing it in the Stoneblock 2 modpack

**Comment by AlexIIL** [comment]
Do you mean it doesn't output *any* items like even the stone it mines?

**Comment by DAmNRelentless** [comment]
Well, I was just stupid. Ignore me.

**Comment by Roodypoo0123** [comment]
After such a heated debate, I'd hope the work required to re-activate that feature is relatively light as you identified the bits responsible.
So light that maybe the fix could make it for .21 ?

**Comment by AlexIIL** [comment]
Ok this should be fixed in 7.99.22-pre1 (https://mod-buildcraft.com/pages/tests.html), however I'll close this issue when that is released properly.
