### ISSUE TITLE
[Question] What's the block ID of oil when it's in the world?

### ISSUE THREAD

**Issue by TheDeviantCrafter** [BuildCraft/BuildCraft#4323]
I want to make geodes of oil generate underground with CoFH World. To do this, I need the block ID of the block while it's in the world. The Forge fluid registry ID won't help me here.

I'm looking for the ID of unprocessed crude oil. The same stuff that spawns in oil wells.

**Comment by AlexIIL** [comment]
`buildcraftenergy:fluid_block_oil_heat_0`

Note that you can find this out by looking at the tab completion options for `/setblock ~ ~ ~ buildcraftenergy:<tab>`
