### ISSUE TITLE
Redstone engines not responding

### ISSUE THREAD

**Issue by KieranVollmer** [BuildCraft/BuildCraft#4333]
BuildCraft version: 1.12.2
Forge version: 1.12.2
Link to crash report or log: 
Singleplayer or multiplayer: Single
Steps to reproduce: None
Additional information: I installed the mod-pack part way through a play-through and the redstone engine will only place facing upward and doesn't respond to redstone signals, no matter the surrounding. I've yet to test other engines

**Comment by AlexIIL** [comment]
Currently the engines won't move if they don't have a valid block to power (and that block must also *need* power).

Can you screenshot the engine and what it's next to?

**Comment by KieranVollmer** [comment]
I did some tinkering and found the animations are unresponsive, but the generators still produce RF

**Comment by AlexIIL** [comment]
erm are you talking about redstone engines or a different generator? (Redstone engines produce very small amounts of MJ, not RF).

**Comment by KieranVollmer** [comment]
AE2 uses a different power system. I think that's my problem

**Comment by AlexIIL** [comment]
Ah, ok then, that would probably be the issue.
