### ISSUE TITLE
World corruption using an Energy Converter on a wooden pipe

### ISSUE THREAD

**Issue by bluesun212** [BuildCraft/BuildCraft#4338]
Note:  Energy Converters 1.2.0.10 must be installed.

BuildCraft version: 7.99.21
Forge version: 14.23.5.2768
Link to crash report or log: [Link to PasteBin](https://pastebin.com/H733Br6V)
Singleplayer or multiplayer: Single player
Steps to reproduce: 
1. Create a new creative single player world
2. Place down a chest, and attach a wooden transport pipe
3. Place an MJ Energy producer adjacent to the transport pipe
4. The game should crash, and subsequent attempts to launch the world will crash the game.

**Comment by AEnterprise** [comment]
this is an bug with energy converts, it is sending energy to the wooden pipe on the client side, and causing client side item extraction. This is a very bad idea and should never be done, all item/energy logic should only run on the server, not the client.
