### ISSUE TITLE
MineCraft crash when trying to use boilerfireboxes

### ISSUE THREAD

**Issue by WVMCr** [BuildCraft/BuildCraft#4344]
Win7 platform, 4GB RAM allocated to MineCraft

BuildCraft version: 7.99.21
Forge version: 1.12.2-14.23.5.2806
Link to crash report or log: [crash-2019-01-31_11.56.44-server.txt](https://github.com/BuildCraft/BuildCraft/files/2816618/crash-2019-01-31_11.56.44-server.txt)
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: by placing a solid fuel firebox from RailCraft, the game crash immediately. Same happens when placing a fluid fueled firebox.
Additional information: If I remove the BuildCraft Mod, I can place a firebox and no problem.

**Comment by AlexIIL** [comment]
Can you report this to railcraft as well? As this crash only contains railcraft blocks I think we'd need their input on this too.

**Comment by WVMCr** [comment]
Will do. Thx.

**Comment by WVMCr** [comment]
RailCraft said it should be fixed in Beta 5.
