### ISSUE TITLE
Error when loading ver 7.99.21

### ISSUE THREAD

**Issue by Raportuy** [BuildCraft/BuildCraft#4351]
BuildCraft version:  7.99.21
Forge version: 1.12.2-forge1.12.2-14.23.5.2808
Link to crash report or log: https://pastebin.com/TfcMFxzj
Singleplayer or multiplayer: singleplayer 
Steps to reproduce: to run minecraft
Additional information: -

**Comment by Raportuy** [comment]
I'm sorry, I forgot to write how to cause this error.
I poured the universal capsule from IC2 into the **Combustion Engine**. After that, minecraft caused a crash and I can’t enter anymore.
**Version IC2**: 2-2.8.109-ex112

**Comment by InThayne** [comment]
Just had a similar issue.
Try setting advanced tooltips to false in options.txt

**Comment by AlexIIL** [comment]
@InThayne This isn't related your issue as this crashed while loading the buildcraft gui config file. Although I think I actually fixed this in 7.99.22 but didn't add it to the changelog - can you try updating instead>

**Comment by Raportuy** [comment]
Yes, there is no more error, thanks.
