### ISSUE TITLE
7.22.91 redstone engine not rotating to mining well

### ISSUE THREAD

**Issue by Raghalin** [BuildCraft/BuildCraft#4360]
BuildCraft version:  7.22.91
Forge version:  forge-1.12.2-14.23.5.2807-universal.jar
Link to crash report or log: 
Singleplayer or multiplayer: multi
Steps to reproduce:  place mining well, place 5 redstone engines (all face up) unable to rotate to connect to mining well.  mining well will connect to redstone pipe.
Additional information:    I apologize if it's me and I missed a note about it not accepting redstone engine powers.  (side note loved the work since minecraft 1.7 thank you)

**Comment by AlexIIL** [comment]
Redstone engines only produce "low" power, so they cannot be used for anything other than wooden extraction pipes, the autoworkbench, and the pump. (Although the last two are temporary).

**Comment by Raghalin** [comment]
ok, thats what had be confused.  since the pump is still active.  ty for the fast responce
