### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by InThayne** [BuildCraft/BuildCraft#4369]
BuildCraft version: 7.99.21
Forge version: 14.23.5.2807
Link to crash report or log:  https://pastebin.com/7tzcUWtB
Singleplayer or multiplayer: neither- fail to load
Steps to reproduce: attempt load
Additional information: Removing BC 7.99.21 allows the pack to load
Re-adding BC 7.99.21 results in failure to load.

**Comment by InThayne** [comment]
It was an issue with the advanced tooltips being enabled in options.txt
Set to false and good to go!

**Comment by AlexIIL** [comment]
If it crashes then it's a bug. It doesn't matter what your configuration is.
However this is a duplicate of #4261, so I'll track it's progress there instead.
