### ISSUE TITLE
[Suggestion] Use Forge MultiPart instead facades

### ISSUE THREAD

**Issue by DjArt** [BuildCraft/BuildCraft#4370]
Benefits:

- Lower server / client load while using FMP & Buildcraft Silicon
- Compatible with other mods(like Red Project & Gregtech CE)
- Expanded number of facades

Disadvantages:

- Incompatibility with older versions

**Comment by bookerthegeek** [comment]
How would this work with the phased facades?

**Comment by DjArt** [comment]
Phased facade can be implemented as BC block(all panels are FMP single block). And they should act like other similar blocks(ex redstone bundle from Project Red): if it was connected with proper block(pipe with wire), did same things like now, else be in default state.

**Comment by LuigiHutch** [comment]
Benefits:
> Lower server / client load while using FMP & Buildcraft Silicon

You can just turn off BC facades in the config btw

>Compatible with other mods(like Red Project & Gregtech CE)

Do many other mods have support for it? I know a lot of other mods have moved away from it in the past to MCMP or their own solution. So why do you suggest FMP over MCMP?

> Expanded number of facades 

What blocks do not have BC facades which shouldhave/FMP has?

Disadvantages:
- Requires an external mod which does against BC's no dependencies rule
- Is written in SCALA so is very diffucult to integrate with
- Doesn't provide all the functionality that facades offer
- It has been known to be very buggy / have alot of performance issues in the past

**Comment by AlexIIL** [comment]
Not happening unfortunately - a while ago there were plans for a multipart API to be a part of forge, but that hasn't happened. Perhaps in the future though.
