### ISSUE TITLE
Quarry no longer accepting power

### ISSUE THREAD

**Issue by Solverbolt** [BuildCraft/BuildCraft#4382]
BuildCraft version:  7.99.21
Forge version: ForgeMultipart-1.12.2-2.6.1.81-universal.jar
Link to crash report or log: 
Singleplayer or multiplayer:  Multiplayer
Steps to reproduce:  Try connecting any kind of power
Additional information:  I have tried to connect any kind of power to the quarry, and it has the same issue as the Rock Crusher, it wont accept power from any source. 

this is from the FTB Ultimate Reloaded Modpack. From the way other mods have been brutally nerfed and/or doctored (good point in fact is Immersive Engineering, its missing 80% of the mod), the modpack developer did massive abusive changes that destroyed or made mods unusable, including buildcraft/railcraft. 

best way to resolve this, Deny FTB from being able to use any of the mods not developed solely by them until they sign an agreement stating that wont make drastic changes without prior approval and have tested to ensure that everything is working.  From what myself and quite a few others have found, this modpack developer did not even test it first before releasing it, and has made the statement a number of times that he is not responsible for any issues, despite having made extreme changes to the code that others wrote

**Comment by AlexIIL** [comment]
BuildCraft uses MJ now - what are you trying to power it with?

**Comment by Solverbolt** [comment]
I tried with MJ, RF, and whatever IE produces, As i know that quite a while back, Buildcraft quarry was made to be compatible with at RF. as such, even Buildcrafts own power generation was either nerfed to produce nothing, and in some cases, removed entirely, There is a ton of content missing from multiple mods in this pack, without reason to do so, yet he did not bother to update tooltips information, if he was just trying to make a more difficult mod pack.

**Comment by AlexIIL** [comment]
Ok, can you try using a buildcraft combustion engine with buildcraft oil inside?

**Comment by Solverbolt** [comment]
Nope. FTB modpack developer removed all the buildcraft engines from the mod. Did the same to Immersive Engineering. Only reason TE Dynamos are still there, is because removing them would create a crash conflict in the server.

**Comment by AlexIIL** [comment]
Ok, I think it makes more sense to track this on the modpack issue tracker (https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/146) as this isn't something I can change in buildcraft itself.

**Comment by Zarkazm** [comment]
> Nope. FTB modpack developer removed all the buildcraft engines from the mod.

This is incorrect.  I'm playing the same pack on version 1.4.0 and all BC engines are craftable.  I'm powering a Quarry with Combustion Engines with no trouble.

I think what you're not realizing is that the golden age of "every mod uses RF" is over.  Both BuildCraft and RailCraft are using their own power now.  RF can't be used to power these mods unless you convert the power in some way.  RF style cabling, such as Thermal Expansion's Fluxducts, won't connect to BC/RC machines.  It's not the modpack author "changing everything".

**Comment by ShatteredPixelz** [comment]
> > Nope. FTB modpack developer removed all the buildcraft engines from the mod.
> 
> This is incorrect. I'm playing the same pack on version 1.4.0 and all BC engines are craftable. I'm powering a Quarry with Combustion Engines with no trouble.
> 
> I think what you're not realizing is that the golden age of "every mod uses RF" is over. Both BuildCraft and RailCraft are using their own power now. RF can't be used to power these mods unless you convert the power in some way. RF style cabling, such as Thermal Expansion's Fluxducts, won't connect to BC/RC machines. It's not the modpack author "changing everything".

Fluxducts still work just the Universal cables do not work.
