### ISSUE TITLE
RF energy using (configurable by cfg)

### ISSUE THREAD

**Issue by KiBergMK** [BuildCraft/BuildCraft#4386]
BuildCraft version: 
Forge version: 
Link to crash report or log: 
Singleplayer or multiplayer: 
Steps to reproduce: 
Additional information:

**Comment by AlexIIL** [comment]
MJ (in it's current iteration) is new, and still in alpha status. In the future it should be more interesting and actually functionally different.

For now you can use a converter mod to get RF <-> MJ.
