### ISSUE TITLE
1.7.10 Forge Server Crash On Startup

### ISSUE THREAD

**Issue by APerson1738** [BuildCraft/BuildCraft#4388]
BuildCraft version: 7.1.23
Forge version: 1.7.10-10.13.4.1614-1.7.10 Server
Link to crash report or log: https://pastebin.com/R1dgF6ju
Singleplayer or multiplayer: Multiplayer, Singleplayer Not Tested.
Steps to reproduce: Run The Server, It Crashes On Startup.
Additional information: I Know It Isn't Just Buildcraft Erroring But Since BuildCraft Was Erroring First I Wasn't Sure If The Other Was Because Of BuildCraft.

Here Is My Server Folder: https://www.mediafire.com/file/a3a173deeetrewn/My_Server_Folder.zip/file

**Comment by AlexIIL** [comment]
One of your mods includes an older version of the buildcraft API (likely universal-electricity) - you'll need to either update it to a newer version or remove it in order to play with buildcraft. (Or remove buildcraft if you'd rather play with universal electricity.

**Comment by APerson1738** [comment]
Ok Thanks, I'll Try That Now.

**Comment by APerson1738** [comment]
I Did Some Research And Found Out That Universal Electricity Was Merged Into Another Mod I Had So I Removed Universal Electricity And Now It Works Fine. Thanks!
