### ISSUE TITLE
BC tanks and techreborn Cell

### ISSUE THREAD

**Issue by NocturnalScream** [BuildCraft/BuildCraft#4395]
BC tanks get fully emptied when trying to remove one bucked worth of fluid with a techreborn empty cell.

BuildCraft version: 7.99.23
Forge version: 14.23.5.2815
Link to crash report or log: 
Singleplayer or multiplayer: both
Steps to reproduce: take any liquid out of a bc tank with the techreborn empty cell
Additional information: Not 100% sure whether this is on bcs side or techreborn side, modmuss couldnt find the issue on his side.

**Comment by LuigiHutch** [comment]
https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/115

**Comment by estebes** [comment]
This is a bug on Tech Reborn side. Can be close here.
