### ISSUE TITLE
Copper is not Bronze

### ISSUE THREAD

**Issue by PestoPosta** [BuildCraft/BuildCraft#4397]
I presume this has already been brought up, but bronze tools are crafted using copper plates, and not bronze plates...
I also noticed that bronze items are repaired with bronze ingots, while being made with copper plates... me things there is something hinky going on here.

As I said, copper is not bronze. 

Cheers love this modpack and I really hope to see more of it.

BuildCraft version: 
Forge version: 
Link to crash report or log: 
Singleplayer or multiplayer: 
Steps to reproduce: 
Additional information:

**Comment by AEnterprise** [comment]
you are in the wrong place. this issue tracker is only bugs in the mod BuildCraft, not whatever modpack you are using, you want to report it to their issue tracker

**Comment by PestoPosta** [comment]
... my apologizes, I saw the bug report in sevtech and assumed it was for sevtech XD

Cheers have a good day.
