### ISSUE TITLE
About the old bug

### ISSUE THREAD

**Issue by Alex7896** [BuildCraft/BuildCraft#4398]
BuildCraft version: 3.7.2
Forge version: 7.8.1.738
Singleplayer
Minecraft 1.5.2
                 
Screenshots:
![2019-04-20_13 21 53](https://user-images.githubusercontent.com/42738314/56456185-7791aa00-6371-11e9-8689-25f48e2a5063.png)
![2019-04-20_13 22 02](https://user-images.githubusercontent.com/42738314/56456192-8aa47a00-6371-11e9-97dd-a67b8f8327ca.png)

**Comment by AEnterprise** [comment]
i'm sorry but minecraft 1.5.2 is no longer supported. currently only 1.12.2 and 1.7.10 are getting bugfixes

**Comment by Alex7896** [comment]
Yes, I know it, but is there a way to fix it?
