### ISSUE TITLE
Server crashes when player join after BC update

### ISSUE THREAD

**Issue by Roodypoo0123** [BuildCraft/BuildCraft#4399]
BuildCraft version: 7.99.24
Forge version: 1.12.2-14.23.5.2836
Link to crash report or log: https://cdn.discordapp.com/attachments/309218760814886922/569575670267772958/Crash-report__logs.zip
Singleplayer or multiplayer: Multiplayer
Steps to reproduce: Start server, join the game.
Additional information: The world loads fine and crashes when the player join. Save state includes lots of engines active, fluids/items in transit, all kind of pipes. I am a lone player on my own server, I cannot test if the issues occurs with someone else.

**Comment by SubliminallySublime** [comment]
BuildCraft version: 7.99.24
Forge version: 1.12.2-14.23.5.2836
Link to crash report or log: 
[crash-2019-04-21_16.50.31-server.txt](https://github.com/BuildCraft/BuildCraft/files/3101587/crash-2019-04-21_16.50.31-server.txt)
Singleplayer or multiplayer: Multiplayer
Steps to reproduce: Start server, join the game.
INITIAL steps to reproduce: Place quarry, wait for frame to finish. I don't know how long it took to crash but it was less than 5m.

I can reproduce this, although I have other mods installed and I can't get into my world to remove anything to test it. I am gonna try a few things and see if I can come back with more helpful info. Here's the log I have currently.

**Comment by AlexIIL** [comment]
Nope, the release 7.99.24 is critically broken server-side and I'll release 7.99.24.1 as a hotfix ASAP.

**Comment by AlexIIL** [comment]
Ok, 7.99.24.1 is building now and should be out on the website and curseforge shortly.

**Comment by AlexIIL** [comment]
It's fully uploaded an approved on curse - can you retry with it?

**Comment by SubliminallySublime** [comment]
It appears to be working for me. Thanks for the speedy fix.

**Comment by Roodypoo0123** [comment]
I can join the server normally with 24.1.

**Comment by AlexIIL** [comment]
Ok! Thanks for testing :)
