### ISSUE TITLE
Auto workbench make 64 items but uses just 1 item for the craft

### ISSUE THREAD

**Issue by totolevelo** [BuildCraft/BuildCraft#4400]
Hello,
when I try to make a circuit for example, the auto workbench is making 64 circuit for 6 cable, 2 redstones and 1 refined iron. is this normal ? I didn't find any subject about this.

![SharedScreenshot](https://user-images.githubusercontent.com/49959813/56686819-2701b000-66d5-11e9-87e5-537a88bf58e9.jpg)

Thanks

**Comment by totolevelo** [comment]
Tell me if you don't understand

**Comment by totolevelo** [comment]
It's ok i've just restarted the game... sorry for this useless topic ;)

**Comment by LuigiHutch** [comment]
So i'm guessing restarting your game sorted it? Good to know. Please actually use the issue template you deleted next time. Thanks!
