### ISSUE TITLE
Oil and Lily Pad

### ISSUE THREAD

**Issue by KollinsPlays** [BuildCraft/BuildCraft#4401]
BuildCraft version: 7.99.24
Forge version: 14.23.5.2836
Link to crash report or log: n/a
Singleplayer or multiplayer: SP (both?)
Steps to reproduce: In previous versions of BuildCraft (I tested in 1.4.7 FTB Ultimate, 1.6.4 FTB Monster and 1.7.10 Bevo Tech Pack) it was possible to place a vanilla lily pad on top of oil. This made it very easy to set up oil extraction machines at the top of a geyser. Vanilla Lily Pads can't be placed on oil in 1.12.2 BuildCraft 7.99 
Additional information:

**Comment by AlexIIL** [comment]
Lily pads are hardcoded to only accept water blocks or blocks with an icy material. As I can't change oil to either of these I can't really implement this.

(Also I don't think real lily pads would be sustained by crude oil?)
