### ISSUE TITLE
Portable Tank does not visually fill up

### ISSUE THREAD

**Issue by Cr33dC0d3r** [BuildCraft/BuildCraft#4404]
When using a portable tank and trying to fill it with some buckets of lava, the fluit level visually stops increasing after the first bucket, even though one is adding, e.g., four buckets in total. 

BuildCraft version: 7.99.24.1
Forge version: 1.12.1-14.23.5.2836
Link to crash report or log: 
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Place a "Portable Tank" and try to fill it with a lava bucket.
Additional information:

**Comment by LumberWizard** [comment]
Portable tanks are items from Thermal Expansion. Are you sure you didn't mean to submit it to [their issue tracker](https://github.com/CoFH/Feedback/issues)?

**Comment by Cr33dC0d3r** [comment]
Ah yeah - might be the better way. Got confused cause im using them with the pipes. My bad, thanks.
