### ISSUE TITLE
Buildcraft machines wont take eu

### ISSUE THREAD

**Issue by Smegly420** [BuildCraft/BuildCraft#4408]
Buildcraft machines will only take power from buildcraft engines and no other power source, I have tried lots of different cables and power transfer methods but none will work. Cables don't even join with the machines. Do buildcraft machines not take rf anymore or am I being extremely thick

BuildCraft version: 7.99.21
Forge version: 14.23.5.2808
Link to crash report or log: 
Singleplayer or multiplayer: both
Steps to reproduce: place any buildcraft item and try to attach cables to it

**Comment by AlexIIL** [comment]
As of BuildCraft only accepts MJ in 7.99.x  - not RF or EU. (Or any other power system)
