### ISSUE TITLE
AE2 can't put Facades on ME Glass Cable

### ISSUE THREAD

**Issue by hullekulleka** [BuildCraft/BuildCraft#4409]
Hello,
i just recognized, that the Facades aren't compatible with the AE2 Cables.
Could this be added in an future update? The blank Cables just look so ugly :'D

BuildCraft version: buildcraft-all-7.99.24.1
Forge version: --
Link to crash report or log: No Crash
Singleplayer or multiplayer: Multiplayer

**Comment by LumberWizard** [comment]
AE2 has its own facades. It is not BuildCraft's responsibility to cover objects added by other mods.

**Comment by zacharyhenry** [comment]
they have facades only  for buildcraft
and they have facades  only for ae2

**Comment by LuigiHutch** [comment]
AE2 used to allow placing BC facades on AE2 cables back in MC 1.7.10. Im assuming AE2 hasnt readded that functionality back in versions for MC 1.12.

Considering this functionality was originally found in AE2 natively, this issue would be better suited to the AE2 bug tracker unless they would prefer to keep the compat external.
