### ISSUE TITLE
[1.12.2] Crash in Loading Forge

### ISSUE THREAD

**Issue by PulseBeat02** [BuildCraft/BuildCraft#4412]
While I was loading my modpack, I encountered a crash with Buildcraft, mainly on the Buildcraft Lib.
Here are the details;

BuildCraft version: 7.99.24.1 
Forge version: 14.23.5.2838
Link to crash report or log: https://pastebin.com/1EtA5WYB

(Sorry I am in a rush I can't a very descriptive context)

**Comment by Daffehh** [comment]
This isn't a problem with BuildCraft; while the issue originates with BuildCraft, this crash has only started happening for me beginning with updating Real Filing Cabinet to 0.2.0.7. Try downgrading your version of RFC and see if the bug persists.

**Comment by HellFirePvP** [comment]
https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/enchantment/amulet/AmuletHolderCapability.java#L73

Capability passed in is/was null.

**Comment by bafomdad** [comment]
Hmm, I am indeed missing the NonNull annotations on the capability provider calls.

Not entirely sure if that's the whole problem..there are two other older items that use the same capability that passed through init fine. The only thing different about the auto folder that was added in this version is they are present in the creative tab.

**Comment by AEnterprise** [comment]
BC uses the creative tab to find the items, so it just didn't crash before as BC didn't know about the items existing

**Comment by AEnterprise** [comment]
should have been fixed in realfilingcabinets
