### ISSUE TITLE
Redstone engine works only when other redstone engine is on top of it. Minecraft 1.12.2

### ISSUE THREAD

**Issue by Sairus314** [BuildCraft/BuildCraft#4423]
BuildCraft version: buildcraft-all-7.99.24.1
Forge version:  1.12.2-14.23.5.2838
Singleplayer or multiplayer:  Singleplayer
Steps to reproduce: Single redstone engine is not working, redstone engine with other redstone engine on top of it is working, not works if place other blocks.

Also, redstone engine can`t be moved with workbench. 

![Base Profile Screenshot 2019 06 09 - 18 32 38 05](https://user-images.githubusercontent.com/23504691/59160268-0b1b6780-8ae5-11e9-8c03-7f7ceb340d1b.png)

**Comment by AlexIIL** [comment]
Redstone engines must be facing a valid receiver in order to emit power or pump normally (so a wooden item or fluid pipe, or an autoworkbench or pump).
