### ISSUE TITLE
Incompatibility with Mekanism AGAIN!

### ISSUE THREAD

**Issue by IDEDARY** [BuildCraft/BuildCraft#4426]
BuildCraft version: 1.12.2 - 7.99.24.1 (Newest 12.6.2019)
Forge version: 1.12.2 - 14.23.5.2837
Link to crash report or log: is it not crashing
Singleplayer or multiplayer: i think both
Steps to reproduce: what?
Additional information: Cables from Mekanism dont connect to BC blocks,it is not issue from mekanism mod, cause mekanism is compatible with thermal expansion, so there is bigger chance problem is in BC. Thanks.

PS. If anybody know any mod that makes Mekanism, BC, Industrial forgegoing, thermal expansion, extreme reactors atc. using ONLY redstone flux let me know pls. Im making super modpack and this issue i want to be solved!!!

**Comment by IDEDARY** [comment]
And if it is in config file, how make everything compatible, let me know.

**Comment by AEnterprise** [comment]
this is intentionally, BuildCraft uses MJ instead of FE now, you will need engines or a converter mod to power BuildCraft machines
