### ISSUE TITLE
Buildcraft requires minecraft 1.12.2

### ISSUE THREAD

**Issue by evilporkmaster** [BuildCraft/BuildCraft#4428]
im trying to install buildcraft but i keep getting the message buildcraft requires minecraft 1.12.2
![buildcraft](https://user-images.githubusercontent.com/51806792/59476936-96179d00-8e18-11e9-86ed-44aa89214d1c.png)

**Comment by AEnterprise** [comment]
That is because you have 1.12 but buildcraft requires 1.12.2, you should just be able to update MC to 1.12.2 as all mods should have an compatible update out (or even just work as it's a small bump)
