### ISSUE TITLE
Crash at startup java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Chupp4-Jo3** [BuildCraft/BuildCraft#4433]
I have no idea if this even is BC but it references buildcraft.lib.tile.TileBC_Neptune in the crash.

https://pastebin.com/a6t7ApJW

forge: 14.23.5.2838
BC: 7.99.24.1

**Comment by AlexIIL** [comment]
I'm not quite sure what could have caused that, but it should probably provide more information about what caused that to go wrong.

**Comment by Chupp4-Jo3** [comment]
It was after updating a few mods in a (rather large) modpack. Unfortunately the Twitch launcher doesn't have a 'sort by release date' or 'sort by most recently updated' mode so I'll have to go through manually and see what was changed. It's late for my so I'll check tomorrow!

**Comment by Chupp4-Jo3** [comment]
Okay, so according to the mods folder since the 24th I've added:

EnchantmentDescriptions-1.12.2-1.1.15
industrialcraft-2-2.8.164-ex112
jei_1.12.2-4.15.0.283
JustEnoughResources-1.12.2-0.9.2.60
ThaumicAdditions-1.12.2-18r
thaumicbases-3.3.350.6r
Erebus-1.0.30
tinkersdefense-1.4.2.28
UnlimitedChiselWorks-0.2.2
BiomesOPlenty-1.12.2-7.0.1.2441-universal
Bookshelf-1.12.2-2.3.585
EverlastingAbilities-1.12.2-1.5.1
EvilCraft-1.12.2-0.10.76
LagGoggles-FAT-1.12.2-4.4
Quark-r1.5-164
AutoRegLib-1.3-31
FTBLib-5.4.3.120
FTBUtilities-5.4.0.99

All of these are updates as opposed to new mods added (I did remove BoP then realised that removing it changes the block ID's for half the items in the game changing cursed earth to blazing pyrotheum and such ;_;) but I don't know how this could cause this issue. If there's more info you need (logs and such) let me know!

**Comment by AlexIIL** [comment]
Ok thanks for that, unfortunately buildcraft itself doesn't log enough information to see what's really going on so I think I'll need to add some to a new version of buildcraft.

**Comment by AlexIIL** [comment]
Can you retry with 7.99.24.3-pre1 from the [tests page](https://mod-buildcraft.com/pages/tests.html)?

**Comment by Chupp4-Jo3** [comment]
Seems to work now. Still got some issues but seem unrelated to BC.

Thanks for the quick fix!
