### ISSUE TITLE
journeymap not working with ur mod

### ISSUE THREAD

**Issue by zacharyhenry** [BuildCraft/BuildCraft#4436]
BuildCraft version: 7.99.24.1-all
Forge version: 14.23.5.2838
Link to crash report or log: 
Singleplayer or multiplayer: singleplayer
Steps to reproduce: turned off ConnectedTexturesMod and Buildcraft and map started working journeymap is looking into it 
Additional information: 
other versions of journeymap is 1.12.2-5.5.5b8
...................

buildcraft 7.99.24.1-all
same
same
buildcraft items make journeymap full screen not work(work around disable buildcraft)
journeymap 1.12.2-5.5.5.b7

**Comment by AEnterprise** [comment]
duplicate of #4199
