### ISSUE TITLE
Facades Not Working

### ISSUE THREAD

**Issue by vizthex123** [BuildCraft/BuildCraft#4437]
I can't place any pipe facades form BuildCraft onto Logistics Pipes blocks, nor can I do the same with Forge Microblocks covers.

BuildCraft version: 7.99.24.1
Forge version: 14.23.5.2838
Link to crash report or log: N/A
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: 
Additional information:

**Comment by AEnterprise** [comment]
this is not a buildcraft issue but rather with logistics pipes, they need to add support for this to make it work

**Comment by vizthex123** [comment]
Ah ok, was thinking so but wasn't sure.
