### ISSUE TITLE
Engines aren't working correctly

### ISSUE THREAD

**Issue by AnnaTheKitty** [BuildCraft/BuildCraft#4438]
**BuildCraft version**: Buildcraft-all-7.99.24.1
**Forge version**: Forge-14.23.5.2838
**Link to crash report or log**:  http://www.mediafire.com/file/6oqxsg2ii7pphag/buildcraft.rar/file
**Singleplayer or multiplayer**:  Possibly both, only tried Singleplayer 
**Steps to reproduce**: Just place a engine
**Additional information/Rant**: I got Buildcraft to make factories and also to use OpenComputers, which turns out you can use the engines to give the computers power, surprise! The engines didn't work, no matter what you do, you aren't able to change the direction of it, and barely any of the pipes actually change the directions. Even when I try to put it underneath the computer and run it with a torch, it doesn't do anything. Btw anything that I do to try to give the daum thing power doesn't work.  I tried using the gear tool still doesn't do anything either... So... yeah :/ Also! You know those particles that appear when you break a block? When you break a engine, it shows missing textures. 

**Some pictures**: ![2019-07-12_23 54 26](https://user-images.githubusercontent.com/48998087/61166721-7ef3ca00-a500-11e9-87b7-83d0bf6be59a.png)

![2019-07-13_00 14 08](https://user-images.githubusercontent.com/48998087/61166870-37227200-a503-11e9-8dee-1662c41be69d.png)

**Comment by AEnterprise** [comment]
several things are going on here

1) you are placing item transport pipes, those do not transfer MJ, only items. you need to use a wooden kinesis pipe to extract power and then other kinesis pipes to transport the power
2) redstone engines are not powerful enough to provide power to wooden kinesis pipes and can only power blocks directly
3) BC is using MJ, not RF or FE, as such it can not power other mods their machines like that computer, you need a converter mod for that

**Comment by AnnaTheKitty** [comment]
> several things are going on here
> 
> 1. you are placing item transport pipes, those do not transfer MJ, only items. you need to use a wooden kinesis pipe to extract power and then other kinesis pipes to transport the power
> 2. redstone engines are not powerful enough to provide power to wooden kinesis pipes and can only power blocks directly
> 3. BC is using MJ, not RF or FE, as such it can not power other mods their machines like that computer, you need a converter mod for that

Guess the old videos on buildcraft were wrong then :/

**Comment by AlexIIL** [comment]
> Guess the old videos on buildcraft were wrong then :/

*Technically* those videos are correct for the versions of buildcraft that they were made for, but in 1.12 buildcraft changed to use a different power system.
