### ISSUE TITLE
Pumping fuel and ore into a furnace at the same time causes the furnace to lose/forget its current inventory

### ISSUE THREAD

**Issue by RedFox134** [BuildCraft/BuildCraft#4439]
1. BuildCraft version: 7.99.24.1
2. Forge version: 1.12.2.14.23.5.2824
3. Link to crash report or log: Not crashing just not performing as expected in game.  Doesn't appear to be any info on the missing items in the log either as it only shows me joining the server prior the items disappearing.
4. Singleplayer or multiplayer: Multiplayer
5. Steps to reproduce: Have two items pumped into a furnace at the same time (ore, and coal) using transportation pipes.
6. Additional information: When adding fuel and the item to be smelted to a furnace via cobble stone transport pipes and wooden transport pipes powered by redstone engines at the same time the furnace will forget it's current inventory and only show one of the last items to be added.

e.g If you add 4 coal and 4 iron ore at the same time while already having 24 iron ore smelting and 23 coal piece in the furnace, any smelted iron ingots and coal will disappear and only 4 iron ore would show in the furnace.  Furnace shows as if it is still trying to smelt the resources even though they are now missing.

**Note**
Using mod as part of Tekxit 3 v0.92.  Tested in single player and multiplayer.  Does not appear to be an issue in single player.

**Comment by RedFox134** [comment]
Upon further testing to try to recreate the issue it seems to be random.  Will need to test more to see if I can consistently get the bug to reproduce itself.  For now it appears to be working just fine despite experiencing the issue multiple times over the past day or two.  Since this only happens in multiplayer I wondering if it isn't just something to do with how the server handles communication between the client and server.

**Comment by RedFox134** [comment]
Realizing this might be similar to open issue [1828](https://github.com/Railcraft/Railcraft/issues/1828).  Although I do not have any blast furnaces/coke ovens (that I know of) in my world.  In addition I'm not kicked out of the GUI when working in the furnace.  Just coming back to it later to check sometimes results in what was in the furnace no longer being inside.

**Comment by AEnterprise** [comment]
this is not a buildcraft bug, all pipes do is ask the inventory "i have x of this item, can you accept this?", if it can then it tells the block "here is x of this item, accept it"

at either point the block can say BC that it can not or will not accept the item, handling items that don't fit in the inventory is a job for the block accepting the items
