### ISSUE TITLE
Bug 1.11.2

### ISSUE THREAD

**Issue by ScarLegendary** [BuildCraft/BuildCraft#4441]
El motor de redstone no sé los demás, no se colocan de lado, solo hacia arriba por lo que no permite activar ninguna máquina

BuildCraft version: 7.99.8.1
Forge version: 13.20.1.2386
Link to crash report or log: 
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: 
Additional information:

**Comment by AlexIIL** [comment]
#### English:

> The redstone engine do not know the others, they are not placed sideways, only upwards so it does not allow to activate any machine

The redstone engine is not powerful enough for most machines, instead you'll need either a stirling engine or a combustion engine, and the correct type of fuel

#### Spanish:

> El motor de Redstone no conoce a los demás, no se colocan de lado, solo hacia arriba por lo que no permite activar ninguna máquina.

El motor redstone no es lo suficientemente potente para la mayoría de las máquinas, en lugar de eso, necesitará un motor stirling o un motor de combustión, y el tipo de combustible correcto.

*(Unfortunately this has gone through google translate as I don't speak spanish)*
