### ISSUE TITLE
Gate Intentory empty with IC2 machine upgrade

### ISSUE THREAD

**Issue by stewardqq** [BuildCraft/BuildCraft#4442]
when IC2 machine have upgrade, Inventory Empty will be false

BuildCraft version: 7.99.24.1
Forge version: 1.12.2-14.23.5.2838
Link to crash report or log: none
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: 
Additional information: 
![2019-07-21_15 59 26](https://user-images.githubusercontent.com/19276572/61588606-2cd23900-abd1-11e9-9112-3443921be241.png)
![2019-07-21_16 06 53](https://user-images.githubusercontent.com/19276572/61588626-93efed80-abd1-11e9-9cb8-1477c856caf8.png)

**Comment by AEnterprise** [comment]
This is not a bug, there are items in the machine and the block returns this to the gate when asked about it's inventory status

IC2 needs to provide their own trigger that ignores those slots or not expose those slots
