### ISSUE TITLE
1.12.2 mod conflict

### ISSUE THREAD

**Issue by Leghtin** [BuildCraft/BuildCraft#4443]
BuildCraft version: buildcraft-all-7.99.24.1
Forge version: 14.23.5.2838
Link to crash report or log: 
https://pastebin.com/07YvX7ky
Singleplayer or multiplayer: singleplayer
Steps to reproduce: Just start minecraft with some mods
Additional information: 
When forge loading at step 5, loading buildcraft, game was crashed. When I just use buildcraft, minecraft will start as normal and I can play BC. But when I get other mod, it can't start.

**Comment by AEnterprise** [comment]
problem with tofucraft crashing on some invalid value (they are probably not clamping it), though bc could probably hande this a bit better as well

**Comment by Leghtin** [comment]
> problem with tofucraft crashing on some invalid value (they are probably not clamping it), though bc could probably hande this a bit better as well

THANKS! I will delete tofucraft and enjoy my game

**Comment by AlexIIL** [comment]
This is likely related to https://github.com/0999312/TofuCraftReload/issues/38, although I'm not sure exactly what could be done to fix this on TofuCraftReloaded's end. (Although we can't really do much about it here).

**Comment by ekultails** [comment]
@Leghtin As an alternative to TofuCraft, I highly recommend [Pam's HarvestCraft](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft). You can grow soybeans and use it to create meat and milk alternatives for any recipe in the game. It also adds a lot more to farming and food options.

**Comment by Prunoideae** [comment]
Seems it was somehow fixed on our side. This issue could be closed as the crash is neither persistent nor reproducible in our latest running environment.

**Comment by AlexIIL** [comment]
Ok, thanks :)
