### ISSUE TITLE
Crashing while loading v7.99.24.1

### ISSUE THREAD

**Issue by ryan1161** [BuildCraft/BuildCraft#4451]
BuildCraft version: 7.99.24.1
Forge version: 1.12.2-14.23.5.2838
Link to crash report or log: https://pastebin.com/5nuZr8bw
Singleplayer
Additional information:  I can't find a solution online or in the issue related to my crash needing help narrowing down to a couple of mods that could cause this.

**Comment by ryan1161** [comment]
Found the mod causing my crash MFFS-2.5.0.jar going to post on there issue form as well but seems to be conflict between BuildCraft Library and MFFS mod on 1.12.2

**Comment by AlexIIL** [comment]
This is probably due to MFFS shipping an older version of the buildcraft API.

What version of minecraft is MFFS 2.5.0 for? I can't seem to find a link to it?

**Comment by ryan1161** [comment]
OMG I'm so stupid thats for 1.6.2 minecraft found the fix MFFS-1.12.2-4.0.1.0_1.12_cc3a5aa.jar is for 1.12.2
