### ISSUE TITLE
Game crashing while right clicking the sterling engine

### ISSUE THREAD

**Issue by Ohu2115** [BuildCraft/BuildCraft#4452]
BuildCraft version: 7.99.24.1
Forge version: 14.23.5.2824
Link to crash report or log: https://paste.dimdev.org/gihakigemo.mccrash
Singleplayer or multiplayer: multiplayer
Steps to reproduce: just right click the sterling engine
Additional information: game just crashes and brings you to menu, there is no optifine in the mod pack

**Comment by AEnterprise** [comment]
duplicate of #4447
