### ISSUE TITLE
Lasers not working

### ISSUE THREAD

**Issue by ComaGreeny** [BuildCraft/BuildCraft#4454]
i am playing with friends on minecraft version 1.12.2 lan on t launcher with a mod tekkit end and if i make a laser with an assembly table the laser wont shoot even if i power it with a combustion engine with pipes or placing near it i tried going into the files of the modpack and reinstalling buildcraft all but it still didnt work

**Comment by AlexIIL** [comment]
Can you take a screenshot of the laser and assembly table? Also, does the assembly table have a valid recipe that needs to be crafted?

**Comment by ComaGreeny** [comment]
https://cdn.discordapp.com/attachments/434334892973621250/608243780054941706/unknown.png
https://cdn.discordapp.com/attachments/434334892973621250/608244186843578388/unknown.png
https://cdn.discordapp.com/attachments/434334892973621250/608244238584643604/unknown.png

**Comment by AlexIIL** [comment]
Oh, ok. You need to point the laser near to the top of the table, like this: 
![image](https://user-images.githubusercontent.com/3751138/62552303-5348d300-b865-11e9-876e-7ac6f67051a6.png)

**Comment by ComaGreeny** [comment]
OMG THANK YOU SO MUCH I DONT HAVE TO STOP PLAYING MY PLAYTHROUGH WITH MY FRIEND tbh they should just make it work on the ground as well
