### ISSUE TITLE
1.12.2 Buildcraftlib Crash (MultiMC)

### ISSUE THREAD

**Issue by Imbadlol** [BuildCraft/BuildCraft#4457]
Hey guys!

   Recently I've started a custom modpack with some friends (first one I've done so far) and for some reason Builcraftlib is **loaded** , **constructed** and **errored** (LCE status). If i scroll down a bit I also get the message:

" _net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Lib (buildcraftlib)
Caused by: java.lang.NoSuchFieldError: ON_ "

  I tried to see if it overlaps with another mod but I'm kinda clueless to be fair...
Here's the full error:  https://pastebin.com/KhALHp1c

 To mention, forge version that I'm using is (14.23.5.2836), Buildcraft version (buildcraft-all-7.99.24.2), Minecraft version (1.12.2).

 Thanks for the help!

**Comment by AlexIIL** [comment]
This is caused by one of your mods including an older version of the `buildcraft/api/tiles/IControllable$Mode.class` files, which is being loaded instead of the newer version. Unfortunately I'm not sure how you can actually find this out, other than opening each jar file in turn to see if it contains that file.

**Comment by Imbadlol** [comment]
Hey, thanks for the response!
From what I understand, should I uninstall buildcraft and install every jar file that make buildcraft as a whole? (api/builders/compat/etc...)

**Comment by Imbadlol** [comment]
Oh wait lol, I'm dumb, now I understand xD

**Comment by Imbadlol** [comment]
@AlexIIL issue is fixed, problem was from Engineer's Toolbox mod.
Thanks for reaching out!
