### ISSUE TITLE
Consistent Crash with same or similar error

### ISSUE THREAD

**Issue by Americannoli** [BuildCraft/BuildCraft#4468]
Crash Report or Log: https://gist.github.com/Americannoli/ffd47b1124c89460f22231518aceedc2

Always crashes me and others randomly. 

[BuildCraft]: [lib.tile] Unknown owner (null) for class buildcraft.transport.tile.TilePipeHolder at BlockPos{x=-147, y=74, z=317} when reading from NBT

Take a look at the log it shall help. Thank you.

Also lemme know if I can fix it!

**Comment by AEnterprise** [comment]
the unknown owner thing is just a warning though, not something that crashes you, could you provide the crashreport itself?

**Comment by AlexIIL** [comment]
> [Client thread/WARN] [BuildCraft]: [lib.tile] Unknown owner (null) for class buildcraft.transport.tile.TilePipeHolder at BlockPos{x=-134, y=77, z=320} when reading from NBT

Sorry I missed this at first: that error should normally only be shown on the *server* thread, not the client thread! So it turns out this is is logging completely uselessly.

**Comment by AlexIIL** [comment]
This has been fixed and released as part of [7.99.24.3](https://mod-buildcraft.com/buildcraft-799243.html)
