### ISSUE TITLE
Oil gen in dimensions config typo

### ISSUE THREAD

**Issue by xJon** [BuildCraft/BuildCraft#4469]
**Please complete the following information:**
 - Forge Version: 1.12.2-14.23.5.2838
 - BuildCraft Version: 7.99.24.2

**To Reproduce**
1. Generate config file

The config file of the mod regarding oil gen in dimensions looks like this:
```
        # Dimension ID's (e.g. '-1' for the nether,'1' for the end) of dimensions that should never generate oil.
        I:excludedDimensions <
            -1
            1
         >

        # If true then the excluded biomes list will be treated as a blacklist, otherwise it will be treated as a whitelist.
        B:excludedDimensionsIsBlacklist=true
```
There is a typo in the second config, as it should exclude dimensions and not biomes, but also maybe this could be written better? Because even if the second config is set to false the first config is still described as a blacklist, which could be confusing.

**Comment by AlexIIL** [comment]
Ok, this should be implemented in [7.99.24.4](https://mod-buildcraft.com/buildcraft-799244.html).
