### ISSUE TITLE
Minecraft crash by pipes and wires for them

### ISSUE THREAD

**Issue by maximilianrob** [BuildCraft/BuildCraft#4471]
Good day,

I got a crash, when tried remove the pipe wire from the pipe (crash the same for every pipe)

And i found one thing, after restart the wire dissappear from pipe

Crash log: https://gist.github.com/maximilianrob/dd4d54879a8c4e59db554d440d5f9443

**Comment by maximilianrob** [comment]
Additional log without OptiFine and any mods: https://gist.github.com/maximilianrob/cadbd719bac6a5b6bc60c57d389f872e

**Comment by AlexIIL** [comment]
Ok this should be fixed in [7.99.24.3-pre1](https://mod-buildcraft.com/releases/testing/BuildCraft/7.99.24.3-pre1/buildcraft-all-7.99.24.3-pre1.jar), can you test it? (From the tests page: https://mod-buildcraft.com/pages/tests.html)

**Comment by maximilianrob** [comment]
All is fine now

**Comment by AlexIIL** [comment]
Thanks!

**Comment by AlexIIL** [comment]
This has been released properly in [7.99.24.3](https://mod-buildcraft.com/buildcraft-799243.html)
