### ISSUE TITLE
I would like to publish this mod on Minecraft China edition and Request authorization.

### ISSUE THREAD

**Issue by NETEDGW** [BuildCraft/BuildCraft#4479]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AlexIIL** [comment]
I cannot provide any permissions or authorization to you other than what is in the license files (1.7.10 versions and below: https://github.com/BuildCraft/BuildCraft/blob/8.0.x/LICENSE, 1.12.2 versions: https://github.com/BuildCraft/BuildCraft/blob/8.0.x/LICENSE-NEW, API: https://github.com/BuildCraft/BuildCraft/blob/7.1.x/LICENSE.API)

**Comment by asiekierka** [comment]
We have already been approached regarding Minecraft China Edition and could not reach a satisfactory solution. If the licensing documents as present do not grant sufficient permissions, we cannot help you further.
