### ISSUE TITLE
world crash

### ISSUE THREAD

**Issue by zacharyhenry** [BuildCraft/BuildCraft#4480]
steps to what happened

load game-works fine
start game- get to play about 5-10 mintues before it freezes and it goes to minecraft lau

cher with crash.log

1.12.2 
14.23.5.2838 
7.99.24.2- crashes my world
[crash-2019-08-30_23.06.43-server.txt](https://github.com/BuildCraft/BuildCraft/files/3562113/crash-2019-08-30_23.06.43-server.txt)

**Comment by AlexIIL** [comment]
Just to check: is the `spring` block disabled in the buildcraft config file? (Main Menu > Mods > BuildCraft > Config > Blocks)

**Comment by zacharyhenry** [comment]
ill take a look and get back to u
