### ISSUE TITLE
What is the best way to power a quarry?

### ISSUE THREAD

**Issue by theradman221** [BuildCraft/BuildCraft#4486]
I am trying to power a quarry using Immersive engineering for power and power transport and then buildcraft for the mining (obviously). I have everything setup, flick the switch and nothing happens. So after some digging I find out that I need MJ. What is the best way to either convert RF/IF to MJ or just generate MJ? I'm playing with the FTB revelation pack v.3.2.0 (minecraft 1.12.2, buildcraft 7.99.24.2 ) and there don't seem to be any conversion mods, at least none that are found easily.  

Ideally my solution to this problem would be that buildcraft machines would just use any power system plugged into them. I know this is probably not going to happen so my other solution would be that buildcraft would include it's own power converter block since a lot of mods just don't seem to have converters. I would also like to know why buildcraft went to MJ since most the industrial themed mods I use still use RF. Just something I've been wondering.

I have considered just using sterling or combustion engines to power the quarry, but what is the point of building a stupid power system in the first place if it only powers one machine? I have also just considered giving up on buildcraft entirely as a lot of the mods I like using aren't in the pack and it would be easier to drop it entirely than to build a whole new power system just for the quarries. 

**Additional context**
Example of the current setup I would like to work, note that I wouldn't mind replacing the cable system with another if it meant it worked, I just want to be able to use the waterwheel to power my machines.
![example](https://user-images.githubusercontent.com/25518168/65375435-e0e45480-dc52-11e9-860e-84db623a8d87.PNG)

**Comment by AlexIIL** [comment]
You can't use anything that doesn't produce MJ to power buildcraft machines. This is intentional - from my perspective power generation shouldn't ever be simple and easy to automate, which most RF-producing mods seem to do. (Hence why buildcraft was moved away from RF and back to MJ - although some mods (like forestry) add other ways of generating MJ).

(There are power convertor mods available however, so if you really want to you can investigate them separately, although I'm not helping you find them).

**Comment by theradman221** [comment]
ok thanks, I can understand why you would do it that way now that you explained your reasoning. I'll have to look into setting up oil, is there every any plans to add any type of converter block or is that always going to be done by outside mods? (I'm talking months to years in the future) Thanks for getting back to me so fast!

**Comment by AlexIIL** [comment]
Convertor blocks are always going to be done by outside mods - fortunately for you a lot of other modders don't share my opinion, so they will always exist :p
