### ISSUE TITLE
[1.12.2] Console Spam awarding advancement

### ISSUE THREAD

**Issue by VirulentSlayer** [BuildCraft/BuildCraft#4490]
Hello I am running a server with multiple mods, there is now a persistent log showing in the server console. 10 logs per second on average, "[13:09:57] [Server thread/INFO] [BuildCraft]: Awarding advancement to falnen! Or we would do, if this was 1.12..."

 I can only assume my player gained an certain advancement which buildcraft-all-7.99.24.2 doesn't like.

 My latest log is in the pastebin link, there isn't any crash report. https://pastebin.com/eAqwaK6D

 The log isn't showing which advancements were achieved in buildcraft, the last earned achievement in reverse chronological logs is an advancement from the twilight forest; [Trophied Champion]

 I will list the server mods in use, bear in mind that my player was advancing through many achievements at the time the 10 logs a second bug started. I can post advancement data for the player if required.
 Can I suggest that a new cfg line which could switch advancement logging in the console on or off.

I actually have a 48.1mb Log which is just spam from buildcraft. 

github wouldn't let me add it to the issue tracker 👍 

My mods are listed in this link
https://pastebin.com/gJxE2yn3

**Comment by VirulentSlayer** [comment]
notepad tells me the 48.1mb file is only 447809 lines long, the log started at 00:00:01 and finished at only 13:09:57, The player did move wrongly around 16 minutes before the logging started, but I assume it is unrelated to the above article.

**Comment by VirulentSlayer** [comment]
Removing SERVER/world/advancement files does not fix this problem, Running the server as it is could be causing lag, CPU usage at idle is 3.1%-33% averaging around  11% over 60 seconds. which is unusual for my 4790K@4GHz. It is certainly making the server logs much larger, which begs the question should I bother running this or revert to a backup.

**Comment by VirulentSlayer** [comment]
removing SERVER/world/playerdata files didn't stop buildcraft from trying to spam my console. It;s the same message, my forge version is forge-1.12.2-14.23.5.2847

**Comment by AlexIIL** [comment]
This is caused by a pump nearly finishing pumping a sufficiently large oil well - and for some reason I never updated the code from 1.11 to actually award the advancement.

Either way you can either avoid this by finding the pump that is causing this (and then replacing the "oil spring" block at the bottom with normal bedrock) or just turning off any pumps that are nearly finished pumping a large oil well. (Or waiting a few days for me to update it)

**Comment by AlexIIL** [comment]
Ok, this should now be fixed properly in [7.99.23.3-pre.3](https://mod-buildcraft.com/pages/tests.html) (on the tests website, it's not on curseforge yet as I'll release it properly tomorrow).

**Comment by VirulentSlayer** [comment]
Excellent work AxelllL much appreciated. I will have players made aware if this *should*  happen again :P Thank you

**Comment by AlexIIL** [comment]
This has been released properly in [7.99.24.3](https://mod-buildcraft.com/buildcraft-799243.html).
