### ISSUE TITLE
Oil Refinery does not appear as craftable object

### ISSUE THREAD

**Issue by ryamamoton** [BuildCraft/BuildCraft#4491]
I can't craft the oil refinery, it does not appear as a craftable object, using minecraft 1.12.2 forge 14.23.5.2838
I'm currently using the following mods
![img2](https://user-images.githubusercontent.com/11365940/66093305-6a4e2d80-e555-11e9-8856-49e4d5545c15.PNG)
![img3](https://user-images.githubusercontent.com/11365940/66093306-6ae6c400-e555-11e9-8345-c51d057c742e.PNG)
![img1](https://user-images.githubusercontent.com/11365940/66093307-6ae6c400-e555-11e9-8926-316c7a8d9bcc.PNG)

**Comment by AEnterprise** [comment]
works fine with just BC so one of your other mods is probably removing the crafting recipe, you'll need to find what mod that is and talk to the author of that mod

**Comment by AlexIIL** [comment]
Also, do you mean the "distiller" when you say "oil refinery"? (In 1.12.2 buildcraft has a new processing system for oil, which is a bit different to before).

**Comment by ryamamoton** [comment]
Thanks to all for the anwers
