### ISSUE TITLE
Interacting with an active quarry by piston results in a catastrophic crash.

### ISSUE THREAD

**Issue by NicTink** [BuildCraft/BuildCraft#4496]
attempting to push or pull an active quarry results in a catastrophic crash of the client/server.

**Comment by AlexIIL** [comment]
Can you upload the crash report (of the server if it's running on a server, or the client if it's a singleplayer world)?

**Comment by NicTink** [comment]
issue resolved. It was caused by another mod that enabled pistons to act on blocks they shouldn't interact with.

My apologies

**Comment by AlexIIL** [comment]
I'm still interested in the crash though, as there *might* be something we can do to prevent if from crashing? (Although this really depends on what the other mod does to pistons).
