### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by RTT-34** [BuildCraft/BuildCraft#4499]
I have been playing a Minecraft 1.12.2 world for about a week now, and i have the Buildcraft mod installed. The mod has been working fine up until now, Everytime i start my game and get into my world, Minecraft crashes a couple seconds later and provides the crash report. I have no clue what it means: 

Time: 2019-10-19 20:19:53 BST
Description: Rendering ingredient

java.lang.ArrayIndexOutOfBoundsException: -587316
    at net.minecraft.world.ColorizerGrass.getGrassColor(SourceFile:18)
    at com.matez.wildnature.init.WildNatureBlockColors$7.colorMultiplier(WildNatureBlockColors.java:86)
    at net.minecraft.client.renderer.color.BlockColors.getColor(BlockColors.java:173)
    at buildcraft.silicon.client.FacadeItemColours.colorMultiplier(FacadeItemColours.java:20)
    at net.minecraft.client.renderer.color.ItemColors.colorMultiplier(ItemColors.java:148)
    at net.minecraft.client.renderer.RenderItem.renderQuads(RenderItem.java:357)
    at net.minecraft.client.renderer.RenderItem.renderModel(RenderItem.java:171)
    at net.minecraft.client.renderer.RenderItem.renderModel(RenderItem.java:136)
    at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:63)
    at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:32)
    at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:163)
    at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99)
    at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97)
    at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161)
    at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_555_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.client.gui.GuiScreen.drawDefaultBackground(GuiScreen.java:575)
    at net.minecraft.client.gui.inventory.GuiInventory.drawScreen(SourceFile:66)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at sun.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1456)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Ingredient being rendered --
  Mod Name: BuildCraft Silicon
  Registry Name: buildcraftsilicon:plug_facade
  Display Name: Facade: Overgrown Stone
  String Name: 1xitem.Facade@0

-- JEI render details --
  Unique Id (for Blacklist): buildcraftsilicon:plug_facade:0
  Ingredient Type: class net.minecraft.item.ItemStack
  Error Info: 1xitem.Facade@0 buildcraftsilicon:plug_facade nbt:{facade:{isHollow:0b,states:[{state:{Properties:{snowy:"false"},Name:"wildnature:overgrown_stone"}}]}}
  Filter Text: ov
  Edit Mode Enabled: false
  Debug Mode Enabled: false

-- Screen render details --
  Screen name: net.minecraft.client.gui.inventory.GuiInventory
  Mouse location: Scaled: (240, 134). Absolute: (960, 540)
  Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4

-- Affected level --
  Level name: MpServer
  All players: 1 total; [GCEntityClientPlayerMP['__Ross___'/0, l='MpServer', x=27.67, y=64.00, z=732.61]]
  Chunk stats: MultiplayerChunkCache: 121, 121
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (80,64,252), Chunk: (at 0,4,12 in 5,15; contains blocks 80,0,240 to 95,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 624041 game time, 330700 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 41 total; [EntitySpider['Spider'/192, l='MpServer', x=-29.50, y=66.00, z=714.50], GCEntityClientPlayerMP['__Ross___'/0, l='MpServer', x=27.67, y=64.00, z=732.61], EntitySpider['Spider'/324, l='MpServer', x=-33.50, y=67.00, z=722.50], EntityCreeper['Creeper'/389, l='MpServer', x=76.50, y=70.00, z=784.04], EntitySkeleton['Skeleton'/200, l='MpServer', x=-2.50, y=63.00, z=791.50], EntitySkeleton['Skeleton'/264, l='MpServer', x=47.50, y=24.00, z=690.50], EntityZombie['Zombie'/137, l='MpServer', x=-31.50, y=63.00, z=777.50], EntitySpider['Spider'/201, l='MpServer', x=-3.50, y=63.00, z=794.50], EntitySpider['Spider'/265, l='MpServer', x=67.50, y=32.00, z=767.50], EntityCreeper['Creeper'/330, l='MpServer', x=-4.84, y=65.00, z=742.75], EntityZombie['Zombie'/203, l='MpServer', x=-2.50, y=63.00, z=790.50], EntitySkeleton['Skeleton'/333, l='MpServer', x=-31.50, y=35.00, z=716.50], EntityBat['Bat'/78, l='MpServer', x=39.75, y=42.10, z=732.75], EntitySpider['Spider'/334, l='MpServer', x=47.50, y=64.00, z=715.50], EntitySkeleton['Skeleton'/82, l='MpServer', x=-26.50, y=66.00, z=716.50], EntityCreeper['Creeper'/20, l='MpServer', x=-33.50, y=68.00, z=694.50], EntityZombie['Zombie'/346, l='MpServer', x=77.50, y=41.00, z=678.50], EntitySkeleton['Skeleton'/283, l='MpServer', x=-27.50, y=65.00, z=710.50], EntitySkeleton['Skeleton'/286, l='MpServer', x=77.50, y=28.00, z=716.50], EntityCreeper['Creeper'/350, l='MpServer', x=87.50, y=68.00, z=770.50], EntitySkeleton['Skeleton'/287, l='MpServer', x=76.04, y=28.00, z=715.17], EntityZombie['Zombie'/224, l='MpServer', x=73.50, y=33.00, z=770.50], EntityZombie['Zombie'/288, l='MpServer', x=75.41, y=28.00, z=714.73], EntityZombie['Zombie'/289, l='MpServer', x=77.50, y=28.00, z=718.50], EntitySpider['Spider'/229, l='MpServer', x=43.50, y=35.00, z=683.50], EntitySkeleton['Skeleton'/233, l='MpServer', x=-34.30, y=66.00, z=692.50], EntitySkeleton['Skeleton'/299, l='MpServer', x=-30.50, y=66.00, z=676.50], EntityCreeper['Creeper'/304, l='MpServer', x=59.50, y=24.00, z=670.50], EntitySkeleton['Skeleton'/241, l='MpServer', x=70.50, y=20.00, z=725.50], EntitySkeleton['Skeleton'/305, l='MpServer', x=67.50, y=69.00, z=723.50], EntitySkeleton['Skeleton'/242, l='MpServer', x=69.50, y=20.00, z=724.50], EntitySpider['Spider'/179, l='MpServer', x=8.50, y=64.00, z=763.50], EntitySkeleton['Skeleton'/117, l='MpServer', x=61.50, y=13.00, z=708.50], EntitySpider['Spider'/310, l='MpServer', x=-30.50, y=41.00, z=749.50], EntitySkeleton['Skeleton'/119, l='MpServer', x=60.50, y=13.00, z=707.50], EntitySpider['Spider'/248, l='MpServer', x=84.50, y=72.00, z=721.50], EntitySpider['Spider'/312, l='MpServer', x=-28.12, y=41.00, z=755.62], EntityCreeper['Creeper'/250, l='MpServer', x=62.50, y=22.00, z=686.50], EntitySkeleton['Skeleton'/189, l='MpServer', x=90.50, y=23.00, z=793.50], EntityBat['Bat'/62, l='MpServer', x=-11.50, y=20.10, z=794.50], EntityZombie['Zombie'/383, l='MpServer', x=-11.55, y=64.00, z=752.74]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 438931656 bytes (418 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 43 mods loaded, 43 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                           | Version           | Source                                        | Signature                                |
       |:------ |:-------------------------------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                                    | 1.12.2            | minecraft.jar                                 | None                                     |
       | LCHIJA | mcp                                          | 9.42              | minecraft.jar                                 | None                                     |
       | LCHIJA | FML                                          | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
       | LCHIJA | forge                                        | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
       | LCHIJA | micdoodlecore                                |                   | minecraft.jar                                 | None                                     |
       | LCHIJA | com.elytradev.movingworld.common.asm.coremod |                   | minecraft.jar                                 | None                                     |
       | LCHIJA | foamfixcore                                  | 7.7.4             | minecraft.jar                                 | None                                     |
       | LCHIJA | obfuscate                                    | 0.2.6             | minecraft.jar                                 | None                                     |
       | LCHIJA | futuremccore                                 | 0.1.12            | minecraft.jar                                 | None                                     |
       | LCHIJA | dsurroundcore                                | 3.5.5.0           | minecraft.jar                                 | None                                     |
       | LCHIJA | voxelmap                                     | 1.9.11            | forgemod_VoxelMap-1.9.11_for_1.12.2.jar       | None                                     |
       | LCHIJA | buildcraftlib                                | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                  | None                                     |
       | LCHIJA | buildcraftcore                               | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                  | None                                     |
       | LCHIJA | buildcraftbuilders                           | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                  | None                                     |
       | LCHIJA | buildcrafttransport                          | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                  | None                                     |
       | LCHIJA | buildcraftsilicon                            | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                  | None                                     |
       | LCHIJA | buildcraftcompat                             | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                  | None                                     |
       | LCHIJA | buildcraftenergy                             | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                  | None                                     |
       | LCHIJA | buildcraftfactory                            | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                  | None                                     |
       | LCHIJA | buildcraftrobotics                           | 7.99.24.3         | buildcraft-all-7.99.24.3.jar                  | None                                     |
       | LCHIJA | codechickenlib                               | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | thedalekmod                                  | (Update 50.1)     | Dalek Mod - Update 50.1.jar                   | None                                     |
       | LCHIJA | movingworld                                  | 1.12-6.342        | movingworld-1.12-6.342-full.jar               | None                                     |
       | LCHIJA | davincisvessels                              | @DVESSELSVER@     | davincisvessels-1.12-6.340-full.jar           | None                                     |
       | LCHIJA | foamfix                                      | 0.10.8-1.12.2     | foamfix-0.10.8-1.12.2.jar                     | None                                     |
       | LCHIJA | minecraftfuture                              | 0.1.13            | future-mc-0.1.13.jar                          | None                                     |
       | LCHIJA | mantle                                       | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                      | None                                     |
       | LCHIJA | jei                                          | 4.15.0.291        | jei_1.12.2-4.15.0.291 (1).jar                 | None                                     |
       | LCHIJA | tconstruct                                   | 1.12.2-2.13.0.171 | TConstruct-1.12.2-2.13.0.171.jar              | None                                     |
       | LCHIJA | galacticraftcore                             | 4.0.2.237         | GalacticraftCore-1.12.2-4.0.2.237.jar         | None                                     |
       | LCHIJA | galacticraftplanets                          | 4.0.2.237         | Galacticraft-Planets-1.12.2-4.0.2.237.jar     | None                                     |
       | LCHIJA | mekanism                                     | 1.12.2-9.8.2.389  | Mekanism-1.12.2-9.8.2.389.jar                 | None                                     |
       | LCHIJA | mekanismgenerators                           | 1.12.2-9.8.2.389  | MekanismGenerators-1.12.2-9.8.2.389.jar       | None                                     |
       | LCHIJA | mekanismtools                                | 1.12.2-9.8.2.389  | MekanismTools-1.12.2-9.8.2.389.jar            | None                                     |
       | LCHIJA | mekores                                      | 2.0.11            | mekores-2.0.11.jar                            | None                                     |
       | LCHIJA | harvestcraft                                 | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zf.jar               | None                                     |
       | LCHIJA | texfix                                       | 4.0               | TexFix+V-1.12-4.0.jar                         | None                                     |
       | LCHIJA | vanillafix                                   | 1.0.10-SNAPSHOT   | VanillaFix-1.0.10-99.jar                      | None                                     |
       | LCHIJA | vehicle                                      | 0.41.1            | vehicle-mod-0.41.1-1.12.2.jar                 | None                                     |
       | LCHIJA | wildnature                                   | 1.2               | wildnature-1.2 (1).jar                        | None                                     |
       | LCHIJA | xaerominimap                                 | 1.18.5.3          | Xaeros_Minimap_1.18.5.3_Forge_1.12.jar        | None                                     |
       | LCHIJA | orelib                                       | 3.5.2.3           | OreLib-1.12.2-3.5.2.3.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround                                    | 3.5.5.0           | DynamicSurroundings-1.12.2-3.5.5.0.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
  Loaded coremods (and transformers): Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.8-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      FutureMC (future-mc-0.1.13.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      MekanismCoremod (Mekanism-1.12.2-9.8.2.389.jar)
                                        mekanism.coremod.KeybindingMigrationHelper
                                      MovingWorldCore (movingworld-1.12-6.342-full.jar)
                                        
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.5.0.jar)
                                        org.orecruncher.dsurround.asm.Transformer
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.237.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 436.30' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
  Suspected Mods: WildNature mod (wildnature), BuildCraft Lib (buildcraftlib), BuildCraft Compat (buildcraftcompat), BuildCraft Silicon (buildcraftsilicon), BuildCraft (buildcraftcore), BuildCraft Robotics (buildcraftrobotics), BuildCraft Transport (buildcrafttransport), BuildCraft Factory (buildcraftfactory), BuildCraft Builders (buildcraftbuilders), BuildCraft Energy (buildcraftenergy), Just Enough Items (jei)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 436.30, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Bdubs_1.12.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x AMD Ryzen 3 1300X Quad-Core Processor
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by AlexIIL** [comment]
This is a bug in wildnature, can you report this to them?

(2 issues have been created for this before, so you might want to follow those instead: #4435 and #4481)
