### ISSUE TITLE
Redstone engines cool down while working

### ISSUE THREAD

**Issue by Froggg** [BuildCraft/BuildCraft#4500]
when powered and idle they build up heat all the way to black, but as soon as they are given work they just drop heat stages like flies to the point where using BC Pipes for mass transport is basically useless. either spend coal or just don't move more than 4 every 5 seconds. kinda gamebreaking for a main aspect of the mod. 

Also yes, it may sound stupid of me to say this but I AM aware that this has already been reported however that was almost 2 years ago and its still in the most recent version, kinda killing the concept of using transport pipes, even though theyre otherwise really cool. I'd even say its worth its own update instead of waiting to ship it with the Coming Soon MJ update

**Comment by SandGrainOne** [comment]
BuildCraft also have gates that you can mount on top of the pipes. With the correct type of gate you can have a wooden pipe extract items without any need for power.

**Comment by AlexIIL** [comment]
Specifically the pipe pulsar, or power adaptor would work.

I haven't worked on this because I'm too busy porting up to 1.14, however I do agree that this is important. (Instead of tracking this issue though I'll track the original - #3914 )

**Comment by AlexIIL** [comment]
Ok, this should be fixed in 7.99.24.4-pre.2 from the [tests page](https://mod-buildcraft.com/pages/tests.html) and it will included in the next release sometime in the future (although long before the actual MJ update)

**Comment by Froggg** [comment]
Oh wow that was a real quick response. Thanks dude, and I do apologize for my attitude, it was just getting to me a bit, totally unwarranted, thanks for being such an active dev! Awesome that you got it fixed that quick.
