### ISSUE TITLE
Stirling Engine doesn't show remaining fuel very clearly.

### ISSUE THREAD

**Issue by janagyjr** [BuildCraft/BuildCraft#4505]
**Please complete the following information:**
 - Forge Version: forge-14.25.5.2847
 - BuildCraft Version (Add Hash if from github): buildcraft-all-7.99.24.3
 - Any additonal mods:

**To Reproduce**
1. Setup stirling engines
2. apply redstone signal
3. ???
4. Profit

![2019-10-28_05 40 22](https://user-images.githubusercontent.com/23646259/67655916-31358d00-f94a-11e9-8f54-6315a2e96bfc.png)

**Comment by janagyjr** [comment]
Sorry for the misunderstanding. Apparently aeternalis block's duration as a fuel isn't accurately represented by the flames. They did eventually stop, ~12 hours after being fueled.

**Comment by AlexIIL** [comment]
That's quite a long time! I was getting quite worried about looking into this. Although it would probably be a good idea to change the sprite to show when there's a little bit of fuel left rather than looking like it's already completely empty.

**Comment by janagyjr** [comment]
![aeternalisfuelblock](https://user-images.githubusercontent.com/23646259/67736995-95675800-fa01-11e9-82cc-88cd93416804.png)

Perhaps something could be added that would decrease the flames as a ratio of the amount of ticks a fuel declares it burns for?

**Comment by AlexIIL** [comment]
Ok, this should be implemented in [7.99.24.4](https://mod-buildcraft.com/buildcraft-799244.html).
