### ISSUE TITLE
cannot melt items in crucible!!!

### ISSUE THREAD

**Issue by RoseQueen21** [BuildCraft/BuildCraft#4506]
I've started playing Exoria a Minecraft a modpack after watching Captainsparkles and Xeen play it, but when I got up to a certain quest I couldn't continue as every time I try to melt an item in a crucible it doesn't work... For example I can't melt leaves and get water or melt seeds to get seed oil. Please help me I can't continue the game until it's resolved!! `version: 1.3.0c`

**Comment by AlexIIL** [comment]
This is the issue tracker for buildcraft specifically - you would probably have more help if you asked on the issue page for that modpack?

**Comment by AlexIIL** [comment]
(In addition this is completely unrelated to buildcraft as bc doesn't add a crucible or seed oil).
