### ISSUE TITLE
GuideManager takes 40 min

### ISSUE THREAD

**Issue by nift4** [BuildCraft/BuildCraft#4507]
**Please complete the following information:**
 - Forge Version: 14.23.5.2838
 - BuildCraft Version (Add Hash if from github): 7.99.24.3
 - Any additonal mods: To much!

**To Reproduce**
1. Launch game

**Problem**
PostInitalization BuildCraft Lib - Loading GuideManager takes over 40 Minutes in my Modpack (very large). What does this thing and how I can speed up or disable?

**Comment by AlexIIL** [comment]
Can you retry with 7.99.24.4-pre 2 (from the tests page here: https://mod-buildcraft.com/pages/tests.html) as that has some optimisations for the guide loading?

**Comment by nift4** [comment]
I'll try soon, for now I killed Minecraft after 45 min waiting for only Buildcraft Lib.

**Comment by nift4** [comment]
P.S.: The laggy things are 'root.reload.contents_page.add_default.buildcraft/lib/client/guide/Entry/PageEntryItemStack.itr_search', 'root.reload.contents_page.add_default.buildcraft/lib/client/guide/Entry/PageEntryItemStack.itr_search.create_page_link' and 'root.reload.contents_page.add_default.buildcraft/lib/client/guide/Entry/PageEntryItemStack.itr_search.create_page_link.get_tooltip'. Was that optimized? It looks for me like it indexes all 15000 items...

**Comment by nift4** [comment]
Do you need an modlist?

**Comment by nift4** [comment]
Ah and thanks for the fast response.

**Comment by AlexIIL** [comment]
Could you upload your full log? (Essentially I'd like to see the full modlist and the full guide profiler information?)

**Comment by AlexIIL** [comment]
Oh, and 7.99.24.4-pre2 should limit the number of items to 10k by default which *should* make it a lot faster to load in bigger modpacks.

**Comment by nift4** [comment]
Does this mean only 10k items are loaded or when more than 10k items here nothing is loaded?

**Comment by AlexIIL** [comment]
Not quite:

 - If there are more than 10k items present then it will only scan minecraft, buildcraft, and any other mods that have entries in the buildcraft guide book.
 - If there are less than 10k items then it will scan all of them and then all will be present in the buildcraft guide book.

**Comment by AlexIIL** [comment]
(Although I'm still interested in a full log file if you have one?

**Comment by nift4** [comment]
I send a log file soon but now the PC is off ;)

**Comment by nift4** [comment]
Last question: Are there any changes in the prerelease that make in unstable (I ask because I want to use it in a productive environment, I mean the modpack lol)?

**Comment by AlexIIL** [comment]
There shouldn't be any stability issues with this one in particular, although I'll probably release it properly kinda soon as it has been available for quite a while. (In addition it's only available through the website and not curseforge)

**Comment by nift4** [comment]
Okay thanks

**Comment by nift4** [comment]
P.S.: You could add an confog option to always use that minimal guide.

**Comment by nift4** [comment]
Log with stable: https://paste.ee/p/RJJ0x

**Comment by nift4** [comment]
Crash report with mod list (only Iron Backpacks was replaced with Forge Backpacks): https://paste.ee/p/lsZ6P

**Comment by nift4** [comment]
Pre2 works :)

**Comment by nift4** [comment]
I would say that the issue is closable when resease is out. @AlexIIL

**Comment by AlexIIL** [comment]
Ok, thanks!

**Comment by AlexIIL** [comment]
Ok, I've released [7.99.24.4](https://mod-buildcraft.com/buildcraft-799244.html), with very little changes to the guide book since 7.99.24.4-pre.2.
