### ISSUE TITLE
Can't melt anything in a crucible

### ISSUE THREAD

**Issue by RoseQueen21** [BuildCraft/BuildCraft#4508]
no matter how much i try i can't melt leaves to get water or seeds to get seed oil or anything else for that matter so i dont know what else to do

**Comment by AlexIIL** [comment]
This is the issue tracker for buildcraft specifically - you  would probably have more help if you asked on the issue page for that  modpack?

Also, is this a duplicate of #4506 ?

**Comment by RoseQueen21** [comment]
where do I find the issue page for this modpack?

**Comment by aaronliu0130** [comment]
@RoseQueen21 [Here you go.https://github.com/davqvist/Exoria/issues](https://github.com/davqvist/Exoria/issues)
