### ISSUE TITLE
Option to disable biomes (and worldgen layer)

### ISSUE THREAD

**Issue by adosikas** [BuildCraft/BuildCraft#4511]
**Is your feature request related to a problem? Please describe.**
Currently there is no way of disabling the custom oil biomes without completely disabling worldgen (and with it all oil deposits).  
In old BuildCraft this was possible by setting the biome ids to 0 [link](https://github.com/BuildCraft/BuildCraft/blob/8.0.x-1.12.2/src_old_license/buildcraft/BuildCraftEnergy.java#L118-L119).

**Describe the solution you'd like**
Add config option to disable the oil biomes, optionally make the spawn rate configurable.  
Also don't add the world gen layer when the biomes are disabled (similar to setting biome ID to 0 in old BuildCraft).

---

Full disclosure: My primary reason is that the added worldgen layers currently cause inconviences with RTG ([Issue](https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/1338)).

Obviously that problem is not a BuildCraft issue and should be fixed on RTGs end, but regardless of that, I can still see uses for a config options for the biomes.

**Comment by AlexIIL** [comment]
Seems reasonable :)

**Comment by AlexIIL** [comment]
Ok, this should be implemented in [7.99.24.4](https://mod-buildcraft.com/buildcraft-799244.html).
