### ISSUE TITLE
BuildCraft Lib crash

### ISSUE THREAD

**Issue by ADT1710** [BuildCraft/BuildCraft#4513]
Hello, I'm doing a mod pack for my Minecraft 1.12.2, and when I opened the game it inicialized to charge the mods, but when it arrive in BuildCraft Lib this message appears:

"net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Lib (buildcraftlib)
Caused by: java.lang.NoSuchFieldError: logger"

Thanks for help!

Crash Report or Log: https://gist.github.com/ADT1710/f35da4032ae9cdd4daeb2f87c772f948

**Comment by AlexIIL** [comment]
One of your mods includes the old (1.7.10) buildcraft API - to find out which one Can you upload the full log? (Or re-run with [7.99.24.5-pre.1](https://mod-buildcraft.com/releases/testing/BuildCraft/7.99.24.5-pre.1/buildcraft-all-7.99.24.5-pre.1.jar) from the [tests page](https://mod-buildcraft.com/pages/tests.html), which includes that information in the crash report).

**Comment by AEnterprise** [comment]
looking at the mods list, it looks to me like you got most mods from non official sources. Other websites that (often breaking the mods copyright licence) copy mod files, rename them and claim they are for a specific minecraft version (in this case 1.12.2).

Sometimes this is actually that mod for that version, but sometimes that's just an old mod they renamed and slapped on their site. in some extreme cases it's not even a mod malicious code

**Comment by ADT1710** [comment]
@AlexIIL this is the link of the full log generated when I tried the 7.99.24.5-pre.1, the same error again
https://gist.github.com/ADT1710/055a606f74355b6b8b873252b972ca0c
Thanks for the attention

Thanks @AEnterprise for the advice

**Comment by AlexIIL** [comment]
Unfortunately that's a log from before - using 7.99.24.4, rather than 7.99.24.5-pre.1.

However it does say that you're trying to use `universal-electricity-4.0.0.1-dev.jar`, which is for 1.7.10 and not 1.12.2 - so you should remove that.

**Comment by ADT1710** [comment]
@AlexIIL I removed the universal-electricity-4.0.0.1-dev.jar and now is working normally, in the site was saying it was for the 1.12.2 but is what the @AEnterprise says. Sorry for my mistake and thanks for all!

**Comment by AEnterprise** [comment]
@ADT1710 don't worry about it, those sites are just designed to trick users ;)

**Comment by aryan4441** [comment]
> Unfortunately that's a log from before - using 7.99.24.4, rather than 7.99.24.5-pre.1.
> 
> However it does say that you're trying to use `universal-electricity-4.0.0.1-dev.jar`, which is for 1.7.10 and not 1.12.2 - so you should remove that.

How could i remove that
