### ISSUE TITLE
Stirling engine no longer works at max heat and energy

### ISSUE THREAD

**Issue by Explodethis** [BuildCraft/BuildCraft#4515]
In 7.99.24.3 a Stirling engine, receiving a redstone signal (from a lever placed on the back of the engine), powering a wooden pipe and connected to an empty chest would store energy until it reached it's maximum heat value of 215.65 degrees (based on burning coal). If an item was placed in the chest the engine would power the wooden pipe and the item would then be pumped out of the chest.

In 7.99.24.4 the Stirling engine will no longer power the wooden pipe when it has reached 215.65 degrees and it is still receiving a redstone signal. If the redstone signal is turned off then the engine will power the wooden pipe but it will also slowly lose all stored energy and heat. If the redstone signal is turned back on and the heat is less than 215.65 degrees it will power the wooden pipe and pump items.

This change in behavior  was observed in the Tekxit 3 update from V.97 to V.971. This included the update of Buildcraft from 7.99.24.3 to 7.99.24.4. After updating, all previous Stirling engine wooden pipe combinations would cease to work as they did in the previous version.

**Comment by AlexIIL** [comment]
Actually, the behaviour in 7.99.24.3 was accidental: the stirling engine wasn't meant to pause burning if it maxed out it's capacity, instead it should have gone into overheat mode and refused to send any power until it was cooled down. So technically I fixed this by accident when I made the server + client use the same pulsing speed.

**Comment by Explodethis** [comment]
Ok I understand now. The Stirling engine is intended to stop producing power once it reaches its maximum temperature. At this point you need to cool it down in order for it to work again. That sounds like the behaviour I observed after the update. Thanks for the clarification

**Comment by Explodethis** [comment]
The behaviour observed in 7.99.24.3 was not intended. This was fixed in 7.99.24.4 and caused the change in behaviour I observed. As of 7.99.24.4 the Stirling engine is behaving as intended.
