### ISSUE TITLE
[Crash] Caught exception from BuildCraft Silicon (buildcraftsilicon)

### ISSUE THREAD

**Issue by Deathtanium** [BuildCraft/BuildCraft#4516]
I have encountered this crash-on-startup right after installing the mod. A full list of all my mods can be found in the crash log below. Thank you for your time.
[crash-2019-12-27_11.55.39-client.txt](https://github.com/BuildCraft/BuildCraft/files/4006148/crash-2019-12-27_11.55.39-client.txt)

**Comment by AlexIIL** [comment]
Can you upload the game's log? There's some sponge mixin's being applied that aren't listed there.

**Comment by Deathtanium** [comment]
[2019-12-27-2.log](https://github.com/BuildCraft/BuildCraft/files/4007105/2019-12-27-2.log)
I think this is it.

**Comment by AlexIIL** [comment]
Oh, unfortunately buildcraft isn't compatible with baritone's modifications (https://github.com/cabaletta/baritone/issues/760)
