### ISSUE TITLE
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Silicon (buildcraftsilicon)

### ISSUE THREAD

**Issue by typicalname0** [BuildCraft/BuildCraft#4518]
Crash Report or Log: https://gist.github.com/typicalname0/d666cbea20b7db87b6f8e5900c3a2b0e

My friend has issues starting up BuildCraft. I have looked up the error but have found no solutions. He does not use OptiFine

**Comment by AlexIIL** [comment]
Oh, unfortunately buildcraft isn't compatible with baritone's modifications (cabaletta/baritone#760).

You can either try removing the silicon module, or disabling facades to work around this.
