### ISSUE TITLE
Item Duplication When Broken by auto miners of any kind

### ISSUE THREAD

**Issue by SyndicateServers** [BuildCraft/BuildCraft#4529]
Server Log:  https://pastebin.com/ZxXHcgC3
Client Log: (too big for pastebin) https://zerobin.net/?aa51e48824e35372#I2NZo9mibA2TaqS69fCxHbgLCCHD2Ey3OJ6fM2PuzUM=

forge-14.23.5.2847
Buildcraft-all-7.99.24.4
Mods I used when I Tested: **Computer Craft** (turtles specifically) **ProjectRed** (block breaker, diamond block breaker) **(buildcraft quarries and mining wells)**

**To Reproduce**
1, place any buildcraft block with an inventory such as advanced crafting table
2, place block breaker of kinds listed above in such a way that it will break the item
3, activate/power and watch the dupe spit out of its outlet

(pictures provided by a player in my community)

![1](https://user-images.githubusercontent.com/42458375/74628138-d3a89480-5122-11ea-8b22-1723cbd9f0da.png)
![2](https://user-images.githubusercontent.com/42458375/74628141-d5725800-5122-11ea-8ba3-603a4338766e.png)

**Comment by AlexIIL** [comment]
Ok, this should be fixed in 7.99.24.5 - please let me know if that's not the case.

**Comment by SyndicateServers** [comment]
seems to be working fine now, cant get it to go with turtles or block breakers.
