### ISSUE TITLE
GuideManager causes game crash if Crafttweaker tries to remove item tooltips.

### ISSUE THREAD

**Issue by plackyfantacky** [BuildCraft/BuildCraft#4530]
[Crash report](https://gist.github.com/plackyfantacky/e87db13c86599d746218690749aa7775)

Tested this with two instances (One with a pack I'm developing, another with bare essentials to reproduce the crash). 

It seems I am able to repeatedly crash Buildcraft if I try and remove tooltips from an item using CraftTweaker like so:

`<galacticraftplanets:walkway:1>.clearTooltip();`

I thought it was my code or a CT issue at first but seems to only happen with BC. I'm following CT documentation for a pack I'm making. [Here is my ZS file](https://gist.github.com/plackyfantacky/a048b288de0a10a221563b7ee043fcc0) that triggers the GuideManager crash, and here is the [related CT documentation](https://docs.blamejared.com/1.12/en/#Vanilla/Items/Tooltips/).

Sorry to beat a dead horse but can we please have a config option to disable the in-game Guide?

**Comment by AlexIIL** [comment]
That's an odd thing to do, do you have any particular reason for removing tooltips?

(Although it's technically still a bug so I'm still going to fix it).

And no, I'm not adding a config option for disabling the guide book - especially if the only reason why you want to disable it is because of a fixable crash.

**Comment by plackyfantacky** [comment]
Fair enough. This was mostly an example, but in terms of what I'm doing, I am re-writing a lot of the tooltips to fit in the lore/theme of the pack I'm developing. I just remove the existing tooltip, then add in my own.

**Comment by AlexIIL** [comment]
Ah ok, that would make more sense - so everything should have tooltips eventually.

**Comment by AlexIIL** [comment]
Ok, this should be fixed in 7.99.24.5 - please let me know if that's not the case.
