### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by xJon** [BuildCraft/BuildCraft#4532]
Crash Report or Log: https://paste.ubuntu.com/p/T5RdgWXmqw/

> The crash infrequently occurs while entering my chunks with running quarries.

Reported to my modpack over https://github.com/xJon/The-1.12.2-Pack/issues/249.

**Comment by AlexIIL** [comment]
Both crashes mentioned in the issue reports should be fixed in [7.99.24.6-pre.1](https://mod-buildcraft.com/releases/testing/BuildCraft/7.99.24.6-pre.1/buildcraft-all-7.99.24.6-pre.1.jar), although the release isn't actually out yet.

**Comment by xJon** [comment]
Thank you :)

**Comment by xJon** [comment]
When you say both crashes are you also referring to this one?
> https://paste.ubuntu.com/p/T5RdgWXmqw/

**Comment by AlexIIL** [comment]
I fixed https://paste.ubuntu.com/p/T5RdgWXmqw/ in https://github.com/BuildCraft/BuildCraft/commit/c4135ea7ae2f56010e33741b58b6518e861a007f (linked above), and fixed the other crash in https://github.com/BuildCraft/BuildCraft/commit/abdb4f44f08feada89c5f8351a547e13a6e4b953 as it was reported in #4534. (Then when I looked back at your original report I saw that the second crash was basically the same as 4534)

**Comment by xJon** [comment]
Since `7.99.24.6` has been released already I'm closing this :)
