### ISSUE TITLE
Buildcraft Quarry Collision box crash

### ISSUE THREAD

**Issue by Thunderolf** [BuildCraft/BuildCraft#4534]
This has been a pretty old bug I've experienced in buildcraft for a while now and it gets pretty annoying for such an awesome mod. From what I can tell, the solid collision box causes a crash when the chunks are un-rendered and re-rendered (Go out of view and then back in view). Rather the chunk loading is left as is, or assisted with chicken chunks chunk loader.

I am on 1.12.2 using forge 14.23.5.2847 using mod version buildcraft-all-7.99.24.5 downloaded from https://www.curseforge.com/minecraft/mc-mods/buildcraft with OptiFine_1.12.2_HD_U_F4 downloaded from https://optifine.net/home (May be rendering related) No shaders, no resourcepack

Video options:
[options.txt](https://github.com/BuildCraft/BuildCraft/files/4274818/options.txt)
[optionsof.txt](https://github.com/BuildCraft/BuildCraft/files/4274820/optionsof.txt)
[optionsshaders.txt](https://github.com/BuildCraft/BuildCraft/files/4274823/optionsshaders.txt)

I have an intel i7-2600K 3.4GHz with 32GB of RAM using 26GB for the huge modpack its in so its comfortable with just enough ram but not too much.

JVM Arguments: 
-Xmx26G -Xmn12G -d64 -XX:+DisableExplicitGC -XX:PermSize=256M -XX:MaxPermSize=512M -XX:ParallelGCThreads=2 -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=50 -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true -Dfml.readTimeout=2140 -Duser.language=en -Duser.country=US

ps. I know this is a huge modpack, so there can possible be a million factors, but I have had this collision box issue in many other modpacks in many other versions of minecraft and the mod version

Also random screenshot of the crash screen if this helps:
![image](https://user-images.githubusercontent.com/56629665/75668366-da64fa80-5c3e-11ea-910a-10f40d8ff9a0.png)

[crash-2020-03-02_03.51.04-client.txt](https://github.com/BuildCraft/BuildCraft/files/4274782/crash-2020-03-02_03.51.04-client.txt)

**Comment by Thunderolf** [comment]
I can also provide the link to download the custom pack with ~580 mods if that would help

**Comment by AlexIIL** [comment]
Thanks for the detailed information! Fortunately however the crash report contains enough information for me to try and fix this, so can you try the test release [7.99.24.6-pre.1](https://mod-buildcraft.com/releases/testing/BuildCraft/7.99.24.6-pre.1/buildcraft-all-7.99.24.6-pre.1.jar), from the [tests page](https://mod-buildcraft.com/pages/tests.html) to see if that fixes this?

**Comment by Thunderolf** [comment]
I'll start testing it in my huge modpack and I'll report if there is any crashes, if I find none in a month of gameplay. then I'll assume its fixed

**Comment by AlexIIL** [comment]
Ok, this should be fixed in the release 7.99.24.6.
