### ISSUE TITLE
Quarry halt with energyconverters mod

### ISSUE THREAD

**Issue by KiralyCraft** [BuildCraft/BuildCraft#4540]
**Please complete the following information:**
 - Forge Version: forge-1.12.2-14.23.5.2847-universal
 - BuildCraft Version (Add Hash if from github): buildcraft-all-7.99.24.5
 - Any additonal mods: energyconverters_1.12.2-1.3.6.24, EnderIO-1.12.2-5.1.52, EnderCore-1.12.2-0.5.73, spongeforge-1.12.2-2838-7.1.10
-  Using the config from 7.99.24.4

**To Reproduce**
1. Place a Creative Capacitor bank -> FE Energy Consumer -> Energy Bridge -> MJ Energy Producer -> Quarry.
2. The quarry will start to build the frame but then stop all of a sudden. 

1a. Place the Quarry first, power it with creative engines (wooden & golden kinesis pipes). After the frame is built, remove the engines and connect the MJ Energy Producer. The quarry will work for a while then stop completely. Reconnecting the engines at this point has no effect without removing the quarry and placing it again.

Conclusion: Powering the quarry with a MJ Energy Producer will make it work at max speed for a while, then stop forever, until the quarry is removed and placed again.

https://imgur.com/a/wgeVwCA

**Comment by AlexIIL** [comment]
Can you retry with [7.99.24.6-pre.2](https://mod-buildcraft.com/releases/testing/BuildCraft/7.99.24.6-pre.2/buildcraft-all-7.99.24.6-pre.2.jar), from the [tests page](https://mod-buildcraft.com/pages/tests.html)?

**Comment by KiralyCraft** [comment]
It works with  7.99.24.6-pre.2, hurray

**Comment by AlexIIL** [comment]
Ok, this is out in 7.99.24.6
