### ISSUE TITLE
Crash related to pumps

### ISSUE THREAD

**Issue by Owy32** [BuildCraft/BuildCraft#4542]
placing a pump in the nether directly over the lave lakes causes crashes on server and lag on single player

Crash Report or Log: 
Server Crash Log : https://gist.github.com/Owy32/d6933624ddaa718b9f4d2d88d457eccf
Single player Crash Log : single player didnt crash, instead it caused the game to lag in a way were blocks wouldnt drop after being broke and occasional lag spikes, jei wouldnt spawn items in and no longs were recorded from after i first caused this (might be unrelated)

**Comment by AEnterprise** [comment]
please update to BC version 7.99.24.5, the pump should no longer cause this kind of lag with that
