### ISSUE TITLE
[1.12.2] Water bucket and combustion engine

### ISSUE THREAD

**Issue by TheCoolestPaul** [BuildCraft/BuildCraft#4543]
https://hastebin.com/qufozapimu.rb

**Please complete the following information:**
 - Forge Version: 80.99.99
 - BuildCraft Version (Add Hash if from github): 7.99.24.5
 - Any additonal mods: The 1.12.2 pack

**To Reproduce**
1. Place down combustion engine
2. Fill with water
3. Even if filled RClick the engine with another water bucket
4. You can let it drain a bit and RClick with another water bucket and the same thing happens

**Comment by AlexIIL** [comment]
Ok, this should be fixed in the release 7.99.24.6
