### ISSUE TITLE
Pls give me example

### ISSUE THREAD

**Issue by MitiskoSVK** [BuildCraft/BuildCraft#4544]
Hi I use buildcraft-compat-7.99.24.5 and i need remove recipe from .AssemblyTable all chipset...
Old version funcional code is:
mods.buildcraft.AssemblyTable.removeByName(<BuildCraft|Silicon:redstoneChipset:*>);
Please give me example new funcional code...

Very thanks

**Comment by AlexIIL** [comment]
Duplicate of https://github.com/BuildCraft/BuildCraftCompat/issues/93
