### ISSUE TITLE
Crash - Architect Table

### ISSUE THREAD

**Issue by Jos-2** [BuildCraft/BuildCraft#4546]
Putting a blank blueprint into the architect table is crashing my game. Playing Tekxit modpack. Here's the crash report https://paste.dimdev.org/ucezahizoy.mccrash

**Comment by AEnterprise** [comment]
couple of things here:

- the builder and architect table currently only have full support for vanilla blocks, experiment with modded blocks at your own risk
- it's not completely survival ready
- the root of the crash is not buildcraft, it's mcmultipart or whatever multipart is in the area. the builder is just checking if the block is air or not, and the block crashed
