### ISSUE TITLE
Engines Don't Exist Despite enabling them in config

### ISSUE THREAD

**Issue by Benj2005** [BuildCraft/BuildCraft#4547]
Version : buildcraft-all-7.99.24.6

Hi,
for a small bit of context I'm working on a private modpack where I only want a few features of buildcraft in it. I basically disabled everything in objects.cfg and the re-enabled the items / blocks that I wanted  eg. quarries. (Which work fine.) However despite enabling engines, they are not in the game. (Check Attached Screenshot)

I also attached my full buildcraft config.

If you could please let me know what I am doing wrong / if this is a bug that would help a ton!

Note : Engines worked fine before modifying the config. 
![screanshot](https://user-images.githubusercontent.com/62969241/78084813-ee01ad80-7404-11ea-8f31-98db37cd20fd.PNG)

[config.zip](https://github.com/BuildCraft/BuildCraft/files/4411996/config.zip)

**Comment by AlexIIL** [comment]
You need to enable "blocks.engine" too - in 1.12.2 BC stores the different engine combinations in item metadata, which leads to the odd situation that you have to enable engines in two places at once.

**Comment by Benj2005** [comment]
It worked! Thanks for help help and fast response!
