### ISSUE TITLE
Reskillable (minecraft mod) breaks Quarries.

### ISSUE THREAD

**Issue by TurboFunder** [BuildCraft/BuildCraft#4548]
**Please complete the following information:**
 - Forge Version: 14.23.5.2847
 - BuildCraft Version: 7.99.24.6
- Minecraft version: 1.12.2
 - Any additonal mods: (is in a developing modpack)
[Mods list.txt](https://github.com/BuildCraft/BuildCraft/files/4412032/Mods.list.txt)

The quarry pauses mining and attempts to destroy the block w/ the laser. 
However unable to & requires manually mining it by the player.

**To Reproduce**
1. Setup a quarry
2. Make sure Reskillable is installed
2. Let it run
3. Will see quarry halt on ore that drops blocks (iron, gold, modded ore as well).

![2020-03-30_23 54 44](https://user-images.githubusercontent.com/62969085/78084496-366d8c80-736d-11ea-8fbc-4e961da4a909.png)

**Comment by KiralyCraft** [comment]
Does this happen every time? Is it easily reproducible? If it is, You could try adding mods in groups of 5 , placing a quarry real quick and let it do its thing. This way you can at least try to isolate the mod that causes this, as I've personally never seen this happen before. You could (though don't quote me on that, I'm not affiliated with buildcraft) downgrade Buildcraft to 24.4 and test that

**Comment by TurboFunder** [comment]
My friend and I have determined that it is the mod Reskillable causing the issue.

**Comment by AEnterprise** [comment]
then sadly there is not much really that can be done about it from this end, it seems they are preventing fake players (like the quarry) to break blocks (probably because the fake player doesn't have the skill needed to do so)

your best bet is talking to them about a config setting or so to allow fake players to bypass the skill requirements

**Comment by TurboFunder** [comment]
Turns out that's already a config setting for that exact purpose.
It says: 

"  # Set this to true to enforce requirement checks on Fake Players
    B:"Enforce requirements on Fake Players"=true  " 

I set it to false, and the quarry is mining the ores again! Thanks for all your help.
