### ISSUE TITLE
Quarry's stop when hitting max MJ storage 1.12.2

### ISSUE THREAD

**Issue by Owy32** [BuildCraft/BuildCraft#4549]
- Forge Version: 8.0.99.99
 - BuildCraft Version (Add Hash if from github): 7.99.24.5
 - Any additonal mods: https://gist.github.com/Owy32/d6f65eed452d892ccf0c20b4b902c660
Basically Tekkit Classic Reloaded (on Twitch) + optifine + i updated buildcraft to latest

To Reproduce
1. set up a quarry however
2. input it with any medium to large source of MJ/t
3. wait till it hits 24k/24k MJ
4. stops working and nothing can re enable

**Comment by KiralyCraft** [comment]
This has been fixed in 7.99.24.6

**Comment by Owy32** [comment]
Works now, Thanks. MB for not checking if game was updated

**Comment by AlexIIL** [comment]
Ok, thanks for checking.

(Duplicate of #4540).
