### ISSUE TITLE
pumps don't work (1.12.2)

### ISSUE THREAD

**Issue by vixxb** [BuildCraft/BuildCraft#4559]
Hi!
First of all, I have several others mods too (I don't know if there's ones that doesn't work with BuildCraft or not). 
I want to pump the water into my Reaction Chamber (Techguns mod), so I use this mod to do it. I did everything as described. Water, pump, stirling engine, lava bucket, lever, golden waterproof pipes, etc. The pump IS working because it starts moving after I pull the level but the water IS NOT coming anywhere. 
I really need help with that. Thanks xx
![2020-04-17_20 40 03](https://user-images.githubusercontent.com/63874481/79603038-db1cf780-80eb-11ea-9bbf-878242384a0c.png)

**Comment by AlexIIL** [comment]
You opened two issues - so I'll respond to #4560 instead of this one :p

**Comment by vixxb** [comment]
Ooops sorry xD
