### ISSUE TITLE
Can't build buildcraft on windows

### ISSUE THREAD

**Issue by aaronliu0130** [BuildCraft/BuildCraft#4563]
BuildCraft doesn't build on windows at all! Gradlew claims the build is successful, which means a bigger problem! My guess: No actionable tasks?

```
gradlew.bat setupCIWorkspace
Starting a Gradle Daemon (subsequent builds will be faster)
> Configure project : FIGURING [11s]                                > root project
This mapping 'snapshot_20171120' was designed for MC 1.12! Use at your own peril.
#################################################
         ForgeGradle 2.3-SNAPSHOT-6084129e
  https://github.com/MinecraftForge/ForgeGradle
#################################################
                 Powered by MCP
             http://modcoderpack.com
     by: Searge, ProfMobius, R4wk, ZeuX
     Fesh0r, IngisKahn, bspkrs, LexManos
#################################################


BUILD SUCCESSFUL in 48s
4 actionable tasks: 4 executed
```
That's the entire log! A big problem!
**Please complete the following information:**
 - Forge Version: Not Relevant
 - BuildCraft Version (Add Hash if from github): b6763a8f25073f1a116dd6c02e597067cdf2235d
 - Any additonal mods: Not Relevant

**To Reproduce**
1. Clone the code and cd into that directory using windows
2. Run "gradlew.bat setupCIWorkspace"

**Comment by AEnterprise** [comment]
no you're just asking it to do to setup a CI workspace, so that's what it did. you didn't ask it to generate a jar file so it didn't.  for that you want to run the build task as well

**Comment by aaronliu0130** [comment]
Oops, what an error!
