### ISSUE TITLE
[1.12.2] Heat Exchanger animation issue

### ISSUE THREAD

**Issue by WH1T3No1SE** [BuildCraft/BuildCraft#4568]
- Forge Version: 14.23.5.2847
 - BuildCraft Version (Add Hash if from github): 7.99.24.6 
 - Any additonal mods: JEI, Inventory Tweaks, Journey Map

**To Reproduce**
1. Place heat exchenger of any lenght
2. Connect any liquids to it and begin exchanging heat
3. Place pipe next to any part of exchanger
4. Animation stops but exchange doesn't, animation won't return until exchange ends and new one begins

**Comment by AlexIIL** [comment]
I've finally released this fix in [7.99.24.7](https://mod-buildcraft.com/buildcraft-799247.html) - sorry for the delay.
