### ISSUE TITLE
[1.15.2] Is there a plan for 1.15.2 upgrade?

### ISSUE THREAD

**Issue by rikka0w0** [BuildCraft/BuildCraft#4570]
[1.15.2] Is there a plan for 1.15.2 upgrade?
My mod uses buildcraft facades, I just ported it to 1.15.2. I'm wondering if there will be a buildcraft release for 1.15.2?

**Comment by AlexIIL** [comment]
No, however I am porting it to 1.16 ATM. (as it's not done yet and 1.16 is close it will probably be easier to support just 1.16 BC than release 1.15 BC and then have to update shortly afterwords, and support both versions).

**Comment by LordMZTE** [comment]
i hope that doesnt mean that BC will be on fabric only...

**Comment by AEnterprise** [comment]
there are no current plans for a forge version, that being said there are people working on ways to make forge and fabric mods run together in the same instance

**Comment by rikka0w0** [comment]
I know there's a project called "patchwork", their goal is to run forge mods on fabric mod loader. Currently it is for 1.14.4 only, but it will be ported to 1.16.1.
