### ISSUE TITLE
Engines not working (1.12.2)

### ISSUE THREAD

**Issue by maximilianwalter** [BuildCraft/BuildCraft#4573]
Hello!

I'm trying to get engines to work, but they just don't move. 
I tried to only use Buildcraft (no other mods) but it's still not working. 

![image](https://user-images.githubusercontent.com/62749521/81621772-8ec58e80-93ef-11ea-98fa-7cbb9b33077a.png)

I'm not a Buildcraft pro, but this should normally work, right?
It doesn't work in singleplayer as well as on my server.

I'm using Forge 1.12.2, this is  my Buildcraft version: buildcraft-all-7.99.24.6

**Comment by AEnterprise** [comment]
is there actually something in the chest to extract?

**Comment by PrincessOfEvil** [comment]
Also that lever is turned off. :P

>

**Comment by maximilianwalter** [comment]
Yes. Obviously. But now it works. I don't know why.
