### ISSUE TITLE
Incompatibility With Optifine

### ISSUE THREAD

**Issue by ChrisLTheNerd** [BuildCraft/BuildCraft#4581]
The issue is this mod leaves a weird bright overlay in your inventory when used with Optifine. It's only when you place a build craft item like an engine, then you open your inventory. It's gone after getting rid of Optifine. This "overlay" bug also interferes with other mods like Journey's map. 

**Please complete the following information:**
 - Forge Version: 14.20.5.2854
 - BuildCraft Version (Add Hash if from github): buildcraft-all-7.99.24.6
Any additonal mods: Optifine

**To Reproduce**
1. Install optifine 
2. Place a build craft item like an engine
4. Open inventory 
5. See the overlay

Optifine was installed when making this gif
![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/50182206/84433195-ec6e1600-abfb-11ea-8020-c0e2644de85e.gif)

**Comment by DiriectorDoc** [comment]
Out of curiosity, what happens when you try other oddly-shaped blocked from outside of buildcraft? I can't think of any off the top of my head.

**Comment by ChrisLTheNerd** [comment]
I tried it with some oddly-shaped blocks from Galacticraft, Architecturecraft, and Mr Crayfish's Furniture Mod and nothing happened. It's only happening with Buildcraft.

**Comment by Dame-E-in** [comment]
This is most definitely Optifine's problem. This issue has been happening to me for years on my entire hotbar. The last version I played with Optifine was 1.14 and it was still happening to me. Their are certainly other issues that are presented with OF in tandem with BC, and this one may be made worse on some systems, but the issue is that OF is closed source. Their isn't anything that the BC devs or any contributors can do about this or any other OF/BC compat issues.

**Comment by Dame-E-in** [comment]
![image](https://media.discordapp.net/attachments/309218657798455298/527849368867438613/image0.jpg?width=508&height=678) 
Example image of when my Optifine was doing this from 2018.

![image](https://user-images.githubusercontent.com/20918683/84447091-1a138900-ac15-11ea-8628-fc62e067cd42.png)
Also from 2018. I don't even use the same PC anymore, and it still acts the same as it does on this new one.

**Comment by ChrisLTheNerd** [comment]
I never knew that it could also break at random. I'm actually playing my own modded series and I came here since the issue only started around BuildCraft stuff only. I might just remove OptiFine entirely since I have 16GB of ram allocated to Minecraft (good thing that I have 32 gigs of RAM) and I have better fps installed. Also since it has caused other visual glitches in the past on my mod pack, lIke Journeys Map giving me a blue screen when the overlays are there or when some mobs were invisible (this might be the reason why most big modpacks don't have OptiFine). Well I think I have enough evidence to know not just with BuildCraft and I think it's time to close this issue soon. Thanks Dame-E-in.
