### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JDR11** [BuildCraft/BuildCraft#4584]
Crash Report or Log:---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.211.jar)
  MovingWorldCore (MovingWorld-Mod-1.12.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 6/20/20 9:33 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Lib (buildcraftlib)
Caused by: java.lang.Error: Bad class buildcraft.api.core.BCLog loaded from net.minecraft.launchwrapper.LaunchClassLoader@6bf2d08e domain: ProtectionDomain  (jar:file:/C:/Users/joshu/AppData/Roaming/.minecraft/mods/universal-electricity-4.0.0.1-dev.jar!/buildcraft/api/core/BCLog.class <no signer certificates>)
 net.minecraft.launchwrapper.LaunchClassLoader@6bf2d08e
 <no principals>
 java.security.Permissions@7646dfd9 (
 ("java.io.FilePermission" "\C:\Users\joshu\AppData\Roaming\.minecraft\mods\universal-electricity-4.0.0.1-dev.jar" "read")
 ("java.lang.RuntimePermission" "stopThread")
 ("java.net.SocketPermission" "localhost:0" "listen,resolve")
 ("java.util.PropertyPermission" "java.specification.version" "read")
 ("java.util.PropertyPermission" "java.version" "read")
 ("java.util.PropertyPermission" "os.arch" "read")
 ("java.util.PropertyPermission" "java.specification.vendor" "read")
 ("java.util.PropertyPermission" "java.vm.specification.name" "read")
 ("java.util.PropertyPermission" "java.vm.vendor" "read")
 ("java.util.PropertyPermission" "path.separator" "read")
 ("java.util.PropertyPermission" "os.version" "read")
 ("java.util.PropertyPermission" "file.separator" "read")
 ("java.util.PropertyPermission" "line.separator" "read")
 ("java.util.PropertyPermission" "java.vm.specification.vendor" "read")
 ("java.util.PropertyPermission" "java.specification.name" "read")
 ("java.util.PropertyPermission" "java.vendor.url" "read")
 ("java.util.PropertyPermission" "java.vendor" "read")
 ("java.util.PropertyPermission" "java.vm.version" "read")
 ("java.util.PropertyPermission" "java.vm.name" "read")
 ("java.util.PropertyPermission" "java.vm.specification.version" "read")
 ("java.util.PropertyPermission" "os.name" "read")
 ("java.util.PropertyPermission" "java.class.version" "read")
)

	at buildcraft.lib.BCLib.throwBadClass(BCLib.java:123)
	at buildcraft.lib.BCLib.preInit(BCLib.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: logger
	at buildcraft.lib.BCLib.preInit(BCLib.java:72)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 978055472 bytes (932 MB) / 1476395008 bytes (1408 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2816 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version           | Source                                    | Signature                                |
	|:----- |:-------------------------------------------- |:----------------- |:----------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                                    | 1.12.2            | minecraft.jar                             | None                                     |
	| LCH   | mcp                                          | 9.42              | minecraft.jar                             | None                                     |
	| LCH   | FML                                          | 8.0.99.99         | forge-1.12.2-14.23.5.2816.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                                        | 14.23.5.2816      | forge-1.12.2-14.23.5.2816.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore                                |                   | minecraft.jar                             | None                                     |
	| LCH   | com.elytradev.movingworld.common.asm.coremod |                   | minecraft.jar                             | None                                     |
	| LCH   | backpack                                     | 3.0.2             | Backpacks-Mod-1.12.2.jar                  | None                                     |
	| LCE   | buildcraftlib                                | 7.99.24.6         | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LC    | buildcraftcore                               | 7.99.24.6         | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LC    | buildcraftbuilders                           | 7.99.24.6         | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LC    | buildcrafttransport                          | 7.99.24.6         | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LC    | buildcraftsilicon                            | 7.99.24.6         | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LC    | buildcraftcompat                             | 7.99.24.6         | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LC    | buildcraftenergy                             | 7.99.24.6         | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LC    | buildcraftfactory                            | 7.99.24.6         | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LC    | buildcraftrobotics                           | 7.99.24.6         | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LC    | movingworld                                  | 1.12-6.342        | MovingWorld-Mod-1.12.jar                  | None                                     |
	| LC    | davincisvessels                              | @DVESSELSVER@     | Davincis-Vessels-Mod-1.12.jar             | None                                     |
	| LC    | dynamiclights                                | 1.4.9             | DynamicLights-1.12.2.jar                  | None                                     |
	| LC    | dynamiclights_onfire                         | 1.0.7             | DynamicLights-1.12.2.jar                  | None                                     |
	| LC    | dynamiclights_creepers                       | 1.0.6             | DynamicLights-1.12.2.jar                  | None                                     |
	| LC    | dynamiclights_dropitems                      | 1.1.0             | DynamicLights-1.12.2.jar                  | None                                     |
	| LC    | dynamiclights_entityclasses                  | 1.0.1             | DynamicLights-1.12.2.jar                  | None                                     |
	| LC    | dynamiclights_mobequipment                   | 1.1.0             | DynamicLights-1.12.2.jar                  | None                                     |
	| LC    | dynamiclights_flamearrows                    | 1.0.1             | DynamicLights-1.12.2.jar                  | None                                     |
	| LC    | dynamiclights_floodlights                    | 1.0.3             | DynamicLights-1.12.2.jar                  | None                                     |
	| LC    | dynamiclights_otherplayers                   | 1.0.9             | DynamicLights-1.12.2.jar                  | None                                     |
	| LC    | dynamiclights_theplayer                      | 1.1.3             | DynamicLights-1.12.2.jar                  | None                                     |
	| LC    | mantle                                       | 1.12-1.3.3.49     | Mantle-1.12-1.3.3.49.jar                  | None                                     |
	| LC    | jei                                          | 4.15.0.283        | jei_1.12.2-4.15.0.283.jar                 | None                                     |
	| LC    | tconstruct                                   | 1.12.2-2.12.0.135 | TConstruct-1.12.2-2.12.0.135.jar          | None                                     |
	| LC    | galacticraftcore                             | 4.0.2.211         | GalacticraftCore-1.12.2-4.0.2.211.jar     | None                                     |
	| LC    | galacticraftplanets                          | 4.0.2.211         | Galacticraft-Planets-1.12.2-4.0.2.211.jar | None                                     |
	| LC    | waila                                        | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar               | None                                     |
	| LC    | mekanism                                     | 1.12.2-9.4.13.349 | Mekanism-1.12.2-9.4.13.349.jar            | None                                     |
	| LC    | mekanismgenerators                           | 9.4.11            | MekanismGenerators-1.12.2-9.4.13.349.jar  | None                                     |
	| LC    | mekanismtools                                | 9.4.11            | MekanismTools-1.12.2-9.4.13.349.jar       | None                                     |
	| LC    | minions                                      | 2.0.3             | Minions-1.12.2.jar                        | None                                     |
	| LC    | mystcraft                                    | 0.13.4.03         | mystcraft-1.12.2-0.13.4.03.jar            | None                                     |
	| LC    | projecte                                     | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar               | None                                     |
	| LC    | torohealthmod                                | 1.12.2-11         | torohealth-1.12.2-11.jar                  | None                                     |
	| LC    | wawla                                        | 2.6.275           | Wawla-1.12.2-2.6.275.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | xaerominimap                                 | 1.17.3            | Xaeros-Minimap-Fair-Play-1.12.2.jar       | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.211.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
MovingWorldCore (MovingWorld-Mod-1.12.jar)
  
DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.5063' Renderer: 'Intel(R) HD Graphics 5500'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

**Comment by AlexIIL** [comment]
Unfortunately UniversalElectricity is incompatible with newer versions of buildcraft - so you''ll need to remove `universal-electricity-4.0.0.1-dev.jar`.
