### ISSUE TITLE
Refinery uncraftable

### ISSUE THREAD

**Issue by lChaoticl** [BuildCraft/BuildCraft#4585]
![Unbenannt](https://user-images.githubusercontent.com/56038642/87862746-b38c3400-c953-11ea-8316-e450858fe0b9.png)

I am currently using buildcraft 7.1.23, buildcraftadditions-1.7.10-2.2.5 and buildcraft-compat-7.1.5.
Minecraft Version is 1.7.10 and Forge 10.13.3.1355

I dont know exactly why i cant craft a refinery but I can give it to me with /give or in gamemode. 
But it would be awesome to craft it cause I am playing on a server and we don´t want to use gamemode :/

**Comment by LuigiHutch** [comment]
BCA removes the recipe in favour of its multiblock refinery system. It can be re-enabled in the config iirc

**Comment by lChaoticl** [comment]
I appreciate your really quick answer. Everything works as it shoud. Thank you
