### ISSUE TITLE
[1.12.2] Crash with Buildcraft Builders

### ISSUE THREAD

**Issue by Secretname2009** [BuildCraft/BuildCraft#4586]
Description:
This crash log appears sometimes after a mod crashes and VanillaFix shuts down the world and returns to main menu. After encountering this you cannot load any world as this crash happends every time after and the only fix is to restart Minecraft.
I can provide log and other details.
Crash Report or Log:
[crash-2020-07-19_14.39.28-server.txt](https://github.com/BuildCraft/BuildCraft/files/4943707/crash-2020-07-19_14.39.28-server.txt)

**Comment by AlexIIL** [comment]
> This crash log appears sometimes after a mod crashes and VanillaFix shuts down the world and returns to main menu

When minecraft crashes it's possible for the entire game's state to be corrupted - so I can't help you here. Instead you'd need to look into the cause of the original crash, or report the issue to VanillaFix, not us.

**Comment by Secretname2009** [comment]
Alright, thanks for letting me know.
