### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by ReverseRozmosis** [BuildCraft/BuildCraft#4603]
Hello heres my crash report and a little blurb i get from the minecraft launcher. 
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Lib (buildcraftlib)
How do i fix this?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  HCASM (HammerCore-1.12.2-2.0.5.6.jar)
  McLib core mod (mclib-1.0.3-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 10/9/20 9:22 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Lib (buildcraftlib)
Caused by: java.lang.Error: Bad class buildcraft.api.core.BCLog loaded from net.minecraft.launchwrapper.LaunchClassLoader@3d82c5f3 domain: ProtectionDomain  (jar:file:/C:/Users/Rozzy/AppData/Roaming/.minecraft/versions/1.12.2-forge1.12.2-14.23.5.2846/mods/universal-electricity-4.0.0.1-dev.jar!/buildcraft/api/core/BCLog.class <no signer certificates>)
 net.minecraft.launchwrapper.LaunchClassLoader@3d82c5f3
 <no principals>
 java.security.Permissions@38cc9e2d (
 ("java.io.FilePermission" "\C:\Users\Rozzy\AppData\Roaming\.minecraft\versions\1.12.2-forge1.12.2-14.23.5.2846\mods\universal-electricity-4.0.0.1-dev.jar" "read")
 ("java.lang.RuntimePermission" "stopThread")
 ("java.util.PropertyPermission" "java.specification.version" "read")
 ("java.util.PropertyPermission" "java.version" "read")
 ("java.util.PropertyPermission" "os.arch" "read")
 ("java.util.PropertyPermission" "java.specification.vendor" "read")
 ("java.util.PropertyPermission" "java.vm.specification.name" "read")
 ("java.util.PropertyPermission" "java.vm.vendor" "read")
 ("java.util.PropertyPermission" "path.separator" "read")
 ("java.util.PropertyPermission" "os.version" "read")
 ("java.util.PropertyPermission" "file.separator" "read")
 ("java.util.PropertyPermission" "line.separator" "read")
 ("java.util.PropertyPermission" "java.vm.specification.vendor" "read")
 ("java.util.PropertyPermission" "java.specification.name" "read")
 ("java.util.PropertyPermission" "java.vendor.url" "read")
 ("java.util.PropertyPermission" "java.vendor" "read")
 ("java.util.PropertyPermission" "java.vm.version" "read")
 ("java.util.PropertyPermission" "java.vm.name" "read")
 ("java.util.PropertyPermission" "java.vm.specification.version" "read")
 ("java.util.PropertyPermission" "os.name" "read")
 ("java.util.PropertyPermission" "java.class.version" "read")
 ("java.net.SocketPermission" "localhost:0" "listen,resolve")
)

	at buildcraft.lib.BCLib.throwBadClass(BCLib.java:123)
	at buildcraft.lib.BCLib.preInit(BCLib.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: logger
	at buildcraft.lib.BCLib.preInit(BCLib.java:72)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 384401584 bytes (366 MB) / 1073741824 bytes (1024 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2846 Optifine OptiFine_1.12.2_HD_U_E3 101 mods loaded, 100 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version                  | Source                                           | Signature                                |
	|:----- |:------------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft                 | 1.12.2                   | minecraft.jar                                    | None                                     |
	| LCH   | mcp                       | 9.42                     | minecraft.jar                                    | None                                     |
	| LCH   | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2846.jar                    | None                                     |
	| LCH   | forge                     | 14.23.5.2846             | forge-1.12.2-14.23.5.2846.jar                    | None                                     |
	| LCH   | openmodscore              | 0.12.2                   | minecraft.jar                                    | None                                     |
	| LCH   | concheckrmd               | 1.8.1                    | Modpack+Configuration+Checker-1.12.2-v1.8.1.jar  | None                                     |
	| LCH   | actuallyadditions         | 1.12.2-r146              | ActuallyAdditions-1.12.2-r146.jar                | None                                     |
	| LCH   | aether_legacy             | 1.4.4                    | aether_legacy-1.12.2-v1.4.4.jar                  | None                                     |
	| LCH   | aether_legacy_addon       | 1.12.2-v1.2.3            | aether_continuation-1.12.2-v1.2.3.jar            | None                                     |
	| LCH   | baubles                   | 1.5.2                    | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCH   | bibliocraft               | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                | None                                     |
	| LCH   | biomesoplenty             | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar    | None                                     |
	| LCE   | buildcraftlib             | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                     | None                                     |
	| LC    | buildcraftcore            | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                     | None                                     |
	| LC    | buildcraftbuilders        | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                     | None                                     |
	| LC    | buildcrafttransport       | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                     | None                                     |
	| LC    | buildcraftsilicon         | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                     | None                                     |
	| LC    | ic2                       | 2.8.188-ex112            | industrialcraft-2-2.8.188-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| LC    | buildcraftcompat          | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                     | None                                     |
	| LC    | buildcraftenergy          | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                     | None                                     |
	| LC    | buildcraftfactory         | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                     | None                                     |
	| LC    | buildcraftrobotics        | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                     | None                                     |
	| LC    | codechickenlib            | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | chickenchunks             | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux              | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore                  | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar           | None                                     |
	| LC    | cofhworld                 | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | controlling               | 3.0.7                    | Controlling-3.0.7.jar                            | None                                     |
	| LC    | cookingforblockheads      | 6.4.69                   | CookingForBlockheads_1.12.2-6.4.69.jar           | None                                     |
	| LC    | elevatorid                | 1.3.12                   | ElevatorMod-1.12.2-1.3.12.jar                    | None                                     |
	| LC    | endercrop                 | 1.12.2-1.6.0             | endercrop-1.12.2-1.6.0.jar                       | None                                     |
	| LC    | enderstorage              | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | energyconverters          | 1.3.6.24                 | energyconverters_1.12.2-1.3.6.24.jar             | None                                     |
	| LC    | hammercore                | 2.0.5.6                  | HammerCore-1.12.2-2.0.5.6.jar                    | None                                     |
	| LC    | jei                       | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                        | None                                     |
	| LC    | projecte                  | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                      | None                                     |
	| LC    | expequiv                  | 13r                      | ExpandedEquivalence-1.12.2-13r.jar               | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LC    | mantle                    | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                         | None                                     |
	| LC    | thaumcraft                | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                 | None                                     |
	| LC    | twilightforest            | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar    | None                                     |
	| LC    | tconstruct                | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                 | None                                     |
	| LC    | extrautils2               | 1.0                      | Extra-Utilities-Mod-1.12.2.jar                   | None                                     |
	| LC    | forgemultipartcbe         | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | microblockcbe             | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar     | None                                     |
	| LC    | minecraftmultipartcbe     | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar     | None                                     |
	| LC    | grapplemod                | 1.12.2-v11.1             | grapplemod-v11.1-1.12.2.jar                      | None                                     |
	| LC    | gravestone                | 1.10.3                   | gravestone-1.10.3.jar                            | None                                     |
	| LC    | ichunutil                 | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | hats                      | 7.1.0                    | Hats-1.12.2-7.1.0.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | waila                     | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LC    | mts                       | 15.7.0                   | Immersive+Vehicles-1.12.2-15.7.0.jar             | None                                     |
	| LC    | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | ironbackpacks             | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                | None                                     |
	| LC    | ironchest                 | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                  | None                                     |
	| LC    | journeymap                | 1.12.2-5.5.5             | journeymap-1.12.2-5.5.5.jar                      | None                                     |
	| LC    | jrftl                     | 1.1                      | JRFTL[1.12.2]-1.1.jar                            | None                                     |
	| LC    | mclib                     | 1.0.3                    | mclib-1.0.3-1.12.2.jar                           | None                                     |
	| LC    | metamorph                 | 1.1.9                    | metamorph-1.1.9-1.12.2.jar                       | None                                     |
	| LC    | millenaire                | Millénaire 8.0.0         | millenaire-1.12.2-8.0.0.jar                      | None                                     |
	| LC    | modnametooltip            | 1.10.1                   | modnametooltip_1.12.2-1.10.1.jar                 | None                                     |
	| LC    | numina                    | 1.12.2-1.0.38            | Numina-1.12.2-1.0.38.jar                         | None                                     |
	| LC    | railcraft                 | 12.0.0                   | railcraft-12.0.0.jar                             | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LC    | powersuits                | 1.12.2-1.0.46            | ModularPowersuits-1.12.2-1.0.46.jar              | None                                     |
	| LC    | moreoverlays              | 1.15.1                   | moreoverlays-1.15.1-mc1.12.2.jar                 | None                                     |
	| LC    | mrtjpcore                 | 2.1.4.43                 | MrTJPCore-1.12.2-2.1.4.43-universal.jar          | None                                     |
	| LC    | mtsofficialpack           | 12.0.0                   | MTS_Official_Pack_V12.jar                        | None                                     |
	| LC    | mystcraft                 | 0.13.7.04                | mystcraft-1.12.2-0.13.7.04.jar                   | None                                     |
	| LC    | natura                    | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                       | None                                     |
	| LC    | nei                       | 2.4.3                    | NotEnoughItems-1.12.2-2.4.3.245-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | openmods                  | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                    | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LC    | openblocks                | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LC    | harvestcraft              | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zb.jar                  | None                                     |
	| LC    | portalgun                 | 7.1.0                    | PortalGun-1.12.2-7.1.0.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | projectred-core           | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-Base.jar             | None                                     |
	| LC    | projectred-compat         | 1.0                      | ProjectRed-1.12.2-4.9.4.120-compat.jar           | None                                     |
	| LC    | projectred-integration    | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-integration.jar      | None                                     |
	| LC    | projectred-transmission   | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-integration.jar      | None                                     |
	| LC    | projectred-fabrication    | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-fabrication.jar      | None                                     |
	| LC    | projectred-illumination   | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-lighting.jar         | None                                     |
	| LC    | projectred-expansion      | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar       | None                                     |
	| LC    | projectred-relocation     | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar       | None                                     |
	| LC    | projectred-transportation | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar       | None                                     |
	| LC    | projectred-exploration    | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-world.jar            | None                                     |
	| LC    | quickleafdecay            | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar                | None                                     |
	| LC    | recall                    | 1.0                      | recall-1.0.jar                                   | None                                     |
	| LC    | snad                      | 1.12.1-1.7.09.16a        | Snad-1.12.1-1.7.09.16a.jar                       | None                                     |
	| LC    | tc6aspects4jei            | 0.0.2a                   | tc6aspects4jei-0.0.2a.jar                        | None                                     |
	| LC    | thaumicequivalence        | 1.12.2-1.0.5             | ThaumicEquivalence-1.12.2-1.0.5.jar              | None                                     |
	| LC    | thaumicjei                | 1.6.0                    | ThaumicJEI-1.12.2-1.6.0-27.jar                   | None                                     |
	| LC    | thaumicperiphery          | 0.3.1                    | thaumicperiphery-0.3.1.jar                       | None                                     |
	| LC    | thaumictinkerer           | 1.12.2-5.0-353c71c       | thaumictinkerer-1.12.2-5.0-353c71c.jar           | None                                     |
	| LC    | thermalfoundation         | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalexpansion          | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalcultivation        | 0.3.3                    | ThermalCultivation-1.12.2-0.3.3.12-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermaldynamics           | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalinnovation         | 0.3.3                    | ThermalInnovation-1.12.2-0.3.3.12-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermaltinkering          | 1.0                      | ThermalTinkering-1.12.2-2.0.1.jar                | None                                     |
	| LC    | wanionlib                 | 1.12.2-2.4               | WanionLib-1.12.2-2.4.jar                         | None                                     |
	| LC    | llibrary                  | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | unidict                   | 1.12.2-2.9.3             | UniDict-1.12.2-2.9.3.jar                         | None                                     |
	| UD    | mclib_core                | 1.0.3                    | minecraft.jar                                    | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
HCASM (HammerCore-1.12.2-2.0.5.6.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
McLib core mod (mclib-1.0.3-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.55' Renderer: 'GeForce RTX 2080 SUPER/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	HammerCore Debug Information: 
Dependent Mods:
    -Expanded Equivalence (expequiv) @13r

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 19
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.1.04.1.zip
	OpenGlVersion: 4.6.0 NVIDIA 456.55
	OpenGlRenderer: GeForce RTX 2080 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by AlexIIL** [comment]
Unfortunately `universal-electricity` is for minecraft 1.7.10, and not 1.12.2 - so you'll need to remove it to play. (Normally it just wouldn't be loaded, but it includes old 1.7.10 buildcraft code which causes the crash).

**Comment by ReverseRozmosis** [comment]
Okie dokie thank you!

**Comment by ReverseRozmosis** [comment]
would you by any chance know another mod that achieves the same things as universal electricity but for 1.12.2?

**Comment by AlexIIL** [comment]
No, sorry. (Although I don't play with other mods too often, so I'm not that familiar with all of the options).

**Comment by AlexIIL** [comment]
Closing as unfortunately I don't think we can help any further.

**Comment by gatoborrachon** [comment]
> would you by any chance know another mod that achieves the same things as universal electricity but for 1.12.2?

hey, there is a mod for almost everything you can imagine (in versions like 1.7 or 1.12 (right now 1.12 is the best option))
https://www.curseforge.com/minecraft/mc-mods/energy-converters
