### ISSUE TITLE
[1.12.2] "Ticking block entity"

### ISSUE THREAD

**Issue by MoodyBlueSkies** [BuildCraft/BuildCraft#4629]
I used VanillaFix to make it easier for me to get an understandable crash report. I will be redacting my name in the crash report.

So basically, I used a lot of engines and the quarry is pretty fast with 4 or 6 engines. After dealing with an entity ticking crash report, this happened shortly after. Someone explain to me about this crash report and tell me how to fix it if possible. Worst case scenario, I have to delete the mod entirely
[crash-2021-01-16_19.18.28-server.txt](https://github.com/BuildCraft/BuildCraft/files/5824729/crash-2021-01-16_19.18.28-server.txt)

**Comment by AlexIIL** [comment]
`luckyores` doesn't seem to support "fake" players, which are used by the quarry to break blocks. I'm not sure how to fix this, but you'd either need to try updating lucky blocks, or contact the lucky blocks dev to try and see if they can fix this, or remove it. (From a little googling this seems to be the same issue as here: https://www.curseforge.com/minecraft/mc-mods/lucky-ores/issues/1)
