### ISSUE TITLE
(Suggestion) Generation Compatibility with Cubic Chunks.

### ISSUE THREAD

**Issue by border999** [BuildCraft/BuildCraft#4634]
I noticed that buildcraft's oil and water springs don't really spawn, at least in the overworld too much, with the cubic chunks modded world type selected.

I'd recommend maybe taking a look at Cubic Chunks to see how much you want to add integration for it, seeing as it alters how the world in effectively set up. This may also prevent issues with items like the quarry when it does deeper than block 0.

It's also possible to go to other dimensions to find oil well if need be. Aromacore's mining dimension for example.

I love Cubic Chunks and hope to get as many of the mod authors who I use mods from to have it in mind when they work on their mods.

**Comment by AlexIIL** [comment]
Making oil generation work better with cubic chunks is a great idea, but I'm unlikely to ever implement in 1.12.2, sorry.

> This may also prevent issues with items like the quarry when it does deeper than block 0.

As far as I'm aware the quarry should already work fine with cubic chunks - see #3609 and #3610. Or has something broken since then?

**Comment by border999** [comment]
Just trying to cover all my bases when it comes to issues that might have popped up between these two mods.

**Comment by Barteks2x** [comment]
On 1.12.2 it would need effectively a completely separate implementation of the BuildCraft worldgen code, so I agree it's unlikely to be something anyone would do (and also why I never actually expected any mod to implement worldgen compatibility on 1.12.2). This should be much more plausible to implement in 1.17+ (after CC is updated).

**Comment by border999** [comment]
Then I await 1.17
