### ISSUE TITLE
Still working for update?

### ISSUE THREAD

**Issue by ErythroCraft** [BuildCraft/BuildCraft#4638]
Hi.

I was wondering that a mod like so often, there is no updates commimg for the newest version of Forge.

Are you still working?
Or you can not doing updates?

What's happen?

**Comment by ProjectET** [comment]
Buildcraft is being ported to fabric 1.16.x. forge 1.12.2 is only receiving bug fixes, there are no plans to port Buildcraft to forge 1.16 for the foreseeable future

**Comment by ErythroCraft** [comment]
Ok thanks

**Comment by grantlmul** [comment]
@ProjectET Where can I find the development of this Fabric port?

**Comment by ProjectET** [comment]
It is being worked on privately by AlexILL
