### ISSUE TITLE
Buildcraft 7.99.24.8 doesn't exist on my Server

### ISSUE THREAD

**Issue by Cheeeeeeeeese** [BuildCraft/BuildCraft#4639]
I downloaded Buildcraft 7.99.24.8 from Curseforge and Forge 14.23.5.2845, both versions are also saved on the server.
In singleplayer the mod works without any problems but when I join the server and try to look up the recipes in jei they don't exist. 
(also the recipes don't work when i try to craft something)

**Comment by AlexIIL** [comment]
It sounds like the server isn't loading buildcraft properly. Are you sure that the server is running the forge server jar file and not vanilla?

**Comment by Cheeeeeeeeese** [comment]
Where can I find the forge server jar?

**Comment by Cheeeeeeeeese** [comment]
Never mind my friend is stupid and didn't put the mod in the server.
