### ISSUE TITLE
[1.7.10 - 7.1.23] Permissions for fake user

### ISSUE THREAD

**Issue by Apvaris** [BuildCraft/BuildCraft#4641]
The issue is that I can not configure permissions to allow modify world.

I tried to remove PermissionsEx plugin and check if mod`s user without restrictions can break blocks (it works).
So, the question is: What I should allow to [buildCraft] user to make it work?

permissions.yml

_groups:
  BuildCraft:
    default: false
    permissions:
     - modifyworld.*
schema-version: 1
users:
  '[buildCraft]':
    group:
    - BuildCraft_

**Comment by LuigiHutch** [comment]
Use `/buildcraft op` or you can find the specific UUIDs to whitelist in the Server startup log

**Comment by Apvaris** [comment]
> Use `/buildcraft op` or you can find the specific UUIDs to whitelist in the Server startup log

thank you.
