### ISSUE TITLE
Compatability issue between BC Silicon and SCP Lockdown

### ISSUE THREAD

**Issue by RoSirius** [BuildCraft/BuildCraft#4643]
- Forge Version: 1.12.2 (14.23.5.2855), Server
- BuildCraft Version: 7.99.24.8
- Any additonal mods: SCP Lockdown 2.4.0

1. Have a server with BuildCraft 7.99.24.8, all or just including the silicon module, and SCP Lockdown 2.4.0 
2. Attempt to start the server
3. Expect an error and consequent crash due to a NoClassDefFoundError error.
4. You'll notice the error involves an issue between BC Silicon and SCP Lockdown where BC Silicon is attempting to create a facade of a SCPL block.
[The error I received in a text file](https://github.com/BuildCraft/BuildCraft/files/6460995/error.txt)

**Comment by AlexIIL** [comment]
It looks like the SCP mod references some client-side code in `Block.getRenderType()` (the method is available on both the client and server, but only used to spawn running particles normally on the server, despite it's name).

Can you open an issue on their end? While I can *technically* work around this on buildcraft's side, I'd rather not have to special case certain blocks more than I have too - especially as SCP seems to still be being worked on?

**Comment by RoSirius** [comment]
Will do.

**Comment by AlexIIL** [comment]
Thanks :)

**Comment by AlexIIL** [comment]
Awesome, thanks!
