### ISSUE TITLE
Project Ozone 3 Game Crash

### ISSUE THREAD

**Issue by xPatryk1PL** [BuildCraft/BuildCraft#4672]
Crash Log:
https://gist.github.com/xPatryk1PL/1ae984ac96cbaa525372d29ef9f74ebd

When i try go to end, eat "ender apple" game crashing
also "end cake" is bugged and not working, (when i place end cake 0/6 bites).

**Comment by AlexIIL** [comment]
You seem to have reported this to the wrong place - this is for issues with the `BuildCraft` mod, not the `Project Ozone 3` modpack (which doesn't include BuildCraft).

Instead you should open an issue here: https://github.com/Cazadorsniper/PO3/issues
