### ISSUE TITLE
Wooden transport pipes can be connected to engines for other mod

### ISSUE THREAD

**Issue by night0v0** [BuildCraft/BuildCraft#4680]
Forge Version:14.23.4.2718
BuildCraft Version :7.99.24.8

**Comment by night0v0** [comment]
Had the same problem with obsidian transport pipes

**Comment by SandGrainOne** [comment]
Do you mean "cannot"? BuildCraft produce a power that is different from what most other mods are using.

**Comment by night0v0** [comment]
Wooden pipes will be connected to the forestry engine

**Comment by night0v0** [comment]
This doesn't seem to be a BuildCraft issue
