### ISSUE TITLE
Buildcraft silicon module crash

### ISSUE THREAD

**Issue by AgentDelta** [BuildCraft/BuildCraft#4687]
We recently added buildcraft to a server me and some of my friends have. Afaik I'm the only one whose client crashes when minecraft is starting up, and if I'm reading the log correctly, the silicon module is causing this. I've tried downloading the modules individually and the same happens, though when I removed silicon and launched with all the other modules I had no problem.

Crash log:
[https://pastebin.com/QGKz4aRs](url)

**Comment by AlexIIL** [comment]
AFAIK this is a bug with the impact client - you'll need to choose between it and buildcraft.

**Comment by AgentDelta** [comment]
Removed impact and minecraft is working perfectly, thank you
