### ISSUE TITLE
buildcraft 1.5.2 curseforge mac

### ISSUE THREAD

**Issue by plakiiskute** [BuildCraft/BuildCraft#4698]
forge ver 7.8.1.738

starting the modpack only with the buildcraft mod
when pressing the PLAY button it gives me this error

sorry,unable to start minecraft

no logs

and no idea what could be causing this

**Comment by asiekierka** [comment]
Well, it is an old version of Minecraft, they're more finicky to get going than the new ones. The best version to play BuildCraft on right now, if you're making a new modpack, is probably 1.7.10, 1.8.9 or 1.12.2.

You could try an alternate launcher, such as Prism Launcher - these tend to have better compatibility with such older versions; but it might just be that a version of Minecraft from 2012 won't run well on macOS from 2023. I don't own a Mac, so I can't help further, especially not without logs.

**Comment by plakiiskute** [comment]
thanks
