### ISSUE TITLE
3.6.0 removes all Dungeons

### ISSUE THREAD

**Issue by BoneDisturbed** [BuildCraft/BuildCraft#908]
After updating to the newest build there are no longer any dungeons to be found anywhere, loaded up a seed were i knew were there where a few dungeons, but they are all gone.

**Comment by Breadabix** [comment]
So im using buildcraft 3.7.2, and want to try and find the seed of a world from youtube, but buildcraft changes where dungeons spawn. Do either of you know how this is done so I can try and reverse engineer it into a tool that uses dungeons to find seeds?
